### ISSUE TITLE
Content-type of uploaded file is incorrect

### ISSUE THREAD

**Issue by PaulTaykalo** [aws-amplify/aws-sdk-ios#10]
Let's say I have this request.

```
AWSS3TransferManagerUploadRequest *uploadRequest = [AWSS3TransferManagerUploadRequest new];
uploadRequest.ACL = AWSS3ObjectCannedACLPublicRead;
uploadRequest.bucket = bucket;
uploadRequest.key = key;
uploadRequest.body = fileURL;
uploadRequest.contentLength = [NSNumber numberWithUnsignedLongLong:(unsigned long long int) fileSize];
uploadRequest.contentType = @"video/mp4";
```

When uploading is done, I will be able to access to the file, but it's content-type will be "from default cofiguration"

When I checking this issue, the real headers those are send here will be like this

```
(lldb) po [mutableRequest allHTTPHeaderFields]
{
    Authorization = "AWS4-HMAC-SHA256 Credential=.....";
    "Content-Type" = "text/xml; charset=utf-8";
    Host = "s3-us-west-2.amazonaws.com";
    "Transfer-Encoding" = Chunked;
    "User-Agent" = "aws-sdk-iOS/2.0.0 iPhone-OS/8.0 en_UA";
    "X-Amz-Date" = 20140626T132939Z;
    "x-amz-acl" = "public-read";
    "x-amz-content-sha256" = "STREAMING-AWS4-HMAC-SHA256-PAYLOAD";
    "x-amz-decoded-content-length" = 3692247;
}
```

In result, when I accessing the file to by the direct link, I will see "Content-Type" = "text/xml; charset=utf-8";

**Comment by soxjke** [comment]
Still actual in latest version.

**Comment by yosuke-matsuda** [comment]
Can you provide a code snippet to reproduce the issue? Please [enable verbose logging](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html#logging) and share it as well. (Please remove any credentials in the logging.) Thanks.
