### ISSUE TITLE
Explicit Sign up / Sign in causes APIClient to misfire

### ISSUE THREAD

**Issue by Dellybro** [aws-amplify/aws-sdk-ios#1019]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

AWSMobileHub CogntioIdentityPool stack

* In what version of SDK are you facing the problem?

2.6.22

* Is the issue limited to Simulators / Actual Devices?

No

* Can your problem be resolved if you bump to a higher version of SDK?

No, I just tried that

* Is this problem related to specific iOS version?

I do not believe so.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I am using Explicity Sign in / SIgn up on my app which means that I do not implement "startCustomAuthenticator" nor do i implement "startPasswordAuthenticator". Once I have successfully logged in the user all "getSession" methods will successfully be called because I have their correct session.

My problem is that, on a RARE occasion, when i use the APIClient I downloaded from mobileHub, I will get the error "Either startCustomAuthentication or startPasswordAuthentication must be implemented..." 

During my signup process I make an API Request to my API Gateway for our own custom phone authenticator, and this is when I am encountering the error I have described above.

Why is this happening? And how am i to fix this issue

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by sunchunqiang** [comment]
Hello @Dellybro 

What do you mean for "on a RARE occasion"? Do you mean the error is not hit for a same code? 

Can you provide some code snippet you are using, so that we can try to reproduce the issue?

**Comment by Dellybro** [comment]
```
+(void)sendRequestWithType:(NSString *)method route:(NSString *)route queryParams:(NSDictionary*)queryParams headerParams:(NSDictionary*)headerParams body:(NSDictionary*)httpBody completionHandler:(void (^)(NSInteger, NSDictionary *))completionHandler{
    
    /* Check reachability */
    if(![ReachabilityManager isReachable]){
        completionHandler(502, @{@"message": @"Zinkn has detected network is unreachable."});
        return;
    }
    
    if(!headerParams){
        headerParams = @{@"Content-Type": @"application/json"};
    }
    AWSAPIGatewayRequest *apiRequest = [[AWSAPIGatewayRequest alloc] initWithHTTPMethod:method URLString:route queryParameters:queryParams headerParameters:headerParams HTTPBody:httpBody];
    AWSServiceConfiguration *serviceConfig = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSWest2 credentialsProvider:[[AWSMobileClient sharedInstance]getCredentialsProvider]];
    
    
    [AWSAPI_9D9C5LJ1F2_CloudZinknApiClient registerClientWithConfiguration:serviceConfig forKey:CloudLogicAPIKey];
    AWSAPI_9D9C5LJ1F2_CloudZinknApiClient *client = [AWSAPI_9D9C5LJ1F2_CloudZinknApiClient defaultClient];


    [[client invoke:apiRequest] continueWithBlock:^id _Nullable(AWSTask<AWSAPIGatewayResponse *> * _Nonnull t) {
        if(t.error){
            NSLog(@"%@", t.error.userInfo);
            /* Error occured */
            completionHandler(t.result.statusCode, @{@"message": [t.error.userInfo objectForKey:NSLocalizedDescriptionKey]});
            return nil;
        }
        
        NSError *jsonError;
        NSMutableDictionary *json = [NSJSONSerialization JSONObjectWithData:[[t result]responseData] options:NSJSONReadingMutableContainers error:&jsonError];

        completionHandler(t.result.statusCode, json);

        return nil;
    }];
}
```

Ye the error is not hit for the same code.

It's like first install on a phone, I get the error that I need some sort of, "Either startCustomAuthentication or startPasswordAuthentication must be implemented...", and this is because during the signup process we send a network request using the APIClient without a logged in user, but the route isn't protected etc etc.

The error ONLY goes away after i successfully log into a user account. Once i log out of the user account and go through the signup process again i get no alerts about needing startCustomauthentication or startPasswordAuthentication

**Comment by desokroshan** [comment]
> How would i use a different credentials provider for un-authenticated calls? I only have one credentials provider.

You can create two instances of AWSMobileClient, one for authenticated calls and the other for unauthenticated calls. 

> Also, so what you are saying is that on app launch i should create only one client. I shouldn't be recreating the client every time i run a network call?

Yes, reuse the AWSMobileClient instances instead of recreating the client for each network call.

**Comment by Dellybro** [comment]
Hello desokroshan,

So are you suggesting I set a nil parameter for the credentials provider in the follow code?

    AWSServiceConfiguration *serviceConfig = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSWest2 credentialsProvider:nil];
    
    [AWSAPI_9D9C5LJ1F2_CloudApiClient registerClientWithConfiguration:serviceConfig forKey:CloudLogicAPIKey];
    unauthenticatedClient = [AWSAPI_9D9C5LJ1F2_CloudApiClient defaultClient];

**Comment by rohandubal** [comment]
Hello @Dellybro 

There is a difference between un-authenticated and open API access. My understanding is that you want to use un-authenticated access. Setting it to nil won't allow un-authenticated access.

To get un-authenticated access using un-auth credentials provider, you should use the following code:

```objective-c

AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:CognitoRegionType
                                                                                                identityPoolId:CognitoIdentityPoolId];
AWSServiceConfiguration *serviceConfig = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSWest2 credentialsProvider:credentialsProvider];

[AWSAPI_9D9C5LJ1F2_CloudApiClient registerClientWithConfiguration:serviceConfig forKey:CloudLogicAPIKey];
unauthenticatedClient = [AWSAPI_9D9C5LJ1F2_CloudApiClient clientForKey:CloudLogicAPIKey];
```

Thanks,
Rohan

**Comment by Dellybro** [comment]
Hello Rohan,

I'm not exactly sure how this creates and unauthenticated client. Currently setting nil as credentials provider seems to be working, I've actually created 2 CloudAPIClients and set one as unauthenticated by feeding it a nil credentials provider.

Is there any way we can get in touch? I have the premium package for AWS.

Thanks,
Travis

**Comment by rohandubal** [comment]
Hey @Dellybro 

We can setup a meeting if required. But I think I understand your case better now. What you have is an open API client (not un-authenticated) which you are accessing. For doing that, the `nil` credentials provider is enough and you have the correct code.

Thanks,
Rohan

**Comment by Dellybro** [comment]
@rohandubal 

Setting the credentials provider to nil and obtaining it using default client as so does not work, and it actually provides only SOME users with this error

![image from ios](https://user-images.githubusercontent.com/10732096/47933298-7935e700-de91-11e8-86f0-ce72f583dbe6.jpg)



when i attempt to use clientForKey:cloudLogicKey I then get this error.
![Uploading Screen Shot 2018-11-02 at 11.17.23 AM.png…]()


So i'm not really sure what to do here. I need to be able to make API calls to routes that are not blocked by the client.

**Comment by fyredave** [comment]
Hi, I'm a fellow developer here with Dellybro. There seems to be miscommunication. The issue is with an unauthenticated APIGateway client. We aren't using the Mobile Hub user pools, nor Cloud Logic.

**Comment by rohandubal** [comment]
Hello @Dellybro @fyredave 

We recently released an updated version of `AWSMobileClient` in SDK version `2.7.0+`  which offers a declarative API for operations like signUp, signIn and also offers direct token access and auto refresh when required. Could you please update to use AWSMobileClient and see if it resolves your issue? 

You can find the documentation here: https://aws-amplify.github.io/docs/ios/authentication

Thanks,
Rohan
