### ISSUE TITLE
Get claims should have a return type of NSDictionary * AWSCognitoIdentityUser

### ISSUE THREAD

**Issue by chapinmark** [aws-amplify/aws-sdk-ios#1026]
Retrieving claims in swift causes a EXC_BREAKPOINT exception.  The json generated dictionary can have arrays, etc in the values.  Swift crashes because the return type is NSDictionary<NSString *, NSString *>.  Changing the return type to NSDictionary * or NSDictionary <NSSTing *, NSObject *> fixes the problem.

AWSCognitoAuth has this defined as NSDictionary *

https://github.com/aws/aws-sdk-ios/blob/6ab2982040eaca984eab38e311b98c3b9227b773/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L1467

**Comment by kvasukib** [comment]
@chapinmark Sorry for the inconvenience caused. Can you post the exception message and stack trace following the crash?

**Comment by chapinmark** [comment]
I'm new to xcode/ios dev so I hope this is what you are looking for.  If not, let me know.

I had to change the function return type in the AWSCognitoIdentityUser.h as well (but that probably goes without saying ;)

Specifically, I'm trying to find the group a user is assigned to.  The claims "cognito:groups" key returns a json array of groups.  This crashes when bringing it back to swift since it is defined as a dictionary with key and values as strings.
 
Thread 1: EXC_BREAKPOINT (code=1, subcode=0x101a085b0)

po Thread.callStackSymbols
▿ 21 elements
  - 0 : "0   ???                                 0x000000010485c550 0x0 + 4370842960"
  - 1 : "1   ???                                 0x000000010485c624 0x0 + 4370843172"
  - 2 : "2   MyCode                      0x0000000100975bb8 main + 0"
  - 3 : "3   libswiftCore.dylib                  0x00000001017cc4f4 _T0s26_forceBridgeFromObjectiveCxyXl_xmtlF + 332"
  - 4 : "4   libswiftFoundation.dylib            0x0000000101eb3cc8 _T0s10DictionaryV10FoundationE26_forceBridgeFromObjectiveCySo12NSDictionaryC_AByxq_GSgz6resulttFZyyp_ypSpy0F1C8ObjCBoolVGtcfU_ + 336"
  - 5 : "5   libswiftFoundation.dylib            0x0000000101eb3dc4 _T0ypypSpy10ObjectiveC8ObjCBoolVGIgiiy_yXlyXlADIyByyy_TR + 116"
  - 6 : "6   CoreFoundation                      0x000000018416e564 <redacted> + 160"
  - 7 : "7   libswiftFoundation.dylib            0x0000000101f4f970 _T0s10DictionaryV10FoundationE26_forceBridgeFromObjectiveCySo12NSDictionaryC_AByxq_GSgz6resulttFZTf4gnn_n + 784"
  - 8 : "8   libswiftFoundation.dylib            0x0000000101eaabf8 _T0s10DictionaryV10FoundationE36_unconditionallyBridgeFromObjectiveCAByxq_GSo12NSDictionaryCSgFZ + 72"
  - 9 : "9   MyCode                      0x000000010095502c _T014MyCode26MyListViewControllerC06configF0yAA11AppDelegateC03appJ0_tFypSgSo7AWSTaskCySo29AWSCognitoIdentityUserSessionCGcfU_yycfU_ + 920"
  - 10 : "10  MyCode                      0x0000000100955f40 _T0Ieg_IeyB_TR + 52"
  - 11 : "11  libdispatch.dylib                   0x00000001021e51dc _dispatch_call_block_and_release + 24"
  - 12 : "12  libdispatch.dylib                   0x00000001021e519c _dispatch_client_callout + 16"
  - 13 : "13  libdispatch.dylib                   0x00000001021e9d2c _dispatch_main_queue_callback_4CF + 1180"
  - 14 : "14  CoreFoundation                      0x00000001841f3070 <redacted> + 12"
  - 15 : "15  CoreFoundation                      0x00000001841f0bc8 <redacted> + 2272"
  - 16 : "16  CoreFoundation                      0x0000000184110da8 CFRunLoopRunSpecific + 552"
  - 17 : "17  GraphicsServices                    0x00000001860f6020 GSEventRunModal + 100"
  - 18 : "18  UIKit                               0x000000018e130758 UIApplicationMain + 236"
  - 19 : "19  MyCode                      0x0000000100975c04 main + 76"
  - 20 : "20  libdyld.dylib                       0x0000000183ba1fc0 <redacted> + 4"

**Comment by rohandubal** [comment]
Hello @chapinmark 

This issue is resolved in SDK version `2.7.1+` 

Please use the `tokenClaims` property to access the claims where you can cast it to appropriate type.

Thanks,
Rohan
