### ISSUE TITLE
iOS AWS v2 S3 Transfer Manager must use specified endpoint

### ISSUE THREAD

**Issue by smartleoyu** [aws-amplify/aws-sdk-ios#103]
I am developing an iOS app using AWS as its backend. Since I expect users to be world wide, I need to switch where the app should download photos in order to increase latency performance. I have created a S3 bucket in EUWest1 and the other in APNorthEast1. As Yosuke said here (https://forums.aws.amazon.com/message.jspa?messageID=586581#586581), you can change the default configuration of AWSServiceManager.defaultServiceManager() from one region to another in order to prevent the error.

But, I still have the same error result even if I followed his tip. Error is:

Error Domain=com.amazonaws.AWSS3ErrorDomain Code=0 "The operation couldn’t be completed. (com.amazonaws.AWSS3ErrorDomain error 0.)" UserInfo=0x14fb7720 {RequestId=D708XXX8E1EDBXXX, Endpoint=bucket-ap-northeast-1.s3-ap-northeast-1.amazonaws.com, Message=The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint., HostId=xxxY31S3yFhpssQe1EsfipWWLw=, Code=PermanentRedirect, Bucket=bucket-ap-northeast-1}

And this is my code:

var credentialsProvider = AWSCognitoCredentialsProvider.credentialsWithRegionType(kCognitoRegionType, accountId: kAWSAccountID, identityPoolId: kCognitoPoolID, unauthRoleArn: kCognitoRoleUnauth, authRoleArn: kCognitoRoleAuth)
var serviceConfiguration = AWSServiceConfiguration(region: AWSRegionType.APNortheast1, credentialsProvider: credentialsProvider)
AWSServiceManager.defaultServiceManager().setDefaultServiceConfiguration(serviceConfiguration)
var transferManager = AWSS3TransferManager.defaultS3TransferManager()
transferManager.download(downloadRequest)

**Comment by faizankhan1909** [comment]
can you share your custom initialization code here?

I am having the same issue. I am trying to run the S3TransferManagerSample by providing my credentials in constants.m

I have tried debugging the code. In "listObjects" call. 

AWSS3 *s3 = [AWSS3 defaultS3];

    AWSS3ListObjectsRequest *listObjectsRequest = [AWSS3ListObjectsRequest new];
    listObjectsRequest.bucket = S3BucketName;
    [[s3 listObjects:listObjectsRequest] continueWithBlock:^id(BFTask *task) {
              .......
              .......
              .......
    }];

I am clearly seeing the configurations set to https://s3-us-west-2.amazonaws.com in s3 object. But i am having this error.

S3TransferManagerSample[5771:188537] listObjects failed: [Error Domain=com.amazonaws.AWSS3ErrorDomain Code=0 "The operation couldn’t be completed. (com.amazonaws.AWSS3ErrorDomain error 0.)" UserInfo=0x7fc1ab82fdf0 {HostId=M8bTRNkXj3vfxw59pdt5eA0Q0EGND4QlcVNkHLZBrxGLYpv4pc7WjzkNh9U/neJxy72+dY/72PE=, Bucket=precept-wine, Endpoint=s3.amazonaws.com, Message=The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint., Code=PermanentRedirect, RequestId=1F39D4FACE874D00}]

I am unable to get how come "s3.amazonaws.com" is shown as the end point in this error where as debugger shows "s3-us-west-2.amazonaws.com" as an end point before making the call?

**Comment by yosuke-matsuda** [comment]
The issue is your bucket is not in US West (Oregon) Region, but you set the default region to US West (Oregon). You need to use the region in which your Amazon S3 bucket is.

**Comment by smartleoyu** [comment]
Hey, I would like to share that part of my codes with you, but I am currently not with my computer that has that project. Anyway, as Yosuke said, you need to explicitly set the region in the serviceConfiguration. Please see here for details: http://stackoverflow.com/questions/27221439/ios-aws-v2-s3-transfer-manager-must-use-specified-endpoint

Hope it helps!

**Comment by faizankhan1909** [comment]
Hi Yosuke and smartleoyu,
   I have just checked my bucket region. And the error is gone but now I am having this error:

   S3TransferManagerSample[1717:48308] listObjects failed: [Error Domain=com.amazonaws.AWSS3ErrorDomain Code=1 "The operation couldn’t be completed. (com.amazonaws.AWSS3ErrorDomain error 1.)" UserInfo=0x7fb71412d300 {HostId=qhjcOyYAPQjHhJIX5REMTN5A48ecxIkHCqt6fFwkQPBff+tKWnML9A4yQobq2C38, Message=Access Denied, Code=AccessDenied, RequestId=B6920900AB17C864}]

can you please guide me through?

**Comment by smartleoyu** [comment]
Hmm.....access denied? I guess this has something to do with your IAM (Identify & Access Management)? Go to IAM from your AWS dashboard and check the Roles. Make sure you have the correct role policy. This is my guessing.

**Comment by faizankhan1909** [comment]
I have created 2 roles one is auth and other is un-auth

here are the inline policies for both roles:

roleARN: Cognito_(projectName)Auth_Role
oneClick_Cognito_(projectName)Auth_Role_1424434616386: {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "mobileanalytics:PutEvents",
        "cognito-sync:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}

policygen-Cognito_(projectName)Auth_Role-201502201739{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1424435859000",
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:ListBucket",
        "s3:PutObject"
      ],
      "Resource": [
        "arn:aws:s3:::(bucket name)/*"
      ]
    }
  ]
}


roleARN: Cognito_(projectName)Unauth_Role:

oneClick_Cognito_(projectName)Unauth_Role_1424434555837:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "mobileanalytics:PutEvents",
        "cognito-sync:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}

policygen-Cognito_(projectName)Unauth_Role-201502201743:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1424436103000",
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:ListBucket",
        "s3:PutObject"
      ],
      "Resource": [
        "arn:aws:s3:::(bucket name)/*"
      ]
    }
  ]
}

**Comment by biogerm** [comment]
@faizankhan1909 

The reason is because your policy has defined s3:ListBucket on the /* level, while it should be granted to the bucket. For example:

`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "xxxxx",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::bucket_itself"
            ]
        }
    ]
}
`

notice that **bucket_itself** is different than **bucket_itself/***

I had a similar problem that I have all permissions granted to the bucket but not the items in it. In this case I can list the bucket but I got "Access Denied" for downloading.
