### ISSUE TITLE
Migrate SDK to Swift

### ISSUE THREAD

**Issue by christiancompton** [aws-amplify/aws-sdk-ios#1030]
* What service are you using?
S3

I'm trying to add object storage to my Swift application running on EC2 https://aws.amazon.com/quickstart/architecture/swift/

This SDK does not work with my server side project.  Are there plans to offer this library in Swift as opposed to Objective-C?

**Comment by christiancompton** [comment]
Any updates @kvasukib?

**Comment by palpatim** [comment]
There are actually two somewhat related requests here:

1. Enable the SDK to run in a server environment
1. Migrate the SDK to Swift

The current SDK is intended for a mobile use case and as such has strong dependencies on mobile frameworks like UIKit. Simply migrating the SDK to Swift, while something we do want to accomplish in the future, would not fulfill that use case.

I'm investigating the ability to enable a server-side SDK in Swift and will post an update once I have more information.

**Comment by palpatim** [comment]
After reviewing with the team, there's not really a good way for the mobile SDK team to make this happen. I've gone ahead and let our internal server product teams know of the community interest in a Swift server-side SDK.

**Comment by palpatim** [comment]
As a followup for folks who are following this, looking for a server-side AWS SDK written in Swift:

You can investigate the [smoke-aws library](https://github.com/amzn/smoke-aws) for your use case. It is a work in progress, and the team is still [working on getting a working S3 client](https://github.com/amzn/smoke-aws/issues/3), but it is in active development.

Hope this helps.
