### ISSUE TITLE
clearAllGlobalSessionAttributes is not clearing a session

### ISSUE THREAD

**Issue by Bhat123** [aws-amplify/aws-sdk-ios#1032]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Amason Lex Mobile SDK - Voice bot integration

* In what version of SDK are you facing the problem?
Latest

* Is the issue limited to Simulators / Actual Devices?
Devices and simulator

* Can your problem be resolved if you bump to a higher version of SDK?
Nope, already using the latest SDK

* Is this problem related to specific iOS version?
nope 

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Cocoapods 

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

My code looks like this. 

        let chatConfig = AWSLexInteractionKitConfig.defaultInteractionKitConfig(withBotName: BotName, botAlias: BotAlias)
        chatConfig.clearAllGlobalSessionAttributes()

Hi Team,
Above is the code i am using to clear of the session of a chat. MY session time is set to 5 in Amazon Lex Service portal.

FRom my mobile app am trying to clear the session everytime i go to chat window or voice window. 

It is not clearing the session. 

How to clear off the session , need help here. 

Regards,
Chandrika

**Comment by rohandubal** [comment]
Hello,

Currently, there is no specific way to explicitly clear a session. Although, you could assign a new userId to start a brand new session.

Thanks,
Rohan

**Comment by Bhat123** [comment]
Thanks a lot Rohan. Can it be implemented in later releases ?

**Comment by palpatim** [comment]
Hi @Bhat123,

Sorry for the delayed response on this--can you explain your use case in a bit more detail? I'm trying to understand the behavior you're trying to achieve that `clearAllGlobalSessionAttributes()` isn't accomplishing. Is it that you are trying to start a new interaction session before the timeout of the previous one has expired?
