### ISSUE TITLE
Add a method to map AWSS3BucketLocationConstraint to AWSRegionType

### ISSUE THREAD

**Issue by simonmaddox** [aws-amplify/aws-sdk-ios#1033]
Right now, I have to write my own massive `switch` statement to convert between these enum values. I can't simply cast between them because they're in different orders, which will give "EU West 1" a different value depending on if its a `AWSRegionType` or a `AWSS3BucketLocationConstraint`.

I'd like a method, provided by Amazon, that converts these for me. Whenever you add a new region, not only do I have to update the SDK I also have to remember to add the new values to my switch statement.

There's also no clear mapping between `AWSS3BucketLocationConstraintEU`, for example, and a `AWSRegionType` - should there be? These can be solved very easily by Amazon providing the method to do this.

**Comment by rohandubal** [comment]
Thanks for reporting this @simonmaddox I will take this as a request to the team. I will update the thread here once we have support for this feature. The constraints are different from the region and agreed that the method will be more useful.

Thanks,
Rohan

**Comment by natanrolnik** [comment]
+1, this is indeed useful.
Also, is there a way to map between a `AWSRegionType` and the actual string identifier for that region?

**Comment by atierian** [comment]
Thanks for opening this feature request. We have no plans to add a new API for mapping between `AWSRegionType` and `AWSS3BucketLocationConstraint` at this time.
