### ISSUE TITLE
How can I get a new idToken with the refreshToken

### ISSUE THREAD

**Issue by nilotic** [aws-amplify/aws-sdk-ios#1034]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
Lastest

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I want to refresh idToken, using the refreshToken

This is my code

    func refresToken() {
        let provider = AWSCognitoIdentityProvider(forKey: CognitoIdentityUserPoolAppClientId)

        guard let request = AWSCognitoIdentityProviderInitiateAuthRequest(), let refreshToken = user?.getSession().result?.refreshToken?.tokenString else { return }
        request.authFlow       = .refreshToken
        request.clientId       = CognitoIdentityUserPoolId
        request.authParameters = ["REFRESH_TOKEN" : refreshToken,
                                  "SECRET_HASH"   : CognitoIdentityUserPoolAppClientId]
        
        provider.initiateAuth(request).continueWith() { response in
            print(response.error.debugDescription)
            print(response.result.debugDescription)
            return nil
        }
    }

  But the completion never called.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
Hello @nilotic 

Could you please elaborate your use-case?

The SDK currently refreshes and gets a valid id token based on the available refresh token. You are not required to do it explicitly. The code can be found here:

https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L187

Thanks,
Rohan

**Comment by nilotic** [comment]
Hi @rohandubal 

I just want to renew the user session after 1 hour (session is expired)

Every time, I refresh user info when the app is resumed.
This is my refresh code.

    func refresh(completion: (() -> Void)? = nil) {
        let user = userPool.currentUser()
        let details = user?.getDetails()
        
        guard (user?.isSignedIn ?? false) == true else {
            completion?()
            return
        }
        
        details?.continueWith { (response) -> Any? in
            guard response.result != nil, self.updateAccessToken() == true, self.requestUserData(completion: completion) == true else {
                self.logOut()
                completion?()
                return nil
            }
            return nil
        }
    }
    

Do I have to do more if I want to refresh the user session (refresh the idToken) ??

**Comment by qaisershehzad** [comment]
Hi @nilotic, please check below code if you are still facing this issue.

You can  use getSession() from AWSCognitoIdentityUser it will handle all for you.
Below is a sample code which is used to getSession of current AWSCognitoIdentityUser

  self.user?.getSession().continueOnSuccessWith(block: { [weak self] (task:AWSTask<AWSCognitoIdentityUserSession>) -> Any?    in
            
            guard let strongSelf = self else { return nil }
            if let error = task.error as? NSError {
                print("Error: \(error)")
                return nil
            }else{
                print("ID Token: \(task.result?.idToken?.tokenString)")
                print("Refresh Token: \(task.result?.refreshToken?.tokenString)")                
            }
            return nil
        })

**Comment by JIBINVARGHESE912** [comment]
Hi,
Sometimes when we invoke getSession() in AWSCognito, getSession() block not fired. So I can't able to get session properly.

If you have faced any issue like this, please provide correct the solution if possible.

**Comment by vigneshwars** [comment]
Hi @rohandubal @JIBINVARGHESE912  is there a way to check the validity of the refresh token itself. My use case is to notify or give a warning to the user before the refresh token to re-login and get the new token.
