### ISSUE TITLE
Get access to Cognito Google identity data (e.g.: email address)

### ISSUE THREAD

**Issue by ekordin** [aws-amplify/aws-sdk-ios#1036]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
2.6.28

* Is the issue limited to Simulators / Actual Devices?
For any device

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Please provide the public functions to access the Google SignIn identity to get the current user email address like it can be done for pure Cognito user:

```
let cognitoUser = AWSCognitoUserPoolsSignInProvider.sharedInstance().getUserPool().currentUser()
let userName = cognitoUser?.username
```

But for Google user such properties and classes are private. The only case I can get the email address of the user that was signed in as Google User is to add a new pod to the project and access the singleton classes:

```
let googleProfile = GIDSignIn.sharedInstance().currentUser.profile
let firstName = googleProfile?.givenName
let lastName = googleProfile?.familyName
let email = googleProfile?.email
let userName = googleProfile?.email

// The same is actual for the Facebook:
FBSDKGraphRequest(graphPath: "me", parameters: ["fields": "id, first_name, last_name, email"])
```
That workaround works, but causes some issues with conflicting files, headers, etc. Please provide the public functions to get access to user's data for Google User (and Facebook identity too). You already have the required classes inside the AWSGoogleSignInProvider stack and AWSFacebookSignInProvider, but required objects are not public. That will a small fixes, but very useful for us.

**Comment by desokroshan** [comment]
Hello @ekordin,
I have filed this as a feature request in our backlog and have submitted it to the team for prioritization. I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the feature is released in the SDK. Thanks!

**Comment by vincenzon** [comment]
@ekordin can you elaborate on your work around? When I look at the GIDSignIn.sharedInstance the currentUser is nil. Do I need to instantiate that instance using the AWSMobileClient.sharedInstance somehow?

**Comment by royjit** [comment]
If you are using HostedUI for signIn in Cognito Userpool, you can map social providers attributes to UserPools via attribute mapping. But if you are directly signIn to Cognito Identity Pool via federated signIn, you have to get the attribute by the social providers SDKs/APIs.
