### ISSUE TITLE
PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by sajadkhan** [aws-amplify/aws-sdk-ios#1045]
I have recently updated the Xcode to 10.0 and after that I'm unable to create archive. This is log I get 

PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/muhammadsajad/Library/Developer/Xcode/DerivedData/ySkolar-cizrgcsvnlwnczdicazrfqwbihhi/Build/Intermediates.noindex/ySkolar.build/Debug-iphoneos/ySkolar.build/Script-9E682694EA2C01ECB09BB0EB.sh (in target: ySkolar)
    cd /Developer/yskolar
    /bin/sh -c /Users/muhammadsajad/Library/Developer/Xcode/DerivedData/ySkolar-cizrgcsvnlwnczdicazrfqwbihhi/Build/Intermediates.noindex/ySkolar.build/Debug-iphoneos/ySkolar.build/Script-9E682694EA2C01ECB09BB0EB.sh

mkdir -p /Users/muhammadsajad/Library/Developer/Xcode/DerivedData/ySkolar-cizrgcsvnlwnczdicazrfqwbihhi/Build/Products/Debug-iphoneos/ySkolar.app/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/muhammadsajad/Library/Developer/Xcode/DerivedData/ySkolar-cizrgcsvnlwnczdicazrfqwbihhi/Build/Products/Debug-iphoneos/AWSCore/AWSCore.framework" "/Users/muhammadsajad/Library/Developer/Xcode/DerivedData/ySkolar-cizrgcsvnlwnczdicazrfqwbihhi/Build/Products/Debug-iphoneos/ySkolar.app/Frameworks"
building file list ... done
deleting AWSCore.framework/_CodeSignature/CodeResources
deleting AWSCore.framework/_CodeSignature/
AWSCore.framework/

sent 142 bytes  received 26 bytes  336.00 bytes/sec
total size is 4594021  speedup is 27345.36
Code Signing /Users/muhammadsajad/Library/Developer/Xcode/DerivedData/ySkolar-cizrgcsvnlwnczdicazrfqwbihhi/Build/Products/Debug-iphoneos/ySkolar.app/Frameworks/AWSCore.framework with Identity iPhone Developer: Azaz Mahmood (3QUCUQH7A8)
/usr/bin/codesign --force --sign DD64EAF55BA0B1B97950184C53316C4D74D569C7  --preserve-metadata=identifier,entitlements '/Users/muhammadsajad/Library/Developer/Xcode/DerivedData/ySkolar-cizrgcsvnlwnczdicazrfqwbihhi/Build/Products/Debug-iphoneos/ySkolar.app/Frameworks/AWSCore.framework'
/Users/muhammadsajad/Library/Developer/Xcode/DerivedData/ySkolar-cizrgcsvnlwnczdicazrfqwbihhi/Build/Products/Debug-iphoneos/ySkolar.app/Frameworks/AWSCore.framework: errSecInternalComponent
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by cm-wada-yusuke** [comment]
I'm having the same issue.
Xcode 10.0

**Comment by sajadkhan** [comment]
At that time I had just updated my Mac OS. I wasn’t able to fix this trying everything, restarting Xcode, reinstalling Pods, Cleaning Project and Build Folder. Then I restarted my Mac and the error went away. I’m not sure but it had to do something with not restarting my computer after OS update. That might not be the case as the update didn’t require a restart, so we can say it was some kind of bug getting things twisted.

**Comment by cm-wada-yusuke** [comment]
In addition,
* I can build and run on simulator.
* I can't build for device. The above error occurred.
Mac OS: Mojave.

**Comment by baris-cincik** [comment]
Okay in my case the problem turned out to be about keychain access. When you are trying to run your app on an actual apple device you are prompted to enter your Mac password to allow keychain access. The first time this happened I accidentally hit "Deny". Once you hit deny you will never be asked to allow keychain access again and have the error above, UNLESS you restart your mac, which fixed the problem.

**Comment by palpatim** [comment]
@sajadkhan are you still having the problem you reported? If so, are you able to provide a minimal sample code project that demonstrates this problem? I'm able to build and archive for all of "Generic", simulator, and device. The most likely problem is some variation on what @baris-cincik pointed out--a local environment issue that is preventing code signing from working as expected.

**Comment by palpatim** [comment]
@cm-wada-yusuke As I noted above, I am able to build for device & simulator, and archive for all, on Xcode 10.

Being unable to build for device is very often a signing issue, which the SDK project, as a CocoaPod, Carthage, or framework dependency, shouldn't impact. Are you able to build your app for device if you remove all references to the AWS SDK? Conversely, are you able to create a barebones app that builds *until* you add the SDK? That would provide evidence that it's the SDK to blame.

**Comment by ltblueberry0** [comment]
I had a quite similar problem. Restarting the computer solved the problem.

**Comment by cm-wada-yusuke** [comment]
@palpatim 
I solved it by restarting my computer. If I encounter similar problems again, I will try to build on skeleton project according to your advice. Thank you.

**Comment by palpatim** [comment]
Thanks for the followups, all. It sounds like this issue is transient, so I'm going to close this. Feel free to open a new issue if you discover repro steps for an issue that cause this issue to recur.

**Comment by Liab-1337** [comment]
**

> Hmm. any fixes for this shit yet?

**

**Comment by codeslubber** [comment]
Omg, is this how you guys do issues?? 'oh sounds like a bunch of people have this problem, but since none of them presented me with a working demonstration, I'm gonna just close this up...'

**Comment by muellerfr** [comment]
Hi @codeslubber,

sorry to hear that you are running into this issue also. I am reopening the issue. We have been unable to reproduce the issue ourselves, which is why we are asking for repro steps. It is not even clear that this is an issue with the AWS SDK for iOS or rather with Cocoapods. 

If you can provide any additional information that would help us to reproduce and debug the issue it would be appreciated.

**Comment by Phoenix7351** [comment]
Having this issue as well.

**Comment by codeslubber** [comment]
Thanks @muellerfr, we resolved this yesterday. I will write up an issue about what fixed it for us. In short: we had to tweak the settings so that the unauth'ed account would not be used while waiting for the user account to auth.

**Comment by muellerfr** [comment]
@codeslubber that's great news. Please let us know the details, so we can prepare a fix.

**Comment by muellerfr** [comment]
Hi @codeslubber, can you share your findings?

**Comment by muellerfr** [comment]
Hi @codeslubber, can you share your findings or even just a consistent repo for the issue?

**Comment by sajadkhan** [comment]
@palpatim I was able to resolve this issue by restarting my computer. By reading the comments I have realized that you people have figured it out. Sorry for the delay I wasn't around.

**Comment by briansullivan1965** [comment]
Just had the same problem. The Xcode error log indicated a permissions error: 

`…/Xcode/Projects/<project-name>/Pods/Target Support Files/Pods-<project-name>/Pods-<project-name>/Pods-frameworks.sh: Permission ### denied 
Command PhaseScriptExecution failed with a nonzero exit code`

I did a chmod +x to the 'Pods-<project-name>-frameworks.sh', cleaned and rebuilt.

It works OK now.

**Comment by hannut91** [comment]
![image](https://user-images.githubusercontent.com/14071105/54977598-2ea03d00-4fe1-11e9-828f-6e7997fac817.png)
In the image above `Referenced from /usr/local/bin/node`
```bash
$ which node
/Users/yunseok/.nvm/versions/node/v10.15.3/bin/node
```
But xcode use node.js in `/usr/local/bin/node`
I use nvm. But node is installed at system too.
So I did delete system node with `brew uninstall --ignore-dependencies node`
I don't know detail what cordova use node, I think cordova use node in `/usr/bin/node`.
So I did this.
![image](https://user-images.githubusercontent.com/14071105/54977555-06b0d980-4fe1-11e9-987a-8900b1256d16.png)
I solved it.

**Comment by StrongFingers** [comment]
I have a similar issue and found a solution [here](https://stackoverflow.com/a/54415718/5030846)

**Comment by hersi** [comment]
Restart your mac then build your workspace. Build your project when the keychain prompts 
enter your mac login and the press always allow. This solution worked for me, but remember to 
update your  Xcode  and iPhone to lates version.

**Comment by yxwandroid** [comment]
> In addition,
> 
> * I can build and run on simulator.
> * I can't build for device. The above error occurred.
>   Mac OS: Mojave.

I'm having the same issue.

**Comment by HareshGediya** [comment]
Just had the same problem.
I did it by remove file in Pods -> Targets Support Files -> Pods-_AppName_ -> Pods-_AppName_-frameworks.sh.
And install pod again using **pod install**.

**Comment by yunseok2** [comment]
I had the same problem. In my case, the problem was caused by the difference between the version of Node.js used by Cordova and the version of Node.js used by Xcode.

**Comment by DSPerson** [comment]
Xcode -> File -> Workspace Setting... -> cut `Build System ` to Legacy Build System. Have Fun

**Comment by caglardurmus** [comment]
i found this solution and it fix my problem
write this code to terminal:

> chmod -R 755 {my_working_folder}

**Comment by mahgolfa** [comment]
I removed the script from run scripts in build phases, then built my app, and re added my script
cleaning project (ie. removing build folder from Xcode/DerivedData) has caused it I suppose.

**Comment by demosthese** [comment]
None of these solutions helped. Any other ideas?

**Comment by youki49** [comment]
In my case installing the latest version of Node.js solved it.

**Comment by Dereex** [comment]
In my case i just enter password from my mac and press allow always

**Comment by WilliamKatz** [comment]
In my case, I built the project without the script running first.  And then re-enabled the script and it worked.

This was the cause of a lot of frustration.

Carthage method, btw

**Comment by guigons** [comment]
reboot my MAC works for me! Thanks!

**Comment by numanayhan** [comment]
I fixed like this : bundle clear and rename and rebuild is Fixed

**Comment by iosjunkie** [comment]
What worked for me is adding all the framework that I've installed with Carthage in the Project Settings -> General -> Frameworks, Libraries, and Embedded Content.

**Comment by BiGapps-IOS** [comment]
For me helped "Clean Build Folder" and cleaning from Derived Data

**Comment by pedromelo98** [comment]
I was having: 
Command PhaseScriptExecution failed with a nonzero exit code
because:
mkdir: third-party: Permission denied
node_modules/react-native/scripts/ios-install-third-party.sh: line 59: cd: third-party: No such file or directory
So i did:
`sudo chown -R $(whoami) ~/.npm`
`sudo chown -R $(whoami) /usr/local/lib/node_modules`
This worked for me.
if `sudo chown -R $(whoami) /usr/local/lib/node_modules` does not work, you can substitute for `sudo chown -R $(whoami) ...pathToYourProject/node_modules`

**Comment by sergiobmstu** [comment]
delete pods directory, and pod install

**Comment by Mihir-mansa** [comment]
There are many reasons why this issue comes up, well in my case when I trying to run my project it gives me an error because of my mac doesn't give me permission to install pods. So I go my System Preferences -> security and privacy-> Allow Always. That's work for me

**Comment by byungwan-Jung** [comment]
Just reboot my mac. 
and recompile so error disappear. 

Thank you.

**Comment by khaledBou** [comment]
in Build Phases  select Run script only when installing
it fixed the problem for me

**Comment by fcoconstante** [comment]
> in Build Phases select Run script only when installing
> it fixed the problem for me

Work For me!! updating project from Swift 3.2 to 5, Thanks!

**Comment by lucasluca** [comment]
Perform the below steps:

Clean the build.
Go to File -> Workspace Settings
In shared workspace settings select "Legacy Build System" in Build System.
Now try to build and run.

**Comment by TheEndType1** [comment]
XCode 11, Exported from Unity( 2019.2.17f1) Windows, Copied files into Mac(Catalina) .
1) Open your project folder using terminal
2) write and execute ->  pod install   
3) then -> pod update
4) The main issue is permission so, -> chmod +x MapFileParser.sh
5) -> chmod +x process_symbols.sh

Worked for me.

**Comment by bluebird78999** [comment]
in Build Phases select all of the optional  options

**Comment by hadasacwebit** [comment]
invalidate and restart to android studio

**Comment by stijlerg** [comment]
Running pod install solved the issue for me

**Comment by samcolak** [comment]
Hey everyone - per the above issue, I noticed that at times, Xcode automatically enters the string {BUILD_VERSION} as opposed to 1 (in the info.plist file) - this will prevent scripts (like incrementing build numbers) from working correctly..

**Comment by gurbela** [comment]
Try this

    # Type a script or drag a script file from your workspace to insert its path.
    # skip if we run in debug
    if [ "$CONFIGURATION" == "Debug" ]; then
    echo "Skip frameworks cleaning in debug version"
    exit 0
    fi
    
    APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
    
    # This script loops through the frameworks embedded in the application and
    # removes unused architectures.
    find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
    do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"
    
    EXTRACTED_ARCHS=()
    
    for ARCH in $ARCHS
    do
    echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
    lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
    EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done
    
    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"
    
    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"
    
    done


check this ans: https://stackoverflow.com/a/64984008/7825015
