### ISSUE TITLE
AWSS3TransferUtility's urlsession cancelation takes time which might cause potential problem

### ISSUE THREAD

**Issue by fans3210** [aws-amplify/aws-sdk-ios#1049]
**Describe the bug**
We have a use case for the scenario below:
Our app has a logout feature. Currently we might call AWSS3TransferUtility's remove method when user logged out to double confirm and make sure that all pending tasks would be cancelled. This method will cause the URLSession to be cancelled and invalidated, which will remove the AWSS3TransferUtility object from the dictionary. But what I found is that the UrlSession's invalidateAndCancel method takes time to finish. If at the same time, user performed a login very fast(This could happen for the refreshToken expired and re-login case) and register another AWSS3TransferUtility with exactly the same identifier, the UrlSession's init method will report error that 'an urlsession with same identifier already exists'. This error is a silent error which won't block user from registering the transferutility but the upload/download feature won't work. I think we should wait until the previous cancelation method has finished before we start to init a new urlsession with the same identifier. 

My temporary solution for my app is: fully disable the 'remove' method from calling for the AWSS3TransferUtility and use a lazy initiated AWSS3TransferUtility globally. 

**To Reproduce**

**Environment(please complete the following information):**
 - SDK Version: 2.6.30
 - Dependency Manager:Cocoapods
 - Swift Version :4.2

**Comment by cbommas** [comment]
@fans3210 

Thank you for bringing this to our attention. I will look into checking if we can add error handling mechanisms to track the failure of creating the session.

For your specific scenario, I would recommend that you cancel (see http://aws.github.io/aws-sdk-ios/docs/reference//Classes/AWSS3TransferUtilityTask.html#//api/name/cancel)  all the tasks prior to calling the AWSS3TransferUtility's remove method. That should reduce the amount of work the `invalidateAndCancel` method has to do and speed it up.

**Comment by minbi** [comment]
Hi @fans3210 ,

We have just released version 2.8.2 of the SDK. Please check if this fixes the issue for you.

**Comment by cbommas** [comment]
@fans3210 

2.8.2 contains the error checking I mentioned previously. Please upgrade and let us know how it goes.

**Comment by fans3210** [comment]
@cbommas  Sorry I'm unable to test this functionalities recently. At least have some back up solutions as mentioned above. Will reopen this issue again if face any problem in the future.
