### ISSUE TITLE
How to add AWSLexButton in chat window?

### ISSUE THREAD

**Issue by SreekanthGudisi** [aws-amplify/aws-sdk-ios#1052]
**Add AWSLexButton**

**AWS Lex**

**Environment(please complete the following information):**
 - SDK Version: [2.6.30]
 - Dependency Manager: [Cocoapods :- 1.6.0.beta.1]
 - Swift Version : [4.1]

**Device Information (please complete the following information):**
 - Device: [iPhone8, Simulator]
 - iOS Version: [iOS 10.0]

What is **key** here in the below code?
```
let serviceConfig = AWSServiceConfiguration(region: Region, credentialsProvider: AWSIdentityManager.default().credentialsProvider)
  
guard let request = AWSLexPostTextRequest() else { return }
request.botName = ChatbotBotName
request.botAlias = ChatbotBotAlias
request.userId = UUID().uuidString
request.sessionAttributes = sessionAttributes as? [String : String]
request.inputText = "i need help"
  
let key = "testPostText"
AWSLex.register(with: serviceConfig!, forKey: key)
AWSLex(forKey: key).postText(request) { (response, error) in
    print(response?.message)
}
```

Getting response using above code. See below,

```
Optional(<AWSLexPostTextResponse: 0x600000a72fc0> {
    dialogState = 8;
    intentName = Hi;
    message = "Hello";
    responseCard = "<AWSLexResponseCard: 0x6000006249a0> {\n    contentType = 1;\n    genericAttachments =     (\n        \"<AWSLexGenericAttachment: 0x600000457cd0> {\\n    buttons =     (\\n        \\\"<AWSLexButton: 0x600000636c60> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000635060> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x6000006340a0> {\\\\n    text = \\\\\\\"text\\\\\\\";\\\\n    value = \\\\\\\"value\\\\\\\";\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000636ba0> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000633e40> {\\\\n    text = \\\\\\\"text\\\\\\\";\\\\n    value = \\\\\\\"value\\\\\\\";\\\\n}\\\"\\n    );\\n    subTitle = \\\"subTitle1\\\";\\n    title = \\\"title1\\\";\\n}\",\n        \"<AWSLexGenericAttachment: 0x6000006454f0> {\\n    buttons =     (\\n        \\\"<AWSLexButton: 0x600000634b00> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000634ac0> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000634760> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000634660> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\"\\n    );\\n    subTitle = \\\"subTitle1\\\";\\n    title = \\\"title2\\\";\\n}\"\n    );\n    version = 1;\n}";
    sessionAttributes =     {
    };
    slots =     {
    };
})
```

I Got stuck here. I Need to like this in the chat window
<img width="390" alt="screen shot 2018-09-30 at 9 45 42 pm" src="https://user-images.githubusercontent.com/23524697/46259677-38e1f280-c4fa-11e8-9d01-a444f1adb42f.png">

**Comment by kvasukib** [comment]
@SreekanthGudisi The key is used to retrieve the AWSLex client object that you create. Each client object that you created can be associated with a key (string) and you can retrieve the object using the key.

For the error response that you are getting, can you post the error message?

**Comment by SreekanthGudisi** [comment]
@kvasukib thanks for the reply.

> @SreekanthGudisi The key is used to retrieve the AWSLex client object that you create. Each client object that you created can be associated with a key (string) and you can retrieve the object using the key.
> 

Ok..

> For the error response that you are getting, can you post the error message?
>
I'm not getting any error. Getting response using that code.. Using that response i Need to add Buttons in chat window .
By the by why u closed this is issue ?

**Comment by SreekanthGudisi** [comment]
@kvasukib hello, When it will be solve ? ..

**Comment by palpatim** [comment]
Hi @SreekanthGudisi,

We don't currently offer a UI control for displaying buttons like those in a custom view. You can craft your own UI components by destructuring the response like so:

```swift
lex.postText(request) {
    (response, error) in
    guard let response = response else {
        print("Error: \(error?.localizedDescription ?? "No error description")")
        return
    }
    let message = response.message ?? "(No message available)"

    guard let responseCard = response.responseCard else {
        return
    }

    guard let genericAttachments = responseCard.genericAttachments else {
        return
    }

    for attachment in genericAttachments {
        let title = attachment.title ?? "No title provided"
        let subTitle = attachment.subTitle ?? "No subTitle provided"
        let imageUrl = attachment.imageUrl ?? "No imageUrl provided"

        guard let buttons = attachment.buttons else {
            continue
        }

        for button in buttons {
            let buttonText = button.text ?? "No button text provided"
            let buttonValue = button.value ?? "No button value provided"
        }
    }
}
```

You can find more info in the [API Documentation](http://aws.github.io/aws-sdk-ios/docs/reference//Classes/) (search for "AWSLex" to find the relevant classes.

Hope this helps.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
