### ISSUE TITLE
AWSIoT and AWSAppSync  in same project 

### ISSUE THREAD

**Issue by mrmrdolph** [aws-amplify/aws-sdk-ios#1053]
Is it not possible to use the **AWSIOT** framework and the **AWSAppSync** framework in the same project? 

Ive spent hours trying to get the AWSIoT Framework to compile. 
The pod is installed just fine, but trying to build the project results in 
_lexical or preprocessor issue_ with multiple files not found.

After lots of time ive realised that its the existing AWSAppSync pod that introduces this problem as it goes away if i remove it. So is this a bug or are these frameworks not compatible since they both have some form of MQTT implementation in them?  
Cant find any documentation indicating they aint.

**Comment by cbommas** [comment]
@mrmrdolph 

Unfortunately, you can't use both the AWSIOT and AWSAppSync framework in the same project. The AWSAppSync project has a slightly customized implementation of the AWSIOT implementation with overlapping classes, because of which the two can't be used together in the same app.

We have an item on the roadmap to re-architect the SDK to address this problem. I don't have a firm timeline on when that will be done.

**Comment by mrmrdolph** [comment]
Glad to hear that its on the roadmap since the two frameworks do not necessarily serve the same purpose. 
Luckily at this point i only need to update and get device shadow with IoT which i understand Im able to do without the SDK using REST.

**Comment by nneuberger1** [comment]
I'm interesting in understanding when this would be available.

I noticed that there are duplicate files with the same names between the two API's. So I believe I could have a workaround.  I forced a specific library to pull the specific from the corresponding class.

#import <AWSIot/AWSMQTTSession.h>
#import <AWSIot/AWSSRWebSocket.h>

Here's the rough files I had to modify.

AWSIoTDataManager.m
AWSIoTMQTTClient.h
AWSIoTMQTTClient.m
AWSIoTWebSocketOutputStream.h
AWSIoTWebSocketOutputStream.m

Does this sound like a good solution for a PR?  If so, I can push something up.  I would really like to have support between both.

**Comment by muellerfr** [comment]
Reopening this feature request until it is implemented.

**Comment by matthewbga** [comment]
> I'm interesting in understanding when this would be available.
> 
> I noticed that there are duplicate files with the same names between the two API's. So I believe I could have a workaround. I forced a specific library to pull the specific from the corresponding class.
> 
> #import <AWSIot/AWSMQTTSession.h>
> #import <AWSIot/AWSSRWebSocket.h>
> 
> Here's the rough files I had to modify.
> 
> AWSIoTDataManager.m
> AWSIoTMQTTClient.h
> AWSIoTMQTTClient.m
> AWSIoTWebSocketOutputStream.h
> AWSIoTWebSocketOutputStream.m
> 
> Does this sound like a good solution for a PR? If so, I can push something up. I would really like to have support between both.

Did you create a pod repo for this work? I'd like to take advantage of that. Otherwise, I am going to work on ding the same.

**Comment by nneuberger1** [comment]
No I didn't. I ended up only using AWSIoT and AWSDynamoDB core libaries. IMO, I really struggled with implementing AWSAppSync and how it was complicated in fully understanding GraphSQL and it's auto generated classes. I may try and transition to it at some point though.

**Comment by bnlerner** [comment]
@cbommas any update on when both pods could be used together? is there a milestone this is tied to?

**Comment by palpatim** [comment]
@mrmrdolph, @bnlerner, et al.

With the release of AppSync 3.0.0, we removed the dependency on the AWSIoT SDK, in favor of a new pure WebSocket connection using the [StarScream](https://github.com/daltoniam/Starscream) library.

This should allow you to use the AppSync and IoT libraries in the same app.
