### ISSUE TITLE
onLogin called twice when app starts

### ISSUE THREAD

**Issue by muellerfr** [aws-amplify/aws-sdk-ios#1054]
Originally submitted by @simonhopkin on the aws/aws-mobilehub-helper-ios:

Hi,

I'm seeing the `onLoginWithSignInProvider` call back of `AWSSignInDelegate` called twice when my app starts.

Is this intended behaviour?

I traced it down to the `resumeSessionWithCompletionHandler()` method of `AWSSignInManager`.  This makes a call to `[self.potentialSignInProvider reloadSession]` which in turn results in a call to `completeLogin()`.  However `completeLogin()` is also called within `resumeSessionWithCompletionHandler()`.  It might be clearer if I point it out in the code:

```
- (void)resumeSessionWithCompletionHandler:(void (^)(id result, NSError *error))completionHandler {

    self.completionHandler = completionHandler;
    
    for(NSString *key in [self getRegisteredSignInProviders]) {
        if ([[self signInProviderForKey:key] isLoggedIn]) {
            self.potentialSignInProvider = [self signInProviderForKey:key];
        }
    }
    
    [self.potentialSignInProvider reloadSession];    // Results in a call to completeLogin
    
    if (self.potentialSignInProvider == nil) {
        [self completeLogin];                    // Results in second call to completeLogin
    }
}
```

Is this a bug?

Reference: https://github.com/aws/aws-mobilehub-helper-ios/issues/45 

@kvasukib responded:

Thank you @simonhopkin for reporting to us. For Facebook and Cognito User Pools Sign In providers, the reloadSession method internally calls completeLogin which sets the signInProvider to nil (https://github.com/aws/aws-mobilehub-helper-ios/blob/master/AWSMobileHubHelper/Authentication/AWSSignInManager.m#L138). Now self.potentialSignInProvider == nil is true and completeLogin is called again.

We have moved the code for authentication from this library to AWS iOS SDK - AWSAuthSDK/AWSAuthCore (https://github.com/aws/aws-sdk-ios/blob/master/AWSAuthSDK/Sources/AWSAuthCore/AWSSignInManager.m#L106)

We are working on to fix the issue. We will update this thread once the fix is out. Thank you!

**Comment by BillBunting** [comment]
I also notice that resumeSessionWithCompletionHandler is called twice.  Any update on when this will be resolved?

[[AWSSignInManager sharedInstance] resumeSessionWithCompletionHandler:^(id  _Nullable result, NSError * _Nullable error) {
// CALLED TWICE WITH THE SAME RESULT
}

**Comment by kvasukib** [comment]
@BillBunting Have you checked with the latest iOS SDK?
