### ISSUE TITLE
Completion block is called for transfers that were started while offline after the app is force quit

### ISSUE THREAD

**Issue by hipwelljo** [aws-amplify/aws-sdk-ios#1058]
**Describe the bug**
I am seeing if you start an upload transfer while offline, then you force quit the app and reopen it, the task's completion block is called with a `nil` error and the task's status is 3 (`AWSS3TransferUtilityTransferStatusCompleted`). This occurs because in `didFinishLaunchingWithOptions` I register the `AWSS3TransferUtility` and in that completion block I reassign the progress and completion blocks for the upload tasks.

**To Reproduce**
1. Take your phone offline
2. Start an upload
3. Force quit the app
4. Rerun it

**Which AWS service(s) are affected?**
AWSS3TransferUtility

**Expected behavior**
I expected the transfer tasks to have a status of unknown, so the completion block wouldn't be called, and I would have to retry uploading them as new upload tasks, which is the behavior I see when starting the upload while online.

**Environment:**
 - SDK Version: 2.6.31
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information:**
 - Device: iPhone 6 Plus
 - iOS Version: 10.3.2

**Comment by hipwelljo** [comment]
Thanks @cbommas! No, it would not be possible to have been uploaded successfully since the device was offline the entire time.

**Comment by hipwelljo** [comment]
@cbommas Have you been able to take a look at this issue?

**Comment by cbommas** [comment]
@hipwelljo 
I was able to reproduce this issue. l have an update for you in the next few days

**Comment by cbommas** [comment]
@hipwelljo 

Just a quick update - I have a fix for this that I am currently testing. Will post back after I finish my testing and get the fix into the release pipeline.

**Comment by cbommas** [comment]
@hipwelljo 
The latest rev of the SDK 2.6.34 contains the fix for this issue. With this fix, when the app is force closed, the NSURLSession task associated with the transfer is canceled by the OS and the TransferUtility Task will move to an Error status.

Please give this a try and let me know how it goes.

**Comment by hipwelljo** [comment]
Confirmed this is working, thanks!
