### ISSUE TITLE
How to get the raw/full error message in ec2?

### ISSUE THREAD

**Issue by ssferrazza** [aws-amplify/aws-sdk-ios#1062]
**State your question**
Hi,
I'm wondering how to get the full error message as it is in the xml response of a failed ec2 request? E.g. 
`<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'i-011111111111' for instanceId. Instance does not have a volume attached at root (/dev/xvda)</Message></Error></Errors><RequestID>some-id</RequestID></Response>`

The problem is that the error provided in the completionblock (result is nil) locks like this `Error Domain=com.amazonaws.AWSEC2ErrorDomain Code=0 "(null)` but I want the error message as it is in the xml.

**Which AWS Services are you utilizing?**
EC2

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.6.20
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:
Non specific device/iOS version issue

Any help is appreciated.

Thanks
-Sal

**Comment by ssferrazza** [comment]
@cbommas Any news on this?

**Comment by cbommas** [comment]
@ssferrazza 

Sorry for the delay on this topic. I looked into it and expected to find the details in the userInfo object that is attached to the error, but saw that was null. Will investigate further and get back to you.

**Comment by ssferrazza** [comment]
@cbommas 

Thanks for the feedback.
I think I've located the cause for this and hacked a temporary workaround. In `AWSURLSessionManager.m`  is a method called `- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)sessionTask didCompleteWithError:(NSError *)error` and there the error object will be set with the following lines 
`if (error) {
                        delegate.error = error;
                    }`.
I replaced that line with this one:
`if (error) {
                        [self handleErrors: delegate];
                    }`.

And the handleErrors method:
`- (void) handleErrors: (AWSURLSessionManagerDelegate *)delegate {
    NSDictionary *responseDict = delegate.responseObject;
    delegate.error = [NSError errorWithDomain:AWSNetworkingErrorDomain code:AWSNetworkingErrorUnknown userInfo: responseDict[@"Error"]];
}`

Now I see the details in the userInfo object, but I'm not sure if I've catched all.

Hth
Sal

**Comment by cbommas** [comment]
@ssferrazza 
I will mark this as a bug and put it on our TODO list to fix. I will respond back here when I have more information.

**Comment by natanrolnik** [comment]
@cbommas This is still going on in 2.9.3 :/
Trying to run an instance in EC2 and getting not more than `Error Domain=com.amazonaws.AWSEC2ErrorDomain Code=0 "(null)"`

**Comment by kvasukib** [comment]
This happens because of an error in the deserialization of the response received from EC2.

**Comment by kneekey23** [comment]
Close with above PR
