### ISSUE TITLE
Uploads not starting on new SDK

### ISSUE THREAD

**Issue by simeondrage** [aws-amplify/aws-sdk-ios#1065]
**Describe the bug**
Sometimes our uploads are not starting. The solution is to try a combination of these
a) turn wifi off and on / disconnect reconnect the device
b) turn the device off and on
c) wait for x hours or minutes

**To Reproduce**
I am unable to consistently reproduce this. I have had it reported by about 10 customers and got all files to eventually upload using a combination of the above methods

**Which AWS service(s) are affected?**
s3

**Expected behavior**
The app has connectivity and access to the bucket is not blocked so it should upload. However it doesnt.
No error message is displayed.

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: iPads on iOS 12 (generally) is what our customers are using

**Additional context**

**Comment by pablogeek** [comment]
We are using AWSS3 2.6.31.

our code to upload is using TransferUtility

```
AWSTransfer(video: video) { [weak self] transferUtility in
            
            let fileURL = URL(fileURLWithPath: video.localFilePath)
            
            let task = transferUtility?.uploadUsingMultiPart(fileURL: fileURL,
                                                             bucket: video.amazonBucket,
                                                             key: video.uploadKey,
                                                             contentType: "video/mov",
                                                             expression: expression, completionHandler: completionBlockUpload)
            
            task?.continueWith(executor: AWSExecutor.mainThread()) {
                (uploadTasks) -> AnyObject! in
              
                if let error = task?.error as NSError? {
                    print("Error: \(error.localizedDescription)")
                
                }            
                if let res = task?.result {
                    // Do something with uploadTask.
                    self?.transferTasks[video.uploadKey] = res
                }
                return nil
            }
        }
```

**Comment by cbommas** [comment]
@simeondrage @pablogeek 

Hey guys,
Sorry to hear that you are running into this issue. Just so that I am clear - did this issue start with 2.6.31 or has it been present in prior versions of the SDK as well? Please let me know.

Some context: I have seen similar issues with download/upload speeds depending on whether the app is in the foreground, background, amount of charge on the phone, phone being plugged in etc. The slowest performance has been when the app is in the background ( or killed by the system) and the phone is low on battery. In all of testing that I have done, the transfers speed up once the app is in the foreground and always finish successfully. More information is available on this thread https://github.com/aws/aws-sdk-ios/issues/769 - At this point, I am inclined to believe that this is based on how the background transfer is being prioritized by the OS.

**Comment by simeondrage** [comment]
@cbommas thanks for getting back to us

We only released the latest version to our customers so not sure if it was present in previous versions of _this_ SDK. It wasn't present in the previous version we were using (Pablo would have to tell you the version we used before).

For the customers whilst they might have backgrounded the app, the upload was not starting when in the foreground. It doesnt seem like a speed issue as the upload isnt starting at all. In our app its showing _uploading_ status rather then _queued_ or _error_ but there is no progress at all. 

If we get more reports I will check if they have backgrounded the app

**Comment by pablogeek** [comment]
We were using 2.6.25 before

**Comment by cbommas** [comment]
@simeondrage  @pablogeek  
Thanks for getting back to me quickly - I have one other question - can you check to see if this issue is restricted to iOS 12 devices or if it is happening on older OS versions as well?

**Comment by simeondrage** [comment]
I haven't got any logs of this so will need to ask my team to collect this information

**Comment by cbommas** [comment]
@simeondrage @pablogeek

One of things that jumped out at me in the code snippet in #1066 is that you are creating a separate TransferUtility for each video that you are uploading. I believe that you are using the video key as the name for the TransferUtility session

      AWSS3TransferUtility.register(with: self.configurationAWSfor(video: video)!, forKey: key)

Each time you register a new key using  `AWSS3TransferUtility.register` it maps to a new NSURLBackground session. The testing that I have done and referenced in #769 all used a single TransferUtility to transfer multiple files, sometimes 100s  of files at a time. When I transferred a lot of files in quick succession, I would only see a few start and when they completed, the next few would start etc. This behavior i.e., how many transfers run at a time and in what order, at what speed etc is all controlled by the OS.

In your case, each transfer is tied to its own NSURLBackground session - I don't have definitive information on how transfers in multiple NSURLSessions are prioritized and scheduled by the OS. Could you try running a single TransferUtility that is shared across all the files in your app - A best practice that I would recommend is to register the `TransferUtility` in the app delegate 

        //Create and register TransferUtility client.
        AWSS3TransferUtility.register(
            with: serviceConfiguration!,
            transferUtilityConfiguration: transferUtilityConfiguration,
            forKey: "CONSTANT_VALUE"
            ) { (error) in
          }

and then look it up where ever needed using 

         //Grab the transfer Utility
         let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "CONSTANT_VALUE") 

Please let me know what you think.

**Comment by pablogeek** [comment]
@cbommas Hey! We have different keys for each video, thats why we create different configurations in `configurationAWSfor` we get those credentials from our backend. We get different credentials in each upload, thats why we need to create a TransferUtility in each upload.

**Comment by cbommas** [comment]
@pablogeek 
I see. Thanks for clarifying.

I will continue to look for any documentation on how to tweak the NSURL Background session to increase speeds. Here is some interesting info - see the section on background downloads in https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/DeferNetworking.html

**Comment by simeondrage** [comment]
Just had another report of this. User was on iOS 11.3.1

**Comment by simeondrage** [comment]
We have 2 ways to getting the upload started
1) turning the device off and on
2) turning the wifi off , hard quit the app and relaunch, then turn wifi back on
neither are 100% reliable but between them we are gettingstuck uploads started

**Comment by minbi** [comment]
Hi @simeondrage,

We have just released version 2.8.2 of the SDK. Please check if this fixes the issue for you.

**Comment by simeondrage** [comment]
we are currently using the old SDK. We can't reliably reproduce this issue (though we did have about 20 reports from customers). We can't risk using the new SDK at the moment I'm afraid as we wont be able to confirm if the issue is resolved. 
@minbi

**Comment by cbommas** [comment]
@simeondrage 

I understand. 

The change in this most recent version of the SDK was to create all the NSURLSession tasks up-front, which should prevent tasks being created when the app is in the background. The idea is that tasks created when the app is in the background are prioritized lower by the OS and this would prevent that.

I will go ahead and close this issue. When you are able to upgrade to this version at some later time, please do let me know if you run into issues ( create a new thread at time if required)
