### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by muellerfr** [aws-amplify/aws-sdk-ios#1073]
Issue was originally opened by @bhanuteja501 
https://github.com/awslabs/aws-sdk-ios-samples/issues/316

**State your question**

I newly started application(using aws). i didn't getting how to user name and password send to aws cognito . i didn't gettting swift functions exactly. aws tutorial given other pods with new version. here different . please help me. i want to start implement login .

**Which AWS Services are you utilizing?**

Cognito

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by desokroshan** [comment]
@bhanuteja501, All the client APIs needed to implement login is now provided through AWSMobileClient. You can find snippets for [initializing](https://aws-amplify.github.io/docs/ios/authentication#initialization), adding [sign-in UI](https://aws-amplify.github.io/docs/ios/authentication#drop-in-auth) and other authentication functionalities [here](https://aws-amplify.github.io/docs/ios/authentication#drop-in-auth). Do let me know if you have any questions.
