### ISSUE TITLE
Verbose Logging statement does not report correct successful submitted events

### ISSUE THREAD

**Issue by Wavewash** [aws-amplify/aws-sdk-ios#1074]
**Describe the bug**
AWSPinpointEventRecorder.m line 923
AWSDDLogInfo(@"Successful submission of %lu events. Response code: 202", (unsigned long)[[_processedEvents objectForKey:@"removeEvents"] count]);

Always prints "Successful Submission of 0 events. Response code: 202" - even though many events may have been successfully submitted.

I believe this is due to the fact that we're displaying the key "removeEvents" on _processedEvents instead of "acceptedEvents"

**To Reproduce**
Set logging to verbose
AWSDDLog.sharedInstance.logLevel = .verbose
and submit any number of events to pinpoint

You'll notice that the printed accepted event count is 0 because the key "removeEvents" doesn't exist on _processedEvents

**Which AWS service(s) are affected?**
AWSPinpoint

**Expected behavior**
The Log statement should reflect the successful events dispatched

**Environment(please complete the following information):**
 - SDK Version: 2.6.33
 - Dependency Manager: Cocoapods
 - Swift Version : 4.1

**Device Information (please complete the following information):**
 - Device: iPhone7
 - iOS Version: iOS 11.4

**Comment by palpatim** [comment]
@Wavewash Thanks for the detailed bug report! I confirm the behavior, and we'll get a fix in for an upcoming release.

**Comment by palpatim** [comment]
This is fixed in v2.6.34
