### ISSUE TITLE
not able do to signin, (if it gives wrong details "user does not exits" , if gives true details) getting these issues

### ISSUE THREAD

**Issue by muellerfr** [aws-amplify/aws-sdk-ios#1075]
Issue originally submitted by @santhoshappdev at https://github.com/awslabs/aws-sdk-ios-samples/issues/317

**State your question**

 '*** -[Swift._NSContiguousString substringFromIndex:]: Index 9223372036854775808 out of bounds; string length 47'
![screen shot 2018-10-29 at 5 56 07 pm](https://user-images.githubusercontent.com/35039366/47654633-4221b600-dbb1-11e8-9dfb-7462f1d4dd3a.png)

**Which AWS Services are you utilizing?**

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by rohandubal** [comment]
Hello @santhoshappdev 

This error is due to incorrect User Pool ID. You need to specify a valid user pool id to use the app correctly.

Thanks,
Rohan
