### ISSUE TITLE
AWSCognito tvOS support 

### ISSUE THREAD

**Issue by eclaires** [aws-amplify/aws-sdk-ios#1078]
**Which AWS Services is the feature request for?**
tvOS support for AWSCore, AWSCognito, AWSKinesis

**Is your feature request related to a problem? Please describe.**
When I try to include the pods for the tvOS target I get this
[!] The platform of the target `BTVtvos` (tvOS 11.0) is not compatible with `AWSCognito (2.6.30)`, which does not support `tvos`.
[!] The platform of the target `BTVtvos` (tvOS 11.0) is not compatible with `AWSCore (2.6.30)`, which does not support `tvos`.
[!] The platform of the target `BTVtvos` (tvOS 11.0) is not compatible with `AWSKinesis (2.6.30)`, which does not support `tvos`.

We are using Firehose to track user actions for our iOS app, would love to see what our tvOS users are doing.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by muellerfr** [comment]
Hello @eclaires,

Thank you for submitting the feature request. I will take this to the team, and update the issue thread with updates.

**Comment by eclaires** [comment]
Thank You!

**Comment by dan-didjatv** [comment]
@muellerfr any update on where this went? Seems like it's just a platform targeting issue. We could hit the APIs directly but we're already using Amplify for iOS and seems silly to do that because of a build issue.

**Comment by kramesh2005new** [comment]
@palpatim @muellerfr Any update about tvOS support ?

**Comment by zivz** [comment]
Any update on this?

**Comment by skatolyk** [comment]
Any update on this?

**Comment by temymykytaoliinyk** [comment]
Any update on this?

**Comment by drochetti** [comment]
Hi @eclaires, we're currently evaluating supporting other platforms, such as tvOS. Our primary goal is to add support for other platforms in [Amplify iOS](https://github.com/aws-amplify/amplify-ios), we're still not sure if we'll be able to cover all the SDKs, since there's quite a bit of area to cover and also legacy code. Regardless I'll keep you posted.

In case you're working on new projects, I suggest you check if Amplify is a good fit for you.

**Comment by eclaires** [comment]
Thank you for updating me! I've had to download source and include it in our project for tvOS each time I update our version of AWSCognito. I have a script which makes the necessary header file include changes.
Please let me know if the tvOS version of AWSCognito becomes available.

**Comment by eclaires** [comment]
Hi Daniel,
Any update on this? I'm updating 3rd party libraries and would like to use the latest versions of AWSCore, AWSCognito, AWSKinesis.
Using Amplify doesn't really work for us as we only need the functionality in those librarues.
Thanks! Claire

**Comment by royjit** [comment]
Please ref - https://github.com/aws-amplify/aws-sdk-ios/issues/280#issuecomment-910398359 regarding support on other platforms with AWS SDK.

**Comment by VaibhavJais** [comment]
Hi AWSCognito, AWSCognitoIdentityProvider and other categories are supported in tvOS? I have to add authentication in tvOS using AWS Cognito and AWSCognitoIdentityProvider.

**Comment by hrvoje0099** [comment]
Any update about tvOS support ?

**Comment by anton-tropashko** [comment]
Apparently noone cares.

**Comment by harsh62** [comment]
Please refer to the [comment](https://github.com/aws-amplify/aws-sdk-ios/issues/280#issuecomment-910398359) regarding support of tvOS platform.
