### ISSUE TITLE
Pinpoint Analytics - PN Campaigns - Once - Sessiton heat map shows sessions in past & future, opens for silent pushes

### ISSUE THREAD

**Issue by sshilko** [aws-amplify/aws-sdk-ios#1080]
Hello, we just sent out a campaign A (push notifications channel only to iOS client)
"Once" type-schedule campaign A: created at 16:00 with Scheduled time 17:00 (w/o respect local time) with around 80k iOS APNS (non sandbox) segment endpoints 

We now (at 17:30) open AWS Console - Pinpoint - Analytics - Campaigns - select campaign A
and see on "Campaign session heat map" that there are:

- more than 0 session starts before 17:30 (few days AGO)

- more than 0 session starts in future >1 day (even >3 days in future) ahead in future

**1. How can this happen that we see sessions in past/future?**
**2. The campaign type was silent with "{}" payload, but we see "Opens" number >0, how is that?**

Does some recipients have their device time in past/future ? 

Or what is the explanation for this heatmap then.

We see similar behaviour with "respect local time" checkbox enabled too.

Thanks

```
- AWSCore (2.6.32)
 - AWSPinpoint (2.6.32):
   - AWSCore (= 2.6.32)
 - AWSS3 (2.6.32):
   - AWSCore (= 2.6.32)
```
![s4](https://user-images.githubusercontent.com/1147808/47866752-edc04580-ddff-11e8-99bb-8e6189b7d325.png)
![s3](https://user-images.githubusercontent.com/1147808/47866669-b782c600-ddff-11e8-929c-da58b50348fd.png)
![s2](https://user-images.githubusercontent.com/1147808/47866670-b782c600-ddff-11e8-98be-7a0961619058.png)
![s1](https://user-images.githubusercontent.com/1147808/47866672-b81b5c80-ddff-11e8-96dc-54a733b9cf48.png)

![s4](https://user-images.githubusercontent.com/1147808/47867241-43492200-de01-11e8-95fa-fce7322d904f.png)
![s3](https://user-images.githubusercontent.com/1147808/47867243-43e1b880-de01-11e8-9370-cc5928ac2358.png)
![s2](https://user-images.githubusercontent.com/1147808/47867244-43e1b880-de01-11e8-963e-661cb7973f9e.png)
![s1](https://user-images.githubusercontent.com/1147808/47867245-43e1b880-de01-11e8-893c-d25158dcc408.png)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@sshilko Sorry for the delayed response. Can you email me (karthba at amazon dot com) your Pinpoint application ID so I can communicate with the Pinpoint Service team?

**Comment by sshilko** [comment]
Just close it, i spent already 2 montha talking to aws support. Fixing
pinpoint seems to be low priority.
