### ISSUE TITLE
Custom Challenge flag in getSession method call (iOS)

### ISSUE THREAD

**Issue by iosfitness** [aws-amplify/aws-sdk-ios#1081]
**Which AWS Services is the feature request for?**
AWSCognito services in AWS on iOS platform

**Is your feature request related to a problem? Please describe.**
 More details can be found here #1072

**Describe the solution you'd like**
Need a flag which can help to edit isInitialCustomChallenge

**Describe alternatives you've considered**
I tried to manually set the flag to **YES** in AWS library code 

- (AWSTask<AWSCognitoIdentityUserSession*>*) getSession:(NSString *)username password:(NSString *)password validationData:(NSArray<AWSCognitoIdentityUserAttributeType*>*)validationData {
    
    return [self setConfirmationStatus: [[self srpAuthInternal:username password:password validationData:validationData lastChallenge:nil isInitialCustomChallenge:YES] continueWithSuccessBlock:^id _Nullable(AWSTask<AWSCognitoIdentityProviderRespondToAuthChallengeResponse *> * _Nonnull task) {
        return [self getSessionInternal:task];
    }]];
}

**Comment by royjit** [comment]
@iosfitness 
This is available now in the latest iOS SDK as part of custom auth changes. Closing this issue, please reach back to us if you have any questions.
