### ISSUE TITLE
5000 memory leaks on registering AWSS3 client with config

### ISSUE THREAD

**Issue by alexander-aernos** [aws-amplify/aws-sdk-ios#1084]
I've been trying to figure out for the past two days why this simple setting up of a AWSS3 configuration could possibly create 5000+ memory leaks.  This is the the code I have running in AppDelegate:

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // SetUp AWS Config
        let myIdentityPoolId = Constants.AWS_IDENTITY_POOL_ID
        let credentialsProvider: AWSCognitoCredentialsProvider = AWSCognitoCredentialsProvider(regionType: .USWest2,
                                                                                               identityPoolId: myIdentityPoolId)
        if let configuration = AWSServiceConfiguration(region: .USWest2, credentialsProvider:credentialsProvider) {
            AWSS3.register(with: configuration, forKey: "defaultKey")
        }
        
        return AWSMobileClient.sharedInstance().interceptApplication(application,
                                                                     didFinishLaunchingWithOptions: launchOptions)
    }

Using Instruments, I've tested removing all the code I shared (except for the return AWSMobileClient.sharedInstance().interceptApplication) and found that I get no memory leaks, but as soon as I add it back I end up with all the leaks... What gives?

If it helps, I'm wanting to list the objects of my AWS bucket which works with the following code:

     let listRequest: AWSS3ListObjectsRequest = AWSS3ListObjectsRequest()
        let s3 = AWSS3.s3(forKey: "defaultKey")
        
        listRequest.bucket = Constants.AWS_BUCKET
        listRequest.prefix = Constants.SPECIAL_PREFIX
        
        s3.listObjects(listRequest).continueWith { (task) -> AnyObject? in
    }

Am I making an obvious mistakes?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/rXi9O.png

**Environment(please complete the following information):**
 - SDK Version: 2.6.33
 - Dependency Manager: CocoaPods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: iPhone 7+
 - iOS Version: iOS 11.4.1

**Comment by rohandubal** [comment]
Hello @alexander-aernos 

I tried to reproduce this issue on my side but was unable to do so. Your code looks correct to me.

Will it be possible for you to provide a sample app where we can reproduce this? It will be also nice if you could paste the full stack (bottom right of image you posted) which can help us identify where the leak originated from.

Thanks,
Rohan

**Comment by alexander-aernos** [comment]
@rohandubal Hey, thanks for getting back to me.  I re-ran instruments leak checker just now and am surprised to find no memory leaks.  Whatever the issue was, I can't recreate it anymore.
