### ISSUE TITLE
Polly running on XCUITest with no audio sound

### ISSUE THREAD

**Issue by desokroshan** [aws-amplify/aws-sdk-ios#1086]
I made a small test app using Polly to speak some text and it plays well. I then moved the same piece of code to XCUITest, there is no compile or run-time error when the code runs through, but there is no sound came out. Any clue what to look for to solve this problem? Just want to let you know that XCUITest is running on a background thread.

**Comment by desokroshan** [comment]
This issue was originally opened by @jingyul.

**Comment by palpatim** [comment]
I've confirmed that our Polly integration tests run in the background against a host app and do generate sound. There may be some configuration option that XCUITests require, but for now, I can confirm that this is working as expected on both apps and integration tests. 

@jingyul if you are still facing this issue, can you open a new issue with repro steps, and possibly a repro app that demonstrates the issue?
