### ISSUE TITLE
Cognito Auth with S3 bucket download

### ISSUE THREAD

**Issue by muellerfr** [aws-amplify/aws-sdk-ios#1087]
Originally opened by @gasparuff  at https://github.com/awslabs/aws-sdk-ios-samples/issues/318

**State your question**

I have setup Cognito Auth like in the example, although I cannot download an image directly after logging in. I'm always getting this unauthenticated access is not allowed..." directly after login. I'm using the S3 TransferUtility for this. When I close the app from the background and relaunch it, the image download works. I figured out the loginMap` is not set in the credentialsprovider directly after logging in and trying to fetch the file from the bucket. What can be wrong?

**Which AWS Services are you utilizing?**

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by sunchunqiang** [comment]
Hi @gasparuff 

Which version of aws sdk are you using. Can you provide some code snippet for us to reproduce the issue?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
