### ISSUE TITLE
Token renew token after expiration

### ISSUE THREAD

**Issue by desokroshan** [aws-amplify/aws-sdk-ios#1092]
According to https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-user-pools-using-the-refresh-token

The Mobile SDK for iOS and the Mobile SDK for Android automatically refresh your ID and access tokens if there is a valid (non-expired) refresh token present, and the ID and access tokens have a minimum remaining validity of 5 minutes. If the refresh token is expired, your app user must reauthenticate by signing in again to your user pool.

Could u please provide example in swift how to renew the token ? Just to be sure that we r on right way?

**Comment by desokroshan** [comment]
Originally opened by @evgzor [here](https://github.com/awslabs/aws-sdk-ios-samples/issues/319).

**Comment by rohandubal** [comment]
Hello @evzgor

There is no explicit action required from your side for handling the token refresh. The SDK internally refreshes it before giving a callback. The code for that can be found here: 

https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L178-L226

Hope this helps.

Thanks,
Rohan
