### ISSUE TITLE
Velocity of mobile landscape on aws is not fun as a developer and existing users

### ISSUE THREAD

**Issue by rromanchuk** [aws-amplify/aws-sdk-ios#1097]
I have been using aws for mobile for a very long time. Before mobile serverless software suites were a "thing". My largest use case was interfacing aws services with cognito to provide temporary  unauthenticated credentials backed by IAM policies.  I noticed it's been getting increasingly more difficult and time consuming to keep myself up to date as amazon scrambles to repackage, remarket, and rebrand their mobile offerings. 

Every 12 months it feels like a service i'm using gets rolled up into a new service as aws attempts to better align themselves with the competitive market. I get it, for new customers it's a much better onboarding experience and it's a much easier sale  by repositioning around the value prop to those unfamiliar with what AWS has to offer. 

I understand the strategy, just put a big wrapper on top of everything. For existing users it starts getting annoying as configuration management and documentation is constantly shifting. I've tried to force myself to switch over to using these wrappers in hopes to make troubleshooting and documentation easier to parse. For example, i tried switching my existing project over, but there was no way to use my existing identity pool or dynamodb resources. It gave me absolutely nothing, besides a configuration setting that now directly conflicts with my existing resources.  

I think mobile analytics is probably on its fourth restructure now. Anyways, I went in today to audit whatever it is now `Pinpoint` or is it `MobileHub`, or maybe it's pinpoint on mobilehub, who knows. 

Do i do it through here:
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-analytics.html

Here?
https://console.aws.amazon.com/mobilehub/home#/fff07d85-388e-4adc-af0e-a739bcda1680/build/analytics

Here? 
https://console.aws.amazon.com/pinpoint/home/#/apps/876e176ea76842cab82392aca9a7aeb8/settings/nativeAnalytics

Here is one instruction
```swift
import AWSCore
import AWSPinpoint

     class AppDelegate: UIResponder, UIApplicationDelegate {

         var pinpoint: AWSPinpoint?

         func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions:
         [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

         //. . .

         // Initialize Pinpoint
         pinpoint = AWSPinpoint(configuration:
                 AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions))

         //. . .
         }
     }
```

Here is another one:

```swift
import AWSCore
import AWSPinpoint
import AWSMobileClient

class AppDelegate: UIResponder, UIApplicationDelegate {

    /** start code copy **/
    var pinpoint: AWSPinpoint?
    /** end code copy **/

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions:
    [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

         //. . .

         // Initialize Pinpoint
         /** start code copy **/
         pinpoint = AWSPinpoint(configuration:
             AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions))

         // Create AWSMobileClient to connect with AWS
         return AWSMobileClient.sharedInstance().interceptApplication(application, didFinishLaunchingWithOptions: launchOptions)
         /** end code copy **/
    }
}
```

What is `AWSMobileClient`?

https://aws-amplify.github.io/aws-sdk-ios/docs/reference/Classes/AWSMobileClient.html

> AWSMobileClient helps you initialize the SDK, fetch the Cognito Identity and resume any previously signed-in session. It also registers the SignIn providers based on the information provided in awsconfiguration.json file

Oh god that sounds important, vague, but important. Let's dig around some more:

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/getting-started.html

Oh no, another mobile service integrator with a new name. Did they buy amplify the mobile analytics company? 

> Get started building a cloud-powered iOS app using the AWS Amplify CLI and the AWS SDK for iOS. This page guides you through setting up an initial backend and integrating the SDK into your app.

My goal here is just to make sure i have mobile analytics setup..err i mean pinpoint analytics. My dashboard has data, but something is seriously off. I turned on debugging and sure enough my IAM policies were getting access denied messages, which is most definitely a regression or something i induced fumbling around aws. Sure enough my cognito unauthenticated role has a bunch of warning on it that my resource type is unsupported, even though i confirmed i have the same ARN one of the tools above told me should be set. 

> You chose actions that require the apps resource type.

I press the tool tip that defines

> The definition of a mobile app stored in Amazon PinPoint. 

Which the learn more redirect me to https://docs.aws.amazon.com/pinpoint/latest/apireference/welcome.html

I'm guessing this was some switch to better align the concept of an "App" thats wrapped around a config file and a UI

Finally figure out it's barfing because i have other resources defined with wildcards.  

AWS needs to reel it in a bit. I can feel the anxiety that management has towards Firebase and it's awkward sitting on the other side of it. I just don't think kitchen sinking this project is ever going to win. 

/rant over xoxoox

**Comment by palpatim** [comment]
Thanks for your candid and detailed feedback @rromanchuk. As you may have noticed, we are attempting to consolidate our SDK documentation under a single site, and updating it to use our currently-recommended best practices. You can find the new documentation for the iOS SDK [here](https://aws-amplify.github.io/docs/ios/start).

However, that documentation doesn't really address your underlying concerns, which if I'm interpreting correctly primarily revolve around:

1. Inconsistent integration steps across multiple revisions of the various modules the SDK covers (e.g., MobileAnalytics/Pinpoint)
1. Multiple and unclear entry points for accomplishing integration tasks (e.g., Mobile Hub vs. Amplify vs. Pinpoint console)
1. Breaking configuration changes moving from old systems to new (as noted with the wildcard ARN issue above)
1. Unclear or missing documentation on configuration options

I'm passing on your feedback to our product team to handle the first items. Regarding the last (documentation about `awsconfiguration.json`), there is unfortunately no documentation on that file. In general, you should be able to declare different configuration sets in the `awsconfiguration.json` file, per service, as you have done above, and then access them with the service's appropriate registration method. For example, for S3TransferUtility, you should be able to use the configuration above with a call like `let profilePicturesTransferUtility = AWSS3TransferUtility(forKey: "ProfilePictures")`. 

But since there is no consolidated documentation for the various keys available in a particular AWSInfo's infoDictionary, it's difficult to discover which options are respected in a given configuration dictionary. I've added a backlog item for us to improve this documentation.

**Comment by rromanchuk** [comment]
@palpatim 

**edit**: _I forgot to hit send on this two weeks ago, half of it is probably invalid/changed since then, you guys move fast._ 

Yeah, I think my anxiety stems from lifting my head up and not being able to find the answers i'm looking for. My relationship with mobile and aws is using services to solve problems and using language SDKs to work with those services. It feels like my country was just invaded by Javascriptistan 😈. 

I've already noticed a ton of documentation being swept up, but it's frustrating because the focus looks like it's being spent around how to auto-configure an app with the kitchen sink. A lot of it is also being obfuscated from the actual aws services which back it.  

For example, i wanted to embrace pinpoint, it makes total sense. I'm already using SES to deliver my transactional emails, twilio for SMS, and consolidating all of these on top of analytics and the ability to segment makes total sense. 

Since I'm already using SES, i figured i'd start with that channel first. The onboarding experience was a little funky because i'm already using SES, so understanding the relationship between Pinpoint and SES was a little confusing. I figured that maybe pinpoint injects itself around a special SMTP interface that handles the analytics and the "open and click tracking".  I then realized there is a `PinpointEmail` API with a slightly different signature then the `ses` sdk. That makes sense, this must be how Pinpoint does what it does. 

So then i sent this PR in https://github.com/aws/aws-sdk-rails/pull/24  that is a drop in replacement to utilize the pinpoint API for email delivery. It had no change on my email analytics. I'm clearly missing some fundamental concept. After slowing down and reading, i see that if i use my own domain i need some sort of redirect to ingest email opens, unfortunately, the "learn more" link just redirects back to console.

Then there's endpoints, (basically obfuscated SNS topics), i get the why, this is how we're going to use our channels with segments to create great campaigns. I want to utilize all of these channels, so my next step was to get endpoints generated for my authenticated users. This was actually a pretty difficult task to execute on. 

I noticed there is a lot of concepts that are mashed together making implementation so much harder. Analytics is deeply entangled into endpoints, and channels, and this is not how people conceptualize basic event tracking. 

In the analytics section of the ios implementation https://aws-amplify.github.io/docs/ios/analytics there is instructions on how to bind the "user endpoint" to your identifier if you don't use User Pools.  

```swift
if let targetingClient = pinpoint?.targetingClient {
    let endpoint = targetingClient.currentEndpointProfile()
    // Create a user and set its userId property
    let user = AWSPinpointEndpointProfileUser()
    user.userId = "UserIdValue"
    // Assign the user to the endpoint
    endpoint.user = user
    // Update the endpoint with the targeting client
    targetingClient.update(endpoint)
    print("Assigned user ID \(user.userId ?? "nil") to endpoint \(endpoint.endpointId)")
}
```

Here are some rhetorical questions, which i got answered by just digging down into the source.  What is my current endpoint? When did it get created? Does every endpoint have to be attached to a channel?  Is this an endpoint on the APN channel, what if I didn't intercept didRegister? What does it mean to record events on a channel? What if i want to record a revenue event for a user from my server, what endpoint do i use to record this event and what does that even mean? How do i register more endpoints for my authenticated user (phone, email). 

I decided it was wayyyyyy to cumbersome to register these endpoints from the client so i decided to do it from the backend. So I fumbled through wrangling dictionaries https://gist.github.com/rromanchuk/7a54969f68c18be012905d1a56de8d29

I also wanted to punish myself and figure out how to send events from the backend too (Firebase doesn't actually yet support this at all, so +1 for Pinpoint) https://docs.aws.amazon.com/pinpoint/latest/apireference/rest-api-events.html

This was very painful, mostly because I haven't fully grokked endpoint concepts, the data structures are complex, and legacy `MobileAnalytics` documentation still dominates SEO. I had to do some careful digging to find monetization event labels. 
https://gist.github.com/rromanchuk/d7ec05b43b81a97de29ffe8963b1a488

One thing i noticed in this transition is all the Kinesis talk. The emphasis on Kinesis is curious to me as well. Sooo much Kinesis talk. Who is manually importing endpoints with json and then utilizing kinesis firehose in any productive manner? I know it's attractive in order to market the offering to someone who is just starting a new react mobile app and window shopping between google and aws, but the focus seems premature to me. 

Didn't mean this to be novel, i'm excited to move all my mobile services under the AWS ecosystem, i think my user persona is just in an awkward state as mobile is shifting. I think the best thing that will help developers, especially those already using aws services with production apps already in the wild, is more realistic production examples. Right now the focus is on getting started, and a lot of the usage is contrived. The now deprecated example libraries had a strong focus on problem/solution examples and a good mixture between reference and implementation. I know you guys know this, and I know it's coming down the pipeline, so just need to be patient. Great job to all the technical writers working at break neck speed. I've been watching the transition, y'all have super powers and probably consuming a lot of coffee. 

Appreciate the response, hopefully this feedback is helpful and provides context for my type of customer persona.
