### ISSUE TITLE
'resumeSessionWithCompletionHandler' can call the 'completionHandler' more than once

### ISSUE THREAD

**Issue by desokroshan** [aws-amplify/aws-sdk-ios#1108]
PS I forgot to mention that I noticed the 'resumeSessionWithCompletionHandler' can call the 'completionHandler' more than once.  eg.  If I resume with google, and since the delegate is asynchronous, first I see the completionHandler called (not logged in) and then a short while later it calls back from the CompleteGLogin with loggedIn true.  Probably this is intended behavior,  but maybe it needs a mention in the code base.

Originally pointed out by @WhiteHexagon [here](https://github.com/awslabs/aws-sdk-ios-samples/issues/27#issuecomment-147716861)

**Comment by rohandubal** [comment]
Hello @WhiteHexagon,

We released `AWSMobileClient` version `2.7.0` recently which introduces new API like `initialize` which streamlines usage of method of `resumeSessionWithCompletionHandler`. The `initialize` method will make sure there are no race conditions or duplicate callbacks. 

Please refer to documentation here: https://aws-amplify.github.io/docs/ios/authentication 

Thanks,
Rohan
