### ISSUE TITLE
AWSHealth API Coverage

### ISSUE THREAD

**Issue by plafue** [aws-amplify/aws-sdk-ios#1111]
Hello! Are there any plans to offer an API to interact with [AWSHealth](https://docs.aws.amazon.com/health/latest/APIReference/Welcome.html)?

**Environment**
 - SDK Version: 2.7.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2.1

Thank you very much in advance

**Comment by cbommas** [comment]
@plafue 

I am not aware of any plans to add support in the iOS SDK for AWSHealth. I will bring it our product team for prioritization. Will loop back once there is more  information.

**Comment by plafue** [comment]
This feature request is now obsolete
