### ISSUE TITLE
Custom IoT Authorizer for iOS SDK?

### ISSUE THREAD

**Issue by spencerkohan** [aws-amplify/aws-sdk-ios#1112]
**Which AWS Services is the feature request for?**

iOS SDK: AWSIoT component

**Is your feature request related to a problem? Please describe.**

Currently we are using a custom IoT authorizer for our system, and there does not seem to be support to access this (i.e. to get a thing shadow, to subscribe to MQTT topics) using the iOS SDK.

Custom IoT authorizers are a [supported, documented feature of AWS](https://docs.aws.amazon.com/iot/latest/developerguide/custom-authorizer.html) however there does not appear to be support in the mobile SDKs.

**Describe the solution you'd like**

We would like to be able to provide custom headers for connecting to AWS IoT as is already possible in the node SDK:

https://github.com/aws/aws-iot-device-sdk-js#custom-authorization-configuration

I suppose this would be somehow required in the initialization of the `AWSIoTDataManager`.

Also, if you can provide any guidance on a workaround using the current SDK it would be much appreciated.

**Comment by muellerfr** [comment]
Hello @spencerkohan,

we'll take this a feature request and repot back when it's implemented.

**Comment by ambarc** [comment]
+1 to this feature request.

**Comment by johnflanagan-spok** [comment]
+1
Could this support also be added to the web socket connect methods?

**Comment by ambarc** [comment]
Btw - I tested custom authorizers over websockets with some modifications to the SDK code. Will see if I can get cycles to get a PR together.
