### ISSUE TITLE
[FeatureRequest] AWS SDK doc for Objective c

### ISSUE THREAD

**Issue by LekhaWiinnova** [aws-amplify/aws-sdk-ios#1118]
I am trying to implement user authentication with Amazon Cognito Federated Identities (Google sign in). I am using objective c language. Currently the doc is available only in swift language. So can you please share any doc in objective c language?

Available doc in swift language: https://aws-amplify.github.io/docs/ios/start

**Which AWS Services are you utilizing?**
Amazon Cognito Federated Identities

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 
 - Dependency Manager:  Cocoapods
 - Objective c

**Device Information (please complete the following information):**
 

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@LekhaWiinnova

Thank you for reporting to us. I will bring it our product team for prioritization. Will loop back once there is more information.

**Comment by LekhaWiinnova** [comment]
Thank you so much

**Comment by moeenahmad05** [comment]
is it available for Objective c or still not ?

**Comment by ukhan-amazon** [comment]
Closing due to priority given to Swift Documentation going forward.
