### ISSUE TITLE
Archive Validation Error: The bundle at AWSMobileClient.framework contains disallowed file 'Frameworks'.

### ISSUE THREAD

**Issue by cornr** [aws-amplify/aws-sdk-ios#1123]
**Describe the bug**
After updating from 2.6.18 to 2.7.3 we get following error when deploying to the app store.

> Invalid Bundle. The bundle at 'My.app/Frameworks/AWSMobileClient.framework' contains disallowed file 'Frameworks'.

**To Reproduce**
1. Use Carthage Setup as described in https://aws-amplify.github.io/docs/ios/manualsetup#carthage-setup (with carthage command:  carthage update --platform ios --cache-builds --no-use-binaries)
2. Upload to AppStore

**Which AWS service(s) are affected?**
AWSiOSSDKv2 2.7.x

**Expected behavior**
No Error from Appstore 😀
"AWSMobileClient.framework should not contain Frameworks directory."?

**Additional context**
I think this error results in embedding Swift Frameworks into AWSMobileClient.framework (since Swift code was introduced in 2.7). I wonder if this is necessary. Or do we have a project configuration error?

**Comment by palpatim** [comment]
It looks like we are setting the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` flag in the AWSMobileClient project. I'm testing to make sure our samples work as expected when we unset that, but I think that will be the fix.

**Comment by rohandubal** [comment]
Thanks for confirming @gokeji 

We are working on a fix and it will be fixed in a future release.

Thanks,
Rohan

**Comment by rohandubal** [comment]
Hello,

This issue is resolved in `2.7.4` SDK release. Please let us know if you continue to face issues.

Thanks,
Rohan
