### ISSUE TITLE
"NotAuthorizedException","message":"Incorrect username or password.

### ISSUE THREAD

**Issue by gaborcsontos** [aws-amplify/aws-sdk-ios#1124]
Hello.

I can register a new user, but when I would like to use the credentials(email and password)to login, it always fails and I get an error:
:"NotAuthorizedException","message":"Incorrect username or password.

I use the correct password and the email which I registered.
@muellerfr ?

Thanks.

**Comment by muellerfr** [comment]
Hi @gaborcsontos, can you please provide a code snippet?  Have you tried using our new AWSMobileClient? https://aws-amplify.github.io/docs/ios/authentication

**Comment by gaborcsontos** [comment]
Hi @muellerfr! Thanks man, its working properly now:) Cheers mate.
