### ISSUE TITLE
Possible to change AWSServiceManager defaultServiceConfiguration halfway through in app?

### ISSUE THREAD

**Issue by cheeyi** [aws-amplify/aws-sdk-ios#1125]
**State your question**
I see that the `defaultServiceConfiguration` property of AWSServiceManager can only be set once, but I'm trying to implement the ability to sign in and out of an AWSIoT MQTT session using different sets of credentials in the same app lifecycle and that requires me to tear down the old session and recreate a new certificate sometimes. This doesn't seem possible based on the fact that the `defaultServiceConfiguration` can only be set once.

Is there a way to be able to set the `defaultServiceConfiguration` property of AWSServiceManager more than once per app lifecycle? Or what is the best way to be able to use an instance of `AWSIoTManager.default()` to call `createKeysAndCertificate` with a different identity pool ID (and possibly other fields) than the previous session?

**Which AWS Services are you utilizing?**
- Cognito
- AWS IoT

**Provide code snippets (if applicable)**

```swift
func setupAWSIoT(identityPoolID: String, endpoint: String, topicName: String, regionType: AWSRegionType) {
    let credentialsProvider = AWSCognitoCredentialsProvider(regionType: regionType, identityPoolId: identityPoolID)
    guard let iotEndpoint = AWSEndpoint(urlString: endpoint),
        let awsIoTConfig = AWSServiceConfiguration(region: regionType, endpoint: iotEndpoint, credentialsProvider: credentialsProvider),
        let awsDefaultConfig = AWSServiceConfiguration(region: regionType, credentialsProvider: credentialsProvider) else {
            delegate?.awsSetupDidFail(error: "Failed to set up service configurations")
            return
    }
    AWSIoTDataManager.register(with: awsIoTConfig, forKey: iotDataManagerKey)
    AWSIoTData.register(with: awsIoTConfig, forKey: iotDataKey)

    // Here is where I try to set defaultServiceConfiguration with the user-provided credentials but this only works the first time
    AWSServiceManager.default()?.defaultServiceConfiguration = awsDefaultConfig

    // Generate certificate
    let iotManager = AWSIoTManager.default()
    let csrDictionary = ["commonName": "redacted",
                         "countryName": "United States",
                         "organizationName": "redacted",
                         "organizationalUnitName": "redacted"]
    iotManager?.createKeysAndCertificate(fromCsr: csrDictionary) { [unowned self] response in
        guard let response = response else {
            // ALWAYS fails here because the identity pool ID is from the old session
            self.delegate?.awsSetupDidFail(error: "Failed to generate certificate for policy named \(self.policyName). Please make sure you\'ve created the policy with this name correctly and have granted full IoT permissions to it from the AWS IoT console.")
            return
        }
        // Attach principal policy from response...
    }
}
```

**Environment(please complete the following information):**
 - SDK Version: 2.6.31
 - Dependency Manager: CocoaPods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone X
 - iOS Version: iOS 12.1
 - Specific to simulators: n/a

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by cheeyi** [comment]
I was able to fix this by registering a config with my AWSIoTManager instead of using `default()` on AWSIoTManager:

```swift
// Set
AWSIoTManager.register(with: awsDefaultConfig, forKey: iotManagerKey)
// Get
let iotManager = AWSIoTManager(forKey: iotManagerKey)
```

**Comment by palpatim** [comment]
Hi @cheeyi. Thanks for the update--that's what I would have suggested as well. :)
