### ISSUE TITLE
Missing API References for AWSMobileClient

### ISSUE THREAD

**Issue by kvasukib** [aws-amplify/aws-sdk-ios#1127]
The API Reference for `AWSMobileClient` is missing. https://aws-amplify.github.io/aws-sdk-ios/docs/reference/ should be updated with the API for `AWSMobileClient`

**Comment by rohandubal** [comment]
We should be using [`jazzy`](https://github.com/realm/jazzy) to generate docs for `AWSMobileClient`. We should be generating it for public methods for the class `AWSMobileClient`.

**Comment by minbi** [comment]
Verified with @sunchunqiang. Code is in place. Documentation will be released with next SDK release.

**Comment by minbi** [comment]
Documentation added in 2.8.2 release
