### ISSUE TITLE
[FeatureRequest] Getting jwt tokens when using user pools login with facebook/google

### ISSUE THREAD

**Issue by gasparuff** [aws-amplify/aws-sdk-ios#1128]
I have my AWS API Gateway configured so that is uses user pool authorization and not IAM. So it expects a valid JWT token in the request header. The question is - how can I get those tokens when the user logs in by using facebook or google? I have followed the tutorial on showing the login (https://aws-amplify.github.io/docs/ios/authentication) and I'm able to get valid jwt tokens by calling 
```
AWSMobileClient.sharedInstance().getTokens({ (tokens, error) in
    debugPrint("tokens: \(tokens?.idToken)")
})

```
but this only works when the user logs in with some username and password (not through fb or google)

I have implemented this previously in a different way, by using AWSCognitoAuth which just shows some html page and calls the app with a predefined scheme and passes some code, which then is used to fetch all the tokens... this worked, but I don't really like that way and would prefer using the AWS Mobile Client to handle everything for me (there are some other reasons for that as well, but those are not so relevant right now). What's the right way of doing this, without switching my API gateway to IAM Authorization? I have been digging through the documentation and must say that I'm a bit confused...

**Comment by palpatim** [comment]
Hi @gasparuff, can you confirm:

* What version of the SDK are you using?
* Are you using Amplify to provision & configure your backend, or is it manually configured?
* Via what mechanisms are you tying your UserPool to your API Gateway API?
* You mention that you're able to manually retrieve tokens if the user does login via username/password. Does that also imply that the API request work as expected?

In the meantime, I'm asking @rohandubal to weigh in here on the best way to accommodate this use case.

**Comment by gasparuff** [comment]
Hi @palpatim ,
as stated by the instructions on this page (https://aws-amplify.github.io/docs/ios/manualsetup), I have added all the dependencies into my podfile and installed all the pods.

_What version of the SDK are you using?_
all AWS libraries were pulled with version number 2.7.3.

_Are you using Amplify to provision & configure your backend, or is it manually configured?_
The backend is manually configured. We are currently running a test service on heroku to which the AWS API gateway forwards the requests.

_Via what mechanisms are you tying your UserPool to your API Gateway API?_
Not sure if I understand the question correctly - but I created a mobbilehub project in the aws dashboard, enabled facebook login and provided the fb app id. This also created a new userpool. After that, I downloaded the awsconfiguration.json and dropped it into my project and started with just the very simple and basic signin process like stated in the examples:

`    override func viewDidLoad() {
        super.viewDidLoad()
        
        AWSMobileClient.sharedInstance().initialize { (userState, error) in
            if let userState = userState {
                switch(userState){
                case .signedIn:
                    
                    DispatchQueue.main.async {
                        self.signInStateLabel.text = "Logged In"
                        AWSMobileClient.sharedInstance().getTokens({ (tokens, error) in
                            debugPrint("tokens: \(tokens?.idToken)")
                        })
                    }
                case .signedOut:
                    AWSMobileClient.sharedInstance().showSignIn(navigationController: self.navigationController!, { (userState, error) in
                        if(error == nil){       //Successful signin
                            DispatchQueue.main.async {
                                self.signInStateLabel.text = "Logged In"
                                AWSMobileClient.sharedInstance().getTokens({ (tokens, error) in
                                    debugPrint("tokens: \(tokens?.idToken)")
                                })
                            }
                        }
                    })
                default:
                    AWSMobileClient.sharedInstance().signOut()
                }
                
            } else if let error = error {
                print(error.localizedDescription)
            }
        }

        // Do any additional setup after loading the view, typically from a nib.
    }
`

_You mention that you're able to manually retrieve tokens if the user does login via username/password. Does that also imply that the API request work as expected?_
Yes, the request works perfectly in that case. 

The reason I don't get back tokens is because the `getTokens()` functions in AWSMobileClientExtensions.swift has the following check at the beginning: 
`
        if (self.federationProvider !=  .userPools) {
            completionHandler(nil, AWSMobileClientError.notSignedIn(message: "User is not signed in, please sign in to use this API."))
            return
        }
`

and this `self.federationProvider` is set to `oidcFederation`, that's why it just returns that error. But I was expecting that it's still a UserPools login, since I enabled the social login stuff on that exact UserPool.

Thanks for your reply :-)

**Comment by rohandubal** [comment]
Hello @gasparuff 

Sorry that you are having issues using the SDK. I understand the use-case you are trying to achieve. Unfortunately, this is currently not supported in `AWSMobileClient` and you will have to use `AWSCognioAuth`. 

I am taking this as a feature request to the team for prioritization. I will update this thread when I have more information.

Thanks,
Rohan

**Comment by gasparuff** [comment]
Hi @rohandubal 

thanks for your answer. I tried doing it with `AWSCognitoAuth` but then I had troubles using `AWSMobileClient` properly. It would be great to have this functionality added into `AWSMobileClient` :).

**Comment by lexakozakov** [comment]
any news? it's a blocker.

**Comment by royjit** [comment]
Getting token via getToken is currently supported in AWSMobileClient when signed in to social provider through Cognito User Pool. Closing this issue.
