### ISSUE TITLE
AWSCognitoAuth getSession memory leak

### ISSUE THREAD

**Issue by NiltiakSivad** [aws-amplify/aws-sdk-ios#1134]
**Describe the bug**
There is a memory leak when the `getSession` method is called.

**To Reproduce**
I originally was seeing the issue in my project, but isolated it using the Swift AWSCognito sample project found here: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample/Swift

1. Download the project and comment out all of the code in `ViewController.swift` other than the call to `getSession` in the `signInTapped` method (including commenting out the code in the callback). Also leave the call to `signInTapped` in `viewWillAppear` intact.
2. Use Instruments Leak inspector and run the project

It results in the following leaks: 

![image](https://user-images.githubusercontent.com/4063424/49316131-8d332f80-f4b5-11e8-9ff9-67901f5e343a.png)

**Which AWS service(s) are affected?**
AWSCognitoAuth

**Expected behavior**
There to be no memory leaks

**Environment(please complete the following information):**
 - SDK Version: 2.7.3
 - Dependency Manager: CocoaPods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhoneX
 - iOS Version: 12.1
 - Specific to simulators: Tested on both real device and simulator

**Comment by rohandubal** [comment]
Hello @NiltiakSivad 

Thanks for reporting this. I am looking into this issue.

**Comment by rohandubal** [comment]
Hello,

This issue is resolved in `2.7.4` SDK release. Please let us know if you continue to face issues.

Thanks,
Rohan
