### ISSUE TITLE
crash at  reateUploadSubTask:(AWSS3TransferUtilityMultiPartUploadTask *) transferUtilityMultiPartUploadTask                          subTask: (AWSS3TransferUtilityUploadSubTask *) subTask   startTransfer: (BOOL) startTransfer in uploadTaskWithRequest

### ISSUE THREAD

**Issue by rivkiG** [aws-amplify/aws-sdk-ios#1135]
hi,
I'm developing an app that was working well for me. I updated the SDK a month ago to 2.6.31  
my app uploads all the data from the phone to the AWS cloud. I use the S3TransferUtility class.
but when I run the app in the background after a while the app crashes and it crashes in the 
-(NSError *) createUploadSubTask:(AWSS3TransferUtilityMultiPartUploadTask *) transferUtilityMultiPartUploadTask  subTask: (AWSS3TransferUtilityUploadSubTask *) subTask  startTransfer: (BOOL) startTransfer in the uploadTaskWithRequest part and i get this error:
"Attempted to create a task in a session that has been invalidated"
do you have any idea what could be the problem?
thank you for your help

**Comment by cbommas** [comment]
@rivkiG 

Sorry to hear that you are running into issues. 

Can you check if you are calling the `removeS3TransferUtilityForKey` method on the TransferUtility anywhere within the app? If you are, please remove that and see if that resolves the crash. Please let me know how it goes.

**Comment by cbommas** [comment]
@rivkiG 

Closing this thread as I haven't heard back. Please feel free to reopen if you are still running into issues.
