### ISSUE TITLE
Add documentation tags on gh-pages for every release

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/aws-sdk-ios#1142]
We need to tag every API docs with tag which can be used for future reference. Previously when we did that it caused an issue with Carthage (Refer #1101 )

It was fixed by using a format 2.8.1_api_docs format as specified [here](https://github.com/aws-amplify/aws-sdk-ios/issues/1101#issuecomment-446794224)

We need to update the CircleCI script to do this when we release the docs.

**Comment by minbi** [comment]
The script has been added. Due to issues with the last release the job was not run automatically. Resolved with next release when the job runs.
