### ISSUE TITLE
Linker warning with bitcode enabled

### ISSUE THREAD

**Issue by KleMiX** [aws-amplify/aws-sdk-ios#1145]
**Describe the bug**
There is a linker warning when building with bitcode enabled - `Linker asked to preserve internal global: 'AWSPinpointSessionKey'`.
There are 2 `AWSPinpointSessionKey` strings in the project, one is static other one is not. Making both of them static, or making static one as extern fixes warning.

**To Reproduce**
Build AWSPinpoint with bitcode enabled.

**Which AWS service(s) are affected?**
AWSPinpoint

**Expected behavior**
No warnings should be generated.

**Environment(please complete the following information):**
 - SDK Version: 2.6.28
 - Dependency Manager: Cocoapods

**Comment by sunchunqiang** [comment]
Hi @KleMiX 
Thanks for your information and suggestion. We will check and fix the issue.

**Comment by sunchunqiang** [comment]
Hi @KleMiX

Did you get the warning when you build AWSPinpoint or build your project which uses AWSPinpoint?

**Comment by sunchunqiang** [comment]
Hi @KleMiX 
I still cannot reproduce the issue. Could you please provide a small sample project with which I can reproduce the issue?

**Comment by KleMiX** [comment]
Hi,
Never mind I guess, I wasn't able to reproduce it in a test project no matter what, tried to use configuration as close as possible. Still getting it in my project though.
