### ISSUE TITLE
Unable to cast AWSMobileClientError on singIn operations

### ISSUE THREAD

**Issue by alemarcon** [aws-amplify/aws-sdk-ios#1150]
When I try to login to my UserPool and i need to reset my account password, from the method singUp i receive an error, but i'm unable to cast this error. I only have a localizedDescription method that return this string "Error The operation couldn’t be completed (AWSMobileClient.AWSMobileClientError error 14.)"

**To Reproduce**
1. Select an user in a UserPool e put in state RESET_REQUIRED by requeste the password reset
2. Try to singIn with AWSMobileClient singIn method with the old password
3. Try to cast the error

**Which AWS service(s) are affected?**
AWS Cognito
AWS MobileClient

**Expected behavior**
I suppose to be able to cast the error to recognize what to do

**Environment(please complete the following information):**
 - SDK Version: 2.8.1
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 12.1
 - Specific to simulators: iPhone 7

Thanks 
Alessandro

**Comment by cbommas** [comment]
hello @alemarcon 

Can you post a code snippet to help debug this further.  An example of how to cast the error and inspect it for the type of error is shown here - https://github.com/aws-amplify/aws-sdk-ios/blob/335e4d82a641fdb9cdc84773bf115951e850b884/AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTests.swift#L81

**Comment by alemarcon** [comment]
Hello @cbommas i resolved my issue. It was my error. The cast works correctly. Many thanks and sorry for report this "false issue".

Alessandro
