### ISSUE TITLE
Support for building static library versions of the build

### ISSUE THREAD

**Issue by mobileben** [aws-amplify/aws-sdk-ios#1151]
**Which AWS Services is the feature request for?**
MobileAnalytics

**Is your feature request related to a problem? Please describe.**
it would be easier to manage what library dependencies are needed for size sensitive applications. If one includes all the frameworks, the frameworks are huge. 130MB+, which can easily push your app to be outside of the downloadable by WiFi size.

More preferred would be having static libs (.a) variants of the SDK as well. This would allow one to link up against them all, but only have the necessary parts linked.

**Describe the solution you'd like**
It would be great if building static libs was part of the build process.

**Describe alternatives you've considered**
I've just started looking at using this for analytics. However if sizing is an issue (the frameworks are larger than my game), I'll have to move on.

Note I do understand ... but have to test, that I only need to include the frameworks I need. However, I haven't found anything that describes the bare bones frameworks needed for certain configurations. This would be Nic to have.

**Additional context**

**Comment by mobileben** [comment]
Also note that I have have bitcode disabled in my game.

**Comment by cbommas** [comment]
@mobileben 

I will discuss this request with my team and post back on this thread. Also, I would recommend that you use AWSPinpoint instead of AWSMobileAnalytics. AWSPinpoint has been deprecated as of version 2.8.0

**Comment by mobileben** [comment]
@cbommas sorry for the late reply.

Would all I need is only the AWSPinpoint framework? Or are there other dependencies that are needed? This is one of the unfortunate things I'm finding with this SDK is that there isn't great documentation on what needs what. The number of frameworks built is pretty overwhelming. So if you are starting off, it makes it hard to onboard in a relatively short period of time.

**Comment by royjit** [comment]
The SDK is available as individual Cocoapods dependency as well as XCFrameworks. Hope this solves your issue.
