### ISSUE TITLE
Amazon Elastic Transcoder Usage

### ISSUE THREAD

**Issue by mrikh** [aws-amplify/aws-sdk-ios#1157]
I am looking for the functionality of being able to trim videos to a specific duration using the AWS SDK. For example lets say the video is of a length 20 seconds that i uploaded before to my bucket and i want to trim 2 seconds out of it at a later date. I was looking around the AWS products and the Amazon Elastic Transcoder seems to offer what i want as far as i can understand it. Am i correct in this?
([This](https://aws.amazon.com/about-aws/whats-new/2016/11/amazon-elastic-transcoder-adds-support-for-clip-stitching/) is the url that brought me here)

Additionally there seems to be no reference to the elastic transcoder usage in the iOS SDK. So the only way to integrate this functionality into the iOS application is by having it implemented on the server side? Like any reference/examples to an api call to implement the feature?

**Comment by minbi** [comment]
Hi @mrikh ,

We have not published an iOS SDK for that service. The AWS SDK for Java has published [aws-java-sdk-elastictranscoder](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-elastictranscoder) which you may look at for your server side.

I will mark this as a feature request and have our team evaluate this service.

**Comment by royjit** [comment]
Elastic transcoder is supported in the new AWS SDK for Swift - https://github.com/awslabs/aws-sdk-swift/ . Please take a look and see if the SDK handles your use case. Please note that the AWS SDK for Swift is currently in developer preview mode.
