### ISSUE TITLE
Support reinitialize SQLite(FMDB) file that used by KinesisRecorder.

### ISSUE THREAD

**Issue by r-plus** [aws-amplify/aws-sdk-ios#1161]
**Which AWS Services is the feature request for?**
Kinesis

**Is your feature request related to a problem? Please describe.**
Sometimes we encountered problem that is app using kinesis(data stream) could not save/send any string(application log string) In our production.
According to our investigation, error was always SQLite database file is malformed error(error code 11 is `SQLITE_CORRUPT`).
```
Error Domain=AWSFMDatabase Code=11 "database disk image is malformed" UserInfo={NSLocalizedDescription=database disk image is malformed}
```
Probably corrupt cause is application crash while read/write SQLite.

**Describe the solution you'd like**
In that case, we should delete SQLite file in application temporary directory that KinesisRecord using then restart application to recovery Kinesis back to work correctly.
We wrote that code to delete SQLite file for recovery but file path of SQLite used by Kinesis is not public so we hope that AWSKinesis framework provide method to delete SQLite file used by KinesisRecord instance and reinitialization(recreate SQLite file).

**Describe alternatives you've considered**
Change to public accessible(readonly) about file path of SQLite used by KinesisRecord instance.

Thanks.

**Comment by minbi** [comment]
Hi @r-plus ,

Thanks for reporting this issue. We will investigate and update this thread.

**Comment by muellerfr** [comment]
@r-plus, we released a fix for this. Please try out the latest SDK version.

**Comment by r-plus** [comment]
@muellerfr Hi, thanks for your report.

I just look recently change of `AWSAbstractKinesisRecorder.m` and `AWSKinesisRecorder.m` but there are only fixed typo on https://github.com/aws-amplify/aws-sdk-ios/commit/149e9f54d37a58cdd5a6f8f3f613c11449b52863#diff-2c1cb8bc0ef330fc22e27c486e1d7c44.

Where do you pointing fix for this issue?

**Comment by palpatim** [comment]
@r-plus I'm embarrassed to say that this was my fault: I incorrectly reported to @muellerfr that I had fixed it recently as part of https://github.com/aws-amplify/aws-sdk-ios/commit/149e9f54d37a58cdd5a6f8f3f613c11449b52863 which included a FMDB helper with expose a `serialDatabaseQueueWithPath` method. Unfortunately, I mis-remembered updating Kinesis to use that new method, but I had actually only done Pinpoint.

I will get a fix for this ready for the next release. Sorry again for the confusion!

**Comment by palpatim** [comment]
@r-plus We have released this fix on 2.9.6: https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.9.6

Please let us know if you continue to see problems.

**Comment by r-plus** [comment]
@palpatim ok, we reopen this issue if we see same problem after v2.9.6.

**Comment by r-plus** [comment]
Close.
