### ISSUE TITLE
Crash in AWSIoTManager importIdentity - Wrong Passphrase

### ISSUE THREAD

**Issue by aniketudeshmukh** [aws-amplify/aws-sdk-ios#1166]
When a wrong passphrase is supplied to importIdentity api, the app crashes.

**Comment by desokroshan** [comment]
@aniketudeshmukh Thanks for reporting the issue. Could you please share the stack trace?

**Comment by aniketudeshmukh** [comment]
Here it is:

[AWSIotCrash.txt](https://github.com/aws-amplify/aws-sdk-ios/files/2744176/AWSIotCrash.txt)

**Comment by desokroshan** [comment]
@aniketudeshmukh Thanks for stack trace. Apologies for the delay in response. I will try to reproduce the issue on my end and get back to you soon as I can.

**Comment by palpatim** [comment]
Released in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.12.7
