### ISSUE TITLE
Error uploading images to S3 with Cognito authentication

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/aws-sdk-ios#1168]
I am getting an error while uploading an image to S3 bucket. I have added auth followed by storage as per the documentation(https://aws-amplify.github.io/docs/ios/storage) but when I try to upload an image, I am receiving following error.

com.amazonaws.AWSServiceErrorDomain error 11.

This is in regards to an iOS app. Once the user is signed-in, I am using AWSS3TransferUtility.default() to get the instance which as per documentation, internally utilizes signed-in cognito Identity. I can see both auth and unauth role created by cli but not sure why I am still getting the error.

I am suspecting that the signed-user isn't getting proper role to upload the image. Any help is appreciated?

Here is code snippet:

let transferUtility = AWSS3TransferUtility.default()
        transferUtility.uploadUsingMultiPart(data:data,
                                             bucket: "uniquename",
                                             key: "fileName",
                                             contentType: "image/jpeg",
                                             expression: expression,
                                             completionHandler: completionHandler).continueWith {
                                                (task) -> AnyObject? in
                                                if let error = task.error {
                                                    print("Error: \(error.localizedDescription)")
                                                }
                                                
                                                if let _ = task.result {
                                                    // Do something with uploadTask.
                                                }
                                                return nil;

**Comment by desokroshan** [comment]
@rohit3d2003 As you correctly pointed out a particular user needs to know the identity Id of all the users to be able to access their images. The attached policy should be such that it allows all the users to list the files within `protected/<user-a-cognito-identity-id>` but only `user-a` can upload files to it.

**Comment by rohit3d2003** [comment]
@rohandubal - As mentioned earlier, I am able to upload the images now but with the same 'key', nothing comes back. There isn't any error, just the 'data' is nil. Any idea?

**Comment by desokroshan** [comment]
Can you please confirm from the console if the data was uploaded successfully in the folder?

**Comment by rohit3d2003** [comment]
After looking further, I am able to download the image now without making any change

**Comment by returnzer0** [comment]
@rohit3d2003 I am facing the same issue, do you mind sharing how you were able to upload the file? Thanks

**Comment by rohit3d2003** [comment]
@returnzer0 - Just make sure the bucket path is correct. In my case, I uploaded everything under 'public' with the role that logged-in user assumed. If you want to upload the image to private or protected, you need to know the user's identity Id.

**Comment by returnzer0** [comment]
Ok, awesome, I got it working. Thanks a lot!
