### ISSUE TITLE
Offline Mutation (optimistic update) transaction fails if performed before query

### ISSUE THREAD

**Issue by zigfreid5** [aws-amplify/aws-sdk-ios#1170]
Attempting to create an offline mutation fails if the query used for the transaction has not been used previously. This is troublesome for a "Create User" scenario.

**To Reproduce**
1. Attempt performing mutation with an optimistic update transaction that uses a query that has not been used previously
2. An error will be thrown stating "missing value"

**Expected behavior**
If data object does not exist for a query it should be created

**Environment(please complete the following information):**
 - AWSAppSync SDK Version : 2.8.0
 - AWSMobileClient SDK Version : 2.8.2
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Comment by desokroshan** [comment]
Migrated to [appsync-ios repo](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/149).
