### ISSUE TITLE
MissingAuthenticationToken when I use SNS and Cognito

### ISSUE THREAD

**Issue by dannySaron** [aws-amplify/aws-sdk-ios#1171]
Hello guys, I have a problem when, after get session from Cognito, I try to create an endpoint for SNS.

`static let manager = CognitoService()
    
    let serviceConfiguration : AWSServiceConfiguration = AWSServiceConfiguration(region: .EUWest1, credentialsProvider: nil)
    
    let cognitoConfiguration : AWSCognitoIdentityUserPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: "\(Bundle.main.infoDictionary.map { return $0[CognitoDictionaryKey.clientId.rawValue] as! String } ?? "")", clientSecret: nil, poolId: "\(Bundle.main.infoDictionary.map { return $0[CognitoDictionaryKey.poolId.rawValue] as! String } ?? "")")

    var awsUserPool : AWSCognitoIdentityUserPool?
    
    private(set) var currentUser : AWSCognitoIdentityUser?
    private(set) var currentUserSession : AWSCognitoIdentityUserSession?
    
    private var pswTmp: String?
    
    deinit {
        
    }
    
    override init() {
        super.init()
        
        AWSServiceManager.default().defaultServiceConfiguration = self.serviceConfiguration
        AWSCognitoIdentityUserPool.register(with: self.serviceConfiguration, userPoolConfiguration: self.cognitoConfiguration, forKey: "yape")
        AWSSNS.register(with: serviceConfiguration, forKey: "yape")
        
        self.awsUserPool = AWSCognitoIdentityUserPool.init(forKey: "yape")
        self.awsUserPool?.delegate = self
    }
    
    func login(email: String, password: String, completitionBlock: @escaping ((String?, String?, String?) -> ()), errorBlock: @escaping ((Error?) -> ())) {
        let emailAttr = AWSCognitoIdentityUserAttributeType()
        emailAttr?.name = "email"
        emailAttr?.value = email
        let user = self.awsUserPool?.getUser(email)
        self.currentUser = user
        
        // Having a user created we can now login with this credentials
        user?.getSession(email, password: password, validationData: [emailAttr!])
            .continueOnSuccessWith(block: { [weak self] (task) in
                guard let session = task.result, task.error == nil else {
                    debugPrint(task.error!)
                    return nil
                }
                self?.currentUser = user
                self?.currentUserSession = session
                
                UserHelper.saveEmail(email)
                UserHelper.savePassword(password)
                
                print("TOKEN: \(session.idToken?.tokenString ?? "No token received")")
                print("ACCESS: \(session.accessToken?.tokenString ?? "No token received")")
                print("REFRESH: \(session.refreshToken?.tokenString ?? "No token received")")

                let request = AWSSNSCreatePlatformEndpointInput()
                request?.token = "\(UserDefaults.standard.string(forKey: "deviceTokenForSNS") ?? "")"
                request?.platformApplicationArn = "\(Bundle.main.infoDictionary.map { return $0["SNS_ARN"] as! String } ?? "")"
                let SNS = AWSSNS.default()
                SNS.createPlatformEndpoint(request!).continueWith(executor: AWSExecutor.mainThread(), block: { (task: AWSTask!) -> AnyObject? in
                    if task.error != nil {
                        print("Error: \(String(describing: task.error))")
                    } else {
                        let createEndpointResponse = task.result! as AWSSNSCreateEndpointResponse
                        if let endpointArnForSNS = createEndpointResponse.endpointArn {
                            print("endpointArn: \(endpointArnForSNS)")
                            UserDefaults.standard.set(endpointArnForSNS, forKey: "endpointArnForSNS")
                        }
                    }
                    return nil
                })
                
                DispatchQueue.main.async {
                    completitionBlock(session.idToken?.tokenString, session.accessToken?.tokenString, session.refreshToken?.tokenString)
                }
                
                return nil
            }).continueWith { (task) -> Any? in
                guard task.error == nil else {
                    debugPrint(task.error!)
                
                    DispatchQueue.main.async {
                        errorBlock(task.error)
                    }
                    return nil
                }
                
                return nil
            }
    }`

`Error: Optional(Error Domain=com.amazonaws.AWSServiceErrorDomain Code=10 "(null)" UserInfo={Type=Sender, Message=Request is missing Authentication Token, Code=MissingAuthenticationToken, __text=(
    "\n    ",
    "\n    ",
    "\n    ",
    "\n  "
)})
`

What is Authentication Token? and where should I add it?

**Comment by desokroshan** [comment]
@dannySaron Thanks for reaching out. I will try to recreate the issue at my end and post an update on this thread.

**Comment by minbi** [comment]
Hi @dannySaron ,

The authentication token is missing because you are not passing in a credentials provider here:
`let serviceConfiguration : AWSServiceConfiguration = AWSServiceConfiguration(region: .EUWest1, credentialsProvider: nil)`

We would recommend you use [AWSMobileClient](https://aws-amplify.github.io/docs/ios/authentication) to handle the authentication token because it handles authentication steps that you are still missing.
