### ISSUE TITLE
AWS IoT SSL handshake fails (invalid certificate)

### ISSUE THREAD

**Issue by hotbott** [aws-amplify/aws-sdk-ios#1172]
**Describe the bug**
I'm receiving an SSL handshake error while connecting to an AWS IoT endpoint via a socket connection. Looks like the certificate for `*.iot.us-east-1.amazonaws.com` is not valid anymore. Starting from iOS 12.1.1, [Symantec was removed from the list of trusted certificate authorities](https://support.apple.com/en-us/HT208860).

**To Reproduce**
Connect to an AWS IoT endpoint using a web socket on an iOS 12.1.1+ device.

```objc
[_iotDataManager connectUsingWebSocketWithClientId:clientId
                              cleanSession:YES
                              statusCallback:nil]
```

**Which AWS service(s) are affected?**
AWS IoT

**Expected behavior**
Valid SSL certificate for `*.iot.us-east-1.amazonaws.com` is available.

**Screenshots**
<img width="880" alt="20190109-aws-ssl-error" src="https://user-images.githubusercontent.com/6315122/51042908-b6b79e80-15bd-11e9-87ba-462a81a1fb01.png">

**Environment(please complete the following information):**
 - SDK Version: 2.8.2
 - Dependency Manager: Carthage

**Device Information (please complete the following information):**
 - Device: iPhone X
 - iOS Version: 12.1.1
 - Simulator is not affected (latest version is iOS 12.1)

**Additional context**
Symantec is no longer a trusted CA on the iOS truststore
https://support.apple.com/en-us/HT208860

**Comment by cbommas** [comment]
@hotbott 

You will need to use the use an endpoint configured with a Amazon Trust Services certificate. In anticipation of this issue, AWS IOT has proactively configured this URL for you. You can get the update URL by going to the AWS Console->IoT Core ->Settings page. See the installation and configuration section of https://aws-amplify.github.io/docs/ios/pubsub for documentation on how to do this.

Also see https://github.com/aws-amplify/aws-sdk-ios/issues/1138 for more information on how other folks have solved this issue.

**Comment by hotbott** [comment]
@cbommas Thanks! Using the ATS enabled endpoint works!
