### ISSUE TITLE
S3TransferUtility: PHAssetResourceManager integration

### ISSUE THREAD

**Issue by vitalyster** [aws-amplify/aws-sdk-ios#1173]
**Which AWS Services is the feature request for?**
S3
**Is your feature request related to a problem? Please describe.**
I want to upload big video using `S3TransferUtility`. It provides `uploadFileUsingMultipart` and `uploadDataUsingMultipart` methods where I need to provide file URL (while Photos URLs are inaccessible for background tasks and I need to extract data to temporary directory) or full file content, and it will split file into multiple parts. It may need too much time before actual upload starts.
iOS provides `PHAssetResourceManager` API for asynchronous chunks requests to avoid waiting full asset extraction and it is easy to push these chunks to multipart S3 upload API.
**Describe the solution you'd like**
High-level solution: API method like `uploadAssetUsingMultipart` with `PHAsset` as parameter, which will use `PHAssetResourceManager` to feed chunks into multipart upload.

**Describe alternatives you've considered**
Low-level solution (~~which presents in AWS SDK for different languages~~ actually exists in `AWSS3Service`): `initiateMultipartUpload`, `uploadPart`, `completeMultipartUpload`

**Comment by muellerfr** [comment]
@vitalyster thank you for submitting the feature request. I will discuss with the team and we will update this issue thread when we have updates.

**Comment by oleg-moseyko** [comment]
any new?

**Comment by atierian** [comment]
Thanks for opening this feature request. We recommend using the Storage category in Amplify Swift going forward -- for more information, please visit https://docs.amplify.aws/swift/build-a-backend/storage/

If you'd like to see this feature added to Amplify Swift, please open a feature request here https://github.com/aws-amplify/amplify-swift

Thanks!
