### ISSUE TITLE
[Auth] Federated sign in with Cognito Identities

### ISSUE THREAD

**Issue by MinCheTsai** [aws-amplify/aws-sdk-ios#1177]
**State your question**
I want to use ```AWSMobileClient.sharedInstance().federatedSignIn()``` but I can't get any feedback
I have checked my cognito & facebook settings, it is correct running on the website software.
And I have setting the awsconfiguration.json and Info.plist follow with Amplify Authentication document.
Please let me know, what' is my lost? thank you.

**Which AWS Services are you utilizing?**
AWS Cognito

**Provide code snippets (if applicable)**

```swift
AWSMobileClient.sharedInstance().federatedSignIn(providerName: "com.softchef.dev", token: "my facebook app token") { (userState, error) in
    print("federatedSignIn facebook login", userState!, error)
    // Output: federatedSignIn facebook login signedIn nil
}
```

**Environment(please complete the following information):**
 - SDK Version: 2.8.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 11.4
 - Specific to simulators:

**Comment by palpatim** [comment]
Hi @MinCheTsai,

I'm going to let @rohandubal reply with a more authoritative followup, but in the meantime:

>  it is correct running on the website software

Do you mean, you're using the same configuration values in your `awsconfiguration.json` file as in your web application?

A couple of other questions:

1. Can you confirm that you are using CognitoIdentityPools to federate identities?
1. Can you confirm that you added the required [configuration data to add to your app's `Info.plist` file](https://aws-amplify.github.io/docs/ios/authentication#facebook-login-in-your-mobile-app)?

**Comment by rohandubal** [comment]
Hello @MinCheTsai 

The first obvious change which I can suggest in the code snippet is to change the provider name to `graph.facebook.com` since it is a facebook token. 

```swift
AWSMobileClient.sharedInstance().federatedSignIn(providerName: "graph.facebook.com", token: "my facebook app token") { (userState, error) in
    print("federatedSignIn facebook login", userState!, error)
    // Output: federatedSignIn facebook login signedIn nil
}
```

Other follow up question I have is:

- Q. Are you using developer authenticated identities?

**Comment by MinCheTsai** [comment]
> Hi @MinCheTsai,
> 
> I'm going to let @rohandubal reply with a more authoritative followup, but in the meantime:
> 
> > it is correct running on the website software
> 
> Do you mean, you're using the same configuration values in your `awsconfiguration.json` file as in your web application?
> 
> A couple of other questions:
> 
> 1. Can you confirm that you are using CognitoIdentityPools to federate identities?
> 2. Can you confirm that you added the required [configuration data to add to your app's `Info.plist` file](https://aws-amplify.github.io/docs/ios/authentication#facebook-login-in-your-mobile-app)?

1. Yes, I'm using CognitoIdentityPools for connect to AWS IoT, It's work.
2. My Info.plist has added
```
<key>FacebookAppID</key>
    <string>224182xxxxxx</string>
    <key>FacebookDisplayName</key>
    <string>Coral-Develop</string>
    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>fbapi</string>
        <string>fb-messenger-api</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
    </array>
    <!-- END OF FACEBOOK PLIST ENTRIES HERE -->
    <!-- ADD AN ENTRY TO CFBundleURLTypes for Facebook -->
    <!-- IF YOU DO NOT HAVE CFBundleURLTypes, YOU CAN COPY THE WHOLE BLOCK BELOW -->
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>fb2241826259xxxxxx</string>
            </array>
        </dict>
    </array>
```

About federated setting on AWS console, I'm only fill in the Cognito User Pool, not in the Cognito Identity Pool is correct?

**Comment by MinCheTsai** [comment]
> Hello @MinCheTsai
> 
> The first obvious change which I can suggest in the code snippet is to change the provider name to `graph.facebook.com` since it is a facebook token.
> 
> ```swift
> AWSMobileClient.sharedInstance().federatedSignIn(providerName: "graph.facebook.com", token: "my facebook app token") { (userState, error) in
>     print("federatedSignIn facebook login", userState!, error)
>     // Output: federatedSignIn facebook login signedIn nil
> }
> ```
> 
> Other follow up question I have is:
> 
> * Q. Are you using developer authenticated identities?
A. Yes, I has created facebook app on the developer.facebook.com

I changed the providerName to ```graph.facebook.com```, but still not resolve.
Then I add user state listener, ``` AWSMobileClient.sharedInstance().addUserStateListener(self) { (userState, info) in```
I can receive signedIn state when I call ``` AWSMobileClient.sharedInstance().federatedSignIn()```, but the simulator not popup any facebook auth confirm.

**Comment by rohandubal** [comment]
Hello @MinCheTsai 

I think I understand the issue. 

The `federatedSignIn` API is supposed to be used when you have a Facebook token already with you (from your own implementation.)

If you want to use a managed UI, I would recommend using our drop-in UI which manages the Facebook authentication for you. You can find the documentation for that here:

https://aws-amplify.github.io/docs/ios/authentication#drop-in-auth 
https://aws-amplify.github.io/docs/ios/authentication#facebook-login-in-your-mobile-app

Please let us know if this works for you.

Thanks,
Rohan

**Comment by josh-chai** [comment]
@rohandubal OK, I will try it before next 2 weeks, then report here. thanks.

**Comment by morrislwt** [comment]
Hi, I'm facing the same situation,

I've done the **info.plist** and **configuration.json** setting like above, 
When I call 
```
AWSMobileClient.sharedInstance().federatedSignIn(providerName: IdentityProvider.facebook.rawValue, token: "XXXXXXXX") { (userState, error) in
            print("federatedSignIn facebook login", userState!, error)
        }
    }
//get output: federatedSignIn facebook login signedIn nil
```
but didn't pop up Facebook sign in page, and also didn't create user.

I try to use **FBSDKLoginKit** 
```
FBSDKLoginManager().logIn(withReadPermissions: ["public_profile", "email"], from: self) { (result, error) in
            if error != nil {
                self.logger.log("Facebook login error",error)
            }else{
                
                self.logger.log("Facebook login result", result)
                self.fetchProfile()
                
            }
        }
```
It show pop up page and able to get user's profile and email when I click sign in via Facebook page.
but didn't create user in Cognito user pool.
I'm wondering is it possible to use `AWSMobileClient.sharedInstance().federatedSignIn` without Auth UI? 
Thank you very much.


**Environment(please complete the following information):**

- SDK Version: 2.8.4
- Dependency Manager: Cocoapods
- Swift Version : 4.2

**Device Information (please complete the following information):**

- Device: Simulator
- iOS Version: iOS 12.1
- Specific to simulators:

**Comment by MinCheTsai** [comment]
Hi @muellerfr
@morrislwt is my partner, he has feedback at 2 weeks ago, please help we, thank you.

**Comment by kvasukib** [comment]
@morrislwt @MinCheTsai Sorry for the delayed response. There appears to be some disconnect in the understanding of the `federatedSignIn` method.

1) `federatedSignIn`:  No Facebook Pop-up UI from AWS SDK.

Workflow by the SDK: Provide the Facebook Token to federatedSignIn -> Cognito Identity pool -> Identity Id and AWSCredentials

```swift
AWSMobileClient.sharedInstance().federatedSignIn(providerName: IdentityProvider.facebook.rawValue, token: "XXXXXXXX") { (userState, error) in
            print("federatedSignIn facebook login", userState!, error)
        }
    }
```

This method can be used when you manage the Facebook SignIn UI **yourself** using the `FBSDKLoginKit` and you have the JWT-Token of the user who is signed in with Facebook. 

`federatedSignIn` method will take the token you gave and federate it with `Amazon Cognito Identity Pool`. Tis means that you are federating the Facebook token with Amazon Cognito Federated Identities and obtain a Cognito Identity Id and AWSCredentials.

See: https://aws-amplify.github.io/docs/ios/authentication#federated-sign-in
Currently, the federation feature in the AWSMobileClient supports Cognito Identity Pools only.

2) Facebook Pop-up UI from AWS SDK

Workflow: Show Facebook Pop-up UI -> SignIn user -> Obtain a Facebook Token  -> federatedSignIn -> Cognito Identity pool -> Identity Id and AWSCredentials

If you want the AWS SDKs to show the pup-ui UI to the end-user to signin with Facebook, you can use the `drop-in` UI that `AWSMobileClient` offers using https://aws-amplify.github.io/docs/ios/authentication#drop-in-auth API as follows:

```swift
AWSMobileClient.sharedInstance().showSignIn(navigationController: self.navigationController!, { (signInState, error) in
    if let signInState = signInState {
        print("logged in!")
    } else {
        print("error logging in: \(error.localizedDescription)")
    }
})
```

When this method is executed, the end-user will be prompted with a Facebook SignIn UI if you have the necessary information about your Facebook app in `awsconfiguration.json` and `Info.plist`. Once the user is authenticated with Facebook, `AWSMobileClient` will federate the token received from Facebook and retrieve a Cognito Identity Id and AWSCredentials from Amazon Cognito Federated Identities.

**Remember that the above two flows don't use Amazon Cognito UserPools at this moment**

Are you looking to federate with Amazon Cognito UserPools?

**Comment by morrislwt** [comment]
Hi @kvasukib ,

I succeed to signup/login via facebook & google using AWSCognito and AWSMoblieClient,
thank you for your help.
here is my code hope can help someone had same situation
```
//Setup config here:
func socialLogin(_ option: IdentityProvider){
        var configuration: AWSCognitoAuthConfiguration?
        switch option {
        case .facebook:
            configuration = AWSCognitoAuthConfiguration(
                appClientId: "xxxxxxxxx",
                appClientSecret: nil,
                scopes: Set<String>(["openid","aws.cognito.signin.user.admin"]),
                signInRedirectUri: "myapp://",
                signOutRedirectUri: "myapp://",
                webDomain: "https://xxxxxxx.auth.eu-west-1.amazoncognito.com",
                identityProvider: "Facebook",
                idpIdentifier: nil,
                userPoolIdForEnablingASF: nil)
        case .google:
            configuration = AWSCognitoAuthConfiguration(
                appClientId: "179a8fm2dg02o2bnq3pdgrsi8k",
                appClientSecret: nil,
                scopes: Set<String>(["openid","aws.cognito.signin.user.admin"]),
                signInRedirectUri: "myapp://",
                signOutRedirectUri: "myapp://",
                webDomain: "https://coral-develop.auth.eu-west-1.amazoncognito.com",
                identityProvider: "Google",
                idpIdentifier: nil,
                userPoolIdForEnablingASF: nil)
        default:
            break
        }
```

//And call get session using AWSCognitoAuth sdk
```
AWSCognitoAuth.registerCognitoAuth(with: configuration!, forKey: "cognitoAuth")
        self.auth = AWSCognitoAuth(forKey: "cognitoAuth")
        self.auth?.delegate = self
            self.auth?.getSession { (session:AWSCognitoAuthUserSession?, error:Error?) in
            if(error != nil) {
                print((error! as NSError).userInfo["error"] as? String)
                AWSMobileClient.sharedInstance().signOut()
            }else {
                if let token = session?.accessToken {
                    AWSMobileClient.sharedInstance().federatedSignIn(providerName: option.rawValue, token: token.tokenString, completionHandler: { (state, error) in
                        if let state = state {
                            switch state {
                            case .signedIn:
                                self.dismiss(animated: true, completion: nil)
                            default:
                                break
                            }
                        } else if let error = error as? AWSMobileClientError {
                            self.logger.log(error)
                            switch(error) {
                            case .userNotFound(let message):
                                self.showMessageView(message, .error)
                            case .invalidParameter(let message):
                                self.showMessageView(message, .error)
                            case .notAuthorized(let message):
                                self.showMessageView(message, .error)
                            default:
                                break
                            }
                        }
                    })
                }
            }
        }
```

**Comment by muellerfr** [comment]
@morrislwt - thank you for the update, and happy to hear it's working for you. @MinCheTsai, can you take a look at responses provided @kvasukib and @morrislwt and let us know if this solves your issue?

**Comment by Marquis103** [comment]
@morrislwt Would you be willing to share your source code file?

**Comment by AngeloGiurano** [comment]
Hi @kvasukib I'm looking on how to federate with Amazon Cognito UserPools, moreover I'm looking on an official flow to how to create an user in an UserPool after using the `federatedSignIn` any ideas on it?

**Comment by kvasukib** [comment]
@AngeloGiurano Thank you for reporting to us. This issue is closed. Can you create a new issue with more information on what you are looking for? We can continue our conversation on the new issue.

**Comment by morrislwt** [comment]
Hi @Marquis103 
I post my source code [here](https://github.com/aws-amplify/aws-sdk-ios/issues/1177#issuecomment-464317503) 
using AWSCognitoAuth and AWSMobileClinet can create a user in cognito user pool,

make sure you give each login method detail such as Facebook / Google from info plist or code

```
@IBAction func facebookLogin(_ sender: UIButton) {
        socialLogin(.facebook)
    }
    
    
    @IBAction func googleLogin(_ sender: UIButton) {
        socialLogin(.google)
    }
    
    func socialLogin(_ option: IdentityProvider){
        var configuration: AWSCognitoAuthConfiguration?
        switch option {
        case .facebook:
            configuration = AWSCognitoAuthConfiguration(
                
                appClientId: appClientId,
                appClientSecret: nil,
                scopes: Set<String>(["openid","aws.cognito.signin.user.admin"]),
                signInRedirectUri: "myapp://",
                signOutRedirectUri: "myapp://",
                webDomain: webDomain,
                identityProvider: "Facebook",
                idpIdentifier: nil,
                userPoolIdForEnablingASF: nil)
        case .google:
            configuration = AWSCognitoAuthConfiguration(
                appClientId: appClientId,
                appClientSecret: nil,
                scopes: Set<String>(["openid","aws.cognito.signin.user.admin"]),
                signInRedirectUri: "myapp://",
                signOutRedirectUri: "myapp://",
                webDomain: webDomain,
                identityProvider: "Google",
                idpIdentifier: nil,
                userPoolIdForEnablingASF: nil)
        default:
            break
        }
        guard configuration != nil else { self.logger.log("config nil"); return }
        AWSCognitoAuth.registerCognitoAuth(with: configuration!, forKey: "cognitoAuth")
        self.auth = AWSCognitoAuth(forKey: "cognitoAuth")
        self.auth?.delegate = self
            self.auth?.getSession { (session:AWSCognitoAuthUserSession?, error:Error?) in
            if(error != nil) {
                AWSMobileClient.sharedInstance().signOut()
            }else {
                if let token = session?.accessToken {
                    AWSMobileClient.sharedInstance().federatedSignIn(providerName: option.rawValue, token: token.tokenString, completionHandler: { (state, error) in
                        if let state = state {
                            switch state {
                            case .signedIn:
                                self.dismiss(animated: true, completion: nil)
                            default:
                                break
                            }
                        } else if let error = error as? AWSMobileClientError {
                            self.logger.log(error)
                            switch(error) {
                            case .userNotFound(let message):
                                self.showMessageView(message, .error)
                            case .invalidParameter(let message):
                                self.showMessageView(message, .error)
                            case .notAuthorized(let message):
                                self.showMessageView(message, .error)
                            default:
                                break
                            }
                        }
                    })
                }
            }
        }
    }
```

also imlement this delegate 
```
extension SignInViewController: AWSCognitoAuthDelegate {
    func getViewController() -> UIViewController {
        return self
    }
}
```
Hope this can help you.
Thanks.

**Comment by Marquis103** [comment]
thanks @morrislwt

**Comment by AngeloGiurano** [comment]
Thanks @morrislwt however I'd like to point out this would work out just by using a custom UI, is there a way also if you use the Drop-In Auth UI?

**Comment by AngeloGiurano** [comment]
> @AngeloGiurano Thank you for reporting to us. This issue is closed. Can you create a new issue with more information on what you are looking for? We can continue our conversation on the new issue.

@kvasukib Done, the new issue is here https://github.com/aws-amplify/aws-sdk-ios/issues/1280

**Comment by morrislwt** [comment]
Hi @AngeloGiurano ,


I tried Drop-In Auth UI before, but not able to create a user in Cognito user pool.

Sorry.
