### ISSUE TITLE
Get other user's attributes by its id/username through AWSMobileClient

### ISSUE THREAD

**Issue by medvedNick** [aws-amplify/aws-sdk-ios#1179]
I'm making an iOS app using amplify. Auth is performed using Cognito, and the database is Appsync GraphQL.

There is a `Post` entity in the database, which has `userID` attribute got from Cognito. I'd like to show creator's info in that `Post` in app UI. For example, `username` and a few other attributes from Cognito user (like profile picture).

Is there any way I can achieve this? I do not see any methods to fetch other users details neither in `AWSMobileClient`, nor in `AWSCognitoIdentityUserPool`. Or should I create a separate entity `user` to be able to access it with AppSync?

I've created duplicate issue [here](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/154) since I do not know which is the better place to ask.

**Comment by dankuchler** [comment]
I do not see the getUserAttributes() API in the amplify documentation either.  In the unit tests it looks like there is an example of how to retrieve the user attributes from AWSMobileClient:

https://github.com/aws-amplify/aws-sdk-ios/blob/cf6611a407c6290f2bf12df69f98f34175ade80b/AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTests.swift#L206

**Comment by palpatim** [comment]
Closing this in favor of https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/154.
