### ISSUE TITLE
Ability to update a user attribute through Amplify iOS SDK (AWSMobileClient)

### ISSUE THREAD

**Issue by dankuchler** [aws-amplify/aws-sdk-ios#1182]
Within the Amplify AWSMobileClient iOS SDK unit tests I see an example for how to retrieve user attributes:

https://github.com/aws-amplify/aws-sdk-ios/blob/cf6611a407c6290f2bf12df69f98f34175ade80b/AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTests.swift#L206

In the Amplify iOS SDK documentation I see an example where the user attributes are provided as part of sign up:

https://aws-amplify.github.io/docs/ios/authentication#user-attributes

Is there any sample code or example for how you would update a user attribute through AWSMobileClient (for instance change a user attribute through a profile screen)?

**Comment by palpatim** [comment]
Hi @dankuchler,

You can use the `updateUserAttributes` method for that:

```swift
// Update attributes: one previously existing attribute and one new attribute
let newUserAttributes = [
    "custom:mutableStringAttr1": "new value for previously set attribute",
    "custom:mutableStringAttr2": "value for never-before-set attribute"
]

AWSMobileClient.sharedInstance().updateUserAttributes(attributeMap: newUserAttributes) { result, error in
    guard error == nil else {
        XCTFail("Received un-expected error: \(error.debugDescription)")
        return
    }

    // Result is expected to be an empty delivery details list
    guard let result = result else {
        XCTFail("updateUserAttributes result unexpectedly nil")
        return
    }
    XCTAssertEqual(result.count, 0)
}
```

I've added a test locally and it will be pushed in an upcoming release. Thanks for calling that out!

Hope this helps.
