### ISSUE TITLE
[WIP - Investigating] uploadUsingMultiPart stalls when running after a termination event after at least one previous completed upload

### ISSUE THREAD

**Issue by rromanchuk** [aws-amplify/aws-sdk-ios#1183]
**Describe the bug**
I'm picking up the crash below with increased velocity, i believe since the update to `2.8.2` https://github.com/aws-amplify/aws-sdk-ios/blob/master/CHANGELOG.md#282

```
Fatal Exception: NSInvalidArgumentException
Cannot read file at file:///var/mobile/Containers/Data/Application/84A1972F-5901-4360-AD58-FFD28647B943/Library/Caches/S3TransferUtility/2D541829-F904-4662-9960-4AAA9828728F
__InstrumentUploadTaskWithRequestFromFile_block_invoke
```

Full stack trace is here: https://gist.github.com/rromanchuk/f43cdd8badf93905b03681d4e68be147

**To Reproduce**
I have no known way to reproduce this myself yet, still investigating. Here is basically a full example of my usage https://gist.github.com/rromanchuk/56e102f06a22c55d54a2d073486a838d

 

**Which AWS service(s) are affected?**
S3TransferUtility, multiPartUpload with background support

**Expected behavior**
No crashy

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: i believe it started at `2.8.2`
 - Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
I don't see any specific trends related to a particular device or ios, various amounts of devices iphoneSE-XS, and various ios 12 versions

**Additional context**
I also faced a serious regression that was basically able to brick my app, it was extremely difficult to find and debug. It seems like there was a very subtle behavior change, that wrecked unfortunate havoc in my `handleForeground()` method. Below was the logic that regressed. From my frantic investigation i believe the regression happened to users either who resigned the app, or experienced a system dialogue that resigned. When the user posts, we put a blocking progress screen, when the app regained focus the pending upload would short circuit because the pending status was`AWSS3TransferUtilityTransferStatusType.completed` creating a mismatched animation. I added this hack, because in previous versions, it was launching the animation on completed uploads. This is most likely developer error, where my fix was actually introducing a bug, but it was very clear that some behavior changed, as the only change was the library. 

```swift
func handleForeground() {
        transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: C.AWS.transferUtilityIdentifier)
        if let multiPartUploadTasks = self.transferUtility?.getMultiPartUploadTasks().result, let uploads = multiPartUploadTasks as? [AWSS3TransferUtilityMultiPartUploadTask] {
            for upload in uploads {
                guard upload.status != AWSS3TransferUtilityTransferStatusType.completed else {
                    return
                }
                self.startAnimating()
                upload.setProgressBlock(progressBlock)
                upload.setCompletionHandler(completionBlock)
            }
        }
    }
```

I need to a lot more investigation, i've been busy putting out fire, as soon I can focus and do a deep dive I'll update this ticket. I just want to put it out there for signal if anyone else is experiencing this.

**Comment by rromanchuk** [comment]
I just noticed i'm also getting an increased number of 

```
Non-fatal: Error
Domain: com.amazonaws.AWSS3TransferUtilityErrorDomain Code: 2
closure #1 in closure #1 in UploadManager.init()
```

```
Message
Expected to send [5375539], but sent [132659] and there are no remaining parts. Failing transfer
nserror-code
2
nserror-domain
com.amazonaws.AWSS3TransferUtilityErrorDomain
```

Also, can you give me a little insight on how aws manages an unauthenticated cognito user? For example, is there anything the end user needs to know in terms of credential management besides the timeout. I'm under the assumption that calling `uploadUsingMultiPart` manages refreshing the token etc. Are there caveats we should know, for example, does credential management happen at the constructor `AWSS3TransferUtility.s3TransferUtility(forKey: C.AWS.transferUtilityIdentifier)`?

**Comment by cbommas** [comment]
@rromanchuk 
Sorry to hear that you are running into issues. Would it be possible for you to share details about how you are using the TransferUtility in your app ( how are you instantiating, are you doing anything on background vs. foreground etc)

On the question regarding `upload.status`, note that the status can take on any of the values specified in the `AWSS3TransferUtilityTransferStatusType` enum. #1047 has information that may be be useful for you.

**Comment by cbommas** [comment]
I noticed your gist link - I will look into that and post back here if I spot anything.

**Comment by cbommas** [comment]
From your gist, I can make a few suggestions
- you appear to be using the same completion handler and progress objects for all of your transfers. Not that it is a problem, but I am assuming you are maintaining a list of on going transfers somewhere and doing the mapping in your app
- in the handleground method ( I presume that this is being called everytime the app is transition to the foreground), you don't need to set the progress block or completion handler. Whatever was in place when the app went to the background will still be there, so you don't need to do that.
- In the completion block, check for the task.status value and then update the UI accordingly
- Credentials management: The transfer utility uses presigned URLs and those are valid for 50 minutes ( since you are using Cognito). If a transfer goes on for longer than 50 minutes, individual parts can fail due to invalid URLs. However those parts will be automatically retried, at which point the credentials will be refreshed.

For the crashes you are reporting, it will be great if you can provide information about how long the transfers take (typically) in your app, are the crashes happening after you upgrade the app etc.

Also, I will be happy to jump on a call with you early next week to help get these issues to resolution.

**Comment by rromanchuk** [comment]
@cbommas just for my own debugging purposes, what is the lifecycle of `AWSS3TransferUtilityMultiPartUploadTask` is it true that they stick around until the app is restarted?  Or is this an indication of a retain cycle?  I was also wondering, is there any way to probe a task in able to determine if completion blocks were already set? 

One very confusing thing i'm banging my head on, is if i'm running a build to my device, and rebuild, the subsequent upload will stall at `transferUtility.uploadUsingMultiPart`, as in, none of the callbacks are ever executed.  if I resign the app, and open it again, the task has a status of `AWSS3TransferUtilityTransferStatusInProgress`, and even, for good measure if I explicitly set callbacks, it remains in the status of `AWSS3TransferUtilityTransferStatusInProgress`

If I delete the app, and rebuild, no issues, only when rebuilding. This sounds oddly familiar to https://github.com/aws-amplify/aws-sdk-ios/issues/1047#issuecomment-427759262  What i'm concerned about is when a user updates the app. I have to research what the lifecycle events for that action, but starting to suspect that termination is canceling the NSURLSession, and it's putting my transfer client in a bad state, more alarming is that these tasks aren't reporting something sensible like `AWSS3TransferUtilityTransferStatusUnknown`

**Comment by rromanchuk** [comment]
OK, figured it out, although I was re-registering, i failed to actually instantiate `didFinishLaunchingWithOptions`

`let _ = AWSS3TransferUtility.s3TransferUtility(forKey: C.AWS.transferUtilityIdentifier)`

Here's the kicker, by failing to instantiate immediately, attempting to upload later, would consistently stall out. 

```swift
// Failing to fetch the transfer instance from didFinishLaunchingWithOptions, caused this to "stall out"
let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: C.AWS.transferUtilityIdentifier)
transferUtility.uploadUsingMultiPart() //redacted
```
The curious thing though is, I understand why instantiating the transfer object early for existing transfers is important, but i'm struggling to understand why a new upload would fail when it istself instantiates the transfer object, but just at a later time.  

I'm able to this consistently now, but I feel like i'm going looney. If it helps, i could attempt to make a reproducible project without so many moving parts to as a sanity test

**Comment by cbommas** [comment]
@rromanchuk 
Thanks for the multiple posts with the context. Here are some thoughts 
1) as your average file is 1MB, I would recommend that you switch to using non-multipart uploads. The minimum part size for multipart uploads is 5MB, it would be sub-optimal to use multipart uploads in your case.
2) The `AWSS3TransferUtilityMultiPartUploadTask` and `AWSS3TransferUtilityUploadTask` will stick around across app restarts as long they haven't reached a final/terminal status such as `completed` , `error`, `cancelled` or `Unknown`. Once it reaches a final status, it will still stick around in the current app instance, but will be gone after the app restarts.
3) You shouldn't need to instantiate the TransferUtility in the `didFinishLaunchingWithOptions` method. My suspicion is that the `register` method ( this is an async method) is not completed before the call to `s3TransferUtility(forKey: ...` method is executed. The `register` operation has a completionHandler that you can use to make sure the registration has completed and hasn't encountered errors.

**Comment by rromanchuk** [comment]
OK, so i just released an expedited review, thinking everything working smoothly, couldn't reproduce a single time.  Turns out I made things much worse. The problem definitely is happening to users who have recently updated/terminated the application. I changed the identifier of my TransferUtility, and i'm guessing that all existing users who updated had their transferutility get into this state.  

I have no idea how to reproduce it, but i'm getting many many many angry e-mails 

What's the best way i can add verbose logging around the backing `NSURLSession`? if TransferUtility is in a non functional state, my application needs to immediately abort(), right now i'm completely blind and users are basically telling each other to "restart your phone to fix" 

UPDATE: @cbommas just saw your update, the `async` registration call has to be the issue. Didn't even realize there was a signature with a callback option.  Is there any chance that something regressed where a developer fetching an instance of the transfer client before registration (with same id) would but put the session into an invalid state?

**Comment by rromanchuk** [comment]
Ahh this is probably the `Error` information i'm looking for. 

```swift
AWSS3TransferUtility.register(with: configuration!, transferUtilityConfiguration: tuConf, forKey: C.AWS.transferUtilityIdentifier) { (error) in
            
        }
```

**Comment by cbommas** [comment]
@rromanchuk 
If the call to fetch the instance happens before the registration call, I would expect the fetch to fail and result in a nil object. Calling an upload on that object should be a no-op and can appear to be stalled.

Also, can you share  details of the error that you are receiving from the register call?

**Comment by rromanchuk** [comment]
Ohh man, this is definitely going to lead to trouble for a swift developer.  

<img width="243" alt="screen shot 2019-01-21 at 11 35 34 am" src="https://user-images.githubusercontent.com/102188/51495350-d8a8e200-1d70-11e9-9461-8223ed6a4b1f.png">

Even with best intentions, after reading the amplify documentations, another swift developer on team could easily create a race condition, especially on re-launch after termination where the transfer instance may not be ready for use. This is especially true for someone using this https://aws-amplify.github.io/docs/ios/storage#manage-a-transfer-when-a-suspended-app-returns-to-the-foreground  Notice the the usage in of `transferUtility` and "When an app that has initiated a transfer becomes suspended and then returns to the foreground", this is a prime candidate for a race condition, and the implementor wouldn't know any better. 

```swift
let test = AWSS3TransferUtility.s3TransferUtility(forKey: C.AWS.transferUtilityIdentifier)
log.info("transferUtility: \(test)")
AWSS3TransferUtility.register(with: configuration!, transferUtilityConfiguration: tuConf, forKey: C.AWS.transferUtilityIdentifier) { (error) in
    guard error == nil else {
        log.error(error!)
        SparAnalytics.logError(error!)
        fatalError(error!.localizedDescription)
    }
    log.info("Registration of \(C.AWS.transferUtilityIdentifier) complete")
    let test = AWSS3TransferUtility.s3TransferUtility(forKey: C.AWS.transferUtilityIdentifier)
    log.info("transferUtility: \(test)")
}
```

```
11:31:17.837 💙 INFO AppDelegate.application():69 - transferUtility:
11:31:17.842 💙 INFO AppDelegate.application():76 - Registration of spar-upload-manager-sync complete
11:31:17.842 💙 INFO AppDelegate.application():78 - transferUtility: <fir_0x600001270180_AWSS3TransferUtility: 0x600001270180>
```

`AWSS3TransferUtility.s3TransferUtility(forKey: )` desperately needs a return value of `AWSS3TransferUtility?`

**Comment by rromanchuk** [comment]
I haven't been able to yet trigger an error within registration, which isn't surprising because i'm not able to reproduce the issue my users are reporting. My best guess of trying to reproduce would be some arrangement of these factors:

- Change of identifier string
- Existing AWSS3TransferUtilityMultiPartUploadTasks
- A race condition attempting to access a transferUtility when registration has not completed
- Some type of termination event which will cause `didFinishLaunchingWithOptions` to trigger async registration, which also causes running `didBecomeActive` delegate to be call, that attempts to call the transfer instance in attempt to to assign callbacks

**Comment by rromanchuk** [comment]
> If the call to fetch the instance happens before the registration call, I would expect the fetch to fail and result in a nil object. Calling an upload on that object should be a no-op and can appear to be stalled.

Yeah thats what makes this especially dangerous in swift, the no-op message to nil doesn't leave any indication, ...no completion or progress block is ever going to be ran, giving the developer no way to recover their interface. 

This definitely needs to be defined as nullable, `+ (nullable instancetype)S3TransferUtilityForKey:(NSString *)key;`  just explaining it isn't going to be enough as it's very anti-pattern in swift, and the compiler won't be able to offer any help.

**Comment by rromanchuk** [comment]
One thing i would recommend, is not allowing the completion block  to be optional on register. To be honest, i think any type of error here should absolutely throw. By allowing  execution to continue without being handled it doesn't make any sense to continue as we know any subsequent usage is going to be completely hosed. I'm pretty sure for some of my users case, register failed and everything  was swallowed (copy paste from getting started), and then again swallowed/obfuscated as i was unwillingly interacting with a transfer instance that either 1. hasn't finished initializing, 2. or failed initializing

The documentation on amplify shouldn't use this method
```swift
AWSS3TransferUtility.register(
    with: configuration!,
    transferUtilityConfiguration: tuConf,
    forKey: "transfer-utility-with-advanced-options"
)
```
- Not obvious it's async
- Not obvious that something bad could ever happen 
- Not obvious it's a wrapper around NSURLSession, and that if something did happen here, your app could end up in an unrecoverable state


And here is my best guess what our users were visually seeing. 

```swift
// ########################
// Very dangerous SDK
// ########################
UI.showThing()
let transfer: AWSS3TransferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: C.AWS.transferUtilityIdentifier) // -> AWSS3TransferUtility

transfer.upload() { (error) // <--- not only won't the callback return, upload was messaged to nil
  UI.hideThing()
}
// Now showThing is forever orphaned because someone broke a promise to me 😭
// It's very possible that register could have just completely failed, and this happily returns nil for the rest of its lifetime

// ########################
// Safe SDK
// ########################
UI.showThing()
let transfer: AWSS3TransferUtility? = AWSS3TransferUtility.s3TransferUtility(forKey: C.AWS.transferUtilityIdentifier) // -> AWSS3TransferUtility?

// This won't compile anymore, as it shouldnt
// transfer.upload() { (error) in
//   UI.hideThing()
// }

guard let transfer = transfer else {
  UI.hideThing()
  log.error("woahhhh this is actually really bad, and you probably really want to know about it. Either a race condition, or registration failed completely")
  return
}

transfer.upload() { (error) in
  UI.hideThing()
}
```

**Comment by cbommas** [comment]
@rromanchuk 
I see that you have created a PR for the documentation changes. I will work to get that merged into the repository.

Just so I am tracking this correctly, at this point it looks like you have been able to reproduce and confirm that the issue is due to the TransferUtility not being fully initialized before the upload is attempted. 

I understand the issue with the Swift semantics - I will get it addressed in an upcoming version of the SDK.

**Comment by rromanchuk** [comment]
@cbommas I have done a lot of cleanup, and have aborts in every place where things may go wrong, but have yet to trigger one. The thing that is really scaring me is,  i've had two two times where the upload stalled, where no aborts were triggered, `uploadUsingMultiPart` returned the task fine, but non of the callbacks were ever called, causing a similar situation users have reported. 

The problem is these were times where I wasn't closely paying attention, but i'm pretty sure they were when i was doing something disruptive. For example, when i switch between branches to update them from upstream, or switch over to a new device. What concerns me, this also seems to be something in common with the users who have been inflicted by this. 

Is there something unique about a binary update (a literal change in the build number?) vs other types of events? 

 I think you are tracking this correctly, but my concern is those were actually secondary issues disguised as the same bug. When things are normal starting from first launch, i have battle tested every edge case under the sun and everything is fine. 

I just forked and going to do some lower level debugging. https://github.com/rromanchuk/aws-sdk-ios/pull/1

Boy oh boy, i do **not** like this behavior. 😡😡😡
```objective-c
+ (instancetype)S3TransferUtilityForKey:(NSString *)key {
    @synchronized(self) {
        AWSS3TransferUtility *serviceClient = [_serviceClients objectForKey:key];
        if (serviceClient) {
            return serviceClient;
        }
        
        AWSServiceInfo *serviceInfo = [[AWSInfo defaultAWSInfo] serviceInfo:AWSInfoS3TransferUtility
                                                                     forKey:key];
        if (serviceInfo) {
            AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:serviceInfo.region
                                                                    credentialsProvider:serviceInfo.cognitoCredentialsProvider];
            
            NSNumber *accelerateModeEnabled = [serviceInfo.infoDictionary valueForKey:@"AccelerateModeEnabled"];
            AWSS3TransferUtilityConfiguration *transferUtilityConfiguration = [AWSS3TransferUtilityConfiguration new];
            transferUtilityConfiguration.accelerateModeEnabled = [accelerateModeEnabled boolValue];
            
            [AWSS3TransferUtility registerS3TransferUtilityWithConfiguration:serviceConfiguration
                                                transferUtilityConfiguration:transferUtilityConfiguration
                                                                      forKey:key];
        }
        
        return [_serviceClients objectForKey:key];
    }
}
```

**Comment by rromanchuk** [comment]
Ok I was just able to reproduce
1. After successful upload i swipe up to terminate
2. I relaunch 

```
2019-01-21 19:06:11:362 SPAR[904:374492] In Recovery for TU Session [com.amazonaws.AWSS3TransferUtility.Default.Identifier.spar-upload-manager-sync]
2019-01-21 19:06:11:390 SPAR[904:374492] Found MultiPartUpload [C5A9FB5D-2751-4133-BAC7-BDD342CF188D] with Multipart ID [dt9mxs1eNYt61u8v1s7PaTHzUo.EWTQACZH9UERm68VLp0mXEmwtMU8yEqzcEc21vAR8MbBw6nSrwL8DXM791zm2xYom2cgH9Ou07IOc9Su3xQOOMAxa2.XZTDBLe8CgAwXhaL0yMQ.DwvViD.hhX_Y_bPN6x4R_ViCUNVdbFac-] and status [1]
2019-01-21 19:06:11:390 SPAR[904:374492] Found MultiPartUpload SubTask [C5A9FB5D-2751-4133-BAC7-BDD342CF188D] with taskNumber [1] and status [3]
2019-01-21 19:06:11:395 SPAR[904:374584] Multipart transfer status is [1]
19:06:11.417 💙 INFO SparUploadManager.init():73 - Registration of spar-upload-manager-sync complete
```

I then submit a new upload and i get this

```
2019-01-21 19:10:02:963 SPAR[904:374492] File size is 975939
2019-01-21 19:10:02:963 SPAR[904:374492] Number of parts is 1
19:10:03.016 💙 INFO CheckInPreviewViewController.submit():99 - currentAWSTask Optional(<AWSTask: 0x28380c400; completed = NO; cancelled = NO; faulted = NO;>), result: nil
2019-01-21 19:10:04:000 SPAR[904:375109] Added task [0] to inProgress list
2019-01-21 19:10:04:011 SPAR[904:375109] Starting subTask 0
```

No callbacks occur, and and stuck with loading screen

**Comment by rromanchuk** [comment]
Looks like completed multiparts are having their status flags accidentally reset  inProgress or they were never updated. One thing that immediately comes to mind is if ios does directory cleanup, maybe it was never flushed to the db or something?

On relaunch this is odd,  it finds a task
```
2019-01-21 19:06:11:390 SPAR[904:374492] Found MultiPartUpload SubTask [C5A9FB5D-2751-4133-BAC7-BDD342CF188D] with taskNumber [1] and status [3]
2019-01-21 19:06:11:395 SPAR[904:374584] Multipart transfer status is [1]
```

**Comment by rromanchuk** [comment]
OK, i think i should have trusted my intuition more on this one. 

Given
- Users started reporting these, with the only change being a library update
- The size of the diff related to the exact same parts of the service i'm using https://github.com/aws-amplify/aws-sdk-ios/commit/cf6611a407c6290f2bf12df69f98f34175ade80b#diff-cb56d2828510f3a582e6e6ef63b32331
-   The complexity and specificity of the steps to reproduce. Requires existing completed tasks, a termination event, and then subsequent uploads

With the velocity of reports coming from existing everyday users around update events i'm going to aucoms razor this and assume there is in fact a regression from the changecommit above. I'm going to remove multipart support for now and get an emergency fix and then come back to this later, before i go any more crazy hahaha.

**Comment by cbommas** [comment]
@rromanchuk 

Sorry to hear about the trouble that you are going through on this. Appreciate you keeping me abreast - to your point, looks like there is a very specific set of circumstances that need to happen for this issue to occur. I haven't been able to reproduce this at all in my local testing so far, but I will continue to investigate and dig through the code. 

In your case, given that the average file size is around 1 MB, going away from Multipart uploads is the right choice, even in the long term, as the advantages of multi part upload only kicks in once you go beyond 5 MB

**Comment by rromanchuk** [comment]
@cbommas i think i have a pretty good handle on it now. I need to take a break, but i'll get you an example project soon. Funny thing is, it's about **how** you run in it to get it in this state.. the cruel thing is, it sets itself up in way that will probably only hit your most active users. 

Silver lining is that almost everything above is just a lot of noise.

**Comment by rromanchuk** [comment]
@cbommas sorry to keep harassing you, a one more question.

As a thought experiment, imagine you were uploading in an adversarial environment. Do you know how atomic `uploadUsingMultiPart:fileURL` vs `uploadUsingMultiPart:Data` is? Imagine you were handed a file URL that could only be considered valid until you lost scope. Imagine a scenario where any random time after uploading, after your stack is popped, another developer wipes the directory, ios purges `Application_Home/Library/Cache`. Just from casual observing it looks like the file method will use the file as is, where data creates and manages the files under aws's own namespace. 

I took a crack at making a reproducible project https://github.com/rromanchuk/aws-sdk-ios-samples/pull/1  I'm purposely being as reckless as possible, i was able to consistently reproduce for a while, changed something, and now can't reproduce at all.  I'm thinking through all the potential vectors that are making this feel non deterministic. Race conditions, thread confinement abuse,  spelling errors and all the other usual trappings. 

I wouldn't worry about this until I can get you something reproducible that doesn't require a rain dace. I can confirm though, after ditching multiPart i have not once been able to reproduce in production project.

**Comment by cbommas** [comment]
@rromanchuk 
Good to hear that by moving to non-multipart downloads, you are having a more stable solution. Also good to hear your comment on the silver lining - I will continue to try to reproduce the issue on my side ( will look forward to getting your sample/repro steps)

Regarding the question on the thought experiment, the upload methods are very far from being atomic. All the uploads are done via a NSURL Background session, in a separate process that is independent of the app process. NSURL Background sessions always require a file for upload, so the `uploadUsingMultiPart:Data` will create temporary files as required.

Also, each `part` of the `multipart` request will have its own temporary file. So if you have a file of 12 MB that needs to be uploaded, internally the logic will break it up into 3 parts, each having its own temporary file, increasing the number of failure points in this adversarial environment. If the underlying temporary files ( or the file to be transferred) are deleted in this adversarial environment, I would expect the upload to fail. That said, I would expect the _failure to be contained_ i.e., the failure would be limited to this upload - future uploads may succeed or fail independent of this, based on their prevailing environment conditions.

**Comment by rromanchuk** [comment]
closing until i have a reproducible proj
