### ISSUE TITLE
Can someone tell me the exact IAM JSON policy for an Unauthenticated cognito role to use every possible Pinpoint service

### ISSUE THREAD

**Issue by rromanchuk** [aws-amplify/aws-sdk-ios#1189]
I don't use amplify-cli. I'm looking for a policy that allows complete functionality for the entire pinpoint suite in context of a mobile user, for any mobile property under my account. Basically when i turn on logging, I never want to see Access denied ever again for at least a year 😁😁 For some reason, wildcards don't work. I have it working now (IAM console yelling at me for breaking a bunch of rules), but i have literally no idea what i'm doing anymore, i just don't want to spend another minute with this. 

https://docs.aws.amazon.com/mobileanalytics/latest/ug/migrate-sdk.html

https://github.com/aws-amplify/docs/issues/296

https://github.com/aws-amplify/amplify-js/issues/1759

Also, how can i get rid of this
Message=Exceeded maximum endpoint per user count 10, responseDataSize=57, NSLocalizedFailureReason=BadRequestException}

Any active device should get priority over any other endpoint, i definitely don't want to managing this myself.

**Comment by kvasukib** [comment]
@rromanchuk Sorry for the inconvenience caused. What is the version of AWS SDK for iOS you are using?

1) For the issue related to the IAM policies, if you are submitting events using `submitEvents` method which internally does a `PutEvents` operation and if you are updating endpoint, you require the following policies attached to the IAM role.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:UpdateEndpoint",
                "mobiletargeting:PutEvents"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:*:${accountID}:apps/${appId}*"
            ]
        }
    ]
}
```

We will update the amplify/docs to reflect this change.

2) For the issue related to "Exceeded maximum endpoint per user count 10", this is a limit enforced by the Pinpoint service. You cannot have more than 10 unique endpoints per user ID. See [Pinpoint service limits](https://docs.aws.amazon.com/pinpoint/latest/developerguide/limits.html#limits-endpoint) for more details.

**Comment by rromanchuk** [comment]
Is pinpoint using SNS behind the scenes? It has to be right? 

Developers have a product. That product has users. Those users interact with the product on devices. Depending on the user, and the devices the user interacts with, I can communicate with that user across a variety of channels. APN, GCM, SMS, and e-mail. 

Here's my dream ios SDK
```swift
Pinpoint.setup() // in AppDelegate, swizzle and and handle notifications, creates apn "endpoint"

Pinpoint.trackEvent() // Anywhere, get out of the developer's way

// Sometime after authentication
Pinpoint.setIdentifiers(email: currentUser.email, phone: currentUser.phone) // creates email/phone "endpoints" 
// For segmenting on console
Pinpoint.addAttribute(["science", "politics", "travel"], forKey: "interests")
```

**Comment by kawells924** [comment]
@rromanchuk you're not alone in your feedback, well stated. just don't want to spend cycles on what segment, etc. have long ago solved.

**Comment by kvasukib** [comment]
@rromanchuk @kawells924 Sorry for the inconvenience caused. I'm summarizing your concerns and my answers here:

1) Issue with setting policies in the IAM console: By `arn:aws:mobiletargeting:*:${accountID}:apps/${appId}*` I mean you would substitute the accountId and appId with the actual identifiers you have.

2) Pinpoint's bigger picture. Yes, you are right. Pinpoint provides many functionalities under one roof `Amazon Pinpoint`. 
**Action Item:** I can extend our docs to provide additional details about what an endpoint represent and the programming model with the concept of endpoint. Meanwhile I would suggest looking at the [docs](https://docs.aws.amazon.com/pinpoint/latest/apireference/rest-api-endpoints.html). 

In short, An endpoint uniquely identifies a mobile device, email address, or phone number that can receive a message. You can use this resource to create or update endpoints. An endpoint has certain properties associated with it such as: User, Demographic, Location, etc. From an SDK perspective, it corresponds to the `AWSPinpointEndpointProfile`(https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSPinpoint/AWSPinpointEndpointProfile.h) which encapsulates all the information related to an endpoint. You can call `updateEndpoint` API in the SDK to update any changes to the endpoint information.

3) A single user Id cannot be associated with more than 10 endpoints. If you are running your app on different emulators, you might have reached this limit easily. If you encountered this issue while testing on different emulators, I would suggest you to remove the endpoints either through the SDK or AWS CLI.

If this issue occurred in production to one of your users, can you provide additional details on how you set the userId in the `endpointProfile`.

4) Documentation: I understand that our docs talk about the introductory use-cases and detailed API reference.

**Action Item:** Add docs for advanced use-cases. Can you provide the list of use-cases you would like to see the docs for?

I have two action items from this issue and I will work on that.

**Comment by kvasukib** [comment]
@rromanchuk Please let me know if you need any further information.

**Comment by zoellner** [comment]
Can someone explain how adding `mobiletargeting:UpdateEndpoint` isn't an issue where one user coudl update the endpoint of another user? Wouldn't that statement need some sort of condition to limit the endpoints to the ones of the submitting user?

**Comment by RickvdP** [comment]
> Can someone explain how adding `mobiletargeting:UpdateEndpoint` isn't an issue where one user coudl update the endpoint of another user? Wouldn't that statement need some sort of condition to limit the endpoints to the ones of the submitting user?

While attack surface is probably small (hard to guess a GUID) a +1 for an AWS answer to this? Any reason why this is not an issue? Any way to conditionally limit update access to only user-owned endpoints?
