### ISSUE TITLE
Login to Cognito through Username/Password, Facebook and Google

### ISSUE THREAD

**Issue by n1schal** [aws-amplify/aws-sdk-ios#1191]
Hi.

I'm sorry if my approach is totally wrong or if I'm even doing things the right way, but here's what I have until now: 

I'm currently developing an app with Swift and the app needs to let users sign in through three different modes:

a. Username/Password
b. Facebook
c. Google

I checked out the CognitoYourUserPools sample app, updated values with my AWS User Pool settings,and I was able to Sign Up, Login and do the basics. I was also able to obtain the id token and access token through the user.getSession method, which is required by my server to further handle AWS usage (the guy developing the server side of things says these two are required)

I have successfully implemented Facebook & Google setup and implemented the logins for both platforms and received corresponding tokens. 

I now want to pass the tokens to Cognito and get the access token and id tokens for logins through Facebook and Google. After taking a look at some of the AWS docs and SO questions, what I did was  this: 

```
func awsSignInFacebook(fbAuthToken: String){
        let logins = ["graph.facebook.com" : fbAuthToken]
        let customIdentityProvider = CustomIdentityProvider(tokens: logins)
        
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .APSouth1, identityPoolId: AWSConstants.CognitoFederatedIdentityUserPoolId, identityProviderManager: customIdentityProvider)
        
        let configuration = AWSServiceConfiguration(region: .APSouth1, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        credentialsProvider.getIdentityId().continueWith { (task: AWSTask!) -> AnyObject? in
            
            if (task.error != nil) {
                print("Error: " + (task.error?.localizedDescription)!)
                
            } else {
                // the task result will contain the identity id
                let cognitoId = task.result
                Log.add(info: "Cognito ID : \(cognitoId)")
            }
            return nil
        }
    }
```

```
class CustomIdentityProvider: NSObject, AWSIdentityProviderManager {
    var tokens : [String : String]?
    
    init(tokens: [String : String]) {
        self.tokens = tokens
    }
    
    @objc func logins() -> AWSTask<NSDictionary> {
        return AWSTask(result: tokens! as NSDictionary)
    }
}
```

through which I get corresponding cognito Id for the user.

Is there any way that I can now proceed with getting access token and the id token through the Cognito id that is returned to me from the above call? Or is this approach wrong?

Taking a look at the CognitoAuth sample app, clicking on Sign In takes me to the hosted UI, and upon completion of login through Facebook/Google I can get the id token and access token but this isn't how the client prefers to let the users login to the application (needs to be through a native login screen with facebook/google buttons and username/password field)

So my query is, is there a way that I can use a *similar* flow where logins through username/password, facebook and google return me the id token and access token without using the hosted UI? Also, can my feature request be met if I used the AWSMobileClient instead?

I'm hoping to be pointed to the right direction as I haven't done much development within the AWS ecosystem and if necessary, would also like to suggest changes on the server side development if our approach is completely off track.

Thanks in advance!

**Which AWS Services are you utilizing?**
AWS Cognito

**Environment(please complete the following information):**
 - SDK Version: Latest
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: iPhone XS
 - iOS Version: iOS 12.1
 - Specific to simulators: No

**Comment by n1schal** [comment]
I'll check this out today and let you know what happens! Thanks!

**Comment by cbommas** [comment]
@n1schal 
Thank you for letting me know. I will close this issue - Please don't hesitate to reach back if you run into any other problems using the `AWSMobileClient` and open a new issue if required.

**Comment by n1schal** [comment]
@cbommas 

So I tried configuring things through AWS Amplify and then used AWSMobileClient to do what I was looking to do, but I noticed through federated sign in, I don't get tokens but rather get credentials which has an access key, but no id token.

If I do use the drop-in UI to facilitate the social sign ins, will I get the id token or will i still be returned the credentials?

**Comment by mohaumpoti** [comment]
Hey @n1schal! The sample code you provided in your question, that retrieves an identityId from a Cognito identity Pool saved my life! I couldn't make it work for the life of me. Thanks!

**Comment by balashivashankar-Diatoz** [comment]
am getting this error 

Use of unresolved identifier 'AWSConstants'


can any one slove this..?

**Comment by KosalaFMF** [comment]
@mohaumpoti how to continue login process with retrieved identityId?

**Comment by KosalaFMF** [comment]
How to get accessToken After getting identity id

**Comment by dcristolovean** [comment]
old question, but still actual.  I have apps using the new AWSMobileClient but also old apps with  AWSCognitoCredentialsProvider.
I need the accessToken to send it to the server so it allows user deletion.

How can I get the access token with the old AWSCognitoCredentialsProvider method ?
