### ISSUE TITLE
The Pinpoint AppId is nil.

### ISSUE THREAD

**Issue by vijjuk** [aws-amplify/aws-sdk-ios#1194]
I am getting the error. while using pinpoint - *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The Pinpoint AppId is nil. You need to configure it in awsconfiguration.json or Info.plist before using this method.'

I have awsconfiguration.json in the target and also has the "PinpointAnalytics": {
"Default": {
"AppId": "f6f5cc63467e4e2f83aba08f6a2dce44",
"Region": "us-east-1"
}
},

this is SUPER frustrating..can somebody tell me what is wrong

I created everything as per the documentation using amplify CLI

**Comment by cbommas** [comment]
@vijjuk 

Sorry to hear that you are running into issue using the SDK.
Just so that I have all the data on my side, can you provide the versions of the amplifyCLI and SDK you are using?

**Comment by kvasukib** [comment]
@vijjuk Sorry for the inconvenience caused. I suspect one of the following could happen.

1) Are you using Pinpoint for a) Analytics only b) Targeting only c) Both Analytics & Targeting? If you intend to use TargetingClient, you need a snippet under `PinpointTargeting`.
```
PinpointTargeting": {
  "Default": {
    "AppId": "f6f5cc63467e4e2f83aba08f6a2dce44",
    "Region": "us-east-1"
  }
}
```

2) When you added the `awsconfiguration.json` file in your iOS app, did you add it to the XCode Project? This exception occurs when the file is not added to the XCode target.

**Comment by jc-delvalle** [comment]
For some still having the issue:

awsconfiguration.json must also have this:
```

    "IdentityManager": {
      "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
              "PoolId": "xxxx",
              "Region": "us-xx-1"
            }
        }
    },
```
