### ISSUE TITLE
AWSMobileClient AWSUserPoolSignUpViewController Cognito Phone Number Format +1

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-ios#1201]
**Which AWS Services is the feature request for?**
AWSMobileClient AWSUserPoolSignUpViewController Cognito, Phone number format and validation (+1) returned by cognito sign up.

**Is your feature request related to a problem? Please describe.**
Real users do not know how to enter a phone number using the sign up UI. 

The app I have in production receives poor reviews and frequent complaints about the sign up process due to the misunderstanding and difficulty in entering +1 before a phone number. Many people in my app's demographic are from the US and do not understand an international phone number format (they may not be use to entering international numbers). Entering a plus on some devices when a number pad is displayed on the phone as the keyboard is also cumbersome. 

Here is a real review: "I’d like to use this app but I can’t even make an account it is saying my phone number is incorrect and coming up with a bunch of errors when making a password, username etc."

**Describe the solution you'd like**
Do not require a +1 before US phone numbers. 
Provide a way for developers to customize or override default error validation messages.

Please make this a priority along with any related sign-up validation issues prior reported. Any app developed using the sign up UI will have this real-world problem, especially for users in the United States. Thank you.

**Comment by cbommas** [comment]
Linking to the open RFC for Auth related requests #1158

**Comment by BillBunting** [comment]
@cbommas Any update ? estimate when available ?

**Comment by BillBunting** [comment]
I have since moved away from allowing users to create new username/password Cognito Identity Pool based accounts. Our users experienced too many issues with the Drop-in AWSAuthUI user experience. Our app still allows existing users to sign-in with usernames/passwords, but directs new users to sign-in with Apple, Google, or Facebook using the respective native experience supported by the Drip-in UI. Our app dates back to MobileHub and uses the MobileClient Drop-in UI (not the hosted UI). Everything is still working well with the current version os AWS API (2.27.7) for how we are using it.
