### ISSUE TITLE
AWSMobileClient custom auth challenge ?

### ISSUE THREAD

**Issue by ryancrunchi** [aws-amplify/aws-sdk-ios#1204]
**State your question**
Is it possible to use custom auth challenge with AWSMobileClient for signin and signup functions ?

**Which AWS Services are you utilizing?**
Cognito, S3

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.8.4
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Comment by sunchunqiang** [comment]
Hi @ryancrunchi ,  AWSMobileClient does not support custom custom authentication challenge up to now.

**Comment by ryancrunchi** [comment]
Hello, thanks for your support.

I already have implemented custom auth with `AWSCognitoIdentityProvider`. But I find the new `AWSMobileClient` much easier to use.
I found interactive auth is too much interferring on how we built our view controllers flows, and AWSMobileClient would get rid of this. But I require custom auth, so I will leave my implementation as is waiting for more features on AWSMobileClient.
Thank you.

**Comment by Can-Sahin** [comment]
@rohandubal @ryancrunchi Hi.

I am also stuck with the 'passwordless' authentication, meaning custom auth challenges. In js it's so simple but `AWSMobileClient` doesn't support it yet. Can you share some code about doing it `AWSCognitoIdentityProvider`. Or any guide ? 

Thanks.

**Comment by juliogarcia93** [comment]
Hi @rohandubal and @ryancrunchi,

I too am interested in such functionality. I agree with Ryan in that the AWSMobileClient is much easier to use and that it would be nice if the API client had a way of initializing a Custom Auth flow and allow us to work with the cognito lambda triggers nicely. Is there any plan for something like this in the future? I'd be happy to help with any PR's needed

**Comment by james-ff** [comment]
Would very much be for this feature too

**Comment by mato2593** [comment]
Hi @rohandubal 

Is this possible following this guide? https://aws-amplify.github.io/docs/ios/authentication#customizing-authentication-flow

**Comment by royjit** [comment]
Hi @mato2593 
Custom auth is currently supported in `AWSMobileClient` as documented above. Sorry for not updating this issue when we released it.

**Comment by hossamghareeb** [comment]
@royjit if I want to use `AWSMobileClient` for custom auth, I had to put `"authenticationFlowType": "CUSTOM_AUTH"` in the awsconfiguration.json file. However, doing this messes up the normal (non custom) authentication with username and password. Do you know how can we support both?

**Comment by hossamghareeb** [comment]
to whom it may concern. you can use 
```
let pool = AWSCognitoIdentityUserPool.default()
pool.isCustomAuth = true
```
to set custom auth programatically
