### ISSUE TITLE
AWS Cognito iOS - InvalidIdentityPoolConfigurationException on sign in, but works after app restart

### ISSUE THREAD

**Issue by thomers** [aws-amplify/aws-sdk-ios#1206]
I'm developing on iOS, using the AWS SDK 2.8.4, Xcode 10.1, on Simulator running iOS 12.1

I'm using the AWSAuthUI with email/password.

Without any changes that I'm aware of, I now get this weird, 100% reproducable behavior:

Trying to sign in with email/password (with an existing user/password, on the correct pool)  fails with this error:

> Error: Error Domain=com.amazonaws.AWSCognitoCredentialsProviderErrorDomain Code=2 "GetCredentialsForIdentity keeps failing. Clearing identityId did not help. Please check your Amazon Cognito Identity configuration." UserInfo={NSLocalizedDescription=GetCredentialsForIdentity keeps failing. Clearing identityId did not help. Please check your Amazon Cognito Identity configuration.}

But when I restart my app, `[[AWSSignInManager sharedInstance] isLoggedIn]` is `true`  and I'm signed in automatically.

The awsconfiguration.json has been downloaded from AWS Mobile Hub.

This is the IAM role (default, also created by AWS Mobile Hub):

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "cognito-identity:GetId"
                ],
                "Resource": [
                    "arn:aws:cognito-identity:*:*:identityPool/us-xxxxx-x:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                ]
            }
        ]
    }

So if the Sign In did work, why do I get this error? Thanks for any hint.

**Comment by sunchunqiang** [comment]
Hi @thomers Can you provide some code snip so that we can reproduce your issue?

**Comment by thomers** [comment]
Hi @sunchunqiang - I'm just using the AuthUI screens. All I'm doing is calling

	if (![[AWSSignInManager sharedInstance] isLoggedIn]) {
		[AWSAuthUIViewController presentViewControllerWithUIViewController:self configuration:authUIConfig completionHandler:^(id<AWSSignInProvider>  _Nonnull signInProvider, NSError * _Nullable error) {
      // etc
     }

What I discovered is that the problem only appears in my "prod" configuration. For the "dev" configuration, everything works as intended.

I checked the "Auth" and "Unauth" IAM roles for both the "dev" identity pool (that is working) and the "prod" identity pool and made sure they are exactly the same. Also, I double checked that the correct roles are set as "Unauthenticed role" and "AUthenticated role" in the "Edit identity pool" page.

Under "Authentication providers", the "User Pool ID" and "App client id" values are also set correctly.

Again, the problem is: With the "prod" config, Sign in initially fails, but when I restart the app, the correct credentials are fetched from the keychain (?) and I'm logged in. When I sign out, and try to sign in again, the same thing happens (and I can restart again).

BTW, I noticed I get a slightly different error message now: 

> Error: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=5 "(null)" UserInfo={__type=InvalidIdentityPoolConfigurationException, message=Invalid identity pool configuration. Check assigned IAM roles for this pool.}

**What else can I check and which configuration values can I compare between those 2 configurations?**

**Comment by rohandubal** [comment]
Hello @thomers 

I think I understand this issue. This error is thrown when the `UserPool` provider for `IdentityPool` is incorrectly configured. Which means that the `UserPool` sign-in (email password sign in) is successful, but the federation with `CognitoIdentityPool`  (which helps get AWS Credentials) is unsuccessful. 

To fix this issue, you need to go to you `Cognito Federated Identities` settings in console and make sure the `CognitoUserPool ID` is provided correctly.

Also FYI, we have recently launched `AWSMobileClient` with auth feature supports which makes it simple to use these typical auth flows. You can find the documentation [here](https://aws-amplify.github.io/docs/ios/authentication). The flow which you are using is an older flow and is replaced by `AWSMobileClient`.

Thanks,
Rohan

**Comment by thomers** [comment]
Hello @rohandubal , thanks for the answer.

from what I can tell, the CognitoUserPool ID is specified correctly - but maybe I'm overlooking something?

<img width="1174" alt="screen shot 2019-02-11 at 15 18 48" src="https://user-images.githubusercontent.com/453568/52569133-c28ebe80-2e10-11e9-9449-120d93ce9694.png">
<img width="1250" alt="screen shot 2019-02-11 at 15 15 11" src="https://user-images.githubusercontent.com/453568/52569152-ccb0bd00-2e10-11e9-93b8-eae8324069a4.png">
<img width="1318" alt="screen shot 2019-02-11 at 15 15 01" src="https://user-images.githubusercontent.com/453568/52569201-e520d780-2e10-11e9-9a6d-d60cf850da1a.png">

What am I missing?

Thanks, 
Thomas

PS: Thanks for the tip to use AWSMobileClient, I will update my code.

**Comment by thomers** [comment]
Interestingly, the update to use the new AWSMobileClient mysteriously fixed the error message.

To make sure I'm using it correctly - what's the "legacy mode" in AWSMobileClient, and under which circumstances should I be using it / not be using it?

**Comment by thomers** [comment]
Note: I posted a follow-up problem/question here: https://github.com/aws-amplify/aws-sdk-ios/issues/1235 

Still fighting with the proper configuration, but this specific issue can be closed.

**Comment by svsharsha** [comment]
Hello,
Im an IOS developer and I INTEGRATED AWS through cocoapods.
Sometimes I get below errors while downloading content from AWS S3.Please help me out.
1. com.amazonaws.AWSCognitoCredentialsProviderErrorDomain Code=4 
2. com.amazonaws.AWSS3TransferUtilityErrorDomain error 2.
3. com.amazonaws.AWSS3ErrorDomain Code=0
etc.

thanks.
