### ISSUE TITLE
Ability to delete a cognito user through the Amplify iOS SDK (AWSMobileClient)

### ISSUE THREAD

**Issue by dankuchler** [aws-amplify/aws-sdk-ios#1207]
Is there a way for a user to delete themselves from AWS Cognito through the Amplify iOS SDK (AWSMobileClient)?  Reviewing the Amplify iOS SDK documentation and unit tests for AWSMobileClient I wasn't seeing the right way to accomplish this. 

**Which AWS Services are you utilizing?**

AWS Cognito
AWS Amplify iOS SDK

**Environment:**
 - SDK Version: 2.8.4
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Comment by sunchunqiang** [comment]
Hi @dankuchler  Do you mean delete  users themselves from AWS Cognito user pool?

**Comment by dankuchler** [comment]
Yes @sunchunqiang .  If the user decides they no longer want to use an application and wants to delete their user account from AWS Cognito - is there a way in the Amplify iOS SDK (AWSMobileClient) to delete a user from the cognito user pool.

**Comment by rohandubal** [comment]
Thanks for the information @dankuchler 

Unfortunately, `AWSMobileClient` currently does not support the `deleteUser` flow. There is however, an alternative path which you can use. 

The `AWSCognitoIdentityProvider` SDK supports this feature which you can leverage. You can use the following method:

```swift
        AWSCognitoIdentityUserPool.default().currentUser()?.delete().continueWith(block: { (task) -> Any? in
            if let error = task.error {
                print("Error deleting user: \(error.localizedDescription)")
            }
            if let _ = task.result {
                print("User deleted successfully.")
            }
            return nil
        })
```

To support this feature in `AWSMobileClient` I am taking it as feature request to the team. I will provide an update here if/ when it is available.

Thanks,
Rohan

**Comment by dankuchler** [comment]
It is unclear to me what feedback was being requseted.  The last comment on the request seems to indicate that it was being classified as a feature request.  I do not see any open questions, so I'm not sure what feedback was being requested.  In the future please clearly indicate what feedback is being requested.

**Comment by shaikhshoeb** [comment]
AWSCognitoIdentityUserPool.default().currentUser()?.delete().continueWith(block: { (task) -> Any? in
            if let error = task.error {
                print("Error deleting user: \(error.localizedDescription)")
            }
            if let _ = task.result {
                print("User deleted successfully.")
            }
            return nil
        })


This code does not delete user from cognito user pool

**Comment by cyrillelegrand** [comment]
Re-opened as https://github.com/aws-amplify/aws-sdk-ios/issues/3824 because it will be mandatory starting jan. 31, 2022, as per Apple's annoucement.

**Comment by cyrillelegrand** [comment]
Release 2.26.7 from today solves this, confirmed working.
