### ISSUE TITLE
How should I assign user attributes and user id with existing endpoint using pinpoint SDK?

### ISSUE THREAD

**Issue by rohitkowadkar** [aws-amplify/aws-sdk-ios#1212]
**How should I assign user attributes and user id with existing endpoint using pinpoint SDK?**

**PinPoint SDK**

**Need similar functionality in iOS SDK as stated in following code snippet which is in JAVA**
https://github.com/awsdocs/amazon-pinpoint-developer-guide/blob/master/doc-source/endpoints.md

**Environment :**
 - SDK Version: 2.8.4
- Dependency Manager: Cocoapods
 - Swift Version : [e.g. 4.0]

**Comment by rohandubal** [comment]
Hello @rohitkowadkar 

You can use methods which include [`currentEndpointProfile`](https://github.com/aws-amplify/aws-sdk-ios/blob/6ab2982040eaca984eab38e311b98c3b9227b773/AWSPinpoint/AWSPinpointTargetingClient.h#L28), [`updateEndpointProfile`](https://github.com/aws-amplify/aws-sdk-ios/blob/6ab2982040eaca984eab38e311b98c3b9227b773/AWSPinpoint/AWSPinpointTargetingClient.h#L33) and the [`Endpoint Profile attributes`](https://github.com/aws-amplify/aws-sdk-ios/blob/6ab2982040eaca984eab38e311b98c3b9227b773/AWSPinpoint/AWSPinpointEndpointProfile.h#L26) to achieve your use-case.

Hope this helps,
Rohan

**Comment by rohitkowadkar** [comment]
@rohandubal thanks for your response I have achieved assigning user by following method call
`AWSPinpointTargeting.default().updateEndpoint(ENDPOINTREQUEST)`
