### ISSUE TITLE
AWS AppSync on a regular interval e.g. every 30 minutes

### ISSUE THREAD

**Issue by aslam-unikove** [aws-amplify/aws-sdk-ios#1214]
**Describe the bug**

**To Reproduce**

**Which AWS service(s) are affected?**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**

**Comment by palpatim** [comment]
@aslam-unikove 

It looks like you may have filed this by mistake--there are no details beyond the content of the bug template. Can you edit the issue to provide details or close this issue if you filed it by mistake?

Also, if this is related to AppSync, please file it on our AppSync issues page: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/

Cheers.
