### ISSUE TITLE
App Sync in ObjC project

### ISSUE THREAD

**Issue by edfinegan** [aws-amplify/aws-sdk-ios#1215]
**State your question**
I'm unable to get an ObjC project to see the Swift classes that are part of AWSAppSync. I'm installing the framework via Cocoapods. I'm able to get the sample project working from the documentation if I do it in Swift. If I try to make the same project in ObjC after using "@import AWSAppSync;" I'm only able to reference the symbols defined in a .h from my ObjC code. Am I missing an import statement?

For example, I get "Use of undeclared identifier" when referencing AWSAppSyncClient. However I can reference AWSAppSyncClientVersionNumber since it is defined in a .h and not .Swift file.

**Which AWS Services are you utilizing?**
AWSAppSync
AWSCore

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
2.9.0

 - Dependency Manager: [e.g. Cocoapods, Carthage]
Cocoapods

**Comment by rohandubal** [comment]
Hello @edfinegan 

AppSync is currently only supported in Swift. It uses swift constructs like `structs` which are not visible to ObjC and is the reason why you see those errors. You will have to use Swift to use the AppSync SDK.

Thanks,
Rohan
