### ISSUE TITLE
Document awsconfiguration.json format and usage

### ISSUE THREAD

**Issue by leandrodemarco** [aws-amplify/aws-sdk-ios#1216]
**State your question**
I'm trying to report analytics events using pinpoint. Only analytics, no targeting, nor nothing extra.
I'm not using amplify CLI, I've got the Pinpoint project setup via console in browser; I also have the App Client set up in a Cognito User Pool. 

However, when application launches It complains and crashes:

> The Pinpoint AppId is nil. You need to configure it in `awsconfiguration.json` or `Info.plist` before using this method. 

I can't find anywhere how the plist or the json should look. I tried adding this to my Info.plist:

```	
<key>PinpointAnalytics</key>
<dict>
	<key>Default</key>
	<dict>
		<key>AppId</key>
		<string>mypinpoint_project_ID</string>
		<key>Region</key>
		<string>us-east-1</string>
	</dict>
</dict>
```
but get the same result
**Which AWS Services are you utilizing?**
Pinpoint

**Provide code snippets (if applicable)**
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    // Setup AWS Pinpoint
    let pinpointConfiguration = AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions)

    // Create AWSMobileClient to connect with AWS
    AWSMobileClient.sharedInstance().initialize { userState, error in
        if let error = error {
            print("Error initializing AWSMobileClient: \(error.localizedDescription)")
        }
    }
    return true
 }
```

**Environment(please complete the following information):**
 - SDK Version: 2.8.4
 - Dependency Manager: Carthage
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 6s
 - iOS Version: iOS 12.1

**Comment by rohandubal** [comment]
Hello @leandrodemarco 

Sorry that you are having issues using the SDK. For the code snippet which you are using, you will need to use an `awsconfiguration.json` file. It should look like this:

```json
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-west-2:xxxxxxxxxxx-7c8b-425f-91c9-xxxxxxxxxxx",
                "Region": "us-west-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-west-2_XXXX",
            "AppClientId": "xxxxxxxxxxx",
            "AppClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Region": "us-west-2"
        }
    },
    "PinpointAnalytics": {
        "Default": {
            "AppId": "YOUR_PINPOINT_APP_ID",
            "Region": "us-east-1"
        }
    },
    "PinpointTargeting": {
        "Default": {
            "Region": "us-east-1"
        }
    }
}
```

I will try to document this better in our documentation.

Hope this helps,
Rohan

**Comment by leandrodemarco** [comment]
Hello @rohandubal. Thanks a lot, it worked :) I believe that perhaps adding to documentation this would ease things, but that's a personal opinion.

**Comment by returnzer0** [comment]
@leandrodemarco Did this work for you? I am facing the same issue and my json is correct.

**Comment by returnzer0** [comment]
@rohandubal what if you only have a cognito user pool and not using an identity pool then could one remove the CognitoIdentity fields?

**Comment by kvasukib** [comment]
@returnzer0 Sorry for the delayed response.

You are right. If you are not using the Cognito Identity Pool, you could remove it from the `awsconfiguration.json`. 

Are you using Amplify CLI for generating the `awsconfiguration.json` or are you hand-writing the fie yourself based on the resources you created from your AWS account.

**Comment by returnzer0** [comment]
Hey @kvasukib, no worries.

I am using cloudformation templates to create all of the resources and then I create the `awsconfiguration.json` file using a script (so yes, manually).

**Comment by kvasukib** [comment]
@returnzer0 Sorry for the delayed response. I have created an issue in our aws-amplify/docs repo and this issue will be tracked there. 

Ref: https://github.com/aws-amplify/docs/issues/735

Thank you for your patience.
