### ISSUE TITLE
AWSMobileClient failed in signIn method

### ISSUE THREAD

**Issue by erickfox** [aws-amplify/aws-sdk-ios#1219]
**Describe the bug**
When I try to log in using the SignIn method with user and password, this method has an error: _Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value._, in structure: SessionToken and line: 429.

**To Reproduce**
1. call signIn method
2. See error

**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**
That the authentication process is done

**Snippet**
`AWSMobileClient.sharedInstance().signIn(username: "someuser", password: "somepassword") { (signInResult, error) in`

**Environment(please complete the following information):**
 - SDK Version: 2.8.4
 - Dependency Manager:  Cocoapods
 - Swift Version: 4.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 12.1
 - Specific to simulators: iPhone 8 Plus

**Comment by rohandubal** [comment]
Hello @erickfox 

Sorry that you are having issues using the SDK. To help me debug this, could you provide some additional info? 

- Do you have a standard UserPools setup in the backend?
- If not, can you please provide details of a custom setup?
- Could you please show how do the contents of your `awsconfiguration.json` look like? I want to ensure you have the correct constants in it. It should look something like this:

```json
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-west-2:xxxxxxxxxxx-7c8b-425f-91c9-xxxxxxxxxxx",
                "Region": "us-west-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-west-2_XXXX",
            "AppClientId": "xxxxxxxxxxx",
            "AppClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Region": "us-west-2"
        }
    },
    "PinpointAnalytics": {
        "Default": {
            "AppId": "YOUR_PINPOINT_APP_ID",
            "Region": "us-east-1"
        }
    },
    "PinpointTargeting": {
        "Default": {
            "Region": "us-east-1"
        }
    }
}
```

Thanks,
Rohan

**Comment by erickfox** [comment]
Hello @rohandubal, I checked my settings, I configured again and now everything works well, I think it could be bad settings in my project. Thanks a lot
