### ISSUE TITLE
When is it safe to call getIdentityId() after Cognito authentication?

### ISSUE THREAD

**Issue by JLau-cy** [aws-amplify/aws-sdk-ios#1221]
**State your question**
I am using `AWSCognitoIdentityPasswordAuthentication` for Cognito authentication.

I would like to know when is it appropriate to call `getIdentityId()`? I tried calling it in the `AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails>` `continueWith` block when it succeeds. However I noticed that the userPool.currentUser() is still nil at this point which causes the `getIdentityId()` function of the credentials provider to do nothing.

If I add a delay of 2 seconds before calling `getIdentityId()` in the same block, then it works.

My question is which callback actually indicates a sign in success so I know when I can call other authenticated APIs such as 'getIdentityId()'?

**Which AWS Services are you utilizing?**
AWSCognitoIdentityProvider

**Code snippet**
```        
passwordAuthenticationCompletionSource?.task.continueWith { task in
            guard task.error == nil else {
                completionHandler(.error(task.error!))
                return nil
            }

           // Without this delay, the following task will never return.
           // With the delay it returns the identityId
            DispatchQueue.global().asyncAfter(deadline: DispatchTime.now() + 2) {
                self.cognitoCredentialsProvider.getIdentityId().continueWith { task in
                    guard task.error == nil else {
                        completionHandler(.error(task.error!))
                        return nil
                    }

                    completionHandler(.success(.signedIn))
                    return nil
                }
            }
            return nil
        }
```

**Environment(please complete the following information):**
 - SDK Version: 2.8.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: all
 - iOS Version: 12.0

**Comment by rohandubal** [comment]
Hello @JLau-cy 

The right time to call getIdentityId() would be after you get a successful session callback which has the `idToken` and `refreshToken`, since they are required to get the `identityId`. The tokens from Cognito User Pools are used by Cognito Identity service to issue Identity ID and AWS Credentials.

Thanks,
Rohan

**Comment by JLau-cy** [comment]
@rohandubal Thanks for the response.

Can you elaborate on how I will know when I have a successful session callback?

I tried calling `getSession()` in the same block, but since userPool.currentUser() returns nil in that block `getSession()` does nothing. Do I have to call getSession on repeat until it returns something?

Are there no notifications or other delegate functions that indicates successful sign in after a passwordAuthentication?

I need the identityId before I can let the user proceed to the next step.

Kind regards
Jeff Lau

**Comment by rohandubal** [comment]
Hello @JLau-cy 

The `getSession` callback would be the place where once you get a callback and the session is not `nil` you are assured that the tokens are available and `getIdentityId` would not fail.

Thanks,
Rohan
