### ISSUE TITLE
Please use Semantic Versioning

### ISSUE THREAD

**Issue by doctorcolinsmith** [aws-amplify/aws-sdk-ios#1225]
Please consider moving to semantic versioning (https://semver.org) for AWS Amplify.  This will make it easier to understand what updates are bug fixes, additions, or breaking changes.  Many popular dependency tool chains (such as Cocoapods and Swift Package Manager) assume semantic versioning as the default behaviour.

In the absence of semantic versioning, clear documentation on your versioning scheme at https://aws-amplify.github.io/docs/ios/start is essential.  Currently there does not appear to be any such documentation.

I recently got a broken build because I thought I could accept minor updates of AWS Amplify.  In the absence of a well-defined versioning scheme, this is clearly not a safe practice.  I'm not too happy I had to learn that the hard way.  This means I need to change my dependency chain to freeze the AWS Amplify version as I can no longer trust the versioning system to tell me what updates are simple additions or bug fixes.

**Comment by kvasukib** [comment]
@doctorcolinsmith Thank you for the valuable feedback. I will discuss this feedback with the team and update you based on the outcome of our discussion.

**Comment by kvasukib** [comment]
@doctorcolinsmith Thank you for your patience. We will add documentation on what the SDK versioning scheme means (X.Y.Z) in our docs page. I will post an update here when the docs site is updated with the content for versioning scheme. Thank you for bringing this to our attention.

**Comment by doctorcolinsmith** [comment]
Thanks for the update.  Good documentation on the versioning scheme will be a big help on the dependency management in my projects.

**Comment by palpatim** [comment]
New PR is https://github.com/aws-amplify/docs/pull/865
