### ISSUE TITLE
Forcing User to validate credentials if logged-in using new device - AWS Cognito

### ISSUE THREAD

**Issue by iTransactions** [aws-amplify/aws-sdk-ios#1227]
**State your question**
I have an iOS app which is integrating with AWS Cognito User pool and I am storing phoneNumber as 'username' with random password. During registration, I am confirming user once they verify code sent over to their phone. Once confirmed, user does not need any other verification. Now, if the user logs in to a new device, since the user already exists, how do I force user to verify the code again? Should I maintain some flag to see the 'user exist' scenario OR add MFA temporarily to re-verify using the same phone numer?

**Which AWS Services are you utilizing?**
AWS Cognito
**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29] 2.8.4
 - Dependency Manager: [e.g. Cocoapods, Carthage] Cocoapods
 - Swift Version : [e.g. 4.0] 4.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] Simulator
 - iOS Version: [e.g. iOS 11.4] iOS 12.0
 - Specific to simulators:

**Comment by kvasukib** [comment]
@iTransactions Thank you for reporting to us. I am looking into the issue and I will have an update soon.

**Comment by minbi** [comment]
Hi @iTransactions ,

If you use the remember devices feature you can achieve this use-case. You will need to enable the remember devices feature on the service-side before proceeding.

See [AWSMobileClient docs][1] on how to instantiate the client.
Sign-in the user. They user will go through user/pass, MFA code, etc.
Then once signed-in call [remember device][2] to register the device with the account.

Then, when the user signs-out and signs-in again. The device will be recognized by the service and the MFA code will not be required to successfully sign-in.

When a user gets a new device, then the service will not recognize it and prompt for the MFA code. You should again call [remember device][2] to register the device with the account.

Does this fit your use-case?

[1]: https://aws-amplify.github.io/docs/ios/authentication
[2]: https://aws-amplify.github.io/docs/ios/authentication#remember-device

**Comment by rohit3d2003** [comment]
In the current use case, we are asking user to sign-up using just the phone number and they receive a verification code to confirm the entered number on their device. With MFA on, AWS sends the code twice - first to verify the phone number and second for MFA which is not something that we want. 

@minbi - The scenario you mentioned will work for all registered users who are signing-in but for new users sign-up process runs into above mentioned workflow which isn’t something that we want

**Comment by palpatim** [comment]
@rohit3d2003 

I have brought this up to the service team as a feature request, but at this point this is not a supported feature. Since this request requires a service change, and has no client-side workarounds, I'm going to close this issue. We'll update Cognito docs if and when the status changes.
