### ISSUE TITLE
AWSS3TransferUtility: Upload of image fails with no error response

### ISSUE THREAD

**Issue by william-gill** [aws-amplify/aws-sdk-ios#1228]
**Describe the bug**
I am trying to upload an image to a pre-existing S3 bucket with TransferUtility.

When the request is sent, the completion handler is triggered but the file does not upload. 

There is no error message. result.response is nil.

I can't understand why the upload is failing. Sorry if it's something basic; I'm new to AWS and I've tried looking at all the AWS examples out there but I can't find anything that works...

**To Reproduce**

**Which AWS service(s) are affected?**
iOS SDK: TransferUtility, S3

**Expected behavior**
File should upload and return a response object

**Environment(please complete the following information):**
 - SDK Version: 2.8.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone XS
 - iOS Version: iOS 12
 - Specific to simulators:

**Additional context**
Here is the code I am calling to send the upload:
```
let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast2, identityPoolId:"xxxxx")

let configuration = AWSServiceConfiguration(region:.USEast2, credentialsProvider:credentialsProvider)

AWSServiceManager.default().defaultServiceConfiguration = configuration

let tuConf = AWSS3TransferUtilityConfiguration()
tuConf.isAccelerateModeEnabled = true

AWSS3TransferUtility.register(
    with: configuration!,
    transferUtilityConfiguration: tuConf,
    forKey: "transfer-utility-with-advanced-options"
)

let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "transfer-utility-with-advanced-options")

let expression = AWSS3TransferUtilityUploadExpression()
expression.progressBlock = {(task, progress) in
    DispatchQueue.main.async(execute: {
        // Do something e.g. Update a progress bar.
    })
}

var completionHandler: AWSS3TransferUtilityUploadCompletionHandlerBlock?
completionHandler = { (task, error) -> Void in
    DispatchQueue.main.async(execute: {
        // Do something e.g. Alert a user for transfer completion.
        // On failed uploads, `error` contains the error object.
    })
}

let fileName = "will-test-1"
let imageData = UIImage(named: "soon")?.jpegData(compressionQuality: 0.9)

transferUtility.uploadData(imageData! as Data,
                           bucket: "digitiser-user-images",
                           key: fileName,
                           contentType: "image/jpg",
                           expression: expression,
                           completionHandler: completionHandler).continueWith {
                            (task) -> AnyObject? in
                            if let error = task.error {
                                print("Error: \(error.localizedDescription)")
                            }

                            if let result = task.result {
                                print ("upload successful.")
                                print (result.response)
                            }
                            return nil;
}
```

**Comment by kvasukib** [comment]
@william-gill Thank you for reporting to us. Sorry for the inconvenience caused.

1) Did you get any progress update when the transfer started?
2) What is the size of the file you are uploading?
3) Do you have transfer acceleration enabled on the bucket?
4) Do you have any bucket configuration / policies set on the bucket?

**Comment by william-gill** [comment]
Hi @kvasukib thanks for the response!
1. No - there is nothing in the log when the process starts. But I immediately see the result of the print statement `print ("upload successful.")` in the debug.
2. The file is an image 257kb
3. Possibly not; it is the default settings after running `amplify add storage`. I tried again with `tuConf.isAccelerateModeEnabled = false` and it made no difference.
4. All default settings from after running `amplify add storage`

Thanks so much!

**Comment by william-gill** [comment]
Hi,
OK; I have changed the policy on the bucket to be public access read and write. 
Now the upload works! 

Phew! So it is definitely not an error with the SDK.
Sorry for the false alarm!
The error message could be more useful though! It would have saved me many hours of wondering what the issue is.

Now I need to figure out how to set it up so that I don't need to leave the bucket permissions totally public...

**Comment by kvasukib** [comment]
@william-gill Are you using the `amplify-cli`? It can help you configure public, private and protected folders in your S3 bucket for the different access permissions based on the Cognito Identity. That can help you solve the problem of providing access control to information on your S3 bucket.

**Comment by william-gill** [comment]
@kvasukib yes, I'm using `amplify-cli` - I'll check the docs out more. Thanks a lot for your help, I really appreciate it!

**Comment by kvasukib** [comment]
@william-gill Here you go: https://aws-amplify.github.io/docs/ios/storage#storage-access

**Comment by william-gill** [comment]
Hi @kvasukib 
I wonder if you can help me further.
I cannot get the upload to work on a different bucket.
**I had to switch to a different bucket that was already existing**, as this is one that is being used by other apps and we need to share it. So I cannot use Amplify CLI to configure it.

I have used amplify CLI to configure Auth/Cognito for the app and that looks to be working fine. I have assigned "S3 full access" to the IAM roles associated with the Cognito identity pool.

When I attempt to perform an upload:
- I can see that the device is authenticated by Cognito (I see this on the detail page for the identity pool incognito)
- But the file does not appear in the S3 bucket

I have checked and double checked every permission, and even tried making the s3 bucket completely public to test it - but nothing allows me to put a file in that bucket.

Is there something else I need to do inside the app to force it to work?

I have this in my awsconfiguration.json:
``` 
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-2:xxx",
                "Region": "us-east-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-2_xxx",
            "AppClientId": "xxx",
            "AppClientSecret": "xxx",
            "Region": "us-east-2"
        }
    },
    "S3TransferUtility": {
        "Default": {
            "Bucket": "digitiser-user-images",
            "Region": "eu-west-1"
        }
    }
}
```

And this is the code I call to upload the image:
```
func uploadImages() {
        
        //let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast1, identityPoolId:"us-east-1:xxx")
        //let configuration = AWSServiceConfiguration(region:.USEast1, credentialsProvider:credentialsProvider)
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast2, identityPoolId:"us-east-2:xxx")
        let configuration = AWSServiceConfiguration(region:.USEast2, credentialsProvider:credentialsProvider)
        
        let tuConf = AWSS3TransferUtilityConfiguration()
        tuConf.isAccelerateModeEnabled = false
        
        AWSS3TransferUtility.register(
            with: configuration!,
            transferUtilityConfiguration: tuConf,
            forKey: "transfer-utility-with-advanced-options"
        )
        
        let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "transfer-utility-with-advanced-options")

        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = {(task, progress) in
            DispatchQueue.main.async(execute: {
                // Do something e.g. Update a progress bar.
            })
        }
        
        var completionHandler: AWSS3TransferUtilityUploadCompletionHandlerBlock?
        completionHandler = { (task, error) -> Void in
            DispatchQueue.main.async(execute: {
                // Do something e.g. Alert a user for transfer completion.
                // On failed uploads, `error` contains the error object.
            })
        }
        
        let bucketName = "digitiser-user-images"
        
        for image in imageArray {
            let fileName = NSUUID().uuidString + ".jpg"
            print (fileName)
            let imageData = image.jpegData(compressionQuality: 0.9)
            
            transferUtility.uploadData(imageData! as Data,
                                       bucket: bucketName,
                                       key: fileName,
                                       contentType: "image/jpg",
                                       expression: expression,
                                       completionHandler: completionHandler).continueWith {
                                        (task) -> AnyObject? in
                                        if let error = task.error {
                                            print("Error: \(error.localizedDescription)")
                                        }
                                        
                                        if let _ = task.result {
                                            print ("upload successful.")
                                        }
                                        return nil;
            }
        }
    }
```


I know this isn't exactly a bug in the framework, but I'm really lost and nothing I have tried is working. Could you suggest anything I could try?

Thanks so much!!

**Comment by william-gill** [comment]
@kvasukib Hi again
I've tried absolutely everything to get my app connected to an _existing_ AWS Bucket - but nothing works. 

I've checked IAM policies, bucket policy, Cognito pools.
I can see that the device is authenticated by Cognito (because the identity appears in the console). The IAM Policy attached to that pool has **Admin** permission on the Bucket.

I have put the appropriate values for the Cognito pool and the Bucket on the awsconfiguration.json file.

I've tried EVERYTHING. Nothing works.

What am I missing? 
Please help - thanks!!!
❤️

**Comment by kvasukib** [comment]
@william-gill Thank you for the detailed response. Sorry for the inconvenience caused. I checked the `awsconfiguration.json` file and the code snippet you have posted. I couldn't find any issue with the code/json file. Can we get into a call so you can be unblocked? You can email me at karthba at amazon dot com and we can setup a call from there.

**Comment by kvasukib** [comment]
The issue was related to providing the configuration information via the `awsconfiguration.json` vs the code. The issue was resolved when the information is just provided in one place. Closing this issue.
