### ISSUE TITLE
[S3TransferUtility] `uploadUsingMultiPart` is upload fails at credential update timing 

### ISSUE THREAD

**Issue by kimiyash** [aws-amplify/aws-sdk-ios#1230]
**Describe the bug**
I'm using a multipart upload with cognito authentication.
But sometimes multipart uploading failed with refresh credential timing.

I have investigated a above behavior with created a uses S3 TransferUtility multipart upload simple project.

https://github.com/kimiyash/S3TransferUtilityMultipartUploadTest/blob/master/S3TransferUtilityMultipartUploadTest/AppDelegate.swift

NOTE, In order for this to work you need to include the appropriate settings in the Config structure. I have entered settings for cognito's identity pool/identity id/long time alives token and s3 that I can use.

I got a filtered console log by `[debug print]` string with above sample project
```
2019/02/13 13:23:45.890 [debug print] - upload() - start
2019/02/13 13:23:45.929 [debug print] - upload() - uploadDateString:Wednesday, February 13, 2019 at 1:23:45 PM Japan Standard Time
2019/02/13 13:23:46.182 [debug print] - token() - DeveloperCognitoCredentialProvider
2019/02/13 13:23:47.342 [debug print] - upload() - uploadUsingMultiPart - continueWith:<AWSTask: 0x600000e84400; completed = YES; cancelled = NO; faulted = NO; result = <AWSS3TransferUtilityMultiPartUploadTask: 0x600002a08c80>>
2019/02/13 13:23:47.342 [debug print] - upload() - uploadUsingMultiPart - continueWith - task.result.status:1
2019/02/13 13:23:47.830 [debug print] - upload() - completionHandler
...
2019/02/13 13:33:46.681 [debug print] - token() - DeveloperCognitoCredentialProvider
2019/02/13 13:33:46.781 [debug print] - upload() - uploadUsingMultiPart - continueWith:<AWSTask: 0x600000eb4d80; completed = YES; cancelled = NO; faulted = NO; result = <AWSS3TransferUtilityMultiPartUploadTask: 0x600002a1d2c0>>
2019/02/13 13:33:46.781 [debug print] - upload() - uploadUsingMultiPart - continueWith - task.result.status:1
```

I expected a upload processing continue, but the next upload processing did not start.
At this time the content of the log output at [here](https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSS3/AWSS3TransferUtility.m#L1335) was like this.

```
2019-02-13 13:33:46:684 S3TransferUtilityMultipartUploadTest[3764:3378895] Added task [0] to inProgress list
```

This means that `subTask.taskIdentifier` is 0.

Based on this, I have wrote a [this change](https://github.com/kimiyash/S3TransferUtilityMultipartUploadTest/compare/master...investigate-bug) for reproduction a bug and investigate.

I got a below logs.
```
2019/02/13 15:01:40.092 [debug print] - upload() - start
2019/02/13 15:01:40.750 [debug print] - upload() - uploadDateString:Wednesday, February 13, 2019 at 3:01:40 PM Japan Standard Time
2019/02/13 15:01:43.647 [debug print] - token() - DeveloperCognitoCredentialProvider
2019/02/13 15:01:48.986 [debug print] - token() - DeveloperCognitoCredentialProvider
2019-02-13 15:01:49:136 S3TransferUtilityMultipartUploadTest[9845:3483711] [debug print] presignedUrlTask Uncompleted!!!!
2019/02/13 15:01:49.244 [debug print] - token() - DeveloperCognitoCredentialProvider
2019/02/13 15:01:49.439 [debug print] - upload() - uploadUsingMultiPart - continueWith:<AWSTask: 0x600003606980; completed = YES; cancelled = NO; faulted = NO; result = <AWSS3TransferUtilityMultiPartUploadTask: 0x60000127ca00>>
2019/02/13 15:01:49.440 [debug print] - upload() - uploadUsingMultiPart - continueWith - task.result.status:1
```

presignedUrlTask is not completed.
[This code block](https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSS3/AWSS3TransferUtility.m#L1444-L1475) are not ran because presignedUrlTask is not finished.

I attempted to a naive bugfix by [this code](https://github.com/kimiyash/S3TransferUtilityMultipartUploadTest/compare/master...work-around#diff-2fc86b788f1e99d3d84e65bd478d7aedR1480). It seems to keep working normally.

**To Reproduce**
Clone to local pc from master branch of this repository
https://github.com/kimiyash/S3TransferUtilityMultipartUploadTest

- Enter [Config to struct](https://github.com/kimiyash/S3TransferUtilityMultipartUploadTest/blob/master/S3TransferUtilityMultipartUploadTest/AppDelegate.swift#L37
)
You need to include the appropriate settings in the Config structure. I have entered settings for cognito's identity pool/identity id/long time alives token and s3 that I can use.

- Build and Run your xcode

- Expect uploading should be continued, but it stops unintentionally.

**Which AWS service(s) are affected?**
AWSS3TransferUtility#uploadUsingMultiPart

**Expected behavior**
Upload processing should be performed normally even if implicit credential update is performed within `AWSS3TransferUtility#uploadUsingMultiPart`.

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 
```
PODS:
  - AWSCognito (2.9.0):
    - AWSCore (= 2.9.0)
  - AWSCognitoIdentityProvider (2.9.0):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
    - AWSCore (= 2.9.0)
  - AWSCognitoIdentityProviderASF (1.0.1)
  - AWSCore (2.9.0)
  - AWSS3 (2.9.0):
    - AWSCore (= 2.9.0)
```
 - Dependency Manager: Cocoapods
 - Swift Version : Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)

**Device Information (please complete the following information):**
 - Device: iPhoneXR, Simulator
 - iOS Version: iOS 12.1 (16B91)

**Comment by kvasukib** [comment]
@kimiyash Thank you for the details in your bug report. I am looking into the issue. I will post an update when I have more information.

**Comment by cbommas** [comment]
@kimiyash 

Thank you for providing the details for this issue. I am working on a fix for this issue and am targeting it for the next rev of the SDK. I reviewed the PR, but I am leary of using the `waitUntilFinished`, so I am exploring a different approach.

**Comment by kimiyash** [comment]
@cbommas 

Thank you for your reply.
I agree with you. Better not to use `waitUntilFinished`.
I thought that it was better for the `createUploadSubTask` method to return AWSTask, however, which would much change to method interfaces, I could not do that by me...
I sincerely hope that a better change will be made and the defect will be fixed :)

**Comment by cbommas** [comment]
@kimiyash 

I have coded up a fix for this issue that doesn't use `waitUntilFinished`. I am targeting to get this included in the next rev of the SDK.  I will post back on this thread once I have confirmation.

**Comment by kimiyash** [comment]
@cbommas 

Amazing!!! I appreciate your work!

**Comment by cbommas** [comment]
@kimiyash 

After testing, I ended up using a hybrid approach that also utilizes `waitUntilFinished`, which is available in v2.9.2 of the SDK. Please give it a try and see if that resolves the issue for you.

Also, Thank you very much for bringing this issue to our attention and for suggesting the fix.  Much appreciated 👍

**Comment by cbommas** [comment]
@kimiyash 
I will go ahead and close this out. Please feel free to post here if you are still facing issues.

**Comment by kimiyash** [comment]
@cbommas 
Sorry for the late reply.
I confirmed this issue has been fixed with my Xcode test project.
Thank you so much!

**Comment by cbommas** [comment]
@kimiyash 
Excellent! Thank you for confirming. 👍
