### ISSUE TITLE
AWSCognitoAuth getSession callback is not executed, browser remain.

### ISSUE THREAD

**Issue by morrislwt** [aws-amplify/aws-sdk-ios#1234]
**State your question**
This is my code 
``` 
func facebookLogin(_ sender: UIButton) {
        let cognitoAuth = AWSCognitoAuth(forKey: "cognitoAuth")
        cognitoAuth.delegate = self
        
        cognitoAuth.getSession { (session, err) in
            self.logger.log(session)
            self.logger.log(err)
            if(err != nil) {
                NSLog(err.debugDescription)
            } else {
                
            }
        }
    }
```
I got a new user in UserPool when I success login via facebook page,
also receive a url like this:
```
myapp:///?code=93d4ee32-98d2-4557-b582-67fd2f44acc7&state=db7102fc-b1d1-4d3a-9216-23cfa604a7c9
```

but the app still on web page won't dismiss.
When I click "Done" button and login again, get error message 
```
 Optional(Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-2000 "(null)" UserInfo={error=Loading page failed})
```

I do implement configuration 
```
 let configuration = AWSCognitoAuthConfiguration(
            appClientId: "xxxxxxo2bnq3pdgrsi8k",
            appClientSecret: nil,
            scopes: Set<String>(["openid","aws.cognito.signin.user.admin"]),
            signInRedirectUri: "myapp://",
            signOutRedirectUri: "myapp://",
            webDomain: "https://xxxxx.auth.eu-west-1.amazoncognito.com",
            identityProvider: "Facebook",
            idpIdentifier: nil,
            userPoolIdForEnablingASF: "eu-west-1_xxxxzN")

        AWSCognitoAuth.registerCognitoAuth(with: configuration, forKey: "cognitoAuth")
``` 
and also add this function in AppDelegate 
```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {

        return AWSCognitoAuth(forKey: "cognitoAuth").application(app, open: url, options: options)
    }
```
How can I dismiss the browser when user login/signup success also make sure the status is logged in via Facebook.
Thank you.

**Which AWS Services are you utilizing?**

**AWSCognitoAuth**

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.9.0]
 - Swift Version : [e.g. 4.2]

**Device Information (please complete the following information):**
 - Device: [iPhoneX, Simulator]
 - iOS Version: [e.g. iOS 12.1]

**Comment by kvasukib** [comment]
@morrislwt Thank you for reporting to us. Sorry for the inconvenience caused while setting up `AWSCognitoAuth`.

If I understand correctly, you are encountering an issue after successfully signing in. 

Have you set up the required configuration information in `Info.plist` for `AWSCognitoAuth`? You can see https://github.com/awslabs/aws-sdk-ios-samples/blob/master/CognitoAuth-Sample/Swift/CognitoAuthSample/Info.plist#L37 as a reference.

You can also see the required setup instructions here: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample/Swift

I suspect if you have the right `CognitoAuthSignInRedirectUri` in the `Info.plist`.

**Comment by morrislwt** [comment]
@kvasukib  Thank you for the reply.

I found the problem is I set the 
```
signInRedirectUri = "sampleAPP://" 
```
then the browser won't close,
 when I set URI to **myapp://**, is works.

**Comment by kvasukib** [comment]
Thank you @morrislwt for the confirmation. Glad it worked. I'm closing the issue. Feel free to open if you face any issues.
