### ISSUE TITLE
Api.swift file not generated 

### ISSUE THREAD

**Issue by andrewdr** [aws-amplify/aws-sdk-ios#1236]
**Describe the bug**
Api.swift file is not created after Amplify Push.

**To Reproduce**
([following the AWS Amplify iOS Tutorial](https://aws-amplify.github.io/docs/ios/start))
Amplify Init
Amplify Push
Amplify  add api
Amplify Push

**Which AWS service(s) are affected?**
AMPLIFY

**Expected behavior**
After following the AWS Amplify 'Getting Started' tutorial, the 'api.swift' file is not  generated. I saw this was an issue in November and updated my NPM and Amplify to the latest versions, but it's still not working.

**Screenshots**
![screen shot 2019-02-14 at 4 11 55 pm](https://user-images.githubusercontent.com/17263996/52821040-4a740300-3073-11e9-81d4-47e1a1566c15.png)

<img width="1006" alt="screen shot 2019-02-14 at 4 08 30 pm" src="https://user-images.githubusercontent.com/17263996/52820886-d9cce680-3072-11e9-891e-21d45228d58e.png">

**Environment(please complete the following information):**
Xcode 10.1
Cocoapods
 Swift 4.2

**Device Information (please complete the following information):**
 - Device: iPhone Xs
 - iOS Version: 12.1.4

**Additional context**

**Comment by yuth** [comment]
@andrewdr could you paste the configuration you have for codegen. Its stored in `.graphqlconfig.yml` file which is in the root of your project. 

Please obfuscate `graphQLApiId` and ` endpoints` when you paste the content

**Comment by kvasukib** [comment]
@andrewdr Sorry for the inconvenience caused. This is an issue with the amplify-cli. I have opened an issue for you in that repository. https://github.com/aws-amplify/amplify-cli/issues/879

**Comment by andrewdr** [comment]
here is my .graphqlconfig.yml file

<img width="688" alt="graphql-config-file-screenshot" src="https://user-images.githubusercontent.com/17263996/52823507-d0477c80-307a-11e9-9f82-a400ee1c7e11.png">

**Comment by yuth** [comment]
@andrewdr do you have file named `q` in your project root? 

From the screenshot it looks like the generated file would be named `q` instead of `API.swfit`. Could you change the `generatedFileName` to `API.swift` see if that fixes the problem.

**Comment by andrewdr** [comment]
I updated the file, still getting the errors. Updated file below

<img width="674" alt="updated-graphql file" src="https://user-images.githubusercontent.com/17263996/52824582-bf006f00-307e-11e9-8c2e-9f1560fc25f2.png">

**Comment by yuth** [comment]
@andrewdr what error do you get?

**Comment by andrewdr** [comment]
From my project

<img width="996" alt="screen shot 2019-02-14 at 5 49 29 pm" src="https://user-images.githubusercontent.com/17263996/52825066-e7896880-3080-11e9-8347-17abfbe58c69.png">

**Comment by yuth** [comment]
Could you clarify the following:
1. Do you see any file with `.graphql` extension inside `<proj-root>/graphql/` folder
2. Do you get any error if you run `amplify codegen`
3. Do you see `API.swift` in your project root?

**Comment by andrewdr** [comment]
Yes sorry,

1. I have mutations.graphql, queries.graphql, and subscriptions.graphql in the root/graphql folder
2. I do not get any errors when I run amplify codgen
3. Yes, I see API.swift in my project root

**Comment by yuth** [comment]
Thanks for confirming. Could you paste contents of `mutation.graphql`

**Comment by andrewdr** [comment]
<img width="416" alt="screen shot 2019-02-14 at 6 09 27 pm" src="https://user-images.githubusercontent.com/17263996/52825995-9ed3ae80-3084-11e9-99db-2d43f3d6e8f1.png">

**Comment by kvasukib** [comment]
@andrewdr If the `API.swift` is generated, can you check if this file is being part of the XCode target? You can check this by clicking on the file and opening the right pane to see the `Target Membership`?

**Comment by andrewdr** [comment]
No, I don't believe it is. How do I add it?

**Comment by kvasukib** [comment]
@andrewdr You can read about XCode Target here: https://developer.apple.com/library/archive/featuredarticles/XcodeConcepts/Concept-Targets.html.

1) Click the `API.swift` file and open the right pane (Hide or show Utilities). 
2) Find `Target Membership` section
3) Make sure your XCode target for your app is selected here.

**Comment by andrewdr** [comment]
That worked! I had to manually drag the API.swift file into the project. The file wasn't showing up after dragging via the finder window. Thanks!

**Comment by kvasukib** [comment]
Thank you @andrewdr for confirming. Glad it worked!

**Comment by bdering** [comment]
Hi, I had the same issue. Instead of 
`includes:
      - graphql/**/*.graphql` 
amplify inserted 'y' in my file in the same line, this was cause why it was not possible for me to generate the Api.swift file.
