### ISSUE TITLE
[MobileClient] Check for token validity during initialization

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-ios#1239]
**Which AWS Services is the feature request for?**
AWSMobileClient

**Is your feature request related to a problem? Please describe.**

In https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/185, @zigfreid5 reported that initializing a MobileClient instance with an expired token nonetheless returned a `.signedIn` user state. It looks like the initialization check looks at the *presence of* rather than the *contents or validity of* the token.

**Describe the solution you'd like**

Initialization should inspect the token and compare its expiration date to the local cached time. There could be issues with clock skew, or with a user intentionally changing the clock, but those should be edge cases--the happy path is that the device and server clocks are close enough in agreement that the local validity check would be meaningful.

Checking for token validity would also match the [described behavior during a fetch operation](https://aws-amplify.github.io/docs/ios/authentication#token-fetch-and-refresh): 

> The AWSMobileClient will return valid JWT tokens from your cache immediately if they have not expired. If they have expired it will look for a Refresh token in the cache. If it is available and not expired it will be used to fetch a valid IdToken and AccessToken and store them in the cache.

**Describe alternatives you've considered**

1. **Do nothing.** This is resulting in at least some customer confusion, since the behavior is different from what happens during fetch, and what logically might be expected by a user of the SDK.

**Comment by Dellybro** [comment]
Any news on this? It seems as though this may be the issue to my users being signed out after not opening their app within 48hours.

**Comment by atierian** [comment]
This issue appears be resolved via the linked pull request, which was included in [2.30.3](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.30.3)
- https://github.com/aws-amplify/aws-sdk-ios/pull/4547

Thanks!
