### ISSUE TITLE
Some data not showing in Pinpoint

### ISSUE THREAD

**Issue by jspargo** [aws-amplify/aws-sdk-ios#1241]
**Describe the bug**
Certain events are not showing in the AWS Pinpoint console despite being triggered by the AWS iOS SDK and appearing the payload sent.

**To Reproduce**
1. Fire a number of analytics events using the AWS iOS SDK (`recordEvent`)
2. Verify the payload being sent to pinpoint (using Charles or similar network sniffing tool) to confirm that all the data is present
3. Search AWS Pinpoint dashboard for sent events
4. Some data is missing despite being present in the payload and no errors being observed in the iOS app.

**Which AWS service(s) are affected?**
Pinpoint

**Expected behavior**
All events should be sent to Pinpoint with relevant metics and attributes

**Actual behavior**
Only a subset of events are being sent to Pinpoint. In the payload below, for example, `user.sign_in.success` appears in the Pinpoint console but `inventory.stock_item.added` is not.

**Payload (intercepted request to Pinpoint)**
```
{
  [{
    "timestamp": "2019-02-14T13:58:24.484Z",
    "session": {
      "id": "43f724e3-BC09FEBE-20190214-133823259",
      "duration": 1213065,
      "startTimestamp": "2019-02-14T13:38:23.260Z"
    },
    "metrics": {
      "Internet reachable via WiFi": 1
    },
    "eventType": "inventory.stock_item.added",
      "attributes": {
        "Device": "iPad Simulator",
        "app_version": "3.5.0",
        "app_session": "CAA1129C-E812-4B25-BECF-14AA3C182A75",
        "register_uuid": "0703B773-2B47-4FAB-B63E-8F3A160DDF89",
        "Build configuration": "Distribution",
        "current_employee_uuid": "4114CE01-EC32-467A-9A15-DE64695431F9",
        "Selected store name": "testea8bc91",
        "Selected store environment": "staging",
        "current_employee_session": "9BF37B16-B351-46C8-AE2F-B6B4490EF944"
      }
  }, {
    "timestamp": "2019-02-14T13:58:36.299Z",
    "session": {
      "id": "43f724e3-BC09FEBE-20190214-133823259",
      "duration": 1213066,
      "startTimestamp": "2019-02-14T13:38:23.260Z"
    },
    "metrics": {
      "Internet reachable via WiFi": 1,
      "queue_job_count": 0,
      "queue_unrescued_job_count": 0
    },
    "eventType": "user.sign_in.success",
    "attributes": {
      "app_session": "CAA1129C-E812-4B25-BECF-14AA3C182A75",
      "Selected store environment": "staging",
      "app_version": "3.5.0",
      "screen": "Cashier screen",
      "employee_name": "Manager Manager",
      "register_uuid": "0703B773-2B47-4FAB-B63E-8F3A160DDF89",
      "Selected store name": "testea8bc91",
      "Build configuration": "Distribution",
      "current_employee_session": "9BF37B16-B351-46C8-AE2F-B6B4490EF944",
      "Device": "iPad Simulator",
      "login_code": "xxxx",
      "current_employee_uuid": "4114CE01-EC32-467A-9A15-DE64695431F9",
      "current_shift_opened_at": "2019-02-07T15:46:10Z"
    }
  }]
}
  
```

**Environment(please complete the following information):**
 - SDK Version: 2.6.16 (also tried with 2.9.0)
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: iPad and Simulator
 - iOS Version: iOS 12.1
 - Specific to simulators: no

**Additional context**
It appears that there are certain set of events that appear in the payload (and can be seen fired successfully when debugging in Xcode) that never appear on the AWS Pinpoint dashboard. For the affected event, it appears that they are still appearing for some devices/users, but the unaffected events are appearing for all devices/users.

**Comment by palpatim** [comment]
@jspargo 

Can you share the IAM policy for the roles (auth & unauth) that submit events to Pinpoint? Please obfuscate account IDs when pasting, but do verify that they match the expected account ID.

For example, here is one I generated from the Amplify CLI:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint",
                "mobiletargeting:GetUserEndpoints"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:*:123456789012:apps/1234567890abcdef1234567890abcdef*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

The pieces I'm particularly interested in are `"mobiletargeting:PutEvents"` and `"mobiletargeting:UpdateEndpoint"`. We've seen some customers using `"mobileanalytics:PutEvents"` instead.

**Comment by jspargo** [comment]
Thanks @palpatim 

I don't think we _have_ any IAM policies setup for use by Pinpoint. We pretty much did a straight replacement of the `AWSMobileAnalytics` pod with the `AWSPinpoint` pod in April 2018.

There was the addition of some settings in our `Info.plist` but nothing about an IAM role (values obfuscated):
```
<key>AWS</key>
	<dict>
		<key>CredentialsProvider</key>
		<dict>
			<key>CognitoIdentity</key>
			<dict>
				<key>Default</key>
				<dict>
					<key>Region</key>
					<string>USEast1</string>
					<key>PoolId</key>
					<string>us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</string>
				</dict>
			</dict>
		</dict>
		<key>PinpointAnalytics</key>
		<dict>
			<key>Default</key>
			<dict>
				<key>Region</key>
				<string>USEast1</string>
				<key>AppId</key>
				<string>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</string>
			</dict>
		</dict>
	</dict>
```

I would have thought if the IAM role was wrong (or not set) that none of the events were being sent? As it stands it looks like the vast majority of events _are_ being sent. 🤔

**Comment by jspargo** [comment]
Sorry, to answer your later questions:

> Also, to clarify, are you seeing that some clients are submitting all events, while some are submitting no events; or is it that all clients are submitting some events?
Frustratingly the answer is: somewhere in between those two. It seems like most clients are submitting _all_ events, and some clients (hard to put a figure on it, but I'd hazard a guess that it's a small percentage) are seeing _most_ events but missing some. When events are missing, it's always the same ones. For example, I have one user who if I perform 5 events and observe them in the payload, the same 2 events always appear but 3 are always missing.

> If the former, are you able to identify any pattern in the clients that submit no events (e.g., they are all using a particular SDK version).
No obvious pattern occurs, but all our clients are using 2.6.16. I tested locally with 2.9.0 and observed the same behaviour.

> If the latter, are you able to identify any pattern in the missing events (e.g., they have specific names, attributes, payload sizes, etc)?
In my original attached example, with payload, `user.sign_in.success` is _always_ seen in the Pinpoint console for this user, `inventory.stock_item.added` is _never_ seen for this user.

**Comment by palpatim** [comment]
@jspargo 

Thanks for the replies. Unfortunately, even if your app is set up to use them, the IAM roles are difficult to discover, as they are loosely coupled to the pinpoint client only in the role definition.

For example, here is the process I have to go through to find the roles associated with my pinpoint sample app that I recently set up using the Amplify CLI:

* Go to the Cognito console: https://console.aws.amazon.com/cognito
* Select your region in the upper-right
* Click "Manage Identity Pools"
* Find the identity pool associated with your app
* Click the "Edit Identity pool" link in the upper-right of the page
* There will be an entry for "Authenticated role" and (probably) "Unauthenticated role"
* Go to the IAM console: https://console.aws.amazon.com/iam
* Click on the "Roles" link in the nav bar
* Search for the role you found above
* On the "Permissions" tab, I find an inline policy attached to the role (the one I pasted in my comment above)

Assuming the Roles aren't the issue, can you review the [Pinpoint Limits](https://docs.aws.amazon.com/pinpoint/latest/developerguide/limits.html) to see if any of these may be preventing your events from being recorded? Most of the limits are unlikely to pertain, but it might be worth reviewing **Event Ingestion Limits**. For example, if an event has more than 50 characters in an attribute key, it might get rejected; or if the total batch exceeds 100 events, the batch submit request would be rejected.

**Comment by jspargo** [comment]
Hi @palpatim - thanks for your response and sorry for my slow response.

I followed your helpful steps and this seems to have gone almost all the way to resolve this issue. There is one outstanding issue though that you may want to be aware of. 

We are using AWS Kinesis to stream the data from PinPoint to S3 where it then retrieved by a data analysis application. I can see that the data is now making it through to this application, and when I inspect a handful of the payloads on S3 they all look to be correct now, but it seems this data isn't always visible in the AWS Pinpoint console. It seems that this must be a bug (or perhaps some data limitation?) in the AWS Pinpoint console itself. 

This isn't impacting our workflow, so I'd be happy if you wanted to close this now, but if you wanted to dig deeper into the console bug I'd be happy to show you the bug through a private channel.

Thanks again!

**Comment by Prachi95** [comment]
Hi @jspargo - I am facing same issue. I have added new key-value (attribute) in an old event, but even though it is not adding that attribute in that event.

Also pinpoint is capturing usage data events very slowly nowadays for my account. Previously when I was working on this, it used to take hardly 5-10 minutes to log any custom event in pinpoint. I could see new events , new attributes in my testing.

But recently when I have added this new attribute, it is not adding in event. Also there is limit of 40 attributes in one event, I have only 15-16 attributes, still I am facing this issue.

We are fetching data from s3 bucket using python script. You have mentioned that it might not be visible in pinpoint dashboards but it will be there in retrieved data, but in my case that attribute is not getting added in s3 too. 

Could you please help if you have any knowledge regarding this

Thanks in advance!

**Comment by muellerfr** [comment]
@jspargo - We have opened a ticket on the Pinpoint service team to investigate the console issues you reported. We will provide an update when we receive it from the service team.

**Comment by kvasukib** [comment]
@jspargo Is it possible for you to send the Pinpoint application Id to us so our Pinpoint service team can debug this issue further? You can email me at karthba at amazon dot com. Thank you!

**Comment by kvasukib** [comment]
@jspargo Thank you for sending the Pinpoint appId. I have passed the information to the Pinpoint service team for further analysis. Meanwhile, we have few questions for you:-

1) What are the event types?
2) Which page / widget in the console are you monitoring?

**Comment by kvasukib** [comment]
@jspargo Do you have the information for the questions asked in https://github.com/aws-amplify/aws-sdk-ios/issues/1241#issuecomment-485504896?

You can reach out to Amazon Pinpoint Service team either through AWS Forums or AWS Customer Support if you have more information. Thanks.
