### ISSUE TITLE
[Auth] Maintain user state when migrating from AWSCognitoIdentityProvider to AWSMobileClient

### ISSUE THREAD

**Issue by Thuran** [aws-amplify/aws-sdk-ios#1243]
**Describe the bug**
We have a released application with Cognito implemented with the following pods:
```
pod 'AWSCore'
pod 'AWSCognitoIdentityProvider'
```
We tried to switch to the new sdk:
`pod 'AWSMobileClient', '~> 2.8.0'`

But when I try to get the user session, the userState of the initialize's method is signedOut
**To Reproduce**
If we use the "legacy" code, we are able to get the current user session:
```
pool.currentUser()!.getSession().continueWith { task in
}
```
But, if we try to get the user session with the AWSMobileClient, the userState is signedOut:
```
AWSMobileClient.sharedInstance().initialize { (userState, error) in
            if let userState = userState {
                print("UserState: \(userState.rawValue)")
            } else if let error = error {
                print("error: \(error.localizedDescription)")
            }
        }

```

**Which AWS service(s) are affected?**
Cognito

**Expected behavior**
Keep the user session when we switch to the new SDK.

**Environment(please complete the following information):**
 - Dependency Manager: Cocoapods
 - Swift Version: 4
 - Device: any
 - iOS Version: any
 - Specific to simulators: No

**Additional context**
Your legacy Cognito implementation is based on this project: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Swift

**Comment by rohandubal** [comment]
Hello @Thuran 

`AWSMobileClient` manages state by storing credentials in the keychain. When using AWSCognitoIdentityProvider and signing in a user, the AWSMobileClient is not aware about the user state and hence will never have the useState of signedIn. To migrate to use AWSMobileClient for an existing application, you will have to require the end-user to re-login into your app so that `AWSMobileClient` is aware about the userState and manages the lifecycle correctly. 

Thanks,
Rohan

**Comment by Thuran** [comment]
Hy @rohandubal,
 
I understand, but I think it's really bad. Because everyone who will migrate to the new SDK, they will have to log off their users, and in our case this is very annoying for them.

Thanks for your response.

**Comment by atierian** [comment]
Thanks for opening this. We're closing this as migration logic to AWSMobileClient is no longer relevant. We recommend using the Auth category in Amplify Swift going forward -- for more information, please visit https://docs.amplify.aws/swift/build-a-backend/auth/
