### ISSUE TITLE
Sporadic Failure with syncDataSet.synchronize(): Domain=com.amazonaws.AWSCognitoSyncErrorDomain Code=0 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=AccessDeniedException

### ISSUE THREAD

**Issue by AnthonyUccello** [aws-amplify/aws-sdk-ios#1245]
Howdy!

I noticed two older issues without a clear resolution but the exact same problem:
https://github.com/aws-amplify/aws-sdk-ios/issues?utf8=%E2%9C%93&q=NSLocalizedFailureReason%3DAccessDeniedException

For Facebook login specifically (Google works just fine), I am having a hit and miss login. 50-90% of the time, when I call syncDataSet.synchronize() I get this error:

`Domain=com.amazonaws.AWSCognitoSyncErrorDomain Code=0 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=AccessDeniedException:}`

Been stuck on this for several days. I have put many break points and sometimes there is no error, sometimes there is so I am wondering if you have any insight as to why this is sporadically failing.

We are using a podfile install so we have the latest version:

```
Using AWSAPIGateway (2.9.1)
Using AWSCognito (2.9.1)
Using AWSCognitoIdentityProvider (2.9.1)
Using AWSCognitoIdentityProviderASF (1.0.1)
Using AWSCore (2.9.1)
Using AWSSNS (2.9.1)
```

The code use is pretty straight forward:

    public static func synchronize(label: String?, completion: ((THResponse<Bool>) -> Void)? = nil) {
        // Sync remotely to Cognito Sync
        syncDataset.synchronize().continueWith { task in
            guard task.error == nil else {
                let error = task.error ?? THError.general(code: 500, message: task.error?.localizedDescription ?? "Unknown Error")
                print("👤 Failed synchronizing Cognito Sync profile \"\(String(describing: label))\": \(error)")
                if let label = label {
                    THLogger.Failure("👤 Failed synchronizing Cognito Sync profile \"\(label)\": \(error)")
                }
                

                completion?(THResponse(error: error))
                return task
            }

            if let label = label {
                THLogger.Success("👤 Successfully synchronized Cognito Sync profile \"\(label)\"")
            }

            let resp = THResponse(response: true)
            completion?(resp)
            return task
        }
    }

Do you have any suggestions as to why this is happening and what might be a possible solution?

Thank you!

**Comment by muellerfr** [comment]
Hi @AnthonyUccello, sorry to hear you are running into issues using Cognito Sync. Are you a new user trying to use Cognito Sync? If so, have you taken a look at AppSync? https://docs.aws.amazon.com/appsync/latest/devguide/welcome.html

**Comment by AnthonyUccello** [comment]
Hi @muellerfr 

This is some inherited code I am working with. At the moment I was hoping to to find a fix for the current issue. Re-writting to switch to AppSync would be a last resort.

**Comment by muellerfr** [comment]
Hi @AnthonyUccello, thanks for confirming. We'll investigate and report back here.

**Comment by AnthonyUccello** [comment]
I believe the issue is related to a Facebook Access Token.

There are 2 reasons I have found the token is bugging out. The first is recent versions of the facebook SDK have a bug: https://github.com/facebook/facebook-swift-sdk/issues/286

Moving my facebook login kit down to 4.36 has fixed the first issue. 

However, AFTER making a graph request (which we do before calling syncDataset.synchronize().continueWith) the Facebook Access Token becomes nil.

I have no figured out why this occurs yet, I am going to file a bug with the facebook SDK. But I believe this issue can reproduced by having a nil facebook access token.

**Comment by AnthonyUccello** [comment]
After fixing the nil token issue this problem is resolved.

**Comment by 18295718240** [comment]
Please ask me how to solve it in the end. I also encounter the same problem. When guest users click live, error to get channel endpoint
Error to get channel endpoint: Error Domain=com.amazonaws.AWSKinesisVideoErrorDomain Code=1 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=AccessDeniedException:http://internal.amazon.com/coral/com.amazon.coral.service/}
