### ISSUE TITLE
Crash: AWSS3TransferUtility.m line 1451

### ISSUE THREAD

**Issue by pablogeek** [aws-amplify/aws-sdk-ios#1249]
I opened this two weeks ago but I have this crash again from few users. Not happening very often
https://github.com/aws-amplify/aws-sdk-ios/issues/1232

AWSS3TransferUtility.m line 1451
Fatal Exception: NSInvalidArgumentException
Cannot read file at file:///var/mobile/Containers/Data/Application/CDD5C0C8-4F6A-4CBD-B901-1D13ABFBC14E/Library/Caches/S3TransferUtility/102A076D-946B-443E-B8B2-A45D0D2D5ED1

**To Reproduce**
It is not reproducible in my devices

**Which AWS service(s) are affected?**
S3
**Expected behavior**
Not crash

**Environment(please complete the following information):**

* SDK Version: [e.g. 2.6.29] 2.9.1
* Dependency Manager: Cocoapods
* Swift Version : 4.2

**Device Information (please complete the following information):**
Ipad mini 2, iOS 12

**Comment by simeondrage** [comment]
Any news on this please? Affecting quite a few of our customers 
Possibly linked to us upgrading to 2.9.1

**Comment by cbommas** [comment]
@simeondrage 
I believe this issue happens when the `part` file is deleted before we kick off the upload task. Possibly more likely to happen if the amount of storage on the device is low and the OS is trying to reclaim space. I will work on putting  logic to safeguard from crashing when this occurs.

**Comment by simeondrage** [comment]
thank you. I think we might go back to 2.6.35 in the meantime as all our issues started when we upgraded from that!

**Comment by cbommas** [comment]
@simeondrage 
I fully understand. I am working on a fix and will update this thread once I have more information.

**Comment by royjit** [comment]
We made a fix to handle the crash in #1627. This will go to master in the next release.

**Comment by kvasukib** [comment]
This has been released in `2.9.10` version of the SDK.

**Comment by AMORFATI-TRL** [comment]
This crash is still happening in **2.11.0**
My crash log says AWSS3TransferUtility.m - Line 1074
`Fatal Exception: NSInvalidArgumentException
Cannot read file at file:///var/mobile/Containers/Data/Application/ABFF803E-96FA-4AE5-A790-E2B755EC9226/Library/Application%20Support/MeerkatSessionManager/sessions/5CF60E3A-63DF-4E69-9C16-94A94D865101.1571063762

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x19ff9127c __exceptionPreprocess
1  libobjc.A.dylib                0x19f16b9f8 objc_exception_throw
2  CFNetwork                      0x1a0606fd8 -[__NSURLBackgroundSession placeholderErrorWithURL:]
3  CFNetwork                      0x1a054e338 -[__NSURLBackgroundSession _onqueue_uploadTaskForRequest:uploadFile:bodyData:completion:]
4  CFNetwork                      0x1a06073ec __80-[__NSURLBackgroundSession uploadTaskForRequest:uploadFile:bodyData:completion:]_block_invoke
5  CFNetwork                      0x1a0607120 __68-[__NSURLBackgroundSession performBlockOnQueueAndRethrowExceptions:]_block_invoke
6  libdispatch.dylib              0x19f9d17d4 _dispatch_client_callout
7  libdispatch.dylib              0x19f97fc18 _dispatch_lane_barrier_sync_invoke_and_complete
8  CFNetwork                      0x1a0544664 -[__NSURLBackgroundSession performBlockOnQueueAndRethrowExceptions:]
9  CFNetwork                      0x1a054d26c -[__NSURLBackgroundSession uploadTaskForRequest:uploadFile:bodyData:completion:]
10 AWSS3                          0x10383710c __55-[AWSS3TransferUtility createUploadTask:startTransfer:]_block_invoke + 1074 (AWSS3TransferUtility.m:1074)
11 AWSCore                        0x1035767f8 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 331 (AWSTask.m:331)
12 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
13 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
14 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
15 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
16 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
17 AWSCore                        0x103576a04 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 340 (AWSTask.m:340)
18 AWSCore                        0x1035768ac __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 348 (AWSTask.m:348)
19 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
20 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
21 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
22 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
23 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
24 AWSCore                        0x103576a04 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 340 (AWSTask.m:340)
25 AWSCore                        0x1035767f8 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 331 (AWSTask.m:331)
26 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
27 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
28 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
29 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
30 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
31 AWSCore                        0x1035768c8 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 354 (AWSTask.m:354)
32 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
33 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
34 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
35 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
36 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
37 AWSCore                        0x103576a04 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 340 (AWSTask.m:340)
38 AWSCore                        0x1035768ac __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 348 (AWSTask.m:348)
39 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
40 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
41 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
42 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
43 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
44 AWSCore                        0x103576a04 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 340 (AWSTask.m:340)
45 AWSCore                        0x1035767f8 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 331 (AWSTask.m:331)
46 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
47 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
48 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
49 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
50 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
51 AWSCore                        0x103576a04 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 340 (AWSTask.m:340)
52 AWSCore                        0x1035767f8 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 331 (AWSTask.m:331)
53 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
54 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
55 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
56 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
57 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
58 AWSCore                        0x103576a04 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 340 (AWSTask.m:340)
59 AWSCore                        0x1035768ac __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 348 (AWSTask.m:348)
60 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
61 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
62 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
63 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
64 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
65 AWSCore                        0x103576a04 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 340 (AWSTask.m:340)
66 AWSCore                        0x1035768ac __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 348 (AWSTask.m:348)
67 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
68 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
69 AWSCore                        0x1035763f8 -[AWSTask runContinuations] + 308 (AWSTask.m:308)
70 AWSCore                        0x103575f60 -[AWSTask trySetResult:] + 247 (AWSTask.m:247)
71 AWSCore                        0x1035773d0 -[AWSTaskCompletionSource setResult:] + 45 (AWSTaskCompletionSource.m:45)
72 AWSCore                        0x103590160 __61-[AWSURLSessionManager URLSession:task:didCompleteWithError:]_block_invoke + 417 (AWSURLSessionManager.m:417)
73 AWSCore                        0x103576d9c __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 398 (AWSTask.m:398)
74 AWSCore                        0x1035767f8 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 331 (AWSTask.m:331)
75 AWSCore                        0x103545288 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 66 (AWSExecutor.m:66)
76 AWSCore                        0x1035457b0 -[AWSExecutor execute:] + 131 (AWSExecutor.m:131)
77 AWSCore                        0x103576660 -[AWSTask continueWithExecutor:block:cancellationToken:] + 368 (AWSTask.m:368)
78 AWSCore                        0x103576cfc -[AWSTask continueWithExecutor:successBlock:cancellationToken:] + 394 (AWSTask.m:394)
79 AWSCore                        0x103576e24 -[AWSTask continueWithSuccessBlock:] + 404 (AWSTask.m:404)
80 AWSCore                        0x10358f2e0 -[AWSURLSessionManager URLSession:task:didCompleteWithError:] + 260 (AWSURLSessionManager.m:260)
81 CFNetwork                      0x1a0714420 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.182
82 Foundation                     0x1a09f5ef8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
83 Foundation                     0x1a09023e0 -[NSBlockOperation main]
84 Foundation                     0x1a09018c8 -[__NSOperationInternal _start:]
85 Foundation                     0x1a09f7c7c __NSOQSchedule_f
86 libdispatch.dylib              0x19f9d0a38 _dispatch_call_block_and_release
87 libdispatch.dylib              0x19f9d17d4 _dispatch_client_callout
88 libdispatch.dylib              0x19f976018 _dispatch_continuation_pop$VARIANT$mp
89 libdispatch.dylib              0x19f9756dc _dispatch_async_redirect_invoke
90 libdispatch.dylib              0x19f98202c _dispatch_root_queue_drain
91 libdispatch.dylib              0x19f9828d0 _dispatch_worker_thread2
92 libsystem_pthread.dylib        0x19fbb11b4 _pthread_wqthread
93 libsystem_pthread.dylib        0x19fbb3cd4 start_wqthread`
