### ISSUE TITLE
AWS IoT Register Shadow

### ISSUE THREAD

**Issue by karasahinemre** [aws-amplify/aws-sdk-ios#1250]
**Environment**

* SDK Version: [2.9.1]
* Dependency Manager:  Cocoapods

Hi there,

When I am using iOS SDK register function for registering shadows its automatically subscribe 7 different topics.

In my project, I am using shadows for my smart home devices online status. 

When user has more than 7 devices I can not subscribe any of the device topics so I can not receive any messages from devices.

Are there any way to limit these shadow registration topics subscription?

For example I don't want to listen delta, rejected, documents etc. topics.

**Comment by docee** [comment]
Why not use Wildcards?

https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

**Comment by karasahinemre** [comment]
My system uses the Device Shadows service to monitor updates to the states of individual devices (which correspond in a 1:1 fashion to Shadow instances) in the user's ecosystem. My app requires to keep track of greater than 50 devices at a given time if the user's ecosystem contains more than 50, meaning i must subscribe to topic $aws/things/<THING_NAME>/update/accepted for greater than 50 <THING_NAME>s. I cannot use the topic wildcards to, for instance, keep track of all things with only a single topic subscription ($aws/things/+/update/accepted), as doing so would mean that every app client would be notified every time any device in the app's universe (which spans many user ecosystems) is updated.

**Comment by karasahinemre** [comment]
Hi,

Any update?
