### ISSUE TITLE
The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.

### ISSUE THREAD

**Issue by omaraksim** [aws-amplify/aws-sdk-ios#1251]
I'm using AWSMobileClient for Cognito 
signIn seems to work properly but when trying signup this error gets thrown, googling this seems to be related to a bug
UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-02-27 17:23:16.336573+0100 Eggplore[3167:36325] [NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
The operation couldn’t be completed. (AWSMobileClient.AWSMobileClientError error 9.)

To Reproduce
just try to signup as the doc suggests using this method
AWSMobileClient.sharedInstance().signUp

i'm using Xcode 10.1 and  AWSMobileClient 2.9.1

**Comment by omaraksim** [comment]
trying this with a real device throws this error
plus I should mention that this only happens for signup, signin is working properly 

2019-02-28 12:02:47.579140+0100 Eggplore[667:103982] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x282481f20, domain=1, instance=1>
The operation couldn’t be completed. (AWSMobileClient.AWSMobileClientError error 9.)

I'm using this config

`{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-2:xxxxx",
                "Region": "us-east-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-2_xxxx",
            "AppClientId": "xxxxx",
            "AppClientSecret": "xxxxx",
            "Region": "us-east-2"
        }
    }
}`

**Comment by omaraksim** [comment]
I finally found fixed it, 
for people who still have this issue this error log is a bit misleading I hope to be changed to something more meaningful
this error means that you have an invalid attribute or more sent in the signup
for my case it was the password not satisfying the rules (letters, number, uppercase, ... )

**Comment by desokroshan** [comment]
The error message suggests issue with the network connectivity. For the case of error message for invalid attributes, we will investigate the current error messages and update them if required.

**Comment by rohandubal** [comment]
This is likely an Xcode 10 issue: https://stackoverflow.com/questions/52455652/xcode-10-seems-to-break-com-apple-commcenter-coretelephony-xpc

Could you please try the solution mentioned in the stackoverflow post and check if it fixes the issue for you?
