### ISSUE TITLE
Crash: NSGenericException when uploading using AWSTransferUtility

### ISSUE THREAD

**Issue by pablogeek** [aws-amplify/aws-sdk-ios#1252]
Fatal Exception: NSGenericException*** Collection <__NSDictionaryM: 0x165d96b0> was mutated while being enumerated.

AWSS3TransferUtility.m line 1366
__130-[AWSS3TransferUtility internalUploadFileUsingMultiPart:bucket:key:contentType:expression:temporaryFileCreated:completionHandler:]_block_invoke

**Which AWS service(s) are affected?**
S3 uploads

**Environment(please complete the following information):**
 - AWS iOS SDK Version: 2.9.1
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2
 - Device: iPad mini
 - iOS 9

**Comment by cbommas** [comment]
@pablogeek 

Thanks for bringing this to my attention. I believe this is the same issue as #1230. I have a fix for this that I am testing and targeting to include in the next rev of the SDK.

**Comment by pablogeek** [comment]
Great! Thank you!

**Comment by cbommas** [comment]
@pablogeek 

The fix for #1230 is available in the latest rev of the SDK - 2.9.2
Please give this a try when you can and let me know if you are still facing this issue.

**Comment by cbommas** [comment]
Closing this issue as I haven't heard back. Please feel free to post here if still facing issues.
