### ISSUE TITLE
Request for allowing the client to customize/specify the filePath in AWSCognitoSQLiteManager

### ISSUE THREAD

**Issue by Aravind-V-Symantec** [aws-amplify/aws-sdk-ios#1253]
**Which AWS Services is the feature request for?**
AWSCognitoSQLiteManager

**Is your feature request related to a problem? Please describe.**
We are unable to set a custom path to save the DBs managed by AWS. Due to this, there is no way to share a DB between the App and App-extensions and among apps, using shared containers with the help Associated App- groups in iOS. Having multiple copies of the same DB under the App's sandbox and the Extension's sandbox, creates redundancy.

**Describe the solution you'd like**
Allow the client to provide/customize the filePath where the DBs can be stored.

**Describe alternatives you've considered**
We have considered maintaining multiple copies of the files/DBs in each app' or extension's sandbox, rather than maintaining just one copy in a shared container that can be shared among apps/extensions belonging to the same app-group.

**Additional context**
If there exists a way to get around this, please let us know.

**Comment by kvasukib** [comment]
@Aravind-V-Symantec Thank you for reporting to us. CognitoSync SDK is deprecated and we do not address feature requests in the AWSCognito Sync SDK. We recommend you to migrate to AWS AppSync (https://aws-amplify.github.io/docs/ios/api#graphql-realtime-and-offline).

If you migrate to AWS AppSync, you can accomplish this use-case by passing a custom path for the local database through the cache configuration.

Documentation: https://aws-amplify.github.io/docs/ios/api#client-initialization

```swift
// You can choose the directory in which AppSync stores its persistent cache databases
let cacheConfiguration = try AWSAppSyncCacheConfiguration()
```

I am assigning this issue to our Product Manager to come up with migration guide to move from Cognito Sync to AppSync.

**Comment by royjit** [comment]
Closing this issue as wont fix.
