### ISSUE TITLE
isSignedIn & isLoggedIn are false even though user is logged in

### ISSUE THREAD

**Issue by daviskoh** [aws-amplify/aws-sdk-ios#1258]
**Describe the bug**

After successfully logging in, and relaunching the app, `AWSMobileClient.sharedInstance().isSignedIn` & `AWSMobileClient.sharedInstance().isLoggedIn` are both false. `AWSMobileClient.sharedInstance().currentUserState` is also `unknown`.

**To Reproduce**

A code sample or steps:

1) Login:

```
AWSMobileClient.signIn(username: username, password: password) { signInResult, error in
  ...
}
```

2) Relaunch app

Confirm that you are logged in:

```
AWSMobileClient.sharedInstance().getUserAttributes { attrs, error in
  print(attrs) // should print user attributes
  print(error) // should be nil
}
```

3) Signout:

```
AWSMobileClient.sharedInstance().signOut()
```

4) Repeat step 2) and see that you **were** indeed logged in because `getUserAttributes()` should not fail.

**Which AWS service(s) are affected?**

AWSMobileClient

**Expected behavior**

Ideal: For User to stay logged in.
Will Accept with Justification: Reason why values in **Describe the bug** Section are returning `false` even though requests are succeeding.

**Screenshots**

**Environment(please complete the following information):**
 - AWS iOS SDK Version: 2.8.4
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2.1
 - Device: Simulator
 - iOS Version: iOS 12.1
 - Specific to simulators:  No

**Additional context**

**Comment by kvasukib** [comment]
@daviskoh Sorry for the inconvenience caused. Have you initialized the `AWSMobileClient` when the app is launched? You could do this either in `AppDelegate` or `ViewController`?

The docs for initialize is here: https://aws-amplify.github.io/docs/ios/authentication#initialization

```swift
import AWSMobileClient

    override func viewDidLoad() {
        super.viewDidLoad()
        AWSMobileClient.sharedInstance().initialize { (userState, error) in
            if let userState = userState {
                print("UserState: \(userState.rawValue)")
            } else if let error = error {
                print("error: \(error.localizedDescription)")
            }
        }
    }
```

```
@IBOutlet weak var signInStateLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        AWSMobileClient.sharedInstance().initialize { (userState, error) in
            if let userState = userState {
                switch(userState){
                case .signedIn:
                        DispatchQueue.main.async {
                            self.signInStateLabel.text = "Logged In"
                    }
                case .signedOut:
                    AWSMobileClient.sharedInstance().showSignIn(navigationController: self.navigationController!, { (userState, error) in
                            if(error == nil){       //Successful signin
                                DispatchQueue.main.async {
                                    self.signInStateLabel.text = "Logged In"
                                }
                            }
                        })
                default:
                    AWSMobileClient.sharedInstance().signOut()
                }
                
            } else if let error = error {
                print(error.localizedDescription)
            }
        }
    }
```

When the app is launched again, initialize would fetch the state stored in keychain during the previous signin and resumes your previously signed-in session.

**Comment by daviskoh** [comment]
Gotcha. I was mistaken in thinking that `addUserStateListener` would be able to handle initial state as well. Thank you.
