### ISSUE TITLE
Limit a query with secondary index return no results

### ISSUE THREAD

**Issue by nourahassan** [aws-amplify/aws-sdk-ios#1261]
I am having a query that works fine and return results from dynamoDB. When I add a limit  to the query expression it returns zero results.

Here's the code:

```
let queryExpression = AWSDynamoDBQueryExpression()
queryExpression.keyConditionExpression = "#id = :id"
queryExpression.filterExpression = "#type = :type"
queryExpression.expressionAttributeNames = ["#id": "id", "#type" : "type"]
queryExpression.expressionAttributeValues = [":id":  targetId, ":type":  filterType]
queryExpression.indexName = "idx_id-time"
queryExpression.scanIndexForward = false
dynamoDbObjectMapper.query(entity, expression: expression) { output, error in
    
}
        
```

This code returns *62* items, adding limit returns *zero*

```
queryExpression.limit = 1
```

**Environment(please complete the following information):**
 - AWS iOS SDK Version: 2.9.1
 - Dependency Manager: Carthage
 - Swift Version : 4.2
 - Device: Simulator
 - iOS Version: iOS 12.1
 - Specific to simulators: No

**Comment by kvasukib** [comment]
@nourahassan Sorry for the inconvenience caused. Have you tried with other limit values? Does this happen for any query expression and any dynamodb table?

**Comment by nourahassan** [comment]
I only tried on this case. I will let you know when I try with different table.

**Comment by kvasukib** [comment]
@nourahassan 
Do you have a secondary index configured on your DynamoDb table?
What is the number of records you get when you do not specify a limit?

**Comment by nourahassan** [comment]
Without setting limit it will return 30 records and with limit it returns no records. And yes the index is configured on the DynamoDB table.

**Comment by kvasukib** [comment]
@nourahassan This is how pagination with filters works with DynamoDB. When you have a filter expression and limit, DynamoDB first applies the limit and gets limit number of records and then applies the filter on top of it. [limit first, filter second strategy].

You would be getting a pagination token with the response which you can use to retrieve the next set of records.

Documentation:

In a request, set the Limit parameter to the number of items that you want DynamoDB to process before returning results.

In a response, DynamoDB returns all the matching results within the scope of the Limit value. For example, if you issue a Query or a Scan request with a Limit value of 6 and without a filter expression, DynamoDB returns the first six items in the table that match the specified key conditions in the request (or just the first six items in the case of a Scan with no filter). If you also supply a FilterExpression value, DynamoDB will return the items in the first six that also match the filter requirements (the number of results returned will be less than or equal to 6).

For either a Query or Scan operation, DynamoDB might return a LastEvaluatedKey value if the operation did not return all matching items in the table. To get the full count of items that match, take the LastEvaluatedKey value from the previous request and use it as the ExclusiveStartKey value in the next request. Repeat this until DynamoDB no longer returns a LastEvaluatedKey value.

For further information: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.Pagination

**Comment by nourahassan** [comment]
Is there a way to get the latest record with some criteria on DynamoDB using one call? 

Can I also suggest to rename the expression.limit to be `pageSize` something to reflect what did you explain about its functionality.

**Comment by kvasukib** [comment]
@nourahassan Can you elaborate on what do you mean by the `latest` record? Is it the last updated record in the table?

For renaming, I will take this feedback to the team.

**Comment by nourahassan** [comment]
Say I am having posts by some authors, posts can be categorized. I want to show latest post an author wrote in a specific category.

In SQL db, the query should look like:

`select * from posts where author = x and category = y ordered by time desc limit 1`

**Comment by minbi** [comment]
Hi @nourahassan ,

This is service behavior that we don't have control over. We will send your feedback to the service team, but the SDKs won't be fixing this behavior.
