### ISSUE TITLE
AWSIoT how I can disable reconnect feature

### ISSUE THREAD

**Issue by HayTran94** [aws-amplify/aws-sdk-ios#1263]
**State your question**
I want to disable reconnect feature to make my own reconnect mechanism.

**Which AWS Services are you utilizing?**
AWSIoT

**Provide code snippets (if applicable)**
I can not found anywhere.

**Environment(please complete the following information):**
 - SDK Version: 2.9.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: Any device
 - iOS Version: Any version

**Comment by cbommas** [comment]
@HayTran94 

There isn't an option currently to disable auto-retries currently. A work around would be to  set the `baseReconnectTimeInterval` to a large number and issuing a `disconnect` on the client when you get a connection error. Explicitly calling `disconnect` will prevent re-tries from happening.

See #1057 for more information on this topic.

**Comment by HayTran94** [comment]
@cbommas 
Thanks for your explanation. I will implement that as your recommend.
