### ISSUE TITLE
[Lex] Support passing requestAttributes in AWSLexInteractionKit

### ISSUE THREAD

**Issue by ikirincic** [aws-amplify/aws-sdk-ios#1264]
AWSLex

I need to send request attributes in some cases when making requests with interactionKit.
On android requestAttributes is a parameter in text and voice request methods but its missing in iOS version. 
Will this be added to iOS?
Is there an alternative for setting requestAttributes?

android method with desired functionality:
 public void textInForAudioOut(final String text, final Map<String, String> sessionAttributes, final Map<String, String> requestAttributes)

**Comment by kvasukib** [comment]
@ikirincic Thank you for reporting to us. Currently the `AWSLexInteractionKit` doesn't support passing in `requestAttributes`. It only supports session attributes and global session attributes in its API. I am tagging this issue as a feature request.
