### ISSUE TITLE
Push notifications for any change in DB (CRUD) when app is closed

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/aws-sdk-ios#1266]
**State your question**
I am building an iOS app using AWS Amplify with appsync. AppSync does provide a way to subscribe to changes in data and it works when the app is running. If the app is closed, how do we achieve the same result? I was looking into AWS Pinpoint but couldn't find a way to trigger a notification based on CRUD operation on DB. Simple example in this case can a chat application where-in if the user is using the app then he/she will receive all the messages but if the app is closed new messages won't be posted unless app is restarted. At least user should notified that a new message has arrived based on updates in DB.
**Which AWS Services are you utilizing?**
AppSync
Cognito
DynamoDB
Analytics (Pinpoint)
Storage (S3)
**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]AWSAppSync (2.10.2), AWSMobileClient (2.8.4), AWSPinpoint (2.8.4)
 - Dependency Manager: [e.g. Cocoapods, Carthage] Cocoapods
 - Swift Version : [e.g. 4.0] 4.2

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] Simulator
 - iOS Version: [e.g. iOS 11.4] iOS 12.0
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@rohit3d2003 I have transferred the issue to AWS AppSync iOS SDK repo: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/195

I will close this issue.
