### ISSUE TITLE
Passing nil to client secret causes index out of bounds crash 

### ISSUE THREAD

**Issue by afanaian** [aws-amplify/aws-sdk-ios#1272]
**Describe the bug**
Using AWSCognitoIdentityUserPoolConfiguration passing nil for secret causes an index crash. 

Passing nil to the optional secret field causes index out of bounds crash. 
 '*** -[__NSCFConstantString substringFromIndex:]: Index 9223372036854775808 out of bounds; string length 0'

**Work around: **
Pass empty string ""  - Causes error:
=App client is not configured for secret but secret hash was received 

**To Reproduce**
A code sample or steps:
1. Create a AWSCognitoIdentityUserPoolConfiguration and pass nil to the secret field

Your code
let config = AWSCognitoIdentityUserPoolConfiguration(clientId: AWSConfig.clientID, clientSecret: nil, poolId: AWSConfig.poolID)

**Which AWS service(s) are affected?**
AWSCognitoIdentityProvider

**Expected behavior**
Not crash

**Environment(please complete the following information):**
 - AWS iOS SDK Version: 
  AWSCognitoAuth (2.9.1):
  AWSCognitoIdentityProviderASF (= 1.0.1)
  AWSCognitoIdentityProvider (2.9.1):
  AWSCognitoIdentityProviderASF (= 1.0.1)
  AWSCore (= 2.9.1)
  AWSCognitoIdentityProviderASF (1.0.1)
  AWSCore (2.9.1)

 - Dependency Manager: Cocoapods
 - Swift Version : 4.2
 - Device: iPhone XS + literally every device
 - iOS Version: 12.1.2
 - Specific to simulators:  No

**Comment by kvasukib** [comment]
@afanaian Sorry for the inconvenience caused.

I can see in `AWSCognitoUserPool` when we try to access the `clientSecret`. There is a nil check before the `clientSecret` can be used to compute the secret hash.

From https://github.com/aws-amplify/aws-sdk-ios/blob/6ab2982040eaca984eab38e311b98c3b9227b773/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m#L300 I can see we do not access the `clientSecret` before checking for nil.

Can you paste the code snippet and the stacktrace so I could spot exactly where the crash occurs?

**Comment by afanaian** [comment]
> @afanaian Sorry for the inconvenience caused.
> 
> I can see in `AWSCognitoUserPool` when we try to access the `clientSecret`. There is a nil check before the `clientSecret` can be used to compute the secret hash.
> 
> From
> 
> [aws-sdk-ios/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m](https://github.com/aws-amplify/aws-sdk-ios/blob/6ab2982040eaca984eab38e311b98c3b9227b773/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m#L300)
> 
> Line 300 in [6ab2982](/aws-amplify/aws-sdk-ios/commit/6ab2982040eaca984eab38e311b98c3b9227b773)
> 
>  if(self.userPoolConfiguration.clientSecret == nil) 
> I can see we do not access the `clientSecret` before checking for nil.
> Can you paste the code snippet and the stacktrace so I could spot exactly where the crash occurs?

My apologies. The issue turned out to be a nil secret + empty Pool ID. The empty pool was causing a crash in this line: 
- (NSString*) strippedPoolId {
    return [self.userPoolConfiguration.poolId substringFromIndex:[self.userPoolConfiguration.poolId rangeOfString:@"_" ].location+1];
}

Closing issue.
