### ISSUE TITLE
Deleting object from S3

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/aws-sdk-ios#1274]
**State your question**
I am using AWS Amplify CLI to create S3 buckets to upload/download images. This works great with AWSS3TransferUtility using Cognito but there isn't an example to delete the same object if needed. I tried to delete the object using custom code but I am getting 'Access Denied' issues.
**Which AWS Services are you utilizing?**
AWS S3, Cognito

**Provide code snippets (if applicable)**
<img width="653" alt="Screen Shot 2019-03-09 at 4 39 12 PM" src="https://user-images.githubusercontent.com/16943885/54079084-e4515900-4289-11e9-8900-ca8cdc83eb75.png">

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29] AWSS3 (2.8.4), AWSMobileClient (2.8.4)
 - Dependency Manager: [e.g. Cocoapods, Carthage] Cocoapods
 - Swift Version : [e.g. 4.0] 4.2

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] Simulator
 - iOS Version: [e.g. iOS 11.4] iOS 12.0
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@rohit3d2003 Sorry for the inconvenience caused. Do you have the required IAM policy added to the IAM roles (Authenticated / Unauthenticated) of your Cognito Identity-pool id? 

Ideally, your IAM role should have a policy like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:DeleteObject",
            "Resource": "arn:aws:s3:::${bucketName}/"
        }
    ]
}
```

**Comment by rohit3d2003** [comment]
@kvasukib - Thanks for the suggestion. The policy does have all the necessary permissions but I forgot to pass 'public' in the key while deleting the file
