### ISSUE TITLE
Error uploading images to S3 using Cognito authentication

### ISSUE THREAD

**Issue by JimCSaratoga** [aws-amplify/aws-sdk-ios#1275]
**State your question**

I am having an issue with my first test to implement S3 uploads using Swift 4.2 / cocoa pods / Amplify config.  

The file uploads (including creating the private file structure, under a user_identity_id folder) however the file _resulting is a 0B file_ and is owned by the S3 bucket owner (viewing on the AWS S3 dashboard).  This occurs for tests conducted with image/jpeg and a text/plain  respective files.    I've followed the procedure described in the standard GitHub repository https://aws-amplify.github.io/docs/ios/storage.  Additionally I used Amplify to create the cloud service (adding both auth and storage).  I'm logged in using Cognito auth.

The error output is nil and I'm logging the "Error: Failed." out of the else statement for progressView not equaling 1.0. I have added auth followed by storage as per the documentation(https://aws-amplify.github.io/docs/ios/storage) Transfer Acceleration is not enabled

I've retrieved the user_identity_id and appended it to the key name.  Upon testing using a public/{user_identity_id} and private, both uploads result with a 0B file.

Thanks for help in advance. I've exhausted everything I can think of that would be causing this.
many thanks, Jim

Here is code snippet:

```
import UIKit
import AWSMobileClient
import AWSS3

class ViewController: UIViewController {
  
    @IBOutlet weak var progressView: UIProgressView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        progressView.progress = 0.0
        
//        
        let myBucket = "testawss35a524623b89e43XXXXXXXXXXXX"
        let myKey = "YahooArticle.txt"
        
        guard let user_identity_id = AWSMobileClient.sharedInstance().identityId else { return }
        print("user_identity_id = \(user_identity_id)")
        
        let privateKey = "private/" + user_identity_id + "/" + myKey
        print("privateKey = \(privateKey)")
        
        let publicKey = "public/" + user_identity_id + "/" + myKey
        print("publicKey = \(publicKey)")
        
        AWS_S3_uploadData(bucket: myBucket, key: publicKey)        
    } // end viewDidLoad
    
    
    func AWS_S3_uploadData(bucket: String, key: String) {
        
        let data: Data = Data() // Data to be uploaded
        
        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = {(task, progress) in
            DispatchQueue.main.async(execute: {
                self.progressView.progress = Float(progress.fractionCompleted)
                // Do something e.g. Update a progress bar.
            })
        }

        
        let completionHandler: AWSS3TransferUtilityUploadCompletionHandlerBlock = { (task, error) -> Void in DispatchQueue.main.async(execute: {
            if let error = error {
                NSLog("Failed with error: \(error)")

            }
            else if(self.progressView.progress != 1.0) {
                NSLog("Error: Failed.")

            } else {
                NSLog("Success.")

            }
        })
        }
        
        var refUploadTask: AWSS3TransferUtilityTask?
        
        let transferUtility = AWSS3TransferUtility.default()
        
        transferUtility.uploadData(data,
                                   bucket: bucket,
                                   key: key,
                                   contentType: "text/plain",
//                                   contentType: "image/jpeg",
                                   expression: expression,
                                   completionHandler: completionHandler).continueWith {
                                    (task) -> AnyObject? in
                                    if let error = task.error {
                                        print("Error: \(error.localizedDescription)")
                                    }
                                    
                                    if let uploadTask = task.result {
                                        print("upload result \(String(describing: task.result))")
                                        refUploadTask = uploadTask
                                        // Do something with uploadTask.
                                    }
                                    return nil;
        }
    }
    
    func AWS_S3_downloadData(bucket: String, key: String) {
        let expression = AWSS3TransferUtilityDownloadExpression()
        expression.progressBlock = {(task, progress) in DispatchQueue.main.async(execute: {
            // Do something e.g. Update a progress bar.
        })
        }
        
        var completionHandler: AWSS3TransferUtilityDownloadCompletionHandlerBlock?
        completionHandler = { (task, URL, data, error) -> Void in
            DispatchQueue.main.async(execute: {
                // Do something e.g. Alert a user for transfer completion.
                // On failed downloads, `error` contains the error object.
            })
        }
        
        let transferUtility = AWSS3TransferUtility.default()
        transferUtility.downloadData(
            fromBucket: bucket,
            key: key,
            expression: expression,
            completionHandler: completionHandler
            ).continueWith {
                (task) -> AnyObject? in if let error = task.error {
                    print("Error: \(error.localizedDescription)")
                }
                
                if let _ = task.result {
                    // Do something with downloadTask.
                    
                }
                return nil;
        }
    }
```    

**Which AWS Services are you utilizing?**

Cognito / S3

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - AWSMobileClient 2.8.4 / AWSS3 2.8.4
 - Dependency Manager: Cocoa-pods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhoneXR via Simulator, iPhone 8Plus via direct connect
 - iOS Version: iOS 12.1

**Comment by JimCSaratoga** [comment]
Obviously I don’t know how to do a code snipit correctly.  Sorry about that

**Comment by kvasukib** [comment]
@JimCSaratoga Sorry for the inconvenience caused.

What is the size of the file you are uploading? Does the file exist on the device?
Did you get state and progress updates for the transfer?

**Comment by JimCSaratoga** [comment]
Thanks for the quick reply.  The files are manually in the main group folder of the Xcode app at the moment.  The txt file is 2kb and the jpeg is 26kb.  

Unfortunately there is no progress update (I've added an IBOutlet for a progress bar) yet just from a simple print of the progress object results with

"progress = <NSProgress: 0x60000335d540> : Parent: 0x0 / Fraction completed: 0.0000 / Completed: 0 of 0" 

In the console log  with verbose logging this is all I get:  
"2019-03-10 13:26:04.688630-0400 Test-AWS-S3[49152:26607902] Error: Failed."

(that's with log level at verbose from my AppDelegate.
AWSDDLog.sharedInstance.logLevel = .verbose

I can programmatically load the files from the IB - would that be the cause ?  At the moment as mentioned above they are at the same level as my ViewController & AppDelegate files for the purpose of testing  (apologies if that's the issue)

**Comment by kvasukib** [comment]
@JimCSaratoga Thank you for the quick response. Assigning to @cbommas to triage the issue further.

**Comment by JimCSaratoga** [comment]
@kvasukib @cbommas Just thinking through the upload function.  

I'm wondering if the file structure in Xcode needs to replicate the private/{_user_identity_id_}/data... as it does with the delivery of the key to the transferUtility.uploadData function.  If so then it represents a couple of issues that I can think of - first is that it would be very hard to replicate the structure within the app and secondly if so the user_identity_id has a **:** character in it (us-east-1:) so it won't be a valid folder name in macOS/xcode to pull the source file from (including using FileManager for sandbox storage / archiving).  

My guess is that I get zero progress because the function is looking to find the source file that it created a container for in S3 in the private/us-east1:71fc...../ folder within the iOS app.  

Maybe it would be better to change the function to deliver a file into it (using a preferred folder structure) and secondly a URL structure to tell S3 where to place the file.  

I'm assuming if I'm correct about the assumption above that it's solely an issue using Cognito auth (AWSMobileClient) since the private/ public/ and protected/ folder structure  would yield a permissions error trying to place a file anywhere else including the root of the S3 bucket.   

hope this is helpful - again thank you for looking into this for me.

**Comment by JimCSaratoga** [comment]
Morning gents -  appreciating that you are answering and researching multiple inquiries like this one - any thoughts on the 0B file that I could potentially look at to assist ?  Thank  you !

**Comment by cbommas** [comment]
@JimCSaratoga 

Answer to the first question: The structure or name of the local file doesn't have any bearing on where it is stored on the server. It just needs to be a valid path that your app/test code has access to.

Answer to the second question: Yes, that is correct. You should specify the path in the `key`. The `bucket` should be just the bucket name and shouldn't contain anything else

Answer to the third question: I don't believe that there is difference to giving the upload function a file or a data object. A file is probably better, because internally the data object is written to a temporary file before being transferred - giving the function a file would prevent that second write from happening.

Looking at your code sample and the fact that the upload does not make any progress, I am suspecting that the call to upload is getting an empty NSData object ( or is unable to access the file if you are specifying the file). The error object will typically have additional information that you can get to as follows

        let errorInfo = err.userInfo["Error"] as? [String: Any]
        if errorInfo != nil {
            print("Found error in response. Details are:")
            for element in errorInfo! {
                print(">> \(element.key): \(element.value)")
            }
          } 

Could you add this to your completion handler and see if that reveals further info about the exact error and post it here?

**Comment by JimCSaratoga** [comment]
Thanks for your reply - I've added it now but have a scope issue (error) with .userInfo being undefined in the handler error object defined using the AWSS3TransferUtilityUploadCompletionHandlerBlock structure to contain the task and error information.

(FYI i've renamed err to my container for the error object "error" unless I've missed this as a value of another object).   

Just to make sure i'm not misunderstanding - your guidance was to put the error handler above into my upload function block ?  

Apologies for being new to iOS programming and the AWSMobileClient environment in advance.  I greatly appreciate the help !!

**Comment by JimCSaratoga** [comment]
@cbommas it does in fact look like a Data object issue.  
If you have any sample code of how to convert an image (png/jpeg), pdf, etc  into the correct object format that the .uploadData function is looking for I would appreciate that.  
Also per the above I was unable to use your code snip to view the error dictionary as the userinfo parameter being in the error objects that were returned (could be another rookie mistake on my part again).  
Lastly I used the transferUtility.uploadFile function (vs. the transferUtility.uploadData function) and was able to upload files to the bucket.   Is there a  document describing the differences between these functions? Thanks again !

**Comment by rohandubal** [comment]
Hello @JimCSaratoga 

Here are couple ways in which we can inspect and handle the error:

```
          if let error = task.error {
                    NSLog("Error: %@",error.localizedDescription);
                    
                    let errorInfo = (error as NSError).userInfo["Error"] as? [String: Any]
                    if errorInfo != nil {
                        print("Found error in response. Details are:")
                        for element in errorInfo! {
                            print(">> \(element.key): \(element.value)")
                        }
                    }
                    
                    
                    if error._domain == AWSS3TransferUtilityErrorDomain {
                        if error._code == AWSS3TransferUtilityErrorType.serverError.rawValue {
                            //handle here
                        }
                    }
                }
```
