### ISSUE TITLE
Can I customize the 'Create new account' window?

### ISSUE THREAD

**Issue by RomeoDelta** [aws-amplify/aws-sdk-ios#1277]
When I ‘amplify add auth’, I added some standard attributes (nickname, family name, given name).
And I performed ‘amplify push’.
I added the codes into the View Controller.

                    AWSMobileClient.sharedInstance().showSignIn(
                        navigationController: self.navigationController!,
                        { (userState, error) in
                        if(error == nil){       //Successful signin
                            DispatchQueue.main.async {
                                print("Logged In")
                            }
                        }
                    })

When I clicked ‘Create new account’ in the signin window , the fields I added (for example, nickname) don’t show up,
and after I tried to sign up, a popup shows and it says
    ‘InvalidParameterException 
     Attributes did not conform to the schema: nickname: The attribute is required ….'

Are there any ways to customize the signup screen? Can I add the fields in the signup window?

**Comment by muellerfr** [comment]
Transferred the issue from  aws-amplify/docs to aws-amplify/aws-sdk-ios, since this appears to be a product question.

**Comment by kvasukib** [comment]
@RomeoDelta Thank you for reporting to us. I have added a note on https://github.com/aws-amplify/aws-sdk-ios/issues/1158 RFC about your request.

**Comment by RomeoDelta** [comment]
Thank you!
