### ISSUE TITLE
AWSMobileClient - Passing Pool ID / Client ID outside awsconfiguration file?

### ISSUE THREAD

**Issue by afanaian** [aws-amplify/aws-sdk-ios#1281]
I'm trying to initialize pool/client IDs without having to use .json or plist files. I've searched all over the docs + tried every sample SDK. Using AWSCognitoIdentityUserPool.register doesn't seem to take any effect on AWSMobileClient (For obvious reasons).
I'm just trying to sign in (depending on which pool they pick) --> Get tokens. 

Is this really not supported?

**Which AWS Services are you utilizing?**
AWSMobileClient

**Comment by rohandubal** [comment]
Hello @afanaian 

Unfortunately this is currently not supported. You will have to use an `awsconfiguration.json` file to provide the values for your UserPoolId etc.

Is there a specific reason why you are unable to add the values in a configuration file?

I will take this as a feature request to the team and update here once we prioritize it.

Best,
Rohan

**Comment by afanaian** [comment]
@rohandubal I don't have issues adding the values to the config file, but it isn't ideal to add the values at run time. The client requires to point to different user pools depending on what the server returns. I'll manually edit the config file for now, but please keep it as a feature request.

**Comment by rohandubal** [comment]
@afanaian thanks for the explanation. That makes sense, I will mark this as feature request and take it to the team!

**Comment by afanaian** [comment]
@rohandubal any chance there's a roadmap on when this change is coming?

**Comment by TizianoCoroneo** [comment]
@rohandubal I got exactly the same requirement for my application. Has this issue been placed on the roadmap? Otherwise I'll have to swizzle some configuration methods in the sdk... I would prefer not to go there.

**Comment by royjit** [comment]
This feature has been released in the latest SDK. More details here - https://aws-amplify.github.io/docs/ios/manualsetup#configure-using-an-in-memory-object.

Closing this issue, feel free to reach out if you have more questions.
