### ISSUE TITLE
Xcode hangs at archiving AWSMobileClient for WatchKit app

### ISSUE THREAD

**Issue by zhang-bo-lilly** [aws-amplify/aws-sdk-ios#1291]
The issue is isolated in a standalone barebone WatchKit project [here](https://github.com/zhang-bo-lilly/AWSMobileClientWatchKitFreeze). The app runs fine in the simulator. However, Xcode hangs during archiving. I am using Xcode 10.1, Swift 4, and the cocoa pods 1.5.3. Would be happy to know if there is anything wrong with my build settings.

**Comment by rohandubal** [comment]
Hello @zhang-bo-lilly 

Thanks for report this, I will investigate this and reply back with an update.

**Comment by rohandubal** [comment]
Hello @zhang-bo-lilly 

I clone the project and tried archiving and was able to do that successfully. It might be an issue with the local environment. Have you tried cleaning and building?
<img width="1081" alt="Screen Shot 2019-03-16 at 10 25 05 AM" src="https://user-images.githubusercontent.com/7157240/54479027-ebbaba00-47d5-11e9-80f1-d60373cee701.png">

Best,
Rohan

**Comment by zhang-bo-lilly** [comment]
Hello @rohandubal, thank you for testing it out. I have tried cleaning the build folder but the problem still exists, not only for the WatchKit app, but also for a standalone barebone iOS app. My Xcode is version 10.1 (10B61) and my OS is 10.13.6. If there is more information about my local environment you want to know, please let me know. 

<img width="1409" alt="Screen Shot 2019-03-16 at 1 57 45 PM" src="https://user-images.githubusercontent.com/42588744/54479585-98a42f80-47f4-11e9-8464-d5e24ad33cc9.png">
<img width="1497" alt="Screen Shot 2019-03-16 at 2 02 35 PM" src="https://user-images.githubusercontent.com/42588744/54479589-9cd04d00-47f4-11e9-9987-eb8cdb43216d.png">

**Comment by royjit** [comment]
Hi @zhang-bo-lilly Apologies for the delayed response. Are you still facing this issue? If yes, what error are you seeing for the Archive failure?

**Comment by zhang-bo-lilly** [comment]
Hi @royjit, thanks for checking back with me. I no longer need that pod in my application now and have no issue archiving.

**Comment by royjit** [comment]
Thanks for confirming. Closing the issue, feel free to reopen if you have more questions.
