### ISSUE TITLE
2.9.3 AWSMobileClient & AWSCognitoAuth compatibility

### ISSUE THREAD

**Issue by markfinlabs** [aws-amplify/aws-sdk-ios#1298]
I just wanted to note to developers that when upgrading from 2.9.1 to 2.9.3 my pod file which included both ```pod 'AWSCognitoAuth'``` and ```pod 'AWSMobileClient'``` caused build errors until I removed  ```pod 'AWSCognitoAuth'``` and replaced ```import AWSCognitoAuth``` with ```import AWSMobileClient``` in my project.

I am not requesting any change just noting simultaneous use of AWSCognitoAuth and AWSMobileClient seems now deprecated. Any comment on the new relationship between these two libraries from developers very welcome.

(I have read the 2.9.3 release note so realise AWSMobileClient may now 100% supersede AWSCognitoAuth. Possibly there is no reason now to still use AWSCognitoAuth?)

**Comment by rohandubal** [comment]
Hello @markfinlabs 

Apologies that you are having issues using the SDK. 

`AWSMobileClient` now includes features which cover the features included in `AWSCognitoAuth`, so you are correct in what you have noted. I am still curious about understanding the use-case where you need both `AWSMobileClient` and `AWSCognitoAuth`? Also as an implementation detail -- `AWSMobileClient` also includes the source code of `AWSCognitoAuth` as a dependency. 

Thanks,
Rohan

**Comment by markfinlabs** [comment]
Thanks for the amazingly quick response. We did have both AWSMobileClient and AWSCognitoAuth in our app because we are still undecided on whether to use the hosted UI or not (hopefully not) when accessing our user pool. So we have multiple auth solutions implemented.

However as AWSMobileClient is now a strict super-set of AWSCognitoAuth (as suspected when no source changes required and confirmed by you), we don't need to include both in our project explicitly any more and of course will explore moving everything over to updated AWSMobileClient API (hosted and non-hosted auth) as soon as we can.

What we're really hoping/waiting for is a solution for https://github.com/aws-amplify/aws-sdk-ios/issues/1259 or at least support for Cognito custom auth flows. : ). Then we will drop the hosted option fallback.

One question: does AWSMobileClient now also include AWSCognitoIdentityProvider as well (or are there any compatibility issues)?

**Comment by rohandubal** [comment]
@markfinlabs Understood, thanks for the detailed explanation!

`AWSMobileClient` currently takes a dependency on `AWSCognitoIdentityProvider` directly which would mean that there would be absolutely no compatibility issues.  And as you noted, for custom auth flow you might have to use `AWSCognitoIdentityProvider`.

**Comment by markfinlabs** [comment]
Okay, thanks, next thing after moving over to updated AWSMobileClient API will be to investigate custom auth flow with AWSCognitoIdentityProvider and how this works in conjunction with AWSMobileClient. And then examine pros/cons of this vs hosted UI.
