### ISSUE TITLE
Crash on logout (after Federated LogIn)

### ISSUE THREAD

**Issue by N1LaT** [aws-amplify/aws-sdk-ios#1302]
**Describe the bug**
Okay so I have no idea if I'm doing this right because the Docs about this are rather... thin.
I managed to get my app custom login (not drop in) working, via a Userpool as well as with Identities (Facebook, Google).
After the normal login routine has finished I call federeatedSignIn to let AWS know I signed in with a federated sign in. This is working, I can do Cognito DB querys for each user.
So far so good. But when I logout, the app handles not right and i can force a crash.
When logged in with a user from the userpool, logout works. But, when I logout from Facebook or Google not all states get updates accordingly.
For example:
I'm logged in with Facebook. Now I click on Logout.
So my facebook logout routine does:
FBSDKLoginManager().logOut()
FBSDKAccessToken.setCurrent(nil)
FBSDKProfile.setCurrent(nil)

After doing this, the following variables are still set:
AWSMobileClient.sharedInstance().isSignedIn stays true
AWSMobileClient.sharedInstance().currentUserState == .signedIn is false
AWSMobileClient.sharedInstance().identityId is not nil

Therefore I still can do DB querys, even if the user logged out.
When I call AWSMobileClient.sharedInstance().signOut() after this,
the app crashes at:
 internal func performUserPoolSignOut() {
        self.userpoolOpsHelper.passwordAuthTaskCompletionSource?.set(error: AWSMobileClientError.unableToSignIn(message: "Could not get end user to sign in."))

This only happens with Google and Facebook, not if I logged in with username and password.

Am I doing something wrong?
And even if so, an app crash is not very beautiful...

I also tried the other signOut Methods, with parameters/completion handler.
Same result.

**Expected behavior**
Logout should just log me out of everything. No matter if federated login or userpool

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Cocoapods: 1.6.1
 - Pods:
AWSAuth 2.9.3
AWSAuthCore 2.9.3
AWSAuthUI 2.9.3
AWSCognito 2.9.3
AWSCognitoIdentityProvider 2.9.3
AWSCognitoIdentityProviderASF (1.0.1)
AWSCore 2.9.3
AWSDynamoDB 2.9.3
AWSFacebookSignIn 2.9.3
AWSGoogleSignIn 2.9.3
AWSMobileClient 2.9.3
AWSUserPoolsSignIn 2.9.3
Bolts (1.9.0)
FBSDKCoreKit 4.41.0
FBSDKLoginKit 4.41.0
GTMSessionFetcher (1.2.1)
GoogleSignIn (4.4.0)
GoogleToolboxForMac (2.2.0)

**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - OS: iOS 12.1.4

//edit:
This is my last console output, maybe it is useful:
2019-03-15 12:15:31.180681+0100 TestApp[1694:363841] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot set the error on a completed task.'
*** First throw call stack:
(0x1c88adea4 0x1c7a7da50 0x1c87b4484 0x10396ecc0 0x103da50a8 0x103da4994 0x103da451c 0x1027efa00 0x102809080 0x1028090ec 0x1f5a4e314 0x1f54dbd54 0x1f54dc074 0x1f54db074 0x1f5a87a6c 0x1f5a88cd0 0x1f5a67fcc 0x1f5b36e38 0x1f5b39830 0x1f5b32320 0x1c883e0e0 0x1c883e060 0x1c883d944 0x1c8838810 0x1c88380e0 0x1caab1584 0x1f5a4cc00 0x102765fb8 0x1c82f6bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by minbi** [comment]
Hi @N1LaT ,

The behavior you are describing appears to be a bug. We will take a look at this issue. If you are able to pinpoint the issue before we are able to address this issue. We are open to pull requests.

**Comment by N1LaT** [comment]
Hi and thanks for the reply.

The funny thing is, i've rebuilt my code and somehow it works now.
Please don't ask me why but I guess this can be closed.

**Comment by muellerfr** [comment]
@N1LaT - Thanks for the update.
