### ISSUE TITLE
AWSCognitoIdentityCustomChallengeDetails.task.continueOnSuccessWith is called regardless of failure

### ISSUE THREAD

**Issue by JLau-cy** [aws-amplify/aws-sdk-ios#1304]
**Describe the bug**
AWSCognitoIdentityCustomChallengeDetails.task.continueOnSuccessWith block is called regardless of authentication failure.

Given a user account does not exist in the backend
When I call `AWSCognitoIdentityCustomChallengeDetails.task.continueOnSuccessWith `
The block passed into `continueOnSuccessWith` is executed (this is where my success handling code is)
But after the block executes `didCompleteStepWithError` is executed to throw user does not exist error.

This results in the following screen flow:
1. User initiates custom authentication
2. `continueOnSuccessWith` block is called and success screen is shown to user
3. `didCompleteStepWithError ` is called, now an error that contradicts the success screen is displayed.

**To Reproduce**
1. Call `AWSCognitoIdentityCustomChallengeDetails.task.continueOnSuccessWith` with a non existent user account so the backend will throw a user not found error.
2. You will see the success block is invoked, but the AWSTask returned in the block has no error.
3. After success block has been involved the `didCompleteStepWithError` delegate callback will be fired.

**Which AWS service(s) are affected?**
iOS AWSCognitoIdentityProvider

**Expected behavior**
I expect either the AWSTask returned to contain the user does not exist error so I can handle it there or a delegate call back that is the direct opposite of `didCompleteStepWithError` i.e. `didCompleteStepWithSuccess` where it is called explicitly when authentication is successful.

Since there is a delegate explicitly for errors to be handled, I expect an explicit place where success are handled. However `continueOnSuccessWith` seems to only tell me the task has been executed but there is no where that tells me the result of the task was successful.

**Environment(please complete the following information):**
 - SDK Version: 2.8.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: All
 - iOS Version: 12+

**Comment by minbi** [comment]
Hi @JLau-cy ,

The behavior you are describing appears to be a bug. We will take a look at this issue. If you are able to pinpoint the issue before we are able to address this issue. We are open to pull requests.

**Comment by royjit** [comment]
Hi @JLau-cy apologies for the delayed response.

You do not have to call `AWSCognitoIdentityCustomChallengeDetails.task.continueOnSuccessWith`. You just need to set the result on AWSCognitoIdentityCustomChallengeDetails object. SDK will take care of the rest. When the custom auth completes you will get a call back on `didCompleteStepWithError`. If `error` object is nil, that means the step succeeded.
