### ISSUE TITLE
Autogenerated AWSAPIGatewayClient to use AWSMobileClient

### ISSUE THREAD

**Issue by kirilstrax** [aws-amplify/aws-sdk-ios#1305]
**State your question**
Currently we are using straight forward generated AWSAPIGatewayClient. It doesn't use AWSMobileClient instance, which we initialize elsewhere in the app (at least not from visible code). So how do we migrate AWSAPIGatewayClient to use AWSMobileClient, if it even makes sense. Is there an example available? Thanks

**Which AWS Services are you utilizing?**
AWSMobileClient
AWSAPIGateway

**Provide code snippets (if applicable)**
On app startup we initialize AWSMobileClient like this: `AWSMobileClient.sharedInstance().initialize ...`
But generated code appears not to use `AWSMobileClient.sharedInstance()` in any way. For instance configuration is retrieved like this:
```
let serviceInfo = AWSInfo.default().defaultServiceInfo(Configuration.AWS.infoClientKey)
if let serviceInfo = serviceInfo {
serviceConfiguration = AWSServiceConfiguration(region: serviceInfo.region, credentialsProvider: serviceInfo.cognitoCredentialsProvider)
```

and not 
```
let configuration = AWSServiceConfiguration(region: LexRegion, credentialsProvider: AWSMobileClient.sharedInstance())
```

as I've seen in another example.

**Environment(please complete the following information):**
 - SDK Version: 2.9.1
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 7 and above
 - iOS Version: iOS 11.0 and above
 - Specific to simulators: no

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by minbi** [comment]
Hi @kirilstrax ,

I will try to get a similar setup to try out what you are doing, but the `AWSMobileClient` should adhere to the credentialsProvider interface requested by the `AWSServiceConfiguration`.

**Comment by kirilstrax** [comment]
Thanks for your response, minbi

I tried a straight forward conversion:
```
private static let _defaultClient: AWSLambdaMobileClient = {
        let config = AWSServiceConfiguration(region: "...", credentialsProvider: AWSMobileClient.sharedInstance())
        return AWSLambdaMobileClient(configuration: config)
	}()
```
That didn't work. However I managed to get it to work if I:
1. Add API key to `init` of generated `AWSAPIGatewayClient`
```
self.apiKey = "..." // API key that is also present in awsconfiguration.json
```
2. Explicitly add `x-pool-token` header to every request

But I still would like to understand what's the proper/recommended way of using generated AWSAPIGatewayClient with AWSMobileClient. Example would be great.

If example is hard to come up with, I would like to understand at least:
1. Why did I have to add `apiKey` manually, while it should be present in the configuration?
2. Why `AWSAPIGatewayClient` is trying to pass "unAuth" token in `x-amz-security-token` header, while it has a valid Auth role token? Is it a stack configuration issue? or usage

**Comment by royjit** [comment]
Hi @kirilstrax 
Apologies for the delayed response, where you able to make it work? Please check whether your backend is configured correctly to use Cognito User Pool as the authorizer - https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html.
`AWSMobileClient.default()` should work as the credentialsProvider. If you are still facing any issue, try to enable the verbose logs and see if you are seeing any error:
```
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Comment by royjit** [comment]
Also here is another documentation from AWSMobileClient to you token as authorization - https://aws-amplify.github.io/docs/sdk/ios/api#cognito-user-pools-authorization
