### ISSUE TITLE
AWSMobileClient federated sign in facebook always return onResult even though give wrong token

### ISSUE THREAD

**Issue by HayTran94** [aws-amplify/aws-sdk-ios#1307]
**Describe the bug**
Even though give wrong token, but the callback of federatedSignIn method using facebook token always return `error` is `nil` and `userState` is `signedIn`.

**To Reproduce**
```
AWSMobileClient.sharedInstance().federatedSignIn(providerName: IdentityProvider.facebook.rawValue, token: "123456789") { (userState, error) in
            if let error = error {
                // Never be called
                print("error \(error)")
            } else {
                // Always be called
                print("success \(userState)")
            }
        }
```

**Which AWS service(s) are affected?**
AWSMobileClient 

**Expected behavior**
The `error` object should be different `nil` or `userState` object is `signedOutFederatedTokensInvalid`

**Environment(please complete the following information):**
 - SDK Version: 2.9.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: iPhone 6
 - iOS Version: 12.0.1

**Comment by minbi** [comment]
Hi @HayTran94 ,

We are working on a fix in the logic to make this more user-friendly.

**Comment by palpatim** [comment]
The `federatedSignIn` routine does not validate the token before returning. The reasoning here is that the application, not the SDK, owns management of federated sign in tokens, so we are optimistically assuming that the token material is valid.

**Next Steps for @aws-amplify/ios-team**

During the flow, the SDK does send the token to Cognito. We need to validated whether the failure in that call is propagated as an error in the AWSMobileClient state change listener.

**Comment by royjit** [comment]
Currently SDK does not set the status change during the flow. Possible fix is to call `getIdentityId` to update the identity which will use the passed in token. The call will return `notAuthorized` error and we can use this error to update the user state. 

We need to make sure that this is not a blocking call in case of session expiry situation.

**Comment by royjit** [comment]
To verify that the token is valid immediately after sign in, you can call `getAWSCredentials` which will set the right status.

**Comment by lawmicha** [comment]
please see above work around https://github.com/aws-amplify/aws-sdk-ios/issues/1307#issuecomment-852157967
