### ISSUE TITLE
Can't catch errors on occur where in didFinishDownloadingtoURL

### ISSUE THREAD

**Issue by Minsoo-kim92** [aws-amplify/aws-sdk-ios#1310]
**Describe the bug**
<img width="1040" alt="스크린샷 2019-03-21 오후 3 07 29" src="https://user-images.githubusercontent.com/23733661/54736477-9247f600-4bee-11e9-8219-8ac0d66ae184.png">

Can't catch errors which occur where in 
`- (void)URLSession:(NSURLSession *)session
      downloadTask:(NSURLSessionDownloadTask *)downloadTask
didFinishDownloadingToURL:(NSURL *)location {`
, 
Even though I can see an error while debugging 

but I can't catch the file ExceptionError error not only in the completion handler named with `continueWith`
<img width="633" alt="스크린샷 2019-03-21 오후 3 28 30" src="https://user-images.githubusercontent.com/23733661/54736478-9247f600-4bee-11e9-90dd-ca414224196e.png">
but also custom completion handler 
<img width="636" alt="스크린샷 2019-03-21 오후 3 28 41" src="https://user-images.githubusercontent.com/23733661/54736479-9247f600-4bee-11e9-973a-bf0594ea29ec.png">

`
Error Domain=NSCocoaErrorDomain Code=4 "“CFNetworkDownload_v4e7QT.tmp” couldn’t be moved to “Assetbundle” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/<username>/Library/Developer/CoreSimulator/Devices/B481E88B-6982-434C-9996-6E8B89F8529C/data/Containers/Data/Application/C8634989-C6FE-4927-9996-A95A4F2FD4C5/Library/Caches/com.apple.nsurlsessiond/Downloads/<bundleIdentifier>/CFNetworkDownload_v4e7QT.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/<username>/Library/Developer/CoreSimulator/Devices/B481E88B-6982-434C-9996-6E8B89F8529C/data/Containers/Data/Application/C8634989-C6FE-4927-9996-A95A4F2FD4C5/Documents/Unity/Test/Assetbundle/0c0904718da941219c0dcff4f5c79739, NSFilePath=/Users/<username>/Library/Developer/CoreSimulator/Devices/B481E88B-6982-434C-9996-6E8B89F8529C/data/Containers/Data/Application/C8634989-C6FE-4927-9996-A95A4F2FD4C5/Library/Caches/com.apple.nsurlsessiond/Downloads/<bundleIdentifier>/CFNetworkDownload_v4e7QT.tmp, NSUnderlyingError=0x60000200a4c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
`

**Which AWS service(s) are affected?**
S3 SDK for iOS
**Expected behavior**
I used the download method `AWSS3TransferUtility.download(to, key, expression, completionHandler)` and I want the method save downloaded files into the URL path

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.9.2
 - Dependency Manager: Cocoapods
 - Swift Version : 3.0

**Device Information (please complete the following information):**
 - Device: iPhoneXR, Simulator
 - iOS Version: e.g. iOS 12.1
 - Specific to simulators:

**Additional context**

**Comment by cbommas** [comment]
@Minsoo-kim92 

I am not sure I am understanding the issue completely. Is the issue that the download is failing or that the error is not being propagated correctly to the custom completionHandler? Can you please clarify?

From the information you have posted, it appears that the `moveItemAtUrl` method is failing, possibly due to the app not having access to the folder. If your issue is the former, then I would recommend looking into the target fileURL you are providing to the TransferUtility and ensuring that you have access.

**Comment by Minsoo-kim92** [comment]
This issue was just failed to `moveItemAtUrl` method because there are no upper level directories destination directory which are files downloaded, I resolved issue that file can't be moved to designated URL, I just make upper directories..

Btw, I can't handle the file exception using the completion handlers, is that intended flow?

**Comment by cbommas** [comment]
@Minsoo-kim92 
Good to hear that you were able to resolve your issue. The intended flow is to propagate the file exception using the completion handlers - there may be a bug/code path where the error is being overwritten. I will look into this and post back here once I have more info.

**Comment by Minsoo-kim92** [comment]
Is this issue was resolved ? I can't catch errors using completion handler of TransferUtility even I updated AWSS3, AWSCore to 2.9.6

**Comment by palpatim** [comment]
@Minsoo-kim92 Yes, we believe that #1316 fixed this issue. Can you clarify that you're seeing the same error message when debugging? How are you reproducing the error? Perhaps the code path generating your error is something we missed.
