### ISSUE TITLE
 Successfully uploading files using AWS3TransferUtility  But when I browse the file, AccessDenied

### ISSUE THREAD

**Issue by lxooxl** [aws-amplify/aws-sdk-ios#1311]
**State your question**

**Which AWS Services are you utilizing?**
AWSS3

**Environment(please complete the following information):**
 - SDK Version:2.7.2
 - Dependency Manager: Cocoapods
 - Swift Version : objective-c

**Device Information (please complete the following information):**
 - Device: IiPhone XS MAX
 - iOS Version: 12.1.4

upload success then use putObjectAcl set acl to publicRead, the request log

```
2019-03-21 22:31:31.421184+0700 AmazonS3Upload[1011:366991] Request headers:
{
    Authorization = "AWS4-HMAC-SHA256 Credential=7UUSOR96PGANUQQBVJTW/20190321/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-acl;x-amz-content-sha256;x-amz-date, Signature=d15df0b1e7ca1b69259bda0ccdec71fa58926f97758c20c858451771214ad1d0";
    "Content-Type" = "binary/octet-stream";
    Host = "pubup.lovenbyun.com";
    "User-Agent" = "aws-sdk-iOS/2.6.31 iOS/11.4 zh-Hans_KH";
    "X-Amz-Date" = 20190321T153131Z;
    "x-amz-acl" = "public-read";
    "x-amz-content-sha256" = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855;
}
2019-03-21 22:31:31.421658+0700 AmazonS3Upload[1011:366992] Request body:
2019-03-21 22:31:31.981545+0700 AmazonS3Upload[1011:366598] Response headers:
{
    Connection = "keep-alive";
    "Content-Length" = 0;
    "Content-Type" = "application/xml";
    Date = "Thu, 21 Mar 2019 15:31:31 GMT";
    Server = Tengine;
    "x-amz-request-id" = "tx00000000000000576faa1-005c93ae53-10e90b7-zone-26cbd6";
}
```
but also AccessDenied 

if use java setObjectAcl, can success andbrowse the file

**Comment by cbommas** [comment]
@lxooxl 

Can you share code snippets to help debug this further?

**Comment by lxooxl** [comment]
init
```
[[AWSDDLog sharedInstance] addLogger:[AWSDDOSLogger sharedInstance]];
    [AWSDDLog sharedInstance].logLevel = AWSDDLogLevelAll;
    
    AWSStaticCredentialsProvider *credentials = [[AWSStaticCredentialsProvider alloc] initWithAccessKey:self.accessKey secretKey:self.secretKey];
    AWSEndpoint *endPoint = [[AWSEndpoint alloc] initWithURLString:self.endPoint];
    
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionCNNorth1 endpoint:endPoint credentialsProvider:credentials];
    [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;
```

upload file
```
NSData *data = array[i];
                
                NSString *remoteName = [NSString stringWithFormat:@"%@/%lld-%d%@",[YHUser currentUser].userID, (int64_t)([[NSDate date] timeIntervalSince1970] * 1000), i, suffix];
                
                
                AWSS3TransferUtilityUploadExpression * uploadExpression = [AWSS3TransferUtilityUploadExpression new];
                
                uploadExpression.progressBlock = ^(AWSS3TransferUtilityTask * _Nonnull task, NSProgress * _Nonnull progress) {
                    
                };
                
                AWSS3TransferUtility * utility = [AWSS3TransferUtility defaultS3TransferUtility];
                
                dispatch_group_enter(group);
                [[utility uploadData:data bucket:self.bucketName key:remoteName contentType:fType expression:uploadExpression completionHandler:^(AWSS3TransferUtilityUploadTask * _Nonnull task, NSError * _Nullable error) {
                    
                    if (error) {
                        NSLog(@"%@",error.userInfo);
                        NSDictionary *dic = error.userInfo[@"Error"];
                        NSLog(@"%@",dic);
                    } else {
                        if (task.status == AWSS3TransferUtilityTransferStatusCompleted) {
                            AWSS3PutObjectAclRequest *request = [AWSS3PutObjectAclRequest new];
                            request.bucket = self.bucketName;
                            request.key = remoteName;
                            request.ACL = AWSS3ObjectCannedACLPublicRead;
                            AWSS3 *s3service = [AWSS3 defaultS3];
                            
                            [s3service putObjectAcl:request completionHandler:^(AWSS3PutObjectAclOutput * _Nullable response, NSError * _Nullable error) {
                                
                            }];
                            NSLog(@"上传成功");
                            if (i > pathArray.count) {
                                [pathArray addObject:[NSString stringWithFormat:@"./%@",remoteName]];
                            } else {
                                [pathArray insertObject:[NSString stringWithFormat:@"./%@",remoteName] atIndex:i];
                            }
                        } else {
                            NSLog(@"上传中");
                        }
                    }
                    dispatch_group_leave(group);
                }] continueWithBlock:^id _Nullable(AWSTask<AWSS3TransferUtilityUploadTask *> * _Nonnull t) {
                    return nil;
                }];
```

**Comment by cbommas** [comment]
@lxooxl 

I looked at your code and tried to reproduce the issue on my end, but was not able to. To debug this, I would recommend that you check if the call below is erroring out and investigate the contents of the error object. 

      [s3service putObjectAcl:request completionHandler:^(AWSS3PutObjectAclOutput * _Nullable response, NSError * _Nullable error)

In my experiments, I was able to get the `putObjectAcl` method to set the property to `publicRead`.
However, there is an easier way to get this done. You can add the following to your expression object before invoking the transfer utility upload function and that will set the permissions when you upload the object and simplify the logic in your completion handler.

          AWSS3TransferUtilityUploadExpression * uploadExpression =  
                           [AWSS3TransferUtilityUploadExpression new];
           uploadExpression.setValue("public-read", forRequestHeader: "x-amz-acl")
           uploadExpression.progressBlock = 
                      ^(AWSS3TransferUtilityTask * _Nonnull task, 
                                                NSProgress * _Nonnull progress) {
                    
                      };      

Give this a go and let us know how you fare.

**Comment by lxooxl** [comment]
@cbommas

**Comment by cbommas** [comment]
@lxooxl 
Good to hear that the issue has been resolved. From what I can see, it looks like the `AWSS3 *s3service = [AWSS3 defaultS3];` was initializing the client with incorrect credentials, causing the sigV4 signature to fail.

I will go ahead and close out this issue. Please feel free to post here/open another github issue if you are still running into a problem.

**Comment by lxooxl** [comment]
@cbommas 
```
AWSStaticCredentialsProvider *credentials = [[AWSStaticCredentialsProvider alloc] initWithAccessKey:self.accessKey secretKey:self.secretKey];
AWSEndpoint *endPoint = [[AWSEndpoint alloc] initWithURLString:self.endPoint];
```

incorrect credentials, it means mine accessKey/secretKey/endPoint was wrong?

I use awss3TransferUtility upload file, some times receive 
```
awss3TransferUtility Received a 500, 503 or 400 error
```

**Comment by cbommas** [comment]
@lxooxl 
Yes, I believe the that the accessKey/secretKey may be incorrect. We can debug this further if you could turn on verbose logging and paste the logs on to the issue ( best to create a new issue for this)

For the other errors that you are mentioning here, it would be great if you can also open a new github issue so that it can be tracked effectively. For each error case, it would be helpful if you could attach logs.
