### ISSUE TITLE
Difference between isLoggedIn and isSignedIn

### ISSUE THREAD

**Issue by kirilstrax** [aws-amplify/aws-sdk-ios#1313]
**State your question**
There are 2 state variables:
```
AWSMobileClient.sharedInstance().isLoggedIn
AWSMobileClient.sharedInstance().isSignedIn
```
Experimentally I see that they are not always equal, my guess is that `isLoggedIn` is legacy, but I didn't find any explanation about each of them. Furthermore: the comment above `isLoggedIn` confuses situation even more:
```
/**
 * Indicates whether the user is signed-in or not.
 * @return true if user is signed-in
 */
@property (nonatomic, readonly, getter=isLoggedIn) BOOL loggedIn;
```
So what is the difference between them, and which variable to be used to check if the user is currently signed in?
Thanks in advance

**Which AWS Services are you utilizing?**
Cognito with AWSMobileClient

**Provide code snippets (if applicable)**
Provided above

**Environment(please complete the following information):**
 - SDK Version: 2.9.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: any
 - iOS Version: 11 or above
 - Specific to simulators: no

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by minbi** [comment]
Hi @kirilstrax ,

Please use `isSignedIn`. We have aligned our vocabulary and the signIn, signOut, isSignedIn is part of our controlled vocabulary.

**Comment by kirilstrax** [comment]
Thanks for the explanation.
