### ISSUE TITLE
AWSMobileClient getIdentityId fails after successful signIn

### ISSUE THREAD

**Issue by thomers** [aws-amplify/aws-sdk-ios#1320]
**State your question**
I'm using `AWSMobileClient.showSignInScreen`.

When the user signs in (error=nil in the completionHandler), `AWSMobileClient.getIdentityId` fails with 

     GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]

Note that the identity pool *is* configured correctly.

Getting the identityId did work before (with SDK 2.6.x).

(Note that after signIn, `AWSMobileClient.isSignedIn` still returns `NO`, see https://github.com/aws-amplify/aws-sdk-ios/issues/1314 )

**Which AWS Services are you utilizing?**
Cognito
MobileClient

**Provide code snippets (if applicable)**

**Environment:**
 - SDK Version: SDK 2.9.3
 - Dependency Manager: Cocoapods
 - Objective-C !

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 12.2

**Comment by minbi** [comment]
Hi @thomers ,

The `showSignInScreen` method is part of our internal code, it does not include the code to federate the tokens obtained from the UI. See [code](https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift#L473) for what happens after `showSignInScreen` returns. I know you are trying to work around the limitations of AWSMobileClient being Swift only, so this should help in your endeavors.

**Comment by thomers** [comment]
Hi @minbi , thanks for the reply.

My bad - I'm in fact calling `AWSMobileClient.sharedInstance().showSignIn`

The problem stays the same.

**Comment by dokutoshi** [comment]
Seems related to other issues that the identityId is changing.

**Comment by royjit** [comment]
We released some fixes around identityId in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0. Could you please try with the latest SDK and see if the issue still persist?

Please let us know if you have any problems with this.
