### ISSUE TITLE
AWSMobileClient and DynamoDB - Query and Scan working, Save not

### ISSUE THREAD

**Issue by N1LaT** [aws-amplify/aws-sdk-ios#1321]
**State your question**
I am currently trying to get an app working which uses a login via Cognito Userpool as well as Identity Pool and Federated Sign in via Facebook and Google.
After signing up or in I want to interact with my Dynamo Db.
The thing I don't get is, login / signup works properly, and I can query and scan the db tables. BUT I can't save a new object to it. Why?

**Which AWS Services are you utilizing?**
AWSMobileClient, Cognito, DynamoDb

**Provide code snippets (if applicable)**
Due to our mixed application I'm not even sure if this setup is correct but my AppDelegate (.m) looks as follows:

```
MyLoginManager *loginMan = [MyLoginManager shared];
AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:[loginMan CognitoIdentityUserPoolRegion] identityPoolId:[loginMan CognitoIdentityPoolId] identityProviderManager:loginMan];
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:[loginMan CognitoIdentityUserPoolRegion] credentialsProvider:credentialsProvider];
AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;
```

// edit: Okay so it seems that I need this code because without it my app crashes with a SIGABRT on dispatch_once in defaultDynamoDBObjectMapper!!!

That's all I've set up, the rest is done with amplify and is within the serviceconfiguration.json. I'm not sure if everything is set up correctly on those AWS sites as well.

Scan:
```
let dynamoDBObjectMapper = AWSDynamoDBObjectMapper.default()
            let scanExpression = AWSDynamoDBScanExpression()
            scanExpression.exclusiveStartKey = self.lastEvaluatedKey
            scanExpression.limit = 20
            
            dynamoDBObjectMapper.scan(classType.classForCoder, expression: scanExpression).continueWith(executor: AWSExecutor.mainThread(), block: { (task:AWSTask<AWSDynamoDBPaginatedOutput>) -> Any? in
                
                if self.lastEvaluatedKey == nil {
                    self.tableRows?.removeAllObjects()
                }
                
                print("In loadTableContent Completion Block with \(task.result?.items.count ?? -1) items")
                classType.handleTableContent(content: task)
                
                UIApplication.shared.isNetworkActivityIndicatorVisible = false
                
                var errorRet = ""
                if let error = task.error {
                    print("Error: \(error.localizedDescription)")
                    errorRet = error.localizedDescription
                }
                
                self.lock?.unlock()
                
                completion(self.tableRows!, errorRet)
                
                return nil
                
            })
```

Query:
```
let dynamoDBObjectMapper = AWSDynamoDBObjectMapper.default()
   
        print("In getTableRowForUserID \(aU_ID)")
        
        dynamoDBObjectMapper.query(classType.classForCoder, expression: queryExpression).continueWith(executor: AWSExecutor.mainThread(), block: { (task:AWSTask<AWSDynamoDBPaginatedOutput>) -> Any? in
            
            if self.lastEvaluatedKey == nil {
                self.tableRows?.removeAllObjects()
            }
            
            if let error = task.error {
                print("Error GetTableRowIntercom: \(error.localizedDescription)");
            } else {
                
                print("In Completion Block von getTableRowForUserID mit \(task.result?.items.count ?? -1) items")
                classType.handleTableRow(content: task)
            }
            
            completion(self.tableRows!)
            
            return nil
        })
```

Save:
```
let dynamoDBObjectMapper = AWSDynamoDBObjectMapper.default()
        dynamoDBObjectMapper.save(tableRow).continueWith(executor: AWSExecutor.mainThread()) { (task:AWSTask!) -> AnyObject? in
            var retVal = false
            if let error = task.error as NSError? {
                //print("Error Save: \(error.localizedDescription). \(self.description)")
                print("Error Save: \(error)")
            } else {
                print("Successfully inserted the data into the table.")
                retVal = true
            }
            
            completion(retVal, self)
          
            return retVal as AnyObject
        }
```

**Environment(please complete the following information):**
 - SDK Version: 2.9.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 6s
 - iOS Version: iOS 12.1.4, macOS: 10.14.3

Oh and one more question, what exactly is that "logins" Method good for? What should be provided there? A logins map... okay... so what? I don't get it, sorry.... Do I really need it?

// edit: Someone told me that my issue is related to permissions, but I havn't changed anything there?! Does amplify overwrite something there? Because it worked before my rework (from ObjC to Swift and use AWSMobileClient and Amplify)
The error I receive is the following:
`Error Save: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}`
And before the last changes the error was:
Code 6 AccessDeniedException ... assumed role is not authorized to perform: dynamodb:UpdateItem on resource....

**Comment by N1LaT** [comment]
Okay it seems that somewhat (I don't know what or why) changed the permissions on my IAM console. I fixed it so this ticket can be closed, sorry for that.
But maybe someone can answer my questions though.
Thanks

**Comment by minbi** [comment]
Hi @N1LaT ,

The logins map is used to federated identities into Cognito Identity Pools.
The logins map should be unnecessary with the use of AWSMobileClient.

Your above code should look like this:

```
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:[loginMan CognitoIdentityUserPoolRegion] credentialsProvider:AWSMobileClient.sharedInstance()];
AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;
```

**Comment by thomers** [comment]
Hey @minbi , 

In general, if we use AWSMobileClient for Cognito and federated sign in, is this the 
required way to init the defaultServiceConfiguration in order to use the other AWS Services (like S3), or do they „automatically“ use AWSMobileClient as the credentialsProvider ?
