### ISSUE TITLE
s3 Transfer Utility iOS

### ISSUE THREAD

**Issue by harishmaddula32** [aws-amplify/aws-sdk-ios#1322]
**Describe the bug**
I'm running S3BackgroundTransferSampleObjC **(in swift project also)** sample project downloaded from git repo. I configured all necessary things like poolid,region and so on..

While running sample project after clicking in start button app is crashing
exact at what point it is crashing is when upload function is calling at that time.

Crash log is here as follows:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `Info.plist` or set `defaultServiceConfiguration` before using this method.'

But as per documentation i did all necessary things. Added poolid and region in plist. Please let me know how to resolve this issue.

Environment:
SDK Version: 2.8.0
Dependency Manager: Cocoapods
Objective-C !

Device Information (please complete the following information):
Device: Simulator
iOS Version: 10.0

Note: I'm using Xcode 9

**Comment by minbi** [comment]
Hi @harishmaddula32 ,

Are you referring to this sample? https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferUtility-Sample/Objective-C

Did you add both regions?

>AWS --> CredentialsProvider --> CognitoIdentity --> Default --> Region (for example: USEast1)
AWS --> S3TransferUtility --> Default --> Region (for example: USEast1)

**Comment by harishmaddula32** [comment]
I'm referring the same example what you suggested.

I added both regions
AWS --> CredentialsProvider --> CognitoIdentity --> Default --> pooIid (MypoolId)
AWS --> CredentialsProvider --> CognitoIdentity --> Default --> Region (MyRegion)
AWS --> S3TransferUtility --> Default --> Region (MyRegion)

But Still it is crashing
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `Info.plist` or set `defaultServiceConfiguration` before using this method.'

**Comment by minbi** [comment]
Hi @harishmaddula32 ,

Can you check your Info.plist? I was able to successfully run the sample Xcode 9.2 iPhone simulator 8 Plus.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<key>AWS</key>
<dict>
	<key>CredentialsProvider</key>
	<dict>
		<key>CognitoIdentity</key>
		<dict>
			<key>Default</key>
			<dict>
				<key>PoolId</key>
				<string>us-west-2:xxxxxxxxxxx</string>
				<key>Region</key>
				<string>us-west-2</string>
			</dict>
		</dict>
	</dict>
	<key>S3TransferUtility</key>
	<dict>
		<key>Default</key>
		<dict>
			<key>Region</key>
			<string>us-west-2</string>
		</dict>
	</dict>
</dict>
</plist>
```

**Comment by harishmaddula32** [comment]
I check with my plist exactly same as you sent

Note: I'm using Xcode 9 iPad simulator 9.7

**Comment by harishmaddula32** [comment]
Any Waiting for your reply

**Comment by harishmaddula32** [comment]
After doing some R&D somehow i'm manageable to upload data to s3 bucket. 
I have another question 
I want to download **all files from one particular folder** from s3 bucket how can i do it.
can you please send some sample code for that in OBJ-C language

**Comment by harishmaddula32** [comment]
Any help waiting for your reply

**Comment by swift4developer** [comment]
How you resolve that issue, can you please share the solution.

**Comment by harishmaddula32** [comment]
As you said i added only Awsscore and Awss3 framework and shell script. It's working fine.

Mac os : 10.14.4
Xcode : 10.2
iOS : 12

**Comment by muellerfr** [comment]
@harishmaddula32 - We do not have an explicit sample for your use case. However, have a look at the following sample integration test that lists all objects in bucket then deletes them. You can copy the code and change it to download the files rather than delete them.

https://github.com/aws-amplify/aws-sdk-ios/blob/740efb55c1209066f6fe5747384bfa9084491321/AWSS3Tests/AWSS3Tests.m#L139-L164

Please let us know if you need additional help.

**Comment by stardevrk** [comment]
Hi Guys!
I use s3 TransferUtility to upload file to the S3 bucket. How can I set S3 bucket region?

Please help me.
