### ISSUE TITLE
Access Cognito Authenticated ALB(ELBv2) using AppSync

### ISSUE THREAD

**Issue by nipuncs** [aws-amplify/aws-sdk-ios#1323]
**State your question**
I have ALB to access microservice and I used Cognito as the Authentication, But I am getting below error:
```
AWSAppSync.AWSAppSyncClientError.requestFailed(Optional(160 bytes), Optional(<NSHTTPURLResponse: 0x2813a4b40> { URL: https://api.xxx.com/user-service } { Status Code: 401, Headers {
    "Content-Length" =     (
        160
    );
    "Content-Type" =     (
        "text/html"
    );
    Date =     (
        "Wed, 27 Mar 2019 11:06:11 GMT"
    );
    Server =     (
        "awselb/2.0"
    );
} }
```
My ALB config:
<img width="1246" alt="Screen Shot 2019-03-27 at 4 41 07 PM" src="https://user-images.githubusercontent.com/39821254/55071750-78575900-50af-11e9-8800-0eb698d69601.png">

This is working without Cognito very well. But after config the Cognito auth, This is not working. What am I missing here?

**Which AWS Services are you utilizing?**
AWS Cognito
AWS AppSync
AWS Application Load Balancer

**Provide code snippets (if applicable)**
**awsconfiguration.json**
```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:xxxxxxxxxxxxxxxx",
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-xxxxxxxxxx",
            "AppClientId": "2it1chxxxxxxxxxxx",
            "AppClientSecret": "xxxxxxxxxxx",
            "Region": "us-east-1"
        }
    },
    "AppSync": {
        "Default": {
            "ApiUrl": "https://api.xxx.work/user-service",
            "Region": "us-east-1",
            "AuthMode": "AWS_IAM"
        }
    }
}

```
**API Invoking Function**
```
 func getUserList() {
        //Run a query
        do {
            // Initialize the AWS AppSync configuration
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: AWSAppSyncServiceConfig(),
                                                                  credentialsProvider: AWSMobileClient.sharedInstance(),
                                                                  cacheConfiguration: AWSAppSyncCacheConfiguration())
            
            // Initialize the AWS AppSync client
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
            
            appSyncClient?.clearCache()
            
            appSyncClient?.fetch(query: GetUsersQuery())  { (result, error) in
                if error != nil {
                    print(error)
                    return
                }
                result?.data?.users!.forEach { print(($0?.firstName)! ) }
            }
        } catch {
            print("Error initializing appsync client. \(error)")
        }
    }
```

**Environment:**
 - SDK Version: AWSAppSync (2.10.3)
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : 4.0

**Device Information:**
 - Device: iPhone8
 - iOS Version:iOS 11.2

**Comment by palpatim** [comment]
@nipuncs Sorry for the trouble you're having here. It seems like the AppSync layer is working as expected, but the ELB layer is throwing issue.

@awsed, Can you please investigate this?

**Comment by awsed** [comment]
AppSync needs the ID or Access JWT Token that Cognito User Pools generates from an authenticated user to be sent in the Authorization header to the AppSync API endpoint, you need to check if ALB is doing that, @nipuncs

**Comment by nipuncs** [comment]
@palpatim and @awsed, Thank you for your feedback. I have decided to use a manual authentication using JWT Token instead of Cognito.

Since I am no longer facing this issue, I will close this.
