### ISSUE TITLE
AWSCognitoAuth_Internal.h file not found 

### ISSUE THREAD

**Issue by thomers** [aws-amplify/aws-sdk-ios#1328]
Possibly related to https://github.com/aws-amplify/aws-sdk-ios/issues/1126

AWS SDK 2.9.3, using Cocoapods
Xcode 10.1
macOS 10.13.6

#import "AWSCognitoAuth_Internal.h"
in AWSMobileClient/AWSCognitoAuth.m#16

Error on building AWSMobileClient: AWSCognitoAuth_Internal.h file not found

**Comment by Foefirelord** [comment]
Must be related to #1126 

Getting #1126 upon updating to 2.9.3 pods. No cache cleaning is helping.

**Comment by thomers** [comment]
Fixed, probably by removing redundant dependencies from my Podfile. (Also, upgraded to SDK 2.9.4, but that did not change anything initially.)

Now:

        pod 'AWSMobileClient', :path => '~/Development/aws-sdk-ios'
        pod 'AWSAuthUI', :path => '~/Development/aws-sdk-ios'
        pod 'AWSUserPoolsSignIn', :path => '~/Development/aws-sdk-ios'

        # redundant, because added as dependency of other AWS SDKs automatically:
        #  pod 'AWSCore', :path => '~/Development/aws-sdk-ios'
        #  pod 'AWSAuth', :path => '~/Development/aws-sdk-ios'
        #  pod 'AWSCognito', :path => '~/Development/aws-sdk-ios'
        #  pod 'AWSCognitoAuth', :path => '~/Development/aws-sdk-ios'
        #  pod 'AWSCognitoIdentityProvider', :path => '~/Development/aws-sdk-ios'

**Comment by rohandubal** [comment]
To explain the details: `AWSMobileClient` now supports HostedUI OAuth flows directly as part of `showSignIn` API. The dependency of `AWSCognitoAuth` is no longer needed as `AWSMobileClient` internally encapsulates this library. Using both in one project is not recommended and I will be clarifying it in the documentation to make sure no one runs into this issue.

Thanks,
Rohan
