### ISSUE TITLE
No 'defaultClient' in API Gateway-generated iOS Swift SDK

### ISSUE THREAD

**Issue by motivus** [aws-amplify/aws-sdk-ios#1357]
**Describe the bug**
There is no `defaultClient` in the API Gateway-generated <myApiName>Client.swift as per the directions in `README.md`.

**To Reproduce**

I followed [this REST API tutorial](https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-lambda.html) in the API Gateway docs. It's a simple API named 'calc' that calls a Lambda function that performs the calculation. It works perfectly in test invocations via the APIG console.

I generated an iOS Swift SDK as instructed [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk-ios-swift.html) in the docs and followed the instructions for use in my simple iOS project. The problem is that `README.md` states that I should "grab the `defaultClient` from your code"... but there is NO defaultClient in the generated `<myApiName>Client.swift`.

The only references to `defaultClient` (or close) in `<myApiName>Client.swift` is as follows:

```
import AWSCore
import AWSAPIGateway

public class SVTLambdaGateClient: AWSAPIGatewayClient {

	static let AWSInfoClientKey = "SVTLambdaGateClient"

	private static let _serviceClients = AWSSynchronizedMutableDictionary()
	private static let _defaultClient:SVTLambdaGateClient = {
		var serviceConfiguration: AWSServiceConfiguration? = nil
        let serviceInfo = AWSInfo.default().defaultServiceInfo(AWSInfoClientKey)
        if let serviceInfo = serviceInfo {
            serviceConfiguration = AWSServiceConfiguration(region: serviceInfo.region, credentialsProvider: serviceInfo.cognitoCredentialsProvider)
        } else if (AWSServiceManager.default().defaultServiceConfiguration != nil) {
            serviceConfiguration = AWSServiceManager.default().defaultServiceConfiguration
        } else {
            serviceConfiguration = AWSServiceConfiguration(region: .Unknown, credentialsProvider: nil)
        }
        
        return SVTLambdaGateClient(configuration: serviceConfiguration!)
	}()
```

and then just below:

```
	/**
	 Returns the singleton service client. If the singleton object does not exist, the SDK instantiates the <snip>
	 @return The default service client.
	*/
	public class func `default`() -> SVTLambdaGateClient{
		return _defaultClient
	}
```

I assume I should be looking for a `public class func defaultClient()`, right?

**Which AWS service(s) are affected?**
API Gateway

**Expected behavior**
I would expect the the API Gateway-generated iOS Swift SDK would have a `defaultClient()` function in `<myApiName>Client.swift` if the README states that the developer should use it in their iOS app.

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.9.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 12.1
 - Specific to simulators:

**Comment by motivus** [comment]
Just a note that I "grabbed the defaultClient" (to quote the README.md) by calling the **`default`()** function in `<myApiName>Client.swift` as follows:

```
    @IBAction func userInvokeApi(_ sender: UIButton) {
        print("You clicked invoke api...")

        // grab the defaultClient...
        let client = SVTLambdaGateClient.default()
        client.calcGet(operand2: "3", _operator: "+", operand1: "5").continueWith{ (task: AWSTask?) -> AnyObject? in
            if let error = task?.error {
                print("Error occurred: \(error)")
                return nil
            }
            
            if let result = task?.result {
                // Do something with result
                print("Result was returned from REST API")
            }
            
            return nil
        }
    }
```
And my REST API was successfully called, as confirmed in the Cloudwatch logs!

Is this what the README.md meant to do?

I'm going to post another usage question about how to access the result because I'm having trouble figuring out what to do with the AWSTask type.

**Comment by rohandubal** [comment]
Hello @motivus 

Thanks for pointing out this error to us. You are right, the `README` intents to use the `.default()` and not `defaultClient()`

I will update the documentation to reflect that. 

Best,
Rohan

**Comment by motivus** [comment]
Thank you, Sir! And new link noted!

**Comment by mregnauld** [comment]
I don't understand why that thread is closed, since that problem is still here, almost 2 years later...
