### ISSUE TITLE
Get username is null when using showSignIn API

### ISSUE THREAD

**Issue by HayTran94** [aws-amplify/aws-sdk-ios#1391]
**Describe the bug**
Get username is null but token is valid when using showSignIn hosted UI API to sign in Google or Facebook.

**To Reproduce**
```
let hostedUIOptions = HostedUIOptions(scopes: ["openid", "email"], identityProvider: "Facebook")
AWSMobileClient.sharedInstance().showSignIn(navigationController: self.navigationController!, hostedUIOptions: hostedUIOptions) { (userState, error) in
            if let error = error as? AWSMobileClientError {
                print(error.localizedDescription)
            }
            if let userState = userState {
                print("Status: \(userState.rawValue)")
            }
            
            print("username= \(AWSMobileClient.sharedInstance().username)") // username= nil
            
            AWSMobileClient.sharedInstance().getTokens {(token, error) in
                print("token=\(token?.accessToken)") // token= not nil
            }
        }
```

**Which AWS service(s) are affected?**
AWSMobileClient 

**Expected behavior**
Get username is not nil

**Environment(please complete the following information):**
 - SDK Version: 2.9.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone6
 - iOS Version: 12.1

**Comment by rohandubal** [comment]
Hello @HayTran94 

I think this is due to the confusion that the documentation does not explicitly specify that `username` field can be used only when using `username`/ `email` and `password` based login. If you login via Facebook from Hosted UI the `username` value is not available. 

Hope this helps.

Thanks,
Rohan

**Comment by HayTran94** [comment]
Hi @rohandubal,

Thank for your feedback.
