### ISSUE TITLE
AWSMobile Client does not build with Swift 5

### ISSUE THREAD

**Issue by doctorcolinsmith** [aws-amplify/aws-sdk-ios#1394]
**Describe the bug**
I have an app set up with Xcode 10.2 and Swift 5.  The AWSMobileClient framework (v. 2.9.4)  is included using Cocoapods.  The project fails to build with the following error:

```
/<projectpath>/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift:164:38: Cannot override a Self return type with a non-Self return type
```

**To Reproduce**
1. Create a new app with Xcode 10.2 (default settings, including Swift 5)
2. Include AWSMobileClient with Cocoapods (i.e., with the line `pod 'AWSMobileClient', '2.9.4'`)
3. To `ViewController.swift` add the line `import AWSMobileClient`
4. Build and see the above error

**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**
The project should build.

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.9.4
 - Dependency Manager: Cocoapods 1.6
 - Swift Version : 5.0
 - Xcode: 10.2

**Comment by doctorcolinsmith** [comment]
I just noticed there is an open PR that may be related to this: https://github.com/aws-amplify/aws-sdk-ios/pull/1377

**Comment by rohandubal** [comment]
Hello @doctorcolinsmith 

Thanks for reporting this. I will validate the PR and get it in if it passes all the validation.

Best,
Rohan

**Comment by Prince2k3** [comment]
Experiencing this problem as well. Any news on this?

**Comment by MarkTension** [comment]
Same problem here. Tried all suggestions, yet issue persists. Any updates on this?

**Comment by desokroshan** [comment]
We have released a fix for this in the latest patch version 2.9.5. Please feel free to try it out and let us know if the issue persists.

**Comment by AlexeyGolovenkov** [comment]
I had the same problem. Updating to 2.9.5 helped. Thank you.

**Comment by nealpaze** [comment]
I'm not using CocoaPods or Carthage and downloaded the frameworks in a zip file. Xcode keeps telling me AWSMobileClient.framework was compiled with an incompatible version of Swift. I've never used the AWS SDK and was trying to set up a project with PinPoint. Any help would be appreciated.

**Comment by armandr** [comment]
> I'm not using CocoaPods or Carthage and downloaded the frameworks in a zip file. Xcode keeps telling me AWSMobileClient.framework was compiled with an incompatible version of Swift. I've never used the AWS SDK and was trying to set up a project with PinPoint. Any help would be appreciated.

I have this issue as well! This seems to be a separate problem than the Swift 5 issue above.  AWSMobileClient is a PodSpec file and does not have its own code files.  The end of that error message says something about x86/x64.  Maybe the library compiled as ARM binary while the simulator is expecting X64 or vise versa?

**Comment by nealpaze** [comment]
@armandr I got a similar issue when building by default to the Simulator but even building to a generic iOS device scheme based on the imported Frameworks from https://sdk-for-ios.amazonwebservices.com/latest/aws-ios-sdk.zip (2.9.5) dave the Swift 5 error. I can build my project with only AWSCore and Pinpoint added but AWSMobileClient causes the Swift 5 error building to a generic device.

**Comment by palpatim** [comment]
@nealpaze @armandr  "Incompatible version" problems are the result of using binaries compiled with different versions of Swift. Swift 5's ABI compatibility makes steps toward fixing that, but until we adopt Swift 5 you will need to compile the frameworks from source before building them into your project.

**Comment by nealpaze** [comment]
Thanks. I was able to compile with just SNS, AWSCore and Cognito without any issues. It seems the the Framework at issue was AWSMobileClient. I'm frankly unsure of what it is needed for but I was able to get my project working. Thanks for responding.

**Comment by doctorcolinsmith** [comment]
Confirmed that the 2.9.5 release fixed the issue I originally described.
