### ISSUE TITLE
AWSIoT mqtt may fail to decode mqtt message when doing Ota update

### ISSUE THREAD

**Issue by xuaninbox** [aws-amplify/aws-sdk-ios#1398]
After mqtt connect and no action for a while, it may fail to publish message. It seems the web socket has timed out but we didn't get a callback of the status change.

**Comment by cbommas** [comment]
@xuaninbox 
The SDK will send a periodic ping message to make sure that the connection is still valid. Can you share your MQTT Configuration settings, the Quality of service setting, code snippets and logs to help debug further?

**Comment by xuaninbox** [comment]
Update - After further debugging, we saw that the network is NOT the issue, the mqtt message did reached the mqtt client however the decoding is not getting called.

Because we are doing OTA, the messages are coming in a burst (about 200 at a time), not sure if this is related to the decoding not getting triggered.

**Comment by cbommas** [comment]
@xuaninbox 
Can you share logs, configuration, QOS settings etc., to help debug this further

**Comment by xuaninbox** [comment]
After debugging with @roskumr we have narrowed it down to 

https://github.com/aws-amplify/aws-sdk-ios/blob/1229b7b89f631b2a578c3b22d464ba18642556b3/AWSIoT/Internal/MQTTSDK/AWSMQTTDecoder.m#L63-L95

where the byte it read from the stream about the header or length is wrong, which in turn caused all following read from the stream are wrong, as there's not clear of the stream, the retry will fail as well.

We are still investigating if its the raw payload from mqtt is wrong (less likely) or the read from web socket stream has some issue.

**Comment by xuaninbox** [comment]
we have also identified that a check should be added to check if packets are corrupted at 

https://github.com/aws-amplify/aws-sdk-ios/blob/1229b7b89f631b2a578c3b22d464ba18642556b3/AWSIoT/Internal/MQTTSDK/AWSMQTTDecoder.m#L93

else will cause a overflow issue

see: https://github.com/novastone-media/MQTT-Client-Framework/issues/483
