### ISSUE TITLE
Signing up users with only phone number and authentication for every new device

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/aws-sdk-ios#1399]
**State your question**
I am building an application where-in I would like to register the users with just a phone number. If the user changes the device, I want to force them to validate phone number again with confirmation code. Is this scenario supported?
**Which AWS Services are you utilizing?**
Cognito, AppSync
**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]2.9
 - Dependency Manager: [e.g. Cocoapods, Carthage]Cocoapods
 - Swift Version : [e.g. 4.0]5.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]Simulator
 - iOS Version: [e.g. iOS 11.4]iOS 12
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by rohit3d2003** [comment]
Also, is there a way to check if the device where user is logged-in is 'new' or not? I believe it is part of Post Authentication Lambda trigger but wanted to see if there is an API that I can use to identify any new devices where user is trying to log-in.

**Comment by ankitnaugariya** [comment]
Consider using device tracking with an option to suppress MFA for tracked devices: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html
