### ISSUE TITLE
How to use handleAuthResponse in AppDelegate when using Hosted UI?

### ISSUE THREAD

**Issue by HayTran94** [aws-amplify/aws-sdk-ios#1400]
**State your question**
In your hosted ui doc said: 

> Optional: If your app deployment target is < iOS 11, add the following callback in your App Delegate’s application:open url method. This callback is required, because SFSafariViewController is used in < iOS 11 to integrate with the Hosted UI.
> 
> func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
>     return AWSMobileClient.sharedInstance().handleAuthResponse(application, open: url, sourceApplication: sourceApplication, annotation: annotation)
> }

But in your API, the AWSMobileClient.sharedInstance().handleAuthResponse function will return Void type, but Bool type. So how I can use it correctly?

**Which AWS Services are you utilizing?**
AWSMobileClient 

**Environment(please complete the following information):**
 - SDK Version: 2.9.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Comment by rohandubal** [comment]
Hello @HayTran94 

Apologies for the confusion. I will update the documentation to reflect the right behavior. You can simply put a `return true` statement there to ensure it works correctly for `AWSMobileClient.`

Thanks,
Rohan
