### ISSUE TITLE
Please improve the response times on tickets

### ISSUE THREAD

**Issue by thomers** [aws-amplify/aws-sdk-ios#1401]
Hello, I'd urgently need some feedback from AWS support on these tickets:

https://github.com/aws-amplify/aws-sdk-ios/issues/1328 - opened 6 days ago, no response from AWS yet.

https://github.com/aws-amplify/aws-sdk-ios/issues/1318 - opened 10 days ago, no response from AWS yet.

https://github.com/aws-amplify/aws-sdk-ios/issues/1235 - opened Feb 14, latest AWS reponse Feb 15 "we will post an update here about our findings" - no more info despite multiple requests.

Thanks,
Thomas

**Comment by rohandubal** [comment]
Hello @thomers 

We will be following up on the issues which you have opened. I am closing this specific as the follow up would be on individual threads.

Thanks,
Rohan

**Comment by thomers** [comment]
Thank you!
