### ISSUE TITLE
AWSMobileClient - Documentation for needed Unauthenticated / Authenticated IAM Roles?

### ISSUE THREAD

**Issue by thomers** [aws-amplify/aws-sdk-ios#1406]
I'm using AWSMobileClient 2.9.4 with a Cognito user pool + federated identities.

I'm not using the aws-amplify CLI.

What are the required IAM policies for the unauthenticated and authenticated Cognito roles that AWSMobileClient expects?

**Comment by rohandubal** [comment]
Hello @thomers 

AWSMobileClient itself would not need IAM policies. The IAM policies would be for the services which you are using. Can you specify which services and what use-cases are you using them for?
