### ISSUE TITLE
AWSMobileClient AuthUI - more customization options for SignUp form

### ISSUE THREAD

**Issue by thomers** [aws-amplify/aws-sdk-ios#1407]
**Which AWS Services is the feature request for?**
The Cognito SignUp form of the drop-in UI

**Is your feature request related to a problem? Please describe.**
We need more customization options for the SignUp form of the drop-in Auth UI.

**Describe the solution you'd like**
Required:
* Terms of Service - link to webpage shown in modal popup and required checkbox for signup 
* Privacy Policy - same as above (not sure what Apple currently expects in terms of GDPR etc.)

Ideally, some generic, modular way to add form fields to the signup form.

**Comment by rohandubal** [comment]
Hello @thomers 

These definitely seem reasonable things to add on the sign in screen.

How do you imagine this feature to be available for the developers? Would it be in a way that we allow specifying 2-3 custom links at bottom of screen? Or would it be something which the developer will customize via some hooks?

**Comment by thomers** [comment]
Hi @rohandubal , for reference, here's how [Firebase Auth UI](https://github.com/firebase/FirebaseUI-iOS/blob/master/Auth/README.md#customizing-firebaseui-for-authentication ) does it.

I don't have any strong opinion on this, just thinking about the requirement to be GDPR compliant.

Some more references:

https://www.mobiloud.com/blog/gdpr-compliant-mobile-app/
> When someone registers on your mobile app, they should be asked to opt-in to have their data collected, or to receive communications, such as emails or Push Notifications. We highly recommend showing a consent screen on app launch, as this is the only way to be fully GDPR compliant. You should also notify users on these screens exactly where their data will be used. For example, will they be tracked in Google Analytics, or have data sent to Google Admob to show them relevant ads? Your users need to know, and it’s your obligation to inform them as soon as they begin using your GDPR compliant mobile app!

Also, https://brianpagan.net/2018/privacy-a-quick-overview-for-app-designers/ has a great overview and UX/UI examples.

**Comment by atierian** [comment]
Thanks for this feature request. We recommend using [Amplify Authenticator](https://ui.docs.amplify.aws/swift/connected-components/authenticator), which has extensive customization options.
