### ISSUE TITLE
Put S3 bucket policy

### ISSUE THREAD

**Issue by trondkr** [aws-amplify/aws-sdk-ios#1408]
Hi, 
I am trying to put a bucket policy on a newly created S3 bucket programmatically but it fails. Below is my policy class which returns the policy as a JSON dictionary as a string: 

CLASS 1 - create the policy 
```Swift
import Foundation 
import awsosx 
class SDBucketPolicy { 

private func jsonToString(json: AnyObject)-> String? { 
 do { 
    let data1 = try JSONSerialization.data(withJSONObject: json, options: 
    JSONSerialization.WritingOptions.prettyPrinted) // first of all convert json to the data 
    return String(data: data1, encoding: String.Encoding.utf8)
  } catch let myJSONError { 
    print(myJSONError) 
  } 
return kSDEmpyString 
} 


@objc func returnS3Policy(bucketName:String, accountSTS:AWSSTSGetCallerIdentityResponse)-> String? { 

    let account = accountSTS.account 
    let userId = accountSTS.userId 
    let bucketDetailObj = "arn:aws:s3:::\\(bucketName)" 
    let bucketDetail = "arn:aws:s3:::\\(bucketName)/*" 
    guard let userIdstring = userId else { 
     return kSDEmpyString 
    }  

    guard let accountstring = account else { 
       return kSDEmpyString 
    } 
    let iamUserId = userIdstring 
    let iamAccount = accountstring 
    let jsonPolicy:[String:Any] = [ 
    "Version": "2012-10-17", 
    "Id": "S3BucketPolicy", 
    "Statement": [ 
    "Sid":"DenyAllAccessExceptToUser", 
    "Effect": "Deny", 
    "Principal": [ 
    "AWS": "*" 
    ], 
    "Action": ["s3:*"], 
    "Resource": [bucketDetail,bucketDetailObj], 
    "Condition": [ 
    "StringNotLike": [ 
    "aws:userId": [iamUserId,iamAccount] 
    ] 
   ] 
  ] 
 ] 
    if (JSONSerialization.isValidJSONObject(jsonPolicy)) { 
       return jsonToString(json: jsonPolicy as AnyObject) 
   } 
  return kSDEmpyString 
 }  
 } 
```

CLASS 2: Below are the methods that use the methods in CLASS 1 to request the putBucketPolicy: 

```Swift
@objc class SDBucketPolicyTools:NSObject { 

    func getCallerID(region:String)-> AWSTask<AnyObject> { 

       let sts = AWSSTS(forKey: region) 
       return sts.getCallerIdentity(AWSSTSGetCallerIdentityRequest()).continueWith { (task) -> 
      Any? in 
       return task 
      } 
    } 
@objc func putBucketPolicy(bucket:SDS3Bucket) -> AWSTask<AnyObject>? { 

    if let putBucketpolicyReq = AWSS3PutBucketPolicyRequest() {  
    putBucketpolicyReq.bucket = bucket.name 
    let awsClient = AWSS3.s3(forKey:bucket.regionShortName) 

    getCallerID(region:bucket.regionShortName).continueWith(block: { (task) -> AnyObject in 

    if let res = task.result { 
     let sts = res as! AWSSTSGetCallerIdentityResponse 
    // Create and return the policy for the bucket and store as attribute string 
     let pt = SDBucketPolicy() 
     putBucketpolicyReq.policy = pt.returnS3Policy(bucketName:bucket.name, accountSTS:sts) 

     return awsClient.putBucketPolicy(putBucketpolicyReq).continueWith(block: { (task) -> Any? in 
     if ((task.error) != nil){ 
     }else{ 
    } 
    return task 
    }) 
    } 
    return task 
    }) 
   } 
   return nil 
   } 
   }  
```
This fails with: 
```bash
2019-04-05 12:11:27.724227-0700 TestDebug[4792:1325618] awsmtl_JSONDictionaryTransformerWithModelClass: NSString 
2019-04-05 12:11:27.724308-0700 TestDebug[4792:1325618] *** Assertion failure in +[NSValueTransformer awsmtl_JSONDictionaryTransformerWithModelClass:], /Users/trondkr/Dropbox/Projects/AWS/aws-sdk-macos/AWSCore/Mantle/NSValueTransformer+AWSMTLPredefinedTransformerAdditions.m:52
```
Do you see what could be wrong? Thank you. Cheers, Trond

**Comment by rohandubal** [comment]
I see from the error log that this SDK is modified for OSX. In that case it would be difficult to identify why the marshaller would run into issues. The SDK and marshaller have not been validated for OSX and can be unstable.

**Comment by trondkr** [comment]
Thanks for your response. I understand that I have modified the SDK to be usable as a macos framework but everything works very well except the `putBucketPolicy`. I can't understand why the framework serializer/marshaller should behave differently on a macos vs iOS, although I may be wrong. But this is the only method I can´t get to work and I think there may be a bug in the method. If I run the above code without specifying a policy it works except it comes back with an error message "malformed policy". So the problem is how the policy is added to the request. When you add a policy to an SNS request you can send it as a JSON NSString. I thought that would work here as well (and `AWSS3PutBucketPolicyRequest.policy` is an NSString), but the method then fails with the serializer that does not conform to AWSModel class but instead as NSString:

```
awsmtl_JSONDictionaryTransformerWithModelClass:` NSString
```

I noticed that in `ASWSS3Serializer.m` there is a strange workaround which I was wondering was the culprit of the error:
```
> //get and put bucket policy use json, while rest use xml
        if([[_actionName lowercaseString] isEqualToString:@"putbucketpolicy"]
           || [[_actionName lowercaseString] isEqualToString:@"getbucketpolicy"]){
            NSLog(@"JSONDefinition %@",JSONDefinition);
            _requestSerializer = [[AWSJSONRequestSerializer alloc]initWithJSONDefinition:JSONDefinition actionName:actionName];
        }else{
            _requestSerializer = [[AWSXMLRequestSerializer alloc]initWithJSONDefinition:JSONDefinition actionName:actionName];
        } 
```

I can create an iOS example for this but I honestly think this could be a bug in the method.

**Comment by trondkr** [comment]
@rohandubal  So I have looked into this some more and I think this crashes because of a bug in the Serializer. In 'AWSS3Model.m' the 'AWSS3PutBucketPolicyRequest' sends an 'NSString' to the 'awsmtl_JSONDictionaryTransformerModelClass' which does not conform to the 'AWModel' class and therefore fails. The NSString is only sent in the 'putBucketPolicy' and 'getBucketPolicy' methods and I, therefore, wonder if this is a bug. The Serializer won't be able to parse the JSON file given the lack of an AWSModel for the policy (e.g. like AWSTagging class). Could you take a look? Thank you, Cheers, Trond

**Comment by trondkr** [comment]
@rohandubal - Any chance you could review my last comment here? I think its a bug with both put and get a policy on S3 bucket, but I may be mistaken. Great to hear your thoughts.

**Comment by trondkr** [comment]
@palpatim and @muellerfr - would you know if this is an issue you expect to have fixed in the near future? For me, it would be great to have this issue fixed to be able to put custom policies on s3 buckets to users.

**Comment by palpatim** [comment]
@trondkr 

Sorry for the delayed response. As @rohandubal alluded to, we have to keep our efforts focused on our officially supported platforms. If you're able to identify a code fix and file a PR that makes this cross-platform compatible, we can look merging it in (we have to be somewhat careful, since many of our serializers are automatically generated based on service models), but realistically, this is not likely to make our list of priorities any time soon.
