### ISSUE TITLE
Refresh Token has been revoked

### ISSUE THREAD

**Issue by krunaldarji** [aws-amplify/aws-sdk-ios#1410]
**Describe the bug**
Intermittently i am getting "Refresh Token has been revoked" error and that time session completeBlock not getting executed.

```
-(void)checkIfUserIsLoggedInWithCompletionHandler:(void (^)(AWSTask<AWSCognitoIdentityUserSession*> * session,bool isSignedIn))completionHandler {
    
    [self awsGeneralSetUp];
    
    AWSCognitoIdentityUserPool * pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:USER_POOL_KEY];
    
    pool.delegate = self;
    
    AWSCognitoIdentityUser * user = [[AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:USER_POOL_KEY] currentUser];
    
    if (user.isSignedIn) {
        AWSTask<AWSCognitoIdentityUserSession*> * session = [user getSession];
        
        DDLogInfo(@"User session %@",session.result);
        [session continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserSession *> * _Nonnull session) {

**//RESPONSE NOT COMING HERE**
                if (session.result.idToken.tokenString != nil) {
                    DDLogInfo(@"Token to be used %@ accessToken %@ refreshToken %@",session.result.idToken.tokenString,session.result.accessToken.tokenString,session.result.refreshToken.tokenString);
                    DDLogInfo(@"User has already logged in");
                    //* Strt timer for refresh token
                    [iOSHelper performActionOnMainThread:^{
                        timerForRefreshTokens = [NSTimer scheduledTimerWithTimeInterval:TOKEN_REFRESH_DELAY target: self selector:@selector(refreshTokens) userInfo: nil repeats:YES];
                    }];
                    completionHandler(session,true);
                } else {
                    completionHandler(nil,false);
                }
                return nil;
            }];
        
        
    } else {
        completionHandler(nil,false);
    }
}
```

**Environment(please complete the following information):**
 - SDK Version: 2.8.1
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Objective C

***Logs***

2019-04-04T07:54:12.905-0400|11589|D|Response headers:
{
    "Content-Length" = 78;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Thu, 04 Apr 2019 11:54:12 GMT";
    "x-amzn-errormessage" = "Refresh Token has been revoked";
    "x-amzn-errortype" = "NotAuthorizedException:";
    "x-amzn-requestid" = "5d1b7f0a-56d0-11e9-a6e5-9ba0ebe3a920";
}|[AWSURLSessionManager-[AWSURLSessionManager printHTTPHeadersForResponse:]@575]

2019-04-04T07:54:12.905-0400|11589|D|Response body:
{"__type":"NotAuthorizedException","message":"Refresh Token has been revoked"}|[AWSURLResponseSerialization-[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:]@62]

**Comment by dokutoshi** [comment]
Seems I am having a similar issue too.  AWS Please fix.

**Comment by royjit** [comment]
Hi, When refresh token expires the SDK will call `startPasswordAuthentication`, here you have to return an object that conforms to `AWSCognitoIdentityPasswordAuthentication` protocol.

SDK then will invoke `getPasswordAuthenticationDetails` method on the object. Please verify that you have this logic in place. [Ref Cognito Doc](https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-ios-sdk.html)
