### ISSUE TITLE
Controlling when mutation gets trigger, instead of depending on device connectivity

### ISSUE THREAD

**Issue by AoumiS** [aws-amplify/aws-sdk-ios#1437]
**State your question**
Is there a configuration / work-around to prevent AppSync mutations from processing even when device is connected to the internet. 

Currently, if device is offline, the mutation is being store and will automatically submit offline mutation to the server, we would like to control this function. User can toggle a setting which will not submit mutations to server (even device is online) until the user decides to toggle back to allow mutations to be synced to server.

**Which AWS Services are you utilizing?**
AWS AppSync

**Provide code snippets (if applicable)**
No Available

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29] Lastest
 - Dependency Manager: [e.g. Cocoapods, Carthage] Cocoapods
 - Swift Version : [e.g. 4.0] 4.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] Device & Simulator
 - iOS Version: [e.g. iOS 11.4] > 11.0
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by desokroshan** [comment]
Closing this issue in favor of https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/231
