### ISSUE TITLE
S3 SDK INTEGRATION MANUAL PROCESS

### ISSUE THREAD

**Issue by harishmaddula32** [aws-amplify/aws-sdk-ios#1443]
Manually integrating SDK in sample application. getting below error.

Steps followed by below link:
[https://aws-amplify.github.io/docs/ios/manualsetup](https://aws-amplify.github.io/docs/ios/manualsetup)

bash: /Users/mindscape/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/Integration.app/Frameworks/AWSCore.framework/strip-frameworks.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
![Screen Shot 2019-04-12 at 5 24 59 PM](https://user-images.githubusercontent.com/3964198/56035487-f40c0380-5d47-11e9-99a6-3c1b38ca4535.png)

[dyld: Library not loaded: @rpath/AWSCore.framework/AWSCore
  Referenced from: /Users/mindscape/Library/Developer/CoreSimulator/Devices/293337D6-E308-4E38-A006-6C08CBBADE76/data/Containers/Bundle/Application/71EF2D9E-32F9-48DF-93D7-2BCE91E1E52E/Integration.app/Frameworks/AWSS3.framework/AWSS3
  Reason: image not found
(lldb)

XCODE : 10.2
MAC OS : 10.14.4
SMULATOR

**Comment by palpatim** [comment]
@harishmaddula32 

Thanks for the report. It is necessary to link AWSCore to your project for manual setup to work. Can you confirm that you've added the AWSCore framework to your linked frameworks, as well as AWSS3?

If that turns out to solve your issue, please reply here, as we may need to clarify this step in our documentation.

**Comment by harishmaddula32** [comment]
Yes It's working. Tq

**Comment by muellerfr** [comment]
@harishmaddula32 - thank you for confirm. I am going to close this issue. If you still require help, please open another issue.
