### ISSUE TITLE
AWS Cognito confirmedStatus is incorrect

### ISSUE THREAD

**Issue by johnmurphy01** [aws-amplify/aws-sdk-ios#1469]
**Describe the bug**
The value of `confirmedStatus` is not set properly when the `signUp` method is called. If the account in question is already confirmed, the value of `confirmedStatus` will always be "unconfirmed". This is because `userConfirmed` is a boolean value being cast to an integer whereas `confirmedStatus` is an enum.

**To Reproduce**
1. Use the sample or create a sample in which the account being created will automatically be confirmed and verified
2. If auto confirmed, perform a different flow than if not auto confirmed

**Which AWS service(s) are affected?**
AWSCognitoIdentityProvider

**Expected behavior**
The `confirmedStatus` should be confirmed for auto confirmed accounts

**Screenshots**
Line numbers of offending bug: https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m#L211-L215

**Environment(please complete the following information):**
 - SDK Version: 2.9.1
 - Dependency Manager: Cocoapods
 - Swift Version : 4 and 5

**Device Information (please complete the following information):**
 - Device: any
 - iOS Version: 11 and 12

**Additional context**
We can work around this by directly accessing `userConfirmed`

**Comment by royjit** [comment]
Hi @johnmurphy01 Thank you for reporting this issue. I have raised a PR #1844  to handle this.

**Comment by palpatim** [comment]
We released this in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0

Please let us know if you have any problems with this.
