### ISSUE TITLE
Lost connection to background service (-997) - AWSTransferUtility

### ISSUE THREAD

**Issue by wowrahul** [aws-amplify/aws-sdk-ios#1472]
**Describe the bug**
We use uploadFile method to upload files in our app. For some of our iOS users, the upload task fail with Lost connection to background service (-997). Once the app runs into this issue, all new uploads fail. We are also seeing unknown error for some of these users.

Some of the users were able to get it fixed by resetting network settings. But we haven't been able to find a consistent way of handling this.

**To Reproduce**
We haven't been able to reproduce this on our end but some of our users have run into this.

**Which AWS service(s) are affected?**
AWSTransferUtility

**Expected behavior**
In case of -997 error, the app should be able to upload other files.

**Environment(please complete the following information):**
 - SDK Version: 2.8.4
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: Any iOS device

**Additional context**
We believe this issue popped up in iOS 12. Since it's related to background session, is there anything that can be done from within the app to address this?

**Comment by wowrahul** [comment]
Any updates on this?

**Comment by royjit** [comment]
Hi,

Apologies for the delayed response. Looks like this error is generated when the deamon for NSURLSession background session crashes. Would you be able to check the device logs if this is happening?
Are you facing the issue in the latest SDK?
