### ISSUE TITLE
Transfer listener for downloading multiple files

### ISSUE THREAD

**Issue by harishmaddula32** [aws-amplify/aws-sdk-ios#1473]
Below code i'm using for downloading multiple files contains in one single folder..
Is there any block or completion handler to know status once all files are downloaded ?

Note: I'm asking for completion status for all files not for single file.

AWSS3ListObjectsOutput *listObjectsOutput = task.result;
            for (AWSS3Object *s3Object in listObjectsOutput.contents)
            {
                NSString *fileName = [[s3Object.key componentsSeparatedByString:@"/"] lastObject];
                listObjectsRequest.prefix = fileName;
                NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
                NSString *documentDirectory = [paths objectAtIndex:0];
                NSString *downloadingFilePath = [documentDirectory stringByAppendingPathComponent:fileName];
                NSString *filePath = [downloadingFilePath stringByDeletingLastPathComponent];
                NSError *error;
                BOOL isDir;
                BOOL isExists = [[NSFileManager defaultManager] fileExistsAtPath:filePath isDirectory:&isDir];
                if (!isExists)
                {
                    if (![[NSFileManager defaultManager] createDirectoryAtPath:filePath withIntermediateDirectories:NO attributes:nil error:&error])
                    {
                        NSLog(@"Create directory error: %@", error);
                    }
                }
                NSURL *downloadingFileURL = [NSURL fileURLWithPath:downloadingFilePath];
                NSLog(@"path.... %@",downloadingFilePath);
                NSLog(@"s3 key.... %@",s3Object.key);
                
                AWSS3TransferUtilityDownloadExpression *expression = [AWSS3TransferUtilityDownloadExpression new];
                expression.progressBlock = ^(AWSS3TransferUtilityTask *task, NSProgress *progress) {
                    dispatch_async(dispatch_get_main_queue(), ^{
                    });
                };
                
                AWSS3TransferUtilityDownloadCompletionHandlerBlock completionHandler = ^(AWSS3TransferUtilityDownloadTask *task, NSURL *location, NSData *data, NSError *error) {
                    if (error) {
                        NSLog(@"Failed to Download");
                    }
                    if (data) {
                        //NSLog(@"Successfully Downloaded");lll.
                        NSLog(@"data.. %@",data);
                        NSLog(@"path %@",downloadingFilePath);
                    }
                };
                
                AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
                transferUtility.s
                [[transferUtility downloadToURL:downloadingFileURL bucket:@"aisles3" key:s3Object.key expression:expression completionHandler:completionHandler]continueWithBlock:^id(AWSTask *task) {
                    if (task.error) {
                        NSLog(@"Error: %@", task.error);
                    }
                    return nil;
                }];
            }

**Comment by palpatim** [comment]
@harishmaddula32 The TransferUtility does not offer this feature. One possible workaround would be to create a `DispatchGroup` to indicate that you can move to the next step. Each downloaded file would `enter` the group, and its completion handler (on either success or failure) would `leave` the group. In the group's `notify` method, you could then inspect the results of each individual file operation and take appropriate actions.

Longer term, this seems like something we'd want to address an a fully-fledged "directory operations" feature, but we don't have any current roadmap item for that.
