### ISSUE TITLE
Crash in AWSMQTTEncoder.m line 50

### ISSUE THREAD

**Issue by docee** [aws-amplify/aws-sdk-ios#1488]
**Describe the bug**

Fabric shows more crashes here, but I can't reproduce the crash at this time.

**To Reproduce**

Can not reproduce

**Which AWS service(s) are affected?**

IoT

**Expected behavior**
Do not crash

**Environment(please complete the following information):**
 - SDK Version: 2.9.5
 - Dependency Manager: Cocoapods
 - Swift Version : Objc

**Device Information (please complete the following information):**
 - Device: iPhone7, iPhone 7P, iPhone 8, etc
 - iOS Version: iOS 12
 - Specific to simulators:

**Additional context**
[com.netviewtech.mynetvue_issue_crash_834afa5dce7f472a8ef2d979050b5c1d_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101807/com.netviewtech.mynetvue_issue_crash_834afa5dce7f472a8ef2d979050b5c1d_DNE_0_v2.txt)
[com.netviewtech.mynetvue_issue_crash_d3b7aaff1d6e4ba48b7520e262cc258f_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101808/com.netviewtech.mynetvue_issue_crash_d3b7aaff1d6e4ba48b7520e262cc258f_DNE_0_v2.txt)
[com.netviewtech.mynetvue_issue_crash_82097f40134a47199fd1a73dc2f71436_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101809/com.netviewtech.mynetvue_issue_crash_82097f40134a47199fd1a73dc2f71436_DNE_0_v2.txt)

**Comment by palpatim** [comment]
@docee 

Thank you for the report and the stack traces. As we investigate this, can you confirm whether you're seeing this crash on the most recent version of the SDK? We did an IoT bug fix in 2.9.4 that may impact some instabilities during the connection release/reconnect phase.

**Comment by docee** [comment]
@palpatim 

I am very sorry, I wrote the wrong SDK version, it should be 2.9.5.

When our device list changes, we need to update the STS. After updating the STS, we need to reconnect the IoT Client (not IoT Data, so we need to reconnect) to control the new device with the new STS permission.

Because the state callback of AWSIoTDataManager is slow, especially disconnected. So I used a MAGIC method, set AWSIoTDataManager to nil and new a new AWSIoTDataManager. 

So I suspect that it may be that AWSIoTMQTTClient does not set some pointer to NULL when dealloc.

**Comment by docee** [comment]
BTW, if AWSIoTDataManager can add a **reconnect** method is perfect. 😁

**Comment by barbarity** [comment]
@docee can you confirm if that solved your issue? We are experiencing a similar crash.

**Comment by docee** [comment]
@barbarity In fact, it has not been resolved. So my choice is to let it go.
