### ISSUE TITLE
Crash in AWSIoTMQTTClient.m line 1184

### ISSUE THREAD

**Issue by docee** [aws-amplify/aws-sdk-ios#1489]
**Describe the bug**

Fabric shows more crashes here, but I can't reproduce the crash at this time.

**To Reproduce**

Can not reproduce

**Which AWS service(s) are affected?**

IoT

**Expected behavior**
Do not crash

**Environment(please complete the following information):**
 - SDK Version: 2.9.5
 - Dependency Manager: Cocoapods
 - Swift Version : Objc

**Device Information (please complete the following information):**
 - Device: iPhone7, iPhone 7P, iPhone 8, etc
 - iOS Version: iOS 12
 - Specific to simulators:

**Additional context**
[com.netviewtech.mynetvue_issue_crash_cebd34082cfc4b39b3eb3adc9d41845a_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101810/com.netviewtech.mynetvue_issue_crash_cebd34082cfc4b39b3eb3adc9d41845a_DNE_0_v2.txt)
[com.netviewtech.mynetvue_issue_crash_e6e8fea135e741469f9b780fd54ad20d_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101811/com.netviewtech.mynetvue_issue_crash_e6e8fea135e741469f9b780fd54ad20d_DNE_0_v2.txt)
[com.netviewtech.mynetvue_issue_crash_fd0b3ec61d8b4767946394725dd4e0ea_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101812/com.netviewtech.mynetvue_issue_crash_fd0b3ec61d8b4767946394725dd4e0ea_DNE_0_v2.txt)

**Comment by palpatim** [comment]
@docee 

Thank you for the report and the stack traces. As we investigate this, can you confirm whether you're seeing this crash on the most recent version of the SDK? We did an IoT bug fix in 2.9.4 that may impact some instabilities during the connection release/reconnect phase.

**Comment by docee** [comment]
@palpatim 

I am very sorry, I wrote the wrong SDK version, it should be 2.9.5.

When our device list changes, we need to update the STS. After updating the STS, we need to reconnect the IoT Client (not IoT Data, so we need to reconnect) to control the new device with the new STS permission.

Because the state callback of AWSIoTDataManager is slow, especially disconnected. So I used a MAGIC method, set AWSIoTDataManager to nil and new a new AWSIoTDataManager. 

So I suspect that it may be that AWSIoTMQTTClient does not set some pointer to NULL when dealloc.

**Comment by wooj2** [comment]
Looking at the stack trace on:
https://github.com/aws-amplify/aws-sdk-ios/issues/1490
Seems to be very similar to the stack traces posted to this ticket (symbol-cated differently, but seems like the same issue)

This seems to have been fixed as of aws sdk ios 2.16.0

Closing as a duplicate.
