### ISSUE TITLE
Crash in AWSSRWebSocket.m line 773

### ISSUE THREAD

**Issue by docee** [aws-amplify/aws-sdk-ios#1490]
**Describe the bug**

Fabric shows more crashes here, but I can't reproduce the crash at this time.

**To Reproduce**

Can not reproduce

**Which AWS service(s) are affected?**

IoT

**Expected behavior**
Do not crash

**Environment(please complete the following information):**
 - SDK Version: 2.9.5
 - Dependency Manager: Cocoapods
 - Swift Version : Objc

**Device Information (please complete the following information):**
 - Device: iPhone7, iPhone 7P, iPhone 8, etc
 - iOS Version: iOS 12
 - Specific to simulators:

**Additional context**
[com.netviewtech.mynetvue_issue_crash_7594c2f694154697ab846b0077db3092_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101815/com.netviewtech.mynetvue_issue_crash_7594c2f694154697ab846b0077db3092_DNE_0_v2.txt)
[com.netviewtech.mynetvue_issue_crash_2b62ed61449a459183239990f180fe62_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101816/com.netviewtech.mynetvue_issue_crash_2b62ed61449a459183239990f180fe62_DNE_0_v2.txt)
[com.netviewtech.mynetvue_issue_crash_6f1a203829c4440cb50c7b39a7c710e8_DNE_0_v2.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3101817/com.netviewtech.mynetvue_issue_crash_6f1a203829c4440cb50c7b39a7c710e8_DNE_0_v2.txt)

**Comment by palpatim** [comment]
@docee 

Thank you for the report and the stack traces. We know that we're As we investigate this, can you confirm whether you're seeing this crash on the most recent version of the SDK? We did an IoT bug fix in 2.9.4 that may impact some instabilities during the connection release/reconnect phase.

That commit didn't touch SocketRocket in particular, so it may be unrelated, but we'd still like to confirm the behavior.

**Comment by docee** [comment]
@palpatim 

I am very sorry, I wrote the wrong SDK version, it should be 2.9.5.

When our device list changes, we need to update the STS. After updating the STS, we need to reconnect the IoT Client (not IoT Data, so we need to reconnect) to control the new device with the new STS permission.

Because the state callback of AWSIoTDataManager is slow, especially disconnected. So I used a MAGIC method, set AWSIoTDataManager to nil and new a new AWSIoTDataManager. 

So I suspect that it may be that AWSIoTMQTTClient does not set some pointer to NULL when dealloc.

**Comment by wooj2** [comment]
Seems like the bug we are seeing here would get resolved with the commit merged here:
https://github.com/aws-amplify/aws-sdk-ios/pull/2984

I am optimistically closing this issue as the original issue seemed to report that this fix helped them in fixing this crashing bug.
