### ISSUE TITLE
AWS API Gateway GET request header missing.

### ISSUE THREAD

**Issue by manomuthu-optisol** [aws-amplify/aws-sdk-ios#1496]
Hi guys,

 Am using AWS API Gateway(2.6.33) auto generated SDK for Swift. While using that for GET request am passing auth token in header with IAM credentials. But its returning "Missing Token Header.”. While am checking in postman it’s working fine. Don’t know what am missing here.

Thanks in advance.
Muthu

**Comment by palpatim** [comment]
@manomuthu-optisol 

Thanks for reporting the issue. Do note that 2.6.33 is fairly old; we're up to version 2.9.6 now. That said, I wouldn't expect there to be any changes in APIGateway behavior since that code.

Can you provide a code snippet showing how you populate the header and invoke the `GET` request on your generated client? Please make sure not to include any sensitive information like credentials or keys.

**Comment by manomuthu-optisol** [comment]
Thanks for the support @palpatim. As you said while am trying to update the framework I got the below error. 
<img width="570" alt="Screenshot 2019-04-24 at 11 58 26 AM" src="https://user-images.githubusercontent.com/20903164/56637061-50e0b580-6688-11e9-919c-34be36a2844d.png">

Here is what am doing in app.

Using the Accesskey, SecretKey and session Token am registering the new client with a unique key

let credentialsProvider = AWSBasicSessionCredentialsProvider(accessKey: accessKey, secretKey: secretKey, sessionToken: sessionToken)
        let configuration = AWSServiceConfiguration(region:region, credentialsProvider:credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        ******NetworkClient.registerClient(withConfiguration: configuration!, forKey: "key")

After registering the client am trying to hit GET method as below:

        let client = ******NetworkClient.client(forKey: "key")
        
        client.userProfileGet(token: token).continueWith { (task: AWSTask<******UserProfileResponse>) -> Any? in
            
            
            if let error = task.error {
                print("Error occurred: \(error)")
                return nil
            }
            
            if let result = task.result {
                // Do something with result
            }
            return nil
        }


public func userProfileGet(token: String) -> AWSTask<*******UserProfileResponse> {
	    let headerParameters = [
                   "Content-Type": "application/json",
                   "Accept": "application/json",
                   "Token": token
	            ]
	    
	    let queryParameters:[String:Any] = [:]
	    
	    let pathParameters:[String:Any] = [:]
	    
	    return self.invokeHTTPRequest("GET", urlString: "/user/profile", pathParameters: pathParameters, queryParameters: queryParameters, headerParameters: headerParameters, body: nil, responseClass: *******UserProfileResponse.self) as! AWSTask<*******UserProfileResponse>
	}


In the above you can see that am passing the "Token" in header. Even though am receiving error as Missing Token header.

**Comment by manomuthu-optisol** [comment]
After Updating the framework to version 2.9.6. Issue was cleared and its working fine. Thanks for the support @palpatim

**Comment by palpatim** [comment]
Glad it worked out!
