### ISSUE TITLE
How do I store the certificateID into the keychain to connect to MQTT ?

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-ios#1498]
Originally posted by [devish](https://forums.aws.amazon.com/profile.jspa?userID=481810) on [AWS Forums](https://forums.aws.amazon.com/thread.jspa?threadID=302154&tstart=0)

---

I'm having trouble using the `AWSIotDataManager` class to connect to the AWS MQTT broker in order to subscribe to events. I was passing the the `certificateID` string to the `.connect` method , but then realised that above the `.connect` method definition it mentions that: "the `certificateID` must be stored in the KeyChain".

I came across the `AWSIoTKeychain` class but I not sure how to use it.

I also came across the `AWSIoTManager.createKeysAndCertificateFromCsr`, but I also cannot figure out how to utilise it given the fact that I'm using the `AWSIoTDataManager` class instead.

How do I store the certificateID in the keychain? and then how do I use it to connect to the AWS MQTT broker? (I have the `certID`, `pem`, and `privateKey`)

```swift
let credentialsProvider:AWSCognitoCredentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSRegionType.EUWest1, identityPoolId: consumerPoolId);
    
let iotEndPoint = AWSEndpoint(urlString: endPoint);
 
let iotDataConfiguration = AWSServiceConfiguration(
      region: AWSRegionType.EUWest1,
      endpoint: iotEndPoint,
      credentialsProvider: credentialsProvider
);
AWSServiceManager.default()?.defaultServiceConfiguration = iotDataConfiguration;
AWSIoTDataManager.register(with: iotDataConfiguration!, forKey: KEYSTORE_NAME);
 
iotDataManager = AWSIoTDataManager(forKey: KEYSTORE_NAME);
 
func mqttEventCallback(status: AWSIoTMQTTStatus) {
      if(status == AWSIoTMQTTStatus.connected) {
        iotDataManager.subscribe(
          toTopic: topic,
          qoS: .messageDeliveryAttemptedAtMostOnce,
          messageCallback: {
            (payload) ->Void in
            let stringValue = String(data: payload, encoding: String.Encoding.utf8)!;  
            // do stuff with the payload
            // ...
        } );
        
      }
}
 
let isConnected: Bool = iotDataManager.connect(withClientId: clientID,
                           cleanSession: true,
                           certificateId: certID,
                           statusCallback: mqttEventCallback);
```

**Comment by armouti** [comment]
@palpatim @rohandubal From looking briefly at the source code of the method, it seems to me that the callback provided to the `statusCallback` parameter is supposed to be invoked even if the connection failed for any reason. However, I should draw your attention to the fact that the callback provided as `mqttEventCallback` is never invoked.

**Comment by armouti** [comment]
@palpatim @rohandubal any help on this would be greatly appreciated!
