### ISSUE TITLE
Hosted UI can not get 'name' of Google user

### ISSUE THREAD

**Issue by HayTran94** [aws-amplify/aws-sdk-ios#1501]
**Is your feature request related to a problem? Please describe.**
Even though I check "name" attribute mapping of Google provider but I can get it, but I can do that with Facebook account.

**Describe the solution you'd like**
Support get name of Google account like Facebook does.

**Comment by royjit** [comment]
Hi @HayTran94 How are you fetching the `name` attribute? I was able to see the `name` inside the attributes when I invoked the following method:

```
AWSMobileClient.default().getUserAttributes { attributes, error in
            print(attributes!["name"])
}
```

**Comment by HayTran94** [comment]
> Hi @HayTran94
> Apologies for the delayed response.
> How are you fetching the `name` attribute? I was able to see the `name` inside the attributes when I invoked the following method:
> 
> ```
> AWSMobileClient.default().getUserAttributes { attributes, error in
>             print(attributes!["name"])
> }
> ```

I do not use this sdk anymore. So if you find out it work now, you should close it.

**Comment by royjit** [comment]
Thank you for the reply. Please feel free to reach out to us if you have any other questions.
