### ISSUE TITLE
S3TransferUtilitySampleSwift Version Issue

### ISSUE THREAD

**Issue by colinheye** [aws-amplify/aws-sdk-ios#1503]
Build fails with error SWIFT_VERSION '3.0' is unsupported (in target 'AWSMobileClient' and 'S3TransferUtilitySampleSwift'). 

I cloned sample repository, followed Readme instructions for the S3 sample and am running Xcode 10.2.1 

 - SDK Version: awsconfiguration.json has Version 0.1.0
 - Dependency Manager: Cocoapods
 - Swift Version : Apparently 3

 - Device: iPhone XR Simulator
 - iOS Version: Targeting 9.0 (I believe)

**Comment by palpatim** [comment]
Thanks for reporting. I've got an in-process project to ensure compatibility with Swift 5, and I'll ensure that this is part of that effort.

**Comment by colinheye** [comment]
Is it possible to run this sample in Xcode 10.2.1, either by downgrading the compiler to Swift 3 or by updating the code to Swift 4 or 5? Apologies if this is a naive question

**Comment by palpatim** [comment]
@colinheye 

Unfortunately, the only solution is to update the projects to use Swift 4.2 or higher.

We're working on a release of the core SDK now that makes it build properly with Xcode 10.2, and the samples are in progress. I've got some of them working, but some are taking a bit longer to migrate. I'll update here when I have more info.

In the meantime, you can check my work in progress on the [`palpatim/swift-5-compat` branch of the samples repo](https://github.com/awslabs/aws-sdk-ios-samples/tree/palpatim/swift-5-compat).

```bash
git clone https://github.com/awslabs/aws-sdk-ios-samples.git
cd aws-sdk-ios-samples
git checkout palpatim/swift-5-compat
```

The Podfiles in that branch depend on `~> 2.9.0` of the AWS SDKs, which until we release 2.9.8, may not be compatible with Xcode 10.2. To fix, you can manually update the Podfile to point to the develop branch:

**S3TransferUtility-Sample/Swift/Podfile**

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'S3TransferUtilitySampleSwift' do
  pod 'AWSMobileClient', :git => 'git@github.com:aws-amplify/aws-sdk-ios.git', :branch => 'develop'
  pod 'AWSS3', :git => 'git@github.com:aws-amplify/aws-sdk-ios.git', :branch => 'develop'
end
```

**Comment by palpatim** [comment]
@colinheye 

We just released an update to the samples repo that should fix this issue. Please let us know if you have any continued issues.
