### ISSUE TITLE
Disable interactive auth

### ISSUE THREAD

**Issue by ryancrunchi** [aws-amplify/aws-sdk-ios#1504]
**State your question**
For some web services on my own, I would like to use non mandatory session tokens. This means if the user is logged in, ok use tokens. If not logged in, do not force him to log in with interactive auth.
Is it possible to disable interactive auth when trying to fetch session tokens ?

**Which AWS Services are you utilizing?**
Cognito, S3

**Provide code snippets (if applicable)**
We can not do the following :
```
var request = URLRequest(...)
userPool.delegate = nil
userPool.currentUser()?.getSession().continue.continueWith(block: { task in
    if let token = task.result?.idToken?.tokenString {
        request.setValue("Bearer "+token, forHTTPHeaderField: "Authorization")
        // success(request)
    }
    else {
        // success(request) anyway
    }
}
```
Compiler error : `'nil' cannot be assigned to type 'AWSCognitoIdentityInteractiveAuthenticationDelegate'`

**Environment(please complete the following information):**
 - SDK Version: 2.9.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: any
 - iOS Version: 11.3+

**Comment by ryancrunchi** [comment]
OK I worked around by creating an empty delegate class :
```
class EmptyAuthDelegate: NSObject, AWSCognitoIdentityInteractiveAuthenticationDelegate {}
...
userPool.delegate = EmptyAuthDelegate()
```

But still, is there an "official" way of doing this ?

**Comment by royjit** [comment]
`CognitoSDK` for iOS does not support this. You need to have a delegate. If you are using `AWSMobileClient` for signing in the user, you can get the token by `AWSMobileClient.getToken` as explained (here)[https://aws-amplify.github.io/docs/ios/authentication#managing-security-tokens]
