### ISSUE TITLE
Detect error in post-authentication lambda from iOS Mobile SDK

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-ios#1506]
Originally opened by [SwipeStudio](https://forums.aws.amazon.com/profile.jspa?userID=482097) on [AWS Forums](https://forums.aws.amazon.com/thread.jspa?threadID=302373&tstart=0)

---

Hi, 

I'm attempting to implement device limiting functionality on and iOS app using the AWS SDK as described in this doc:

https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/

According to the section 'Limiting Devices' : 

"With this small addition, you can set a maximum for the number of devices that can be linked to a user’s account. Within your post-authentication Lambda hook, you can call the AdminListDevices API to count the number of devices currently linked if the newDeviceUsed flag is set to true. If it is over your determined limit, you fail the call, which then fails the authentication."

I have tried 'failing' the post authentication lambda by returning an error in the callback and a 400 response object in the lambda:

```javascript
    const response = {
                            statusCode: 400,
                            body: JSON.stringify('maximum devices reached'),
                     };
                    
                    var error = new Error("too many devices");
                    event.response = response
                    callback(error, event); 
                    return response;
```

However, this error message never reaches the app via the sdk. Although I can see that the call has failed via the logs an error is not passed back to the app so I can't notify the user. Also, because no error is passed back in the authentication delegate methods the login still succeeds :

```swift
    public func didCompleteStepWithError(_ error: Error?) {
        DispatchQueue.main.async {
            if let error = error as NSError? {
                self.loginCompletionHandler?(LoginAuthenticationResult.error(error))
            } else {
                let authenticationResult = LoginAuthenticationResult.success
                self.loginCompletionHandler?(authenticationResult)
            }
        }
    }
```

Is there anyway I can see the response from the post-authentication lambda in the app? So I can ask the user to 'forgot' other devices?

Any help would be greatly appreciated!!

Thanks, Vick

**Comment by SwipeInteractive** [comment]
Hi, 

Any updates on this? 

Thanks, 
Vick

**Comment by fdarsot** [comment]
@palpatim were you able to successfully create a post-authentication lambda? Im new to lambdas and looking to implement this exact same function. would you mind helping me out?
