### ISSUE TITLE
Loosing network during AWSS3 uploads does not properly reset progress reporting.

### ISSUE THREAD

**Issue by jeffjvick** [aws-amplify/aws-sdk-ios#1512]
**Describe the bug**
I have noticed that if while you are uploading you disable the network and then reenable it (causing the currently upload parts to restart) the progressBlock stops getting updates until the progress has surpassed the point where it left off.  This is true for both single part and multiple-part uploads.  I have not tested downloads.

**To Reproduce**
This is especially evident if you do a **non**-multipart upload. So for example you are uploading a 50 mb file and at 30% you turn on/of the network, it will restart the upload from he beginning but the progress will just sit at 30% until the restarted upload passes back over 30% From there it will continue on as normal.  Obviously this would be very confusing to the user as to what is happening.

**Which AWS service(s) are affected?**
AWSS3

**Expected behavior**
`transferUtilityUploadTask.progress.completedUnitCount` should adjust appropriately back down after upload parts are restarted.  To reflect the current % completed not just sit at the last % point.

**Screenshots**
NA

**Environment(please complete the following information):**
 - SDK Version: 2.9.7
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: iPhone 7 plus
 - iOS Version: iOS 12.2
 - Specific to simulators:  You should only be testing on real devices and not have them connected to the debugger to simulate real world behavior.

**Additional context**

This is referenced from: https://github.com/aws-amplify/aws-sdk-ios/issues/769
@cbommas 

I looked into the AWS3TransferUtility.m code and see the issue. It is only updating transferUtilityUploadTask.progress.completedUnitCount if it is less than'totalBytesSent but this doesn't take into account if totalBytesSent gets reset when parts (or the whole) upload needs to get restarted. I think the easiest way to fix this would be to just use !=. I'm not sure why you have <. I made these two changes and it is working:

```
if (transferUtilityUploadTask.progress.completedUnitCount != totalBytesSent) {
    transferUtilityUploadTask.progress.completedUnitCount = totalBytesSent;
    
    if (transferUtilityUploadTask.expression.progressBlock) {
        transferUtilityUploadTask.expression.progressBlock(transferUtilityUploadTask, transferUtilityUploadTask.progress);
    }
}
```

```
if (transferUtilityMultiPartUploadTask.progress.completedUnitCount != totalSentSoFar ) {
    transferUtilityMultiPartUploadTask.progress.totalUnitCount = [transferUtilityMultiPartUploadTask.contentLength longLongValue];
    transferUtilityMultiPartUploadTask.progress.completedUnitCount = totalSentSoFar;

    //execute the callback to the progressblock if present.
    if (transferUtilityMultiPartUploadTask.expression.progressBlock) {
        AWSDDLogDebug(@"Total %lld, ProgressSoFar %lld", transferUtilityMultiPartUploadTask.progress.totalUnitCount, transferUtilityMultiPartUploadTask.progress.completedUnitCount);
        transferUtilityMultiPartUploadTask.expression.progressBlock(transferUtilityMultiPartUploadTask, transferUtilityMultiPartUploadTask.progress);
    }
}
```

**Comment by jeffjvick** [comment]
@palpatim Tim, Hi, has someone been assigned to this?

**Comment by lawmicha** [comment]
Thanks for the details in this issue. I agree that the the behavior of the progress handler should reflect the actual progress of the work being done, and leave it up to the app developer to decide whether to use the reset-ed value, or use the largest value seen, if for example to show the progress in a progress bar. 

I was able to verify that an upload with wifi toggle does reset to the beginning:
[UploadWifiOnOffVerificationLogs.txt](https://github.com/aws-amplify/aws-sdk-ios/files/3532233/UploadWifiOnOffVerificationLogs.txt)

and it should affect mutlipart uploads as well. I could not reproduce this with the downloads which means the downloads may not reset to the beginning and continue where it left off

Since I was able to verify this, I'll send out a PR with the proposed change.

**Comment by jeffjvick** [comment]
Thanks @lawmicha for taking this on.  You can see my suggested changes in the description if that is helpful in your PR.

**Comment by palpatim** [comment]
We released this in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0

Please let us know if you have any problems with this.

**Comment by jeffjvick** [comment]
Thanks @palpatim, I will try this out this evening.

**Comment by jeffjvick** [comment]
@lawmicha @palpatim 
Hi, I tested 2.11.0 and confirmed that your PR behaves in the same manner as the changes I suggested.  Thanks for integrating this into the project.
