### ISSUE TITLE
isSignedIn returns false after sign-up

### ISSUE THREAD

**Issue by julio-rivera** [aws-amplify/aws-sdk-ios#1515]
**Describe the bug**
Hi, after instantiating a `AWSCognitoIdentityUserPool` object and successfully signing up a user, 'currentUser()?.isSignedIn' is equal to false. I would assume after signing up a user, this returns true. I wrote a lambda function to auto-confirm the user at sign-up.

The first screen someone is presented with I call getDetails to kick off the protocol method to see if a user is signed in.

If I'm doing this wrong, what flag should I be checking if a user is authenticated?

Thank you!

**Environment(please complete the following information):**
- AWSCognito 2.9.7 
- AWSCognitoIdentityProvider 2.9.7 
 - Dependency Manager: Cocoapods

**Device Information (please complete the following information):**
 - Device: iPhone XR Simulator
 - iOS Version: 12.2

**Comment by eanntuan** [comment]
I'm having the same issue! Is there an update on this?

**Comment by royjit** [comment]
Hi, Thank you for reporting this issue. Could you please provide us the steps you  performed. Did you call `getSession` on the user?
