### ISSUE TITLE
AWSServiceConfiguration returning invalid credentials

### ISSUE THREAD

**Issue by allanweir** [aws-amplify/aws-sdk-ios#1521]
**Describe the bug**
When creating services like Lambda, using **AWSMobileClient.sharedInstance()** as credentialsProvider in AWSServiceConfiguration leads to no methods being executed with no debug logs produced. When building a configuration like **AWSCognitoCredentialsProvider(regionType: .EUWest1, identityPoolId: "[POOL ID]", identityProviderManager: AWSMobileClient.sharedInstance())** the service needs recreating on login. It works when the app is restarted without recreating, however after waiting a few hours Lambda returns a UnrecognizedClientException requiring a signout and signin. AWSMobileClient meanwhile has the correct identityId and returns true for isSignedIn

**Update:**
Using the default invoker like **AWSLambdaInvoker.default().invoke()** also leads to no function being executed and no logs being produced. Callbacks aren't fired.

**To Reproduce**
1. Create service configuration using **AWSCognitoCredentialsProvider(regionType: .EUWest1, identityPoolId: "[POOL ID]", identityProviderManager: AWSMobileClient.sharedInstance())** and
**AWSLambdaInvoker.register(with: serviceConfiguration, forKey: "custom")**
2. Log in with **AWSMobileClient.sharedInstance().signIn(username:password:)**
3. Execute a lambda function
3. Wrong role is associated, still maintains unauth role

OR
1. Create service configuration using **AWSCognitoCredentialsProvider(regionType: .EUWest1, identityPoolId: "[POOL ID]", identityProviderManager: AWSMobileClient.sharedInstance())** and
**AWSLambdaInvoker.register(with: serviceConfiguration, forKey: "custom")**
2. Log in with **AWSMobileClient.sharedInstance().signIn(username:password:)**
3. Recreate AWSLambdaInvoker using same details
4. Execute a lambda function
5. Works ok UNTIL..

1. Re-open terminated app after enough time for tokens to expire
2. Create service configuration using **AWSCognitoCredentialsProvider(regionType: .EUWest1, identityPoolId: "[POOL ID]", identityProviderManager: AWSMobileClient.sharedInstance())** and
**AWSLambdaInvoker.register(with: serviceConfiguration, forKey: "custom")**
3. Execute lambda function
4. Error returned is **UnrecognizedClientException**

**Which AWS service(s) are affected?**
AWSMobileClient
AWSCognito
Lambda

**Expected behavior**
Using **AWSMobileClient.sharedInstance()** as credentialsProvider means services always have the correct token.
Using any other credentialsProvider provides a refreshed token following app inactivity, able to execute lambda functions

**Environment(please complete the following information):**
 - SDK Version: 2.9.7
 - Dependency Manager: Carthage
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 8 Simulator (12.2)
 - Device: iPhone X actual device (12.2)

**Additional context**
All sign in and signup is handled with AWSMobileClient following upgrade from 2.6.x.
App is running on a clean install. It has been deleted and reinstalled.
Elsewhere in the app, the only other related methods used are
AWSCognitoUserPoolsSignInProvider.sharedInstance().isLoggedIn() and AWSFacebookSignInProvider.sharedInstance().isLoggedIn to determine the type of login for the user, and which account view to show

awsconfiguration.json:
`{
  "IdentityManager": {
      "Default": {}
  },
  "Cognito": {
      "Default": {
          "Region": "eu-west-1"
      }
  },
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "[POOL ID]",
        "Region": "eu-west-1"
      }
    }
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "[POOL ID]",
      "AppClientId": "[CLIENT ID]",
      "AppClientSecret": "[SECRET]",
      "Region": "eu-west-1"
    }
  },
  "S3TransferUtility": {
    "Default": {
      "Bucket": "[BUCKET]",
      "Region": "eu-west-1"
    }
  },
  "FacebookSignIn": {
      "AppId": "[APP ID]",
      "Permissions": "public_profile"
  },
  "LambdaInvoker": {
      "Default": {
          "Region": "eu-west-1"
      }
  }
}`

**Comment by allanweir** [comment]
After a bit more testing I think I've found the problem, it seems like when switching from 2.6.x to 2.9.7 that some of the old way of doing things might have changed.

I was manually creating AWSServiceConfiguration for Pinpoint, Lambda and S3 and when I do this it leads to inconsistent results or errors. For places where I need to have a custom service configuration because of timeout or retry values I am now using the default service config as a base like
**let serviceConfiguration = AWSLambda.default().configuration.copy() as? AWSServiceConfiguration**
and this seems to be working ok. 

Can anyone confirm if this is the best way to go about things? I can rename the ticket and update the details once I know if it's a bug/feature/upgrade issue.

**Comment by royjit** [comment]
Hi @allanweir If you have initialized AWSMobileClient, the credential provider should be created for you by default. And you can go with default configuration like you did to modify timeout and retries.

Please let us know if you face any other issue with the SDK.
