### ISSUE TITLE
Unable to signIn using email 

### ISSUE THREAD

**Issue by Nookaraju** [aws-amplify/aws-sdk-ios#1532]
**Describe the bug**
We have integrated all required sdk to our project and able to use all method of AWSMobileClient like signUp and confirmation and all. But when we try signIn method by providing email and password it fails with error "notAuthorized". We already configured our user pool to able to login using email.

I checked with aws support and nothing wrong with the pool configuration and found singIn working fine from web client.

**To Reproduce**
1.  Configure pool with signIn Option "Email address or phone number - Users can use an email address or phone number as their "username" to sign up and sign in."
2. SignUp and confirmSignUp from mobile SDK
3.  try AWSMobileClient.sharedInstance().signIn method with registered email.
4.  It returns Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=20 "(null)" UserInfo={__type=NotAuthorizedException, message=Incorrect username or password.}

Congito user pool SignIn

**Expected behavior**
Its should allow to login using email

**Environment(please complete the following information):**
 - SDK Version:  2.9.7
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: All(Simulator/Device)
 - iOS Version: iOS 12.0

**Additional context**

**Comment by palpatim** [comment]
@Nookaraju 

Could you confirm that the client is fully initialized (that is, you've received the appropriate status callback) before attempting the sign in?

Do the steps you describe happen during the same session--that is, your user signs up, confirms, and attempts to sign in all during the same app session?

**Comment by Nookaraju** [comment]
Yes AWSMobileClient initialised in AppDelegate.
        AWSMobileClient.sharedInstance().initialize { (userState, error) in
        }

And the user state gives me "signedOut".

I tried signIn on the same session after signUp and signUp confirmation. Also tried SignIn In next launch but same result.

**Comment by Nookaraju** [comment]
@palpatim Do you have suggestions/inputs?

**Comment by jamesatfish** [comment]
@Nookaraju @palpatim I just raised a similar issue - #1575. We are seeing the same notAuthorized error, we also use email address as the username for signup.

**Comment by royjit** [comment]
Hi @Nookaraju Can you provide more information about your use case so that we can try to reproduce the same behavior? It be great if you can share some code sample on how you are invoking the api. Also, could you share your Cognito settings.
