### ISSUE TITLE
How to update  a row in the table using amplify in aws dynamodb in ios?

### ISSUE THREAD

**Issue by ramakrishna013** [aws-amplify/aws-sdk-ios#1536]
Hi, i'm using amplify frame work to create a db and tables in that. I'm able to add data to the table and also able to get that data. Now i want to update a row in that table. How can i do that?

**Comment by palpatim** [comment]
@ramakrishna013 

The best practice is to front your DynamoDB instance with API Gateway or AppSync--direct database access from a client app is nearly always a bad idea. Services like those I mention can help you abstract your data store CRUD operations into self-contained, authorizable, validatable API calls, as well as provide a host of other functionality to help your app stay secure, manageable, and scalable.

Please see our docs for the [Amplify API category](https://aws-amplify.github.io/docs/ios/api) for more information.

That said, the DynamoDB `PutItem` ([Docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html) | [iOS API](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/Classes/AWSDynamoDBPut.html)) or `UpdateItem` ([Docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) | [iOS API](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/Classes/AWSDynamoDBUpdate.html)) calls will write to existing objects to DynamoDB.
