### ISSUE TITLE
AWSMobileClient error 8

### ISSUE THREAD

**Issue by gggal123** [aws-amplify/aws-sdk-ios#1538]
I actually don't know if it is a bug or a useful question. 
I couldn't find a solution to this anywhere so I'm asking here.
I'm using AWSMobileClient on iOS and Amplify.
I followed the docs, added federated signIn with Google and Facebook (which seems to work fine, I get UserState: signedIn from `AWSMobileClient.sharedInstance().initialize`)
Than I signed out and tries to perform a sign up using:

```
AWSMobileClient.sharedInstance().signUp(username: email, password: password, userAttributes: ["email": email, "phone_number": phoneNumber]) { (signUpResult, error) in
            if let signUpResult = signUpResult {
                switch(signUpResult.signUpConfirmationState) {
                case .confirmed:
                    print("User is signed up and confirmed.")
                case .unconfirmed:
                    print("User is not confirmed and needs verification via \(signUpResult.codeDeliveryDetails!.deliveryMedium) sent at \(signUpResult.codeDeliveryDetails!.destination!)")
                case .unknown:
                    print("Unexpected case")
                }
            } else if let error = error {
                if let error = error as? AWSMobileClientError {
                    switch(error) {
                    case .usernameExists(let message):
                        print(message)
                    default:
                        break
                    }
                }
                print("AWS WAS FUCKING ERRORED: \(error.localizedDescription)")
            }
        }
```

As written in the docs on Amplify. But I got the errors:

> Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x281789220, domain=1, instance=1>

and 

> The operation couldn’t be completed. (AWSMobileClient.AWSMobileClientError error 8.)

I followed the docs carefully and added an updated awsconfiguration.json file (without copy files if needed option), but still, nothing works and the error doesn't really help me understand what to do.

**Which AWS service(s) are affected?**
Auth
**Expected behavior**
I expect the framework to perform the signUp successfully. 

**Environment(please complete the following information):**
 - SDK Version: 2.9.7
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0.1

**Device Information (please complete the following information):**
 - Device: iPhone 7
 - iOS Version: 12.1.4

Thanks.

**Comment by palpatim** [comment]
@gggal123 

The "Signal strength query returned error" messages are innocuous and [can be ignored](https://stackoverflow.com/questions/53526194/how-to-troubleshoot-resolve-signal-strength-query-returned-error-logs-that-are).

The real issue appears to be the "AWSMobileClient.AWSMobileClientError error 8", which resolves to an `invalidParameter`. In your code above, you catch and print the error only in the case of a `usernameExists` error. What message do you see if you print for any error?

```swift
if let error = error as? AWSMobileClientError {
    let printableMessage: String
    switch error {
    case .aliasExists(let message): printableMessage = message
    case .codeDeliveryFailure(let message): printableMessage = message
    case .codeMismatch(let message): printableMessage = message
    case .expiredCode(let message): printableMessage = message
    case .groupExists(let message): printableMessage = message
    case .internalError(let message): printableMessage = message
    case .invalidLambdaResponse(let message): printableMessage = message
    case .invalidOAuthFlow(let message): printableMessage = message
    case .invalidParameter(let message): printableMessage = message
    case .invalidPassword(let message): printableMessage = message
    case .invalidUserPoolConfiguration(let message): printableMessage = message
    case .limitExceeded(let message): printableMessage = message
    case .mfaMethodNotFound(let message): printableMessage = message
    case .notAuthorized(let message): printableMessage = message
    case .passwordResetRequired(let message): printableMessage = message
    case .resourceNotFound(let message): printableMessage = message
    case .scopeDoesNotExist(let message): printableMessage = message
    case .softwareTokenMFANotFound(let message): printableMessage = message
    case .tooManyFailedAttempts(let message): printableMessage = message
    case .tooManyRequests(let message): printableMessage = message
    case .unexpectedLambda(let message): printableMessage = message
    case .userLambdaValidation(let message): printableMessage = message
    case .userNotConfirmed(let message): printableMessage = message
    case .userNotFound(let message): printableMessage = message
    case .usernameExists(let message): printableMessage = message
    case .unknown(let message): printableMessage = message
    case .notSignedIn(let message): printableMessage = message
    case .identityIdUnavailable(let message): printableMessage = message
    case .guestAccessNotAllowed(let message): printableMessage = message
    case .federationProviderExists(let message): printableMessage = message
    case .cognitoIdentityPoolNotConfigured(let message): printableMessage = message
    case .unableToSignIn(let message): printableMessage = message
    case .invalidState(let message): printableMessage = message
    case .userPoolNotConfigured(let message): printableMessage = message
    case .userCancelledSignIn(let message): printableMessage = message
    case .badRequest(let message): printableMessage = message
    case .expiredRefreshToken(let message): printableMessage = message
    case .errorLoadingPage(let message): printableMessage = message
    case .securityFailed(let message): printableMessage = message
    case .idTokenNotIssued(let message): printableMessage = message
    case .idTokenAndAcceessTokenNotIssued(let message): printableMessage = message
    case .invalidConfiguration(let message): printableMessage = message
    case .deviceNotRemembered(let message): printableMessage = message
    }
    print("error: \(error); message: \(printableMessage)")
}
```

To cut to the chase: if you are seeing an `invalidParameter`, I'd expect you to see the message: 
> For using developer authenticated identities, you need to specify the `CognitoIdentityId` in `FederatedSignInOptions`.

 since the only place we return an `invalidParameter` error is during federated identity sign in: https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift#L312

It's a bit surprising to me that you'd be seeing this during signUp, however, which is why it would be useful to validate that you're seeing the "error 8" inside of the signUp result handler.

**Comment by willrust** [comment]
Would it be bad practice to include the original error as a property of AWSMobileClientError? It appears to be passed to ErrorMappingHelper but is left off of the AWSMobileClientError enum.
This would allow us to dig into the errors a little more for ourselves. And, would be really useful when our own auth triggered lambdas throw errors for any custom validations.

**Comment by gggal123** [comment]
@palpatim 
Well your answer helped me a lot!
I used AWS Amplify documentation and in there, they only catch `usernameExists`, so I had no idea which other errors can I catch...
Anyway, the problem that was caught, is `InvalidParameter` Error.
`error: invalidParameter(message: "Invalid phone number format."); message: Invalid phone number format.`
And it indeed occurred inside `SignUp`.

Thank you very much for your help, an also, is there a place which errors that can occur during any process using AWSMobileClient are documented in? If you could refer here for other people to use it would be great!

Have a great day and again, **Thanks**!

**Comment by velociraptor111** [comment]
I agree, I feel like the documentation isn't as complete as I thought it would be.

**Comment by mdadithasan** [comment]
the documentation is really bad. I am getting the following error while i sign up

"The operation couldn’t be completed. (AWSMobileClient.AWSMobileClientError error 33.)"

**Comment by ENRAG3DCHICKEN** [comment]
Solution is to use Firebase (j/k not j/k)
