### ISSUE TITLE
AWSAPIGateway auto generated SDK response model is empty.

### ISSUE THREAD

**Issue by manomuthu-optisol** [aws-amplify/aws-sdk-ios#1544]
While we are trying to create a Auto generated SDK for iOS (swift). Am receiving empty model in that. Kindly suggest how can we do that.

Thanks in advance.

**Model look like below:**

```
import Foundation
import AWSCore


@objcMembers
public class *********ArrayOfViewLoopResponse : AWSModel {
    
    
}
```

**AWS Model:**

```
{
  "type" : "array",
  "items" : {
      "type": "object",
      "properties": {
          "intxType": {"type": "string"},
          "intx": {
            "type" : "array",
            "items" : {"$ref":"https://apigateway.amazonaws.com/restapis/********/models/ViewInteractionResponse"}
          }
      }
  }
}
```

**Our Array will look something like below**

```
[
    {
        "intxType" : "FIRST Event"
        "intx" : [{
            "id": "00000",
            "tenantId": "0000",
            },
            {
            "id": "00000",
            "tenantId": "00000",
            }
        ]
    },
    {
        "intxType" : "SEC Event"
        "intx" : [{
            "id": "00000",
            "tenantId": "0000",
            },
            {
            "id": "00000",
            "tenantId": "00000",
            }
        ]
    }
    
]
```

**Comment by thuanngo1990** [comment]
I got the same issue. 

"Fatal error: NSArray element failed to match the Swift Array Element type". 
 - Here's my model : 

@objcMembers
public class AWSRegistry: AWSModel{
    var a : String?
    var b  : String?
    var c : String?
    var d : String?
    
    public override static func jsonKeyPathsByPropertyKey() -> [AnyHashable : Any]!{
        var params:[AnyHashable : Any] = [:]
        
        params["a"] = "a"
        params["b"] = "b"
        params["c"] = "c"
        params["d"] = "d"
   
        return params
    }
} 
 
 - Calling : 
    if let result = task.result {  
             let registryList = result as! [AWSRegistry]
             let testValue = registryList[0]            // Crashing at here.  
    }

Anybody can help me?

**Comment by rohandubal** [comment]
Hello @manomuthu-optisol 

It looks like you are trying to use nested arrays in your API. Nested arrays are currently not supported by the code generator for API Gateway for iOS (ObjC and Swift)

I will take this as a feature request to the team.

Best,
Rohan

**Comment by rohandubal** [comment]
Hello @thuanngo1990 

Your issue looks like something different from @manomuthu-optisol 

I would recommend opening a new issue for it. 

How are you generating your AWSModel? Is it hand written? Based on the code snippet, it looks like the `registryList` is coming as an empty array which is causing the crash. Can you please check if thats the case?

Thanks,
Rohan

**Comment by manomuthu-optisol** [comment]
@rohandubal Thanks for the info.

Is there any work around to implement that in front-end? If any please let me know.

Thanks,
Muthu

**Comment by thuanngo1990** [comment]
@rohandubal . Thank you for your infor. I will check it :). 

Thanks, 
QT.
