### ISSUE TITLE
How to get an existing table data into my project created with amplify framework?

### ISSUE THREAD

**Issue by ramakrishna013** [aws-amplify/aws-sdk-ios#1545]
Hi, I have some existing tables created in my `dynamodb` and I want to get those tables data. how can I get those tables data with amplify framework?

**Comment by rohandubal** [comment]
Hello @ramakrishna013 

I will need some more information to answer this question. 

What is the use-case you are trying to achieve?
- Is it accessing the dynamodb data via a GraphQL API?
- Is it accessing the dynamodb data directly?
- Do you want to move the dynamodb data to some different place?

Thanks,
Rohan

**Comment by ramakrishna013** [comment]
@rohandubal In my case, our web developers created some tables for my project in Dynamodb. So, I have to access those in my app to show the data.

1. Do you want to move the `Dynamodb` data to some different place?
   : - In my case, I don't have to move to a different place.

2. Is it accessing the `Dynamodb` data via a GraphQL API?
   :- In my case, I set up my project using `amplify cli` and I've set the API type as `graphql`. So, Yes it accessing the `Dynamodb` using `graphql`.

3. Is it accessing the `Dynamodb` data directly?
    :- Yes I want to access the Dynamdb directly.

**Comment by rohandubal** [comment]
Hello @ramakrishna013 

Since you have a graphql API setup already, I would recommend using that API to retrieve the data from dynamodb table. 

Could you please follow the [docs here](https://aws-amplify.github.io/docs/ios/api#code-generation) to setup the graphql API in your app and consume it?

Thanks,
Rohan

**Comment by ramakrishna013** [comment]
@rohandubal That process is useful when I created the Dynamodb table using the amplify and the amplify generate the Graphql code(schema, mutations, queries, etc.) to do operations on the table. In my case, I've created a table without Amplify. I've directly login to AWS console and in the Dynamodb create a table like `UserData`. how can I access that `UserData` table?

**Comment by palpatim** [comment]
@ramakrishna013 You can import a DDB table as a GraphQL schema by following [these instructions](https://docs.aws.amazon.com/appsync/latest/devguide/import-dynamodb.html), then you can regenerate your API to access the new resource in your client code.
