### ISSUE TITLE
Overriding keychain of AWSMobileClient to change accessibility level

### ISSUE THREAD

**Issue by martsie** [aws-amplify/aws-sdk-ios#1546]
**State your question**
We’re dealing with sensitive data and would like to be able to change the AWSMobileClient to lock the keychain for our cognito behind a user’s touch id / face-id before unlocking (and also prevent the keychain from being shared in iCloud).

AWSMobileClient instantiates a `AWSUICKeyChainStore` that uses the accessibility `AWSUICKeyChainStoreAccessibilityAfterFirstUnlock` specified in the default `commonInit` method in `AWSUICKeyChainStore`.

I haven’t found a way to intercept, overload or override AWSMobileClient to change the keychain accessibility. If AWSMobileClient was an open class we’d be able to do everything we need to however it’s currently a public class.

Does anybody have any suggestions on how we can implement biometric / passcode security confirmation from a user before logging them into our AWS service without rewriting the AWSMobileClient class?

**Which AWS Services are you utilizing?**
Appsync, AWSMobileClient

**Environment(please complete the following information):**
 - SDK Version: 2.1
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 12.2

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by rohandubal** [comment]
Hello @martsie 

Thanks for the detailed description. I will take this as a feature request to the team and loop back if we need more information from you. Will keep this thread updated.

Thanks,
Rohan

**Comment by martsie** [comment]
Great, thanks Rohan.

A token storage API similar to the one for amplify js over at https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens would be ideal.

**Comment by crspybits** [comment]
In my use case, our app has to run in the background and I want to make sure the KeyChain item setting works with that.

**Comment by atierian** [comment]
Thanks for opening this feature request. We don't plan on supporting the ability to change keychain accessibility levels, however we use `*ThisDeviceOnly` by default as of [v2.30.1](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.30.1).
