### ISSUE TITLE
AWSIoT unsubscribe from topic isn't working

### ISSUE THREAD

**Issue by baljakbratislav** [aws-amplify/aws-sdk-ios#1547]
**Describe the bug**
- (void)unsubscribeTopic:(NSString *)topic;
method isn't working at all. 
When I change subscription to a new topic. But previously I have called unsubscribeTopic. I will receive events from both topics!

**To Reproduce**
Subscribe to "AA" topic.
Unsubscribe to "AA" topic.
Subscribe to "BB" topic.

**Current behavior**
Receiving events from both topics: from "AA" and "BB"

**Expected behavior**
Receiving events only from last topic: from "BB"

**Environment(please complete the following information):**
 - "AWSIoT", "2.9.3"
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: all iPhones
 - iOS Version: all iOS versions

**Comment by rohandubal** [comment]
Hello @baljakbratislav 

Could you please give the code snippet you are using to initialize the IoT client and make the subscribe call? That will help us identify the issue and reproduce it on our side.

Thanks,
Rohan

**Comment by baljakbratislav** [comment]
Of course I can:

**This is code for initialization**
`if let socketProtocol = socket?.socketProtocol, let host = socket?.host, let identityPoolId = socket?.identityPoolId {
            let endpoint = socketProtocol + "://" + host
            let iotEndPoint = AWSEndpoint(urlString: endpoint)
            let credentialProvider = AWSCognitoCredentialsProvider(regionType: .EUWest1, identityPoolId: identityPoolId)
            let configuration = AWSServiceConfiguration(region: .EUWest1, endpoint: iotEndPoint, credentialsProvider: credentialProvider)

            if let config = configuration {
                AWSIoTDataManager.register(with: config, forKey: "EUWest1IoTDataManager")
                AWSServiceManager.default()?.defaultServiceConfiguration = configuration
                let iotDataManager = AWSIoTDataManager.init(forKey: "EUWest1IoTDataManager")
                return iotDataManager
            }
        }`

**This is for connection**
`iotDataManager?.connectUsingWebSocket(withClientId: UUID().uuidString, cleanSession: true) { [weak self] (status) in`

**And last but not the least: for subscription**
`iotDataManager?.subscribe(toTopic: "topic", qoS: .messageDeliveryAttemptedAtLeastOnce) { [weak self] (message) in`

If you have any more questions, feel free to ping me. @rohandubal
