### ISSUE TITLE
Incorrect identityID between sessions

### ISSUE THREAD

**Issue by allanweir** [aws-amplify/aws-sdk-ios#1548]
**Describe the bug**
In the app I am using AWSMobileClient to handle user sessions, generally this works fine. Occasionally after a day or more, when the app is re-opened AWSMobileClient gives a userState of 'signedIn' and 'isSignedIn' is true but the identityID property is incorrect for the user which is logged in. The ID seems to become an unauth identity, rather than the Cognito User Pool one (email based). This becomes apparent when a 403 error is returned from Lambda because the requesting role is unauth, despite AWSMobileClient saying it is logged in.

**To Reproduce**
1. Login using AWSMobileClient.sharedInstance().signIn(username:password:)
2. Use the app as normal (Pinpoint, Lambda, S3)
3. Return to the app 24 hours later
4. Try to access a lambda function restricted to auth role
5. Receive 403 error
6a. I can see that calls to pinpoint.eu-west-1.amazonaws.com contain the unauth ID
6b. I can see calls to lambda contain the unauth ID
6c. I can see calls to https://cognito-idp.eu-west-1.amazonaws.com/ contain the correct Auth ID and return UserAttributes of the auth user

**Which AWS service(s) are affected?**
Cognito, Lambda

**Expected behavior**
The user should remain signed in between session, the userState reflects this as it currently does, and the identityID remains consistent between sessions. Or, at the least the framework notifies the app of the state 'signedOutUserPoolsTokenInvalid'.

**Environment(please complete the following information):**
 - SDK Version: 2.9.7
 - Dependency Manager: Carthage
 - Swift Version : 5.0

**Device Information (please complete the following information):**
- Device: iPhone 8 Simulator (12.2)
- Device: iPhone 8 actual device (12.1.4)
- Device: iPhone X actual device (12.2)

**Additional Context**
_Pinpoint initialisation:_
`self.pinpoint = AWSPinpoint(configuration: AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions))`
_awsconfiguration.json_
```
"PinpointTargeting": {
      "Default": {
          "AppId": "[APP ID]",
          "Region": "eu-west-1"
      }
  },
  "PinpointAnalytics": {
      "Default": {
          "AppId": "[APP ID]",
          "Region": "eu-west-1"
      }
  }
```

_Lambda initialisation:_
```
let serviceConfiguration = AWSLambda.default().configuration.copy() as? AWSServiceConfiguration ?? AWSLambda.default().configuration// AWSAuthService.shared.createDefaultAWSServiceConfiguration()
        serviceConfiguration.maxRetryCount = 5
        serviceConfiguration.allowsCellularAccess = true
        serviceConfiguration.timeoutIntervalForRequest = 30
        serviceConfiguration.timeoutIntervalForResource = 30
        
        AWSLambdaInvoker.register(with: serviceConfiguration, forKey: APIClient.invokerName)
```

_awsconfiguration.json_
```
"Lambda": {
      "Default": {
          "Region": "eu-west-1"
      }
  },
```

During normal usage, both services work fine and switch between auth and unauth states

**Comment by rohandubal** [comment]
Hello @allanweir 

I think the issue here is the initialization order. While registering the clients using `register` method, I would recommend using `AWSMobileClient.sharedInstance()` as the credentials provider. When the app is launched, the first step should be to initialize the `AWSMobileClient`. It will ensure that `AWSMobileClient` becomes the default credentials provider for other clients.

Thanks
Rohan

**Comment by allanweir** [comment]
Hey,

I had a different issue when manually setting the credentials provider in the past https://github.com/aws-amplify/aws-sdk-ios/issues/1521 - it seemed like letting the libraries automatically create the service configuration was working but now it's having issues after the session expires

**Comment by allanweir** [comment]
I've just had my app running on the simulator whilst I've been out, so about an hour and when I've come back the calls to lambda are no longer working. It is still sending a token which has the auth role but it seems like it's expired as lambda is returning a 403. The function it's calling is setup to work with both the auth and unauth roles. This is after changing the lambda registration to work from `let serviceConfiguration = AWSServiceConfiguration(region: .EUWest1, credentialsProvider: AWSMobileClient.sharedInstance())!`

**Comment by afriedmanGlacier** [comment]
We are not using AWSMobileClient, but we are having a similar issue where there are issues after the session expires such that we need to explicitly log out and then back in for it to work.

**Comment by Foefirelord** [comment]
Related question: how does the way OP sets up Lambda service config differ from this?

```
let lambdaCredentialsProvider = AWSMobileClient.sharedInstance().getCredentialsProvider()

        let lambdaConfiguration = AWSServiceConfiguration(
            region: CognitoIdentityUserPoolRegion,
            credentialsProvider: lambdaCredentialsProvider)

        AWSServiceManager.default().defaultServiceConfiguration = lambdaConfiguration
```
Are both ways of configuring it equally viable?

**Comment by dokutoshi** [comment]
Is AWS using dispatch_group in GCD to manage the async tasks?  Otherwise race conditions will lead to spurious events, e.g. identityId changing and the underlying accessToken and idToken.  This can lead to weird failures.

**Comment by royjit** [comment]
We made few bug fixes related to identityId in the last iOS release of the SDK,  https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0. Could you please check if the issue still exists with the updated SDK.

Please let us know if you have any problems with this.

**Comment by F9** [comment]
This issues is not fixed. Please re-open. I'm in the same condition.

**Comment by YZ-Inspify** [comment]
I'm experiencing the same issue intermittently, although I'm not using Lambda in my iOS code base. 
Question - at what point in time can we know the correct identityId will be returned when invoking `AWSMobileClient.default().identityId`?

**Comment by YZ-Inspify** [comment]
I'm having the same problem, although it's intermittently. It seems when the rest of the code is going to make use of identityId of current user, the identityId is incorrect, i.e. no longer the same identityId that user is associated to.

Question - at what point in time can we rely on the correctness of identityId when invoking `AWSMobileClient.default().identityId`?

Thanks.

**Comment by royjit** [comment]
We made a lot of changes to fix threading issue that was present in AWSMobileClient, since there is low traffic in this issue we are closing this. Feel free to report us if you are still facing any issue with AWSMobileClient.
