### ISSUE TITLE
Random Crashes in AWSSRWebSocket

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/aws-sdk-ios#1551]
**Describe the bug**
We have an iOS application supported by AWS AppSync. Recently we have started noticing random AWSSRWebSocket errors leading to app crashes for selected users and we are not able to reproduce it intentionally.

**To Reproduce**
Random crashes, unable to reproduce (~probably threading issues)

**Which AWS service(s) are affected?**
AWS AppSync

**Expected behavior**
Application should not crash

**Screenshots**
<img width="1031" alt="Screen Shot 2019-05-16 at 7 20 24 AM" src="https://user-images.githubusercontent.com/16943885/57861261-1bbd1400-77ab-11e9-83de-00ad5c0dcec5.png">

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29] AWSMobileClient ~ 2.9.8 & AWSAppSync ~ 2.13.0
 - Dependency Manager: [e.g. Cocoapods, Carthage] Cocoapods
 - Swift Version : [e.g. 4.0] 5.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] iPhone 6S
 - iOS Version: [e.g. iOS 11.4] 12.2
 - Specific to simulators: None

**Additional context**
We have lot of subscription watcher objects in memory (Class level objects) and we don't remove/unsubscribe them for the entire lifecycle. The class itself is static. Basically any data that UI retrieves from Server, we create subscriptionWatcher to wait for any add/update/delete events. Is this the best practice? Not sure if this is causing these issues.

**Comment by royjit** [comment]
Hi @rohit3d2003 

Apologies for the delayed response. `AWSSRWebSocket` is removed as part of the latest iOS SDK for AppSync. Release notes - https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.0.0
