### ISSUE TITLE
AWS Task invokeHTTPRequest send imagedata as body. 

### ISSUE THREAD

**Issue by thuanngo1990** [aws-amplify/aws-sdk-ios#1557]
Hi everyone,

On IOS (swift 4.2). I'm using AWSAPIGatewayClient to connect the AWS server with "invokeHTTPRequest" method. 

How can I put ImageData as Body parameter? 

Note: I can do that on Android with ByteArray. 

Thanks,
QT.

**Comment by rohandubal** [comment]
Hello @thuanngo1990 

Have you tried passing the image contents as `Data` object to the HTTP body parameter?

Thanks
Rohan

**Comment by thuanngo1990** [comment]
Yes @rohandubal . Do you have any ideas for that? 
Thank you :)

**Comment by palpatim** [comment]
@thuanngo1990 As you point out API Gateway should [support binary data natively](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html). Can you provide:

- A code snippet of the API call
- A sample of your API setup where you specify the content type of the binary data
- Any errors you receive
- The SDK version you're using
