### ISSUE TITLE
AWSS3TransferUtilityDownloadTask retains completionBlock after download finish

### ISSUE THREAD

**Issue by trzeciak** [aws-amplify/aws-sdk-ios#1565]
**State your question**
Why AWSS3TransferUtilityDownloadTask retains completionBlock (and progressBlock) after download finish?

**Which AWS Services are you utilizing?**
AWSS3 + AWSCore

**Environment(please complete the following information):**
 - SDK Version: 2.9.7
 - Dependency Manager: Cocoapods
 (- ObjC)

**Device Information (please complete the following information):**
 - Device: Simulator, probably doesn't matter
 - iOS Version: 12+

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@trzeciak Thank you for reporting to us. The completion block and progress block could be freed upon successful completion of a transfer. I will tag this as a feature request and add it to our backlog.

**Comment by royjit** [comment]
This was fixed as part of this PR - https://github.com/aws-amplify/aws-sdk-ios/pull/3833
