### ISSUE TITLE
API Gateway calls with Cognito authentication not working properly

### ISSUE THREAD

**Issue by miguelbanda** [aws-amplify/aws-sdk-ios#1568]
**API Gateway calls with Cognito authentication not working properly**
I was working with Cognito(SignUp, SignIn, Forgot Password, etc.) and everything works fine, until I got a problem calling my API Gateway, sometimes it works and insert the data into my Dynamo DB, but other times it shows this error message:

```
Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}
```

I was following [this tutorial](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk-ios-swift.html), download the SDK for Swift(iOS) and get this code to call the API Gateway : 

```
if AWSMobileClient.sharedInstance().currentUserState == .signedIn {
        let client = MYAPPClient.client(forKey: "MYAPP")
        
        let body = MYAPPUser()
        body?.email = "test@test.com"
        
        client.usersPost(body: body!).continueWith { (task) -> Any? in
            if let error = task.error {
                print("ERROR: ", error)
            } else if let result = task.result {
                print(result)
            }
            return nil
        }
}
``` 

And setting this configuration on the AppDelegate file:
```
let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast1,
                                                                identityPoolId: "us-east-1:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX")
        let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        JOULECLIENTProdjouleappapiClient.registerClient(withConfiguration: configuration!, forKey: "MYAPP")
```

I want to know if I'm missing something or if  it is a bug in the API, hope you can help me.

**Which AWS Services are you utilizing?**
Cognito and API Gateway

**Provide code snippets**
This is my awsconfiguration.json file
```
{
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-1_XXXXXXXXX",
            "AppClientId": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
            "Region": "us-east-1"
        }
    }
}
```

**Environment:**
 - SDK Version: 2.9
 - Dependency Manager: Cocoapods
 - Swift Version: 4.2

**Device Information:**
 - Device: Simulator
 - iOS Version: 12.0
 - Specific to simulators: Only tested on simulator

**Comment by kvasukib** [comment]
@miguelbanda Sorry for the inconvenience caused. Is the Cognito Identity pool used in `CredentialsProvider` section in `awsconfiguration.json` file the same as the Cognito Identity Pool used in the constructor of `AWSCognitoCredentialsProvider`?

Have you enabled `Unauthenticated access to Identity pool` in the Amazon Cognito Identity Pools console?

**Comment by miguelbanda** [comment]
Yes they are the same Cognito Identity Pool ID in both places.

No, the access for the Cognito Identity Pool is only for Authenticated users via Cognito User Pools

**Comment by kvasukib** [comment]
If you only need to allow "Authenticated users via Cognito User Pools" in your Cognito Identity Pool, you need to have a valid Id Token from Cognito User Pools and federate this token into the Cognito Identity Pool and then retrieve credentials from Amazon Cognito which will be accepted by AWS API Gateway.

If you try to retrieve credentials without a valid Id Token being federated into Amazon Cognito Identity Pool, you will encounter the error:

```
Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}
```

**Comment by miguelbanda** [comment]
I'm using this method to Sign In my users: 
```
AWSMobileClient.sharedInstance().signIn(username: self.email, password: self.password) { (signInResult, error) in
            if let error = error  {
                    print(error.localizedDescription)
            } else if let signInResult = signInResult {
                switch (signInResult.signInState) {
                case .signedIn:
                    self.loadCompleteProfile()
                case .newPasswordRequired:
                    break
                case .passwordVerifier:
                    break
                default:
                    print("Sign In needs info which is not yet supported.")
                }
            }
        }
```

After this, how do I federate my tokens into my Identity Pool?

**Comment by kvasukib** [comment]
`AWSMobileClient` automatically federates the token retrieved from Cognito User Pools in the Cognito Identity pool configured through the `awsconfiguration.json` file. When you use `AWSMobileClient.sharedInstance()` as the credentials provider in your `AWSServiceConfiguration`, it should work.

```
let serviceConfiguration = AWSServiceConfiguration(region: AWSRegionType.USEast1,
              credentialsProvider: AWSMobileClient.sharedInstance())
```

See https://aws-amplify.github.io/docs/ios/api#iam-authorization for more details.

**Comment by miguelbanda** [comment]
I did some tests and it's working, thank you @kvasukib

**Comment by kvasukib** [comment]
@miguelbanda Thank you for the confirmation. Closing the issue.
