### ISSUE TITLE
Sometimes backgound tasks are not finished

### ISSUE THREAD

**Issue by Pumpkin-SweetPotato** [aws-amplify/aws-sdk-ios#1571]
**Describe the bug**
Sometimes download tasks of AWSS3TransferUtility are not finished when Application entered background, but sometimes succeeded 

**To Reproduce**
create multi download tasks about 70 and make App enter background

**Which AWS service(s) are affected?**
S3 Transferutility

**Expected behavior**

Always success background download tasks

**Screenshots**
tasks successfully completed
 <img width="388" alt="스크린샷 2019-05-24 오후 2 33 03" src="https://user-images.githubusercontent.com/23733661/58304978-6be24900-7e31-11e9-8632-59fa7cc469bd.png">

tasks being stopped and not start again when enter foreground
<img width="355" alt="스크린샷 2019-05-24 오후 2 33 30" src="https://user-images.githubusercontent.com/23733661/58304979-6be24900-7e31-11e9-9924-b287e71b834b.png">

completionhandler which appdelegate call when App entered background 
<img width="849" alt="스크린샷 2019-05-24 오후 2 35 48" src="https://user-images.githubusercontent.com/23733661/58304944-55d48880-7e31-11e9-9725-42020fb5b506.png"> 

**Environment(please complete the following information):**
 - SDK Version: AWSS3, AWSCore,  2.9.6
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**

**Comment by lawmicha** [comment]
Hi @Pumpkin-SweetPotato 

Thanks for reporting the issue, this looks the same as the issue that was reported here https://github.com/aws-amplify/aws-sdk-ios/issues/1513 . 

I believe when the app goes to the background, the transfer is on-going but does not report progress. When you bring the app back to the foreground after some time, you will see a single progress call with 100% and the completion handler called. To get the progress handler called again, please see this workaround:  https://github.com/aws-amplify/aws-sdk-ios/issues/1513#issuecomment-531407454

**Comment by lawmicha** [comment]
hi @Pumpkin-SweetPotato are you still seeing this issue with the latest SDK or were you able to test the workaround?
