### ISSUE TITLE
ScretsManager

### ISSUE THREAD

**Issue by cbm-mghebaji** [aws-amplify/aws-sdk-ios#1574]
Hello,

Do you provide ScretsManager support in the iOS sdk ?

**Comment by minbi** [comment]
Hi @cbm-mghebaji ,

We do not currently support [Secret Manager](https://aws.amazon.com/secrets-manager/)

Potential duplicate #1012

**Comment by cbm-mghebaji** [comment]
Hi @minbi 
Can i used the c++ sdk that have Secret Manager with an iOS application ? If not what solution do you advise to get keys from Secret Manager to iOS application ?

Thanks for help

**Comment by bartjacobs** [comment]
The AWS SDK for iOS doesn't have built-in support for AWS Secrets Manager at the time of writing. What is the recommended approach to use AWS Secrets Manager in an iOS client?

**Comment by jonathanarevalogaray** [comment]
Is this still not supported?

**Comment by atierian** [comment]
Thanks for opening this feature request. We are not adding new service clients to the AWS SDK for iOS at this time.
