### ISSUE TITLE
InitiateAuth returning notAuthorized Error for some users

### ISSUE THREAD

**Issue by jamesatfish** [aws-amplify/aws-sdk-ios#1575]
**Describe the bug**
A subset of our users are experiencing issues where the InitiateAuth function returns a notAuthorized error for their account, despite them entering the correct credentials.

**To Reproduce**
There appears to be no particular pattern to reproduce the issue, but we're seeing scenarios like:

1. User signs up for a new account via our mobile app, obtains the identity and refresh tokens and accesses our app.
2. User launches app over subsequent days, AWS SDK correctly retrieves the cached refresh token, obtains a new identity token, allows user to use app.
3. User launches app the next time, AWS SDK fails with notAuthorized error.  User is taken to the normal login screen (our app clears cached tokens & user identities at this point).  User attempts to login with correct credentials, continues to get notAuthorized error and is not able to use our app.

This issue does not appear to affect our Android users hence raising this as a potential bug in the iOS SDK.

**Which AWS service(s) are affected?**
Cognito Identity.

**Expected behavior**
We expected our users to continue to be able to login to our app using their correct Cognito credentials and/or cached identity and refresh tokens.

**Environment(please complete the following information):**
 - SDK Version: 2.9.8
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
Various iOS devices, almost all running iOS 12.

**Comment by minbi** [comment]
Hi @jamesatfish ,

Can you provide a code snippet so that we can investigate the code path you are using?

**Comment by jamesatfish** [comment]
@minbi certainly.

Upon app launch we are attempting to automatically login the user (against our database) using the identityToken returned from `AWSMobileClient.sharedInstance().getTokens`:

```
    func applicationDidBecomeActive(_ application: UIApplication) {
        
        ...
        
        AWSMobileClient.sharedInstance().initialize { (userState, error) in
            if let userState = userState {
                
                if userState == .signedIn {
                    
                    // perform database login with Cognito user credentials
                    APPXXXAPI.loginUser(success: { (userAccount) in
                        print("login API success")
                        print(userAccount)
                        
                        ...
                        
                    }, failure: { (error) in
                        print("login API error")
                        print(error)
                        
                        // The AWS SDK says we are signed in as a user, but the token provided doesn't allow us to return a database user so we assume a login failure
                        // Sign the user out of the AWS SDK and display the login controller
                        AWSMobileClient.sharedInstance().signOut()
                        AWSMobileClient.sharedInstance().invalidateCachedTemporaryCredentials()
                        AWSMobileClient.sharedInstance().clearCredentials()
                        AWSMobileClient.sharedInstance().clearKeychain()
                        
                        // set the initial view controller to the login screen
                        DispatchQueue.main.async {
                            if let _ = self.loginViewController {
                                self.window!.rootViewController = self.loginNavigationController
                            }
                        }
                    })
                    
                    
                } else {
                    // AWS Cognito client is initialised but user is not logged in
                    AWSMobileClient.sharedInstance().signOut()
                    AWSMobileClient.sharedInstance().invalidateCachedTemporaryCredentials()
                    AWSMobileClient.sharedInstance().clearCredentials()
                    AWSMobileClient.sharedInstance().clearKeychain()
                    
                    // set the initial view controller to the login screen
                    DispatchQueue.main.async {
                        if let _ = self.loginViewController {
                            self.window!.rootViewController = self.loginNavigationController
                        }
                    }
                }
                
                
            }
            ...
        }
```


If we end up at the loginNavigationController we use the SDK to directly call signIn with username and password credentials entered by the user:

```
@IBAction func loginUser(sender: AnyObject) {
        
        // clear any renmant of an existing session, as we occasionally see cached credentials ruin a login attempt
        AWSMobileClient.sharedInstance().signOut()
        AWSMobileClient.sharedInstance().invalidateCachedTemporaryCredentials()
        AWSMobileClient.sharedInstance().clearCredentials()
        AWSMobileClient.sharedInstance().clearKeychain()
        
            
            if let emailAddress = self.emailAddressField.text, let password = self.passwordField.text {
                if !emailAddress.isEmpty && !password.isEmpty {
                    
                    AWSMobileClient.sharedInstance().signIn(username: emailAddress, password: password) { (signInResult, error) in
                        if let error = error  {
                            print("\(error.localizedDescription)")
                            
                            ...
                            
                        } else if let signInResult = signInResult {
                            switch (signInResult.signInState) {
                            case .signedIn:
                                print("User is signed in.")
                                
                                APPXXXAPI.loginUser(success: { (userAccount) in
                                    print("login API success")
                                    print(userAccount)
                                    
                                    ...
                                    
                                    
                                }, failure: { (error) in
                                    print("login API error")
                                    print(error)
                                    
                                    ...
                                })
                                
                            case .smsMFA:
                                print("SMS message sent to \(signInResult.codeDetails!.destination!)")
                            case .newPasswordRequired:
                                print("A change of password is needed. Please provide a new password.")
                                
                                self.changePasswordFromCognitoRequirement()
                                
                            default:
                                print("Sign In needs info which is not yet supported.")
                            }
                        }
                    }
                } else {
                    
                    UIAlertController.createAndPresentAlertController(withTitle: "Login Error", message: "Please enter your email address and password to login.", actionButtonTitle: "OK")
                }
            } else {
                
                UIAlertController.createAndPresentAlertController(withTitle: "Login Error", message: "Please enter your email address and password to login.", actionButtonTitle: "OK")
            }
            
        }
    }
```

**Comment by jamesatfish** [comment]
@minbi can we provide any further assistance with this issue to help diagnose?

We are seeing a fairly regular pattern in our app with users coming back to accounts they've not used for a while.  They will try to login with known/saved credentials, will get a 'notAuthorized' response and assume their account has been deleted so will try to sign-up again with the same account (where they get a 'username exists' error).

We can't figure out any pattern to why those users are getting 'notAuthorized' when their credentials are correct.

If we can provide more detail from our code to help resolve this issue that would be great.

**Comment by YoanGJ** [comment]
Same problem here, any update?

**Comment by palpatim** [comment]
Hi all,

We believe we've identified a race condition (#1686)  that causes the signIn callback and the user state change listener to report events out of order, and can also result in the user state being flipped between signed-in and not-signed-in states. We're investigating this and will update that issue when we have more information.

In the meantime, I'm linking this issue to that one so we can follow up here once we have a fix in place for #1686.

**Comment by palpatim** [comment]
An update:

The race condition is more difficult to resolve than we originally thought, but we are continuing to work on it. In the meantime, @royjit has merged #1815, which fixes an error where signIn and confirmSignIn callbacks would sometimes not be called.

We'll update this issue when we have more information.

**Comment by palpatim** [comment]
We released a fix for some of the surrounding issues in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0

As noted, the underlying condition still exists, but overall, AWSMobileClient should be more stable.

**Comment by julien-tamade** [comment]
Hi, I am still having this issue. Some users are unable to sign back in after signing out. They get the "notAuthorized(message: "Incorrect username or password.")" error. When I test with a newly created user, everything works fine.

**Comment by VinnyScorsatto** [comment]
@julien-tamade , did you get any feedback on this issue? I am facing the same problem

**Comment by julien-tamade** [comment]
@VinnyScorsatto I can't remember what the conclusion was for us. Only one of our users experienced it so I'm not sure if it just never came back or we found a specific solution. One fix I remember making around that time was to make sure that the user is actually signed out before signing in again. I think we had an issue with the app not fully logging users out before they tried to sign in again. Not sure if that was related to that issue though. Sorry I can't be more specific.

**Comment by VinnyScorsatto** [comment]
@julien-tamade , thanks a lot.. my issue was regarding our lambda that was ignoring SRP initial step because of our web application. Cheers
