### ISSUE TITLE
Using aws-sdk-ios with custom DynamoDB endpoints

### ISSUE THREAD

**Issue by brockboe** [aws-amplify/aws-sdk-ios#1578]
**State your question**

Hello, I am working on an iOS application that uploads information to an Amazon DynamoDB. At the moment I have it successfully uploading and retrieving information from Amazon's own remote servers, but I would like to use my own dynamodb hosted on my own local network. I understand custom endpoints are a feature that have been added, and I am looking for  information, steps, or documentation on how to connect an iOS app to a custom endpoint, namely one hosted by yourself for use with DynamoDB, as current documentation on this feature is very scarce. Can anyone provide me with such information or point me in the right direction?

**Which AWS Services are you utilizing?**

DynamoDB

**Environment(please complete the following information):**
 - SDK Version: 2.9.9
 - Cocoapods
 - Swift Version : 4.1.3

**Device Information (please complete the following information):**
 - Device: iPad Air (real device, not simulation)
 - iOS Version: 12.3.1
 - Specific to simulators:

**Comment by minbi** [comment]
Hi @brockboe ,

As a starting point, you will need to change the endpoint for the DynamoDB client. This can be configured using the [endpoint property](https://github.com/aws-amplify/aws-sdk-ios/blob/806daa1279cb629e63a3dc4f33297a8d52bba4e1/AWSCore/Service/AWSService.h#L94)

Generally how the service configuration is passed in.

```
 *Swift*

     func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let credentialProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: "YourIdentityPoolId")
        let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
 
        return true
    }

 *Objective-C*

     - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
          AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1
                                                                                                          identityPoolId:@"YourIdentityPoolId"];
          AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1
                                                                               credentialsProvider:credentialsProvider];
          [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;

          return YES;
      }
```

**Comment by brockboe** [comment]
Yes, that did the trick! Looking through the objective-c code there is an AWSServiceConfiguration constructor that takes the endpoint as an argument [here](https://github.com/aws-amplify/aws-sdk-ios/blob/806daa1279cb629e63a3dc4f33297a8d52bba4e1/AWSCore/Service/AWSService.h#L104). 

Once you have an endpoint and credentials constructed, plugging them into the function yields a connection to the desired database. Thank you for your help!
