### ISSUE TITLE
AWSS3TransferUtility sometimes is not calling completionHandler

### ISSUE THREAD

**Issue by alejouribesanchez** [aws-amplify/aws-sdk-ios#1581]
Hi @kvasukib, Amazon engineers I am getting an issue related with "Stuck upload" the transfer appears to be stuck and the callback not being invoked. This is happening from time to time.

Can you share a code snippet where you construct the callback object?

```
[[transferUtility uploadDataUsingMultiPart: zipData
                                        bucket: self->auth_AWS_BucketName
                                           key: packagePathWithFileName
                                   contentType: @"application/zip"
                                    expression: expression
                             completionHandler: completionHandler] continueWithBlock:^id(AWSTask *task) {
        
        if (task.error) {
             // No enter here
        }
        
        if (task.faulted) { 
           // No enter here
        }
        
        if (task.result) {
            // YES, enter here
        }
        
        
        if (task.cancelled) {
           // No enter here
        }
        
        if (task.completed) {
           // YES, enter here but the completionHandler is not called, 
        }
        return nil;
    }];
```

Can you try with the latest version of the SDK?
Using AWSCore (2.9.7)
Using AWSS3 (2.9.7)

What version of iOS are you using? 12.2

What is the state of the app? Foreground

I am getting the task.completed but the  completionHandler is never called

**Comment by alejouribesanchez** [comment]
<img width="1144" alt="task_object" src="https://user-images.githubusercontent.com/3950665/58601132-236dc580-824d-11e9-84fd-939c75911313.png">
<img width="727" alt="task_complete" src="https://user-images.githubusercontent.com/3950665/58601146-2f598780-824d-11e9-99ea-27ab6ea89858.png">

**Comment by minbi** [comment]
Hi @alejouribesanchez ,

We have a sample app for S3 upload and download (although not multipart). Can you see if you can reproduce the issue in the sample app? The [upload method][1] and the [completionHandler][2] it uses.

[1]: https://github.com/awslabs/aws-sdk-ios-samples/blob/792dd0af3741b639071539b574b11100cb106b78/S3TransferUtility-Sample/Swift/S3BackgroundTransferSampleSwift/UploadViewController.swift#L82
[2]: https://github.com/awslabs/aws-sdk-ios-samples/blob/792dd0af3741b639071539b574b11100cb106b78/S3TransferUtility-Sample/Swift/S3BackgroundTransferSampleSwift/UploadViewController.swift#L49

**Comment by alejouribesanchez** [comment]
Hi @minbi I finally found the reason for the issue, but I think it's important for developers to understand this, to replicate it is easy, just try to upload a file in the sample app, during the upload put your phone on airplane mode, you will see that task completed is called as I mentioned above but the completionHandler is never called, so after inspecting your code I found this:

`static NSTimeInterval const AWSS3TransferUtilityTimeoutIntervalForResource = 50 * 60; // 50 minutes`

that means that I need to wait 50 minutes until the completionHandler is called even on bad networks or Airplane mode as my example.

So to fix this I set up my own timeout following your recommendations in the docs:
`transferUtilityConfiguration.timeoutIntervalForResource = 60;`

after that, of course, you need to register the new configuration 
```
      [AWSS3TransferUtility registerS3TransferUtilityWithConfiguration: configuration
                                            transferUtilityConfiguration: transferUtilityConfiguration
                                                                  forKey: sessionId];
```
Finally, I tested it again and after putting my phone in airplane mode, the completion handler was called after my 60 seconds defined above.

**Comment by semerda** [comment]
Is there any update on this issue from AWS team? @minbi ?

**Comment by lawmicha** [comment]
@alejouribesanchez @semerda , sorry the behavior of the large default timeoutIntervalForResource caused such a confusion on the usability of the transfer utility. we will take this issue into consideration when choosing better default values, as the purpose of it is cover the most common use cases for the developers. It sounds like you are able to get the completion handler invoked on network issues (airplane mode, network conditioning) by setting it to a smaller value. please let us know if you have any other questions or issues!

**Comment by lawmicha** [comment]
just a quick update- i'm currently investigating a bug with multipart upload where retried tasks are not resumed immediately on the retry, causing the transfer to take a long time to complete, essentially stalling the completionhandler from being called. once i get a chance to test the bug fix, and we release it, i will update this issue at that time for any one still interested in taking the release with those changes

**Comment by lawmicha** [comment]
https://github.com/aws-amplify/aws-sdk-ios/pull/1944

**Comment by lawmicha** [comment]
the above PR should have fixed it, please try with the latest version and let us know if you are still facing issues with multipart uploads not calling the completionHandler
