### ISSUE TITLE
Is AWSMobileClient.sharedInstance().interceptApplication() still required?

### ISSUE THREAD

**Issue by Foefirelord** [aws-amplify/aws-sdk-ios#1583]
**State your question**
The Amplify docs for authentication and analytics seem to have had the `interceptApplication()` method in them fairly recently, but I can no longer find it, so my question is: does AWSMobileClient still need to `return AWSMobileClient.sharedInstance().interceptApplication()` at the end of `application(_:didFinishLaunchingWithOptions:)` or is it deprecated?

**Which AWS Services are you utilizing?**
Cognito, Pinpoint

**Environment(please complete the following information):**
 - SDK Version: 2.9.7
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 12.3.1

**Comment by minbi** [comment]
Hi @Foefirelord ,

If you have migrated over to the new usage pattern shown in [these docs][1], then I'm not aware of a use-case that requires this intercept.

@rohandubal Can you verify my statement?

[1]: https://aws-amplify.github.io/docs/ios/authentication

**Comment by rromanchuk** [comment]
does anyone know if i can completely get rid of `AWSMobileClient`, i use in Federated identities to provide limited unauthenticated access via `AWSCognitoCredentialsProvider` and `AWSS3TransferUtility`, i'm worried about any potential voodoo that may disrupt my current implementation by removing this. 

For example https://aws-amplify.github.io/docs/ios/analytics#add-analytics

```swift
/** start code copy **/
        // Create AWSMobileClient to connect with AWS
        AWSMobileClient.sharedInstance().initialize { (userState, error) in
          if let error = error {
	    print("Error initializing AWSMobileClient: \(error.localizedDescription)")
          } else if let userState = userState {
	    print("AWSMobileClient initialized. Current UserState: \(userState.rawValue)")
          }
        }
```
What is the above code doing, and is it *actually* required.

What would happen to the following call without initializing above. 
```swift
let pinpointConfiguration = AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions)
pinpoint = AWSPinpoint(configuration: pinpointConfiguration)
```

**Comment by Foefirelord** [comment]
@rromanchuk You want to be going in the opposite direction. Replacing the old libraries with AWSMobileClient methods simplifies the necessary code by a country mile. It does all the same things the old libraries did but simpler and in an easier to grasp form.

**Comment by rromanchuk** [comment]
@Foefirelord  according to who?  I don't use amplify.

**Comment by rromanchuk** [comment]
And by "not using amplify" i mean, i don't interface with AWS through a marketing abstraction layer. I don't use  Amplify Auth™  (cognito user pools), i use federated identities, to do one thing, and one thing only. 

It's been an extremely straightforward configuration. This SDK is being cannibalized into one giant hello world project. 
 
```swift
let credentialProvider = AWSCognitoCredentialsProvider(regionType: .USEast2, identityPoolId: C.AWS.cognitoPoolEast2)

// Setup the service configuration
let configuration = AWSServiceConfiguration(region: .USEast2, credentialsProvider: credentialProvider)

// Setup the transfer utility configuration
let tuConf = AWSS3TransferUtilityConfiguration()
tuConf.isAccelerateModeEnabled = true
tuConf.retryLimit = 15
tuConf.multiPartConcurrencyLimit = 5
tuConf.bucket = C.AWS.checkInBucket

AWSS3TransferUtility.register(with: configuration!, transferUtilityConfiguration: tuConf, forKey: C.AWS.transferUtilityIdentifier) { error in
    // ....
}
```

**Comment by royjit** [comment]
Hi, apologies for the delayed response.
@Foefirelord `AWSMobileClient.sharedInstance().interceptApplication()` is deprecated and will be removed in the next release. 
@rromanchuk Yes, you can use the SDK without using `AWSMobileClient` if you prefer to use so.
