### ISSUE TITLE
AWS IOT AWSIoTMQTTClient crash

### ISSUE THREAD

**Issue by Wanxujie** [aws-amplify/aws-sdk-ios#1586]
**Describe the bug**
I am facing an issue cause with IoT open streams

libobjc.A.dylib | objc_msgSend + 16
-- | --
1 CoreFoundation | __inputStreamCallbackFunc + 56
2 CoreFoundation | __signalEventSync + 216
3 CoreFoundation | __cfstream_solo_signalEventSync + 244
4 CoreFoundation | __CFStreamSignalEvent + 308
5 CFNetwork | SocketStream::dispatchSignalFromSocketCallbackUnlocked(SocketStreamSignalHolder*) + 64
6 CFNetwork | SocketStream::socketCallback(__CFSocket*, unsigned long, __CFData const*, void const*) + 148
7 CFNetwork | SocketStream::_SocketCallBack_stream(__CFSocket*, unsigned long, __CFData const*, void const*, void*) + 88
8 CoreFoundation | ___CFSocketPerformV0 + 668
9 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
10 CoreFoundation | ___CFRunLoopDoSource0 + 88
11 CoreFoundation | ___CFRunLoopDoSources0 + 176
12 CoreFoundation | ___CFRunLoopRun + 1040
13 CoreFoundation | CFRunLoopRunSpecific + 436
14 Foundation | -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
15 AWSIoT | -[AWSIoTMQTTClient openStreams:] + 996
16 Foundation | ___NSThread__start__ + 1040
17 libsystem_pthread.dylib | __pthread_body + 128
18 libsystem_pthread.dylib | _pthread_start + 48

**To Reproduce**
1. App connects WiFi(internet) to connect IoT
2. App changes the WiFi to a device's AccessPoint (not internet)
3. App setup a TCP socket to the device in AccessPoint
4. device's AccessPoint breakdown and App auto reconnect the WiFi (internet)
5. IoT will auto be changed to disconnect、reconnect、error or other states in SDK
6. It will sometimes be crashed in AWSIoTMQTTClient openStreams

**Which AWS service(s) are affected?**
AWS IoT

**Expected behavior**

**Screenshots**
.0
![1](https://user-images.githubusercontent.com/10541985/58687448-3a7af780-83b4-11e9-8593-475aea73dae9.png)
![2](https://user-images.githubusercontent.com/10541985/58687461-3e0e7e80-83b4-11e9-8b61-d31acf1b63bc.png)

**Environment(please complete the following information):**
 - SDK Version: 2.9.5
 - Dependency Manager: Cocoapods
 - Swift Version : 4

**Device Information (please complete the following information):**
 - Device: iPhone6
 - iOS Version: 12.3
 - Specific to simulators:

**Additional context**

**Comment by minbi** [comment]
Hi @Wanxujie ,

Thanks for bringing this to our attention.

@desokroshan Can you see if you have any context on this issue?

**Comment by Wanxujie** [comment]
@minbi Is anyone help here?

**Comment by steelzeh** [comment]
@cbommas Our customers are experiencing this issue aswell.
![Screenshot 2019-07-23 at 15 29 38](https://user-images.githubusercontent.com/7465835/61716097-b400e780-ad5e-11e9-90f5-d706c22f5a1d.png)

Happening on the latest release.
