### ISSUE TITLE
How do I authenticate to Amazon Cognito using AWSMobileClient?

### ISSUE THREAD

**Issue by ghost** [aws-amplify/aws-sdk-ios#1592]
Problem: I have two user pools in Cognito. Let's call them Pool A and B. I am able to authenticate a user to "Pool A" successfully.

I need to authenticate a user created by backend dynamically to "Pool B" from the client.

Docs I have read: 
- Amazon Amplify
- Amazon Cognito
- Amazon SDK for iOS
- AWSMobileClient

My setup: 
- AWSMobileClient v2.9.8
- iOS 12.0
- iPhone 7 Plus

I have tried the following solution:

- awsconfiguration.json has information regarding "Pool A"
- I log in a user to "Pool A" and perform business logic (success)
- I log out the user globally and invalidate the tokens. (success)
- I setup configuration for "Pool B" from code, I'm not sure how to specify multiple user pools in awsconfiguration.json. Not sure if it's doable.
- I login the user created by the backend present in "Pool B". (fails with the error message "Could not get the end user to sign in")

AWSMobileClient.sharedInstance().signIn(username: "user_present_in_pool_a", password: "password" ) { result, error in

        debugPrint(result, error)

        // Async sign out

        AWSMobileClient.sharedInstance().signOut(
            options: .init(
                signOutGlobally: true,
                invalidateTokens: true
            ),
            completionHandler: { error in

            debugPrint(error)

            // setup configuration for "Pool B"
            let serviceConfig = AWSServiceConfiguration(
                region: .USWest2,
                credentialsProvider: nil
            )

            let poolConfig = AWSCognitoIdentityUserPoolConfiguration(
                clientId: "pool_b_client_id", clientSecret: nil, poolId: "pool_b_id"
            )

            // init pool client
            AWSCognitoIdentityUserPool.register(
                with: serviceConfig,
                userPoolConfiguration: poolConfig,
                forKey: "some_key"
            )

            AWSMobileClient.sharedInstance().signIn(
                username: "user_present_in_pool_b",
                password: "password"
            ) { result, error in
                debugPrint(result, error)
            }
        })
    }

The aws-sdk-ios documentation is vague and I would really appreciate pointers to appropriate docs or perhaps a solution. Thank you :)

**Comment by desokroshan** [comment]
@aqeelbhat This is currently not supported in AWSMobileClient. I have marked this as a feature request. I will take it to the team for prioritization. At this point I do not have a specific timeline that I can share with you. I will update this thread when I have more information.

**Comment by palpatim** [comment]
This should be fulfilled when we implement #1649.

**Comment by royjit** [comment]
You can now configure `AWSMobileClient` on runtime. But multiple configuration is not supported. You can read more about it from [here](https://aws-amplify.github.io/docs/ios/manualsetup#configure-using-an-in-memory-object).

**Comment by royjit** [comment]
Closing this based on the comment above. Some discussion regarding multiple configuration can be found here.
