### ISSUE TITLE
why base64EncodedStringWithOptions returned 44 characters instead of 64?

### ISSUE THREAD

**Issue by alexliuxe** [aws-amplify/aws-sdk-ios#1597]
**State your question**
In getSessionInternal method (file: AWSCognitoAuth.m) `- (void)getSessionInternal: (nullable UIViewController *) vc completion: (AWSCognitoAuthGetSessionBlock) completion {`, there are a couple methods which will generate a 32 bytes string then encode it with sha256 then encode with base64. My question is why the result it not a string with 64 character. Instead the length is 44.

**Provide code snippets (if applicable)**

Original SDK code.
`
self.proofKey = [self generateRandom:32];
 self.proofKeyHash = [self calculateSHA256Hash:self.proofKey];
`

**Environment(please complete the following information):**
 - SDK Version: 2.9.8
 - Dependency Manager:  Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
simulators: XR- iOS 13.0

**Comment by royjit** [comment]
Hi @alexliuxe Apologies for the delayed response. SHA256 produces a 256 bit result. When we do a base64 on this the 256bits, it will be chunked into 6 bits group ie `256/6 = 42.6666666667` and with padding this will go to 44.

Please reach out to us if you are facing any issue or have any other question with using our SDKs.
