### ISSUE TITLE
AWSStaticCredentialsProvider missing constructor for session token

### ISSUE THREAD

**Issue by purmonen** [aws-amplify/aws-sdk-ios#16]
In the current version it's not possible to provide a session token in the constructor to the AWSStaticCredentialsProvider.

**Comment by gkaur1** [comment]
Hi, I created custom credentialProvider thru which I can set the sessionToken
But I don't in the logs that Authorization or Credentials parmaeter in the header. 
Can you please adivse what I might be doing wrong? thanks

**Comment by yosuke-matsuda** [comment]
Can you share a minimal code snippet to reproduce the issue so that we can take a look?

**Comment by gkaur1** [comment]
Hi, thank you for the response, it was a mistake on my part. 
After defining my custom Credentials provider class, I named my property as sessionToken and NOT sessionKey, my mistake.
