### ISSUE TITLE
Cannot compile for UIKit for Mac

### ISSUE THREAD

**Issue by colinhumber** [aws-amplify/aws-sdk-ios#1603]
**Describe the bug**
With the new UIKit for Mac support in Xcode 11 and macOS Catalina, this library is currently unable to compile the My Mac target. There are unavailable keychain APIs preventing the SDK from being compiled.

**To Reproduce**
- install the SDK into an iPad Xcode 11 project
- enable Mac support
- compile the app for the My Mac target

**Which AWS service(s) are affected?**

**Expected behavior**
The SDK should compile

**Screenshots**
![image](https://user-images.githubusercontent.com/104855/59164787-f3d17f80-8ace-11e9-84b1-f279e29a8505.png)

**Environment(please complete the following information):**
 - SDK Version: 2.9.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: macOS Catalina
 - iOS Version: n/a
 - Specific to simulators: 

**Additional context**

**Comment by colinhumber** [comment]
Just as a note, not asking specifically about macOS support, just that the internal dependency on UICKeychainStore be updates to remove any calls to unavailable APIs.

**Comment by kvasukib** [comment]
@colinhumber Thank you for reporting to us. I have tagged this as a feature request and added to the backlog for prioritization.

**Comment by colinhumber** [comment]
@kvasukib I would be happy to work on this. After checking the custom prefixed `UICKeychainStore` code in both `AWSCore` and `AWSCognitoAuth`, the offending methods are already wrapped in an `#if TARGET_OS_IOS`. These methods are also not called anywhere in the AWS code. In Xcode 11 there's also a new `TARGET_OS_UIKITFORMAC` macro available to deal with these unavailable APIs. Of course, that can't be included until the public release, but this should be a pretty trivial change, as far as I can tell to get this working for both iOS targets and iPad apps deployed to macOS.

**Comment by mmdumi** [comment]
Hi, Any other news regarding this ?

**Comment by EmperiorEric** [comment]
Hoping for updates here. Is there a branch with this working?

**Comment by EmperiorEric** [comment]
@kvasukib Any updates on this? We're probably about a month or less from release.

@colinhumber Did you work around this somehow?

**Comment by air720boarder** [comment]
Bumping for updates

**Comment by colinhumber** [comment]
I've been waiting to get an official update, but in the meantime I have this on a branch. I might just do a PR since there's been no word as to whether this will be internally handled.

https://github.com/colinhumber/aws-sdk-ios/tree/uikit-for-mac

**Comment by Hardiktspaceo** [comment]
When we get the updated pod which is also support macCatalyst ?

**Comment by meyumeapps** [comment]
Another vote for an updated pod please with support for macCatalyst

**Comment by awumsuri** [comment]
Please update

**Comment by ralfebert** [comment]
AWS for iOS still doesn't work out of the box with Xcode 11 because of these errors.

**Comment by xylys** [comment]
Please update

**Comment by happasquared** [comment]
yes please ;)

**Comment by chrisCGL** [comment]
Please make this update to the pod file so that we can work with the catalyst

**Comment by amuresia** [comment]
Bumping for updates, thanks!

**Comment by jaelee1993** [comment]
Has this been resolved?

**Comment by gorlov-clearscale** [comment]
It will not work if we are using Cognito, because it includes compiled .a lib.

**Comment by gorlov-clearscale** [comment]
Another problem is SFAuthetnicationSession which is not available on Catalyst.

**Comment by ppamorim** [comment]
Please fix this.

**Comment by LYM-collab** [comment]
I need a fix for this if possible. Thanks

**Comment by jhays** [comment]
I tried using @colinhumber 's uikit-for-mac branch, but my project needs AWSIoT, and I am running into another error when trying to build for macOS Catalyst in AWSSRWebSocket.m - the import <Endian.h> is not found.

**Comment by samirsd** [comment]
fucking fix this please

**Comment by samirsd** [comment]
please fix

**Comment by robwithhair** [comment]
Now the only reason my app doesn't work on mac.  PLEASE FIX ASAP AWS!!!

**Comment by jaelee1993** [comment]
Any luck on this?

**Comment by LYM-collab** [comment]
Going to keep asking here as this is important to us.

**Comment by robwithhair** [comment]
@nikhil-dabhade any update on this?

**Comment by robwithhair** [comment]
@royjit any update on this?  Just won't build on Xcode ATM.

**Comment by Jeremy-Kotai** [comment]
Please update!

**Comment by code-surf** [comment]
Any updates?

**Comment by roddymunro** [comment]
This is blocking us from working on our Mac Catalyst app. Please update ASAP.

**Comment by jaivia** [comment]
Why is AWS so against any sort of macOS support...since 2010 it makes cross platform Apple applications impossible

**Comment by robwithhair** [comment]
There’s nothing worse than investing your time writing against a library only to find it gets you 99% of the way there but not that last 1%. Re-wrote my app to use API calls at great expense. Won’t waste my time on an Amazon maintained library again.

**Comment by samirsd** [comment]
can i at least get the brand of wax that jeff bezos uses for his head? thnx in advance

**Comment by junya100** [comment]
Any update?

**Comment by ppamorim** [comment]
Sadly I don't think AWS will help us, instead, we will wait for macOS Big Sur that allows iOS apps to work directly.

**Comment by msuzoagu** [comment]
@nikhil-dabhade can you please provide an update on this? Are we ever going to get this or not? So we know how to move forward.

**Comment by drochetti** [comment]
Hi @msuzoagu, we're currently evaluating supporting other platforms, such as MacOS. Our primary goal is to add support for other platforms in [Amplify iOS ](https://github.com/aws-amplify/amplify-ios), we're still not sure if we'll be able to cover all the SDKs, since there's quite a bit of area to cover and also legacy code. Regardless I'll keep you posted.

In case you're working on new projects, I suggest you check if Amplify is a good fit for you.

**Comment by quangctkm9207** [comment]
@drochetti : Thank you for sharing the primary goal on Amplify iOS.
Yeah, it is better to migrate there, but it might take time. 
Can you help me to clarify several things?

1. Does Amplify iOS support Mac Catalyst at the moment?
2. And is there any plan that AWS SDK iOS supports Mac Catalyst in the near future too? If not, I might migrate to Amplify iOS as soon as possible. 

Many thanks,
Quang.

**Comment by drochetti** [comment]
> @drochetti : Thank you for sharing the primary goal on Amplify iOS.
> Yeah, it is better to migrate there, but it might take time.
> Can you help me to clarify several things?
> 
> 1. Does Amplify iOS support Mac Catalyst at the moment?
> 2. And is there any plan that AWS SDK iOS supports Mac Catalyst in the near future too? If not, I might migrate to Amplify iOS as soon as possible.
> 
> Many thanks,
> Quang.

It's very unlikely we will add support to anything other than iOS to the SDKs, but we are evaluating and working on a plan to support more platforms on Amplify. An issues was created recently asking for macOS support, feel free to +1 it and also leave comments about your needs. The more info we have about developers' needs, the better: https://github.com/aws-amplify/amplify-ios/issues/1124

**Comment by colinhumber** [comment]
@drochetti If you're cool with it, I'm going to close this issue as you mentioned there's a feature request already set that's a better place for people to +1.

**Comment by palpatim** [comment]
Thanks @colinhumber, it would be great to consolidate feedback on that issue rather than splitting the conversation.

**Comment by parachutemind** [comment]
ditto for this request. Catalyst open up the possibility of using UIKit code in macOS. However, with Swift UI and Apple Multiplatform projects it is  possible to write "pure" UIs that can easily run on macOS. We have a project that requires macOS support and we hit this early snag of not able to use graphql with Amplify and AppSync.

**Comment by kvaDrug** [comment]
@drochetti, you misunderstand the request. Mac Catalyst is not the same as macOS. To add this platform you need much less steps, it's almost like iOS simulator running on mac.
