### ISSUE TITLE
User is signed in on reinstalling the app

### ISSUE THREAD

**Issue by vincenzo-favara** [aws-amplify/aws-sdk-ios#1605]
**Describe the bug**
Though Re-installing App again, " AWSMobileClient.sharedInstance().isSignedIn " always return "true"

**To Reproduce**
1. Logi in
2. disinstall the app
3. reinstall
4. user is still logged in

**Which AWS service(s) are affected?**

**Expected behavior**
user should be logged out

**Environment(please complete the following information):**
 - SDK Version: 2.9.9
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Comment by JesusMartinAlonso** [comment]
I have faced the same issue. The "problem" is that AWS SDK stores the login information in the keychain, and this information is not deleted when the app is uninstalled.

My solution was to perform a signout in the first access of the user to the app. I use a Bool in UserDefaults to know if it is the first access.

**Comment by kvasukib** [comment]
@vincenzo-favara What version of iOS are you using? This behavior is different for different iOS versions based on the Keychain implementation in the iOS version.

**Comment by spandana-batchu** [comment]
> I have faced the same issue. The "problem" is that AWS SDK stores the login information in the keychain, and this information is not deleted when the app is uninstalled.
> 
> My solution was to perform a signout in the first access of the user to the app. I use a Bool in UserDefaults to know if it is the first access.
@JesusMartinAlonso  JesusMartinAlonso Is this a good practice to do this? Or would rather let the user be logged in when he reinstalls the app?
