### ISSUE TITLE
aws connect faile on ios

### ISSUE THREAD

**Issue by 18638597928** [aws-amplify/aws-sdk-ios#1607]
this is my code:
 let credentialProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: "us-east-1:c6d1e831-5135-49c0-b307-afa890b56a10")

        var configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration

        let d = a.connect(withClientId: "us-east-1:c6d1e831-5135-49c0-b307-afa890b56a10", cleanSession: true, configuration: configuration, keepAlive: 60, willTopic: "test", willMsg: nil, willQoS: 0, willRetainFlag: true) { (ststus) in
            print("++")
            print(ststus.rawValue)
        }

but  it is error,  error message is that:
2019-06-14 17:04:23.955118+0800 awsDemo[8814:227299] TCP Conn 0x600001895bc0 Failed : error 0:-65554 [-65554]
2019-06-14 17:04:23:955 awsDemo[8814:227461] didFailWithError: Websocket failed With Error Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={_kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, kCFGetAddrInfoFailureKey=8}

how can i do

**Comment by royjit** [comment]
HI @18638597928 Apologies for the delayed response.
Could you please provide more details on the error? Not sure what the variable `a` in your code sample points to. 
Are you trying to use AWSConnectService? Please provide details:

**Which AWS service(s) are affected?**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:
