### ISSUE TITLE
Not able to update AWSServiceConfiguration in AWSS3TransferUtility after register it one time.

### ISSUE THREAD

**Issue by VikasPrajapatiSA** [aws-amplify/aws-sdk-ios#1614]
**Not able to update AWSServiceConfiguration in AWSS3TransferUtility after register it one time.**
I am following this link to upload an image: https://aws-amplify.github.io/docs/ios/storage

I want to upload an image in AWSS3 bucket. So, I am using AWSS3TransferUtility to upload image in the bucket. Now, the problem is in my project we have session key which expires in one hour, So, I need to update configuration in AWSS3TransferUtility, But, Now we don't have any approach to do this.

        let credential = AWSBasicSessionCredentialsProvider.init(accessKey: //accesskey, secretKey: //secrate key, sessionToken: //session key)
        
        guard let configuration = AWSServiceConfiguration.init(region: .USEast2, credentialsProvider: credential) else{
            return
        }
        let tuConf = AWSS3TransferUtilityConfiguration()
        
        AWSS3TransferUtility.register(
            with: configuration,
            transferUtilityConfiguration: tuConf,
            forKey: "transfer-utility-with-advanced-options"
        ) { (error) in
            if let error = error {
                //Handle registration error.
                print(error.localizedDescription)
            }
        }

If I am calling AWSS3TransferUtility.register again then it gives me an error like, 

A background URLSession with identifier com.amazonaws.AWSS3TransferUtility.Default.Identifier.transfer-utility-with-advanced-options already exists!

For the solution, I tried one more way to first remove this key and then again call AWSS3TransferUtility.register but it does not work fine.
                
AWSS3TransferUtility.remove(forKey: "transfer-utility-with-advanced-options")

Can you please help me to solve this problem?

**Comment by rohandubal** [comment]
Hello @VikasPrajapatiSA 

Can you remove the registered client and re-add it? There is a `removeTransferUtilityForKey` API on `AWSS3TransferUtility` client which you can find here:  
https://aws-amplify.github.io/aws-sdk-ios/docs/reference/Classes/AWSS3TransferUtility.html#//api/name/removeS3TransferUtilityForKey:

Thanks,
Rohan

**Comment by VikasPrajapatiSA** [comment]
Thanks for suggestion @rohandubal. I tried this but as I mentioned when I remove the registered client and re-add it then its some time remove or sometimes not.

Code:

AWSS3TransferUtility.remove(forKey: "transfer-utility-with-advanced-options")

    AWSS3TransferUtility.register(
        with: configuration,
        transferUtilityConfiguration: tuConf,
        forKey: "transfer-utility-with-advanced-options"
    ) { (error) in
        if let error = error {
            //Handle registration error.
            print(error.localizedDescription)
        }
    }

When I write above code then library not remove properly and gives the same error:

A background URLSession with identifier com.amazonaws.AWSS3TransferUtility.Default.Identifier.transfer-utility-with-advanced-options already exists!

Can you please take a look at this case?

**Comment by kvasukib** [comment]
@VikasPrajapatiSA What is the key in `AWSS3TransferUtilityConfiguration` you are trying to update? We recommend using a fixed configuration (`AWSS3TransferUtilityConfiguration`) for the lifecycle of the app.

If you have varying configuration for different transfers, then we recommend you to create different `TransferUtility` objects based on the different configurations created.

The error you are seeing is due to the fact that the NSURLSession identifier is created based on the configuration key and we expect it to remain the same for the lifecycle of the app and the transfers that are started using that configuration.

**Comment by VikasPrajapatiSA** [comment]
I understand that the problem happens because of NSURLSession related stuff. But, If I am using the different key every time for TransferUtility object then I have to make sure to remove all old key when creating new TransferUtility object with a new key. So do you have another way to resolve it? Because I am removing key first and regenerate but now working which I mentioned above.

**Comment by kvasukib** [comment]
@VikasPrajapatiSA You could create new keys based on a random UUID for every unique configuration and store the keys in your app for future retrieval.

**Comment by zcramos** [comment]
I'm running into a similar issue. The primary use case is uploading photos (so, small files that should not have long-running URL sessions), and our credentials have a relatively short expiration timeout. I'm not setting a custom `AWSS3TransferUtilityConfiguration` - I just need to update the `AWSServiceConfiguration` with new credentials when necessary. My current code registers an `AWSS3TransferUtility` for the key `"S3Utility"` in one method, and another method gets the transferUtility (`guard let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "S3Utility")` then initiates an upload. 

It appears as though simply registering a new `AWSS3TransferUtility` doesn't quite work. Initiating an upload after I've done this results in the following logger output:
```
didSendBodyData called for task 2

Thread:<NSThread: 0x600003c459c0>{number = 26, name = (null)}: didCompleteWithError called for task 2

Unable to find information for task 2 in taskDictionary
```

I'd like to avoid removing a previously-registered utility in case any transfers are currently in-flight when credentials are refreshed. My original theory was that registering a new transfer utility atop the original would remove the reference in AWSS3TransferUtility's `_serviceClients` dictionary, and once any in-flight uploads are completed there would be no more references to that instance so it would be garbage collected. Is this not the case? Or is my second attempt at registering a transfer utility failing somehow?

This is a react-native app so upon completing a transfer I `resolve` with the results of the transfer. As long as the completion block will be preserved with all its original references (specifically for the `resolve`/`reject` params my upload method accepts), then I suppose if the S3 client enables this I could grab all in-progress transfers, cancel them, remove the existing `transferUtility`, then create a new one and re-initiate all the upload tasks. Is that possible?

**Comment by palpatim** [comment]
> I'd like to avoid removing a previously-registered utility in case any transfers are currently in-flight when credentials are refreshed.

Yes, since you're using a static identifier, the correct behavior is to register the client once per app launch.

The responsibility for providing refreshed credentials to the TransferUtility lies with the credentials provider registered with the service configuration, you shouldn't need to re-register a service configuration every time the credentials need to be refreshed.

> As long as the completion block will be preserved with all its original references (specifically for the resolve / reject params my upload method accepts)...

The completion block will be preserved while the app is in memory; if the app is restarted then you would need to recreate completion blocks by iterating over active tasks for the registered TransferUtility instance, using `getUploadTasks`, `getDownloadTasks`, and `getMultiPartUploadTasks`.

I think the root of your issue though is that you'll want a credentials provider that can refresh credentials automatically, rather than re-registering a client. Our [S3 Sample App](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferUtility-Sample/Swift) uses `AWSMobileClient` to do this.

**Comment by VikasPrajapatiSA** [comment]
@zcramos  I found one solution as we can resolve this type of problem.
When you create again AWSS3TransferUtility then first remove this object with the same key and make the object again after a one-second delay. I think that it will work fine.

AWSS3TransferUtility.remove(forKey:"S3Utility")
DispatchQueue.main.asyncAfter(deadline: .now() + 0.1, execute: {
       // create object again
})

Hope it will help you.

**Comment by SukanyaDey** [comment]
I found similar issue like below,

```
didSendBodyData called for task 2

Thread:<NSThread: 0x600003c459c0>{number = 26, name = (null)}: didCompleteWithError called for task 2

Unable to find information for task 2 in taskDictionary
```

The problem was that the app was registering the transfer utility object multiple times with same key. I have modified the code like below,

```
NSString *key = [NSString stringWithFormat:@"testKey"];
AWSS3TransferUtility * transferUtility1 =  [AWSS3TransferUtility S3TransferUtilityForKey: key];  
if(transferUtility1 == nil){
[AWSS3TransferUtility registerS3TransferUtilityWithConfiguration:config transferUtilityConfiguration:tuConf forKey: key completionHandler:^(NSError * _Nullable error) {
  }];
        
transferUtility1 =  [AWSS3TransferUtility S3TransferUtilityForKey: key];
   
 }
```

This change solved my problem. However I'm little confused if this is the correct approach. Please suggest.
