### ISSUE TITLE
Prebuilt binaries are not built with Xcode 10.2 / Swift 5

### ISSUE THREAD

**Issue by jweg29** [aws-amplify/aws-sdk-ios#1615]
**Describe the bug**
Running `carthage bootstrap --platform iOS --cache-builds` downloads the AWS framework binaries as expected, but they are incompatible due to being built with Xcode 10.1 / Swift 4.2.1. I am then forced to build the frameworks locally, which can take over an hour since there is no way to specify specific AWS libraries in the cartfile.

**To Reproduce**
1. Using the current version of Xcode's (10.2.1) toolchain  run `carthage bootstrap --platform iOS --cache-builds`
2. Should receive the following error: "Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)."

**Which AWS service(s) are affected?**
aws-sdk-ios

**Expected behavior**
The prebuilt binaries should be built with the current version of Xcode (10.2.1)

**Environment(please complete the following information):**
 - Dependency Manager:  Carthage
 - Swift Version : 5.0.1

**Comment by james-ff** [comment]
Same thing

**Comment by steelzeh** [comment]
+1 
Building in Carthage seriously takes 15-30 minutes. Please update it to Swift 5.0
@cbommas

**Comment by olegdanu-newstore** [comment]
Experiencing the same issue :/

**Comment by jweg29** [comment]
@rohandubal  @kvasukib @cbommas is there any timeline on this? Swift 5 and Xcode 10.2 have been out for months now.  Xcode 11 with Swift 5.1 will be officially released next week which will make your binaries even more out of date. You should either support specifying individual AWS frameworks in Carthage or keep your prebuilt binaries reasonably up to date, but forcing every developer to deal with these build times is ridiculous.

**Comment by james-ff** [comment]
I've had to reluctantly switch to cocoapods because of this. Can't understand why you can target individual packages in Pods but not in Carthage.

**Comment by w0mba7** [comment]
+1

**Comment by palpatim** [comment]
Whoops, should have closed this when we released #1935. Carthage will now be built with an ABI-compatible version of Swift, which should solve the original problem of incompatible Swift versions.

Regarding not being able to build individual libraries--I'm not aware that there is a way to specify individual targets in the cartfile--it seems that Carthage wants to build all shared schemes.
