### ISSUE TITLE
Use AWSS3TransferUtility Download is not the latest file

### ISSUE THREAD

**Issue by RuiKQ** [aws-amplify/aws-sdk-ios#1616]
**State your question**
I use AWSS3TransferUtility to download a file which was uploaded by AWSS3TransferUtility. Then I edit this file and upload it again. Then I use AWSS3TransferUtility to download it again. The file I downloaded at this time is not the latest. However I get the latest file when I use AWSS3TransferManager. 

**Which AWS Services are you utilizing?**
AWSS3Transfer

**Provide code snippets (if applicable)**

```objective-c
AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionEUWest1 identityPoolId:[[S3Environment shareInstance] poolId]];
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:self.config.region credentialsProvider:credentialsProvider];
AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;

```

```objective-c
AWSS3TransferUtility *utility = [AWSS3TransferUtility defaultS3TransferUtility];

    [utility downloadToURL:[NSURL fileURLWithPath:fullFilePath] bucket:self.config.bucketName key:[CSKeyManager storageFileKey:key] expression:nil completionHandler:^(AWSS3TransferUtilityDownloadTask * _Nonnull task, NSURL * _Nullable location, NSData * _Nullable data, NSError * _Nullable error) {
        if (error) {
            kLogI(@"Error uploading  ---%@, reason :(%@)",key.lastPathComponent,error);
            successBlock(NO);
        } else {
            kLogI(@"Upload completed ---%@",key.lastPathComponent);
            successBlock(YES);
        }
    }];
```

**Environment(please complete the following information):**
 - SDK Version: 2.9.9
 - Dependency Manager: Cocoapods
 - Swift Version : OC

**Device Information (please complete the following information):**
 - Device: iPhone6
 - iOS Version: 12.3.1
 - Specific to simulators:

**Comment by rohandubal** [comment]
Hello @RuiKQ 

- How have you implemented the logic to kick off re-downloading the new file? Is there a possibility of a race condition that the download begins before the upload has completed?
- Is the download location of new download same as the previous download?

Thanks,
Rohan

**Comment by RuiKQ** [comment]
Thank you for your reply.
1. I use AWSS3 to backup and recovery file. When I edit a file( a database file) I will upload it.  Next time I will download it. It was work fine when I used AWSS3TransferManager.
2. The key of the same file is fixed. That is to say, The key for uploading the same file each time is the same. It is also when I download same file.

I just change this function in my project and It can't work. Did the S3 service will cover the old file when I upload a new file used the same key?
```objective-c
-(void)downloadFilePure:(NSString*) fullFilePath key:(NSString*)key  successBlock:(void (^)(BOOL result))successBlock
{

//    AWSS3TransferManagerDownloadRequest *downloadRequest = [AWSS3TransferManagerDownloadRequest new];
//    downloadRequest.bucket = self.config.bucketName;
//    downloadRequest.key = [CSKeyManager storageFileKey:key];
//    downloadRequest.downloadingFileURL = [NSURL fileURLWithPath:fullFilePath];
//    kLogI(@"start download pure key:(%@),---- request key:(%@)", key,downloadRequest.key);
//
//    AWSS3TransferManager *transferManager = [AWSS3TransferManager defaultS3TransferManager];
//    [[transferManager download:downloadRequest] continueWithExecutor:[AWSExecutor mainThreadExecutor]  withBlock:^id _Nullable(AWSTask * _Nonnull t) {
//        if (t.error){
//            kLogI(@"Error downloading -- %@,reason:(%@)",downloadRequest.key.lastPathComponent,t.error);
//            successBlock(NO);
//        } else {
//            kLogI(@"Download completed --- %@",downloadRequest.key.lastPathComponent);
//            successBlock(YES);
//        }
//        return nil;
//    }];
    
    AWSS3TransferUtility *utility = [AWSS3TransferUtility defaultS3TransferUtility];

    [utility downloadToURL:[NSURL fileURLWithPath:fullFilePath] bucket:self.config.bucketName key:[CSKeyManager storageFileKey:key] expression:nil completionHandler:^(AWSS3TransferUtilityDownloadTask * _Nonnull task, NSURL * _Nullable location, NSData * _Nullable data, NSError * _Nullable error) {
        if (error) {
            kLogI(@"Error uploading  ---%@, reason :(%@)",key.lastPathComponent,error);
            successBlock(NO);
        } else {
            kLogI(@"Upload completed ---%@",key.lastPathComponent);
            successBlock(YES);
        }
    }];
}
```

**Comment by RuiKQ** [comment]
Does anyone know what the problem is?

**Comment by RuiKQ** [comment]
Hi @rohandubal

**Comment by palpatim** [comment]
@RuiKQ 

I believe this was an intentional change, not a bug, although the behavior does represent a change from the old client. You will need to specify a new URL to download to, and copy the file to the desired destination URL (removing any existing file before doing so).

**Comment by RuiKQ** [comment]
Thank you for your reply. I will do this.
