### ISSUE TITLE
AWSMobileClient- signInUIOptions

### ISSUE THREAD

**Issue by AGoyal1980** [aws-amplify/aws-sdk-ios#1619]
**Which AWS Services is the feature request for?**
AWSMobileClient SignInUIOptions

**Is your feature request related to a problem? Please describe.**
I am using 

```swift
AWSMobileClient.sharedInstance().showSignIn(navigationController: navigationController!, signInUIOptions: SignInUIOptions(
            canCancel: true,
            logoImage: UIImage(named: "human-2944065"),
            backgroundColor: UIColor.black )) 
Currently I get UserName, Password, Email and PhoneNumber on the SignUp screen. 
```

**Describe the solution you'd like**

I need only Email, Password and Phonenumber.

**Describe alternatives you've considered**
Custom UI

**Additional context**

**Comment by rohandubal** [comment]
Hello @AGoyal1980 

Thanks for the description. I will take this as a feature request to the team and post updates when we pick it up.

Thanks,
Rohan

**Comment by jeryini** [comment]
Hello @rohandubal ! It seems it's still not possible to specify that we need only certain fields for registration process?

**Comment by royjit** [comment]
Marking this as duplicate - https://github.com/aws-amplify/aws-sdk-ios/issues/1998
