### ISSUE TITLE
Use Facebook native sdk to log in and create user pool

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-ios#1620]
_Original issue opened by @lovekumartrantor: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/265_

---

**State your question**
I want to be able to use Facebook's native SDK to log in to my facebook account, which on completion, would also create a user in user pool.

I'm currently using the code below to log into facebook which also creates a user in user pool for me. 

Problem with this approach - A new user is created and the user is directed to home. Now, when the app is killed and opened home screen opens, but the facebook login popup comes for a few seconds and is automatically dismissed. I'm not able to find the resolution so looking for other ways.

I have tried federatedSignIn but that does not create a user in the user pool.

**Provide code snippets (if applicable)**
All the setup required for below has been done as per given in docs.

```swift

let hostedUIOptions = HostedUIOptions(scopes: ["openid", "email","aws.cognito.signin.user.admin", "profile"], identityProvider: "Facebook")

AWSMobileClient.sharedInstance().showSignIn(navigationController: navigationController, hostedUIOptions: hostedUIOptions) { (userState, error) in
    
    if let error = error as? AWSMobileClientError {
        print(error.localizedDescription)
        DispatchQueue.main.async { completion(.failure(.awsMobileClientError(error))) }
    } else if let error = error {
        DispatchQueue.main.async { completion(.failure(.unknown(error))) }
    }
    
    if let userState = userState {
        print("Status: \(userState.rawValue)")
        completion(.success("showLoading"))
        AWSMobileClient.sharedInstance().getUserAttributes { (attributes, error) in
            
            if let error = error {
                DispatchQueue.main.async { completion(.failure(.unknown(error))) }
            }
            
            guard let name = attributes?["name"] else { return }
            guard let sub = attributes?["sub"] else { return }
            guard let email = attributes?["email"] else { return }
            
            UserDefaults.standard.set(name, forKey: Constants.UserDefaultskeys.userAttributeName)
            UserDefaults.standard.set(sub, forKey: Constants.UserDefaultskeys.userAttributeSub)
            UserDefaults.standard.set(email, forKey: Constants.UserDefaultskeys.userAttributeEmail)
            
            completion(.success(nil))
        }
    }
```

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.13.1
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 12.2
 - Specific to simulators: No

**Comment by royjit** [comment]
Creating a user in UserPool after social provider authentication is currently supported only if you use [HostedUI](https://aws-amplify.github.io/docs/sdk/ios/authentication#using-hosted-ui-for-authentication). This has been taken as a feature request to Cognito.

Closing this as duplicate #1937
