### ISSUE TITLE
AWSTextract documentation in Swift

### ISSUE THREAD

**Issue by ramakrishna013** [aws-amplify/aws-sdk-ios#1622]
This is not an issue in aws-sdk-ios.

I am just trying to confirm if Amazon Textract SDK is available in Swift?

I am currently referring this documentation - https://docs.aws.amazon.com/textract/latest/dg/how-it-works.html

It has Java, Python and AWS CLI. Any help would be greatly appreciated! Thank you! :)

**Comment by palpatim** [comment]
@ramakrishna013 

Textract SDK is not yet available in the iOS or Android SDKs. We'll take this on as a feature request and update this thread when we have more information.

**Comment by ramakrishna013** [comment]
@palpatim  Thanks for the information. We are waiting for that.

**Comment by kvasukib** [comment]
@ramakrishna013 To be precise, I am working on this, however the Textract SDK in iOS will be written in ObjC.

**Comment by karthironald** [comment]
@kvasukib When can we expect this Textract iOS SDK? Is it released?

**Comment by palpatim** [comment]
@karthironald We just released this on https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.10.2

**Comment by karthironald** [comment]
Sorry if I'm missing anything. I have tried to integrate SDK manually by downloading and adding in Xcode. But I couldn't find Textract SDK. Can you please help with this?
<img width="772" alt="Screenshot 2019-08-01 at 7 17 59 PM" src="https://user-images.githubusercontent.com/19427160/62298780-49a02380-b491-11e9-9f6c-eeb48a6b716e.png">

**Comment by palpatim** [comment]
@karthironald Sorry for the error--I think I might know what's going on. Did you encounter this error while following the instructions at https://github.com/aws-amplify/aws-sdk-ios#frameworks ?

**Comment by karthironald** [comment]
I think, i downloaded from [here](https://aws-amplify.github.io/docs/ios/manualsetup#frameworks-setup). Though, first i tried to install via cocoapod using `pod AWSTextract`. But I got below error,

> Unable to find a specification for `AWSTextract`

that's why i tried for manual integration. Please help me. 

Thanks!

**Comment by palpatim** [comment]
Thanks! The framework link at https://sdk-for-ios.amazonwebservices.com/latest/aws-ios-sdk.zip is now up-to-date with the Textract library. I'll investigate the Pods as well, although I'm able to see a pod for it: https://cocoapods.org/pods/AWSTextract

Be sure to do a `pod repo update` before attempting to install via CocoaPods.

**Comment by karthironald** [comment]
Will try and update you soon. Thanks for your help!

**Comment by lawmicha** [comment]
once we get documentation in, will be good to look reproducing the service issue that looks like it's not customer's fault: https://github.com/aws-amplify/aws-sdk-ios/issues/1838

**Comment by lawmicha** [comment]
This issue is quite old now and should be unblocked since the release of the AWSTextract SDK. For those that are coming here looking for API reference: https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSTextract/Classes/AWSTextract.html 

Amplify Predictions also provides this use case: https://docs.amplify.aws/lib/predictions/identify-text/q/platform/ios

**Comment by jp-dubey07** [comment]
Hi Team, I want to understand response format from AWS Textract. 

Suppose, if any document is scanned (say electricity bill) and data is uploaded to AWS Textract for processing then response would be in JSON (Format 1) or single string separated with special character (Format 2)?

And if it is in JSON format then response is meaningful? For eg. electricity bill has name, payable amount etc so response JSON should be in below format

**FORMAT 1:**
{
. . . 

"name" : "abdcdef",
"payable amount" : "1000"
. . .
}

I tried Google Cloud Vision which is giving response as JSON format but it is not meaningful (Format 2).

**FORMAT 2:**
{
. . .
"text" : "name\nabcdef\npayable amount\n1000"
. . . 
}
