### ISSUE TITLE
Uploading big enough files with multipart crashes the app due to memory issues 

### ISSUE THREAD

**Issue by TalDabush** [aws-amplify/aws-sdk-ios#1624]
Describe the bug
when upload starts, it consume very large amounts of memory, which causes the app to crash due to low memory 

To Reproduce
Upload a big file (mine was 800MB) using AWSTransferUtility

Which AWS service(s) are affected?
S3

Environment(please complete the following information):

AWS iOS SDK Version: 2.9.9
Dependency Manager: Cocoapods
Swift Version : 4.2
Device: any
iOS Version: any
Specific to simulators: NO

I saw that this bug already mentioned in other issues as fixed but I'm reproducing him even with smaller size files.

My code:
```swift
            let s3Handler = take.getS3Handler()

            let expression = AWSS3TransferUtilityMultiPartUploadExpression()

            expression.progressBlock = s3Handler.getProgressBlock()

            let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "ReporterS3TransferUtility")

                let request = transferUtility?.uploadUsingMultiPart(
                    data: data,
                    bucket: Utils.S3BucketName,
                    key: createS3FileNameAndPath(),
                    contentType: "video/mp4",
                    expression: expression,
                    completionHandler: s3Handler.getCompletionHandler()
                    ).continueWith(block: ){ (task) -> AnyObject? in

                        if let error = task.error {

                            NSLog("Error: %@",error.localizedDescription);
                        }

                        if let _ = task.result {

                            DispatchQueue.main.async {
                                .
                                .
                                .
                            }
                        }
                }
```

I was moving from regular upload to multipart upload and it helped a little but, the upload now consume about half of the memory than before. but its still huge amount of memory which causes many crashes to our users.
bellow you can see the instruments screenshot when the upload starts.

![image](https://user-images.githubusercontent.com/45621174/60279560-f1ae5400-9909-11e9-9125-8b98873d6d85.png)

before using multipart upload it consumed 1.66 GB (!)

Any help would be appreciated!
Thanks, Tal

**Comment by kvasukib** [comment]
@TalDabush Sorry for the inconvenience caused. We are looking into reproducing the issue.

When you say you could reproduce the issue with files of smaller file sizes, can you give an example of a file size where this issue occurs?

Do you have concurrent file transfers happening in the app? Or is this the only file transfer?

**Comment by TalDabush** [comment]
Hey @kvasukib, thank you for your answer.
The files I upload starts to crash the app from about 800 MB (I used iPhone XS to test it and it didn't crash because it has more available RAM but devices that I tried like iPhone 6S couldn't handle it.)

My problem is exactly this transient bumps in the `All Heap & Anonymous VM` category, 
they are so big that the device just couldn't handle it (As an example, when I'm trying to upload files with size of 400MB, the bumps are smaller, so the device handles it and indeed the bumps are transient).
bellow you can see the instruments screenshots, the AWSS3 doesn't consume very small amount of memory but there is huge amount of allocations.
The bump happens the moment I hit the upload button in my app- which executes the code in the comment above.
My guess (after reading posts with almost similar problems) is that the operation of cutting the files to small chunks consumes lot of memory - is it possible?

If any other information needed let me know.

Thank you!

![image](https://user-images.githubusercontent.com/45621174/60489831-f5e1c500-9cad-11e9-8e69-e1f2c495236c.png)

![image](https://user-images.githubusercontent.com/45621174/60489903-20cc1900-9cae-11e9-852e-6acb524113a9.png)

**Comment by TalDabush** [comment]
Hi,
any update?
I updated to 2.9.10 and things became even worse.
![image](https://user-images.githubusercontent.com/45621174/60768898-0b9e2280-a0d2-11e9-875d-4ceb0d924394.png)

The upload starts at 900MB and climbs to 1.69GB (with multipart)
Many users are affected because of it so I will really appreciate any response or update.

**Comment by TalDabush** [comment]
I moved to uploadFile instead of uploadData and the problem was solved.
