### ISSUE TITLE
Crash: reason 'The Pinpoint AppId is `nil`

### ISSUE THREAD

**Issue by vtamnh14** [aws-amplify/aws-sdk-ios#1625]
**Describe the bug**
Hi supporter,
I try to init AWSPinpointConfiguration by custom appId
But I still got a crash when starting the application.
This is my code: 
```swift
            let conf = AWSPinpointConfiguration(appId: pinpointId,
                                                launchOptions: launchOptions)
            pinpoint = AWSPinpoint(configuration: conf)
```
In my Info.plist file
I just added two fields: appId and PoolId

```swift
         <key>appId</key>
	<string>$(PINPOINT_ID)</string>
	<key>PoolId</key>
	<string>$(AMAZON_POOL_ID)</string>
```
How can I init AWSPinpointConfiguration doesn't by awsconfiguration.json file.

Thanks,

**Comment by kvasukib** [comment]
@vtamnh14 Thank you for reporting to us. You need to have a `AWSServiceConfiguration` object registered if you are not using `awsconfiguration.json` file.

```swift
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast2, identityPoolId: "XXXX")
        let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        let pinpointConfiguration = AWSPinpointConfiguration(appId: "YYYY", launchOptions: launchOptions)
        pinpoint = AWSPinpoint(configuration: pinpointConfiguration)
```

**Comment by rromanchuk** [comment]
@kvasukib so is Info.plist not a valid lookup location?  And if it is valid, can you publish the keys and datatype it expects? 

Maybe just get rid of this https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSPinpoint/AWSPinpointConfiguration.m#L88


ps `let pinpointConfiguration = AWSPinpointConfiguration(appId: "YYYY", launchOptions: launchOptions)` 

is a really annoying signature, `launchOptions` is not a configuration param, it's an initialization
