### ISSUE TITLE
Support for new Facebook SDK version 5.0 and greater

### ISSUE THREAD

**Issue by Machanna** [aws-amplify/aws-sdk-ios#1626]
Tried adding AWSFacebookSignIn(2.9.9) to my project using cocoapods. My project also has facebook sdks with 5.0 version. pod installation throws me an error, saying that AWSFacebookSignIn doesnot support Facebook SDKs > 4.42.0

**Comment by kvasukib** [comment]
@Machanna Thank you for bringing this to our attention. We will look into supporting the latest Facebook SDK version in the `AWSFacebookSignIn` SDK.

**Comment by royjit** [comment]
Closing as duplicate issue #1516
