### ISSUE TITLE
How to get HTTP Status in iOS AWS API gateway auto generated file.

### ISSUE THREAD

**Issue by manomuthu-optisol** [aws-amplify/aws-sdk-ios#1643]
Need to access http header status code to show user appropriate error message. In response I can able access error object and result object. 

Am using 'AWSAPIGateway', '~> 2.9.6' version 

Thanks in advance 

Regards,
Muthu

**Comment by royjit** [comment]
We have this tracked here issue #659. Please monitor #659 for updates. 
Will be closing this issue.
