### ISSUE TITLE
Information about user servers 

### ISSUE THREAD

**Issue by vvorlov** [aws-amplify/aws-sdk-ios#1644]
How to authorize users by the Amazon account in the app and get a token with access to users' servers info (e.g. EC2, Lightsail, etc.)? One way to get access for API calls like `GetInstances` is to ask Access keys, but it takes too many actions from the user. iOS app AWS Console (https://apps.apple.com/ru/app/aws-console/id580990573?l=en) has login by email, is it possible to integrate this flow to a third party app via OAuth or smth?

If I understand correctly User pools and Federated identities help to create own authentication process without access to actions on users' Amazon accounts.

**Comment by royjit** [comment]
Hi @vvorlov 

Thank you for contacting us. We do not support this use case in the aws iOS SDK. You can refer [here](https://aws-amplify.github.io/docs/ios/authentication) for the supported authentication mechanisms.

Thanks,
Jithin

**Comment by royjit** [comment]
Just wanted to clarify what you are trying to achieve.

1. Are you trying to let customer sign-in to your app using their Amazon account? 
This is currently supported with AWS iOS SDK using Cognito.

2. Are you trying to let customer sign-in to their AWS account and see a list of all of their resources?
This is not supported with our SDK.

- Jithin

**Comment by vvorlov** [comment]
The second one. Maybe it could be achieved with something else, not iOS SDK?

**Comment by palpatim** [comment]
Some Amazon billing applications allow customers to see a list of their resources in aggregate, but I'm not aware of any publicly exposed API that allows this.
