### ISSUE TITLE
AWSS3 v2.8.4 AWSS3TransferUtility.m line 423

### ISSUE THREAD

**Issue by ayushawasthi** [aws-amplify/aws-sdk-ios#1646]
**Describe the bug**
When using `AWSS3TransferUtility.register`, `(instancetype)initWithConfiguration(AWSServiceConfiguration *)serviceConfiguration transferUtilityConfiguration:(AWSS3TransferUtilityConfiguration*)transferUtilityConfiguration identifier:(NSString *)identifier completionHandler: (void (^)(NSError *_Nullable error)) completionHandler` gets called and when session configuration `timeoutIntervalForResource` is assigned `_transferUtilityConfiguration` is nil so no matter what value is provided in init parameter timeoutIntervalForResource is always zero. I guess this should be "`transferUtilityConfiguration`" instead of "`_transferUtilityConfiguration`" as "`_transferUtilityConfiguration`" is assigned below this code on line 452.

**To Reproduce**
1. Go to AWSS3TransferUtility.m
2. Scroll down to the line 423

**Which AWS service(s) are affected?**
AWSS3

**Expected behavior**
The value passed in init parameters for transferUtilityConfiguration should have been picked up for session configuration.

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: AWSS3 v2.8.4
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone6, Simulator
 - iOS Version: 12.2, 12.0
 - Specific to simulators: No

**Additional context**

**Comment by ayushawasthi** [comment]
![Screenshot](https://user-images.githubusercontent.com/5653624/61047966-479cf480-a3fe-11e9-918c-f0602a0aa023.png)

**Comment by lawmicha** [comment]
Hi @ayushawasthi 

Thanks for taking the time to report the issue. When you pass in `transferUtilityConfiguration` to the init function with `timeoutIntervalForResource` set, it will then be set on the configuration and then passed to the session.

```
configuration.timeoutIntervalForResource = transferUtilityConfiguration.timeoutIntervalForResource;
...
_session = [NSURLSession sessionWithConfiguration:configuration
                                                 delegate:self
                                            delegateQueue:nil];
```

Can you verify that it is working for you with a short timeoutIntervalForResource and try to download a large file to see that it times out quickly for your use case?

**Comment by ayushawasthi** [comment]
Yeah, actually the line you have written is the problem because you see in the code screenshot that I posted `transferUtilityConfiguration` ivar is used instead of parameter var. So even if I pass the correct value it won't update as at the time of assignment the value of `_transferUtilityConfiguration` is `nil`.
