### ISSUE TITLE
Sometimes getting error "A server with the specified hostname could not be found".

### ISSUE THREAD

**Issue by VikasPrajapatiSA** [aws-amplify/aws-sdk-ios#1655]
**Describe the bug**
Sometimes when I try to login with username and password then its gives me error "A server with the specified hostname could not be found".
I don't know this issue root cause.

Using the below method for sign in.

AWSMobileClient.sharedInstance().signIn(username: "your_username", password: "Abc@123!") { (signInResult, error) in
    if let error = error  {
        print("\(error.localizedDescription)")
    } else if let signInResult = signInResult {
        switch (signInResult.signInState) {
        case .signedIn:
            print("User is signed in.")
        case .smsMFA:
            print("SMS message sent to \(signInResult.codeDetails!.destination!)")
        default:
            print("Sign In needs info which is not et supported.")
        }
    }
}

Can you please help me to solve this issue?

**Comment by palpatim** [comment]
@VikasPrajapatiSA I'm not able to repro this in our sample app from my network. It sounds like it might be related to your network setup--perhaps you are testing in a poor network connectivity situation? Unfortunately, without more details, it's going to be hard to make any progress on this. If you can provide a small sample app, or identify some configurations that seem to cause this, we can investigate further.
