### ISSUE TITLE
User migration trigger

### ISSUE THREAD

**Issue by Thuran** [aws-amplify/aws-sdk-ios#1676]
**Which AWS Services is the feature request for?**
Cognito user pool

**Is your feature request related to a problem? Please describe.**
We can’t set migration enabled in AWSMobileClient.
In old ios-sdk i can set this in Pool configuration passing migrationEnabled=true:
```
AWSCognitoIdentityUserPoolConfiguration(clientId: CognitoIdentityUserPoolAppClientId,
                                                                        clientSecret: CognitoIdentityUserPoolAppClientSecret,
                                                                        poolId: CognitoIdentityUserPoolId,
                                                                        shouldProvideCognitoValidationData: true,
                                                                        pinpointAppId: nil,
                                                                        migrationEnabled: true)

```

**Describe the solution you'd like**
I need to be able to migrate my users from the old base. So I need to set this flag at the time of signin and forgot password;

**Comment by desokroshan** [comment]
We are tracking this in the [Authentication RFC](https://github.com/aws-amplify/aws-sdk-ios/issues/1158). Closing.
