### ISSUE TITLE
Can't import as Static library with Cocoapods

### ISSUE THREAD

**Issue by alexliuxe** [aws-amplify/aws-sdk-ios#1677]
**Describe the bug**
Import `AWSCognitoAuth` as static library instead of dynamic library from `Cocoapods` and the way I did was remove `use_frameworks!` from podfile. 

**To Reproduce**
1. In an empty project with Cocoapods, go to podfile. (Swift project)
2. remove this line if exists : `use_frameworks!`. Make sure you have this line as well `pod 'AWSCognitoAuth'`
3. Save and run pod install to update dependencies. 
4. In any swift file, add this on top `import AWSCognitoAuth`
5. Build the project and you will see this : `/CognitoStaticFramework/ViewController.swift:11:8: No such module 'AWSCognitoAuth'`

**Which AWS service(s) are affected?**

AWSCognitoAuth

**Expected behavior**

Should be able to compile it as same was dynamic framework which means with `use_frameworks!` in podfile. 

**Environment(please complete the following information):**
 - SDK Version: iOS 12
 - Dependency Manager: Cocoapods 1.6.2
 - Swift Version : 5.0

**Comment by palpatim** [comment]
@alexliuxe It's a bit unusual to be importing CognitoAuth; our auth functionality tends to be exposed through AWSMobileClient or AWSCore. What is your use case for importing CognitoAuth?

That said, I do confirm the unexpected behavior suppressing `use_frameworks!` even in AWSCore, so this is something we'll need to investigate.

**Comment by MattFoley** [comment]
I currently ship a large (million user plus), dynamic framework, that uses AWS heavily. Previously we built and included static libraries directly, but as far as I can tell, AWS Amplify is only meant to be shipped as a dynamic framework. Does any documentation exist as far as including the raw source code, or static library versions of AWS?

**Comment by palpatim** [comment]
@MattFoley 

I'm not aware of such documentation, and as you note, the projects are set up to be built as Dynamic Library. It's been quite a while since I've worked with static libraries, and unfortunately never had to worry about converting back and forth, so I don't have any advice for you. If you are able to figure this out, we'd welcome a PR against our [`README`](https://github.com/aws-amplify/aws-sdk-ios/blob/master/README.md) file to add those instructions for other developers who may have a similar requirement.

**Comment by MattFoley** [comment]
Hey @palpatim, you’d likely want to setup your Xcode project to have both static and dynamic targets for each library. It can take awhile to set that up. For now, we’ll likely include the source directly, and tweak the imports to work with that. It’s not often that frameworks use other frameworks, so I understand not having a solution already built! If you’re curious, Lottie might be a good example, I believe their project is setup to create both Static and Dynamic outputs.

**Comment by palpatim** [comment]
@MattFoley 

Thanks for the pointer. At this point, we haven't heard a lot of customer requests for supporting static library builds from source, so I'm going to close this so it stays focused on the issue of building static via CocoaPods.

If you feel building static from source would be generally useful, please feel free to open a new feature request that we can add to the backlog.
