### ISSUE TITLE
License clarification for AWSCognitoIdentityProvider pod

### ISSUE THREAD

**Issue by cbryantryback** [aws-amplify/aws-sdk-ios#1684]
All code in this SDK appears to have been relicensed as Apache 2.0 via #1517, except for AWSCognitoIdentityProvider.podspec which was later changed back via #1559. Was the licensing of this particular pod with the Amazon Software License intentional?

**Environment:**
 - SDK Version: 2.9.9 (also applies to 2.10.0)
 - Dependency Manager: Cocoapods

**Comment by palpatim** [comment]
@cbryantryback That reversion was unintentional. Thanks for catching that, and sorry for the confusion. We'll fix that on the next release.

**Comment by palpatim** [comment]
This is released in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.10.1
