### ISSUE TITLE
ifModifiedSince in AWSS3HeadObjectRequest does not work

### ISSUE THREAD

**Issue by odaeagle** [aws-amplify/aws-sdk-ios#1689]
We are trying to retrieve a file only when it is last modified after a specific date, the code roughly look like this

let request = AWSS3HeadObjectRequest()
request?.bucket = "SOME_BUCKET"
request?.key = "SOME_KEY"
request?.ifModifiedSince = date1
request?.ifUnmodifiedSince = date2

let s3 = AWSS3.default()
        s3.headObject(request!).continueWith { (task) -> AnyObject? in
            if let error = task.error {
               // error

            } else {
               // success
            }
            return "" as AnyObject
        }

however, whatever what ifModifedSince time 'date1' we are using, the request always finish without error, ifUnmodifedSince does work

and in the response, 

lastModified = "2019-07-26 01:39:53 +0000";

it also looks right

is there any special setting we missed?

tried both version 2.9.7 and 2.10

**Comment by royjit** [comment]
Hi @odaeagle 

Apologies for the delayed response.

Are you seeing any error in the logs? 
From what I understand, you are not getting back any result if you specify `ifModifiedSince`?

The SDK just calls the `headObject` api here passing your values and it should work as expected.
Few questions:
1. Are you setting both `ifModifiedSince` and `ifUnmodifiedSince` on make a request?
2. What is the date format you are specifying? Can you provide an example?
