### ISSUE TITLE
Multiple presigned URL generation takes a long time

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-ios#1691]
Customer reports:

**Steps to reproduce**

**Preparation**
- Create Single View App (Objc)
- pod install AWSS3 2.9.3
- amplify init
- amplify add storage
- amplify push
- open [ProjectName].xcworkspace
- enable KeychainSharing
- Implement AppDelegate & ViewController as attached

**AppDelegate**

```objective-c
    AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1
                                                                                                    identityPoolId:@"my-identity-pool-id"];
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1
                                                                         credentialsProvider:credentialsProvider];
    AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;
```

**ViewController**
```objective-c
- (void)getPreSignedURL {
    NSLog(@"i=0: %@", [NSDate date]);
    NSString *bucket = @"some-test-bucket";
    NSMutableArray *arr = [NSMutableArray array];
    for (int i=0; i < 1000; i++) {
        NSUUID *uuid = [NSUUID UUID];
        NSString *key = [NSString stringWithFormat:@"testkey%@", uuid.UUIDString];
        AWSS3GetPreSignedURLRequest *getPreSignedURLRequest = [AWSS3GetPreSignedURLRequest new];
        getPreSignedURLRequest.bucket = bucket;
        getPreSignedURLRequest.key = key;
        getPreSignedURLRequest.expires = [NSDate dateWithTimeIntervalSinceNow:3600];
        getPreSignedURLRequest.HTTPMethod = AWSHTTPMethodGET;
        [[[AWSS3PreSignedURLBuilder defaultS3PreSignedURLBuilder] getPreSignedURL:getPreSignedURLRequest]
         continueWithBlock:^id(AWSTask *task) {
             if (task.error) {
                 NSLog(@"Error: %@",task.error);
             } else {
                 NSURL *presignedURL = task.result;
                 [arr addObject:presignedURL.path];
             }
             if (i == 999) {
                 NSLog(@"i=999: %@", [arr description]);
             }
             return nil;
         }];
    }
}
```

**Execution**

1. Run App: It takes only few seconds to finished generate 1000 pre-signed URLs.
2. Stop and Re-Run App again: It takes two or three minutes to finished generate 1000 pre-signed URLs.
3. Stop App then Wait about an hour
4. Run App again: It takes only few seconds to finished generate 1000 pre-signed URLs.
5. Stop and Re-Run App again: It takes two or three minutes to finished generate 1000 pre-signed URLs.

**Comment by palpatim** [comment]
Seems to be related to #1554--that fix resolves this behavior as well.

**Comment by palpatim** [comment]
Also possibly related to #1549, which reports a regression of #1188 (which was originally fixed in #1192).

**Comment by phanchutoan** [comment]
@palpatim. Fixing may be incomplete. As the credential still expire.
https://github.com/aws-amplify/aws-sdk-ios/issues/1554#issuecomment-514425999

**Comment by phanchutoan** [comment]
Any update for this?

**Comment by palpatim** [comment]
## Background

There are two basic issues here:

1. Depending on the timing of the initial invocation, all but one of the requests may fail
1. Subsequent to at least one successful call to retrieve credentials, calls do not read the credentials from memory, but instead read from the keychain each time, as reported in #1554. For a network call, this amounts to a latency on the order of 10ms for a single request, but for an operation like generating a batch of presigned URLs locally, this can significantly delay the execution time of the batch.

## Discussion

Regarding issue 1: The code is behaving as designed: in a case where multiple simultaneous requests for any operation that needs credentials is called (which this does, as PresignedURLBuilder relies on credentials as part of its workflow), the first one to hit initiates the network request, and subsequent ones are queued with a 5 second timeout behind it. If the initial request succeeds in under 5 seconds, then all requests will succeed with the cached credentials. If the initial request fails, or takes longer than 5 seconds, then all subsequent requests will fail with an error message:

```
2019-09-04 12:46:33:027 PresignedURLTest[57372:1536951] Unable to refresh. Error is [Error Domain=com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper Code=0 "Obtaining an identity id in another thread failed or didn't complete within 5 seconds." UserInfo={NSLocalizedDescription=Obtaining an identity id in another thread failed or didn't complete within 5 seconds.}]
```

After one request has succeeded, subsequent requests will use the cached credentials, and appear to behave as expected (as evidenced by the "After initial run" results above: 1000 successes, no failures, ~18s elapsed time).

The "initial test" condition is the same whether the app has never run, or whether the app has sat idle for longer than one hour, after which the refresh token would have expired. In either of those cases, there are not fresh credentials available in the keychain, so the SDK makes a "get credentials" call.

**Initial Test Results**
Initial install: 1 success, 999 failures, 5.74s
App restart after initial run : 1000 success, 0 failures, 18.54s

(All test results are run on a simulator on my laptop, so would likely be faster than all but the most recent iDevices with a speedy network connection.)

## Solution for issue 1: Preemptively retrieve credentials

The workaround to prevent failures for multiple simultaneous operations when fresh credentials are not available would be to ensure that credentials are valid before starting any large batch operations. That is: do something like this modification to the above sample code:

**ViewController.m*
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^(void) {
        [[[[[AWSS3 defaultS3] configuration] credentialsProvider] credentials] waitUntilFinished];
        [self getPreSignedURL];
    });
}

- (void)getPreSignedURL {
    // as before
}
```

Note that we dispatch the credentials refresh onto a background thread--calling `waitUntilFinished` on the main thread is a bad idea.

Doing that "preemptive" credential refresh drastically improves performance even of the success case, since the system isn't having to manage 100s or 1000s of in-flight tasks:

**2.10.3 with preemptive credential fetch:**
Initial install: 1000 success, 0 failures, 1.33s
App restart after initial run : 1000 success, 0 failures, 18.56s

**Conclusion**: The preemptive fetch solves the problem of multiple failures in the initial case, and improves performance of that initial case.

## Solution for issue 2: Store credentials in-memory after retrieving from keychain

We expect that the 18s elapsed time would be greatly improved by caching the internal credentials as suggested in #1554 and implemented in #1678, and in fact that is validated by tests that apply the fix locally:

**2.10.3 with preemptive credential fetch, and patch from #1678 
Initial install: 1000 success, 0 failures, 1.58s
App restart after initial run : 1000 success, 0 failures, 0.71s

So once I validate #1678 and can ensure that we aren't causing a data race by setting the internal credentials from multiple threads, we should have a fix for this issue.

I will update this issue once I have more detail.

**Comment by palpatim** [comment]
#1678 does appear to fix the issue, and we have a fix pending the next release. No firm ETA on it, but we're actively working on resolving the last blocking issues.

**Comment by palpatim** [comment]
We released this in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0

Please let us know if you have any problems with this feature.

**Comment by phanchutoan** [comment]
@palpatim 
May I ask how long a credentials live, as I tried to debug into the SDK, It seem that the credential will live for 1 hour. But actually. It often die after 10~15 minutes.

Are there any method we can use to check if a credential is still alive or not?

I am using it to make a collection view showing many image.
