### ISSUE TITLE
AVURLAsset stream url for S3 stored video file

### ISSUE THREAD

**Issue by borisdering** [aws-amplify/aws-sdk-ios#1698]
**State your question**
Is there a way to get the class AVURLAsset imported from AVFoundation / AVKit to work with AWSS3? Maybe by setting request headers like in the attached example.
Currently, I'm able to download or upload files to or from S3 but not able to assign the URL due to unauthorized response which is fine, but I would like to use the predefined class in a UICollectionView and not manually download each video file or video part for local usage. I'm also familiar with the possibility of pre-signed URLs, but this can not be a solution due to the expiration time constraint of 50 minutes or so and heavy lifting on both ends. 

**Which AWS Services are you utilizing?**
AWSMobileClient, AWSAppSync, AWSS3.

**Provide code snippets (if applicable)**
```
let dateFormatter = DateFormatter()
dateFormatter.dateFormat = "YYYYMMDD'T'HHMMSS'Z'"

let headers = [
   "Authorization": "AWS \(AWSAccessKeyId):AWSSecretAccessKey",
   "x-amz-date": dateFormatter.string(from: Date())
]
let asset = AVURLAsset(url: URL(string: "xxx")!, options: [
   "AVURLAssetHTTPHeaderFieldsKey": headers
])
```
In this case, I still receiving an HTTP status 403 (forbidden) as a response.
Even extracted in a playground I have issues to access the file as shown in the example below.

````
import Foundation

var str = "Hello, playground"

let dateFormatter = DateFormatter()
dateFormatter.dateFormat = "YYYYMMDD'T'HHMMSS'Z'"
print(dateFormatter.string(from: Date()))

let session = URLSession(configuration: URLSessionConfiguration.default)
let url = URL(string: "https://_xxx_.s3-accelerate.amazonaws.com/__bucket__/__key__")!
var request = URLRequest(url: url)
request.httpMethod = "get"
request.addValue("AWS keyID:KeyIDSecret", forHTTPHeaderField: "Authorization")
request.addValue(dateFormatter.string(from: Date()), forHTTPHeaderField: "x-amz-date")
let task = session.downloadTask(with: request) { (url, response, error) in
    guard error == nil else {
        print(error)
        return
    }
    
    print((response as! HTTPURLResponse).statusCode)
}

task.resume()

````
**Environment(please complete the following information):**
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Comment by palpatim** [comment]
We've had some internal discussions about some utilities/wrappers to make it easier to work with Asset classes inside of TransferUtility, but haven't gotten very far with our thinking. In the meantime, you might explore the [AWSS3PresignedURLBuilder](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/Classes/AWSS3PreSignedURLBuilder.html) to see if that would help with your use case.
