### ISSUE TITLE
Sign in callback invoked before all sign in operations are complete

### ISSUE THREAD

**Issue by royjit** [aws-amplify/aws-sdk-ios#1700]
**Describe the bug**
Callback for sign is called before the actual status is set internally.

**To Reproduce**
We call self.performUserPoolSuccessfulSignInTasks and then calls completionHandler without waiting for the first task to complete.
https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift#L480
i) Inside self.performUserPoolSuccessfulSignInTasks we call ‘mobileClientStatusChanged’
ii) After that we remove keychain values and update with new ones
iii) After that we call the two lines below
self.internalCredentialsProvider?.clearCredentials()
self.internalCredentialsProvider?.credentials()

This means that if we rely on AWSMobileClient.sharedInstance().addUserStateListener, and perform task based on the status. It will be wrong.

**Comment by royjit** [comment]
PR for the fix - https://github.com/aws-amplify/aws-sdk-ios/pull/1721/

**Comment by Foefirelord** [comment]
So would this be why using `getIdentityId()` or invoking a Lambda based on `addUserStateListener`'s `.signedIn` state fails for a certain period of time but then suddenly starts succeeding?

Any ETA on when this will be fixed?

**Comment by palpatim** [comment]
No ETA yet but we are actively working on it.

**Comment by royjit** [comment]
PR #1721 approved and pushed to develop branch.

**Comment by royjit** [comment]
Had to revert the PR since we found another callback which was invoked before signIn completes. This is caused by [`currentSignInHandlerCallback`](https://github.com/aws-amplify/aws-sdk-ios/blob/abba0bf6c4895b92077484adceaa1e9fb996670c/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift#L916) which is called in `getTokens` method during signIn.

**Comment by royjit** [comment]
This should be solved in the [PR #1822](https://github.com/aws-amplify/aws-sdk-ios/pull/1822).

**Comment by palpatim** [comment]
We released this in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0

Please let us know if you have any problems with this.
