### ISSUE TITLE
Help!!!!  Swift demo error

### ISSUE THREAD

**Issue by Lewanny** [aws-amplify/aws-sdk-ios#1703]
hi teams,
i download the demo at https://github.com/awslabs/aws-sdk-ios-samples/tree/master/Lex-Sample/Swift.

and change my configure like that:
{
    "Version": "1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-west-2:64ec6961-c504-4622-86a2-d70fb05cb56a",
                "Region": "us-west-2"
            }
        }
    }
}

let LexRegion = AWSRegionType.USWest2                       // Change this is this is not your Lex region (most are currently AWSRegionType.USEast1)
let BotName = "testScheduleAppointment"                                     // Put your bot name here
let BotAlias = "$LATEST"                                    // You can leave this if you always want to use

but it did not work, the error is：
error Error Domain=com.amazonaws.AWSLexErrorDomain Code=0 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=AccessDeniedException:http://internal.amazon.com/coral/com.amazon.coral.service/}

thanks for helping me.

**Comment by palpatim** [comment]
@Lewanny 

Please also note that the setting up the sample requires a number of other [steps](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/Lex-Sample/Swift) including role and policy setups, as well as setting up and publishing the bot itself. Having run through the demo myself several times, I sympathize that it be a bit tedious to set up for the first time, but I've successfully set it up from scratch following those instructions.

Your error implies that something in the permissions is not correctly configured--possibly along the path from IdentityPool -> Role -> `AmazonLexRunBotsOnly` Policy. I recommend starting your investigation there.

**Comment by Lewanny** [comment]
@palpatim  
Thank you. I solved this problem with the method you provided.

**Comment by yourPresents** [comment]
hi,
i integrated AWSLex on mobile platforms android and iOS, and I found that AWSLex provided a way to record. But I want to record with my smart device, can this be done? If it can be done, what I need to do with the audio. Thanks for your reply.
