### ISSUE TITLE
AWS transcribe model training

### ISSUE THREAD

**Issue by temitopefunmi** [aws-amplify/aws-sdk-ios#1706]
Are there options to train aws transcribe models for dialects, accents, e.t.c? For instance, using datasets containing audio and human labeled transcriptions.

**Comment by palpatim** [comment]
@temitopefunmi 

We on the SDK team don't have deep knowledge of the Transcribe service beyond what APIs are available in the SDK itself. Please try asking your question on the [Transcribe AWS forum](https://forums.aws.amazon.com/forum.jspa?forumID=278) to see if someone there can provide an answer.

If I'm misunderstanding your question and you're asking about an SDK feature, please provide more context so we can investigate further.

**Comment by temitopefunmi** [comment]
Okay. Thanks
