### ISSUE TITLE
The AWSLex problem: recording with smart devices

### ISSUE THREAD

**Issue by yourPresents** [aws-amplify/aws-sdk-ios#1710]
hi,
i integrated AWSLex on mobile platforms android and iOS, and I found that AWSLex provided a way to record. But I want to record with my smart device, can this be done? If it can be done, what I need to do with the audio. Thanks for your reply.

**Comment by palpatim** [comment]
The Lex SDK is intended to send audio to the Lex service for bot-driven interactions. If you wish to record audio on the device, I'd advise you to look at a different solution. If I'm misunderstanding your question, please provide more detail.

**Comment by yourPresents** [comment]
@palpatim
Thank you for your reply. i want to record audio on the device, and send audio streams to mobile phones.  Then send audio received to the Lex service for bot-driven interactions through mobile devices. I wonder if this solution can be achieved with Lex SDK, thanks.

**Comment by palpatim** [comment]
@yourPresents No, there is no facility for doing that via the Lex SDK.
