### ISSUE TITLE
New password required state not propagated to drop-in UI

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-ios#1711]
**Describe the bug**

- Create a user from the Admin console
- Attempt to sign in as that user

**Expected behavior**

- Drop in UI presents the user with a password change screen

**Additional context**

There are a couple of underlying issues:

1. There appears to be no UI for handling the `FORCE_CHANGE_PASSWORD` state
1. We are not properly propagating errors for the `FORCE_CHANGE_PASSWORD` when using Drop in UI

`- (AWSTask<AWSCognitoIdentityUserSession*>*) startNewPasswordRequiredUI:(AWSCognitoIdentityProviderRespondToAuthChallengeResponse*) lastChallenge return AWSTaskWithError`

This task goes back till this line https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSAuthSDK/Sources/AWSUserPoolsSignIn/AWSCognitoUserPoolsSignInProvider.m#L120

Here it just checks for successtasks so does not uses the error.

The last place I could see an error is handled is here - https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L579

**Comment by royjit** [comment]
PR created - https://github.com/aws-amplify/aws-sdk-ios/pull/1943

**Comment by palpatim** [comment]
This was released in [2.12.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.12.0)
