### ISSUE TITLE
Storing Token on another Local Database such as Realm

### ISSUE THREAD

**Issue by jaelee1993** [aws-amplify/aws-sdk-ios#1723]
**State your question**
What is best practice?
**_Options_**
1) Storing id_token and access_token into a separate database such as Realm/CoreData and using it from there.
-or- 
2) Just use the **AWSMobileClient.sharedInstance().getTokens**  api when I need to use a token.

**Which AWS Services are you utilizing?**
AWSMobileClient
AWS Cognito 

**Provide code snippets (if applicable)**
`AWSMobileClient.sharedInstance().getTokens { (tokens, error) in
            if let error = error {
                print("Error getting token \(error.localizedDescription)")
            } else if let tokens = tokens {
                print(tokens.idToken!.tokenString!)
//                URLSession call with token
            }
        }`

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
      **AWS SDK for iOS 2.10.2**
 - Dependency Manager: [e.g. Cocoapods, Carthage]
     Carthage
 - Swift Version : [e.g. 4.0]
     5.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
       all
 - iOS Version: [e.g. iOS 11.4]
       12
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by royjit** [comment]
I would recommend to use `AWSMobileClient.sharedInstance().getTokens` since it handles refreshing the token or informing if signIn is required etc. You can find details in the [iOS amplify documentation](https://aws-amplify.github.io/docs/ios/authentication#managing-security-tokens)

**Comment by jaelee1993** [comment]
Thank you for your response @royjit. So does AWS check the validation of the token using the expiration date internally or does it make another network request to AWS servers?

**Comment by royjit** [comment]
It checks the validation internally and makes network request if the the token is expired.

**Comment by jaelee1993** [comment]
@royjit Awesome, thank you for the help!
