### ISSUE TITLE
AWSCognitoAuth logout not clearing tokens

### ISSUE THREAD

**Issue by dpachecols** [aws-amplify/aws-sdk-ios#1724]
I am using AWSCognitoAuth to login and logout but when I logout the user is stays alive, it seems as if it does not erase the session globally. 
Login:

````
     AWSCognitoAuth.default().getSession  { (session:AWSCognitoAuthUserSession?, 
     error:Error?) in
            if(error != nil) {
                self.error()
                self.session = nil
            }else{
                self.session = session
            }
        }
````
Logout:
````
        AWSCognitoAuth.default().signOut { (error:Error?) in
            if(error != nil){
                self.alertWithTitle("Ups", message: (error! as NSError).userInfo["error"] as? String)
            }else {
                let secItemClasses =  [kSecClassGenericPassword, kSecClassInternetPassword, kSecClassCertificate, kSecClassKey, kSecClassIdentity]
                for itemClass in secItemClasses {
                    let spec: NSDictionary = [kSecClass: itemClass]
                    SecItemDelete(spec)
                }
                session?.
                AWSCognitoAuth.default().signOutLocallyAndClearLastKnownUser()
            }
         }
````

After I logout and login again the web page do not ask me for my credentials again it pass automatically, I want that cognito ask me my credentials again. I also try to clear the keychains but didn't not work.
 
Pod file:
`pod 'AWSCognitoAuth', '~> 2.8.0'`

**Comment by royjit** [comment]
Hi @dpachecols Thank you for reaching out. Could you please provide us some information about your setup.
1. What identity provider are you using?
2. When you call signOut, does it shows a webpage?

**Comment by dpachecols** [comment]
Hi @royjit thank you for taking my request. 
1.-  Is a SAML external provider, Microsoft ADFS, SAML 2.0
2.- Yes, it redirect to safari web page but the page is always blank and then redirect back to the app. After the singOut, the user state changes successfully to logged out but then when I try to login again the redirect page does not ask for the user, it automatically login with the past user.

**Comment by kwylez** [comment]
@dpachecols I'm experiencing a very similar problem. Did you ever find a fix?
