### ISSUE TITLE
Wrong confirmation code returns unexpected error

### ISSUE THREAD

**Issue by Chesong-Lee-Hospii** [aws-amplify/aws-sdk-ios#1732]
**Describe the bug**
When calling `AWSMobileClient.sharedInstance().confirmForgotPassword(...)` and inserting the wrong `confirmationCode` the error I get is `userNotFound(message: "Username/client id combination not found.")`. I would expect the error to return `securityFailed`

**To Reproduce**
1. Call `AWSMobileClient.sharedInstance().forgotPassword(...)` with an existing `username`
2. Then call `AWSMobileClient.sharedInstance().confirmForgotPassword(...)` with the same `username` as step 1, with a password meeting the requirements, but with the wrong `confirmationCode`
3. Error returns `userNotFound(message: "Username/client id combination not found.")`
4. I would expect `securityFailed` or something similar. I would expect `userNotFound` error to return if I entered a non-existing `username`

**Which AWS service(s) are affected?**
`AWSMobileClient`

**Expected behavior**
I would expect `securityFailed` or something similar. I would expect `userNotFound` error to return if I entered a non-existing `username`

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.10.2
 - Dependency Manager: Cocoapod
 - Swift Version : 4.2

**Additional context**
I may be in the wrong here because the error message does say `Username/client id` combination is not correct.

**Comment by palpatim** [comment]
@Chesong-Lee-Hospii Thanks for reporting this. We'll need to investigate to see if this behavior is intentional or not.

**Comment by lawmicha** [comment]
I was able to get 
`codeMismatch(message: "Invalid verification code provided, please try again.")`

can you confirm you are using the existing username?
