### ISSUE TITLE
Hosted UI sign in fails with AWSCognitoAuthErrorDomain error -7000 when previous hosted sign in user is deleted

### ISSUE THREAD

**Issue by garrettfritz** [aws-amplify/aws-sdk-ios#1737]
**Describe the bug**
I have hosted ui sign in working fine in my application, logging out and re-logging in all works as expected.  The problem comes when the user is deleted.  My delete flow goes like this:

0) user signs in with hosted ui (facebook)
1) iOS app signals back end to delete user
2) back end deletes cognito user with javascript:

`let AWS = require('aws-sdk');

	AWS.config.update(awsConfig);

	let CognitoIdentityServiceProvider = AWS.CognitoIdentityServiceProvider;
	let client = new CognitoIdentityServiceProvider({ apiVersion: '2016-04-19', region: 'us-east-1' });

	var params = {
		UserPoolId: cognito.userPoolId,
		Username: username
	};
	return new Promise((resolve, reject) => {

		client.adminDeleteUser(params, function (err, data) {

			if (err) {
				console.log(err, err.stack);// an error occurred
				resolve(err)
			} else {
				console.log(data); // successful response
				resolve(data)
			}

		});
	})`

3) iOS client logs out of AWSMobbileSDK with:

` AWSMobileClient.sharedInstance().signOut()`

4) User attempts to create an account using the same sign in method (facebook in this case) with: 

` AWSMobileClient.sharedInstance().showSignIn()` 

5) Result: The hosted ui webview appears briefly and immediately dismisses (as though it is trying to use a cached session or something) and returns with the error:
`The operation couldn’t be completed. (com.amazon.cognito.AWSCognitoAuthErrorDomain error -7000.)`

---------

Note: if I sign in with a different hosted ui provider (like google or Amazon) it works fine.  And if I subsequently log out of that other provider, facebook login resumes working again.

Please let me know what your thoughts are.

Thanks,

~G

**Comment by garrettfritz** [comment]
So i have an odd work around that ends up making it work, but it is not ideal....

if I call 

`  AWSCognitoAuth.default().signOut(self.navigationController!) { (error) in }`

before re-attempting to login with the same provider that was deleted, it will then succeed.  (note: I had to set EnableSFAuthenticationSesssion = YES in my info.plist in order for that to actually work as well....

This is not ideal because it prompts that permission dialog twice on sign in, but hopefully helps you identify where the problem may be...?

~G

**Comment by royjit** [comment]
I am hoping that this PR fixes the issue - https://github.com/aws-amplify/aws-sdk-ios/pull/3565 . This will be available in the next release. In the mean time would it be possible for you to test this change by directly pointing to the main branch?

**Comment by royjit** [comment]
The bug fix is released in the latest version of AWS iOS SDK - https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.24.2
