### ISSUE TITLE
Using AWS Amplify for Mobile App authentication

### ISSUE THREAD

**Issue by sindhugudivada** [aws-amplify/aws-sdk-ios#1739]
I like to use Amplify for a Mobile app for authentication(social and general) as well.   I'm planning to build my backend (REST API) with Django/Flask.  So, when the user submits login in my app, I do I share the fact that he is successfully logged in user and infact he can use all the Django REST APIs. **Is there a Amplify App ID that I need to provide to my REST APIs and is there a Python wrapper that I need to use with Django which will ask whether the Cognito/AWS servers whether the candidate is legal (based on JWT Token or something)** Please advise.

**Comment by palpatim** [comment]
It sounds like what you want to do is solved by [Cognito Resource Servers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-define-resource-servers.html), where you would use Cognito to authenticate using an OAuth 2.0 flow, and then use the resource server to control access to your application resources. Please review those docs and see if that matches your requirements. If not, you'll need to ask for more detail from the Cognito team on the [AWS Cognito Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).
