### ISSUE TITLE
Retrieving Cognito Identity ID using credentialsProvider vs AWSMobileClient

### ISSUE THREAD

**Issue by sykhan88** [aws-amplify/aws-sdk-ios#1773]
**Why am I successfully getting getting Cognito ID when I use getIdentityID from credentials provider but get an error when using AWSMobileClient?**
I have setup a Federated Identity with a custom developer provider. I am initializing the Amazon Cognito credentials provider using the code snippet generated by the Amazon Cognito console.  
```swift
let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: "IDENTITY_POOL_ID")
let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialsProvider)
AWSServiceManager.default().defaultServiceConfiguration = configuration
```
Following this, I am retrieving the cognito Identity ID using the following:
```swift
credentialsProvider.getIdentityId().continueWith(block: { (task) -> AnyObject? in
    if (task.error != nil) {
        print("Error: " + task.error!.localizedDescription)
    }
    else {
        // the task result will contain the identity id
        let cognitoId = task.result!
        print("Cognito id: \(cognitoId)")
    }
    return task;
})
```
When I run this, I successfully retrieve the identity ID, and I can also view it as an unauthenticated user on my console for the federated identity. However, when I try retrieving the identity ID using AWSMobileClient as follows:
```swift
AWSMobileClient.sharedInstance().initialize { (userState, error) in
            if let userState = userState {
                print("UserState (AccountView): \(userState.rawValue)")
            } else if let error = error {
                print("error: \(error.localizedDescription)")
            }
        }
        
        // Retrieve your Amazon Cognito ID
AWSMobileClient.sharedInstance().getIdentityId().continueWith { task in
                    if let error = task.error {
                        print("error: \(error.localizedDescription) \((error as NSError).userInfo)")
                        print(error)
                    }
                    if let result = task.result {
                        print("identity id: \(result)")
                    }
                    return nil
                }
```
I get AWSMobileClient  error 30 : **error: cognitoIdentityPoolNotConfigured(message: "Cannot get identityId since cognito credentials configuration is not available.")**

Why is this? What am I missing?

I am using **AWSMobileClient, AWSCore**

**Environment(please complete the following information):**
 - SDK Version: 'AWSMobileClient', '~> 2.10.0',  'AWSCore', '~> 2.10.0'
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0
 - Xcode Version: 10.3 

**Device Information (please complete the following information):**
 - Device: MacOS 10.14.5
 - iOS 12.4

**Comment by royjit** [comment]
Hi, thank you for reaching out. Do you have `awsconfiguration.json` in your project? The above error occurs when AWSMobileClient doesnot have a valid credentialProvider.

**Comment by sykhan88** [comment]
Hi, I do have an awsconfiguration.json in my project which looks like the following:  
```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    }
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "eu-west-1:xxxxx",
                "Region": "eu-west-1"
            }
        }
    }
}
```
A blank awsconfiguration.json file was created when i initialised amplify. Then i manually added the CredentialsProvider section as seen above where xxxx is part of my pool id from the console. i have added the .json file to my iOS project. Am i missing anything in my awsconfiguration file?

**Comment by royjit** [comment]
Did you override ` AWSInfo.defaultAWSInfo.defaultCognitoCredentialsProvider` to some value?  Make sure that `AWSMobileClient.sharedInstance().initialize` is the first thing you do in your app, so that all configurations are setup correctly.

Also, can you check if `AWSInfo.defaultAWSInfo.defaultCognitoCredentialsProvider` is not nil after initializing AWSMobileClient.

**Comment by sykhan88** [comment]
All the code that i have put in above to describe the issue is in my AppDelagate.swift. That is all the code i currently have in my AppDelegate. I haven't overridden ```AWSInfo.defaultAWSInfo.defaultCognitoCredentialsProvider``` to some value. Since I am calling ``` AWSMobileClient.sharedInstance().initialize``` in my AppDelagate, is it early enough?  

 I am however calling the ```AWSMobileClient.sharedInstance().getIdentityId().continueWith ``` right after initialising. Is it possible that this is being called before the AWSMobileClient is fully initialised and hence not returning the identity?

I tried checking ```AWSInfo.defaultAWSInfo.defaultCognitoCredentialsProvider```. A few issues: 
- defaultAWSInfo is a method and so i am forced to add ```()``` to it. 
- After which, swift complains that ```defaultAWSinfo()``` has been changed to ```default()```
- After which, swift complains that ```Value of type 'AWSInfo' has no member 'defaultCognitoCredentialsProvider' ``` 

Can you please guide me on how to use ```AWSInfo.defaultAWSInfo.defaultCognitoCredentialsProvider``` in code

**Comment by royjit** [comment]
Hi @sykhan88 

I configured a sample app with the same configuration as yours and tried to get identityId and it worked. Here are the steps I followed:

Configuration file

```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "xx",
                "Region": "xx"
            }
        }
    }
}
```

In my AppDelegate I have this:

```
AWSMobileClient.default().initialize { (userState, error) in
       ....  
 }
```

And in my viewcontroller:

```
AWSMobileClient.default().getIdentityId().continueWith { (task) -> Any? in
          // Receive identity id       
 }
```
Make sure to clean build the simulator/device. Let me know if you are still facing the issue

**Comment by royjit** [comment]
Also checking `AWSInfo.defaultAWSInfo.defaultCognitoCredentialsProvider` needs some debugging into the SDK. But if you follow the steps like I mentioned above you `defaultCognitoCredentialsProvider` should be initialized for you.
