### ISSUE TITLE
Support federated "Sign In With Apple"

### ISSUE THREAD

**Issue by cornr** [aws-amplify/aws-sdk-ios#1809]
**Which AWS Services is the feature request for?**
AWS SDK iOS, Cognito

**Is your feature request related to a problem? Please describe.**
We are offering Federated Sign In via `AWSGoogleSignInProvider` and `AWSFacebookSignInProvider`. Later this year Apple will force us to support "Sign in with Apple"  see https://developer.apple.com/news/?id=06032019j

**Describe the solution you'd like**
We would like to see something like an `AWSAppleIDSignInProvider`

**Describe alternatives you've considered**
Can't see an alternative to AWS Amplify supporting "Sign in with Apple" on iOS, Android and Web.

**Additional context**
https://developer.apple.com/sign-in-with-apple/

See also feature request for amplify-js: https://github.com/aws-amplify/amplify-js/issues/3395

**Comment by palpatim** [comment]
We'll update this thread once we have word back from the service team on this feature.

**Comment by devlogin** [comment]
Thanks for opening this issue cornr.  We are in need of supporting this going forward.   We are eagerly waiting for an update on this issue as we cannot release our product (and still use AWS cognito) without Cognitor supporting this feature.

**Comment by Mahaswami** [comment]
We too are stuck due to this. This is likely will impact our decision to use Amplify JS moving forward. Ultimately Amplify is meant to encourage use of more services from AWS without friction and hence more revenue for AWS. 

Having committed a development path using Amplify, for something as important as this and clearly indicated by Apple in June itself as requirement, we should not be chasing AWS for an update and be concerned about this.

**Comment by FMJobr** [comment]
@palpatim Any updates on this due to the upcoming iOS 13 release this week?

**Comment by sarahcec** [comment]
Hi all, I'm the PM for Amazon Cognito, which is the service that Amplify uses to provide authentication. Thanks for the feedback. We're glad that you're excited about implementing Sign In with Apple. We're excited too. We are working with Apple closely to make sure that Amazon Cognito customers will have this feature available before Apple requires it in April 2020.

**Comment by markmckim** [comment]
Hi @sarahcec, the April 2020 date is for existing apps. Apple are requiring Sign in with Apple to be implemented for new apps already:

https://developer.apple.com/news/?id=09122019b

This will prevent developers (myself included) from being able to submit my app to App Store until April.

I can’t wait this long and will have to look at alternatives to Cognito unless AWS can bring this date substantially earlier.

Can you escalate the urgency of this please?

Thanks!

**Comment by Mahaswami** [comment]
@markmckim  and all, here is also something confusing about Apple's submission guideline language. 

Basically there are three possibilities here:

1. An App implements their own Sign In only (no social or third party)
2. An App Implements social/third party only (nothing on their own)
3. A mix of #1 and #2

What Apple says is that "Apps that **exclusively** use a third-party or social login service (...) to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option"

The above to my basic understanding only refers to those Apps which use the mode #2.  An app like ours come under the category of #3. However under section of exclusions in their guidelines it doesn't clearly state #3 Mode apps should not require Sign In With Apple.

Perhaps someone at AWS also can take this up with Apple to get a clear clarification of the same.

**Comment by Foefirelord** [comment]
> What Apple says is that "Apps that **exclusively** use a third-party or social login service (...) to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option"

The bullet points that follow seem to counter the "exclusively" wording, so it's just confusing all around.

Definitely need clarification both from Apple on who will be forced to implement Apple Sign-in and from AWS on how soon we'll be able to implement it within the confines of AWS Amplify/Cognito.

**Comment by Mahaswami** [comment]
@sarahcec could you get an answer please? Are you able to recognise that this is critical timeline wise and as new app developers we can't wait till March 2020?

**Comment by iamdavidmartin** [comment]
@sarahcec To add on, we've been building on Amplify for months and are planning on releasing before the end of 2019, but Apple will reject our app unless Amplify supports their federated login.

We can't wait until March or April either. Please reply to us.

**Comment by jdrobert** [comment]
@sarahcec It has been over 3 weeks since the last response. Can we get an update on this?

Our app is set to launch sometime this month. It would be nice to know how I need handle social login.

**Comment by devlogin** [comment]
Hi @sarahcec. Sorry but could you please give us a date in the future for when we can expect an informational update on this issue?  Alot of us are trying to plan our business around this missing functionality.

**Comment by Foefirelord** [comment]
If this isn't addressed soon, it could become a total fiasco for Amazon.

Apparently, apps have already been prevented from being published without Apple Sign-In support. Once already published apps start being kicked off the App Store because AWS has no sense of urgency on issues like this, and once word gets out, I have a feeling Azure and Google Cloud are going to see a real boost to their user bases.

**Comment by akharitonov** [comment]
This entire debacle with Cognito\Amplify still not supporting _Sign-In with Apple_ demonstrates the futility of relying on Cognito or Amplify as part of any semi-serious product or solution. 
And that's considering that open source solutions for Apple sign-in are available on git hub for months for a variety of open and not so open projects.

**Comment by AAAstorga** [comment]
The lack of communication is pretty sad. I want to wrap up my app and ship it, but I need to implement Sign-In with Apple. @sarahcec Please give us an update! Thanks

**Comment by BillBunting** [comment]
Also need implemented in for AWSMobileClient sign-in UX,  AWSMobileClient.default().showSignIn(), along with Facebook, Google, and Username/Password. It will be a crowded sign-in screen, but unfortunately, necessary. Thank you.

**Comment by markmckim** [comment]
@sarahcec Can we please get an update on this? Even if it's not good news, can you give us an expected timeline for Cognito support for Sign in with Apple. I need to know whether to hold off for a few days until support arrives, or to ditch Cognito completely and move to a different provider that supports Sign in with Apple. I can't release my app without this support, so it is now a blocker for me, and I can't afford to delay this decision any longer.

**Comment by ZevEisenberg** [comment]
For those asking for a reply from AWS here, I suggest you open a support ticket. There’s no indication that anyone from AWS is actively reading this thread, and if you have an existing paid relationship with AWS, I suspect you’re more likely to get an answer (or non-answer, as opposed to no answer) here instead: https://console.aws.amazon.com/support/home/

**Comment by richandrews** [comment]
#3395 https://github.com/aws-amplify/amplify-js/issues/3395

**Comment by Saravanakumar22** [comment]
Still, I couldn't find the identity provider for 'Sign in with Apple' like facebook (AWSIdentityProviderFacebook) for custom sign in.
AWS version: 2.12.2

if anyone has done this, please help me

Thanks in advance

**Comment by danielbalderas** [comment]
@Saravanakumar22 Any update?

I have same problem but I can have a solution, I'm trying with this documentation:

- https://aws.amazon.com/blogs/security/how-to-set-up-sign-in-with-apple-for-amazon-cognito/
- https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/cognito-user-pools-configuring-federation-with-social-idp.html

The result is negative, if I try to login  but apple doesn't respond to cognito, the problem that I have is:

When I authenticated with apple I got the url:

https://appleid.apple.com/auth/authorize?client_id=XXXXXX&redirect_uri=https%3A%2F%2FDOMAIN.auth.us-west-2.amazoncognito.com%2Foauth2%2Fidpresponse&scope=email+name&response_mode=form_post&response_type=code&state=XXXXXXX

but doesn't redirect to /oauth/idprespond it keep it on https://appleid.apple.com/auth/authorize?...

I hope someone else can help us.

**Comment by ryaa** [comment]
What value should be used for the Logins property of the parameters required to intialize the Cognito Credentials object (CognitoIdentityCredentials) if I need to support social login for Apple ID.

For facebook this is 'graph.facebook.com', for google this is 'accounts.google.com' but I can't find what should be used for Apple ID anywhere in the AWS documentation and the aws-sdk typescript does not list it - see below
```
    /**
     * A set of optional name-value pairs that map provider names to provider tokens. The available provider names for Logins are as follows:   Facebook: graph.facebook.com    Amazon Cognito user pool: cognito-idp.&lt;region&gt;.amazonaws.com/&lt;YOUR_USER_POOL_ID&gt;, for example, cognito-idp.us-east-1.amazonaws.com/us-east-1_123456789.    Google: accounts.google.com    Amazon: www.amazon.com    Twitter: api.twitter.com    Digits: www.digits.com   
     */
    Logins?: LoginsMap;
```

**Comment by hossamghareeb** [comment]
I'm using custom `HostedUIOptions` like `let hostedUIOptions = HostedUIOptions(scopes: ["openid", "email"], identityProvider: "SignInWithApple")` and then congito show a webview this the native Sign in with apple sheet shows up and works perfectly. I'm not sure how to get rid of that webview and show the sheet directly.

**Comment by tkohout** [comment]
@hossamghareeb :
Seems like this approach works: https://github.com/aws-amplify/aws-sdk-ios/issues/1177#issuecomment-464317503

This will skip the hosted ui (it is still using an url that's on the hosted ui domain) and take you directly to the Apple Sign In Screen.

Only identityProvider has to be changed to "SignInWithApple"

**Comment by hossamghareeb** [comment]
@tkohout I'm using Hosted UI not federated sign thing. In the comment that you referred to, i see they used federated sign in. Do you think it's doable in hosted UI?

**Comment by tkohout** [comment]
@hossamghareeb If you don't care about Identity Pool you don't have to use federated sign in.
If the call `self.auth?.getSession` ends up successfully it will create an user in your User Pool.

**Comment by hossamghareeb** [comment]
@tkohout I tried it and `self.auth?.getSession` is doing the same thing as `awsClient.showSignIn`, both open the hosted UI (website) then the native sheet show up after. Also surprisingly the `func application(_ app: UIApplication, open url: UR` is not being called. Maybe i'm missing something

**Comment by hidrodixtion** [comment]
Any update on this issue? Getting frustrated with the lack of support from Cognito team. Firebase auth already supports sign in with apple 4 months ago, and Identity Pool still doesn't have anything on sight.

**Comment by palpatim** [comment]
As far as I know, the latest status is:

- AWS supports Sign in with Apple as an external federated identity provider for Cognito User Pools, via Hosted UI. See https://aws.amazon.com/blogs/security/how-to-set-up-sign-in-with-apple-for-amazon-cognito/.
- There is a known issue with using Sign in with Apple on iOS 13 devices using FaceID to authenticate. The Cognito team is working with Apple to resolve this.
- I don't have any knowledge of whether Cognito plans to support Sign in with Apple as an Authentication provider for Identity Pools.

We'll update this thread with more information as we get it

**Comment by palpatim** [comment]
@hossamghareeb 

> @tkohout I tried it and `self.auth?.getSession` is doing the same thing as `awsClient.showSignIn`, both open the hosted UI (website) then the native sheet show up after. Also surprisingly the `func application(_ app: UIApplication, open url: UR` is not being called. Maybe i'm missing something

We have successfully tested Sign in with Apple using Hosted UI, but don't confirm the native sheet showing up. Can you open a new issue with details including your configuration, code snippets, and repro steps so we can investigate this further? This issue is mostly dedicated to the theme of "we need Cognito to support Sign in with Apple", and it's long enough that we'll lose context on individual issues if we continue those conversations here.

**Comment by Foefirelord** [comment]
@palpatim The documentation you linked is all good, but it's about setting things up in the backend, in the AWS control panel, to make Sign-in With Apple functional. But that's only half the work needed to implement Sign-in With Apple. The other half is the mobile client.

But the AWS Amplify/Mobile SDK documentation  hasn't been updated with info on implementing Sign-in With Apple.

Sure, it's simple, but we need to know what the string value is for the Sign-in With Apple identity provider when using `HostedUIOptions()` to bypass the Amazon hosted UI and go directly to a particular authentication flow.

Is it  `HostedUIOptions(scopes: ["openid", "email"], identityProvider: "Sign-in With Apple")`?
Or `HostedUIOptions(scopes: ["openid", "email"], identityProvider: "SignInWithApple")`?
Or some other permutation?

I understand that the infrastructure services are at the core of the AWS value proposition, but you really need to stop treating the AWS services and the mobile SDKs as independent of one another. The number of customers using the SDKs  and relying on updated documentation for production is only going to grow.

**Comment by hidrodixtion** [comment]
I finally make it works 😭 

First, in the **IAM Identity Providers**, add these values:

```
Provider URL: https://appleid.apple.com
Audience: <APP_BUNDLE_IDENTIFIER>
```

In the Cognito Identity Pools, edit your Identity Pool. Open the Authentication Providers, and in the OpenID tab, activate `appleid.apple.com`

Next, in your App, add **Sign in With Apple** (SIWA) capability. Follow the official steps from Apple on how to add the button and authenticate the user. When the user is authenticated, call the `federatedSignIn`.

```swift
AWSMobileClient.default().federatedSignIn(providerName: "appleid.apple.com", token: token) { (state, error) in
    print("state \(state)")
    if let state = state {
        if (state == .signedIn) {
            AWSMobileClient.default().getAWSCredentials { (cred, error) in
                print("cred \(cred)")
            }
        }
    }
}
```

For the `token` value, you need to pass it from `appleIdCredential.identityToken` that you can get from `ASAuthorizationDelegate` function
```swift
func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
}
```

One thing to note here, if you follow the Firebase Auth to integrate with SIWA, it requires you to pass nonce when performing authorization request. **Do not add the nonce** if you want to use federated sign in.

**Comment by Saravanakumar22** [comment]
Hi @hidrodixtion,
   Do we need to configure the 'awsconfiguration.json' file in app?. I'm getting this error when I try to get the AWSCredentials.

**Comment by hidrodixtion** [comment]
Hi @Saravanakumar22 , if you already have `awsconfiguration.json` file in your project, you can use the standard configuration. Don't forget to initialize it.

**Comment by Saravanakumar22** [comment]
@hidrodixtion where should I initialize awsconfiguratoin.json file. can you please share the code and should i need to add anything particular for **sign in with apple** in awsconfiguration.json file?

**Comment by hidrodixtion** [comment]
@Saravanakumar22 follow this tutorial: https://aws-amplify.github.io/docs/ios/authentication#manual-setup. Don't forget to add the `awsconfiguration.json` into your XCode project, and No, you don't need to add anything specifically for sign in with Apple.

**Comment by morris-lu** [comment]
Hi,

I got `invalid request` error when I  click `sign in with apple` using showSignin function.
And the description is **No AppPlatform or Primary app for the web application**.
<img width="1085" alt="截圖 2020-02-27 23 25 01" src="https://user-images.githubusercontent.com/40878125/75458168-63b6cb80-59b8-11ea-8c4e-ad95d9fc0e70.png">
Facebook and Google sign in works great.
Does anyone know how to setup OAuth flows and scopes? Thank you.

**Comment by Saravanakumar22** [comment]
Hi @hidrodixtion ,

 Still i'm getting this error **"AWSMobileClient.AWSMobileClientError.cognitoIdentityPoolNotConfigured(message: "There is no valid cognito identity pool configured in `awsconfiguration.json`."**. Please help with this isssue.

**Comment by forestdiggs** [comment]
@Saravanakumar22 are you initializing AWSMobileClient first?

`AWSMobileClient.default().initialize({(userState, error) in...`

Also, make sure you have the correct value for the PoolId key here:

`"CredentialsProvider": {
            "CognitoIdentity": {
                "Default": {
                    "PoolId": "us-east-1:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
                    "Region": "us-east-1"
                }
            }
        },`


@hidrodixtion I've tried your steps, and although it appears I am `signedIn` I get 'nil' when trying to print `cred`. Were there any additional steps you had to take when setting up the IAM Provider?

**Comment by Saravanakumar22** [comment]
@forestdiggs @hidrodixtion 

AWSMobileClient.default().initialize { (state, error) in
                    
                    AWSMobileClient.default().federatedSignIn(providerName: "appleid.apple.com", token: String(decoding: token, as: UTF8.self)) { (resState, error) in
                        
                        if let state = resState, state == .signedIn {
                            
                            AWSMobileClient.default().getAWSCredentials { (credentials, error) in
                                Log.info("Credentials: \(credentials)")
                                Log.info("error: \(error)")
                            }
                        }
                    }
                }
this is my code. **Error** : **Error Domain=com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper Code=0 "Obtaining an identity id in another thread failed or didn't complete within 5 seconds." UserInfo={NSLocalizedDescription=Obtaining an identity id in another thread failed or didn't complete within 5 seconds.}**

**Comment by forestdiggs** [comment]
@Saravanakumar22 
That all looks right - I'm able to get AWS Credentials using the code you've provided. Double check that the PoolId is correct, you can find it on AWS Cognito under Federated Entities here:

![image](https://user-images.githubusercontent.com/25435892/76087998-46b86480-5f85-11ea-9437-6ba475d127f7.png)

**Comment by AndresCanella** [comment]
Thanks, @hidrodixtion. It is worth noting that this solution does federation directly from the Identity Pool. So will not create users in the User Pool.

**Comment by cornr** [comment]
We managed to get SIWA working with @hidrodixtion solution and an IAM IdentityProvider: https://github.com/aws-amplify/aws-sdk-ios/issues/1809#issuecomment-586046122
To resolve this` "There is no valid cognito identity pool configured in awsconfiguration.json."` Error we had to switch from Signing In via `AWSSignInManager` to `AWSMobileClient`.
Now we have to replace the `AWSFacebookSignInProvider` and `AWSGoogleSignInProvider`.

**Comment by Saravanakumar22** [comment]
@forestdiggs I have checked, everything was correct. But still, I'm getting the same error **Error Domain=com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper Code=0 "Obtaining an identity id in another thread failed or didn't complete within 5 seconds." UserInfo={NSLocalizedDescription=Obtaining an identity id in another thread failed or didn't complete within 5 seconds.}**. If anybody has solved this issue. Please help out with this issue.

**Comment by cornr** [comment]
@Saravanakumar22 we do the initialization first (I think its is done synchronously) and then we call federatedSignIn. Also try to disable breakpoints in order to keep the threads running.

**Comment by Saravanakumar22** [comment]
@cornr I'm unable to understand what you mean. Can you please explain?

**Comment by cornr** [comment]
@Saravanakumar22 I was thinking your problem has something to do with active breakpoints preventing operations to complete in 5 seconds. I have also seen this error while implementing SignIn With Apple. But now I cannot reproduce it so forget breakpoints. Sorry

**Comment by wattanakorn495** [comment]
@hidrodixtion 

> I finally made it works. 😭
> 
> First, in the **IAM Identity Providers**, add these values:
> 
> ```
> Provider URL: https://appleid.apple.com
> Audience: <APP_BUNDLE_IDENTIFIER>
> ```
> 
> In the Cognito Identity Pools, edit your Identity Pool. Open the Authentication Providers, and in the OpenID tab, activate `appleid.apple.com`
> 
> Next, in your App, add **Sign in With Apple** (SIWA) capability. Follow the official steps from Apple on how to add the button and authenticate the user. When the user is authenticated, call the `federatedSignIn`.
> 
> ```swift
> AWSMobileClient.default().federatedSignIn(providerName: "appleid.apple.com", token: token) { (state, error) in
>     print("state \(state)")
>     if let state = state {
>         if (state == .signedIn) {
>             AWSMobileClient.default().getAWSCredentials { (cred, error) in
>                 print("cred \(cred)")
>             }
>         }
>     }
> }
> ```
> 
> For the `token` value, you need to pass it from `appleIdCredential.identityToken` that you can get from `ASAuthorizationDelegate` function
> 
> ```swift
> func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
> }
> ```
> 
> One thing to note here, if you follow the Firebase Auth to integrate with SIWA, it requires you to pass nonce when performing authorization requests. **Do not add the nonce** if you want to use the federated sign in.

I follow your setup for react-native app. it work, but how to refresh token?
here is my setup
```
const refreshToken = async () => {
  await MemoryStorageNew.sync();
  const federatedInfo = MemoryStorageNew.getItem('aws-amplify-federatedInfo');
  console.warn('refresh token!', federatedInfo);
  const federatedInfoParsed = JSON.parse(federatedInfo);
  const {token} = federatedInfoParsed;

  return {
    token,
  };
};

Amplify.configure({
  Auth: {
    refreshHandlers: {
      google: refreshToken,
      facebook: refreshToken,
      'appleid.apple.com': refreshToken,
    },
    storage: MemoryStorageNew,
  },
});
```

**Comment by andybezaire** [comment]
@Saravanakumar22 did you ever figure your problem out? I am having the same error: Obtaining an identity id in another thread failed or didn't complete within 5 seconds.
(it actually fails, not a timeout. it fails before the timeout)

**Comment by Saravanakumar22** [comment]
@cornr Can you please share the piece of code used to '**Sign With In Apple**'? I'm getting the same error. And one more doubt do we need to add **Amplify** for **AWSMobileClient**?

@andybezaire nope. facing the same issue

Thanks in advance

**Comment by palpatim** [comment]
Latest status of this:

* The Amazon Cognito service now supports Sign in with Apple for federated sign in to Identity Pools, in addition to the previous support for User Pools via HostedUI.
* We have updated the [HostedUI Auth documentation](https://aws-amplify.github.io/docs/ios/authentication#setting-up-hosted-ui-domain-for-sign-in-with-apple) to provide the correct HostedUI identityProvider value: `"SignInWithApple"`
* We are working on an update to the docs for `federatedSignIn` for IdentityPools. In the meantime, the correct `providerName` is `"appleid.apple.com"`. Don't forget to enable Sign in with Apple in your Identity Pool's "Authentication providers" tab.
* As far as I know, there are still known issues with using Sign in with Apple on iOS devices using Face ID. This is an issue that Cognito and Apple are working on resolving, but I don't have any further updates just now.

We'll be pushing an update to add the Sign in with Apple strings to `AWSMobileClient.IdentityProvider`, but for now, you can use the raw values.

**Comment by andybezaire** [comment]
@Saravanakumar22 I got Sign in with Apple working.
I am doing the same steps you mentioned above and was getting the same error. I was actually getting the signedIn state, but that error came when I tried getAWSCredentials.

The fix was not in the app, but in the server. I didn't do the fix, but here are the comments about how it was fixed:

"It seems that on top of the app cognito pool setup you must add the IAM ferelar setup (above) and then as a extra step go to the identity pool to enable openId login for the thing set up in IAM"

hope that helps

**Comment by andybezaire** [comment]
@palpatim we are having the same issue with google login. Do you know the corresponding IAM setup procedure for google sign in?

**Comment by palpatim** [comment]
@andybezaire Please open a separate issue for your Google login question. This thread is focused on AWS support of Sign in with Apple for iOS clients.

**Comment by cornr** [comment]
@palpatim thanks for the update. We are see expiring tokens after app restarts (after 10+ minutes): AWSMobileClient posts a `signedOutFederatedTokensInvalid` in the UserStateHandler. See: https://github.com/aws-amplify/aws-sdk-ios/issues/2366#issuecomment-614094365
Do you have any thoughts on how to solve this with apple sign in?

**Comment by Saravanakumar22** [comment]
I finally made it works. 😭

@andybezaire  Thanks

**Comment by cornr** [comment]
Hey everyone who has got the Sign in with Apple via `AWSMobileClient` working: do you experience the same issue as we do? We get a `signedOutFederatedTokensInvalid` after 10 mins. Even with a Cognito Refresh Time of 3650 Days.
After that I can see no solution to keep the user signed in without presenting the "Sign in with Apple"-Sheet again (which I find a show stopper). Thanks for your help

**Comment by Saravanakumar22** [comment]
@cornr Yes, I'm also facing the same issue. New token isn't generating. thanks for your help

**Comment by amuresia** [comment]
Hi everyone, could somebody confirm that they got Sign In With Apple to work and managed to run API queries following that?
I implemented the following method
```
AWSMobileClient.default().federatedSignIn(providerName: "appleid.apple.com", token: token) { userState, error in
            if let error = error {
                print("Error in federatedSignIn: \(error)")
                return
            }
            guard let userState = userState else {
                print("userState unexpectedly nil")
                return
            }
            print("federatedSignIn successful: \(userState)")
        }
```
which after I sign in with Apple, logs the following message
```
federatedSignIn successful: signedIn
```
However, when I try to run a GraphQL query I get the following error
```
2020-04-28 22:10:27.964028+0200 Error occured when trying to retrieve the user: Optional(AWSAppSync.AWSAppSyncClientError.authenticationError(AWSMobileClient.AWSMobileClientError.notSignedIn(message: "User is not signed in, please sign in to use this API.")))
```
In my Cognito Identity Pool I can see a new Identity that says `Linked logins: appleid.apple.com`
Looks alright, no?
My GraphQL model definition is like
```
type User
@model
@auth(rules: [{ allow: owner, operations: [create, update, delete] }])
{
    id: ID!
}
```
Am I supposed to add additional auth capabilities to make this work with Federated Identities/ Sign In With Apple, if so, could you please provide a link to some documentation?
Thanks!

**Comment by cornr** [comment]
@amuresia yes API Request work for us after a `federatedSignIn` though we use `AWSAPIGatewayClient` to invoke API Requests.

@Saravanakumar22 good to know that we are not alone. I opened a new bug for that #2513. I wonder if anyone as SIWA with AWS working in production. At least we have time till June 30, 2020.

**Comment by Saravanakumar22** [comment]
@cornr For Facebook and Google, how you are using silent login, can you please share?
thanks in advance.

**Comment by cornr** [comment]
@Saravanakumar22 I haven't implemented Facebook silent login yet since I think this should be handled by cognito. But you probably can have a look at https://github.com/aws-amplify/aws-sdk-ios/blob/6163bef243caf6025cdac90ae16eedbdd4aba65c/AWSAuthSDK/Sources/AWSFacebookSignIn/AWSFacebookSignInProvider.m#L121 when `signedOutFederatedTokensInvalid` is issued for a Facebook sign in. after a success you can probably call `AWSMobileClient.federatedSignIn` again.

**Comment by Saravanakumar22** [comment]
yeah, thanks @cornr

**Comment by YaroslavHavrylovych** [comment]
I see that AWS already have [an official documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/apple.html) about AppleLogin. So, that has to be an answer to every possible question in here :)

**Comment by cornr** [comment]
@YaroslavHavrylovych this is a joke, right?
Or do you have it working?

Does anybody have Sign in with Apple + AWS working in production?

**Comment by YaroslavHavrylovych** [comment]
@cornr This wasn't a joke, originally at least. When I wanted to implement Apple login, there was no doc. Now there is, but I didn't have a chance/time to check, just shared. My idea was if there is official documentation, then probably this thing has to work. Today I will try to implement it, hopefully, it does work.

**Comment by andybezaire** [comment]
We have sign in with apple + AWS working in development right now, soon to production.

I haven’t had a chance to read the new documentation that was linked, but previous documentation was not so good or non-existent.

**Comment by cornr** [comment]
good to hear. have you had any issues with invalid federated tokens after 10 mins of inactivity (or leaving the app and come back 10 mins later)?
See: https://github.com/aws-amplify/aws-sdk-ios/issues/2513

**Comment by YaroslavHavrylovych** [comment]
@cornr I've passed the token from Apple 
`let tokeStr = String(data: appleIDCredential.identityToken!, encoding: .utf8)`

to Credentials Provider through the AWSIdentityProviderManager
`AWSTask(result: ["appleid.apple.com":tokeStr])`

and this was enough to connect to CognitoSync. No misbehaviour since that (e.g. like "invalid federated tokens"). The app will have a good testing session somewhere around Thursday, so maybe then.

As pre-steps I've added Bundle ID to the Cognito's Authentication Providers tab.
<img width="963" alt="auth_provider" src="https://user-images.githubusercontent.com/2469733/82220715-ac32b500-9927-11ea-8f0c-25565821b6b9.png">

**Comment by cornr** [comment]
@YaroslavHavrylovych how was your SIWA testing?

Am I right your not using the [AWSMobileClient](https://docs.amplify.aws/lib/auth/federated-identities/q/platform/ios#set-up-sign-in-with-apple) for federated Sign In? How do you use your AWSIdentityProviderManager for SIWA?

**Comment by KosalaFMF** [comment]
`let logins = ["graph.facebook.com" : fbAuthToken]
    let customIdentityProvider = CustomIdentityProvider(tokens: logins)
    let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .APSouth1, identityPoolId:              AWSConstants.CognitoFederatedIdentityUserPoolId, identityProviderManager: customIdentityProvider)

    let configuration = AWSServiceConfiguration(region: .APSouth1, credentialsProvider: credentialsProvider)
    AWSServiceManager.default().defaultServiceConfiguration = configuration
    
    credentialsProvider.getIdentityId().continueWith { (task: AWSTask!) -> AnyObject? in
        
        if (task.error != nil) {
            print("Error: " + (task.error?.localizedDescription)!)
            
        } else {
            // the task result will contain the identity id
            let cognitoId = task.result
            Log.add(info: "Cognito ID : \(cognitoId)")
        }
        return nil
    }
}`

This is the way I have did facebook and google login , can I do SIWA with this way. I can't use MobileClient, I did all things with this SDK, like user pool sample app, now I only need to do SIWA, please help me any one.

**Comment by palpatim** [comment]
We've posted a [summary of Cognito support of Sign In With Apple](https://github.com/aws-amplify/aws-sdk-ios/issues/2513#issuecomment-774130422) that outlines options for both User Pools and Federated Identities. We are closing this issue since we do support SIWA for Federated Identities/Cognito Identity Pools. If you have other questions or concerns, please feel free to open a new issue and reference this issue or https://github.com/aws-amplify/aws-sdk-ios/issues/2513 for context.
