### ISSUE TITLE
Failed with error: Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)"

### ISSUE THREAD

**Issue by Ramkumartr** [aws-amplify/aws-sdk-ios#1814]
I'm using sdk 2.10.2 and using AWSS3TransferUtility to upload file (Video and text files)
this is the upload
```
_ =   transferUtility.uploadFile(fileURL, bucket: s3BucketName, key: "\(foldername)/\(fileName)", contentType: "text/" + mimeType, expression: expression, completionHandler: completionHandlerA).continueWith { (task) -> AnyObject? in
                    if let error = task.error {
                        print("Error: \(error.localizedDescription)")

                    } else {
                        
                        if let tsk = task.result {
                            self.uploadTask = tsk
                        }
                   
                    }
                    return nil
    }

```
getting this error after the progress

```
Failed with error: Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" 
Found error in response. Details are: 
 >>>> Via: 1.1 362c65c57df97e0bc220116880b0aea7.cloudfront.net (CloudFront) 
  
 >>>> Content-Type: application/xml 
  
 >>>> Connection: keep-alive 
  
 >>>> Server: AmazonS3 
  
 >>>> Date: Fri, 23 Aug 2019 13:11:27 GMT 
  
 >>>> X-Cache: Error from cloudfront 
  
 >>>> x-amz-request-id: BC9830DB6F751902 
  
 >>>> x-amz-id-2: kXRZ2aictx54w2y2XXDqDVZn/IpZM/5PjsSGYJB8qpCCu39Lfx8p8kkXU7RZbpnAN242kgl7lP0= 
  
 >>>> X-Amz-Cf-Id: T1NH8RZoDiob6CX6UkDX8bSHHn1VRQRvnAYGS9b1RJds5GTwOR_6WQ== 
  
 >>>> X-Amz-Cf-Pop: BLR50-C2 
  
 >>>> Transfer-Encoding: Identity 
```

Environment
 - SDK Version: 2.10.2
 - Dependency Manager: Added Manually 
 - Swift Version : 5

Device Information 
  iOS 12.1.4 (16D57)
 Model: iPhone XS Max

**Comment by palpatim** [comment]
Code 2 is `AWSS3TransferUtilityErrorClientError`, which can be thrown in a number of cases during the upload flow. Inspecting the `userInfo` dictionary returned with the error should give more information about the underlying cause. It seems like you may be using the TransferUtility integration test as a basis for error reporting, but that test only reports the `Error` key of the `userInfo` object; all of them will be helpful in figuring out the issue.

Also, are you sure your bucket policies and ACL are properly set up to allow your client to upload to the specified destination?

**Comment by Ramkumartr** [comment]
It was working fine with AWSS3TransferManager. 
The issue is now fixed. I have changed  tuConf.isAccelerateModeEnabled = true
 to false.

**Comment by leodark85** [comment]
I solved enabling  acceleration transfer option
