### ISSUE TITLE
Cannot iOS Archive: AWS framework - library not found for -lAWSS3

### ISSUE THREAD

**Issue by ObjCjoe** [aws-amplify/aws-sdk-ios#1827]
- Xcode 10.3, using Objective C
- AWS-IOS-SDK-2.10.3
- Frameworks SDK method

I added SDK Framework (AWSS3, AWSCore, AWSCognito) using this:
https://aws-amplify.github.io/docs/ios/manualsetup

RUN and BUILD works fine, so app runs on devices and simulator.
But when I try to ARCHIVE, I get error:

ld: library not found for -lAWSS3
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kneekey23** [comment]
@ObjCjoe are you still experiencing this issue with the latest version of the SDK? 2.12.7?
