### ISSUE TITLE
AWSMobileClient is signed in does not equal actual value

### ISSUE THREAD

**Issue by Dellybro** [aws-amplify/aws-sdk-ios#1829]
**Describe the bug**

After calling AWSMobileClient.sharedInstance().signIn(....), AWSMobileClient.sharedInstance.isLoggedIn / isSignedIn, is equal to false.

**To Reproduce**

Create a new iOS project, add AWSMobileClient, create a new user, and signin, then call AWSMobileClient.sharedInstance.isLoggedIn.

**Which AWS service(s) are affected?**

AWSMobileClient

**Expected behavior**

isSignedIn should be == true after signing in

**Environment(please complete the following information):**
 - SDK Version: @Latest
 - Dependency Manager: CocoaPods
 - Swift Version : 4 / 5

**Device Information (please complete the following information):**
 - Device: [Simulator - All Devices]
 - iOS Version: [e.g. iOS 12+]

**Comment by royjit** [comment]
Hi, this issue should be addressed in this [PR #1822](https://github.com/aws-amplify/aws-sdk-ios/pull/1822). This will be available in the next release.

**Comment by Dellybro** [comment]
What's the status on this release? Currently i'm using a timeout function so it's fine until the release, but also on a side note this happens on both React native and the react aws amplify packages.

**Comment by royjit** [comment]
We released this in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0
Please let us know if you have any problems with this.

**Comment by Dellybro** [comment]
@royjit 

I have just tested this morning removing the 0.5s timer i used to wait for the credentials to sync, and it worked!

Thank you, also the rest of the updates are awesome to!

**Comment by royjit** [comment]
Thank you @Dellybro for verifying the fix.
 I am closing this. Feel free to reach out if you face any other issue.
