### ISSUE TITLE
Need to resolve AWSCore version dependency for AWSAppSync and AWSMobileClient

### ISSUE THREAD

**Issue by sykhan88** [aws-amplify/aws-sdk-ios#1833]
**Describe the bug**
I want to install AWSAppSync and AWSMobileClient, both of which depend on different versions of the AWSCore. How can I resolve this conflict in the AWSCore version dependency so that I can install both AWSAppSync and AWSMobileClient

**To Reproduce**
I am trying to install the following pods: 
- pod 'AWSAppSync', '~> 2.12.0' 
- pod 'AWSMobileClient', '~> 2.10.0'

However, AWSAppSync depends on AWSCore ~> 2.9.0 whereas, AWSMobileClient depends on AWSCore = 2.10.0. So based on whatever AWSCore version I install, I can install one of the two required pods. I have run the following already

```
pod install --repo-update
```
which didn't not work. 
I have also tried removing the master repo and running
```
pod setup
```
again, but without any luck. 

I essentially get the following error when I run pod install
```
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In snapshot (Podfile.lock):
    AWSCore (= 2.9.10, ~> 2.9.0)

  In Podfile:
    AWSAppSync (~> 2.12.0) was resolved to 2.12.2, which depends on
      AWSCore (~> 2.9.0)

    AWSMobileClient (~> 2.10.0) was resolved to 2.10.0, which depends on
      AWSAuthCore (= 2.10.0) was resolved to 2.10.0, which depends on
        AWSCore (= 2.10.0)
```

**Which AWS service(s) are affected?**
AWSMobileClient, AWSAppSync

**Expected behavior**
I expect both AWSMobileClient and AWSAppSync to install successfully.

**Environment(please complete the following information):**
- SDK Version: 'AWSMobileClient', '> 2.10.0' , 'AWSCore', '> 2.10.0'
- Dependency Manager: Cocoapods
- Swift Version : 5.0
- Xcode Version: 10.3

**Device Information (please complete the following information):**
- Device: MacOS
- iOS: 12.4

**Comment by royjit** [comment]
Hi, @sykhan88  thanks for reaching out. Looks like a documentation issue, we will update it. In the mean time could you try this:
```
pod 'AWSAppSync', '~> 2.14.0'
pod 'AWSMobileClient', '~> 2.10.0'
```

**Comment by sykhan88** [comment]
Hi @royjit . Same issue again. AWSAppSync is reliant on AWSCore (~> 2.9.0) where is the AWSMobileclient on AWSCore (= 2.10.1). Error is as follows:
```
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In snapshot (Podfile.lock):
    AWSCore (= 2.10.1)

  In Podfile:
    AWSAppSync (~> 2.14.0) was resolved to 2.14.0, which depends on
      AWSCore (~> 2.9.0)

    AWSMobileClient (~> 2.10.0) was resolved to 2.10.1, which depends on
      AWSCognitoIdentityProvider (= 2.10.1) was resolved to 2.10.1, which depends on
        AWSCore (= 2.10.1)

Specs satisfying the `AWSCore (= 2.10.1), AWSCore (= 2.10.1), AWSCore (~> 2.9.0)` dependency were found, but they required a higher minimum deployment target
```

**Comment by royjit** [comment]
I have the following podfile and it worked for me:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Passwordless' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Passwordless
  pod 'AWSAppSync', '~> 2.14.0'
  pod 'AWSMobileClient', '~> 2.10.0'
  
end
```
Could you please try clearing the pods cache and then try a `pod update`.

**Comment by sykhan88** [comment]
Thanks @royjit . Removing cache and using ```pod update``` did the trick. Why is this the case? Is it worth clearing cache and doing pod update periodically?

**Comment by royjit** [comment]
Frankly I do not know much about the internals of pods. More details about pods can be found here - https://guides.cocoapods.org/. `pod update` tries to get the updated version from the package without looking into `Podfile.lock`, which might have done the trick for you.

**Comment by aymenbraham** [comment]
How to fix it plz !!

  pod 'AWSMobileClient', '~> 2.13.0'    
  pod 'AWSAuthUI', '~> 2.13.0'            
  pod 'AWSUserPoolsSignIn', '~> 2.13.0'


[!] CocoaPods could not find compatible versions for pod "AWSMobileClient":
  In snapshot (Podfile.lock):
    AWSMobileClient (= 2.12.7, ~> 2.12.0)

  In Podfile:
    AWSMobileClient (~> 2.12.0)

    AWSMobileClient (~> 2.13.0)

Specs satisfying the `AWSMobileClient (~> 2.12.0), AWSMobileClient (~> 2.13.0), AWSMobileClient (= 2.12.7, ~> 2.12.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by palpatim** [comment]
@aymenbraham I can't really follow your issue description--it looks like you've declared pod dependencies on `AWSMobileClient` twice. Can you remove the 2.12.0 dependency and just use the `~> 2.13.0` one? If that doesn't solve your problem, please open a new issue and fill out the details in the template so we can help troubleshoot.
