### ISSUE TITLE
SwiftUI login success completionHandler not being triggered

### ISSUE THREAD

**Issue by jpelayo** [aws-amplify/aws-sdk-ios#1837]
How can be the outcome of a successful login trigger events in the ContentView?

Better said, **can AWS provide a sample Cognito/MobileHub+Cognito implementation for SwiftUI?**

_(Xcode 11 Beta 7 for ios 13 iPhone Xs simulator - using cocoa pods)._

I have included the UIViewController provided as a sample by AWS inside a UIViewControllerRepresentable that is correctly launched over the UINavigationController in a SwiftUI view. I can receive UIAlerts if the username is not correct, etc. ... but when a successful logon is made, these parts of the code are NOT being called:

1. MobileHUB AWS sample code in [docs](https://docs.aws.amazon.com/es_es/aws-mobile/latest/developerguide/mobile-hub-add-aws-mobile-user-sign-in-customize.html)  :
`
AWSAuthUIViewController.presentViewController(
            with: self.navigationController!,
            configuration: config, completionHandler: {
                (provider: AWSSignInProvider, error: Error?) in
                if error == nil {
                    print("---- Signin ok -----fails to print this")
                } else {print("---- Signin failed -----fails to print this")}
           })
`

2. Cognito  AWS sample code in [repo](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Swift) :

   ` public func didCompleteStepWithError(_ error: Error?) {`
...
`else {
                self.username.text = nil
                 print("Fails to print a logged user:" + (AWSCognitoIdentityUserPool(forKey: AWSCognitoUserPoolsSignInProviderKey).currentUser()?.username ?? "No user"))
                self.dismiss(animated: true, completion: nil)`

I know I should be able to pinpoint the endpoint where I should trigger actions after successful logon, but if sample code is going to be published, I bet it will be leaner.

[Same question reformulated](https://stackoverflow.com/questions/57811633/cognito-uiviewcontroller-embedded-in-swiftui-with-uiviewcontrollerrepresentable)

**_PD: Issues at awslabs/aws-sdk-ios-samples are disabled, so I post here this issue_**

**Comment by lawmicha** [comment]
Hi @jpelayo Sorry for the delay. That sample is a bit outdated, and our recommendation is to use AWSMobileClient, which is a high level client for interacting with AWS Cognito User Pools and Identity Pool.
current docs: https://aws-amplify.github.io/docs/ios/authentication
preview docs: https://docs.amplify.aws/sdk/auth/getting-started?platform=ios

When working with SwiftUI, it should be similar such that you can create a UIViewControllerRepresentable with a NavigationController, then call `AWSMobileClient.default().showSignIn(navigationController: navController ...)` for the HostedUI flow. and the normal SignIn/SignUp methods you can just directly use `AWSMobileClient.default().signIn`

Please let us know if you have more questions

**Comment by eduardo-bermudez** [comment]
Hi @lawmicha - where do you create the UIViewControllerRepresentable with a NavigationController? I am working on a separate project and want to do the same and I am trying to init the navController within didFinishLaunchingWithOptions in my AppDelegate class but I'm still having some issues.

Here is what I currently have:
    import UIKit
    import AWSMobileClient
    @UIApplicationMain
    class AppDelegate: UIResponder, UIApplicationDelegate {

        func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
            // Override point for customization after application launch.
            let navigationController = application.windows[0].rootViewController as! UINavigationController
            initializeAWSMobileClient()
            return true
        }

        func initializeAWSMobileClient(){
            AWSMobileClient.default().initialize { (userState, error) in
                if let uState = userState {
                    if uState == .signedOut {
                AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, { (uState2, error) in
                            print(uState2 ?? "none")
                            print(error?.localizedDescription ?? "no error")

                        })
                    }
                }
           }
        }

I am getting an error with self.navigationController! since the AppDelegate class has no navigationController member. Thanks!
