### ISSUE TITLE
Getting no result with Textract in iOS

### ISSUE THREAD

**Issue by marcabrera** [aws-amplify/aws-sdk-ios#1838]
**State your question**
I'm trying to extract some text from a JPEG image using Textract converting it into bytes. I have set up all the configuration with Cognito and it is working, but when I try to create a request to detect text I keep getting this result 

`<AWSTask: 0x6000033ee680; completed = NO; cancelled = NO; faulted = NO;>`

Am I doing something wrong?

**Which AWS Services are you utilizing?**
Cognito and Textract

**Provide code snippets (if applicable)**

`imageView.image = image

        picker.dismiss(animated: true, completion: nil)

        let encodedImage = imageView.image!.toBase64()

        let textract = AWSTextract.default()

        let request: AWSTextractDetectDocumentTextRequest = AWSTextractDetectDocumentTextRequest()

        let document = AWSTextractDocument()
        document?.bytes = encodedImage?.data(using: .utf8)

        request.document = document

        let result = textract.detectDocumentText(request)`

**Environment(please complete the following information):**
 - SDK Version: 2.10.2
 - Dependency Manager: CocoaPods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 12.4

**Comment by royjit** [comment]
Hi @marcabrera Thank you for reaching out. detectDocumentText is an asynchronous operation. You have to assign callback block to get the response as shown below:

```
textract.detectDocumentText(request).continueWith { (task) -> Any? in
            guard let result = task.result else {
                let error =  task.error as NSError?
                print("Should not produce error: \(error.debugDescription)")
                return nil
            }
            // Work with your result here
            return nil
            }

**Comment by marcabrera** [comment]
Thank you for your quick answer. I did that but I just keep getting this response
`Should not produce error: Optional(Error Domain=com.amazonaws.AWSTextractErrorDomain Code=10 "(null)" UserInfo={__type=ProvisionedThroughputExceededException, Message=Provisioned rate exceeded})`
It happens since I have updated the code, so I assume no images have been uploaded.

Also, reading the documentation it says that detectDocumentText is a synchronous operation, and I just want to use it with a JPEG image. Has that change?

**Comment by royjit** [comment]
As per [here](https://docs.aws.amazon.com/textract/latest/dg/API_DetectDocumentText.html) it looks like you have reached your limit of allowed request. 

```
ProvisionedThroughputExceededException
The number of requests exceeded your throughput limit. If you want to increase this limit, contact Amazon Textract.

HTTP Status Code: 400
```

**Comment by marcabrera** [comment]
Yes, that is what it seems. Weird because I didn't upload any images yet due to the past issue

**Comment by bluepixeltech** [comment]
Hi,

I can see you have used Textract in Swift. Can you please tell me how? Any guides or manual? Thanks

**Comment by marcabrera** [comment]
Hi, I followed AWS official steps as they say in their website: https://docs.aws.amazon.com/textract/latest/dg/getting-started.html
And then reading through their documentation: [https://docs.aws.amazon.com/textract/latest/dg/textract-dg.pdf](url)
Then once I had everything configured and in the podfile, I tried to read the documentation provided in the code, but it has been given of issues that I can't figure out. I guess for iOS is pretty new.

**Comment by bluepixeltech** [comment]
What does your awsconfiguration.json look like? Do you have any item added specifically for Textractor?

**Comment by bluepixeltech** [comment]
Did you solve the problem? I am getting the same error about exceeding the limits, although I have even really used it!

**Comment by lawmicha** [comment]
@marcabrera @bluepixeltech were you able to resolve the service limit issue? If so, what did you do? I'd suggest reaching out to the AWSTextact service team, perhaps the forums is a good start: https://forums.aws.amazon.com/forum.jspa?forumID=338&start=0

For new developers, we recommend trying out Amplify Predictions: https://docs.amplify.aws/lib/predictions/identify-text/q/platform/ios
