### ISSUE TITLE
AWSS3TransferManager upload success but use AWSS3TransferUtility fail

### ISSUE THREAD

**Issue by hatjs880328s** [aws-amplify/aws-sdk-ios#1842]
**Describe the bug**
use AWSS3 sdk 
when i upload  a file to my own server , use AWSS3TransferManager  success.... 
but use AWSS3TransferUtility  fail  
config  have no difference.

i saw  'AWSS3TransferManager' request-header have something.
'AWSS3TransferUtility' request-header have no , but url is long.

**To Reproduce**
Like the Describe the bug

**Which AWS service(s) are affected?**

awss3 upload service 

**Expected behavior**
use  AWSS3TransferUtility  upload success..

**Screenshots**

**Environment(please complete the following information):**
  pod 'AWSS3', '~> 2.10.3'

**Device Information (please complete the following information):**
iphone 6sp

**Additional context**

**Comment by royjit** [comment]
Hi, Thank you for reaching out. Could you please share the code sample that you use for both `AWS3TransferManager` and `AWSS3TransferUtility`?

Also, do you get any error message when it fails?

**Comment by hatjs880328s** [comment]
@objc class IIAWSCore: NSObject {

    /// key
    fileprivate let iiawsKey: String = ""

    var credentialProvider: AWSBasicSessionCredentialsProvider!

    var config: AWSServiceConfiguration!

    var tuConf: AWSS3TransferUtilityConfiguration = AWSS3TransferUtilityConfiguration()

    @objc public func registerIIAWS(uploadInfo: AwsUploadFile) {

        //tuConf.isAccelerateModeEnabled = true
        tuConf.retryLimit = 1


        // Endpoint
        let endPoint = AWSEndpoint(region: AWSRegionType.APNortheast1, service: AWSServiceType.S3, url: URL(string: uploadInfo.url)!)


        /// 这里俩参数需要设置
        self.credentialProvider = AWSBasicSessionCredentialsProvider(
            accessKey: uploadInfo.accessKey,
            secretKey: uploadInfo.secretKey,
            sessionToken: uploadInfo.securityToken)

        self.config = AWSServiceConfiguration(region: AWSRegionType.APNortheast1, endpoint: endPoint, credentialsProvider: credentialProvider)

        AWSS3TransferUtility.register(with: config, transferUtilityConfiguration: nil, forKey: uploadInfo.filename) { ( errInfo ) in
        }
        AWSServiceManager.default()?.defaultServiceConfiguration = self.config
        
    }
}

@objc class IIAWSUpload: NSObject {

    /// use AWSS3TransferUtility upload
    func uploadData(data: Data) {

        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = {(task, progress) in
            DispatchQueue.main.async(execute: {

            })
        }

        var completionHandler: AWSS3TransferUtilityUploadCompletionHandlerBlock?
        completionHandler = { (task, error) -> Void in
            DispatchQueue.main.async(execute: {
            })
        }

        let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "ee2/38a/a2-/ee238aa2-abd1-43d8-8b57-1b210444d6d8")

        transferUtility?.uploadData(data,
                                   bucket: "ecm-cloud-drive",
                                   key: "ee2/38a/a2-/ee238aa2-abd1-43d8-8b57-1b210444d6d8.png",
                                   contentType: "image/png",
                                   expression: expression,
                                   completionHandler: completionHandler).continueWith {
                                    (task) -> AnyObject? in
                                    if let error = task.error {
                                        print("\(error.localizedDescription)")
                                    }

                                    if let _ = task.result {
                                        // Do something with uploadTask.
                                    }
                                    return nil;
        }
        
    }

    /// /// use AWSS3TransferManager upload
    @objc func uploadDataWithMulti(uploadInfo: AwsUploadFile) {
        let uploadRequest = AWSS3TransferManagerUploadRequest()!
        uploadRequest.body = URL(string: uploadInfo.file.fileRealPath ?? "")!
        uploadRequest.key = uploadInfo.filename
        uploadRequest.bucket = uploadInfo.bucket
        uploadRequest.contentType = uploadInfo.contentType
        uploadRequest.acl = .publicRead

        
        let transferManager = AWSS3TransferManager.default()

        transferManager.upload(uploadRequest).continueWith { (task) -> Any? in
            print("task error....\(task.error)")
        }.continueOnSuccessWith { (task) -> Any? in
                if let error = task.error {
                    print("Upload failed with error: (\(error.localizedDescription))")
                }
                // call back
                // ProgressSuccessCallBack().callBack(url: uploadInfo.callBackUrl , params: params)
                return nil
        }
    }
}

**Comment by hatjs880328s** [comment]
2 Classes , first is progress the manager & utility config

last is use them upload a file ...

**Comment by hatjs880328s** [comment]
@royjit royjit

**Comment by palpatim** [comment]
@hatjs880328s What error message are you receiving?

**Comment by KavonSakul** [comment]
Hey guys @palpatim @royjit
I have very similar issue. Upload using `AWSS3TransferManager` is working as expected. Unfortunately  trying to upload the same file with the same AWS configuration using `AWSS3TransferUtility` fails. I can see file being uploaded but after reaching 100% completion block is invoked with an error

**Comment by KavonSakul** [comment]
Ok it seems I found the issue. My configuration was using `AWSAnonymousCredentialsProvider()`, when I changed it to `AWSCognitoCredentialsProvider` everything started working. 👍

**Comment by royjit** [comment]
Hi @KavonSakul Glad it is working for you. 
Closing this issue, please reach out to us if you have more questions.
