### ISSUE TITLE
uploading speed issue in ios

### ISSUE THREAD

**Issue by RajSingh007** [aws-amplify/aws-sdk-ios#1847]
AWSS3TransferUtility uploading file speed is very slow. When I upload an image of 1 mb it takes almost 12-15 second to upload and 5mb image takes more than a minute. The region is us-east-2. Please help I am stuck.
This is how I use AWSS3TransferUtility

        let name = "\(Int(Date().timeIntervalSince1970))\(String.randomString(length: 8))\(file.contentType == .image ? ".jpeg" : ".mp4")"

        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = {(task, status) in
            printDebug(status.fractionCompleted)
            DispatchQueue.main.async(execute: {
                progress?(Float(status.fractionCompleted))
            })
        }
        // For public read
        expression.setValue("public-read", forRequestHeader: "x-amz-acl")

        var completionHandler: AWSS3TransferUtilityUploadCompletionHandlerBlock?
        completionHandler = { (task, error) -> Void in
            DispatchQueue.main.async(execute: {

                if let error = error {
                    printDebug("Upload failed with error: (\(error.localizedDescription))")
                    faliure(error.localizedDescription)
                }
                if let _ = task.response {
                    let bucket = AppConstants.AWS_BUCKET
                    let url = AWSS3.default().configuration.endpoint.url
                    let publicURL = url?.appendingPathComponent(bucket).appendingPathComponent(imageURL.lastPathComponent).absoluteString

                    success(publicURL ?? "", imageURL.absoluteString)

                } else {
                    faliure(LS.somethingWentWrong )
                }
            })
        }

        let transferUtility = AWSS3TransferUtility.default()
        transferUtility.uploadFile(imageURL, bucket: AppConstants.AWS_BUCKET, key: name, contentType: file.contentType == .image ? "image/jpeg" : "video/mp4", expression: expression, completionHandler: completionHandler).continueWith { (task) -> Any? in
            return nil
        }

**Comment by desokroshan** [comment]
@RajSingh007 Thanks for reaching out. Can you please provide following details : 

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here.

**Comment by RajSingh007** [comment]
**@desokroshan** 
SDK Version: [Using AWSCore (2.10.3), Using AWSS3 (2.10.3)]
Dependency Manager: [Cocoapods]
Swift Version : [4.2]

**Device information**
I tested from iPhone 6 to iPhone x and same in the simulator
iOS Version 11.4 and above

**Additional context**
Some times uploading start after 5-10 seconds when I press the upload button and also there is no delay.

**Comment by RajSingh007** [comment]
@desokroshan 
now I am using acceleration for uploading data


        
        let credentialsProvider = AWSCognitoCredentialsProvider( regionType: .USEast2,
                                                                 identityPoolId: poolID)
        let configuration = AWSServiceConfiguration(region:.USEast2, credentialsProvider:credentialsProvider)
        
        // Configuration
        configuration?.timeoutIntervalForRequest = TimeInterval(90) // TimeInterval(18000) // 1/2 hr
        configuration?.maxRetryCount = 1 //5
        configuration?.timeoutIntervalForResource = TimeInterval(3000)
        configuration?.allowsCellularAccess = true
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        //Setup the transfer utility configuration
        let tuConf = AWSS3TransferUtilityConfiguration()
        tuConf.isAccelerateModeEnabled = true
        tuConf.retryLimit = 5
        tuConf.multiPartConcurrencyLimit = 3
        tuConf.timeoutIntervalForResource = 15*60 //15 minutes
        
        //Register a transfer utility object asynchronously
        AWSS3TransferUtility.register(
            with: configuration!,
            transferUtilityConfiguration: tuConf,
            forKey: "transfer-utility-with-advanced-options"
        ) { (error) in
            if let error = error {
                printDebug(error.localizedDescription)
                //Handle registration error.
            }
        }

My configuration code and my uploading code is

    ///upload file func without use of delegates : - it is using closures
    func uploadFileToAWS(file: FileUploadModel,
                         success: @escaping(_ url: String, _ uri: String) -> Void,
                         progress: ((_ progressPercent:Float) -> Void)? = nil,
                         faliure: @escaping(_ message: String) -> Void) {
        
        //Look up the transfer utility object from the registry to use for your transfers.
//        self.transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "transfer-utility-with-advanced-options")
        guard let imageURL = URL(string: file.uri) else { return }
        
        let name = "\(Int(Date().timeIntervalSince1970))\(String.randomString(length: 8))\(file.contentType == .image ? ".jpeg" : ".mp4")"
        
        let expression = AWSS3TransferUtilityMultiPartUploadExpression()// AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = {(task, status) in
            printDebug(Date())
            printDebug(status.fractionCompleted)
            DispatchQueue.main.async(execute: {
                progress?(Float(status.fractionCompleted))
            })
        }
        // For public read
        expression.setValue("public-read", forRequestHeader: "x-amz-acl")
        
        var completionHandler: AWSS3TransferUtilityMultiPartUploadCompletionHandlerBlock?//AWSS3TransferUtilityUploadCompletionHandlerBlock?
        completionHandler = { (task, error) -> Void in
            DispatchQueue.main.async(execute: {
               if let error = error {
                    printDebug("Upload failed with error: (\(error.localizedDescription))")
                    faliure(error.localizedDescription)
                }

                else {
                    let url = URL(string: AppConstants.AWS_BASE_URL)
                    let publicURL = url?.appendingPathComponent(name).absoluteString
                    success(publicURL ?? "", imageURL.absoluteString)
                }
            })
        }
        
        
//        guard let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "transfer-utility-with-advanced-options") else { return }
        guard let tu = self.transferUtility else { return }

        tu.uploadUsingMultiPart(fileURL: imageURL, bucket: AppConstants.AWS_BUCKET, key: name, contentType: file.contentType == .image ? "image/jpeg" : "video/mp4",  expression: expression, completionHandler: completionHandler).continueWith { (task) -> Any? in
            //        transferUtility.uploadFile(imageURL, bucket: AppConstants.AWS_IMAGE_BUCKET, key: name, contentType: file.contentType == .image ? "image/jpeg" : "video/mp4", expression: expression, completionHandler: completionHandler).continueWith { (task) -> Any? in
            if let error = task.error {
                printDebug("error is: \(error.localizedDescription)")
                printDebug(task.error)
            }
            
            if let _ = task.result {
                printDebug(task)
                printDebug(task.result)
            }
            return nil
        }
    }

but the issue is after uploading one image, I am unable to upload the image again and for uploading again I need to restart my app please help

**Comment by amilham** [comment]
> **@desokroshan**
> SDK Version: [Using AWSCore (2.10.3), Using AWSS3 (2.10.3)]
> Dependency Manager: [Cocoapods]
> Swift Version : [4.2]
> 
> **Device information**
> I tested from iPhone 6 to iPhone x and same in the simulator
> iOS Version 11.4 and above
> 
> **Additional context**
> Some times uploading start after 5 to 10 seconds when I press the upload button and also there is no delay and in this situation, 1 mb image takes almost 17- 25 second to upload

@RajSingh007 Did you find a solution for this issue?
