### ISSUE TITLE
STS Role Assumption in AWS Console iOS Application

### ISSUE THREAD

**Issue by SeanSith** [aws-amplify/aws-sdk-ios#1850]
**Which AWS Services is the feature request for?**
AWS Console iOS Application (and potentially Android)

**Is your feature request related to a problem? Please describe.**
Our company (agency-style contract development) makes extensive use of Organizations for segmenting our customers' AWS infrastructure. As we do ongoing support for these customers, we need to perform operations in other accounts. We're beginning the use of cross-account role assumption via STS for the web console and AWSCLI, and would like to be able to do this on our mobile devices, as well, via the AWS Console mobile application. Right now we are forced to maintain IAM accounts in each AWS account in order to use the AWS Console application.

**Describe the solution you'd like**
We would like to be able to configure a profile in the AWS Console mobile application with a role the user can assume in order to perform actions. This profile should be able to point back to another configured account/profile for the base credentials STS needs.

**Describe alternatives you've considered**
Attempting to use the AWS web console on mobile is frustrating, at best. We've also considered writing our own front-end for the basic operations we need, but we figured that something like this may benefit others.

**Comment by desokroshan** [comment]
@SeanSith Thanks for reaching out. I will investigate into this and get back to you.

**Comment by palpatim** [comment]
@SeanSith This repo is specifically for the AWS SDK for iOS, which would encompass usage of the STS SDK in your app, but not the AWS Console mobile app or website. Feedback and feature requests for those products would be better sent through their respective "Contact" or "Support" links.

**Comment by SeanSith** [comment]
I agree. However,[ I am working as directed](https://twitter.com/AWSSupport/status/1171688241109639168), and I didn't see one when I went looking the other day.

**Comment by SeanSith** [comment]
Either way, in playing around with the application this morning, I found "Switch role" in the application menu, which seems to do what I was asking. It's either a welcome addition or my fault for not paying more attention (far more likely). Sorry for the trouble.
