### ISSUE TITLE
pintpont aws services issus

### ISSUE THREAD

**Issue by lilianafma** [aws-amplify/aws-sdk-ios#1851]
Rencently I had a problem with email campaing using pintpoint aws service. Within the message I used Message variables like {{User.UserAttributes.name}} but the users received the email with blank spaces.
I checked: the segments headers are ok , the message variables in the email template are ok too so  Any idea about what could had happened?

**Comment by desokroshan** [comment]
@lilianafma Thanks for reaching out. Can you share more details about the SDK you are using such as version number, relevant code snippet etc.

**Comment by palpatim** [comment]
@lilianafma To expand somewhat on @desokroshan's comment: this repo is specifically for the AWS SDK for iOS, which would encompass usage of the AWSPinpoint SDK, but not general usage questions such as emails from the service. General questions about using Pinpoint would be more appropriate on the [AWS Pinpoint Forum](https://forums.aws.amazon.com/forum.jspa?forumID=225).
