### ISSUE TITLE
AWSCloudFront not working in iOS? 

### ISSUE THREAD

**Issue by martaGonz** [aws-amplify/aws-sdk-ios#1853]
**Describe the question**
I am using AWS CloudFront to play videos hosted in my S3 bucket.  I am following AWS team suggestion of changing the video url from S3 to CloudFront since the app has many videos. However this is not working on the app, I am not sure what I am missing here.

**To Reproduce**
1. Create a new CloudFront Distribution
2. Put the video URL on the Swift Project
3. Play video on iOS app (it doesn't work)
4. Play same url in desktop (it works)

**Which AWS service(s) are affected?**
AWS CloudFront

**Expected behavior**
It should play the videos.  
Is CloudFront only for web? or it should work also on iOS apps?

**Comment by desokroshan** [comment]
@martaGonz Can you please let us know what SDKs and what version are you using in your iOS app? Also can you share relevant code snippets?

**Comment by palpatim** [comment]
@martaGonz To expand somewhat on @desokroshan's comment: this repo is specifically for the AWS SDK for iOS, which would encompass usage of the AWSS3 SDK and the AWSTransferUtility, but not general usage questions. General questions about using CloudFront resources in an iOS would be more appropriate on the [AWS CloudFront Forum](https://forums.aws.amazon.com/forum.jspa?forumID=46).

**Comment by martaGonz** [comment]
Hi! 

The problem was that I was using the url as "http://". The video worked after I used "https://" instead. 

SDKs I am using:

AWSAppSync (2.14.1)
AWSAuthCore (2.10.3)
AWSAuthUI (2.10.3)
AWSCognitoIdentityProvider (2.10.3)
AWSCognitoIdentityProviderASF (1.0.1)
AWSCore (2.10.3)
AWSMobileClient (2.10.3)
AWSS3 (2.10.3)
AWSUserPoolsSignIn (2.10.3)


And the code for creating the url's and playing the video
```
func playVideo() {

        s3Url = AWSS3.default().configuration.endpoint.url
        awscloudfrontString = "http://d2gppph6f8qk.cloudfront.net"
        awscloudfrontUrl = URL(string: awscloudfrontString)!
//        contentUrl = s3Url.appendingPathComponent(bucketName).appendingPathComponent(videoName)
        contentUrl = awscloudfrontUrl.appendingPathComponent(videoName)
        videoBackground.play(view: videoPlayer, url: contentUrl)

}
```

**Comment by palpatim** [comment]
I'm glad to hear you were able to resolve the issue. I'm going to close this issue, but if you encounter a problem using the SDK, please feel free to open a new one.
