### ISSUE TITLE
Cannot update to version 2.11.0 using cocoapods

### ISSUE THREAD

**Issue by JesusMartinAlonso** [aws-amplify/aws-sdk-ios#1858]
**Describe the bug**
I have tried to update AWS dependencies to the latest version (`2.11.0`) but I receive the following error when I execute `pod install` command

```
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In Podfile:
    AWSAppSync (= 2.14.1) was resolved to 2.14.1, which depends on
      AWSCore (~> 2.10.2)

    AWSPinpoint (~> 2.11.0) was resolved to 2.11.0, which depends on
      AWSCore (= 2.11.0)
```

I have printed the `AWSAppSync` pod spec dependency and it depends on a old version of `AWSCore` (`2.10.2`). This seems to be the problem. It has been reported also on #1812 

**To Reproduce**
1.- Given this podfile:

```
platform :ios, '11.0'

target 'ExampleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleProject

  pod 'AWSAPIGateway', '~> 2.11'
  pod 'AWSMobileClient' , '~> 2.11'
  pod 'AWSAuthUI', '~> 2.11'
  pod 'AWSUserPoolsSignIn', '~> 2.11'
  pod 'AWSAppSync', '2.14.1'
  pod 'AWSPinpoint', '~> 2.11.0'
end
```

2.- Execute `pod install` command
3.- An error is thrown:

```
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In Podfile:
    AWSAppSync (= 2.14.1) was resolved to 2.14.1, which depends on
      AWSCore (~> 2.10.2)

    AWSPinpoint (~> 2.11.0) was resolved to 2.11.0, which depends on
      AWSCore (= 2.11.0)
```

**Which AWS service(s) are affected?**

**Expected behavior**
A successfull pod dependencies instalation

**Environment(please complete the following information):**
 - SDK Version: 2.11.0
 - Dependency Manager: CocoaPods
 - Swift Version : 5.0

**Comment by palpatim** [comment]
@JesusMartinAlonso Thanks for pointing this out, we neglected to update the AppSync SDK when we released 2.11.0 last week. https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/296 should fix that

**Comment by palpatim** [comment]
Sorry about the premature close: I forgot that GH closes issues that are referenced as "Fixes".

We are releasing this now.

**Comment by palpatim** [comment]
This was released on https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/2.14.2

Please let us know if you have any problems

**Comment by JesusMartinAlonso** [comment]
Working! Thanks
