### ISSUE TITLE
Allow Pinpoint targeting client to update user attributes

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-ios#1861]
See https://github.com/aws-amplify/aws-sdk-android/issues/1207 for the Android equivalent feature request.

---

The `targetingClient`'s `updateEndpoint` flows do not expose the ability to update UserAttributes, which is supported by the Pinpoint [UpdateEndpoint](https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-endpoints-endpoint-id.html#UpdateEndpoint) operation.

These attributes are important to allow customers to create user segments for targeting.

Current workaround: use the low-level client (`AWSPinpointTargeting.default()`) to directly invoke an `updateEndpoint` operation with a hand-crafted `UpdateEndpoint` request. This is somewhat cumbersome, since it involves recreating the logic already present in [`-[AWSPinpointTargetingClient updateEndpointRequestForEndpoint:]`](https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSPinpoint/AWSPinpointTargetingClient.m#L289) and adding user attributes.

At a minimum, this effort should involve:

- Exposing the user attributes on the API's profile object
- Retrieving and populating those attributes during "get" operations
- Updating those attributes during "post" and "put" operations

**Comment by rjuliano** [comment]
This feature was added to amplify-android. 

https://github.com/aws-amplify/amplify-android/pull/1306
