### ISSUE TITLE
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by elGuille** [aws-amplify/aws-sdk-ios#1862]
**Describe the bug**
I have received the following warning from App Store Connect:

> We identified one or more issues with a recent delivery for your app, APP_NAME. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

**To Reproduce**
1. Look for UIWebView inside your project
Only the following folders use them on my app:
Bolts, FBSDKCoreKit and FBSDKLoginKit

**Which AWS service(s) are affected?**
AWSFacebookSignin

**Expected behavior**
No warning from App Store Connect.
Probably migrating to WKWebView instead

**Environment(please complete the following information):**
Using Bolts (1.9.0)
Using FBSDKCoreKit (4.42.0)
Using FBSDKLoginKit (4.42.0)
Using AWSAppSync (2.14.3)
Using AWSAuthCore (2.11.0)
Using AWSAuthUI (2.11.0)
Using AWSCognitoIdentityProvider (2.11.0)
Using AWSCognitoIdentityProviderASF (1.0.1)
Using AWSCore (2.11.0)
Using AWSFacebookSignIn (2.11.0)
Using AWSMobileClient (2.11.0)

 - Dependency Manager: Cocoapods
 - Swift Version: 5

**Device Information (please complete the following information):**
 - iOS Version: iOS 10.14.6

**Additional context**
I use Facebook login

**Comment by palpatim** [comment]
This would be fixed by #1397

**Comment by palpatim** [comment]
Tagged this as a "Duplicate", but I'm leaving it open since it increases the urgency of #1397.

**Comment by martaGonz** [comment]
Following. I understand we have to wait for an update of the SDKs to get this fixed, right? Can we do something else in the meantime? like deleting the pods with uiwebviews: Bolts, FBSDKCoreKit and FBSDKLoginKit

**Comment by palpatim** [comment]
The AWSFacebookSignIn code relies on those SDKs, so if your app uses Facebook sign in, you'll need to keep them in place. As noted in the linked issue (#1397) the latest FB SDK introduced some unexpected API changes that we have to figure out how to work with before we can upgrade.

**Comment by kneekey23** [comment]
Updated the FB SDK to 5.8. This has been released in the version 2.12.1 and we are now on 2.12.7
