### ISSUE TITLE
AWSS3TransferUtility download bug

### ISSUE THREAD

**Issue by xerxses** [aws-amplify/aws-sdk-ios#1933]
**Describe the bug**
If I want use default AWSS3TransferUtility. I have a problem with downloading files which I downloaded from AWS, remove them and repeat download in one session. I think problem in NSURLSession. I resolve it with reinitialise service, but it should have other way.

**To Reproduce**
1. Download files
2. Remove it locally
3. Repeat downloading
4. Error "load failed with error Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory. UserInfo { Signed URL }", but file will be accessed from browser by logged URL

**Which AWS service(s) are affected?**
AWSS3TransferUtility

**Expected behavior**
Download completed without errors.

**Environment(please complete the following information):**
 - SDK Version: 2.10.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhoneX, Simulator
 - iOS Version: iOS 12.2
 - Specific to simulators: Repeated on device iPhone X, iOS 12.2

**Comment by palpatim** [comment]
@xerxses Off the top of my head, I believe we do rely on the OS to cache downloads as appropriate, so that if the service reports the content hasn't changed and the cache hasn't expired, we would expect the OS to return the cached resource rather than attempt a re-download. It may be that by removing the local file, you're subverting that behavior by removing the resource the OS wants to return.

What use case are you trying to accomplish with the above scenario?

**Comment by xerxses** [comment]
@palpatim we have next scenario:
1) user login
2) download needed resources
3) logout with cleanup user data(which can be shared between few accounts)
4) another user login and couldn't download files which was downloaded on second step

**All steps will be reproduced in one session**

**Comment by lawmicha** [comment]
I've seen downloading to an incorrect path will cause permission denied errors, uploading from non-existent file will cause no such file or directory error, but not when downloading the file and then getting no such file or directory error. Can you clarify with some code snippet how are doing this?

When you do step 3. clean up user data, how do you delete the file? 
In step 4, if the file is deleted, how do you recreate the file path to the file to be downloaded to?

Perhaps when you restart the app, there is some instantiation that is happening that is missing when after you delete the file and do not restart. However, I tested the code below and seems to work fine when I execute it multiple times:

```
let filePath = NSHomeDirectory() + "myfile" + ".tmp"
print(filePath)
if FileManager.default.fileExists(atPath: filePath) {
    print("file exists")
} else {
    print("file does not exist")
}

print("deleting file")
do {
    try FileManager.default.removeItem(atPath: filePath)
} catch {
    print("failed to delete file")
}

print("deleted file")
if FileManager.default.fileExists(atPath: filePath) {
    print("file exists")
} else {
    print("file does not exist")
}

transferUtility.download(
    to: fileURL,
    key: S3DownloadKeyName,
    expression: expression,
    completionHandler: completionHandler).continueWith...
    ...
```

What I'm testing here is that every time i do a download to `filePath`, I am making sure the file is deleted.

**Comment by xerxses** [comment]
@lawmicha code example
```
let fileURL = NSHomeDirectory() + "myfile" + ".tmp"

print("first download in session")

transferUtility.download(
    to: fileURL,
    key: S3DownloadKeyName,
    expression: expression,
    completionHandler: completionHandler).continueWith...

print("deleting file")

do {
    try FileManager.default.removeItem(atPath: fileURL.path)
} catch {
    print("failed to delete file")
}

print("second download in session")

transferUtility.download(
    to: fileURL,
    key: S3DownloadKeyName,
    expression: expression,
    completionHandler: completionHandler).continueWith...

**Comment by lawmicha** [comment]
Hi @xerxses, are you still seeing this issue? I ran this scenario in a unit test which downloads to fileURL, deletes the file, and then downloads to the same fileURL. These are running sequentially by blocking with the `wait` on the expectations

```
 func testExample() {
        let downloadCompleted = expectation(description: "download completed")
        let filePath = NSTemporaryDirectory() + "myfile2" + ".img"
        print("the filePath is \(filePath)")
        let fileUrl = URL(fileURLWithPath: filePath)

        print("first download in session")
        let S3DownloadKeyName: String = "public/test-image.png"    // Name of file to be downloaded
        let expression = AWSS3TransferUtilityDownloadExpression()
        expression.progressBlock = {(task, progress) in
            print("progress \(progress)")
        }

        AWSS3TransferUtility.default().download(to: fileUrl, key: S3DownloadKeyName, expression: expression) { (task, url, data, error) in
            if let error = error {
                print("Failed \(error)")
                XCTFail("Failed")
            }

            downloadCompleted.fulfill()
        }
        wait(for: [downloadCompleted], timeout: 100)

        do {
            try FileManager.default.removeItem(atPath: filePath)
            print("Deleted the file")
        } catch {
            print("failed to delete file \(error)")
        }

        let downloadCompleted2 = expectation(description: "download completed")
        AWSS3TransferUtility.default().download(to: fileUrl, key: S3DownloadKeyName, expression: expression) { (task, url, data, error) in
            if let error = error {
                print("Failed \(error)")
                XCTFail("Failed")
            }

            downloadCompleted2.fulfill()
        }
        wait(for: [downloadCompleted2], timeout: 100)
    }
```

These calls are asynchronous so can you confirm that you are not deleting a file while you are downloading to it? You can also provide more logs by enabling verbose logs in your app
```
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```
