### ISSUE TITLE
Closure not called on login

### ISSUE THREAD

**Issue by sub96** [aws-amplify/aws-sdk-ios#1934]
Describe the bug**
Using the latest iOS SDK (2.10.3), there is a function where the closure is not called:

`AWSMobileClient.sharedInstance().showSignIn(navigationController:nav, signInUIOptions: config) { (userState, error) in …`

To Reproduce**
Steps to reproduce the behaviour:
When a user registers a new account, he gets an email with a temporary password that he needs to login with.
Upon login with the needed credentials, the showSignIn callback does not get triggered.
Please note that if the user enters a wrong password he will get a wrong password pop-up.

Which AWS service(s) are affected?**
AWS Cognito

Expected behavior**
I would expect the code to execute as expected.

Environment(please complete the following information):**
 - SDK Version: 2.10.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5

Device Information (please complete the following information):**
 - Device: iPhone 8+
 - iOS Version: 12.4

**Comment by palpatim** [comment]
@sub96 The latest SDK is actually 2.11.1, and we fixed several errors in the Authentication area, including missing callbacks, in 2.11.0. Can you reproduce this issue in the latest SDK?

**Comment by sub96** [comment]
I tried the latest SDK 2.11.1 and I'm still able to reproduce the issue.
Any ideas?

**Comment by royjit** [comment]
I guess this is a known bug in the SDK as reported [here](https://github.com/aws-amplify/aws-sdk-ios/issues/1711). 
If your use in the state `FORCE_CHANGE_PASSWORD` ?

**Comment by sub96** [comment]
Yes I’m in the ‘FORCE_CHANGE_PASSWORD’ state.
So this issue is not fixed in the last SDK?

**Comment by royjit** [comment]
Hi @sub96 This is not fixed in the latest SDK. We are actively working on a fix, will update here when we have more information.

**Comment by royjit** [comment]
I have created a PR to handle this scenario. Please refer to the original issue #1711 for details. Closing this issue as a duplicate.

**Comment by sub96** [comment]
Hi @royjit, 

in the version 2.12.1 the callback is called and I can reset my password.
The problem now is that if the user press on the `Update Password` button twice the app will crash, the reason is: 
`Cannot set the result on a completed task.`

Thanks for your help!
