### ISSUE TITLE
Subscription suffers delay when receiving new Data

### ISSUE THREAD

**Issue by oahhariri** [aws-amplify/aws-sdk-ios#1936]
**Describe the bug**
Subscription suffer Delay when receiving new data after the Subscription starts and then wait for new data for some time (in my case 15+ minutes). then whenever new data is send to the Subscription ,it get delayed for 2-10 minutes

Note:
-subscription status show Connected and no errors 
-All subscriptions are started from Singleton class

**To Reproduce**
1- Start subscription 
2- send new data to the subscription 
3- wait for 15-25 minutes 
4- send new data to the subscription 
5- the new data will be received after (2-10 minutes)

**Expected behavior**
 subscription should get live data without any delays as long as there is no errors
 
**Environment(please complete the following information):**
 - SDK Version: 2.11.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: [iPhone XS Max, iPhone6s , iPad 9.7 pro]
 - iOS Version: [OS 12.4.1 ,iOS 13.0]

**Comment by royjit** [comment]
Hi @oahhariri Sorry to hear that you are having issue with the SDK. Could you please provide which all AWS services you are using? Can you share your Cocoapods details.

**Comment by oahhariri** [comment]
-Which all AWS services you are using? Can you share your Cocoapods details.?

 pod 'AWSMobileClient'
 pod 'AWSAppSync'

-Any code sample that can help us debug the issue?

there is nothing special i did , i start a subscription as mentioned in the documentation :

![Screen Shot 2019-09-25 at 1 56 59 AM](https://user-images.githubusercontent.com/26073769/65556290-cdc5d300-df37-11e9-976e-85a0a7e3299c.png)

then i write to a Dynamodb so that subscription get triggered whenever new record is created

![Screen Shot 2019-09-25 at 1 51 49 AM](https://user-images.githubusercontent.com/26073769/65556079-0f09b300-df37-11e9-93af-7e56c54a87a4.png)


i found that these scripts : 
AWSIoTMQTTClient.m
AWSMQTTMessage.m
AWSMQTTSession.m

had a variables  (keepAliveInterval , keepAlive) 
i changed the the value of (keepAliveInterval and keepAlive) from 600 second to 120 second and that seems to solve the issue and all my subscription receives live data without any delays

i don't know if this could help but just by changing the mentioned values , subscription work perfectly

**Comment by royjit** [comment]
@oahhariri 

Apologies for the delay. We have made a lot of changes in the subscription code base in the latest SDK. Could you please check if the issue still persists? https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.0.0
