### ISSUE TITLE
Detect new user has been created with Drop Auth UI

### ISSUE THREAD

**Issue by martaGonz** [aws-amplify/aws-sdk-ios#1938]
**State your question**
I am using “drop-in” UI. 
Is there a way to detect that a new user has been created? I need it in order to choose the correct query towards the database. If a user is not new, I use _updateMutation_, but if a user is new, I have to use _createMutation_.

**Which AWS Services are you utilizing?**
Cognito
Drop-in Auth
AppSync

**Provide code snippets (if applicable)**
I have a profile tab where the user can edit personal data 

```
@IBAction func saveBtnTapped(_ sender: Any) {
          createData()  // for new user
        //  updateData() // for repeating user
    }

    func createData() {

        appSyncClient?.perform(mutation: CreateUserMutation(input: createQuery)) {

    }

    func updateData() {

        appSyncClient?.perform(mutation: UpdateUserMutation(input: updateQuery))

    }


```
**Environment(please complete the following information):**
 - SDK Version: latests
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Comment by royjit** [comment]
Hi @martaGonz Thank you for reaching out. What do you mean by a new user? If its the recently signed up user, where are you doing the sign up?

The SDK as such doesnot have any way of checking if its a new user. Maybe you can make use of [custom attributes](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes) to add your own information to identify the user is new or not.

**Comment by martaGonz** [comment]
Hello, thanks for your reply.
Yes, when I say a new user has been created I mean that is a recently signed up user. I use Amazon Cognito Hosted UI so I don't really know if the user is doing a sign in or a sign up. 

I use the code provided by amplify docs 

```
AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, hostedUIOptions: hostedUIOptions) { (userState, error) in
    if let error = error as? AWSMobileClientError {
        print(error.localizedDescription)
    }
    if let userState = userState {
        print("Status: \(userState.rawValue)")
    }
}
```

**Comment by royjit** [comment]
Thank you for the clarification. Do you think [lambda triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) work for your use case?

**Comment by martaGonz** [comment]
Thanks. I am avoiding lambda functions because I don't know how to program them.  For simplicity I used this Amazon Hosted UI but if there is no way to know when a user is created, I can remove it and make a custom login/signup screen.

**Comment by royjit** [comment]
Hosted UI doesnot have any callback to check if the user is new. You can check this [link](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html) about lambda trigger that called when a new user is confirmed. There is some nodejs sample code as well.

**Comment by martaGonz** [comment]
Got it, thank you so much!
