### ISSUE TITLE
User not signed in after reopening app using new sdk initializer

### ISSUE THREAD

**Issue by JesusMartinAlonso** [aws-amplify/aws-sdk-ios#1939]
**Describe the bug**
I'm using the new initializer released in 2.11.0 (https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.11.0). The app seems to work properly (users can sign in) but if the app is closed and reopened again, the user is not signed in (`AWSMobileClient.default().isSignedIn` returns `false`). However, I expect to be true

**To Reproduce**
1. In `didFinishLaunchingWithOptions` method initialize `AWSMobileClient` using new initializer:

```
     _  = AWSMobileClient.init(configuration: awsconfigurationDictionary)

```

2. Sign in with an user using cognito user pools:
` AWSMobileClient.default().signIn(username: username, password: password) `

3. Close app
4. Reopen app, and call `AWSMobileClient.default().isSignedIn`. This returns `false` but I expect `true`

**Which AWS service(s) are affected?**

Cognito, AWSAmplify

**Expected behavior**
I expect user to be signed in after closing and reopening the app

**Environment(please complete the following information):**
 - SDK Version: 2.11.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone XS simulator
 - iOS Version: 12.4

**Comment by royjit** [comment]
Hi @JesusMartinAlonso Did you call `AWSMobileClient.default().initialize`? As shown [here](https://aws-amplify.github.io/docs/ios/manualsetup#configure-using-an-in-memory-object) you need to call `initialize` after init.
```
 _  = AWSMobileClient.init(configuration: awsconfigurationDictionary)
AWSMobileClient.default().initialize { (userState, error) in
    // initialization logic
}  
```
Please let us know if this fixes the issue.

**Comment by JesusMartinAlonso** [comment]
Yes. It seems to work well. Thank you!
