### ISSUE TITLE
Cartfile to download parts framework

### ISSUE THREAD

**Issue by hanxia** [aws-amplify/aws-sdk-ios#1941]
Dear,

I am a new user of AWS SDK for iOS, when I created Cartfile as **github "aws-amplify/aws-sdk-ios"**, it will download about 41 framework(it almost take me 30 minutes), but actually I only need some of them.

I am not sure, if there is some way to only download some frameworks, for example **github "aws-amplify/aws-sdk-ios/AWSXXService"** 

Thanks for your time.

**Comment by royjit** [comment]
Hi @hanxia Thank you for reaching out. Unfortunately the way our SDK and carthage is setup, this is how the build works. A work around is to directly add the framework binary into your project. But this binary is not build against swift 5.0.  We have an active [PR #1935](https://github.com/aws-amplify/aws-sdk-ios/pull/1935) that would enable building against swift 5.0, once its released the binary will work on the newer platform.
