### ISSUE TITLE
OTP based login using Cognito custom authentication

### ISSUE THREAD

**Issue by anees17861** [aws-amplify/aws-sdk-ios#1951]
**State your question**
How to use Cognito iOS SDK for custom Authentication?

I have followed [AWS re:Invent 2016: Add User Sign-In, User Management, and Security with Amazon Cognito (MBL310)](https://www.youtube.com/watch?v=8DDIxqIW1sM) to setup the lambdas.

I'm able to successfully receive the sms and login using android sdk but not sure how the process works in iOS

I've attached the code below. Here the startCustomAuthentication gets called properly and right after that getCustomChallengeDetails is called as well. But the authentication input returns empty. In android when the same callback is called the cloud has done sending the sms and all I have to is set the result to the continuation once the user enters it

I observed that the DefineAuthChallenge trigger is never fired in case of iOS and thus the sms is never sent

One more thing I observed is if I set an empty result in getCustomChallengeDetails (commented in the code) it sends the sms but startCustomAuthentication gets called again making it fall into an infinite loop.

**Which AWS Services are you utilizing?**
Cognito
Lambda

**Provide code snippets (if applicable)**

Call to initiate custom auth
```
self.pool = AWSCognitoIdentityUserPool(forKey: AWSCognitoUserPoolsSignInProviderKey)
self.pool?.delegate = self
self.user = self.pool?.getUser(username!)
self.user?.getSession()
```

Interactive Authentication delegate
```
extension LoginVC : AWSCognitoIdentityInteractiveAuthenticationDelegate {
    func startCustomAuthentication() -> AWSCognitoIdentityCustomAuthentication {
        print("starting custom auth for user : \(self.user?.username ?? "nil")")
        if let otpVC = self.presentedViewController as? OTPViewController {
            return verifyVC
        }
        let otpVC = OTPViewController.init(nibName: "OTPViewController", bundle: nil)
        otpVC.user = self.user
        DispatchQueue.main.async {
            self.present(otpVC, animated: true, completion: nil)
        }
        return otpVC
    }
}
```

Custom Auth delegate
```
extension OTPViewController : AWSCognitoIdentityCustomAuthentication {
    func getCustomChallengeDetails(_ authenticationInput: AWSCognitoIdentityCustomAuthenticationInput, customAuthCompletionSource: AWSTaskCompletionSource<AWSCognitoIdentityCustomChallengeDetails>) {
        self.otpLoginContinuation = customAuthCompletionSource
        print(authenticationInput.challengeParameters) //Gives empty dictionary
            //customAuthCompletionSource.set(result: AWSCognitoIdentityCustomChallengeDetails()) //if result is set with empty response sms is sent but startCustomAuthentication gets called again making it fall into an infinite loop

    }
    
    func didCompleteStepWithError(_ error: Error?) {
        if let error = error as NSError? {
            print("error : \(error)")
        } else {
            print("success")
        }
    }
}
```

Once user enters the OTP
```
self.otpLoginContinuation?.set(result:
                        AWSCognitoIdentityCustomChallengeDetails.init(challengeResponses: [
                            "USERNAME" : self.user!.username!,
                            "ANSWER" : otpString
                        ]))
```
**Environment(please complete the following information):**
 - SDK Version: 2.11.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: Simulator: iPhone Xr
 - iOS Version: iOS 12.2
 - Specific to simulators: No

**Comment by lawmicha** [comment]
Hi @anees17861 

Thanks for detailed explanation of your issue, just a quick note before we dive further, we are currently working on custom auth with AWSMobileClient and will be releasing that soon (in PR here https://github.com/aws-amplify/aws-sdk-ios/pull/1860 ). Looping in @royjit to see if he can identify that this would work for your use case as he has some more context on custom auth.

**Comment by royjit** [comment]
Yes, looks like you can use AWSMobileClient with custom authentication. This should be available in the next release.

**Comment by anees17861** [comment]
I have something similar to Amazon app login. User can login with either phone number/password or with otp. For password flow I call getsession with username and password. For otp flow I set a delegate and call getsession without any parameters.

As for define auth challenge, I don't have access to a desktop right now, so I'll share it later. But it's a word to word copy of the trigger provided in the aws reinvent video (link in previous comment)

**Comment by anees17861** [comment]
Define auth challenge
```
exports.handler = function (event,context,callback) {
    console.log('EVENT request', event.request);
    // TODO implement
    if(event.request.session.length === 0){
        event.response.issueTokens = false;
        event.response.failAuthentication = false;
        event.response.challengeName = 'CUSTOM_CHALLENGE';
    }
    else if(event.request.session.length === 1
        && event.request.session[0].challengeName === 'CUSTOM_CHALLENGE'
        && event.request.session[0].challengeResult === true){
        event.response.issueTokens = true;
        event.response.failAuthentication = false;
    }
    else {
        event.response.issueTokens = false;
        event.response.failAuthentication = true;
    }
    console.log('EVENT response', event.response);
    callback(null,event);
};
```
Create auth challenge
```
var AWS = require('aws-sdk');

exports.handler = function (event,context,callback) {
    console.log('EVENT request', event.request);
    // TODO implement
    if(event.request.session.length === 0
        &&  event.request.challengeName === 'CUSTOM_CHALLENGE' ){
        //Create a otp
        var answer = Math.random().toString(10).substr(2,6);
        
        //sns sms
        var sns = new AWS.SNS({region:'ap-southeast-1'});
        sns.publish({
            Message: 'your otp: '+answer,
            PhoneNumber: event.request.userAttributes.phone_number
        },function(err,data){
           if(err){
               console.log(err.stack);
               return;
           }
           console.log(`SMS sent to ${event.request.userAttributes.phone_number} and otp = ${answer}`);
        });
        
        //set return params
        event.response.publicChallengeParameters = {};
        event.response.privateChallengeParameters = {};
        event.response.privateChallengeParameters.answer = answer;
        event.response.challengeMetadata = 'PASSWORDLESS_CHALLENGE';
    }
    console.log('EVENT response', event.response);
    callback(null,event);
};
```
Verify Auth Challenge
```
exports.handler = function (event,context,callback) {
    console.log(`EVENT request`,event.request);
    // TODO implement
    event.response.answerCorrect = (event.request.privateChallengeParameters.answer === event.request.challengeAnswer);
    console.log(`isAnswerCorrect = ${event.response.answerCorrect}`)
    if(!event.response.answerCorrect){
        console.log(`Correct answer = ${event.request.privateChallengeParameters.answer}`);
        console.log(`Given answer = ${event.request.challengeAnswer}`);
    }
    console.log(`EVENT response`,event.response);
    callback(null,event);
};
```
Sorry for the delay, got occupied elsewhere

**Comment by royjit** [comment]
@anees17861 Thank you for providing the details. I was able to make this work by returning an empty value for the first invocation of `getCustomChallengeDetails` and on the second invocation pass the challenge response to the continuation. 

```
if (authenticationInput.challengeParameters.count > 0) {
            let details = AWSCognitoIdentityCustomChallengeDetails(challengeResponses: ["ANSWER" : "1133"])
            customAuthCompletionSource.set(result: details)
 } else {
            let details = AWSCognitoIdentityCustomChallengeDetails()
            customAuthCompletionSource.set(result: details)
}    

```

Can you please check if this works for you?

**Comment by anees17861** [comment]
`
self.otpLoginContinuation = customAuthCompletionSource
        if(authenticationInput.challengeParameters.count == 0) {
            print("sending user name")
            customAuthCompletionSource.set(result: AWSCognitoIdentityCustomChallengeDetails())
        }
`

Currently I am doing this since I need to wait for the user to enter the otp. It works fine.
But is this the expected way?

Also how should I handle didCompleteStepWithError(_ error : Error?)? It gets fired in both cases. I have to give feedback to the user if otp was success. The only way I can think of is simply maintaining a boolean flag.

**Comment by royjit** [comment]
Unfortunately this is how the SDK is setup and I cannot find an easy way to handle this.  One work around is to listen to the getSession() task and handle success:

```
self.currentUser?.getSession().continueWith(block: { (task) -> Any? in
                            if let session = task.result {
                                // Auth completed.
                            } 
                            return nil
 })
```

We will take this up as a feature request and will update here when we implement this.

**Comment by anees17861** [comment]
Hi,

Thanks for all the help. The login functionality is working fine. But there is another issue I'm facing now.

I'm using Cognito to sign network api calls. To achieve this I'm calling getsession before every api call. This causes the delegate to fire up again. And I end up receiving multiple otps. I tried to set delegate to nil on continueWith() but that was not possible since it's not an optional. How should I solve this. Also if there is a better way to sign the api than calling get session please let me know

**Comment by dholdren** [comment]
@royjit does AWSMobileClient work with this type of custom auth (passwordless) ?

**Comment by royjit** [comment]
Apologies for the delayed response

@anees17861 
`getCustomChallengeDetails ` delegate method will be fired only when the refresh token is expired and the user has to sign In again. 
If you are still seeing this problem please open a new issue with details and we will investigate.

@dholdren 
Yes, AWSMobileClient supports custom auth. You can find more details [here](https://aws-amplify.github.io/docs/sdk/ios/authentication#custom-authentication-in-amplify).
