### ISSUE TITLE
iOS Dark Mode breaks AWSMobileClient signin page

### ISSUE THREAD

**Issue by dconroy** [aws-amplify/aws-sdk-ios#1953]
**Describe the bug**
While the Amplify AWS Mobile client provides a fantastic experience for my users that use light mode on their iPhone, those that are using dark mode are faced with a number of issues. 

1) The text they enter is same color of the background
2) The padding on the inputboxes makes it seem like a broken form

**To Reproduce**
1. Use a device with ios 13 or greater
2. Click on display and brightness, and set appearance to Dark
3. Use any app that uses the AWSMobileClient sign in UI

**Which AWS service(s) are affected?**

AWS Cognitio, Auth SDK

**Expected behavior**
I expect the modal to react appropriately to the dark theme and make sane choices for text colors.

**Screenshots**
https://www.dropbox.com/s/7xo6xno92pz3j4r/RPReplay_Final1570331080.MP4?dl=0

**Environment(please complete the following information):**
 - Dependency Manager: [e.g. Cocoapods]
 - Swift Version : e.g. 4.0
PODS:
  - Alamofire (4.9.0)
  - AppleWelcomeScreen (1.0.2):
    - SnapKit
  - AWSAuthCore (2.11.0):
    - AWSCore (= 2.11.0)
  - AWSAuthUI (2.11.0):
    - AWSAuthCore (= 2.11.0)
    - AWSCore (= 2.11.0)
  - AWSCognitoIdentityProvider (2.11.0):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
    - AWSCore (= 2.11.0)
  - AWSCognitoIdentityProviderASF (1.0.1)
  - AWSCore (2.11.0)
  - AWSMobileClient (2.11.0):
    - AWSAuthCore (= 2.11.0)
    - AWSCognitoIdentityProvider (= 2.11.0)
  - AWSS3 (2.11.0):
    - AWSCore (= 2.11.0)
  - AWSUserPoolsSignIn (2.11.0):
    - AWSAuthCore (= 2.11.0)
    - AWSCognitoIdentityProvider (= 2.11.0)
  - ESTabBarController-swift (2.7)
  - lottie-ios (3.1.2)
  - Mapbox-iOS-SDK (5.3.0)
  - Realm (3.17.3):
    - Realm/Headers (= 3.17.3)
  - Realm/Headers (3.17.3)
  - RealmSwift (3.17.3):
    - Realm (= 3.17.3)
  - SnapKit (5.0.1)
  - WSTagsField (5.0.0)

**Device Information (please complete the following information):**
 - Device: Iphone X
 - iOS Version: [e.g. iOS13.1.2]

**Comment by drochetti** [comment]
Hi @dconroy, I really appreciate the detailed report, the screenshot makes the impact very clear. Thanks!

I'm investigating a fix for this and will keep you posted.

**Comment by palpatim** [comment]
This was released in [2.12.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.12.0). Please let us know if you have any issues with this.
