### ISSUE TITLE
Problem with Pre-signed URL generation

### ISSUE THREAD

**Issue by tapparello** [aws-amplify/aws-sdk-ios#1957]
**Describe the bug**
I am trying to generate a pre-signed URL to allow the users to stream videos directly from a S3 bucket. The user is logged in via a Cognito UserPool, and upload/download through the TransferUtility works fine. However, when I am trying to get a pre-signed URL following the example presented in the [documentation](https://aws-amplify.github.io/docs/ios/storage#temporary-permissions-via-pre-signed-urls) I am getting the error:

`{"__type":"NotAuthorizedException","message":"Unauthenticated access is not supported for this identity pool."}`

Also, in order to get `AWSS3PreSignedURLBuilder.default()` to work, I add to do the following:

`let credentialProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: "us-XXX-X:XXXXX")`
 `let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialProvider)`
`AWSServiceManager.default().defaultServiceConfiguration = configuration`

While, instead, I am initializing the `AWSMobileClient.default()` and all the other AWS services that I am using through awsconfiguration.json. 

**Which AWS service(s) are affected?**
AWS S3

**Expected behavior**
I am expected to get the pre-signed URL. 

Also, I was expecting the AWSS3PreSignedURLBuilder to be able to get my default configuration from the file awsconfiguration.json, so this could be what is causing the issue with the AWSS3PreSignedURLBuilder?

**Environment(please complete the following information):**
 - SDK Version: 
AWSAppSync (2.14.3)
AWSAuthCore (2.11.1)
AWSAuthUI (2.11.1)
AWSCognitoIdentityProvider (2.11.1)
AWSCognitoIdentityProviderASF (1.0.1)
AWSCore (2.11.1)
AWSMobileClient (2.11.1)
AWSPinpoint (2.11.1)
AWSS3 (2.11.1)
AWSUserPoolsSignIn (2.11.1)

 - Dependency Manager: [e.g. Cocoapods, Carthage]
Cocoapods
 - Swift Version : 4

**Device Information (please complete the following information):**
 - Device: iPhone XS Max and different simulators
 - iOS Version: 13.1.1

**Additional Comments:**
Any suggestion/help is greatly appreciated!!

**Comment by tapparello** [comment]
While waiting for feedback on this, I got the following workaround to work. 

I start by connecting the AWSS3PresignedURLBuilder configuration to the AWSS3TransferUtility configuration as follows:

In `AppDelegate.swift`:
`AWSS3PreSignedURLBuilder.register(with: AWSS3TransferUtility.default().configuration, forKey: "USEast1S3PreSignedURLBuilder")`

When I need the pre-signed URL, I use:

`let presignedURLBuilder = AWSS3PreSignedURLBuilder.s3PreSignedURLBuilder(forKey: "USEast1S3PreSignedURLBuilder")`

In this way, the credentials used by the AWSS3PreSignedURLBuilder are linked to the AWSS3TransferUtility, and any use of the latter also refreshes the credentials needed by the AWSS3PreSignedURLBuilder.

Again, this is just a temporary workaround that I found to get the AWSS3PreSignedURLBuilder to work consistently...

**Comment by OlegGordiichuk** [comment]
@tapparello Thx this temp solution is working on my side as well.

**Comment by atierian** [comment]
Closing as resolved as the [documented approach](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSS3/Classes/AWSS3PreSignedURLBuilder.html) works. If you're still experiencing this issue, please let us know and we'll reopen / investigate.
