### ISSUE TITLE
AWSAuthUIViewController crashes when pressing cancel button

### ISSUE THREAD

**Issue by RushanB** [aws-amplify/aws-sdk-ios#1961]
My code:
![image](https://user-images.githubusercontent.com/16970644/66453590-e0113800-ea32-11e9-9b05-28c530993d6c.png)

My UI:
![image](https://user-images.githubusercontent.com/16970644/66453686-40a07500-ea33-11e9-8623-6417d0d37e26.png)

My XCode log:
![image](https://user-images.githubusercontent.com/16970644/66453719-5dd54380-ea33-11e9-90f9-b9a7588beabc.png)

**Comment by drochetti** [comment]
Hi Rushan, can you provide more info about your project and environment?

```
**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:
```

**Comment by palpatim** [comment]
@RushanB We did attempt to reproduce this in one of our apps, but weren't able to see this behavior. Additional code snippets and a crash log would be useful.

In the meantime, I do want to point out that if you happen to be presenting another modal on top of the Auth UI, and then dismiss the modal, iOS may dismiss all open modals, which would cause you to lose your reference, which might result in a crash. Again, it depends a bit on your use case and how you invoke the flows, so code snippets would be helpful.
