### ISSUE TITLE
Sometimes User is authenticated, sometimes not

### ISSUE THREAD

**Issue by ChrisInspect** [aws-amplify/aws-sdk-ios#1964]
**State your question**
I followed the official iOS-SDK-Guide ([https://aws-amplify.github.io/docs/ios/authentication]()) and created an custom-login with user-pool and identity-pool. I linked them together, so I can authenticate an unauthenticated user by Cognito. 
For test purposes I linked S3FullAccess to the authenticated role from my identity-pool.
Now I made a "DownloadButton" inside my app to test this role and here is my problem.
From ten times starting my app and login, only 1-3 times the user is authenticated and can download the testfile. The other times I get the "access denied" error, so I can't download the file.
The user is always the same, without changing anything.
I searched for days for a solution, but I find nothing.
I don't know either where to check anything inside my code or my aws-management-console, because this issue occurs not always.

**Which AWS Services are you utilizing?**
AWSMobileClient
AWSCognito
AWSS3

**Environment(please complete the following information):**
 - Dependency Manager: [Cocoapods]
 - Swift Version : [5.0]

**Device Information (please complete the following information):**
 - Device: [Simulator]
 - iOS Version: [iOS 13]

**Comment by ChrisInspect** [comment]
After reading a lot in other issues here, I guess I made a big mistake. 
I initialized credentials from code and from awsconfiguration.json. So maybe sometimes they blocked each other.

I deleted the entire code in my AppDelegate and now it seems to work. 
I will test this a lot more this afternoon and will let you know, if the problem still exists.

**Comment by drochetti** [comment]
Hi @ChrisInspect, thanks for reporting to us. That is correct, only one configuration method is support at a time.

I'll mark this as "closing soon" for the time being.
