### ISSUE TITLE
How to get aws refreshed token after the token is expired.

### ISSUE THREAD

**Issue by Jitenderios** [aws-amplify/aws-sdk-ios#1965]
static func GetAWSTokens(onCompletion:@escaping (Bool) -> Void) {
        AWSMobileClient.sharedInstance().getTokens({(tokens, error) in
            if let tokens = tokens {
           
                print(tokens.accessToken?.tokenString);
                if let accessToken = tokens.accessToken?.tokenString {
                    RequestModel.saveAccessToken(token: accessToken)
                    onCompletion(true)
                }
                onCompletion(false)

            } else {
                print(error?.localizedDescription ?? "error")
                onCompletion(false)
            }
        })
    }

Above is my code to generate the token. Everytime the token expires i call that method to get new token. I need this inorder to authenticate my local app API calls. I had to pass the token in the API header. Only with valid token I get response from server. Server is validating the token which we are passing. As these token gets expires every 1 hour, I had to call this same to regenerate new token but sometimes its not working. Can someone suggests how can we get the refreshed token when the user is already logged in.

**Comment by palpatim** [comment]
@Jitenderios A few points:

1. AWSMobileClient caches tokens internally, so if you're using your call to `RequestModel.saveAccessToken` to cache tokens, you should consider removing it in favor of a call to `AWSMobileClient.getTokens()` in the flow for each request
1. You have a bug in your code snippet: you invoke `onCompletion(true)` but don't return from that block, which means your very next call is to `onCompletion(false)` :)
1. For a more in-depth discussion of token fetching and refreshing see [the Amplify Documentation](https://aws-amplify.github.io/docs/ios/authentication#token-fetch-and-refresh)

Hope this helps.

**Comment by Jitenderios** [comment]
@palpatim Thanks for your prompt response. Your points helped me in fixing my issue. Thanks alot.
For the people who are looking out to this thread for solution, I will share what I did to fix this issue.

if AWSMobileClient.sharedInstance().currentUserState == .signedIn
                        {
                           print("User already signed in")
                            LoginViewModel.GetAWSTokens(onCompletion: {(success) in
                                if let updateRequest = request.updatedTokenHeader() {
                                    self.performRequest(request: updateRequest, canCancelRequest: canCancelRequest, completion: completion)
                                }
                            })
                        }else{
                            print("User not in signed in")
                            self.apiHitCount = 0
                           ProfileModel.logoutUser()
                        }

After the token is exipired, I am basically checking the currentUserState before calling for getToken method. If currentUserState is .signedIn, then only I am calling for getToken method otherwise I ask user to login again.

Thanks,
Hope this helps to others
