### ISSUE TITLE
Set used tts engine for Polly

### ISSUE THREAD

**Issue by hffmnn** [aws-amplify/aws-sdk-ios#1973]
**State your question**

How to set the used TTS engine polly should use? We are generating a URL via the code snippet below. Question is how to set the TTS engine it should use because we would like to try out `AWSPollyEngineNeural `.

**Which AWS Services are you utilizing?**

Polly

**Provide code snippets (if applicable)**

```
func generatePollyURL(voice: String, ssml: String, callback: @escaping (String?, NSError?) -> ()) {
        let pollyVoice = try! AWSMTLJSONAdapter.model(of: AWSPollyVoice.self, fromJSONDictionary: ["Id": voice], error: ()) as! AWSPollyVoice
        let request = AWSPollySynthesizeSpeechURLBuilderRequest()
        request.text = ssml
        request.textType = .ssml
        request.outputFormat = AWSPollyOutputFormat.mp3
        request.voiceId = pollyVoice.identifier
       
        let task = AWSPollySynthesizeSpeechURLBuilder.default().getPreSignedURL(request)
        task.continueWith() { (awsTask: AWSTask<NSURL>) -> Any? in
            if (awsTask.error != nil) {
                callback(nil, awsTask.error as NSError?) 
            } else {
               let url = awsTask.result!
                callback(url.absoluteString!, nil)
            }
            
            return nil
        }
    }
```

**Environment(please complete the following information):**
- AWSPolly 2.10.3, 
- AWSCore 2.10.3
- Dependency Manager: Cocoapods
- Swift Version: 5.0

**Device Information (please complete the following information):**
 - Device: iPhone7
 - iOS Version: iOS 13

**Comment by palpatim** [comment]
@hffmnn The presigned URL builder, as a hand-generated component of the SDK, does not currently provide the ability to specify the engine for a request. We'll take this as a feature request and update this ticket when we have more information.

**Comment by hffmnn** [comment]
Ok, thanks for the update 👍

**Comment by palpatim** [comment]
It turns out this was an easy feature to add and test, so I've merged it in #1991. It will be coming out in the next release (no ETA yet, but we typically have releases every 1-3 weeks), but you can use the `master` branch if you want to pick up this feature earlier.

**Comment by hffmnn** [comment]
Nice. Thank you so much for that! 👍

**Comment by hffmnn** [comment]
Closing this issue because it already got released via https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.12.1
