### ISSUE TITLE
Support for Google Sign In SDK Version 5.0 and greater

### ISSUE THREAD

**Issue by cornr** [aws-amplify/aws-sdk-ios#1993]
**Which AWS Services is the feature request for?**
AWSAuthSDK

**Is your feature request related to a problem? Please describe.**
`AWSGoogleSignInProvider` does not support the current Google Sign in SDK. It crashes on initialization because `GIDSignIn` is not key value coding-compliant starting with Google Sign in SDK 5.0.0.
I think they made major changes to it. See https://developers.google.com/identity/sign-in/ios/release

> 2019-10-15 16:49:10.448907+0200 App[3176:104691] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<GIDSignIn 0x6000000f1200> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key uiDelegate.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010cb711e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010c20e031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010cb710b9 -[NSException raise] + 9
	3   Foundation                          0x000000010bc2fb47 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 292
	4   AWSGoogleSignIn                     0x0000000126a10de2 -[AWSGoogleSignInProvider initWithGoogleClientID:] + 329
	5   AWSGoogleSignIn                     0x0000000126a10c24 __41+[AWSGoogleSignInProvider sharedInstance]_block_invoke + 49
	6   libdispatch.dylib                   0x00000001116247ec _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x0000000111625d64 dispatch_once_f + 285
	8   AWSGoogleSignIn                     0x0000000126a10bac +[AWSGoogleSignInProvider sharedInstance] + 509

**Describe the solution you'd like**
Support for GoogleSignIn SDK 5.0.0 and above.

**Describe alternatives you've considered**

**Additional context**

**Comment by palpatim** [comment]
Thank you for the feature request. We'll add this to our backlog and update this issue when we have more information.

**Comment by nahung89** [comment]
Just want to give a bit more information:
I'm using the latest `AWSMobileClient (2.11.)1`. The configuration for Google SignIn doesn't work, as the included `GoogleSignIn` library is old
Therefore `GIDSignInDelegate` doesn't response and the login flow for Google doesn't work at all ('m using Drop-In Auth UI)

Then I decide to add `GoogleSignIn (5.0.1)` framework explicitly from Pod, and the above crash appears as OP:

```
 *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<GIDSignIn 0x280e35b00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key uiDelegate.'
```

**Comment by nahung89** [comment]
Hi @palpatim, is there any update for this issue?

**Comment by BillBunting** [comment]
@palpatim @cornr -  Any update on this?  Unable to upgrade to pod 'GoogleSignIn', '~>5.0.2'  (currently, it works with pod 'GoogleSignIn', '~>4.4.0')  Error below. 

```2020-03-02 18:01:41:816 modlist[26546:9242746] Configuring SignInProvider : CognitoUserPool.
2020-03-02 18:01:41:816 modlist[26546:9242746] Registering SignInProvider AWSCognitoUserPoolsSignInProvider from awsconfiguration.json.
2020-03-02 18:01:41:816 modlist[26546:9242746] Configuring SignInProvider : FacebookSignIn.
2020-03-02 18:01:41:816 modlist[26546:9242746] Registering SignInProvider AWSFacebookSignInProvider from awsconfiguration.json.
2020-03-02 18:01:41:816 modlist[26546:9242746] Configuring SignInProvider FacebookSignIn
2020-03-02 18:01:41:817 modlist[26546:9242746] Configuring SignInProvider : GoogleSignIn.
2020-03-02 18:01:41:817 modlist[26546:9242746] Registering SignInProvider AWSGoogleSignInProvider from awsconfiguration.json.
2020-03-02 18:01:41.818016-0500 modlist[26546:9242746] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<GIDSignIn 0x10bc268c0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key uiDelegate.'
*** First throw call stack:``

**Comment by BillBunting** [comment]
The latest AWSGoogleSignIn  pod is using GoogleSignIn 4.4.0 (and not 5.0.x) and is not compliant with new Apple policies because of use of the UIWebView deprecated API. Apple is now sending a warning. 

After submitting an app to Apple on App Store Connect, a warning is sent by email: 

> Dear Developer,

> We identified one or more issues with a recent delivery for your app, "---- ". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by BillBunting** [comment]
@palpatim any update on this issue (support for Google Sign-in > 5)?  Is there any way as a user of the API to see the backlog to help predict when a fix is available?

**Comment by pankajkrastogi** [comment]
I am facing the same issue. is there any plan to fix this issue soon?

**Comment by BillBunting** [comment]
This issue remains a problem and Apple will soon start rejecting apps that use UIWebView. UIWebView is contained in the older version of GoogleSignIn (4.4.0).  The current version is 5.0.2.

grep -r "UIWebView" .
./Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,
Binary file ./Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn matches

Please let me know with AWSGoogleSignInProvider will be upgraded to support the latest version of the GoogleSignIn pod.

**Comment by cornr** [comment]
I just managed to update to GoogleSginIn > 5 by copying the [AWSGoogleSignInProvider](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSAuthSDK/Sources/AWSGoogleSignIn/AWSGoogleSignInProvider.m) over to our project and made the changes stated in the [Googles Migration Guide](https://developers.google.com/identity/sign-in/ios/quick-migration-guide).
I am going to file a PR to aws-sdk-ios next week.

**Comment by BillBunting** [comment]
@cornr thank you - it would be great if you will do the PR !

**Comment by palpatim** [comment]
Thanks for the PR, @cornr! I've merged your change into https://github.com/aws-amplify/aws-sdk-ios/pull/2851 to add a CHANGELOG and a couple of minor tweaks. It should be able to go in the next release, and it is noted as a breaking change.

**Comment by cornr** [comment]
No more `UIWebView`! 🚀

**Comment by BillBunting** [comment]
@cornr thank you. I just upgraded to `pod 'AWSGoogleSignIn', '= 2.15.0'` and no more UIWebView or complaints from Apple upon uploading to itunesconnect. Now, the only issue I still face with Google is that the token expire and the login repeatedly shows after every hour of inactivity.

**Comment by cornr** [comment]
In my tests my user stays signed in since the AWSGoogleSignInProvider or GoogleSignIn SDK supports silent sign in: https://github.com/aws-amplify/aws-sdk-ios/blob/d69516a3fb62525a8c937789b08f56533c27b45b/AWSAuthSDK/Sources/AWSGoogleSignIn/AWSGoogleSignInProvider.m#L184

Whats your credentials expiry time in cognito?

**Comment by BillBunting** [comment]
@Coeur My Cognito app client refresh token expiration is set to 3650. Facebook is able to refresh without problems (Apple is a known issue). I must be doing something in my app differently. The app does repeatedly call `AWSMobileClient.default().initialize`  and upon success, `AWSMobileClient.default().getAWSCredentials` , and  upon success `AWSMobileClient.default().getIdentityId().continueWith` as a workaround to issues I was having getting a the identity ID with a mixed ObjectiveC/Swift app (from the Mobile Hub days). I'll try to clean up some of the code and see if I can pinpoint why Google signInSilently would not be working. Thanks for the reply.

**Comment by Coeur** [comment]
@BillBunting I think you meant @cornr.

**Comment by palpatim** [comment]
We released this in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.15.0

@BillBunting I'm going to close this issue to reflect the fact that the original issue (support updated Google SDK) is complete, but if you continue to have problems with token refresh, please do open a new issues with details.
