### ISSUE TITLE
Please add the landscape orientation to showSignIn().

### ISSUE THREAD

**Issue by ishiwara51** [aws-amplify/aws-sdk-ios#1997]
**Is your feature request related to a problem? Please describe.**

The view shown by showSignIn() seems to support only portrait orientation, which conflicts my app with fixed landscape orientation.

**Describe the solution you'd like**

Please make a variation of the view supporting landscape orientation.

**Describe alternatives you've considered**

Otherwise, please add an option to showSignIn() which makes it possible to apply to showSignIn() view the orientation conflicting to the configured orientation in our app.

**Additional context**

**Comment by palpatim** [comment]
Reopening this and tagging as a feature request.

**Comment by atierian** [comment]
Fixed in [2.28.1](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.28.1)
