### ISSUE TITLE
Please hide the signup textfields which are not used.

### ISSUE THREAD

**Issue by ishiwara51** [aws-amplify/aws-sdk-ios#1998]
**Is your feature request related to a problem? Please describe.**

In my app, users can signup to AWSCognito with their email address and password, and be not requested their username and phonenumber.
However, the signup view shows all of the options including username and phonenumber. Moreover, when I input my email address into the email textfield, the view returns an error saying "Username should be an email."
All above must make our users confused. Please make it better.

**Describe the solution you'd like**

Hide the unused textfields.

**Describe alternatives you've considered**

**Additional context**

**Comment by palpatim** [comment]
Reopening and tagging as a feature request

**Comment by dmennis** [comment]
+1
