### ISSUE TITLE
CFNetwork SSLHandshake failed (-9810)

### ISSUE THREAD

**Issue by Maher-tech** [aws-amplify/aws-sdk-ios#2002]
Connect to aws iot with failure
**aws iot**

 - SDK Version: [2.8.1]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [ 4.0]

 - Device: [ iPhoneX]
 - iOS Version: [e.g. iOS 12.4]

log : Connecting...
2019-10-18 14:14:38.216743+0100 aqua-iot[592:75137] CFNetwork SSLHandshake failed (-9810)
2019-10-18 14:14:38.216860+0100 aqua-iot[592:75137] TCP Conn 0x0 SSLHandshake failed (-9810)
connection status = 5
Connection Error

Any Help PLZ

**Comment by palpatim** [comment]
Could you provide some more details around the issue:

* A code snippet showing how you're configuring the AWS IoT broker, manager, and/or data manager?
* A code snippet that demonstrates the issue?
* Are you able to reproduce this issue using our [IoT Sample App](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift)

Without any details, the only advice I can offer is to check your endpoint. Data operations (e.g., publish, subscribe, etc) should use the ATS-enabled endpoint, which is usually of the form "<endpoint id>-ats.iot.<region>.amazonaws.com". You can find your endpoint by going to [IoT Home](https://console.aws.amazon.com/iot/home?) and clicking "Settings".

**Comment by Maher-tech** [comment]
====thank you for your answer===
my implementation is here :

 AWSMobileClient.sharedInstance().initialize { (userState, error) in
      guard error == nil else {
        print("Failed to initialize AWSMobileClient. Error: \(error!.localizedDescription)")
        return
      }
      print("AWSMobileClient initialized.")
    }
    let iotEndPoint = AWSEndpoint(urlString: "https//a1brkcziqhilz7-ats.iot.eu-central-1.amazonaws.com")

    let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.EUCentral1,
                                                                identityPoolId:"eu-central-1:f90c9590-3835-4a4c-87e1-edb54c687c28")
    let iotConfiguration = AWSServiceConfiguration(region: AWSRegion, credentialsProvider: credentialsProvider)
    let iotDataConfiguration = AWSServiceConfiguration(region: .EUCentral1,
                                                       endpoint: iotEndPoint,
                                                       credentialsProvider: credentialsProvider)
    AWSServiceManager.default().defaultServiceConfiguration = iotConfiguration

    iotManager = AWSIoTManager.default()
    iot = AWSIoT.default()

    AWSIoTDataManager.register(with: iotDataConfiguration!, forKey: ASWIoTDataManager)
    iotDataManager = AWSIoTDataManager(forKey: ASWIoTDataManager)

    {
      DispatchQueue.main.async {
        print("connection status = \(status.rawValue)")
        switch(status)
        {
        case .connecting:
          print("Connecting...")
        case .connected:
          print("Connected")
          
        case .disconnected:
          print("Disconnected")
        case .connectionRefused:
         print("Connection Refused")
        case .connectionError:
          print("Connection Error")
        case .protocolError:
         print("Protocol Error")
        default:
          print("unknown state: \(status.rawValue)")
        }
        NotificationCenter.default.post( name: Notification.Name(rawValue: "connectionStatusChanged"), object: self )
      }
    }
    if (connected == false)
    {
      let defaults = UserDefaults.standard

      var certificateId = defaults.string( forKey: "certificateId")

      if (certificateId == nil)
      {
        DispatchQueue.main.async {
          print("No identity available, searching bundle...")
        }
        let myBundle = Bundle.main
        let myImages = myBundle.paths(forResourcesOfType: "p12" as String, inDirectory:nil)
        let uuid = UUID().uuidString;

        if (myImages.count > 0) {
          written to expect that the
          if let data = try? Data(contentsOf: URL(fileURLWithPath: myImages[0])) {
            DispatchQueue.main.async {
             print ("found identity \(myImages[0]), importing...")
            }
            if AWSIoTManager.importIdentity( fromPKCS12Data: data, passPhrase:"", certificateId:myImages[0]) {
              defaults.set(myImages[0], forKey:"certificateId")
              defaults.set("from-bundle", forKey:"certificateArn")
              DispatchQueue.main.async {
                self.iotDataManager.connect( withClientId: uuid, cleanSession:true, certificateId:myImages[0], statusCallback: mqttEventCallback)
              }
            }
          }
        }

        certificateId = defaults.string( forKey: "certificateId")
        if (certificateId == nil) {
          DispatchQueue.main.async {
           print("No identity found in bundle, creating one...")
          }

          // Now create and store the certificate ID in NSUserDefaults
          let csrDictionary = [ "commonName":CertificateSigningRequestCommonName, "countryName":CertificateSigningRequestCountryName, "organizationName":CertificateSigningRequestOrganizationName, "organizationalUnitName":CertificateSigningRequestOrganizationalUnitName ]

          self.iotManager.createKeysAndCertificate(fromCsr: csrDictionary, callback: {  (response ) -> Void in
            if (response != nil)
            {
              defaults.set(response?.certificateId, forKey:"certificateId")
              defaults.set(response?.certificateArn, forKey:"certificateArn")
              certificateId = response?.certificateId
              print("response: [\(String(describing: response))]")

              let attachPrincipalPolicyRequest = AWSIoTAttachPrincipalPolicyRequest()
              attachPrincipalPolicyRequest?.policyName = PolicyName
              attachPrincipalPolicyRequest?.principal = response?.certificateArn

              // Attach the policy to the certificate
              self.iot.attachPrincipalPolicy(attachPrincipalPolicyRequest!).continueWith (block: { (task) -> AnyObject? in
                if let error = task.error {
                  print("failed: [\(error)]")
                }
                print("result: [\(String(describing: task.result))]")

                // Connect to the AWS IoT platform
                if (task.error == nil)
                {
                  DispatchQueue.main.asyncAfter(deadline: .now()+2, execute: {
                   print("Using certificate: \(certificateId!)")
                    self.iotDataManager.connect( withClientId: uuid, cleanSession:true, certificateId:certificateId!, statusCallback: mqttEventCallback)

                  })
                }
                return nil
              })
            }
            else
            {
              DispatchQueue.main.async {

                print("Unable to create keys and/or certificate, check values in Constants.swift")
              }
            }
          } )
        }
      }
      else
      {
        let uuid = UUID().uuidString;

        // Connect to the AWS IoT service
        iotDataManager.connect( withClientId: uuid, cleanSession:true, certificateId:certificateId!, statusCallback: mqttEventCallback)
      }
    }
    else
    {
      print("Disconnecting...")

      DispatchQueue.global(qos: DispatchQoS.QoSClass.default).async {
        self.iotDataManager.disconnect();
        DispatchQueue.main.async {
          self.connected = false
          print("Connect")
        }
      }
    }

**Comment by palpatim** [comment]
Can you increase the logging level and paste the logs around the connection? Before `AWSMobileClient.sharedInstance().initialize...`, paste:

```swift
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

It seems like the problem is with the connection to the data manager, which eventually ends up in [`MQTTClient.connectWithCert`](https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSIoT/Internal/AWSIoTMQTTClient.m#L285)


Also, is your app using a bundled cert, or following the codepath to create a new cert with a CSR from within the app?

**Comment by Maher-tech** [comment]
*im using an existing certificate and private key and generated a PKCS12 from them and drop it in my project.
log:
AWSMobileClient initialized.
2019-10-18 15:46:16:267 aqua-iot[615:86219] Initializing AWSIoTMqttConfiguration with KeepAlive:300.000000, baseReconnectTime:1.000000,minimumConnectionTime:20.000000, maximumReconnectTime:128.000000, autoResubscribe:Enabled, lwt topic: message: 
2019-10-18 15:46:16:267 aqua-iot[615:86219] <<<NSThread: 0x2820d6dc0>{number = 1, name = main}>>In connectWithClientID
2019-10-18 15:46:16:267 aqua-iot[615:86219] hostName: (null)
2019-10-18 15:46:16:267 aqua-iot[615:86219] URL: https//a1brkcziqhilz7-ats.iot.eu-central-1.amazonaws.com
2019-10-18 15:46:16:270 aqua-iot[615:86219] username is : ?SDK=iOS&Version=2.6.19
2019-10-18 15:46:16:270 aqua-iot[615:86219] Metrics collection is: Enabled
2019-10-18 15:46:16:270 aqua-iot[615:86219] -[AWSMQTTSession initWithClientId:userName:password:keepAlive:cleanSession:willTopic:willMsg:willQoS:willRetainFlag:publishRetryThrottle:] [Line 82], Thread:<NSThread: 0x2820d6dc0>{number = 1, name = main} 
2019-10-18 15:46:16:270 aqua-iot[615:86219] +[AWSMQTTMessage connectMessageWithClientId:userName:password:keepAlive:cleanSession:willTopic:willMsg:willQoS:willRetain:] [Line 66], Thread:<NSThread: 0x2820d6dc0>{number = 1, name = main} 
2019-10-18 15:46:16:270 aqua-iot[615:86219] Creating AWSMQTTMessage with raw data >>>>> <00044d51 54540482 012c0024 35323239 44343943 2d434634 412d3436 37442d41 4431342d 42424537 37383245 32393736 00173f53 444b3d69 4f532656 65727369 6f6e3d32 2e362e31 39> <<<<<
2019-10-18 15:46:16:271 aqua-iot[615:86272] <<<NSThread: 0x282071a80>{number = 3, name = (null)}>> Initializing MQTTEncoder and MQTTDecoder streams
2019-10-18 15:46:16:271 aqua-iot[615:86272] opening encoder stream.
2019-10-18 15:46:16:272 aqua-iot[615:86272] opening decoder stream.
2019-10-18 15:46:16.272837+0100 aqua-iot[615:86272] CFNetwork SSLHandshake failed (-9810)
2019-10-18 15:46:16:272 aqua-iot[615:86272] -[AWSMQTTEncoder stream:handleEvent:] [Line 59] EventCode:1, Thread: <NSThread: 0x282071a80>{number = 3, name = (null)}
2019-10-18 15:46:16.272853+0100 aqua-iot[615:86272] TCP Conn 0x0 SSLHandshake failed (-9810)
2019-10-18 15:46:16:272 aqua-iot[615:86272] -[AWSMQTTDecoder stream:handleEvent:] [Line 55] EventCode:1, stream: <__NSCFInputStream: 0x2807d29a0>, Thread: <NSThread: 0x282071a80>{number = 3, name = (null)}
2019-10-18 15:46:16:273 aqua-iot[615:86272] -[AWSMQTTDecoder stream:handleEvent:] [Line 55] EventCode:8, stream: <__NSCFInputStream: 0x2807d29a0>, Thread: <NSThread: 0x282071a80>{number = 3, name = (null)}
2019-10-18 15:46:16:273 aqua-iot[615:86272] -[AWSMQTTSession decoder:handleEvent:] [Line 351] eventCode:2
2019-10-18 15:46:16:273 aqua-iot[615:86272] MQTT session error, code: 3
2019-10-18 15:46:16:273 aqua-iot[615:86272] closing encoder stream.
2019-10-18 15:46:16:273 aqua-iot[615:86272] closing decoder stream.
connection status = 1
Connecting...
2019-10-18 15:46:17:278 aqua-iot[615:86272] MQTTSessionDelegate handleEvent: 3
2019-10-18 15:46:17:278 aqua-iot[615:86272] MQTTSessionEventConnectionError: Received an MQTT session connection error

**Comment by palpatim** [comment]
Your log shows you using `?SDK=iOS&Version=2.6.19`, which is quite old--the latest version is 2.12.1, and we've made numerous improvements to the SDK since then. Does this issue reproduce on the latest SDK?

**Comment by Maher-tech** [comment]
cant find the latest version of awsIoT
[!] CocoaPods could not find compatible versions for pod "AWSIoT":
  In Podfile:
    AWSIoT (~> 2.12.1)
None of your spec sources contain a spec satisfying the dependency: `AWSIoT (~> 2.12.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Maher-tech** [comment]
in my podfile i work with '2.11.1' and it shows ?SDK=iOS&Version=2.6.19 in log and it shows the same error

**Comment by Maher-tech** [comment]
i cloned sample example: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift
and i updated the region from EUCentral1 to USEast2 and in my end point to and it works.
but in my case i must work with EUCentral1 and it still show me the same error.

**Comment by mochangheng** [comment]
I had the exact same issue as @Maher-tech. After looking around for awhile, I realized that it was because I didn't add "https://" in front of the my endpoint URL, which caused the NSURL class to be unable to parse the host name (nil) for the address. I noticed that in the code that you copied, you wrote "https//" instead of "https://," which could be causing this issue.
