### ISSUE TITLE
How to use new feature CustomConfiguration for AWSMobileClient

### ISSUE THREAD

**Issue by ChrisInspect** [aws-amplify/aws-sdk-ios#2006]
**State your question**
My application has 1 UserPool and 1 IdentityPool to authenticate my users. This Application is running for 1 customer. This works fine for now.
The customer is a company with different users (e.g. admin, worker, guest etc.) and get different permissions to his companybucket. 
Now I want to add a second customer, so I would like to add a second UserPool, IdentityPool and Bucket. 
At the beginning of my application the user have to type in a key for his company. Based on this key I want to initialize the UserPool, IdentityPool and Bucket for him. 

For my use case I thought that the new feature (from 2.11.0) of CustomConfiguration for AWSMobileClient would be the best solution?
Is there any example/documentation (e.g. code snippets for Swift) available?
Do i have to remove my awsconfiguration.json and need to initialize everything through code?
Or is there even a better solution for my use case? 

**Which AWS Services are you utilizing?**
AWSMobileClient
AWSCognito
AWSS3

**Environment(please complete the following information):**
 - SDK Version: 2.12.0
 - Dependency Manager: CocoaPods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPad
 - iOS Version: iPadOS

**Comment by ChrisInspect** [comment]
After lot of reading, I found a code snippet in the documentation.
After other hours of experimenting I got it working.
Sorry for the new opened issue. Better have to read more, before open one :)

**Comment by palpatim** [comment]
@ChrisInspect Glad you were able to discover this. Please open a new issue if you have any problems using the feature.
