### ISSUE TITLE
Conflicting timeoutIntervalForRequest parameters lead to confusing setup of the AWSS3TransferUtility

### ISSUE THREAD

**Issue by AdamEsgie** [aws-amplify/aws-sdk-ios#2008]
**Describe the bug**
When instantiating a AWSSTransferUtility here: https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSS3/AWSS3TransferUtility.m#L389-#L392 ... the method takes two different configuration objects. 
1) a AWSServiceConfiguration object and 
2) a AWSS3TransferUtilityConfiguration object

Both of these objects have a property that can be set called `timeoutIntervalForResource`.

The `AWSServiceConfiguration` is an extension of `AWSNetworkingConfiguration` (which can be seen here: https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSCore/Service/AWSService.h#L90 and AWSNetworkingConfiguration is the one that defines the  `timeoutIntervalForResource` https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSCore/Networking/AWSNetworking.h#L170

The `timeoutIntervalForRequest` for the AWSS3TransferUtilityConfiguration object is defined here: https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSS3/AWSS3TransferUtility.h#L685

As you can see in this portion of the previously mentioned `AWSS3TransferUtility` instantiation, the `timeoutIntervalForRequest` of the `AWSS3TransferUtilityConfiguration` is the property used while setting up the `NSURLSessionConfiguration` object: https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSS3/AWSS3TransferUtility.m#L428

All other configuration values are taken from the `AWSServiceConfiguration` object.  

My team for awhile was setting the `timeoutIntervalForRequest` property value on the `AWSServiceConfiguration` object which was being ignored.  

**To Reproduce**
n/a

**Which AWS service(s) are affected?**
S3

**Expected behavior**
Ideally the same property on two different configuration objects wouldn't be able to be sent to an `AWSS3TransferUtility` instantiation request. 

**Screenshots**
n/a

**Environment(please complete the following information):**
 - SDK Version: at least 2.9.2+ - i did see https://github.com/aws-amplify/aws-sdk-ios/pull/1260 which looks like it fixed a previously known bug
 - Dependency Manager:  cocoa pods 
 - Swift Version : 5.0

**Device Information (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by TalDabush** [comment]
Did you manage to solve it or get any answer from somewhere else?

**Comment by AdamEsgie** [comment]
@TalDabush you can still set the `timeoutIntervalForResource` by setting the value on a AWSS3TransferUtilityConfiguration object rather than the AWSServiceConfiguration object.  My issue is both objects have the same property `timeoutIntervalForResource` but the service AWSServiceConfiguration property value is ignored without any indication that that will be the case.  This can lead to a confusing setup process.

**Comment by TalDabush** [comment]
Thank you!
