### ISSUE TITLE
Login with QRCode / Without username or password

### ISSUE THREAD

**Issue by ChrisInspect** [aws-amplify/aws-sdk-ios#2010]
**Which AWS Services is the feature request for?**
Cognito

**Is your feature request related to a problem? Please describe.**
We developed an app where our customer can, like in nearly every other app, login with username and password. This customer is a company, where everybody has an employee ID card. 
Now we have the idea, that worker, who are using our app, can print an QR-Code on their card and can login to our app very simple with scanning this code. Because the users are often wearing gloves, login would be even possible with gloves and a nice advantage for our customer.
Of course we can create codes, where username and password is saved on, but I think this wouldn't be the safest solution :). Also, if the user changes his password, the code wouldn't work anymore.

**Describe the solution you'd like**
A function where users can scan an QR-Code and get access to their user accounts. 
Correct me, if I am wrong, but I think WhatsApp have something similar with their WebApp?

**Describe alternatives you've considered**
Maybe a login with instead username and password, username and sub-id. So creating a QRCode would be a little bit safer, and changing password wouldn't be a problem anymore.

Maybe there is already a solution for this, and I didn't know or read it? 
Or maybe there is a even better idea to get this working.

**Comment by royjit** [comment]
Hi @ChrisInspect 

Looks like this use case can be handled with  [custom auth](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#amazon-cognito-user-pools-custom-authentication-flow) in AWS Cognito. AWSMobileClient supports this now and you can find more details [here](https://aws-amplify.github.io/docs/sdk/ios/authentication).

**Comment by micstepper** [comment]
Hey @ChrisInspect did you find a solution? I'm looking for an implementation like this in android. Thanks in advance. Mic.
