### ISSUE TITLE
2.12.1 is missing precompiled Carthage Frameworks

### ISSUE THREAD

**Issue by cornr** [aws-amplify/aws-sdk-ios#2012]
**Describe the bug**
The just released SDK Version 2.12.1 is missing the precompiled AWS-SDK-iOS for Carthage.

**To Reproduce**
Create a Cartfile with
> github "aws-amplify/aws-sdk-ios" == 2.12.1

run `carthage update --platform ios --cache-builds`

**Which AWS service(s) are affected?**
Maybe the Deploy process?

**Expected behavior**
Carthage should skip Building AWS and just use the precompiled Frameworks. This works with 2.12.0

**Environment(please complete the following information):**
 - SDK Version: 2.12.1
 - Dependency Manager: Carthage
 - Swift Version : 5

**Comment by royjit** [comment]
Can you please check this again. We uploaded a new precompiled Framework.

**Comment by cornr** [comment]
Its working. Thanks.
Is this a async process?
