### ISSUE TITLE
Crash when trying to use TTS feature with Arabic content

### ISSUE THREAD

**Issue by dingua** [aws-amplify/aws-sdk-ios#2013]
**Describe the bug**
When trying to use TTS feature with Arabic content and configuration the SDK crashes.

**To Reproduce**
If I configure the the request with Arabic configuration it crashes:
`let input = AWSPollySynthesizeSpeechURLBuilderRequest()
        input.outputFormat = AWSPollyOutputFormat.mp3
        input.voiceId = AWSPollyVoiceId.zeina
        input.languageCode = AWSPollyLanguageCode.arb
        input.text = text`

Log:
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: VoiceId)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010679e6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000105907ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001066ecddc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010680d9d6 -[__NSDictionaryM setObject:forKey:] + 1046
	4   AWSPolly                            0x0000000104437ddf __54-[AWSPollySynthesizeSpeechURLBuilder getPreSignedURL:]_block_invoke + 1695
	5   AWSCore                             0x00000001030e3063 __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 163
	6   AWSCore                             0x00000001030e276a __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 106
	7   AWSCore                             0x0000000103085e4a __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 186
	8   AWSCore                             0x00000001030866bf -[AWSExecutor execute:] + 95
	9   AWSCore                             0x00000001030e2610 -[AWSTask continueWithExecutor:block:cancellationToken:] + 864
	10  AWSCore                             0x00000001030e2f4d -[AWSTask continueWithExecutor:successBlock:cancellationToken:] + 317
	11  AWSCore                             0x00000001030e3124 -[AWSTask continueWithSuccessBlock:] + 132
	12  AWSPolly                            0x00000001044376df -[AWSPollySynthesizeSpeechURLBuilder getPreSignedURL:] + 223`
**Which AWS service(s) are affected?**
AWSPolly
**Expected behavior**
It should work fine, tried with English and it works just fine.

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: latest
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Similator
 - iOS Version: iOS 12
 - Specific to simulators:

**Additional context**

**Comment by dingua** [comment]
is there any workaround for this ? it is a blocking the whole feature for Arabic and could be the same for other languages.

**Comment by kneekey23** [comment]
hi @dingua have you tried calling this using Amplify Predictions instead? Set up [here](https://aws-amplify.github.io/docs/ios/predictions).

**Comment by dingua** [comment]
I went back and tested using Xcode 11 and so iOS 13 simulator and the crash is gone.
