### ISSUE TITLE
AWSMobileClientError message accessibility 

### ISSUE THREAD

**Issue by nahung89** [aws-amplify/aws-sdk-ios#2024]
**Which AWS Services is the feature request for?**
`AWSMobileClient`

**Is your feature request related to a problem? Please describe.**
`AWSMobileClientError` supports `message` property, but the accessibility is `internal`. 
Therefore we can't get it from other modules.

**Describe the solution you'd like**
add `public` for this property to expose it:
```
extension AWSMobileClientError {
    /// Underlying error message of `AWSMobileClientError`
    public var message: String { ... }
```

**Comment by glennposadas** [comment]
Up for this. I need to access this object. I think this is an intentional mistake? For now I'm going to unlock the pod, and add `public` keyword.

**Comment by Ricardo1980** [comment]
I was going to open exactly the same issue until I realised it was already done.
This should be public.

**Comment by atierian** [comment]
Thanks for opening this issue. The `message` property has been made public -- this change will be included in the next release.
