### ISSUE TITLE
Dash Replenishment Service Integration

### ISSUE THREAD

**Issue by karasahinemre** [aws-amplify/aws-sdk-ios#2025]
Hello,

When I examined the DRS documentation, I saw that I had to use the login with amazon sdk. As far as I can see, there are no pods for this sdk. Also the sample project is also written in objective-c and does not have any examples for swift.

Is there a way to establish a connection between mobile client and drs? How to register our users to drs system with current updated methods?

In the current case, we use mobile client sdk and need to implement drs support. 

Thank you for your help.

**Comment by lawmicha** [comment]
Hi @karasahinemre 

We don't own those SDK's so your question may be better addressed over on their forums. Can you give these a try?
https://forums.developer.amazon.com/spaces/61/Dash+Replenishment+Service.html
https://forums.developer.amazon.com/spaces/107/Login+With+Amazon.html
