### ISSUE TITLE
Access to IAM-Functions

### ISSUE THREAD

**Issue by ChrisInspect** [aws-amplify/aws-sdk-ios#2026]
**UseCase**
My iOS-App need access to create IAM-policies. Every customer has 1 SuperAdmin-User, who should be able to create policies for IAM-Roles. This roles should be attached to specific groups in the userPool. I predefined parts of the policies for IAM-Roles, so my customer can choose and combine them. This means, that my customer can't write "real" policies, just create his own, based on my preconfigured parts of a policy. 

**Example:**
Customer A's SuperAdmin wants to create a new group inside his UserPool named "employees". He decides, that this group of users should be able to write on 1 object and read on 2 objects in his bucket.
Customer B's SuperAdmin wants to create a new group inside his UserPool named "admins". He decides, that this group of users should be able to write and read every object in his bucket and also can create new users in the userPool.

**My solution** 
For this use case would be, that every customer's SuperAdmin has permissions to create preconfigured policies, attach them to IAM-Roles and finally attach them to his new created groups.

This wouldn't be very difficult, but my main question is, which pod for my iOS-App do I need, to access on AWS IAM? For Cognito I use AWSCognitoIdentityProvider-pod and can create requests inside my app, but for IAM I really found nothing similar to this.

Any suggestions or maybe a better idea for my problem?
  
**Which AWS Services are you utilizing?**
AWS IAM
AWS Cognito

**Environment(please complete the following information):**
 - Dependency Manager: [Cocoapods]
 - Swift Version : [5.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPad]
 - iOS Version: [iOS 13]
 - Specific to simulators:

**Comment by palpatim** [comment]
Hi @ChrisInspect,

The SDK doesn't support this now, because it's not a core mobile use case--most customers are interested in authenticating/authorizing app users, rather than administering user directories and policies.

We'll add this to our feature request backlog and update this issue when we have more information.

**Comment by royjit** [comment]
Closing this request since we are not seeing enough customer request for this feature. Also AWS SDK for Swift seems to support this - https://github.com/awslabs/aws-sdk-swift/tree/main/Sources/Services/AWSIAM . Could you please check if that AWS SDK for Swift solves your use case.
