### ISSUE TITLE
AWSCognitoIdentityMultiFactorAuthentication Never Returns

### ISSUE THREAD

**Issue by perryhoekstra** [aws-amplify/aws-sdk-ios#2028]
**State your question**

I implemented the example from https://github.com/awslabs/aws-sdk-ios-samples/blob/master/CognitoYourUserPools-Sample/Swift/CognitoYourUserPoolsSample/MFAViewController.swift. However, after setting the **AWSTaskComplettionSource** to the entered MFA code, I never get a callback to the **didCompleteMultifactorAuthenticationStepWithError** method within the **AWSCognitoIdentityMultiFactorAuthentication** delegate.

Any thoughts on what my omission could be?

**Which AWS Services are you utilizing?**

AWS Amplify (iOS), Cognito User Pools

**Provide code snippets (if applicable)**
```swift
import Foundation
import UIKit
import AWSMobileClient
import AWSCognitoIdentityProvider

class MFAModalViewController: UIViewController {

    @IBOutlet weak var messageLabel: UILabel!
    @IBOutlet var backgroundView: UIView!
    @IBOutlet weak var boxView: UIView!
    @IBOutlet weak var mfaTextField: UITextField!

    public var message: String?
    var mfaCompletionSource: AWSTaskCompletionSource<NSString>?

    @IBAction func mfaTextFieldChanged(_ sender: Any) {
        if let mfaCode = mfaTextField.text, mfaCode.count == 6 {

            self.mfaCompletionSource?.set(result: NSString(string: mfaCode))
        }
    }

    override func viewDidLoad()
    {
        super.viewDidLoad()

        if let message = message {
            messageLabel.text = message
        }
    }
}

extension MFAModalViewController: AWSCognitoIdentityMultiFactorAuthentication {
    func getCode(_ authenticationInput: AWSCognitoIdentityMultifactorAuthenticationInput, mfaCodeCompletionSource: AWSTaskCompletionSource<NSString>) {
        hud.dismiss()

        self.mfaCompletionSource = mfaCodeCompletionSource
    }

    func didCompleteMultifactorAuthenticationStepWithError(_ error: Error?) {
        ...
    }
}
```

**Environment(please complete the following information):**
 - SDK Version: [from Podfile.lock]
   - AWSAuthCore (2.11.1):
   - AWSCognitoIdentityProvider (2.11.1):
   - AWSCognitoIdentityProviderASF (1.0.1)
   - AWSCore (2.11.1)
   - AWSMobileClient (2.11.1):

 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Device Information (please complete the following information):**
 - Device: iPhone7, Simulator
 - iOS Version: iOS 12+

**Comment by royjit** [comment]
Hi @perryhoekstra 

After you set the value in the completionSource, the SDK makes an async call to validate the MFA challenge. And when the async call returns it will call `didCompleteMultifactorAuthenticationStepWithError`. Your delegate object `MFAModalViewController` should not be de-initialized at this point. If the object is alive it should get the callback.
