### ISSUE TITLE
AwsMobileClient, how do you catch UserNotFound and NotAuthorizedException?

### ISSUE THREAD

**Issue by armandr** [aws-amplify/aws-sdk-ios#2038]
**State your question**
AwsMobileClient's native UI throws UserNotFound and NotAuthorizedException pop-ups in IOS when a user enters wrong username and correct username but wrong password.

How do you catch both types of exceptions so that the app can present a more user friendly pop-up? 

**Which AWS Services are you utilizing?**
Cognito
**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.9.7
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: All
 - iOS Version: 13.x
 - Specific to simulators: nope

**Comment by palpatim** [comment]
Can you clarify your use case? Are you asking if it's possible to distinguish between "this user doesn't exist" and "this user exists, but doesn't have the right password" cases? A code snippet might be helpful to illustrate what you're asking.

**Comment by armandr** [comment]
> Can you clarify your use case? Are you asking if it's possible to distinguish between "this user doesn't exist" and "this user exists, but doesn't have the right password" cases? A code snippet might be helpful to illustrate what you're asking.

In the iOS SDK drop-in Auth UI, after the call to showSignIn(), the closure will NOT be called if the user has an unsuccessful sign-in attempt.  

Instead, AwsMobileClient displays a UIAlert with title: "UserNotFound" or "NotAuthorizedException" with a "Retry" button.

For our use case, we would like to intercept those exceptions and present a UIAlert with a more clear language title and text wording and allow for localization.

Incidentally, a similar issue exists when AwsMobileClient does not have internet access.  There are exceptions thrown at the debug log level, but the app (showSignIn) does not receive any feedback or errors and it looks as though the "submit" button of the Auth-UI does not work.  

It would be nice to receive these kinds of errors in the closure that is passed to showSignIn() or somehow add a listener for exceptions.


```
// Use the iOS SDK drop-in Auth UI to show login options to user (Basic auth, Google, or Facebook)
    // Note: The view controller implementing the drpo-in auth UI needs to be associated with a Navigation Controller.
    func showSignIn() {
        AWSMobileClient.sharedInstance().showSignIn(navigationController: self.navigationController!, {
            (userState, error) in
            
            if(error == nil){   // Successful signin
                DispatchQueue.main.async {
                    print("User successfully logged in")
                 })
                }
            }else
            {
                print(" we have an ERROR: ", error)
            }
        })
    }
```

**Comment by palpatim** [comment]
@armandr Thanks for clarifying. Unfortunately AWSMobileClient doesn't provide a way to suppress this behavior just now. We have a number of Auth UI customization requests that we're considering so we'll take this on as a feature request and update when we have more info.

**Comment by atierian** [comment]
We recommend using Amplify Authenticator for this -- for more information, please visit the [Authenticator docs](https://ui.docs.amplify.aws/swift/connected-components/authenticator). Thanks!
