### ISSUE TITLE
SDK V2.12.1 Crash in AWSIoTMQTTClient.m line 757 -[AWSIoTMQTTClient openStreams:]

### ISSUE THREAD

**Issue by Echo-zhu** [aws-amplify/aws-sdk-ios#2040]
**Describe the bug**
Recently we have received a lot of crash logs regarding this, and the code that caused the crash is pointing to AWSIoTMQTTClient.m line 757
-[AWSIoTMQTTClient openStreams:].

We have used AWS SDK version '2.12.1'

**To Reproduce**
1.IPhone connected to a normal 4G network
2.  IPhone connected to a wifi without network，Until the wifi icon appears in the phone status bar
3. Start connection IoT.Of course, it is not connected.But the SDK has been trying to reconnect
4. Turn off the wifi switch in the control center，Then program will crash

**Environment(please complete the following information):**
 - SDK Version: 2.12.1
 - Dependency Manager: Cocoapods
 - Xcode Version : 10.3

**Device Information (please complete the following information):**
 - Device: iPhone6s
 - iOS Version: iOS 13.0

**connect code**
AWSCognitoCredentialsProvider *provider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:CognitoIdentityPoolId];
    AWSEndpoint *endpoint = [[AWSEndpoint alloc] initWithURLString:EndPoint];
    
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 endpoint:endpoint credentialsProvider:provider];
    [AWSIoTDataManager registerIoTDataManagerWithConfiguration:configuration forKey:@"USEast1IoTDataManager"];
    
    _awsIoTDataManager = [AWSIoTDataManager IoTDataManagerForKey:@"USEast1IoTDataManager"];
    _IoTStatus = AWSIoTMQTTStatusUnknown;
[_awsIoTDataManager connectWithClientId:uuid cleanSession:YES certificateId:certificateId statusCallback:^(AWSIoTMQTTStatus status) {}

**flurry crash log**
Crashed Thread:
0libobjc.A.dylibobjc_release + 24
1CoreFoundation-[__NSSingleObjectArrayI dealloc] + 40
2libobjc.A.dylib(anonymous namespace)::AutoreleasePoolPage::pop(void*) + 668
3CoreFoundation_CFAutoreleasePoolPop + 24
4Foundation-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
5GoveeHome- AWSIoTMQTTClient.m:745-[AWSIoTMQTTClient openStreams:]
6Foundation__NSThread__start__ + 980
7libsystem_pthread.dylib_pthread_body + 124
8libsystem_pthread.dylib_pthread_start + 40
9libsystem_pthread.dylibthread_start + 0

**Comment by palpatim** [comment]
@Echo-zhu Thanks for the crash report and especially the repro steps. We'll investigate and update when we have more info.

**Comment by palpatim** [comment]
@Echo-zhu 

We're still unable to reproduce this. I wanted to verify the repro steps you listed:

> 1. IPhone connected to a normal 4G network
"Normal 4G network" meaning a cellular only network?

> 2. IPhone connected to a wifi without network，Until the wifi icon appears in the phone status bar

* You are talking about the same device as connected to the 4G network, right?
* Do you mean that the phone is connected to both a 4G and wifi network?
* What does "wifi without network" mean?
* When you say "Until the wifi icon appears in the phone status bar", that means "until the wifi is connected", right?

> 3. Start connection IoT.Of course, it is not connected.But the SDK has been trying to reconnect

* Is your app set up to disable cellular data, such that only wifi connections allow data transmission? Why wouldn't the app have sent data on the 4G connection? For that matter, why wouldn't it be sending data on the WiFi connection if the "wifi icon" appears in the status bar?

> 4. Turn off the wifi switch in the control center，Then program will crash
