### ISSUE TITLE
does not conform to protocol 'AWSCognitoIdentityPasswordAuthentication'

### ISSUE THREAD

**Issue by kamifernandez** [aws-amplify/aws-sdk-ios#2041]
I am trying to implement cognito with swift 5, everything is going well without errors, but when implementing the AWSCognitoIdentityPasswordAuthentication the following error appears:

Type 'ViewController' does not conform to the 'AWSCognitoIdentityPasswordAuthentication' protocol

I have already implemented protocols that are not optional, however the error happens.

<img width="1026" alt="Captura de Pantalla 2019-11-15 a la(s) 12 04 30 p  m" src="https://user-images.githubusercontent.com/55001181/68970773-0eaecb00-07b6-11ea-9c3f-bf7ca6ad3b06.png">

and when I try to import it again, it tells me that it is already duplicated, please someone happens a similar case?

<img width="1025" alt="Captura de Pantalla 2019-11-15 a la(s) 12 04 40 p  m" src="https://user-images.githubusercontent.com/8736885/68971023-98f72f00-07b6-11ea-9e9a-9438b4254635.png">

**Environment(please complete the following information):**
 - SDK Version: [2.1.2]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [5.0]

**Comment by royjit** [comment]
Hi @kamifernandez 

Apologies for the delay in responding. Do you have any other protocol that `LoginViewController` conforms too? This is a know bug in using `Cognito` SDK with swift where two delegate methods conflicts with each other. One work around is to make another class conform to one of the protocol and avoiding the conflicts.
`AWSMobileClient` is the newer SDK for auth, and it abstracts out all these issues. I would recommend considering using it if possible. Details can be found [here](https://aws-amplify.github.io/docs/sdk/ios/authentication).
