### ISSUE TITLE
AWMobileClient GetIdentityId Function Gives OSSecurity Error

### ISSUE THREAD

**Issue by karasahinemre** [aws-amplify/aws-sdk-ios#2054]
**Describe the bug**

When AWSMobileClient.default().identityId is empty I call AWSMobileClient.default().getIdentityId().continueWith(block). I'll get OSStatus error: [-25299] Security error has occurred.

**To Reproduce**

```
AWSMobileClient.default().clearKeychain()
AWSMobileClient.default().clearCredentials()

AWSMobileClient.default().getIdentityId().continueWith(block: { (task) -> Any? in
        if let error = task.error {
            print(error.localizedDescription)
            completion("", error)
        }
        else if let cognitoIdentityId = task.result {
            completion(cognitoIdentityId as String, nil)
        }
        return task
})
```

**Which AWS service(s) are affected?**

**Expected behavior**
Not giving any errors.

**Environment(please complete the following information):**
 - SDK Version: 2.12.1
 - Dependency Manager: CocoaPods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone XR
 - iOS Version: 13.2.2

**Additional context**
-25299 --> errSecDuplicateItem but I am pretty sure calling clear keychain function.

**Comment by karasahinemre** [comment]
Any updates?

**Comment by kneekey23** [comment]
hi @karasahinemre can you possibly give me more detail about the exact steps to reproduce? I put the above snippet in an app where  I have cognito user pools set up, I signed in and then called it and no repro.

**Comment by kneekey23** [comment]
hi @karasahinemre are you doing something similar to this issue #1217 ?
