### ISSUE TITLE
AWSAppSyncClientConfiguration stopped working withuserPoolsAuthProvider: AWSMobileClient.default()

### ISSUE THREAD

**Issue by helloniklas** [aws-amplify/aws-sdk-ios#2055]
I recently updated to v 2.12.1 and my old code now stops working. I'm using a Cognito user pool for auth and used to provide this to the AWSAppSyncClientConfiguration like this:

```
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: AWSAppSyncServiceConfig(), userPoolsAuthProvider: AWSMobileClient.default())
            self.appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
            
            //Setup the service configuration
            let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: AWSMobileClient.default())
            
            //Setup the transfer utility configuration
            let tuConf = AWSS3TransferUtilityConfiguration()
            
            //Register a transfer utility object
            AWSS3TransferUtility.register(
                with: configuration!,
                transferUtilityConfiguration: tuConf,
                forKey: "transfer"
            )
            
            AWSS3PreSignedURLBuilder.register(with: configuration!, forKey: "signer")
```

That now complains saying: Cannot convert value of type 'AWSMobileClient' to expected argument type 'AWSCognitoUserPoolsAuthProvider?'

It seems every version update of this system changes how to initialise auth.

**Comment by palpatim** [comment]
@helloniklas Sorry for the frustration using this--it sounds like a recent commit removed AWSMobileClient's conformance to `AWSCognitoUserPoolsAuthProvider`. You mention that you upgraded the Core SDK to 2.12.1; what version of AppSync are you using?
