### ISSUE TITLE
Metrics are not automatically sent to AWS Pinpoint when Cognito User Pools are used

### ISSUE THREAD

**Issue by amuresia** [aws-amplify/aws-sdk-ios#2066]
**Describe the bug**
Metrics are not automatically sent to AWS Pinpoint when Cognito User Pools are used 
**To Reproduce**
1. Add analytics to the project via amplify add analytics
2. Add authentication to the project via amplify add auth
3. Sign up/ Sign in using accounts available in the cognito user pool

**Which AWS service(s) are affected?**
AWS Pinpoint, AWS Cognito
**Expected behavior**
I would expect at least session and 'Authentication metrics' to be populated in Pinpoint.

**Screenshots**
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/16068752/69635253-e774bb00-104b-11ea-8de0-293df179ba7c.png">

**Environment(please complete the following information):**
 - SDK Version: 3.16.0

 - Dependency Manager: Cocoapods
 - Swift Version: 5.0

**Device Information (please complete the following information):**
 - Device: Simulator, iPhone X
 - iOS Version: iOS 13.2
 - Specific to simulators: No

**Additional context**
1. Metrics are sent through if I call the functions manually i.e. `_userauth.sign_in`
2. The IAM role for auth users includes:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:GetUserEndpoints",
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint"
            ],
            "Resource": "arn:aws:mobiletargeting:*:xxx:apps/xxx*"
        }
    ]
}
```
3. My aws-configuration.json - I tried with and without PinpointAppId - the result is the same
```
"CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "eu-west-2:xxx",
                "Region": "eu-west-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "eu-west-2_xxx",
            "AppClientId": "xxx",
            "AppClientSecret": "xxx",
            "Region": "eu-west-2",
            "PinpointAppId": "xxx"
        }
    },
...
"PinpointAnalytics": {
        "Default": {
            "AppId": "xxx",
            "Region": "eu-west-1"
        }
    },
    "PinpointTargeting": {
        "Default": {
            "Region": "eu-west-1"
        }
    }
```
4. When debugging, I can see the following when I launch the application
```
2019-11-26 12:50:41:339 appname[59204:3151419] Endpoint Updated Successfully! <AWSPinpointTargetingUpdateEndpointResponse: 0x600003992420> {
    messageBody = "<AWSPinpointTargetingMessageBody: 0x600003b7a2a0> {\n    message = Accepted;\n    requestID = \"7b410233-c6f2-46fd-b548-feb3fd641223\";\n}";
```
5. I can see that a new endpoint is created, but it is not related to the cognito user in any way
6. The Pinpoint project is not listed under Cognito > User Pools > Analytics > Add analytics and campaigns

**Comment by palpatim** [comment]
@amuresia 

Sorry for the confusion with this. Cognito User Pools only supports sending events to Amazon Pinpoint projects in the US East (N. Virginia) us-east-1 Region, regardless of the region in which the user pool resides.

The AWS documentation has been updated to reflect this.

**Comment by amuresia** [comment]
Hi @palpatim,

Thank you for the clarification.
All of the amplify resources that my project uses are set up in eu-west-2 (London). If I run amplify add analytics then the Pinpoint project is setup in eu-west-1 (Ireland).

However, after several application session restarts, no data is sent to Pinpoint, is this expected? Should the cli allow me to create a dashboard that cannot and will not receive data from the application?
Any suggestions on how to integrate this properly please?

**Comment by Andyluchina** [comment]
I am experiencing the same issue here. I followed the same documentation from above, and pinpoint does not seem to get any data

**Comment by srajsushmitha** [comment]
Same issue
