### ISSUE TITLE
Android SDK has no issues, AppSync Authorization Error (401) when log in using Cognito after arbitrary time usually 5 minutes

### ISSUE THREAD

**Issue by AlaaAlHallaq** [aws-amplify/aws-sdk-ios#2070]
Hello I a have an issue when I use appSync being loged in using CognitoUser Pools
and the same steps are used in our **android** version of the app **DOES NOT** have this issue

Here is my `awsconfiguration.json` file :

          
        {
            "UserAgent": "aws-amplify/cli",
            "Version": "0.1.0",
            "IdentityManager": {
                "Default": {}
            },
            "CredentialsProvider": {
                "CognitoIdentity": {
                    "Default": {
                        "PoolId": "us-east-1:##########",
                        "Region": "us-east-1"
                    }
                }
            },
            "CognitoUserPool": {
                "Default": {
                    "PoolId": "us-east-1_######",
                    "AppClientId": "########",
                    "AppClientSecret": "#######",
                    "Region": "us-east-1"
                }
            },
            "PinpointAnalytics": {
                "Default": {
                    "AppId": "#######",
                    "Region": "us-east-1"
                }
            },
            "PinpointTargeting": {
                "Default": {
                    "Region": "us-east-1"
                }
            },
            "S3TransferUtility": {
                "Default": {
                    "Bucket": "#######",
                    "Region": "us-east-1"
                }
            },
            "AppSync": {
                "Default": {
                    "ApiUrl": "https://########.appsync-api.us-east-1.amazonaws.com/graphql",
                    "Region": "us-east-1",
                    "AuthMode": "AWS_IAM",
                    "ClientDatabasePrefix": "GraphQL_AWS_IAM"
                }
            }
        }

and I initialize AppSync client using the following code:

        do {
            // Initialize the AWS AppSync configuration
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: AWSAppSyncServiceConfig(),
                                                                  credentialsProvider: AWSMobileClient.default(),
                                                                  cacheConfiguration: AWSAppSyncCacheConfiguration())
            
            // Initialize the AWS AppSync client
            let appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
            appSyncClient.apolloClient?.cacheKeyForObject = { $0["id"] }
            onResult(.success(appSyncClient))
        } catch {
            print("Error initializing appsync client. \(error)")
            onResult(.failure(error))
        }

and I register a configuration to my cognito user pool with the following code :

        let credentialProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: AWS_CognitoIdentityUserPoolId)
        let serviceConfiguration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialProvider)
        AWSServiceManager.default().defaultServiceConfiguration = serviceConfiguration
        let configurationUserPool = AWSCognitoIdentityUserPoolConfiguration.init(clientId: AWS_CognitoIdentityUserPoolAppClientId, clientSecret: AWS_CognitoIdentityUserPoolAppClientSecret, poolId: AWS_PoolId)
        AWSCognitoIdentityUserPool.register(with: serviceConfiguration, userPoolConfiguration: configurationUserPool, forKey: AWS_CognitoUserPoolsSignInProviderKey)

where `AWS_###` are constants have the same values as in the `awsconfiguration.json`, since using default configuration resulted in errors:

and for sign in I use the following :

        let pool = AWSCognitoIdentityUserPool.init(forKey: AWS_CognitoUserPoolsSignInProviderKey)
        pool.delegate = self // this ViewController implements the delegate methods
        pool.singUp(....) {
            // covering all cases of invalid user name & password &  
            // user need to be verified
            // finally
            AWSMobileClient.default().signIn(...)
        }

**And finally** as a test case (when ever I start getting 401 not authorized, WHICH does not appear directly after log in, but after arbitrary time, or after restarting the APP) of my Issue:

       let pool = GetUserPool
       let user = pool.currentUser()

        user?.getSession().continueWith {
            let expire = ($0.result?.expirationTime?.formatted()).or(other: "<nil>")
            let current = Date().formatted()
             // **session is valid !!!**
            print("Expire : \(expire), Current: \(current)")
            return nil
        }
        AWSMobileClient.default().initialize {
            if let error = $1 {
                // **no error printed**
                print("error: \(error)")
            } else if let state = $0 {
                print("state: \(state)")
                // **user is signed in**
                let d = UIApplication.shared.delegate as? AppDelegate
                let sync = d?.appSyncClient
                let fav = GetFavoriteByUserQuery(userId: SharedPreferences.userID)
                
                sync?.fetch(query: fav, cachePolicy: .fetchIgnoringCacheData,
                            queue: DispatchQueue.main) { result, error in
                                
                                print("result: \(result.or(other: "<nil>"))")
                                print("Error: \(error.or(other: "<nil>"))")
                }
            }
        }
    }
 
NOTE: `.or(other: )` is just an extension function for `Optional` types that returns an `Any` typed object either the `Wrapped` value or the input parameter if the `self` is nil, just for convenience 
        
SUMMRAY:
1- initialization : no errors
2- sign-in/signup: no errors
3- using AppSync =>
       after arbitrary time or after restarting the app after being logged in using cognito user pools,  **401 not auth ERROR occurs for no reason**

**Comment by royjit** [comment]
Hi @AlaaAlHallaq 
Thank you for reaching out and sorry to hear that you are facing issues. It looks like you are using `AWSMobileClient` and our old `CognitoSDK` in the same app. It is not a recommended approach. 
We recommend just to use `AWSMobileClient` for all your user pool related operations.  Please follow the steps here in [authentication](https://aws-amplify.github.io/docs/sdk/ios/authentication) and [AWS Appsync](https://aws-amplify.github.io/docs/sdk/ios/api#client-initialization).
