### ISSUE TITLE
AppSync Complex Object cannot upload two images in the same mutation

### ISSUE THREAD

**Issue by amuresia** [aws-amplify/aws-sdk-ios#2071]
**Describe the bug**
If a GraphQL model has two S3ObjectInputs defined, only one file is uploaded to S3

**To Reproduce**
1. Create a graphl schema that has a model with two S3Objects
2. Run a mutation to create a record in DynamoDB
3. The record in DynamoDB contains two dictionaries for both S3Objects
4. Only one file was uploaded to the S3 bucket

**Which AWS service(s) are affected?**
AppSync, S3, DynamoDB

**Expected behavior**
Both files should be uploaded to S3

**Environment(please complete the following information):**
 - SDK Version: 2.12.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 13.2
 - Specific to simulators: N

**Additional context**
1. Schema:
```
type Object
@model
@auth(rules: [{ allow: owner, ownerField: "owner", operations: [create, update, delete] }]) {
    id: ID!
    owner: String!
    photo1: S3Object!
    photo2: S3Object!
}

type S3Object {
    bucket: String!
    region: String!
    key: String!
}

input S3ObjectInput {
    bucket: String!
    region: String!
    key: String!
    mimeType: String!
    localUri: String!
}
```
2. Mutation:
```
guard let identityId = AWSMobileClient.default().identityId else { return }
            let photo1Key = "protected/" + identityId + "/" + UUID.init().uuidString + ".jpeg"
            let photo1 = S3ObjectInput(bucket: "wearwell-dev", region: "eu-west-2", key: photo1Key, mimeType: "image/jpeg", localUri: photo1AbsoluteString)
        
        let photo2Key = "protected/" + identityId + "/" + UUID.init().uuidString + ".jpeg"
        let photo2 = S3ObjectInput(bucket: "wearwell-dev", region: "eu-west-2", key: photo2Key, mimeType: "image/jpeg", localUri: photo2AbsoluteString)
        
            let mutationInput = CreateObjectInput(id: self.id, email: self.email, photo1: photo1, photo2: photo2)
```
3. This only uploads one file to S3, most of the times it's photo1
4. The record in DynamoDB contains dictionaries for both files, yet only one is present in S3

**Comment by kneekey23** [comment]
hi @amuresia this is a known feature gap and on our backlog: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/6
