### ISSUE TITLE
How to compile manually for Catalyst

### ISSUE THREAD

**Issue by ppamorim** [aws-amplify/aws-sdk-ios#2072]
In our project the SDK is included as a pre-compiled framework, we are not using the cocoapods setup due the compilation time and caching between targets. Instead we use submodules and use your script to build the framework.

So to compile the SDK we have the script below:

```
AWS_SCHEMES ="AWSCore AWSS3"

cd aws-sdk-ios

chmod +x CircleciScripts/package_sdk.sh

for SCHEME in ${AWS_SCHEMES}; do
  sh CircleciScripts/package_sdk.sh ${SCHEME}
done

cd ..
cp -R aws-sdk-ios/builtFramework/framework/* Frameworks
```
This is working fine for iOS and now we need to compile the SDKs for Catalyst, any idea of what can be done? 

Realm-cocoa has a very nice setup for this (example): https://github.com/realm/realm-cocoa/blob/master/build.sh#L576
Is there anything similar for AWS SDK?

**Which AWS Services are you utilizing?**
AWSCore AWSS3

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.12.2
 - Dependency Manager: None
 - Swift Version : 5.0

EDIT:

I am trying to compile it based on the base configuration script with some modifications:

```
xcodebuild ONLY_ACTIVE_ARCH=NO \
        -configuration Release \
        -project "${project_path}" \
        -target "${project_name}" \
        -destination "platform=macOS,arch=x86_64,variant=Mac Catalyst" \
        SYMROOT=$(PWD)/builtFramework \
        SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES SUPPORTS_MACCATALYST=YES
```

I am not sure if this will work anyway.

**Comment by kneekey23** [comment]
hi @ppamorim as of right now we only support iOS. Until a business/product decision is made to support other platforms, you can merge in this PR yourself: https://github.com/aws-amplify/aws-sdk-ios/pull/2065 to compile for Catalyst although the implications for this merge are unknown with the various parts of the SDK.

**Comment by victorBaro** [comment]
@ppamorim curious to know if you got that working
