### ISSUE TITLE
Semaphore misuse leads to thread explosion

### ISSUE THREAD

**Issue by dtorres** [aws-amplify/aws-sdk-ios#2073]
**Describe the bug**

When cognito is refreshing credentials, there is a step in `AWSCredentialsProvider.m:626` that waits for a semaphore to clear.

If many requests are in flight, this leads to N threads being paused until the semaphore clears or the timeout happens..

- 60 seconds to stall a thread is unacceptable in mobile environments, let alone one for each inflight request

And the more serious problem:
- Dispatch has a hard limit on the threads it spawns, one that limit is reached, Dispatch is unable to do more work, affecting all other services that rely on it.

Attached is the trace this happens in. Note that there are 100 (ONE HUNDRED!) threads with the same stack.
<img width="546" alt="Screenshot 2019-12-04 at 14 57 27" src="https://user-images.githubusercontent.com/71180/70148892-5931b200-16a7-11ea-9076-c2f50f791962.png">

**To Reproduce**
- Use cognito to authenticate
- Start to upload thousands of files to S3* to increase chances of hitting this state
- Profit

* I am able to reproduce this usually with 10-15 items being uploaded. I have no idea what triggers the explosion, but those steps should ensure reproduction
**Which AWS service(s) are affected?**
- None, Just all iOS devices using the SDK
**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**

**Comment by dtorres** [comment]
For now, we are going to patch the SDK and limit the NSOperationQueue concurrent items. (This does not fix the issue, only limits our exposure to it)

**Comment by lawmicha** [comment]
Hi @dtorres, there has been some improvements to the SDK such as https://github.com/aws-amplify/aws-sdk-ios/pull/3872 . Since this has been open for awhile now, please give the latest SDK a try. I'll proactively close this but feel free to open another issue if you are still seeing the problem.
