### ISSUE TITLE
Fatal crash reported via Crashlytics

### ISSUE THREAD

**Issue by bfallon** [aws-amplify/aws-sdk-ios#2074]
**Describe the bug**
We are using Crashlytics to record issues in our app. AWS is triggering a crash:

**+[AWSPinpointDateUtils isoDateTimeWithTimestamp:]**

**To Reproduce**
No reproduction steps

**Which AWS service(s) are affected?**
Pinpoint

**Expected behavior**
Not crashing

**Screenshots**
N/A

**Environment(please complete the following information):**
 - SDK Version: '2.9.6'
 - Dependency Manager: Cocoapods
 - Swift Version : 4

**Device Information (please complete the following information):**
 - Device: iPhone XR
 - iOS Version: 13.2.3
 - Specific to simulators: No

**Additional context**

**Comment by drochetti** [comment]
Do you have more information on when the crash happens? Is it during a specific Pinpoint call?

Also, I realize you're using an older version of the SDK. Is upgrading possible? Current version is 2.12.3
