### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by DTTTickets** [aws-amplify/aws-sdk-ios#2075]
**Which AWS Services is the feature request for?**
The AWSMobileClient for iOS. Specifically the sign in flow.

**Is your feature request related to a problem? Please describe.**
I need to localise all the strings in the sign in flow, and there is no easy way to do this

**Describe the solution you'd like**
Add the possibility to customise more the sign in screen.

**Describe alternatives you've considered**
Localise all the strings.

**Comment by kneekey23** [comment]
hi @DTTTickets we leave localization up to the app developer and all our messages are meant for developers.
