### ISSUE TITLE
Sign In with Custom Auth Does Not Return Challenge Parameters with SignInResult

### ISSUE THREAD

**Issue by rigocarbajal** [aws-amplify/aws-sdk-ios#2148]
**Describe the bug**
We are using Amplify Cognito with Custom Auth. When we initiate sign in, we get back a SignInResult value with signInState == .customChallenge. However, signInResult.parameters returns an empty dictionary. In the Android SDK, at this point, signInResult.parameters contains the challenge parameters for the custom challenge. This is the expected behavior. In iOS, we do not receive back the challenge parameters.  

**To Reproduce**
1. Verify that Cognito is setup for Custom Auth.
2. Call AWSMobileClient.default().signIn(username: email, password: password, completionHandler: ...)
3. Verify that the completion handler is called with signInResult.signInState == .customChallenge.
4. Verify that at this point, signInResult.parameters returns an empty dictionary.

**Expected behavior**
Challenge parameters should be made available to caller when receiving custom challenge in signIn(..) completion handler. This is the current behavior in the Android SDK. 

**Environment(please complete the following information):**
 - SDK Version: 2.12.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 13.0
 - Specific to simulators: No

**Comment by lawmicha** [comment]
Hi @rigocarbajal, thanks for reporting this issue.

- Do you have a particular Custom Auth set up instructions you were following? It would be good to update the docs regarding what the parameters should contain in regards to how custom auth was set up.
- Can you provide more context, on Android side, what are the challenge parameters that you got back?  @desokroshan may have some context on this from Android side and @royjit on iOS side as they were working on that code

**Comment by lawmicha** [comment]
confirmed with @desokroshan  that this is most likely a bug on the iOS side since if it is the same backend, we should be propagating that back up from the lower level SDK to AWSMobileClient.

**Comment by rigocarbajal** [comment]
Hi Michael,

Glad to hear you were able to confirm with desokroshan.

The challenge parameter that we are expecting back is “pollFrequencySecs”. This is a custom value that our backend sends to the client to let us know how often we should poll the service.

Please let me know if you have any other questions.

Thanks,
Rigo

**Comment by royjit** [comment]
Apologies for the late response. I made a fix to handle the issue in this PR #2213. Should be available in the next release of the SDK.

**Comment by rigocarbajal** [comment]
Much appreciated! Any idea when the next release is going out?

**Comment by royjit** [comment]
This is released in the iOS SDK 2.12.5  https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.12.5

**Comment by MaheshSC** [comment]
@rigocarbajal  can you please help me to implement signing flow with AWS Cognito / Mobile Client
