### ISSUE TITLE
User is not logged in after confirmSignup success

### ISSUE THREAD

**Issue by ankitaporwal** [aws-amplify/aws-sdk-ios#2149]
I am using AWS SDK iOS and signing works fine but when I signup and then confirmSignup it returns signup response as confirmed but the calls to getToken return nil and userState is LoggedOut in the SDK. Any help would be appreciated. 

I am using following sdk versions 
 AWSAppSync (3.0.0)
 AWSAuthCore (2.12.3)
 AWSAuthUI (2.12.3)
 AWSCognitoIdentityProvider (2.12.3)
 AWSCognitoIdentityProviderASF (1.0.1)
 AWSCore (2.12.3)
 AWSMobileClient (2.12.3)
 AWSUserPoolsSignIn (2.12.3)

**Comment by royjit** [comment]
Hi @ankitaporwal Thank you for reaching out. 
After signUp and confirmSignUp, you need to call `AWSMobileClient.default().signIn` for the user to sign in properly.
