### ISSUE TITLE
FORCE_CHANGE_PASSWORD Flow fails on modifying non-mutable attributes

### ISSUE THREAD

**Issue by dconroy** [aws-amplify/aws-sdk-ios#2203]
**Describe the bug**
When a cognito user pool has a user that is of state FORCE_CHANGE_PASSWORD, the library detects this and asks user for new password. After entering password, app gives InvalidParameterException error alert "Cannot modify the non-mutable attribute email_verified"

Image: https://imgur.com/BdNip1o

**To Reproduce**
Create a user, and go to cognito user pool and force the user to FORCE_CHANGE_PASSWORD state. Attempt login through aws ios sdk

**Which AWS service(s) are affected?**
AWS Cognito

**Expected behavior**
I'd expect user state to change in cognito to CONFIRMED, password to be updated, and then return with a logged in user to the sign in flow.

**Screenshots**
Image: https://imgur.com/BdNip1o

**Environment(please complete the following information):**
 - SDK Version: 
- AWSAuthCore (2.12.3):
    - AWSCore (= 2.12.3)
  - AWSAuthUI (2.12.3):
    - AWSAuthCore (= 2.12.3)
    - AWSCore (= 2.12.3)
  - AWSCognitoIdentityProvider (2.12.3):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
    - AWSCore (= 2.12.3)
  - AWSCognitoIdentityProviderASF (1.0.1)
  - AWSCore (2.12.3)
  - AWSMobileClient (2.12.3):
    - AWSAuthCore (= 2.12.3)
    - AWSCognitoIdentityProvider (= 2.12.3)
  - AWSS3 (2.12.3):
    - AWSCore (= 2.12.3)
  - AWSUserPoolsSignIn (2.12.3):
    - AWSAuthCore (= 2.12.3)
    - AWSCognitoIdentityProvider (= 2.12.3)
 - Dependency Manager: CocoaPods
 - Swift Version : 4

**Device Information (please complete the following information):**
n/a

**Additional context**
Is this due to some setting of the user pool that the email address cant be updated?

**Comment by ChrisInspect** [comment]
Can you provide your code for confirming signIn?

**Comment by dconroy** [comment]
I am not sure what you are asking. My instantiation of AWSMobileClient signIn is [here]

`func userSignIn(navController: UINavigationController) {
    print("userSignIn->handler")
    let signInUIOptions = SignInUIOptions(canCancel: true, logoImage: UIImage(named: "Icon-86"), backgroundColor:  UIColor.darkGray)
    AWSMobileClient.default().showSignIn(navigationController: navController, signInUIOptions: signInUIOptions, { (state, error) in
        switch (state) {
            case .guest:
                userGlobalState = .userGuest
            case .signedOut:
                userGlobalState = .userSignedOut
            case .signedIn:
                userGlobalState = .userSignedIn
            case .signedOutUserPoolsTokenInvalid:
                userGlobalState = .userSignedOutUserPoolsTokenInvalid
            case .signedOutFederatedTokensInvalid:
                userGlobalState = .userSignedOutFederatedTokensInvalid
            default:
                userGlobalState = .userStateUnknown
        }
    })
}`

**Comment by dconroy** [comment]
I have done some more digging, and the error above is when you create a new user in the cognitor management console, forcing them to change their pw,  and check the box to confirm their email is verified. When resetting their pw at next login, they get the "Cannot modify the non-mutable attribute email_verified"

This is still an issue, because if you are creating new users in cognito management console and do not select their email as verified, they can not  reset their password via the aws sdk forgot password link as an email is never stored in cognito.

**Comment by wooj2** [comment]
Hi!  Thanks for your in-depth investigation towards this issue.  I've created a PR to filter out this field for the FORCE_CHANGE_PASSWORD workflow.

https://github.com/aws-amplify/aws-sdk-ios/pull/2240

**Comment by wooj2** [comment]
Change has been pushed to our develop branch.  Thank you again for detailed investigation and reporting of this bug!

I am optimistically closing this issue since a client side fix has been pushed to our develop branch.
