### ISSUE TITLE
FORCE_CHANGE_PASSWORD Flow UI Issues

### ISSUE THREAD

**Issue by dconroy** [aws-amplify/aws-sdk-ios#2206]
Describe the bug
When a cognito user pool has a user that is of state FORCE_CHANGE_PASSWORD, the library detects this and asks user for new password. While trying to enter the passwords, if  background color is set to black, you cant see the text for canceling/going back,  "New Password Required" or "Please enter your new password below"

Image: https://imgur.com/BdNip1o

To Reproduce
Create a user, and go to cognito user pool and force the user to FORCE_CHANGE_PASSWORD state. Attempt login through aws ios sdk

`signInUIOptions = SignInUIOptions(canCancel: true, logoImage: UIImage(named: "Icon-86"), backgroundColor:  UIColor.black)`

Which AWS service(s) are affected?
AWS Cognito

Expected behavior
I'd expect the ui text to turn white or some color visible over black 

Screenshots
https://imgur.com/RRwVAjo

Environment(please complete the following information):

SDK Version:
AWSAuthCore (2.12.3):
AWSCore (= 2.12.3)
AWSAuthUI (2.12.3):
AWSAuthCore (= 2.12.3)
AWSCore (= 2.12.3)
AWSCognitoIdentityProvider (2.12.3):
AWSCognitoIdentityProviderASF (= 1.0.1)
AWSCore (= 2.12.3)
AWSCognitoIdentityProviderASF (1.0.1)
AWSCore (2.12.3)
AWSMobileClient (2.12.3):
AWSAuthCore (= 2.12.3)
AWSCognitoIdentityProvider (= 2.12.3)
AWSS3 (2.12.3):
AWSCore (= 2.12.3)
AWSUserPoolsSignIn (2.12.3):
AWSAuthCore (= 2.12.3)
AWSCognitoIdentityProvider (= 2.12.3)
Dependency Manager: CocoaPods
Swift Version : 4
Device Information (please complete the following information):
n/a

**Comment by palpatim** [comment]
This would be handled as part of the UI customizations requested in #1158. Just to verify where we're using the `SignInUIOptions` values, here are screenshots where I've set:

```swift
backgroundColor: UIColor.red
secondaryBackgroundColor: UIColor.yellow
primaryColor: UIColor.green
```

![01-signIn](https://user-images.githubusercontent.com/227982/72194960-ee217c80-33c4-11ea-862e-7160eb869603.jpg)

![02-newPassword](https://user-images.githubusercontent.com/227982/72194965-f1b50380-33c4-11ea-8098-9ce86aa3b00d.jpg)
