### ISSUE TITLE
AWSS3TransferUtilityUploadCompletionHandlerBlock is not called

### ISSUE THREAD

**Issue by nick3389** [aws-amplify/aws-sdk-ios#2211]
**Describe the bug**
I upload files with background upload support to S3 using the AWSS3transferUtility for a long time. The last couple of days, there are huge delays or unsuccessful calls of the AWSS3TransferUtilityUploadCompletionHandlerBlock block which lets me know actually that my request is successful. I have an on demand service which uploads some files and I see from the console that the AWSTask is created successfully but it is either uploaded very late or never. Internet connection is on WiFi.

**To Reproduce**
Create a AWSS3TransferUtility instance and make a uploadFile in a bucket request. Set the completion
```
let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "any_key")
transferUtility.uploadFile(fileURLPath, bucket: bucket, key: key, contentType: "application/zip", expression: expression, completionHandler: { (task, error) -> Void in
     print("upload is successful")
}).continueWith { (task) -> Any? in

     if let error = task.error {
           log.error("error in creating aws upload task", error: error)
     }

     if let uploadTask = task.result {
     // Do something with uploadTask.
           print("aws upload task created successfully: \(uploadTask.sessionTask.currentRequest?.allHTTPHeaderFields?["x-amz-meta-taskuuid"] ?? "")")
     }

     return nil
}
})
```
"aws upload task created successfully" print is executed every time, whereas the "upload is successful" is not.

**Which AWS service(s) are affected?**
AWSS3TransferUtility
**Expected behavior**
I expected my files to be immediately available to S3 and my completion block to be called very soon after the request.

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.12.3
 - Dependency Manager: e.g. Cocoapods
 - Swift Version : 5.1.3

**Device Information (please complete the following information):**
 - Device: iPhoneX
 - iOS Version: iOS 13.3
 - Specific to simulators:

**Comment by nick3389** [comment]
@royjit the issue still exists with **v2.12.5**. The upload is random.

**Comment by nick3389** [comment]
@royjit I confirmed today that there is the same issue in another iPhone X. In an iPhone 6s that I tested too, it was working ok.

**Comment by nick3389** [comment]
@royjit Any news about this issue?

**Comment by pskow** [comment]
@royjit I'm experiencing the same issue in v2.12.6.

**Comment by nick3389** [comment]
@royjit Do you have any news? We are still experiencing the same issue as well as some of our clients. Uploading is random in some cases and the issue seems to also happen when using cellular upload mode by setting `allowsCellularAccess` to true in `AWSServiceConfiguration`.

**Comment by nick3389** [comment]
@pskow Do you have any idea of why this is happening? Imagine that my device cannot upload anything since last Thursday... I have tried with both WiFi and Cellular data but still no luck.

**Comment by pskow** [comment]
@nick3389 I noticed that sometimes I'm getting callback from AWSS3TransferUtilityTask with progress.isFinished twice and sometimes just once and completion handler actually informs about successful upload. I'm using RXSwift in my code and I was releasing Operation when I got isFinished from progress. This was causing interruption in sync on very last moment and file just disappeared. When I allow this process to complete without releasing it, I got it to work. If you need more help, you can find my contact on profile page.

**Comment by nick3389** [comment]
@pskow I do not use Operation or OperationQueue at all. I just make an on demand upload request (among others) using the AWSS3TransferUtility API. The problem as I think is that the request is not even fired despite the fact that the success block of the creation of the AWSTask is called as I mentioned before. I will try to intercept all the requests from the device to see if it is actually happening and I will get back with results.

**Comment by nick3389** [comment]
@palpatim Maybe you should close this issue as there is no reoccurrence since then and the linked ticket is closed as well.

**Comment by palpatim** [comment]
Thanks for confirming no recurrence @nick3389. Closing.
