### ISSUE TITLE
How can I upload files to S3 when using AppSync/Aurora/iOS?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/aws-sdk-ios#2212]
Hello,

I see in the documentation something about uploading S3 files when using DynamoDB:
https://aws-amplify.github.io/docs/sdk/ios/storage#storage

But, what about if we use Aurora? There is no mention about Aurora.

Do I have to add a table with those fields manually? (bucket, region and key)

Thanks for any suggestion.

**Comment by royjit** [comment]
Hi @Ricardo1980 

Thank you for reaching out. Complex objects in AWS Appsync currently is supported only by DyamoDB. We will inform the Appsync service team to add this as a feature request.

**Comment by Ricardo1980** [comment]
@royjit 
thanks

But, at the moment, what kind of workaround should I use?
In other words, how can I upload files when I use Aurora?
Thanks

**Comment by royjit** [comment]
You have to manually implement the details. You might need to create custom resolvers that updates the s3 fields into aurora.
