### ISSUE TITLE
Forgot PW UI Issue

### ISSUE THREAD

**Issue by dconroy** [aws-amplify/aws-sdk-ios#2220]
Describe the bug
When resetting password using forgot password link, the following screen has two separate display hint texts, when one is probably desired. See img link below where confirmation and new password labels are duplicated

![Duplicate Hints](https://i.imgur.com/8Te6TDN.png "Duplicate Hints")

To Reproduce
Create a user, then log out, and try to reset password.

Which AWS service(s) are affected?
AWS Cognito

Expected behavior
I'd expect a cleaner display

Screenshots
Image: https://i.imgur.com/8Te6TDN.png

Environment(please complete the following information):

SDK Version:
AWSAuthCore (2.12.3):
AWSCore (= 2.12.3)
AWSAuthUI (2.12.3):
AWSAuthCore (= 2.12.3)
AWSCore (= 2.12.3)
AWSCognitoIdentityProvider (2.12.3):
AWSCognitoIdentityProviderASF (= 1.0.1)
AWSCore (= 2.12.3)
AWSCognitoIdentityProviderASF (1.0.1)
AWSCore (2.12.3)
AWSMobileClient (2.12.3):
AWSAuthCore (= 2.12.3)
AWSCognitoIdentityProvider (= 2.12.3)
AWSS3 (2.12.3):
AWSCore (= 2.12.3)
AWSUserPoolsSignIn (2.12.3):
AWSAuthCore (= 2.12.3)
AWSCognitoIdentityProvider (= 2.12.3)
Dependency Manager: CocoaPods
Swift Version : 4
Device Information (please complete the following information):
n/a

**Comment by wooj2** [comment]
Thanks for reporting this issue.  I have submitted a pull request here:
https://github.com/aws-amplify/aws-sdk-ios/pull/2238

**Comment by wooj2** [comment]
Thanks again for reporting this issue.  The PR has been pushed to our develop branch, and I am optimistically closing this issue.
