### ISSUE TITLE
hundreds of _Null_unspecified warnings as of Version 2.12.5

### ISSUE THREAD

**Issue by Bersaelor** [aws-amplify/aws-sdk-ios#2232]
**Which AWS Services is the feature request for?**

`AWSMobileClient` and `AWSAuthCore`

**Is your feature request related to a problem? Please describe.**
We thought of updating to the latest `AWSMobileClient`, as we were still on `2.10.3` and installed the latest version via `pod update` today.
Unfortunately there are hundreds of warnings caused by the above frameworks, most of them like:
```
...AWSSignature.h:19:28: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
```
**Describe the solution you'd like**

To get rid of the warnings, it would be great if the ObjC frameworks were to include information about their nullability. This language feature in ObjC has been[ introduced in Xcode 7 and around for a while.](https://developer.apple.com/swift/blog/?id=25).

For example, instead of 

```
+ (NSData *)sha256HMacWithData:(NSData *)data withKey:(NSData *)key;
```

we could write
```
+ (NSData * _Nullable)sha256HMacWithData:(NSData * _Nullable)data withKey:(NSData * _Nullable)key;
```

This would make the framework safer to use and give more information about the pointers used in the API to the application developers using AWS.

**Comment by royjit** [comment]
We are aware of this issue and currently tracked here - https://github.com/aws-amplify/aws-sdk-ios/issues/2001.
Closing this as duplicate.
