### ISSUE TITLE
How could I upload image to s3 with public permissions?

### ISSUE THREAD

**Issue by student-101** [aws-amplify/aws-sdk-ios#2233]
How could I upload image to s3 with public permissions?

This code didn't work.
```
let expression = AWSS3TransferUtilityUploadExpression()
expression.progressBlock = uploadProgressBlock
expression.setValue("public-read", forRequestHeader: "x-amz-acl")

let transferUtility = AWSS3TransferUtility.default()
transferUtility.uploadData(data, bucket: bucketName, key: uploadKeyName, contentType: contentType, expression: expression, completionHandler: uploadCompletionHandler).continueWith { (task) -> AnyObject? in
    if let error = task.error {
            
    }
    if let _ = task.result {
                
    }
    return nil
}

```
but this code worked
```
let expression = AWSS3TransferUtilityUploadExpression()
expression.progressBlock = uploadProgressBlock
//    expression.setValue("public-read", forRequestHeader: "x-amz-acl")

let transferUtility = AWSS3TransferUtility.default()
transferUtility.uploadData(data, bucket: bucketName, key: uploadKeyName, contentType: contentType, expression: expression, completionHandler: uploadCompletionHandler).continueWith { (task) -> AnyObject? in
    if let error = task.error {
                
    }
    if let _ = task.result {
                
    }
    return nil
}

```
Why did I fail to add requestHeader?

**Comment by student-101** [comment]
I attached "PutObjectAcl" pulicy to my IAM role and my code worked successfully.

**Comment by lawmicha** [comment]
hi @student-101 , thanks for opening this issue. Good to see you were able to resolve the issue.

"As a general rule, AWS recommends using S3 bucket policies or IAM policies for access control. S3 ACLs is a legacy access control mechanism that predates IAM. However, if you already use S3 ACLs and you find them sufficient, there is no need to change."
https://aws.amazon.com/blogs/security/iam-policies-and-bucket-policies-and-acls-oh-my-controlling-access-to-s3-resources/

If you are interested, please check out https://aws-amplify.github.io/docs/js/storage#using-amazon-s3

when you use Amplify CLI to provision S3, it will guide you through setting up permissions on the S3 bucket which will attach the corresponding polices for each role for proper S3 access
