### ISSUE TITLE
AWSS3TransferUtility iOS 13. Uploading a file to S3 inside a Messages message extension generates The operation couldn’t be completed. (NSURLErrorDomain error -995)

### ISSUE THREAD

**Issue by bmctigue** [aws-amplify/aws-sdk-ios#2250]
I have an application that is an iMessage message extension. The code for uploading is fairly vanilla and is basically the code used for the uploading examples to S3. When I try to upload a file, I am always seeing NSURLErrorDomain error -995 error. From the research I have done this error is related to iOS share groups for sharing data between the message extension and the host application. This may have to do with background uploading. I added the share groups for the host application and the message extension. I also added the share group to the AWSServiceConfiguration, but I still see the error. See below for some sample code. Any insight would be appreciated.

FYI, this file(data) uploads and downloads perfectly with the deprecated AWSS3TransferManager.

Create an iMessage message extension.
Add S3 support to the message extension.
Upload a file to S3.

I expected the file to upload normally. I am getting a NSURLErrorDomain error -995.

 - SDK Version: 2.12.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

 - Device: iPhoneSE, Simulator (Any version of the phone)
 - iOS Version: 13.3

Sample code for main image upload class:

lazy var fileManager = FileManager.default
    lazy var credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast2, identityPoolId: "##########")
    lazy var configuration = AWSServiceConfiguration(region: AWSRegionType.USEast2, credentialsProvider: credentialsProvider)
    lazy var tuConfiguration = AWSS3TransferUtilityConfiguration()
    lazy var serviceManager = AWSServiceManager.default()!
    var transferUtility: AWSS3TransferUtility
    lazy var s3 = AWSS3.default()

init() {
        self.transferUtility = AWSS3TransferUtility.default()
        configuration?.sharedContainerIdentifier = AWSImageStore.shareGroupName
        tuConfiguration.retryLimit = 5
        tuConfiguration.timeoutIntervalForResource = 15*60
        
        AWSS3TransferUtility.register (
            with: configuration!,
            transferUtilityConfiguration: tuConfiguration,
            forKey: "transfer-utility-with-advanced-options"
        ) { (error) in
             if let error = error {
                print("AWSS3TransferUtility.register: \(error.localizedDescription)")
             }
        }
    }

  func saveImage(_ imageURL: URL, conversation: MSConversation, completion: @escaping (String, Error?) -> Void) {
        if let data = fileManager.contents(atPath: imageURL.path) {
            let assetID = UUID().uuidString
            do {
                let expression = AWSS3TransferUtilityUploadExpression()
                expression.progressBlock = { (task: AWSS3TransferUtilityTask, progress: Progress)  in
                      DispatchQueue.main.async(execute: {
                        self.messagesDelegate?.updateUploadProgress(with: Float(progress.fractionCompleted))
                     })
                }
                transferUtility.uploadData(data, bucket: Constants.S3BucketName, key: assetID, contentType: AWSImageStore.contentType, expression: expression)  { task, error in
                    DispatchQueue.main.async {
                        completion(assetID, error)
                    }
                }
            }
        }
    }

**Comment by lawmicha** [comment]
Hi @bmctigue, thanks for reporting this issue. Unfortunately, the iOS SDK is only supported for building iOS apps and does not support building message extensions. It sounds like you were able to download/upload using the deprecated AWSS3TransferManager and the newer AWSTransferUtility is having troubles related to background uploading. If you would like to continue using iOS SDK for this purpose, I would suggest trying to use the lower level `AWSS3` instance to reduce the complexity because they will reduce to just requests against S3. That's what AWSTransferManager and TransferUtility is doing under the covers. But please keep in mind we do not support the messages extension use case.

**Comment by bmctigue** [comment]
Hi Lawmicha, I did as you suggested and replaced the manager and utility code with the AWSS3 default instance. Code is almost identical and is working fine now. Thanks. I'll close this.

**Comment by PrincessMine** [comment]
@bmctigue could you please share which lower level of AWSS3 you had used for this or any other detailed code changes that can help me too to solve this same issue with my Share Extension.

**Comment by Aoi-Takahashi** [comment]
@bmctigue @PrincessMine Me too, please. Over time, we are facing a similar problem now.
