### ISSUE TITLE
AWSMobileClient getIdentityId fails after signIn call

### ISSUE THREAD

**Issue by laurentbourg** [aws-amplify/aws-sdk-ios#2251]
Hi, I am running into an issue when not using the pre-canned Cognito login UI that comes with AWSMobileClient (i.e showSignIn). When using the AWSMobileClient signIn method and passing the username and password, I get a successful signed-in state and then call getIdentityId, but the call fails:

Error Domain=com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper Code=0 "Obtaining an identity id in another thread failed or didn't complete within 5 seconds." UserInfo={NSLocalizedDescription=Obtaining an identity id in another thread failed or didn't complete within 5 seconds.}

 It seems that for some reason, the variable currentSignInProvider in AWSSignInManager does not get set during the AWSMobileClient signIn call. If I restart the app, then all works fine because the resumeSession method is called which sets everything properly. I have the same issue when calling federatedSignIn whereas everything works fine using the Cognito UI.

Thanks in advance for your help.
Laurent

**Which AWS Services are you utilizing?**
Cognito/AWSMobileClient

**Environment(please complete the following information):**
AWSAPIGateway (2.12.3):
    - AWSCore (= 2.12.3)
  - AWSAuthCore (2.12.3):
  - AWSAuthUI (2.12.3):
  - AWSCognitoIdentityProvider (2.12.3):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
  - AWSFacebookSignIn (2.12.3):
    - FBSDKCoreKit (= 5.8)
    - FBSDKLoginKit (= 5.8)
  - AWSGoogleSignIn (2.12.3):
  - AWSMobileClient (2.12.3):
  - AWSS3 (2.12.3):
  - AWSUserPoolsSignIn (2.12.3):
 
- Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Iphone 11 Pro Max Simulator
 - iOS Version: iOS 12.1
 - Specific to simulators: No

**Comment by laurentbourg** [comment]
It breaks in AWSIdentityManager because currentSignInProvider is nil, why doesn't the AWSMobileClient signIn call set that property as a Cognito user pool provider instance?

- (AWSTask<NSDictionary<NSString *, NSString *> *> *)logins {
    if (![AWSSignInManager sharedInstance].**currentSignInProvider**) {
        return [AWSTask taskWithResult:nil];
    }
    return [[[AWSSignInManager sharedInstance].currentSignInProvider token] continueWithSuccessBlock:^id _Nullable(AWSTask<NSString *> * _Nonnull task) {
        NSString *token = task.result;
        return [AWSTask taskWithResult:@{[AWSSignInManager sharedInstance].currentSignInProvider.identityProviderName : token}];
    }];
}

**Comment by laurentbourg** [comment]
Did anybody ever encounter this issue? This seems to be a pretty basic use case and easy to repeat.

**Comment by kneekey23** [comment]
hi @laurentbourg can you post a snippet of your code possibly? I am able to call identityId on a successful .signedIn state without this error.

**Comment by laurentbourg** [comment]
Hi kneekey23, thanks for getting back to me. Try the below test client. 

Important: make sure indentityId is not cached prior (e.g. erase all content and settings on simulator device prior to running)

AppDelegate.swift

import UIKit
import AWSMobileClient

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        return AWSMobileClient.default().interceptApplication(
                 application,
                 didFinishLaunchingWithOptions: launchOptions)
    }

    // MARK: UISceneSession Lifecycle

    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
        // Called when a new scene session is being created.
        // Use this method to select a configuration to create the new scene with.
        return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
    }

    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) {
        // Called when the user discards a scene session.
        // If any sessions were discarded while the application was not running, this will be called shortly after application:didFinishLaunchingWithOptions.
        // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
    }
}

ViewController.swift

import UIKit
import AWSMobileClient

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
     
        AWSMobileClient.default().signOut()
        AWSMobileClient.default().initialize() {userstate, error in
            if let userstate = userstate {
                if (userstate != .signedIn) {
                    AWSMobileClient.default().signIn(username: "cognitousername", password: "cognitopassword") {signInResult, error in
                        if let signInResult = signInResult {
                            if (signInResult.signInState == .signedIn) {
                                AWSMobileClient.default().getIdentityId().continueWith {task in
                                    if let error = task.error {
                                        print(error)
                                    } else if let result = task.result {
                                        print(result)
                                    }
                                    return nil
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

**Comment by laurentbourg** [comment]
If you are able to replicate using code above, then try the following:

In AppDelegate.swift, replace
"return AWSMobileClient.default().interceptApplication(
             application,
             didFinishLaunchingWithOptions: launchOptions)"

with "return true"

The issue then seems to go away :)

**Comment by laurentbourg** [comment]
Hi Nicole, thanks for looking into it, I got back to you in the GitHub thread.

Laurent

**Comment by laurentbourg** [comment]
Hi kneekey23, please don't hesitate if anything else if needed from me in order to replicate the issue.

**Comment by kneekey23** [comment]
hi @laurentbourg in the latest version of the AWSMobileClient, we don't actually support the above functionality (interception from the app delegate), it has been deprecated for our Swift interface, (but not for our Objc Interface) completely per PR #1738 . Your code is actually correct if you just remove that piece from the App delegate so glad it works without it. :)  I am sorry if you found this in out of date documentation, we have tried to update this everywhere but may have missed a spot, I will work to fix this. Let me know if you are experiencing any other issues when you remove this intercept code from the AppDelegate.

**Comment by laurentbourg** [comment]
Thanks @kneekey23 for your reply. The main reason I was using this call in AppDelegate was to ensure that my userState would return guest upon AWSMobileClient initialization, without that statement it returns signedOut. How do I adequately reflect the guest userState status?

**Comment by kneekey23** [comment]
hi @laurentbourg it's actually provided out of the box with mobile client as long as Cognito is set up correctly. Have you tried setting up your auth with the amplify cli per the [amplify documentation](https://aws-amplify.github.io/docs/ios/authentication#guest-access)?

**Comment by laurentbourg** [comment]
Hi @kneekey23, yes I did have it properly setup via the amplify CLI:

Allow unauthenticated logins? (Provides scoped down permissions that you can co
ntrol via AWS IAM) Yes

and I also see the checkbox properly checked for the corresponding identity pool in the AWS Console.



Is the expectation that when I initialize the AWSMobileClient, it would return me a .guess UserState? I get a .signedOut state, but when plugging the interception call, I get a .guest.

**Comment by kneekey23** [comment]
hi @laurentbourg If initialize is giving you the state as ‘signedOut’, try running:
```
 AWSMobileClient.default().getAWSCredentials() {credentials, error in
      print(credentials)
  }
```
With a fresh install AWSMobileClient.default().initialize gives you signedOut as the state. Every time after that, it will properly hit the .guest state when calling initialize.

**Comment by laurentbourg** [comment]
Thanks @kneekey23, I just tried, you are correct, the behavior is confirmed to be as follows:

1) Erase Content & Settings on Simulator

- calling getAWSCredentials
- then calling Initialize -> userState is signedOut
- calling Initialize again -> userState is now Guest

If the getAWSCredentials is not done, the Initialize call never switches to guest.

2) Restart the executable:

- calling Initialize -> userState is guest
- calling Initialize again -> userState is guest
guest is sticky from there on.

Why is this behavior correct, it seems counter intuitive / ambiguous / border line obscure ? Initialize needs to be idempotent. e.g. I should not get different states when calling it twice like above.

My expectation is the following:

The AWSMobileClient initialize call should validate that the identity pool supports unauthorized access and return a userState of guest if that’s the case and signedOut otherwise.

What do you think?

**Comment by kneekey23** [comment]
hi @laurentbourg this would be a massive security flaw if the client library knew how the service was configured before it called it. I do acknowledge that our error messaging, onboarding process and documentation could definitely be better and expect to see more improvements made in general moving forward. You should also know we will be building Auth into Amplify very soon so the general experience of authentication for iOS should improve with the development of the Auth category inside Amplify for iOS. Please check out the project [here](https://github.com/aws-amplify/amplify-ios) and stay tuned for the Auth category when it is starts getting built. Please feel free to close this issue if there are no further issues with the `AWSMobileClient` as it stands today.

**Comment by laurentbourg** [comment]
Thanks @kneekey23 for your help. I am not sure I fully understand the security flaw you are describing, but let's take this offline if needed. Cognito is great but the bottom line is that from a user point of view is the API needs to be intuitive and consistent, the usage pattern we went through is not. I will now close the thread.
