### ISSUE TITLE
'AWSMobileClient-Swift.h' not found with CocoaPods as static libraries 

### ISSUE THREAD

**Issue by lazy-var** [aws-amplify/aws-sdk-ios#2260]
**Describe the bug**
When building a project with Pods as [static libraries](http://blog.cocoapods.org/CocoaPods-1.5.0/) by not including `use_frameworks!` in the `Podfile`, but adding `use_modular_headers!` or `:modular_headers => true` to a single `pod` I get following error:

> 'AWSMobileClient/AWSMobileClient-Swift.h' file not found

**Which AWS service(s) are affected?**
Local AWSMobileClient pod. Not aws services affected.

**Environment(please complete the following information):**
 - SDK Version: pod 'AWSMobileClient', '~> 2.12.2'
 - Dependency Manager: Cocoapods
 - Swift Version : 5.x
 - Target: iOS 13.0
 - Xcode: 11.3.1

** Code related to the issue**
https://github.com/aws-amplify/aws-sdk-ios/blob/b64ed76724f662239f3f5e8df0c40745098626b1/AWSAuthSDK/Sources/AWSMobileClient/Internal/_AWSMobileClient.m#L18

**Possible fix?**
```
-- #import <AWSMobileClient/AWSMobileClient-Swift.h>
++ #import "AWSMobileClient-Swift.h"
```
As `_AWSMobileClient.m` already lives on `AWSMobileClient/`. 
When applying this, project compiles and runs apparently fine.

**Additional context**
I couldn't find a `AWSMobileClient-Swift.h` file inside `AWSMobileClient` directory:

![_AWSMobileCLient m](https://user-images.githubusercontent.com/2856396/73174316-bb3af080-4107-11ea-9db7-d05c1954dfc3.png)

**Related issue**
https://github.com/aws-amplify/aws-sdk-ios/issues/1126

**Comment by wooj2** [comment]
Hi,
Thank you so much for reporting this.

I did some research and found a potential workaround here: https://github.com/CocoaPods/CocoaPods/issues/7594 , and have submitted a PR here: https://github.com/aws-amplify/aws-sdk-ios/pull/2267 .  Please be warned that, I haven't exhaustively tested the implications of compiling each and every library statically, so if/when this PR gets pushed into an official release, please use caution and your best judgement in using this feature.

Thanks again!

**Comment by lazy-var** [comment]
Thank you! I couldn't find that solution.

**Comment by rajuashok** [comment]
I'm still having this issue, but based on this it should be fixed right?

![Screenshot 2020-04-12 20 10 06](https://user-images.githubusercontent.com/2475027/79089091-a8dd5580-7cf9-11ea-8bd1-8cda6f61da61.png)

This is what's in my podfile:

`pod 'AWSMobileClient', '~> 2.13.0'`

I'm running XCode `Version 11.2.1 (11B500)`

**Comment by 4leyam** [comment]
i'm facing the same issue as @rajuashok, is there any way to workaround it?
