### ISSUE TITLE
AWSS3TransferUtility.default() and sAWSS3TransferUtility.3TransferUtility(forKey:) does not restart upload.

### ISSUE THREAD

**Issue by pskow** [aws-amplify/aws-sdk-ios#2263]
**Describe the bug**
For some reason, uploading restarts stopped working. Using `AWSS3TransferUtility.default()` and 
`AWSS3TransferUtility.s3TransferUtility(forKey:)` gives the same result.
**To Reproduce**
1. Start uploading file
2. Quit application entirely
3. Open app
4. See upload started from 0 %

**Which AWS service(s) are affected?**
AWSS3

**Expected behavior**
Upload starts from previous progress.

**Environment(please complete the following information):**
 - SDK Version: 2.12.6
 - Dependency Manager: Cocoapods
 - Swift Version : Swift 5

**Device Information (please complete the following information):**
 - Device: iPhone XS
 - iOS Version: OS 13.3

**Comment by kneekey23** [comment]
hi @pskow, have you tried setting up your solution like the sample app [here](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferUtility-Sample/Swift). Also do you have this in your app delegate to make sure upload can continue when the app moves into the background?
```
func application(_ application: UIApplication, 
                handleEventsForBackgroundURLSession identifier: String, 
                completionHandler: @escaping () -> Void) {
 
     //provide the completionHandler to the TransferUtility to support background transfers.
     AWSS3TransferUtility.interceptApplication(application, 
         handleEventsForBackgroundURLSession: identifier, 
         completionHandler: completionHandler)
 }
```

**Comment by pskow** [comment]
Yes, implementation for upload is almost the same. 
I see in example that `AWSS3TransferUtility.default()` is used.
I tried both as mentioned here -> https://github.com/aws-amplify/aws-sdk-ios/issues/1067

**Comment by kneekey23** [comment]
hi @pskow are you doing a multi-part upload?
