### ISSUE TITLE
Upload file to S3 service 403 ERROR (com.amazonaws.AWSS3TransferUtilityErrorDomain error 2.) Swift iOS

### ISSUE THREAD

**Issue by PashaKharambura** [aws-amplify/aws-sdk-ios#2266]
I listed my problem there. 
https://stackoverflow.com/questions/60004473/upload-file-to-s3-service-403-error-com-amazonaws-awss3transferutilityerrordoma
Is any solutions???

**Comment by kneekey23** [comment]
hi @PashaKharambura is there a reason you are specifying a specific endpoint in your config set up? do you have a custom endpoint are you just trying to hit the general us-east-1 region endpoint?

**Comment by kneekey23** [comment]
I am able to get your exact code working just by changing the one line that is passing in an endpoint to remove it. If you are using custom endpoints then I would need to continue testing but this works if you are not using custom endpoints:
```    
 let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialsProvider)
 AWSServiceManager.default().defaultServiceConfiguration = configuration
```

**Comment by kneekey23** [comment]
also worth noting here that if you did want to pass the endpoint, you need to make sure you are passing the correct endpoint and us-east-1 for s3 has a special region that does not include region as shown below:
```
let configuration = AWSServiceConfiguration(region: .USEast1,endpoint: AWSEndpoint(url: URL(string: "https://s3.amazonaws.com")) , credentialsProvider: credentialsProvider)
```

**Comment by PashaKharambura** [comment]
I have s3 compatible storage. HOST = storage.gpucloud.ru
The support of this storage said that region Doesn't Matter.
android app use this region on that endpoint
Also support gave me AWS accessKey and secretKey.

Im trying to make alamofire put request.
Can maybe you help me and tell the request template? maybe I can do like this. Or another andvice you can give?

**Comment by palpatim** [comment]
@PashaKharambura Our S3 SDK is only intended (and tested) against AWS S3 endpoints. I'm afraid we don't have any insight into how it might perform with other cloud providers, even if they claim compatibility with S3.

> Im trying to make alamofire put request.

In your original question, you mentioned using Transfer Utility, so I'm confused about what you're attempting. If you're not actually using the SDK, but rather directly access to the REST API via Alamofire, I recommend you open a support issue with the cloud provider and troubleshoot it from their end.
