### ISSUE TITLE
Getting uploadSequenceToken nil value

### ISSUE THREAD

**Issue by aliakhtar49** [aws-amplify/aws-sdk-ios#2271]
On first launch I need to get the current sequence token 

```
 func getSessionToken(compltionHandler: @escaping (String?) -> Void) {
        if let describeLogStreamsRequest = AWSLogsDescribeLogStreamsRequest() {
            describeLogStreamsRequest.logGroupName = logGroupName
            describeLogStreamsRequest.logStreamNamePrefix = logStreamName
            
            self.logs.describeLogStreams(describeLogStreamsRequest) { (response, error) in
                compltionHandler(response?.logStreams?.first(where: { $0.logStreamName == self.logStreamName })?.uploadSequenceToken )
            }
        } else {
            compltionHandler(nil)
        }
    }
```

**Getting Response** 

```
<AWSLogsLogStream: 0x60000154f2f0> {
    arn = "arn:aws:logs:us-east-2:673753875031:log-group:ali1new:log-stream:1234";
    creationTime = 1580803691384;
    logStreamName = 1234;
    storedBytes = 0;
}
```

`uploadSequenceToken`  I am getting = nil

**Comment by drochetti** [comment]
Hi @aliakhtar49 

Can you provide more information about your environment? The more details you can provide, the better. I'm looking for:

**Which AWS service(s)/SDK(s) are affected?**

**How did you initialize the client?**

**Environment (please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:
