### ISSUE TITLE
Manually adding dependencies

### ISSUE THREAD

**Issue by XRdeveloper** [aws-amplify/aws-sdk-ios#2278]
**Describe the bug**
When I complete steps that are required for importing frameworks manually in Xcode I start to use them in swift files. Everything works normally when programming, but the problem arise when I want to run my project on either simulator or physical device.

When I try to run project app gets installed but then I get `__abort_with_payload Thread 1: signal SIGABRT`. This is what console print out: 

`dyld: Library not loaded: @rpath/AWSCloudWatch.framework/AWSCloudWatch
  Referenced from: /private/var/containers/Bundle/Application/B5D5E844-9433-4F44-8BBD-6E3717270B4A/aws.app/aws
  Reason: image not found
(lldb) `

**To Reproduce**
1. Import AWS iOS Frameworks to Xcode project manually.
2. Import frameworks to swift file with `import` statement.
3. Run project.
4. See  `Thread 1: signal SIGABRT`.

**Which AWS service(s) are affected?**
Can't specify.

**Expected behavior**
When I run my project I would expecte to run app without any thread errors.

**Screenshots**
![Screenshot 2020-02-07 at 11 59 34](https://user-images.githubusercontent.com/41028060/74024249-b85ebc00-49a1-11ea-9786-48a4a8d197f8.png)

**Environment(please complete the following information):**
 - SDK Version: 2.12.6
 - Dependency Manager: No dependency manager
 - Swift Version : Swift 5

**Device Information (please complete the following information):**
 - Device: Simulator, iPhone X, iPad Pro, iPad mini(5th generation) 
 - iOS Version: iOS 13.3
 - Specific to simulators:

**Additional context**
If I use AWSMobileClient framework in one of my swift files and try to run project on simulator I get swift compiler error:

`/Users/lukacefarin/Desktop/aws/aws/ViewController.swift:10:8: Could not find module 'AWSMobileClient' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7`

**Comment by wooj2** [comment]
Thank you so much for providing such a detailed report.  This seems to be a duplicate issue that was reported here:  https://github.com/aws-amplify/aws-sdk-ios/issues/2274

I will be closing this issue and working towards a solution in the aforementioned issue.

Thanks again!
