### ISSUE TITLE
Cancelling a large file upload doesn't fully allow the associated NSURLSession to become invalidated

### ISSUE THREAD

**Issue by colinhumber** [aws-amplify/aws-sdk-ios#2280]
**Describe the bug**
When uploading a large, multipart upload, only the in-progress session tasks are flagged for cancellation. The parts that are waiting to be uploaded are never cancelled, and as a result the `-[NSURLSession session:didBecomeInvalidWithError:]` is never called.

Due to a unique flow we have in our app in how we vend authentication credentials, each upload requires a separate transfer utility. When cancelling an upload we want to completely clean up any pending tasks and fully remove the registered transfer utility. The transfer utility is only removed when the session has been invalidated in `AWSTransferUtility`. Because the waiting multipart tasks are never cancelled, the `NSURLSession` associated with the transfer utility still has incomplete tasks associated and thus will never be invalidated.

**To Reproduce**
1. Register a new `AWSTransferUtility`
2. Start a large upload (eg. 100MB) that will require the upload to be split in a large number of upload parts
3. Cancel the upload
4. Remove the registered transfer utility

**Which AWS service(s) are affected?**
- AWSS3

**Expected behavior**
- the registered transfer utility should be removed from the registered services after all parts are cleaned up

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.12.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Device Information (please complete the following information):**
 - Device: iPad Pro 11"
 - iOS Version: iOS 13.3
 - Specific to simulators: N/A

**Additional context**
I've tested out a fix by ensuring the upload task's `waitingPartsDictionary` are all cancelled in `AWSTransferUtility`'s `-[NSURLSession session:task:didCompleteWithError:]` when the in-progress tasks are cancelled as well as in `[AWSS3TransferUtilityMultiPartUploadTask cancel]`, thus ensuring any session task associated with the `NSURLSesssion` is marked as completed allowing the session to become fully invalidated.

Want to get some input on this bug before posting a PR.

**Comment by palpatim** [comment]
@colinhumber Thanks for reporting. I have some qualms about registering multiple transfer utilities for each upload--our guidance is typically to have a single transfer utility with a credentials manager that handles authentication on your behalf. However, since I don't know the details of your use case, let's table that discussion for now.

What is clear is that canceling and removing a registered transfer utility should clean up properly, so this is a bug that we'd want to work in the "register a transferUtility, then unregister it" case, including removing parts, canceling in-process background tasks and invalidating any currently-associated NSURLSession (as well as removing the actual TransferUtility instance).

I'm actually troubleshooting an unrelated issue in S3TransferUtility, so it wouldn't be much of a context switch for me to review a PR if you've got one ready.

**Comment by colinhumber** [comment]
@palpatim For sure. I'll make a PR with the details of the fix I put in. I'm not 100% sure if it covers the required cases as it was a bit of a brute force fix just to get things going on my end.

As far as the multiple transfer utilities goes, I completely agree. I'm not a big fan of the setup either, but we couldn't find a better way. Would love some ideas on that, though. Basically, before we upload to S3 we ask our service to generate an access token on our behalf with S3. That token is only valid to upload to a specific folder in a specific bucket. Since we're using static credentials (ie. the previously generated access token), we create a transfer manager for that upload with a credential provider that vends those credentials. Ideally I would be using a single transfer manager. However, since as far as I can tell there's no way to correlate what upload task an instance of `AWSCredentialsProvider` is being used with, I was having troubles correlating the task with the previously generated token.

**Comment by colinhumber** [comment]
I was going to append some additional checks to the `testCancelMultipartUpload` test case to ensure the `.AWSS3TransferUtilityURLSessionDidBecomeInvalid` notification is posted, but I get a ton of build errors when running the tests and I can't find any guidance on getting those setup so I'll just include my initial fixes for now and come back to the tests in the PR if necessary.

**Comment by colinhumber** [comment]
PR at https://github.com/aws-amplify/aws-sdk-ios/pull/2288

**Comment by palpatim** [comment]
Thanks for the PR, @colinhumber. Changes look reasonable to me. I'd like to get some tests on this so if you don't have time just now I'll put it on my list.

**Comment by kneekey23** [comment]
Closing this issue as PR was merged and released.
