### ISSUE TITLE
'Error: notSignedIn(message: "User is not signed in, please sign in to use this API.")' even though logged in with federatedSignIn(). (Facebook)

### ISSUE THREAD

**Issue by Nicolaidam** [aws-amplify/aws-sdk-ios#2291]
**State your question**
I have a AppSync service with integrated cognito as authentication. Right now i have implemented normal cognito-users and I'm able to write/read to the dynamoDB if logged in. However I have a problem when logged in with federatedSignIn(). I am not able to write to the database. Is this possible? How can i do it? 

**Which AWS Services are you utilizing?**
Amplify, Cognito, AppSync
**Provide code snippets (if applicable)**
This is my schema.graphql:
type User @model @auth(rules: [{allow: owner}]) {
  id: ID!
  name: String!
  email: AWSEmail!
}

**Environment(please complete the following information):**
 - SDK Version: 'AWSMobileClient', '~> 2.12.0' and 'AWSAppSync', '~> 3.0.0'
 - Dependency Manager: Cocoapods
 - Swift Version : Swift 4.0

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: iOS 13.1
 - Specific to simulators: Simulator, iPhone 11 pro

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by royjit** [comment]
What is the auth mode setup for your AppSync endpoint? `federatedSignIn` will only federate the social provider through Cognito Identity Pool. So after federated signIn to Cognito Identity pool you can use IAM based auth with AppSync.

**Comment by royjit** [comment]
Closing as there is no response. Please reach out if you are still facing the issue.
