### ISSUE TITLE
Pass clientMetaData to Cognito Triggers

### ISSUE THREAD

**Issue by Skyfallz** [aws-amplify/aws-sdk-ios#2299]
Hi,

on AWSMobileClient, ClientMetadata are not passed to several Cognito API calls : 
- [forgotPassword](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html)
- [confirmForgotPassword](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmForgotPassword.html)
- [signUp](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html)
-  [confirmSignUp](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmSignUp.html)

It seems like @royjit implemented it on confirmSignIn last month in [this PR](https://github.com/aws-amplify/aws-sdk-ios/pull/2209) (thanks for this btw :+1:), maybe it can be adapted for the calls listed above ?

Thanks for your work guys, and let me know if you need more info.

**Comment by kneekey23** [comment]
Closing as this PR was merged in and will be released in the next release.
