### ISSUE TITLE
How can I cast errors from S3, etc.?

### ISSUE THREAD

**Issue by ChrisInspect** [aws-amplify/aws-sdk-ios#2301]
**State your question**
In my App I can cast errors from AWSMobileClient like so

`if let error = error as? AWSMobileClientError {
switch error {
                case .userNotFound( _):
                    //handle error}}`

and so on...
But I found nothing similar for S3,DynamoDB, etc.

There is a class `AWSS3Error` , but when an error occurs, I can't cast it with this class.
Do classes like AWSMobileClientError exists and if, how can I use them?

**Which AWS Services are you utilizing?**
AWSS3
AWSDynamoDB
AWSSES

**Environment(please complete the following information):**
 - SDK Version: [12.7.0]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [5.1]

**Device Information (please complete the following information):**
 - Device: [iPad]
 - iOS Version: [iPadOS 13.3.1]

**Comment by wooj2** [comment]
Hi @ChrisInspect,

Thanks for reaching out to us.  Could you provide some sample code to give us a bit more context into the calls you are attempting to make and the errors you are trying to parse?

Thanks!

**Comment by ChrisInspect** [comment]
Hi @wooj2 ,

```
static func loadImage(bucketName:String,key:String,expression:AWSS3TransferUtilityDownloadExpression,
                               completion: @escaping (_ data:Data?,_ error:Error?)->()){        
        var completionHandler: AWSS3TransferUtilityDownloadCompletionHandlerBlock?
        completionHandler = { (task, URL, data, error) -> Void in
           DispatchQueue.main.async(execute: {
            if task.progress.isFinished{
              completion(data,nil)
            }
            else if let error = error as? AWSS3Error{
              completion(nil,error) //gets never called
            }
           })
        }
        let transferUtility = AWSS3TransferUtility.default()
        transferUtility.downloadData(fromBucket: bucketName,
                                     key: key,
                                     expression: expression,
                                     completionHandler: completionHandler)
        
    }
```

In the example above, the error-case is never called, when an error occurs.
I want to simply cast S3 error with switch-case, like in my example with AWSMobileClient in my first post

**Comment by wooj2** [comment]
Hi @ChrisInspect,

I really appreciate you taking the time to explain your situation and providing such a detailed example.  It really helps us understand our customers and their pain points.
  
That being said, unfortunately I wish I had a better answer for you, but I do not believe that a higher level error interface is available for that call.  If you need to get specific errors you will (unfortunately) have to parse the error code, domain, and user info that is returned in the NSError instance.

I will be optimistically closing this issue, but feel free to re-open if you have other questions regarding this matter.
