### ISSUE TITLE
Navigation Bar for AWSMobileClient sign in 

### ISSUE THREAD

**Issue by FahadOsaimi** [aws-amplify/aws-sdk-ios#2321]
**The Issue**
Navigation Bar for **AWSMobileClient** sign in (**showSignIn**) is not appear in 13.3 and working fine in 12.2 

**Which AWS service(s) are affected?**

`AWSMobileClient.default().showSignIn(navigationController: self.recentNavController
                ) {(userStete, error) in
                                                              if (error == nil){
                                                                  DispatchQueue.main.async {
                                                                    print("user successfully logged in")
                                                                  }
                                                              }
              }`

**Expected behavior**
Navigation Bar  should be visible not blank and Sign In title appear 

**Screenshots**
<img width="431" alt="Screen Shot 2020-02-29 at 6 43 08 PM" src="https://user-images.githubusercontent.com/22099067/75610637-fe7fe900-5b23-11ea-9403-a7974b6e64be.png">
<img width="463" alt="Screen Shot 2020-02-29 at 6 43 49 PM" src="https://user-images.githubusercontent.com/22099067/75610639-02137000-5b24-11ea-9713-c31f03e2a59b.png">

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29] **2.12.7**
 - Dependency Manager: [e.g. Cocoapods, Carthage] **Cocoapods**
 - Swift Version : [e.g. 4.0] **5.0**

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] **iPhone 8 and later** 
 - iOS Version: [e.g. iOS 11.4]  **iOS  13.3**
 - Specific to simulators:

**Comment by lawmicha** [comment]
Hi @FahadOs, thanks for reporting this issue. Unfortunately I was unable to reproduce this.

My pod file
```
platform :ios, '13.0'
AWS_SDK_VERSION = "2.12.7"
...
pod "AWSMobileClient", "~> #{AWS_SDK_VERSION}"
pod "AWSAuthUI", "~> #{AWS_SDK_VERSION}"
pod "AWSUserPoolsSignIn", "~> #{AWS_SDK_VERSION}"
```

![Simulator Screen Shot - iPhone 8 Plus - 2020-03-05 at 09 40 26](https://user-images.githubusercontent.com/1365977/76009051-70aa5200-5ec5-11ea-9904-a527f6850185.png)

Do you see any errors in the console related to the navigation controller? Are you able to reproduce this on a physical device? On other types of Iphone simulators (Iphone 11, X, etc) for 13.3?

**Comment by FahadOs** [comment]
Thank you @lawmicha so much for your reply.

I have not tested yet in a physical device but all iPhone simulators with IOS 13.3 has the same issue 

I have just figure out that once the large titles attribute for navigation bar was set to true the issue will appear :

`           UINavigationBar.appearance().prefersLargeTitles = true
`

My Pod file : 

```
# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
 AWS_SDK_VERSION = "2.12.7"

target 'xxx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hypinder
  pod 'AWSUserPoolsSignIn', "~> #{AWS_SDK_VERSION}"
  pod 'AWSAuthUI', "~> #{AWS_SDK_VERSION}"
  pod 'AWSMobileClient', "~> #{AWS_SDK_VERSION}"
  pod 'AWSGoogleSignIn', '~> 2.12.6'
  pod 'GoogleSignIn'
end
```

**Comment by royjit** [comment]
Hi @FahadOsaimi 
Adding the following code as explained in [here](https://sarunw.com/posts/uinavigationbar-changes-in-ios13/) fixed the issue for me

```
UINavigationBar.appearance().prefersLargeTitles = true
let appearance = UINavigationBarAppearance()
appearance.backgroundColor = UIColor.white
UINavigationBar.appearance().scrollEdgeAppearance = appearance
```

**Comment by FahadOsaimi** [comment]
Thank you @royjit so much , fixed the issue for me too 😊
