### ISSUE TITLE
AWSKinesisVideo, GetMedia operation

### ISSUE THREAD

**Issue by notbenoit** [aws-amplify/aws-sdk-ios#2338]
**Which AWS Services is the feature request for?**
AWSKinesisVideo

**Is your feature request related to a problem? Please describe.**
I'm looking into playing live video feeds. The `AWSKinesisVideo` framework provides the tools to get the `dataEndpoint` (through `getDataEndpoint`). However I can't find the `getMedia` operation that would make use of the `dataEndpoint` to read the stream.

Documentation states :
>Use this endpoint in your application to read from the specified stream (using the <code>GetMedia</code> or <code>GetMediaForFragmentList</code> operations)

**Describe the solution you'd like**
We would like to have an extra function on `AWSKinesisVideo` to call the `getMedia` endpoint and read the stream data.

**Describe alternatives you've considered**
Building and signing the request to the endpoint plus the `getMedia` route through the tools available in the SDK works.

**Additional context**
It looks like these set of APIs are available for `AWSKinesisVideoArchivedMedia`, curious why they would not be available for `AWSKinesisVideo` as well.

**Comment by lawmicha** [comment]
Hi @notbenoit, thanks for letting us know, we'll check in with the Kinesis team on why this method isn't in the SDK and keep you updated.

**Comment by lawmicha** [comment]
I have confirmed with Kinesis team that `GetMedia` API is missing from iOS and Android SDK's. Please use `GetMediaForFragmentList` as the alternative for getting back the video in non-real time. I will mark this as a feature request for the service team.

**Comment by pathfinder1989** [comment]
Could you provide a demo for how to use AWSKinesisVideoArchivedMedia

**Comment by pathfinder1989** [comment]
@lawmicha Could you provide a demo for how to use AWSKinesisVideoArchivedMedia
