### ISSUE TITLE
awsconfiguration.json file manually added 

### ISSUE THREAD

**Issue by saleem359** [aws-amplify/aws-sdk-ios#2340]
Hi , I set up my user on my local machine and installed all the dependencies required for the app in order to use authentication . My android mate told me instead of using amplify init use manual configuration just to create awsconfiguration.json file add poolID and client access id plus client secret id and that's it put that file into Xcode it will work , you do not need to use amplify init. So please tell me what are the precise step of it and here is the error when I created file and added into my project. 

** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `awsconfiguration.json` or `Info.plist` before using this method.'

**Comment by lawmicha** [comment]
hi @saleem359, can you try setting things up with the Amplify CLI, ie.

1. `amplify init`
2. `amplify add auth`

and once it has generated your awsconfiguration.json file, you can use that as a template for replacing its values with your own. It should look like this: https://aws-amplify.github.io/docs/ios/authentication#manual-setup

Also for the file to be picked up from your project, you have to make sure it is added to the bundle. To do this, open the finder, locate awsconfiguration.json, drag it into your xcode workspace, and make sure the "Copy contents" if checked off. You can make sure from the Project->Build Phases -> Copy Bundle Resources, that the awsconfiguration file is listed there. If not, you can add it in from there as well.

**Comment by royjit** [comment]
Closing as there is no response. Feel free to reach out if you are still facing any issue.

**Comment by tahoeWolverine** [comment]
The above link regarding properly configuring existing AWS resources doesn't seem to work anymore (lots of Amplify documentation links seem to have the same fate).

https://aws-amplify.github.io/docs/ios/authentication#manual-setup

If anyone has any details on current best practices, please share!

**Comment by umerasif** [comment]
Updated link 👇

https://docs.amplify.aws/sdk/auth/getting-started/q/platform/ios#manual-setup
