### ISSUE TITLE
Right after user sign in, authenticated role is not assumed to allow API Client (api gateway sdk) to API calls.

### ISSUE THREAD

**Issue by noelle007** [aws-amplify/aws-sdk-ios#2342]
**State your question**

Our sign in flow goes: 
user landing on app grant an unauthenticated role with limited api calls  
-> 
user sign in, either through cognito user pool or facebook 
->  
user sign in federated, in the case of using cognito user pool there is no need as far as I understand 
-> 
user status return as .signedIn 
-> 
app makes api calls to retrieve user data with the newly assumed authenticated role. 

The problem I'm see is the api call made after sign in fails with error message stating unauthenticated role is not authorized to make this call. User has signed in successfully with correct user name and password. And I can confirm by printing out the user's identity id after sign in. 

1 out of 5 times the same api call goes through successfully by reloading app.

**Which AWS Services are you utilizing?**
AWSCore
AWSMobileClient
AWSCognitoIdentityProviderASF
FBSDKCoreKit
API Client SDK generated from APIGateway

**Provide code snippets (if applicable)**

Very similar to https://aws-amplify.github.io/docs/ios/authentication

**Environment(please complete the following information):**
Swift 5
iOS 13
Version 11.2.1

**Device Information (please complete the following information):**
Simulator

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by lawmicha** [comment]
Hi @noelle007, thanks for reporting this issue. 

What is the error message you are getting for "unauthenticated role is not authorized to make this call", any additional context in the response you can paste? 

What are some relevant code snippnets or methods you are using? are you using federated sign in with the cognito identity pool or using cognito hosted ui for sign in with facebook? (what is the call pattern/method call?)

Can you provide the relevant podfile pods and their version?

**Comment by noelle007** [comment]
@lawmicha  Thanks for the prompt response:

Here is our podfile:
```
platform :ios, '13.0'
use_frameworks!
target : MYPROJECTNAME do
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSS3'
    pod 'AWSAPIGateway'
    pod 'AWSMobileClient'
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
end
```



Here is what I have in `AppDelegate.swift`
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool { 
    let identityPoolId = "us-west-2:XXXXXXX"

    let credentialsProvider = AWSCognitoCredentialsProvider(
        regionType: .USWest2,
        identityPoolId: identityPoolId)

    let configuration = AWSServiceConfiguration(
        region: .USWest2,
        credentialsProvider: credentialsProvider)

    AWSServiceManager.default().defaultServiceConfiguration = configuration

    let _ = AWSMobileClient.init(regionType: .USWest2 , identityPoolId: identityPoolId)
            
    AWSMobileClient.default().initialize { (userState, error) in
        if let userState = userState {
            print("UserState: \(userState.rawValue)")
            
        } else if let error = error {
            print("error: \(error.localizedDescription)")
        }
    }
    
    ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
    return true
}
```
The user flow:
```
func login(userName: String, userPass: String) {

    let validation = ["loginEmail": userName, "loginPass": userPass]
    AWSMobileClient.default().signIn(username: userName, password: userPass, validationData: validation) { (signInResult, error) in
        if let error = error  {
            print("User login error \(error.localizedDescription)")
        } else if let signInResult = signInResult {
            switch (signInResult.signInState) {
            case .signedIn:
                print("User is signed in.")
                AWSMobileClient.default().getIdentityId().continueWith{(task: AWSTask) -> AnyObject? in
                    if let error = task.error {
                        print("get identity id error: \(error)")
                    } else {
                        let userIdentityId = task.result
                        let userId = userIdentityId!.components(separatedBy: ":")[1]
                        print(userIdentityId ?? "no user id")
                        signInPost(userId: userId, onComplete: completion, onError: onError)
                    }
                    return nil
                }
                
            default:
                print("Sign In needs info which is not yet supported.")
            }
        }
    }
}


func loginFacebookPressed(_ sender: UIButton) {
    
    let loginManager = LoginManager()
    loginManager.logIn(permissions: ["public_profile"], from: self) { (result, error) in
        if let error = error {
            print("Failed to login: \(error.localizedDescription)")
            return
        }
        guard let accessToken = AccessToken.current else {
            print("Failed to get access token")
            return
        }
        
        loginFederated(token: accessToken.tokenString, onComplete: {(user) in
            //handle next step
            print(user)
        }, onError: {
            print("login Error")
        })
    }
}

func loginFederated(token: String, completion: @escaping (_: User) -> Void, onError: @escaping () -> Void) {
    AWSMobileClient.default().federatedSignIn(providerName: IdentityProvider.facebook.rawValue, token: token) { (userState, error) in
        if let error = error  {
            print("\(error.localizedDescription)")
        } else if let userState = userState {
            switch (userState) {
            case .signedIn:
                AWSMobileClient.default().getIdentityId().continueWith{(task: AWSTask) -> AnyObject? in
                    if let error = task.error {
                        print("get identity id error: \(error)")
                    } else {
                        let userIdentityId = task.result
                        let userId = userIdentityId!.components(separatedBy: ":")[1]
                        signInPost(userId: userId, onComplete: completion, onError: onError)
                    }
                    return nil
                }
            default:
                print("Federated Sign In needs info which is not supported.")
            }
        }

    }
}

func signInPost(userId: String, onComplete: @escaping (_:User) -> Void, onError: @escaping () -> Void) {

    let apiClient = APIGATEWAYCLIENT.default()
    apiClient.userUidLoginPost(uid: userId).continueWith{(task: AWSTask) -> AnyObject? in
        if let error = task.error {
             print("user sign in post api error: \(error)")
             //handle error
             onError()
         } else {
             print("sign in post complete.")
             // go on to  next step
             onComplete
         }
         return nil
     }
}
```
There isn't any error until the line `user sign in post api error`
Here is an example when signing in using cognito user pool. 
```
user sign in post api error: Error Domain=com.amazonaws.AWSAPIGatewayErrorDomain Code=1 "(null)" UserInfo={HTTPHeaderFields=<CFBasicHash 0x6000008cce00 [0x7fff80615350]>{type = immutable dict, count = 10,
entries =>
	0 : x-cache = <CFString 0x60000123b090 [0x7fff80615350]>{contents = "Error from cloudfront"}
	1 : Content-Type = <CFString 0x60000123a9d0 [0x7fff80615350]>{contents = "application/json"}
	2 : x-amzn-errortype = <CFString 0x60000123b030 [0x7fff80615350]>{contents = "AccessDeniedException"}
	3 : x-amzn-requestid = <CFString 0x60000072a940 [0x7fff80615350]>{contents = "XXXXXXX"}
	4 : Via = <CFString 0x60000392f720 [0x7fff80615350]>{contents = "1.1 xxxxxxx.cloudfront.net (CloudFront)"}
	5 : x-amz-apigw-id = <CFString 0x60000123b060 [0x7fff80615350]>{contents = "I9NNAFobvHcFoZg="}
	6 : Date = <CFString 0x60000123b000 [0x7fff80615350]>{contents = "Fri, 06 Mar 2020 07:02:30 GMT"}
	7 : x-amz-cf-pop = SFO5-C3
	10 : Content-Length = 294
	11 : x-amz-cf-id = <CFString 0x600003ea5360 [0x7fff80615350]>{contents = "Xxxxxxxxxxxxxxx=="}
}
, HTTPBody={
    Message = "User: arn:aws:sts::<accountID>:assumed-role/<THE UNAUTHENTICATED ROLE>/CognitoIdentityCredentials is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:us-west-2:********2056:XXXXXX/prod/POST/user/<USER IDENTITY ID>/login";
}}
**THE USER IDENTITY ID here is a valid authenticated user. The api gateway user/<uid>/login (userUidLoginPost) endpoint requires the authenticated role which the user here should be assumed after successful sign in.** 
```
We have similar flow with JS SDKs on our web app. We never have this problem. 

Thanks for looking into this!

**Comment by kneekey23** [comment]
hi @noelle007 is there a reason you are using both the low level SDK AWSCognitoCredentialsProvider and AWSMobileClient, the higher level SDK? They are not intended to be used together. Just to clarify a bit here about Cognito. Cognito has two services available: User Pools and Identity Pools, both of which offer federated authentication. User Pools is used for authentication (think save your users in a db) and Identity Pools is used for authorization (providing temp AWS credentials with permissions defined by IAM roles to your user so they can make calls to your AWS account).  I am assuming you are trying to use them together? The only way you can do that is by using HostedUI with the AWSMobileClient.  Can you clarify here that this is what you are intending?

**Comment by noelle007** [comment]
@kneekey23  thanks for looking into this. 

re : is there a reason you are using both the low level SDK AWSCognitoCredentialsProvider and AWSMobileClient, the higher level SDK? 

Hmm, there is no reason in particular. We have the same setup on web but with Cognito js SDK (implemented before Amplify) . I was assuming it is also needed for iOS.

Yes, we are using User Pools for authentication and Identity Pools for authoring credentials to make API calls. But we are not using the HostedUI.  I can try changing our flow to HostedUI. 

Will update back. Thanks!

**Comment by noelle007** [comment]
@kneekey23  

Tried using HostedUI and confirmed it worked as expected. Thanks for your help with this!!
I do have a question: How do I detect whether a user is signing in vs signing up? same goes signing in/up through User Pool vs Federated Providers?

**Comment by palpatim** [comment]
@noelle007 Glad HostedUI worked for you! 

Regarding your other question: I don't believe the responses from HostedUI allow you to determine whether a user has signed up vs. signed in; similarly, I don't believe there is a way to distinguish in the response what method they used to sign in.

Depending on your use case, you may be able to get some of those answers using [Lambda Triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html), which can hook into your User Pools' auth flows at various points and allow you to inspect and take action on them.

Hope this helps.

**Comment by noelle007** [comment]
@palpatim Thank you for getting back to my question. 

I will look into Lambda Triggers to separate sign up from sign in actions then.

**Comment by noelle007** [comment]
We notice the amplify doc has changed. Are we not supposed to use to use AWSMobileClient going forward? By the way, AWSMobileClient doesn't work really well. The session token only lasts about an hour. User then has to sign in again. I thought AWSMobileClient was supposed to take care the session renewal automatically.  The automatic session renewal works sometimes, but most of the times it doesn't. It is really bad for user experience. 

Our user case is very simple. We use Cognito user pool for user authentication and Cognito federated identity for aws credential to make API calls via API Gateway. API Gateway is triggering lambda functions. Our user pools and federated pools were created way back when Cognito user pool was NOT handling federation. 

What should I use? 

Thanks for your help!

**Comment by gevartosky** [comment]
I just hit the exact same issue with the same error message 
AWSAPIGatewayErrorDomain AccessDeniedException.

The reason we are using AWSMobileClient in conjunction with Amplify Cognito is because using Amplify.API.post was insisting on trying to authenticate using cognito when the endpoint specifically used AWS_IAM. I read some issues and it looked like an SDK would fix it but we were still getting the unauthorized from Amplify. We moved back to AWSMobileClient and it worked initially, but now we started seeing this error.

**Comment by noelle007** [comment]
@gevartosky I found a solution after reading through many many bug threads. Also have been using the newer version of Amplify frameworks for a recently app. I followed their doc. It works pretty well so far.

**Comment by gevartosky** [comment]
Oh thats great to hear @noelle007.
Would you mind sharing what was the solution and the docs you have followed?

**Comment by noelle007** [comment]
@gevartosky 

so I have this block inside `didFinishLaunchingWithOptions` in `AppDelegate` before `return true`

```
       let identityPoolId = "us-east-1:XXXXXXXX"
        
        let _ = AWSMobileClient.init(regionType: .USEast1 , identityPoolId: identityPoolId)
        
        let serviceConfiguration = AWSServiceConfiguration(region: AWSRegionType.USEast1,
                      credentialsProvider: AWSMobileClient.default())
        
        AWSServiceManager.default().defaultServiceConfiguration = serviceConfiguration

        AWSMobileClient.default().initialize { (userState, error) in
            
            if let userState = userState {
                switch (userState) {
                    case .guest:
                        LogManager.Log(3, "user is in guest mode")

                    case .signedOut:
                        LogManager.Log(3, "user signed out")

                    case .signedIn:
                        LogManager.Log(3, "user signed in")

                        // I need the following for another handling after signing in, you might not need that.
                        AWSMobileClient.default().getAWSCredentials { (credentials, error) in
                            if let error = error {
                                LogManager.Log(1, "Error getting token \(error.localizedDescription)")
                            } else {
                                self.getLoggedInUserAttribute(onComplete: {
                                    AWSMobileClient.default().getIdentityId().continueWith{(task: AWSTask) -> AnyObject? in
                                        if let error = task.error {
                                            LogManager.Log(1, "get identity id error: \(error)")
                                            
                                        } else {
                                            LogManager.Log(2, "login complete")
                                        }
                                    return nil
                                    }
                                })
                                
                            }
                        }
                        
    
                    case .signedOutUserPoolsTokenInvalid:
                        LogManager.Log(3, "need to login again.")
                        

                    case .signedOutFederatedTokensInvalid:
                        LogManager.Log(3, "user logged in via federation, but currently needs new tokens")
                        
                    default:
                        LogManager.Log(1, "unsupported, user status unknown")
                        

                }

            } else if let error = error {
                LogManager.Log(1, "error: \(error.localizedDescription)")
            }
        }
```
(There are other functions wherever I have LogManager. I didn't include them here.)

I have these in imports:
```
import Amplify
import AmplifyPlugins
import AWSPluginsCore
import AWSMobileClient
```
some might not be needed for above block but for other AWS related stuff like AWSAPIGatewayClient (which I didn't include here). 

I tried to find the doc I followed but it has been a while I can't really locate the doc any more. Hope that helps
