### ISSUE TITLE
AWS iOS SDK samples replace cocoapods source

### ISSUE THREAD

**Issue by phillipsk** [aws-amplify/aws-sdk-ios#2350]
**Describe the bug**

Remove the sources line 'source 'https://github.com/CocoaPods/Specs.git''
on S3TransferUtility-Sample/Swift/Podfile
See https://stackoverflow.com/q/23755974/3128069 
Or replace with source 'https://cdn.cocoapods.org/' Although I believe the modern Podfile no longer has a sources link

**To Reproduce**
1. Clone repo https://github.com/awslabs/aws-sdk-ios-samples.git
2. pod install S3TransferUtility-Sample/Swift/Podfile

**Comment by kneekey23** [comment]
PR submitted to samples repo here: https://github.com/awslabs/aws-sdk-ios-samples/pull/343
