### ISSUE TITLE
Remember devices leads to Invalid Refresh Token (using AWSMobileClient)

### ISSUE THREAD

**Issue by Nikooos** [aws-amplify/aws-sdk-ios#2354]
**Describe the bug**
When 'remember devices' is set to 'always' in my Amazon Cognito user pool, I receive an 'Invalid Refresh Token'-response when opening the app an hour later. 
That means I'm logged out at that point and I need to log in again. That's not the experience I want to give my users.

I'm using the Amazon best practice AWSMobileClient in this situation.

**To Reproduce**
1. Enable 'remember devices' in the Amazon Cognito user pool
2. Log on in the app that uses that user pool
3. Bring the app to the background or close it for > 1 hour
4. Open the app and see that you're not logged on anymore and received the following response:

```
2020-03-10 13:44:27:373 MyApp[420:21274] Response headers:
{
    "Content-Length" = 70;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Tue, 10 Mar 2020 12:44:27 GMT";
    "x-amzn-errormessage" = "Invalid Refresh Token.";
    "x-amzn-errortype" = "NotAuthorizedException:";
    "x-amzn-requestid" = "f757ba79-b09f-4acc-b66a-20c8cff4c6e3";
}
2020-03-10 13:44:27:373 MyApp[420:21274] Response body:
{"__type":"NotAuthorizedException","message":"Invalid Refresh Token."}
```

**Which AWS service(s) are affected?**
Cognito

**Expected behavior**
I expect to still be logged on.

**Environment(please complete the following information):**
 - SDK Version: ~> 2.11.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: All tested from iPhone SE up to iPhone 11 
 - iOS Version: Various
 - Specific to simulators: NO

**Additional context**
This problem also occurs on our Android implementation.

**Comment by kneekey23** [comment]
hi @Nikooos have you tried updating to the latest version of the SDK 2.13.0? I have seen this issue with prior versions of our SDK. I think #2033 and #2356 are both related here. All receiving invalid refresh tokens one way or another but somehow #2033 was resolved by an update to the latest version.

**Comment by BillBunting** [comment]
@Nikooos Were you able to resolve this issue? or, did you set 'remember devices' is set to 'No' as a workaround? Did updating to the latest version resolve the problem?
