### ISSUE TITLE
Use API Gateway WebSockets with IAM authentication

### ISSUE THREAD

**Issue by ChrisInspect** [aws-amplify/aws-sdk-ios#2355]
**State your question**
I want to implement API Gateway Websockets in my iOS-application. This works fine without authorization and third-party Websocketlibrary ([Starscream](https://github.com/daltoniam/Starscream)), but I need to authenticate my Websocket. As soon as I activate IAM-Authorization in my Websocket API, of course I can't connect anymore. My users are authenticated with Cogntio _inside_ my application.
How can I achieve this? If I am right, there aren't Swift methods for AWS Websockets?

**Which AWS Services are you utilizing?**
API Gateway Websockets
IAM

**Environment(please complete the following information):**
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Comment by kneekey23** [comment]
hi @ChrisInspect can you please provide a code snippet or code sample or how you making the calls?

**Comment by ChrisInspect** [comment]
Hi @kneekey23 ,
I just call the websocket with standard request and some custom header for lambda processing.

```
let socket: WebSocket

init() {
        let url = URL(string: "wss://xxxxxxxxxx.execute-api.eu-central-1.amazonaws.com/test")!
        var request = URLRequest(url: url)
        request.setValue("TableName", forHTTPHeaderField: "TableName")
        socket = WebSocket(request: request, certPinner: FoundationSecurity(allowSelfSigned: true))
        socket.delegate = self
    }
    
func connect(){
        socket.connect()
    }

// and so on....
```

As I mentioned this works and I receive successfully my messages, if authentication in API Gateway is disabled. When authentication is enabled, I guess I have to somehow pass my tokens from AWSMobileClient to the Websocket. Is this right and how can I achieve this?

I would love to have methods directly from AWS for Websocket like `AWSApiGateway.default().connectToSocket(socketUrl:"wss://xxxxxxxxxx.execute-api.eu-central-1.amazonaws.com/test")` which handles all the authentication. Another advantage is, that I wouldn't be dependent to a third party library anymore.
With Amplify and IoT we can see that there exists some kind of Websocket implementation for iOS SDK already. Switching to for example IoT isn't an option for us. We definitely need AWS Api Gateway Websockets.

**Comment by stevenkramer** [comment]
@ChrisInspect I solved this by adding the id token I get from Cognito to the request for opening the websocket. Then I verify the token in the lambda function that handles the $connect route. Looking good so far.

**Comment by rainypixels** [comment]
Hi @kneekey23 Any word on this? From what I can tell, there's no API equivalent to `AWSApiGateway.default().connectToSocket(socketUrl:"wss://xxxxxxxxxx.execute-api.eu-central-1.amazonaws.com/test")`. Is there any other way to sign a websocket connection using an `AWSCognitoCredentialsProvider` instance? I attempted to use the `AWSSignatureV4Signer.generateQueryStringForSignatureV4(:_)` method, but no luck.

**Comment by lawmicha** [comment]
Hi @ChrisInspect,

I don't believe the SDK provides a method to sign the request and connect to the websocket, so you will have to roll your own, I got this working using Foundation Websocket and the `AWSSignatureV4Signer`.

I have a Websocket API from API Gateway, with auth type set to IAM, Cognito Identity Pool with unauth access, and unauth access to connect to the API Gateway.

**Signing the request**
```swift
import AWSCore

func signRequest() -> URL? {
    let credentialsProvider = AWSCognitoCredentialsProvider(regionType: region,
                                                            identityPoolId: identityPool)
    let endpoint = AWSEndpoint(region: region, service: .APIGateway, url: url)
    let keyPath = String(url.path.dropFirst())
    let requestHeaders: [String: String] = ["host": endpoint!.hostName]
    let task = AWSSignatureV4Signer
                .generateQueryStringForSignatureV4(
                    withCredentialProvider: credentialsProvider,
                    httpMethod: .GET,
                    expireDuration: 60,
                    endpoint: endpoint!,
                    keyPath: keyPath,
                    requestHeaders: requestHeaders,
                    requestParameters: .none,
                    signBody: true)
    task.waitUntilFinished()
    if let error = task.error as NSError? {
        print("Error occurred: \(error)")
    }
    if let result = task.result {
        return result as URL
    }
    return nil
}
```
** Websocket **
```swift
let webSocketDelegate: WebSocket
let session: URLSession
var webSocketTask: URLSessionWebSocketTask?
init() {
      self.webSocketDelegate = WebSocket()
      self.session = URLSession(configuration: .default, delegate: webSocketDelegate, delegateQueue: OperationQueue())
}
func connectWithIAMSigning() {
        if let url = signRequest() {
            webSocketTask = session.webSocketTask(with: url)
            webSocketTask?.resume()
        } else {
            print("Could not sign URL")
        }
    }
```

This example took a bit to get going, so if you've looking for the rest of the details, I've documented my experience over in this [sample repo](https://github.com/lawmicha/apiWebsocket) and [gist](https://gist.github.com/lawmicha/6e51bb9c041ac792ce195c28095e09c4)

**Comment by lawmicha** [comment]
> @ChrisInspect I solved this by adding the id token I get from Cognito to the request for opening the websocket. Then I verify the token in the lambda function that handles the $connect route. Looking good so far.

Thanks for sharing this @ChrisInspect. I think it would be better to use token auth over IAM signing but I haven't tried this myself, it should be along the lines of
- Adding new Cognito UserPool Authorizer in the Websocket API Gateway
- Updating the auth type of the `$connect` route to use the new Authorizer
- In the App, sign in with AWSMobileClient, and retrieve the `idToken`
- Add the `idToken` to the authorization header in the request
- Connecting to the websocket with the request

If you have any code snippet to share, that would be great, ie. how did you retrieve the token and add it to your websocket connection request? How did you process the token in the lambda?

**Comment by stevenkramer** [comment]
@lawmicha my approach is similar (the last three steps seem to be identical), except that I validate the token with a lambda instead of going through Cognito - which I didn't know was even possible. The lambda code validates the token's validity date/issuer/etc using some common libraries.

**Comment by lawmicha** [comment]
Thanks for the reply @stevenkramer. That makes sense, i'm guessing you are using some Cognito APIs to validate the token. As for the original problem, please see above comment @ChrisInspect https://github.com/aws-amplify/aws-sdk-ios/issues/2355#issuecomment-770502587
