### ISSUE TITLE
How to test .signedOutUserPoolsTokenInvalid event

### ISSUE THREAD

**Issue by dillonsvincent** [aws-amplify/aws-sdk-ios#2356]
**State your question**
I've had a couple users report them being randomly logged out of our app. I put logging in place to see if it was caused by .signedOutUserPoolsTokenInvalid event, and it was. Now I have a fix in place where I catch that event and sign them back in. I'm wondering if there is a good way to actually force test the invalid token event to see if my logic is handling the state correctly. 

One way I've tested the state was by substituting the signedOutUserPoolsTokenInvalid for the sign out event. I'd feel more comfortable to test the actual flow.

**Which AWS Services are you utilizing?**
AWSMobileClient SDK iOS
AWS Cognito User Pool

**Provide code snippets (if applicable)**

 ```
AWSMobileClient.default().addUserStateListener(self) { (userState, info) in
            switch (userState) {
            case .signedIn:
                if let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "keyxx") {
                    print("transferUtility on signin found");
                }else{
                    let configuration = AWSServiceConfiguration(region: .USWest2, credentialsProvider: AWSMobileClient.default().getCredentialsProvider())
                    
                    //Setup the transfer utility configuration
                    let tuConf = AWSS3TransferUtilityConfiguration()
                    tuConf.retryLimit = 5
                    
                    //Register a transfer utility object
                    AWSS3TransferUtility.register(with: configuration!, transferUtilityConfiguration: tuConf, forKey: "keyxx") { error in
                        let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "keyxx")
                        print("transferUtility created");
                    }
                }
                
            case .signedOutUserPoolsTokenInvalid:
                print("User Token Invalid.")
                Analytics.logEvent(AnalyticsEventSelectContent, parameters: [
                  AnalyticsParameterItemID: "id-token-invalid",
                  AnalyticsParameterItemName: "token-invalid"
                ]);
                MyAuth.SignIn() { success in
                    if !success {
                        Analytics.logEvent(AnalyticsEventSelectContent, parameters: [
                          AnalyticsParameterItemID: "id-invalid-refresh-fail",
                          AnalyticsParameterItemName: "invalid-refresh-fail"
                        ]);
                    }
                }
                
            default:
                print("User Auth State Change: \(userState)")
            }
        }
```

**Environment(please complete the following information):**
 - SDK Version:  pod 'AWSMobileClient', '~> 2.12.0'
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: All
 - iOS Version: 11

**Comment by kneekey23** [comment]
hi @dillonsvincent have you tried updating to the latest version of the SDK 2.13.0? I have seen this issue with prior versions of our SDK. I think #2033 and #2354 are both related here. All receiving invalid refresh tokens one way or another but somehow #2033 was resolved by an update to the latest version.

**Comment by dillonsvincent** [comment]
Thank you for the references, I'll update now and make sure to keep monitoring the invalid token event
