### ISSUE TITLE
AWSMobile client hosted UI and federatedSignIn is not creating user in user pool

### ISSUE THREAD

**Issue by Procurares** [aws-amplify/aws-sdk-ios#2358]
**Describe the bug**
New User is not created inside User Pool using neither **AWSMobileClient.default().federatedSignIn** method nor **AWSMobileClient.default().showSignIn**

**To Reproduce**
I'm having following autogenerated awsconfiguration.json
```json
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "eu-central-1:<some_id>",
                "Region": "eu-central-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "eu-central-1_<some_id>",
            "AppClientId": "<some_client_id>",
            "AppClientSecret": "<some_client_secret>",
            "Region": "eu-central-1"
        }
    },
    "GoogleSignIn": {
        "Permissions": "email,profile,openid",
        "ClientId-WebApp": "<some_id>.apps.googleusercontent.com",
        "ClientId-iOS": "<some_id>.apps.googleusercontent.com"
    },
    "FacebookSignIn": {
        "AppId": "<some_app_id>",
        "Permissions": "public_profile"
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}

```

After successfully completing either Facebook or Google sign in (using hosted ui, i'm having both Facebook and Google buttons on it) i'm having following result:
```swift
AWSMobileClient.default().showSignIn(navigationController: self.navigationController!) { [weak self] state, error in
    NSLog("State is \(state)") //Here the state is .signedIn
    NSLog("Error is \(error)") //Error is nil
    self?.getToken()
}
```

When i check the user pool, no user is created. 
When i'm trying to get the token i'm having following:

```swift
func getToken() {
        AWSMobileClient.default().getTokens { tokens, error in
            if let error = error {
                NSLog("Error getting token \(error)") //Error is - notSignedIn(message: "User is not signed in, please sign in to use this API.") 
            } else if let tokens = tokens, let token = tokens.idToken?.tokenString {
                NSLog("The token is: \(token)")
            } else {
                fatalError("Unhandled getToken state")
            }
        }
    }
```

Same applied for federated sign in.
First i'm login into Facebook using the Facebook button. After making a federated sign in call using received token string.

```swift
    func loginButton(_ loginButton: FBLoginButton, didCompleteWith result: LoginManagerLoginResult?, error: Error?) {
        if let token = AccessToken.current?.tokenString {
            federatedSignIn(token: token)
        }
    }

    func federatedSignIn(token: String) {
       AWSMobileClient.default().federatedSignIn(providerName: IdentityProvider.facebook.rawValue, token: token) { state, error in
            if let state = state {
                switch state {
                case .signedIn:
                    NSLog("AWSMobileClient logged in .signedIn:") // This is the proper case
                default:
                    break
                }
            } else if let error = error as? AWSMobileClientError {
                NSLog("AWSMObileClientError \(error)")
            }
        }
    }
```

After calling above **getToken** method, i'm getting exact same result as after the hosted ui sign in.

**Which AWS service(s) are affected?**

AWSMobileClient
AWSCognito

**Expected behavior**
After making either hostedUI sign in or federatedSignIn a new User must be created inside the User Pool, and i can receive the proper token which i can use to make an Authorized REST API calls.

**Environment(please complete the following information):**
 - Libraries: 
    AWSAuthCore (2.13.0)
    AWSAuthUI (2.13.0)
    AWSCognitoIdentityProvider (2.13.0)
    AWSFacebookSignIn (2.13.0)
    AWSGoogleSignIn (2.13.0)
    AWSUserPoolsSignIn (2.13.0)
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone X
 - iOS Version: iOS 13.3.1

**Comment by royjit** [comment]
Hi @Procurares 

Sorry for the confusion.  If you would like to create a user in `Cognito User Pool`  while using social provider log in, you have to use hosted UI. The one you used above is `DropInUI` which is explained [here](https://aws-amplify.github.io/docs/ios/authentication#drop-in-auth). DropInUI uses  `AWSMobileClient.default().federatedSignIn` internally.

To use hosted UI follow the steps given [here](https://aws-amplify.github.io/docs/ios/authentication#using-hosted-ui-for-authentication).  After going through the steps to enable hosted UI, you can show the signIn ui like this:

```
AWSMobileClient.default().showSignIn(navigationController: navController,
                                                 hostedUIOptions: HostedUIOptions()) { [weak self](userState, error) in
    if let userState = userState {
        print("Status: \(userState.rawValue)")
    }
}



```
