### ISSUE TITLE
Unable to define custom device model name on Demographic event properties

### ISSUE THREAD

**Issue by ruirodrigues-eyenov** [aws-amplify/aws-sdk-ios#2360]
**Describe the bug**
Unable to define custom device model name on Demographic event properties.
Custom defined Demographics properties are being overridden when sending the events properties with the default values.
Currently the "Model" under "Demographic" is being defined using UIDevice.current.model and there is no way to send a more device specific device name. 

**To Reproduce**
1. Setup debug logging:
```
AWSDDLog.sharedInstance.logLevel = .info
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```
2. Create a pinpoint object:
```
pinpoint = AWSPinpoint(configuration:pinpointConfig)
```
3. Set custom device model:
```
let profile = pinpoint.targetingClient.currentEndpointProfile()
profile.demographic?.model = "my_custom_device_model_name"
pinpoint.targetingClient.update(profile)
```
After updating the targeting client you can see on the console 
```
"Model" : "my_custom_device_model_name"
```
4. Sent an event and the `"Model"` property was reverted to the default value.

The Demographics properties are being overridden for all events. Check [this change](https://github.com/aws-amplify/aws-sdk-ios/commit/fb9507264ed30cf1ade49a3b6cff2d85fc77a6c0#diff-0a72197a6c9d6c2193826a779b94a9edR110).

**Which AWS service(s) are affected?**
AWSPinpoint on iOS SDK

**Expected behavior**
Custom Demographic properties can be set without being overridden with default values.

**Environment(please complete the following information):**
 - AWSPinpoint SDL version: 2.10.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Device: iPhone, Simulator
 - iOS Version: iOS 13
 - Specific to simulators: no

**Comment by lawmicha** [comment]
Hi @ruirodrigues-eyenov, currently Pinpoint SDK will automatically create the demographics object for the EndpointProfile with many fields. This gets updated frequently to make sure all of the fields are up to date. I can see that when I set a breakpoint on this line: https://github.com/aws-amplify/aws-sdk-ios/blob/efe22fbf0a60ca0875706c02f1a0944651566f93/AWSPinpoint/AWSPinpointEndpointProfile.m#L377

and then bring the app to background, wait 5 seconds for the session to end, and bring the app back to the foreground, it will start a new session and break to this part of the code again, which is one way that could be overwriting your custom model field.
The model value is automatically populated for the app with a value of "iPhone", "iPod touch", etc. 

If you would like some custom fields on the endpoint profile, can you use `addAttribute` instead?

https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSPinpoint/AWSPinpointEndpointProfile.m#L171

**Comment by ruirodrigues-eyenov** [comment]
Thanks.
Yes, `addAttribute` was the workaround that I used.

Just to clarify `demographics` is not being reset to its defaults after app goes to background. It is being reset on the next `submitEvents` call, on every `submitEvents` call.

**Comment by wooj2** [comment]
@ruirodrigues-eyenov 

Thanks for getting back to us, and glad you found a workaround!  I will be optimistically closing this issue, but feel free to re-open if you have any additional questions about this topic.

Thanks!

**Comment by morfeelright** [comment]
Hi,

I have a similar issue with the optout parameter.
I try to set it to NONE and nothing changes (it stays "ALL").
This way I can't send push notifications.
Can you help?

This is the code I'm using:
`if let targetingClient = pinpoint?.targetingClient {
                let endpoint = targetingClient.currentEndpointProfile()
                endpoint.optOut = "NONE"
                // Update the endpoint with the targeting client
                targetingClient.update(endpoint)
                let endpointId = targetingClient.currentEndpointProfile()
                print("Updated custom attributes for endpoint: \(endpointId)")
            }`
