### ISSUE TITLE
AWSS3 is crashing due to QOS not defined in iOS13

### ISSUE THREAD

**Issue by Zerocool27** [aws-amplify/aws-sdk-ios#2361]
Description:
The crash is captured on firebase and it is hard to reproduce on device

**To Reproduce**
#6. Crashed: NSOperationQueue 0x105fd8730 (QOS: UNSPECIFIED)
0  Quick Photo Print              0x104c2a0f4 closure #1 in closure #1 in ImageData.callMethod() + 76 (ImageData.swift:76)
1  Quick Photo Print              0x104c28bd8 thunk for @escaping @callee_guaranteed (@guaranteed AWSS3TransferUtilityUploadTask, @guaranteed Error?) -> () + 4296756184 (<compiler-generated>:4296756184)
2  AWSS3                          0x1050eed40 -[AWSS3TransferUtility URLSession:task:didCompleteWithError:] + 1996 (AWSS3TransferUtility.m:1996)
3  CFNetwork                      0x1b615e6bc _CFNetworkHTTPConnectionCacheSetLimit + 206248
4  Foundation                     0x1b313f410 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
5  Foundation                     0x1b3049138 -[NSBlockOperation main] + 100
6  Foundation                     0x1b3141698 __NSOPERATION_IS_INVOKING_MAIN__ + 20
7  Foundation                     0x1b3048dd0 -[NSOperation start] + 732
8  Foundation                     0x1b3142090 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
9  Foundation                     0x1b3141b5c __NSOQSchedule_f + 180
10 libdispatch.dylib              0x1b29f97dc _dispatch_block_async_invoke2 + 104
11 libdispatch.dylib              0x1b2a47184 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1b29efa3c _dispatch_continuation_pop$VARIANT$mp + 412
13 libdispatch.dylib              0x1b29ef190 _dispatch_async_redirect_invoke + 600
14 libdispatch.dylib              0x1b29fbfa4 _dispatch_root_queue_drain + 376
15 libdispatch.dylib              0x1b29fc770 _dispatch_worker_thread2 + 128
16 libsystem_pthread.dylib        0x1b2a96b48 _pthread_wqthread + 212
17 libsystem_pthread.dylib        0x1b2a99760 start_wqthread + 8

**Which AWS service(s) are affected?**
AWSS3

**Expected behavior**
No crash should happen

**Environment(please complete the following information):**
 - SDK Version: AWSS3 2.6.35
 - Dependency Manager: Cocoapods
 - Swift Version : Swift 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 7
 - iOS Version: iOS 13.0
 - Specific to simulators: no

**Additional context**
Can try to provide more information if needed. But as I said before crash is captured by Firebase.

**Comment by kneekey23** [comment]
hey @Zerocool27 have you tried updating to the latest version of the SDK? We are on 2.13.0.
