### ISSUE TITLE
How to re sign in after an invalid user pool token?

### ISSUE THREAD

**Issue by cornr** [aws-amplify/aws-sdk-ios#2367]
**State your question**
The user is signed in via the user pool `AWSMobileClient.default().signIn(username: "username", password: "password")`. When the token gets invalid the documentation at https://aws-amplify.github.io/docs/sdk/ios/authentication#cognito-user-pool-tokens says that the listener will receive a `.signedOutUserPoolsTokenInvalid` and the user needs to sign in again.
Is this an automatic process and therefore I need to store username and password in memory? Is that secure enough?
Or does it mean I have to show the Login View again?

**Which AWS Services are you utilizing?**
AWSMobileClient with User Pool

**Environment(please complete the following information):**
 - SDK Version: 2.13.0
 - Dependency Manager: Carthage
 - Swift Version : 5.1

**Comment by kneekey23** [comment]
hi @cornr your tokens will automatically refresh based on the refresh time you have configured user pools with which can be anywhere from 1 to 3650 days. Therefore, if you get this state, the refresh token expired and you should direct the user to log in again. However this changes when the device goes offline. 

From the docs in regards to offline behavior:

>  If you are offline and make a service request, and your tokens are NOT valid, the service request will be blocked and notifications for signedOutUserPoolsTokenInvalid or signedOutFederatedTokensInvalid will be sent to the listener. In the case of the AppSync client this can be ignored and the queries will come from cache or mutations enqueued with credentials automatically refreshing upon reconnection. For all other services, if this happens and you are offline you should not make the service request until you come back online, at which point the AWSMobileClient will automatically re-enter the token refresh flow outlined above and then make the service call with the updated credentials.
> 
> > 

Hope this helps! Let us know if you have any additional follow up questions.

**Comment by cornr** [comment]
I see. Thanks for making this clear. maybe its better to write something like

    // go to Login View

in the example for: `signedOutUserPoolsTokenInvalid`
