### ISSUE TITLE
Failed with error: Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)"

### ISSUE THREAD

**Issue by RahulDighe** [aws-amplify/aws-sdk-ios#2368]
**Describe the bug**
When I log in the first time then it works perfectly and gets success in response. But once I log out and then login with the different user then I got success in AWSS3TransferUtility -> uploadData but gets failure in  AWSS3TransferUtilityUploadCompletionHandlerBlock -> AWSS3TransferUtilityUploadTask with an error message **Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)"**

I used contentType as image/jpeg.

**Environment(please complete the following information):**
 - SDK Version: 2.12.1 also I have tried with latest release 2.13.0 
 - Dependency Manager:  Cocoapods
 - Swift Version : Objective C

**Device Information (please complete the following information):**
 - Device:  iPhone 11
 - iOS Version: iOS 13.3.1

**Additional context**
When I use the same user(Credentials) after logout then it works. But when I log in with different user after logout then it doesn't work for the second user. But, strangely when I kill the app then it works for the second user.

Please guide.

**Comment by RahulDighe** [comment]
Hello @kneekey23, Thanks for the reply.    
**Here is code snippet**

AWSS3TransferUtilityUploadCompletionHandlerBlock completionHandler = ^(AWSS3TransferUtilityUploadTask *task, NSError *error) {
           dispatch_async(dispatch_get_main_queue(), ^{
               if (error) {
                   NSLog (@"Failed to Upload %@",error.userInfo.description);
                 
               } else {
                   NSLog (@"Successfully Uploaded TransferID %@",task.transferID);
                   NSLog (@"Successfully Uploaded Response %@",task.response);
                }
           });
       };
    
    NSString *key = [NSString stringWithFormat:@"%@/%@",cognitoId,mediaInfo.mediaName];
    NSLog(@"Key is %@",key);
    
    AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
    [[transferUtility uploadData:mediaData
                          bucket:[AppDefaults getS3Bucket]
                             key:key
                     contentType:mediaMimeType
                      expression:expression
               completionHandler:completionHandler] continueWithBlock:^id(AWSTask *task) {
        if (task.error) {
            NSLog(@"upload Error: %@", task.error);
        }
        if (task.result) {
            dispatch_async(dispatch_get_main_queue(), ^{
                NSLog(@"Uploading....");
            });
        }
        return nil;
    }];

**Comment by RahulDighe** [comment]
@kneekey23 could you please advise?

**Comment by kneekey23** [comment]
Hi @RahulDighe, did you resolve your issue? Sorry I didn’t have time to get to this this week but i planned to investigate tomorrow. Please let me know and I’d be happy to look into it tomorrow. Thanks

**Comment by RahulDighe** [comment]
Thanks @kneekey23, Now the issue has the resolve.
It was a session problem Previous developed was using following method to get the session

[[self.user getSession:@“username” password:@“password” validationData:@[validationDataArray]]  continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserSession *> * _Nonnull task) {
            dispatch_async(dispatch_get_main_queue(), ^{
                if(task.error){
                    NSLog(@"Error %@",task.error.userInfo[@"message"]);
                    
                }else if(task.result) {
                    NSLog(@"Refresh Token %@", task.result.refreshToken.tokenString);
    
                }
            });
            return nil;
        }];

Now I have replaced with the following method and it works.

[[[self.user getSession] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserSession *> * _Nonnull task) {
            // (Error handling not shown)
            if(task.error){
                NSLog(@"Error %@",task.error.userInfo[@"message"]);
             
            }else
                if (task.result) {
                    NSLog(@"Refresh Token %@", task.result.refreshToken.tokenString);
                    
                }
            return nil;
        }] waitUntilFinished]

**Comment by RahulDighe** [comment]
I got an error message see the followig code snippet  **Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=-1000 "Authentication delegate not set" UserInfo={NSLocalizedDescription=Authentication delegate not set}**

[[[self.user getSession] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserSession *> * _Nonnull task) {
// (Error handling not shown)
if(task.error){
NSLog(@"Error %@",task.error.userInfo[@"message"]);
}else
if (task.result) {
NSLog(@"Refresh Token %@", task.result.refreshToken.tokenString);
}
return nil;
}] waitUntilFinished]

**Comment by royjit** [comment]
Hi @RahulDighe 

The error you are seeing is because you have not setup a delegate for the `AWSCognitoIdentityUserPool` object. When you call `[self.user getSession]` the SDK will inform you of specific events through the delegate. You can see a sample code [here](https://github.com/awslabs/aws-sdk-ios-samples/blob/master/CognitoYourUserPools-Sample/Swift/CognitoYourUserPoolsSample/AppDelegate.swift#L63).

Having said that these flows have been greatly simplified in the latest Amplify for iOS library which we released recently. If you are starting new I would recommend you take a look at this here - https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios

Difference between SDK and Amplify - https://docs.amplify.aws/sdk/q/platform/ios#how-is-the-sdk-different-from-the-amplify-libraries-for-ios
