### ISSUE TITLE
Installation instructions not working out, strange old code coming from Cocoapods

### ISSUE THREAD

**Issue by factorial** [aws-amplify/aws-sdk-ios#2370]
**Describe the bug**
Attempts to follow the various instructions found in README.md and elsewhere in order to implement S3 support in my iOS Swift app have been to no avail:

**To Reproduce**
1. When attempting to use CocoaPods installation instructions in README.md, the process hangs at "Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`". I waited 10 minutes on this with no further output.

2. When attempting to use "Frameworks" installation instructions in README.md, the link to download the SDK archive leads to https://aws.amazon.com/amplify/ which ultimately leads to https://aws-amplify.github.io/docs/sdk/ios/start where CocoaPods instructions are repeated.

3. Digging further into the Amplify docs we're sent to in number 2 above, https://aws-amplify.github.io/docs/sdk/ios/storage gives different Podfile instructions. These call for no "source" line in the Podfile and result in code that won't compile, giving errors like "AWSS3TransferUtilityUploadExpression has no member progressBlock" when compiling the S3 sample project S3TransferUtility-Sample provided in this repository. Some of the code that came down from Cocoapods had © notices dated 2016.

**Which AWS service(s) are affected?**
S3 iOS SDK

**Expected behavior**
I just thought some of the instructions provided w/ the code would lead to running code.

**Environment(please complete the following information):**
 - SDK Version: 2.13 I think
 - Dependency Manager: Cocoapods or None
 - Swift Version : 4

**Device Information (please complete the following information):**
 - Device: None (won't compile)
 - iOS Version: None (won't compile)
 - Specific to simulators: None (won't compile)

**Comment by kneekey23** [comment]
hi @factorial can you paste your podfile please?

**Comment by royjit** [comment]
Just to follow up on here:

> When attempting to use CocoaPods installation instructions in README.md, the process hangs at "Cloning spec repo cocoapods from https://github.com/CocoaPods/Specs.git". I waited 10 minutes on this with no further output.

Cocoapods has moved to use CDN as default spec repo. So the line ` source 'https://github.com/CocoaPods/Specs.git'` is not required. I have created this [PR](https://github.com/aws-amplify/aws-sdk-ios/pull/2375) to remove it from our README file.

> When attempting to use "Frameworks" installation instructions in README.md, the link to download the SDK archive leads to https://aws.amazon.com/amplify/ which ultimately leads to https://aws-amplify.github.io/docs/sdk/ios/start where CocoaPods instructions are repeated

Looks like our documentation was updated and not reflected in the README, I have made the changes here in the [PR](https://github.com/aws-amplify/aws-sdk-ios/pull/2375).

> Digging further into the Amplify docs we're sent to in number 2 above, https://aws-amplify.github.io/docs/sdk/ios/storage gives different Podfile instructions. These call for no "source" line in the Podfile and result in code that won't compile, giving errors like "AWSS3TransferUtilityUploadExpression has no member progressBlock" when compiling the S3 sample project S3TransferUtility-Sample provided in this repository. Some of the code that came down from Cocoapods had © notices dated 2016.

https://aws-amplify.github.io/docs/sdk/ios/storage should have the right information and that is our official documentation for the SDK. The information given there should work, maybe you have some cached information that is conflicting with the pods. Try doing 
```
pod repo remove master // Explained here - http://blog.cocoapods.org/CocoaPods-1.8.0-beta/
pod update
```

Let us know if that fixes your issue.

**Comment by factorial** [comment]
Thank you both for your responses. I have not been able to return this project since posting this issue but intend to give it another thorough pass next week. I will post copies of the Podfiles I use and their results.

**Comment by factorial** [comment]
Apologies, things went a little globally crazy around the time of this issue. I ultimately chose not to pursue S3 or AWS further for my solution after this poor experience with documentation cost me 8 hours of wasted effort.
