### ISSUE TITLE
When the device time set to future download fails with an error

### ISSUE THREAD

**Issue by rameshtek** [aws-amplify/aws-sdk-ios#2371]
**Describe the bug**
When the device time is set to future download fails with an errorcode "0"  and task.result is nil.
but the same works in Android.

**To Reproduce**

Please find the code snippet below.

AWSS3 *s3 = [AWSS3 defaultS3];   AWSS3HeadObjectRequest *request = [AWSS3HeadObjectRequest new];
  request.bucket = @“bucketName”;
  request.key =@“bucketKey”;
  [[s3 headObject:request] continueWithExecutor:[AWSExecutor mainThreadExecutor] withBlock:^id(AWSTask *task) {
	 if (task.error) {
		 NSLog(@"error %@, code %d",task.result, task.error.code);;
	}
}];
Error :
Error Domain=com.amazonaws.AWSS3ErrorDomain Code=0 "(null)"

**Expected behavior**
Download should succeed even if the device time set to future.
**Screenshots**

**Environment(please complete the following information):**
 Pod file versions:
  'AWSCore', '2.7.0'
  'AWSS3', '2.7.0'
  'AWSCognito', '2.7.0'

  Objective C and Swift 5

**Device Information (please complete the following information):**
iOS 11 and above
iOS simulator and iPhone

**Additional context**

**Comment by kneekey23** [comment]
hi @rameshtek right now the SDK is not designed for this use case and should work for about an hour ahead in time or behind but not a significant large difference in time in the future. Can you possibly elaborate a bit more on your use case for why this is needed?
