### ISSUE TITLE
Kinesis video putmedia for iOS

### ISSUE THREAD

**Issue by PaulIPS** [aws-amplify/aws-sdk-ios#2382]
**State your question**
Hi how do you do a put media request to Kinesis using the iOS SDK?. I can't seam to find any reference code after getting the endpoint URL from `getDataEndpoint`. 

I see in the android SDK there is a ` PutMediaClient.builder()` but I can't seam to find something similar in the iOS SDK. 

**Which AWS Services are you utilizing?**
Kinesis Video 

**Environment:**
 - SDK Version: 2.13
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information:**
 - Device: iPad
 - iOS Version: 13.1.3

**Comment by wooj2** [comment]
Hi @PaulScala,

Thanks for reaching out.  I'm not super familiar with this part of the SDK, but it seems like there is a unit tests here named "testGetHlsStreamingSessionUrl"
https://github.com/aws-amplify/aws-sdk-ios/blob/655e13b7db063a30831cb9c968775999f9e40c90/AWSKinesisVideoTests/AWSKinesisVideoTests.swift#L66

Perhaps changing line 84 from:
https://github.com/aws-amplify/aws-sdk-ios/blob/655e13b7db063a30831cb9c968775999f9e40c90/AWSKinesisVideoTests/AWSKinesisVideoTests.swift#L84

to something like:

```
            getDataEndpointRequest?.apiName = AWSKinesisVideoAPIName.putMedia
```
 might be what you're looking for?

**Comment by PaulScala** [comment]
@wooj2 Thank you for the suggestion. 

The problem is `kvClient.getDataEndpoint()` just returns a url string. I can't seam to find any methods in the iOS SDK related to actually pushing data to that URL.

**Comment by wooj2** [comment]
Hey @PaulScala ,

I checked around with people more familiar with this area, and they said that there is currently no easy way to support this at the moment.

They suggested two potential options with moving forward:
1.  You could use the iOS AWS mobile SDK components to get the endpoint and then use custom logic to get the frames from the camera/device, encode it, package it into MKV and use a NSURL type of client to issue SigV4 signed request to PutMedia directly.

2.  You can attempt to compile the C Producer SDK for iOS and use everything natively: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c
In this case you'd still be responsible for retrieving the frames from the device and encoding them.

Option one seems to be very involved, and it seems like option 2 does some of the heavy lifting for you.

Best of luck!

**Comment by PaulScala** [comment]
Hi @wooj2 Thank you for following up on this. It looks like option 1 would be the best path forwards for us. Does the AWS iOS SDK have anything I can leverage for helping make a SigV4 request, or is it best to make my own REST layer.

**Comment by wooj2** [comment]
Hey @PaulScala ,

As part of AWSCore, there is AWSSignature which I believe should be of some help:
https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSCore/Authentication/AWSSignature.h

**Comment by PaulScala** [comment]
Hey @wooj2 So I have been digging into the AWS core SDK trying to implement this, and I got a bit stuck. 

My understanding is that to load data into a web request you need to use a request sterilizer. Since none of the request serializes take a data object in I have to create my own: 

``` swift
class AWSRawRequestSerializer: NSObject, AWSURLRequestSerializer {
    var data : Data
    
    init(data: Data) {
        self.data = data
    }
    
    func validate(_ request: URLRequest!) -> AWSTask<AnyObject>! {
        return AWSTask(result: nil)
    }
    
    func serializeRequest(_ request: NSMutableURLRequest!, headers: [AnyHashable : Any]!, parameters:
        [AnyHashable : Any]!) -> AWSTask<AnyObject>! {
        
        //AWSJSONRequestSerializer
        
        if headers != nil {
            for (key, value) in headers {
                request.addValue(value as! String, forHTTPHeaderField: key as! String)
            }
        }
        
        request.httpBody = self.data
        return AWSTask(result: nil)
    }
}
```

The problem I am having is when I set `request.httpBody` I then get back `The request signature we calculated does not match the signature you provided` . 

any idea what I am missing? When I step step through the request the method `signRequestV4` is being hit inside `AWSSignature`.

**Comment by ShahinOskouie** [comment]
Any updates on this topic? I have the same issue!

**Comment by atierian** [comment]
Thanks for opening this feature request. We don't plan on adding support for `PutMedia` at this time.
