### ISSUE TITLE
Simplifying pods

### ISSUE THREAD

**Issue by pbishnupuri** [aws-amplify/aws-sdk-ios#2384]
I am trying to build an app and submit it to the app store, however the AppStore is not liking some of your pod files, can you help out with this?
 
pod 'AWSAPIGateway'
    pod 'AWSAutoScaling'
    pod 'AWSAppSync'
    pod 'AWSCloudWatch'
    pod 'AWSComprehend'
    pod 'AWSConnect'
    pod 'AWSDynamoDB'
    pod 'AWSEC2'
    pod 'AWSElasticLoadBalancing'
    pod 'AWSKMS'
    pod 'AWSKinesis'
    pod 'AWSKinesisVideo'
    pod 'AWSKinesisVideoArchivedMedia'
    pod 'AWSLambda'
    pod 'AWSLogs'
    pod 'AWSMachineLearning'
    pod 'AWSPinpoint'
    pod 'AWSRekognition'
    pod 'AWSSES'
    pod 'AWSSNS'
    pod 'AWSSQS'
    pod 'AWSSageMakerRuntime'
    pod 'AWSSimpleDB'
    pod 'AWSTextract'
    pod 'AWSS3'
    pod 'AWSMobileClient', '~> 2.12.0'      # Required dependency
    pod 'AWSAuthUI', '~> 2.12.0'            # Optional dependency required to use drop-in UI
    pod 'AWSUserPoolsSignIn', '~> 2.12.0'
 
 
 
 
How do I simplify the number of pods I need?

**Comment by wooj2** [comment]
Hi @pbishnupuri,
Thanks for reaching out to us.  Could you explain a little bit more about what you mean when you say the app store is not liking some of the pod files?  Is there a specific error you are seeing?

Also, without understanding more about what your application does, it is difficult to give advice on what pods you should include/exclude from your Podfile.  Do you know what services you trying to use?

**Comment by pbishnupuri** [comment]
We are making a Run Logging app. We keep getting all the way through the upload process to the app store, and right at the last step we get an error in our upload tool that says “no suitable application records were found. verify your bundle identifier ‘org.cocoapods.AWSSageMakerRuntime’ (and/or any other pod we have from AWS) is correct.”

This isn’t an issue with our application bundle identifier – we can verify this by changing the bundle ID in the app’s build settings manually, and we get  the same error as above, but with our own app bundle ID. It’s definitely an issue with the pods themselves. 

We have our bundle ID under the identifiers tab connected, and can verify that it is connected because when we change the bundle ID, build, and try to upload the error shown is the same as this screenshot except that it is the name of our bundle ID ("Curro-ActivityLogger").

In this case what's weird is it is calling out issues with the bundle identifiers for cocoapods we have installed.

<img width="1146" alt="Screen Shot 2020-03-26 at 12 43 32 PM" src="https://user-images.githubusercontent.com/31415137/77678651-75f83b00-6f5f-11ea-976a-9fed5a71a6a2.png">

**Comment by wooj2** [comment]
This post on stackoverflow seems relevant to what you might be running into: https://stackoverflow.com/questions/48921424/why-verify-your-bundle-identifier-org-cocoapods-alamofire-is-correct ?

It makes me think that there might be a setting of [CFBundlePackageType](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundlepackagetype) that isn't being configured correctly.

1.  I'm not sure why this would be off, unless someone accidentally changed some values, or perhaps is overriding some environment variable?
2.  Maybe try using the latest verison of cocoapods (at least 1.8?) and reintegrating the aws framework into your app?

Best of luck.

**Comment by pbishnupuri** [comment]
We tried that. We changed it to APPL. I don't what the problem can. Thanks for your support!

**Comment by wooj2** [comment]
There seems to be something specific in the build/release/signing settings of your application.  Unfortunately, I don't think there's much we can do from our side, so I will be closing this ticket.

Best of luck!
