### ISSUE TITLE
Threadlock after switching default user pools

### ISSUE THREAD

**Issue by joeboyscout04** [aws-amplify/aws-sdk-ios#2389]
**Describe the bug**
In our app, we have two different user pools, one for staging and one for production.   We recently uncovered a case where the AWS SDK would deadlock if there was data in the keychain from the production pool when attempting to use the staging pool.  

I traced this bug to the following in `AWSMobileClientExtensions.swift`

```
 public func getTokens(_ completionHandler: @escaping (Tokens?, Error?) -> Void) {
        switch self.federationProvider {
        case .userPools, .hostedUI:
            break
        default:
            completionHandler(nil, AWSMobileClientError.notSignedIn(message: "User is not signed in, please sign in to use this API."))
            return
        }
        
        if self.federationProvider == .hostedUI {
            ... some other code
        }
        if self.federationProvider == .userPools {
            self.userpoolOpsHelper.userpoolClient?.delegate = self.userpoolOpsHelper
            self.userpoolOpsHelper.authHelperDelegate = self
            self.tokenFetchOperationQueue.addOperation {
                self.tokenFetchLock.enter()
                self.currentUser?.getSession().continueWith(block: { (task) -> Any? in
// DEBUGGING:  This block never executes!
                    if let error = task.error { 
                        completionHandler(nil, error)
                        self.invokeSignInCallback(signResult: nil, error: error)
                    } else if let session = task.result {
                        completionHandler(self.userSessionToTokens(userSession: session), nil)
                        self.federationProvider = .userPools
                        if (self.currentUserState != .signedIn) {
                            self.mobileClientStatusChanged(userState: .signedIn, additionalInfo: [:])
                        }
                        self.invokeSignInCallback(signResult: SignInResult(signInState: .signedIn), error: nil)
                    }
                    self.tokenFetchLock.leave()
                    return nil
                })
                self.tokenFetchLock.wait()
            }
            return
        }
```

And in `AWSCognitoIdentityUser.m`

```
/**
 Get a session
 */
-(AWSTask<AWSCognitoIdentityUserSession*> *) getSession {
    
    //check to see if we have valid tokens
    __block NSString * keyChainNamespace = [self keyChainNamespaceClientId];
    NSString * expirationTokenKey = [self keyChainKey:keyChainNamespace key:AWSCognitoIdentityUserTokenExpiration];
    NSString * expirationDate = self.pool.keychain[expirationTokenKey];
    
// DEBUGGING: expirationDate is nil
    if(expirationDate){
        ...some other code. 
    }
    return [self setConfirmationStatus: [self interactiveAuth]];
}

```

**To Reproduce**
1. Create a user in the production cognito pool and sign in.  This puts a token in the keychain (we manage our own keychain token store).
2. Delete the application.  
3. Reinstall the application, the staging pool is enabled by default.
4. Attempt to `getTokens`.

**Which AWS service(s) are affected?**
iOS SDK

**Expected behavior**
I would expect the block to return at some point. 

**Screenshots**
N/A

**Environment(please complete the following information):**
 - SDK Version: 2.13.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Device Information (please complete the following information):**
 - Device: iPhone (simulator and physical device), 
 - iOS Version: iOS 13.x
 - Specific to simulators: No

**Additional context**
The application bundle is the same for both production and staging in this test case, so the keychain is shared.

**Comment by joeboyscout04** [comment]
Did a bit more tracing and tracked it further to this code in `AWSMobileClientExtensions.swift`  It's being called through a long chain of callbacks. 

```
//MARK: Extension to hold UserPoolAuthHelperlCallbacks methods
extension AWSMobileClient: UserPoolAuthHelperlCallbacks {
    
    func getPasswordDetails(_ authenticationInput: AWSCognitoIdentityPasswordAuthenticationInput,
                            passwordAuthenticationCompletionSource: AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails>) {
        
        // getPasswordDetails for customAuth will be called when the session expires.
        // This call would be triggered from getSession(). In this case we donot need
        // to inform the user that the session is expired, because that is handled by
        // getCustomAuthenticationDetails.
        if(self.userPoolClient?.isCustomAuth ?? false) {
            let authDetails = AWSCognitoIdentityPasswordAuthenticationDetails(username: self.currentUser?.username ?? "",
                                                                              password: userPassword ?? "dummyPassword")
            passwordAuthenticationCompletionSource.set(result: authDetails)
            userPassword = nil
            return
        }
        if (self.federationProvider != .userPools) {
            passwordAuthenticationCompletionSource.set(error: AWSMobileClientError.notSignedIn(message: "User is not signed in, please sign in to use this API."))
        }
        switch self.currentUserState {
        case .signedIn, .signedOutUserPoolsTokenInvalid:
            self.userpoolOpsHelper.passwordAuthTaskCompletionSource = passwordAuthenticationCompletionSource
            self.mobileClientStatusChanged(userState: .signedOutUserPoolsTokenInvalid, additionalInfo: ["username":self.userPoolClient?.currentUser()?.username ?? ""])
        default:
            break
        }
    }
   ```

In the case of `case .signedIn, .signedOutUserPoolsTokenInvalid:`, (which is the case here, currentUserState == .signedIn), then the passwordAuthenticationCompletionSource.set() is never called.  This causes the block to not return.

**Comment by wooj2** [comment]
Hey @joeboyscout04,

Thanks for reaching out, and reporting this issue.

Unfortunately, the AWS Mobile Client does not currently support two user pools in a single application.

As a workaround, would you be able to use different bundle ids between your debug and production versions of the application?  Doing so would effectively use a different keychain between your production and debug application (which is probably what you want anyways).

**Comment by joeboyscout04** [comment]
Hey there, 
We do use two different bundles in most normal use cases, just occasionally we wanted to test with the production backend in the staging app.  I understand you can’t use two pools at the same time, I was just surprised to see switching them would brick the app so hard it would need a device reset to fix.

However, I’m not sure that having two pools is the only way this is threadlock issue could occur.  I’ve gotten more feedback from testers (in a pure production environment) that when they started using our latest build with Cognito enabled, the app would also hang on launch, the same failure behavior as in the case I noted above.   We’ve also recently had to migrate users from one pool to another, and I assume this bug would also occur in that case.

**Comment by lawmicha** [comment]
hi @joeboyscout04, thanks for the clarifiation on your use case.

> I understand you can’t use two pools at the same time, I was just surprised to see switching them would brick the app so hard it would need a device reset to fix.

we should support different user pools for developer's staging purposes and will take this as a bug for investigation to see if we can switch between two user pools and reproduce the behavior. It looks like from the above use case, we should first test
1. sign up/ sign into user pool 1
2. get session
3. switch the configuration, rebuild the app and run
4. sign up/sign into to user pool2
3. try to get session and see that it doesn't get called

**Comment by krunduev** [comment]
Have the same issue

**Comment by BennettSmith** [comment]
We typically switch between different amplify environments when developer are working on new features. When we switch, if the simulator had an earlier build of the app on it and was signed in, when we launch the app now it deadlocks on this line:

https://github.com/aws-amplify/aws-sdk-ios/blob/520d66b5e5a9c0d71b26d528c25d1c528f2a1f9f/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift#L764

To me, it seems like the solution would be for the AWS Mobile Client to do a bit of validation/cleanup of the keychain items when it is initialized. If it sees items that are for a different user pool id, it should probably clear out the stored values.

As it is, we run into this issue whenever a developer starts working on a new feature and forgets to reset their simulator or device first.

**Comment by DongQuanRui** [comment]
@joeboyscout04 Hi, Sorry for taking us long to reply.

As you mentioned: when you tried to call `getToken()` after switching to a different user pool while keeps a user signed in, what happens is: the auth state is `.signedOutUserPoolTokenInvalid` according to [state tracking](https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/ios#state-tracking).

What you can do is to add the code snippet to [track state](https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/ios#state-tracking) and when state `.signedOutUserPoolTokenInvalid` returns, user is required to call `SignIn()` again to overwrite the previous invalid token and then no more deadlock.

Feel free to reach out if it is not working.
