### ISSUE TITLE
iOS SDK support for Route53

### ISSUE THREAD

**Issue by automatictester** [aws-amplify/aws-sdk-ios#2390]
**Which AWS Services is the feature request for?**
Route53

**Is your feature request related to a problem? Please describe.**
Currently I am managing my Route53 configuration by calling Lambda (using AWS iOS SDK) from my Swift application. I need to use lambda solely for the purpose of managing Route53. All other services I need, like EC2, are already supported by iOS SDK.

**Describe the solution you'd like**
I'd like to interact with Route53 directly (e.g. ChangeResourceRecordSets) from my Swift code, using iOS SDK. 

**Describe alternatives you've considered**
I am currently using Lambda, but that adds complexity to the overall solution.

**Comment by palpatim** [comment]
We will take this on as a feature request to add a Route53 module/pod to the SDK.

**Comment by atierian** [comment]
Thanks for opening this feature request. We are not adding new service clients to the AWS SDK for iOS at this time.
