### ISSUE TITLE
Keep getting Incorrect Username and Password on AWSMobileClient Signin

### ISSUE THREAD

**Issue by VinnyScorsatto** [aws-amplify/aws-sdk-ios#2392]
Hello,

I am trying to use AWSMobileClient.default().signIn, but it keeps returning NonAuthorised (Incorrect username or password).

I am initialising the configuration on memory
let mobileClient = AWSMobileClient(configuration: AppEnvSetting().configuration)

and this is the variable that contains the configuration:

let configuration: [String: Any] = [
        "IdentityManager": [
            "Default": [:]
        ],
        "CognitoUserPool": [
          "Default": [
            "PoolId": "us-west-XXXX",
            "AppClientId": "XXXX",
            "AppClientSecret": "XXXX",
            "Region": "us-west-2"
          ]
        ],
        "Auth": [
            "Default": [
                "authenticationFlowType": "CUSTOM_AUTH"
            ]
        ]
    ]

I can confirm that the user exists at the pool, and I have done tests resetting the password and deleting the user and I am getting the right error messages, just the signing does not return the custom challenge.

the pool is configured to receive email as username, so I am calling on iOS:

AWSMobileClient.default().signIn(username: username, password: "dummy") { (signInResult, error) in
            if let signInResult = signInResult {
                if (signInResult.signInState == .customChallenge) {
                    print("Custom Challenge parameters: \(signInResult.parameters)")
                } else {
                    print("SignInResult: \(signInResult)")
                }
            } else {
                var displayErrorMsg = ""
                if let error = error as? AWSMobileClientError {
                    switch(error) {
                    case .userNotFound(let message):
                        displayErrorMsg = message
                    case .badRequest(let message):
                        displayErrorMsg = message
                    default:
                        displayErrorMsg = "Authentication error."
                        break
                    }
                }
            }
        }

Thanks
"aws-amplify/aws-sdk-ios" "2.13.0" - Carthage
iOS 10.0 or Higher

**Comment by royjit** [comment]
Hi,

Thank you for reaching out. Can you share the lambda trigger you are using. Please take a look at the [documentation](https://aws-amplify.github.io/docs/sdk/ios/authentication#lambda-trigger-setup) regarding the use of lambda trigger with custom auth. Since AWSMobileClient assumes the initial step of custom auth as SRP_A your lambda trigger should be implemented in a particular way as shown in the document..

Also, just a reminder, AWSMobileClient is not implemented to support more than one authType in a single app.

**Comment by VinnyScorsatto** [comment]
Hey @royjit , thanks for that.

Yep, it seems that the way our lambda was implemented to support our web application ignores SRP as the first step, so that is why I am getting this response.. I will close this issue and keep tracking on #2398, that can help my implementation.. thanks
