### ISSUE TITLE
Ability to Define Return Values for AppSync Operations on iOS

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/aws-sdk-ios#2393]
**Which AWS Services is the feature request for?**
AppSync

**Is your feature request related to a problem? Please describe.**
There doesn't seem to be any ready-made/easy way provide flexibility in terms of defining the return values we get from our queries/mutations. In Javascript it is fairly easy to customize queries/mutations to only return the relevant information, but Swift returns all of the data for that model which can be unnecessary and potentially quite costly if there are some data intensive elements contained within a model. 

**Describe the solution you'd like**
I'd like a way to specify in swift which values I'd like to be returned from my queries and mutations.

**Describe alternatives you've considered**
I've considered creating custom resolvers for custom defined queries and mutations for all the different "overloads" or combinations of return data I'd want, although i'm not sure if that would necessarily work. I've also considered modifying the swift.api file to add overloaded methods for the different operations. I've also considered going around appsync using api gateway + lambda + accessing the dynamodb tables for some queries/mutations. although Amplify CLI doesn't provide a way to link api gateway or lambda function to the dynamodb tables generated by Appsync.

**Additional context**
I think this is a huge missing piece from appsync being an awesome tool for iOS development.

**Comment by palpatim** [comment]
> I've also considered modifying the swift.api file to add overloaded methods for the different operations.

@julien-tamade I think this is your best bet. You could overload methods, or even better, create a separate method as an extension of the code-generated models, stored in a separate file. That way, you wouldn't lose your changes when you update the API.swift file via codegen, and it would be obvious that it was something other than "default" behavior.

One other option might be to consider the https://github.com/aws-amplify/amplify-ios project. We are currently in preview mode, but marching toward GA. The API category of Amplify iOS allows you to construct fully custom GraphQL documents for GraphQL API calls, which you can serialize into custom types, giving you a high degree of control over your query and return. Since it is in preview, that might not work with your project timeline, but it's another option.

Hope this helps.

**Comment by julien-tamade** [comment]
@palpatim, thanks for the response. For now my team's gonna stick with the current sdk because we've got our app released and don't want to risk anything. Can you provide some guidance on extending the code-generated models? is it a matter of changing the operationString? Do you have to create entire new GraphQLSelectionSet structs to store the return data? Is there anything else I'm not considering? Would it be possible to provide an example?

Thanks for your help!

**Comment by palpatim** [comment]
@julien-tamade 

Looking at this more closely, you would probably have to re-create the entire operation structure; the generated code is deeply nested and selection set isn't easy to separate out.

Luckily, Amplify CLI offers support for this, as detailed in the [transformer documentation](https://aws-amplify.github.io/docs/cli-toolchain/graphql). In the Workflows section, "Flow 3: No API changes, just update GraphQL statements & generate code" shows how you can:

* Use a locally-defined schema to generate a set of default operations
* Modify the selection set of operations locally, e.g. by editing `./graphql/queries.graphql`
* Regenerate swift code with `amplify codegen types`

For example, the default Todo schema:

**./amplify/backend/api/my_backend_name/schema.graphql**
```graphql
schema.graphql
type Todo @model {
  id: ID!
  name: String!
  description: String
}
```

Generates a default set of query operations that includes the following definition for `GetTodo`:

**./graphql/queries.graphql**
```graphql
query GetTodo($id: ID!) {
  getTodo(id: $id) {
    id
    name
    description
  }
}
```

* Edit that file to remove the `description` field
* Re-generate the API.swift file with `amplify codegen types`
    ```bash
    amplify codegen types
    ✔ Downloaded the schema
    ✔ Code generated successfully and saved in file API.swift
    ```

Note that the API.swift file removes `description` field in the appropriate places:

```diff
diff API.swift API-Original.swift
898c898
<     "query GetTodo($id: ID!) {\n  getTodo(id: $id) {\n    __typename\n    id\n    name\n  }\n}"
---
>     "query GetTodo($id: ID!) {\n  getTodo(id: $id) {\n    __typename\n    id\n    name\n    description\n  }\n}"
942a943
>         GraphQLField("description", type: .scalar(String.self)),
951,952c952,953
<       public init(id: GraphQLID, name: String) {
<         self.init(snapshot: ["__typename": "Todo", "id": id, "name": name])
---
>       public init(id: GraphQLID, name: String, description: String? = nil) {
>         self.init(snapshot: ["__typename": "Todo", "id": id, "name": name, "description": description])
980a982,990
>
>       public var description: String? {
>         get {
>           return snapshot["description"] as? String
>         }
>         set {
>           snapshot.updateValue(newValue, forKey: "description")
>         }
>       }
```

Hope this helps!

**Comment by julien-tamade** [comment]
Thanks @palpatim that's very helpful and saves a lot of time. 

For anybody else reading this, my team found luck with just creating .graphql files containing custom queries and mutations and left them in the generated graphql folder. They seem to get picked up and compiled during the codegen process even when running `amplify codegen` without including `types`.

So that's one option if you want to only add new functionality on top of all of the auto-generated operation, but if you want to remove unnecessary generated functionality you can delete the autogenerated queries.graphql, mutations.graphql, and subscriptions.graphql and leave in your custom files, and then run `amplify codegen types` to only generate the operations you have defined.

@palpatim is there an easier, less manual way of preventing all of the auto-generated operations from being created?

**Comment by palpatim** [comment]
@julien-tamade I'm not aware of any other workflows that would prevent that, but you might want to ask the question on the [CLI repo](https://github.com/aws-amplify/amplify-cli/issues) to get a more educated answer. :)
