### ISSUE TITLE
Username being overwritten by UUID - intended behaviour?

### ISSUE THREAD

**Issue by mickeysox** [aws-amplify/aws-sdk-ios#2394]
**State your question**
I am signing a user up using AWSMobileClient.default().signUp(username: "+44**********"...
and that works fine, a user is generated, but the username is a UUID, is this intended behaviour?

**Which AWS Services are you utilizing?**
AWSMobileClient

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [2.13.1]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [5.1]

**Device Information (please complete the following information):**
 - Device: [iPhone 11 pro Max]
 - iOS Version: [13.4]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by lawmicha** [comment]
Hi @mickeysox, can you clarify how you are retrieving the username? Which method on AWSMobileClient are you calling?
