### ISSUE TITLE
"authenticationFlowType": "USER_PASSWORD_AUTH" being ignored

### ISSUE THREAD

**Issue by VinnyScorsatto** [aws-amplify/aws-sdk-ios#2398]
Hey Guys,

I am trying to use USER_PASSWORD_AUTH, but doing it through aswconfiguration.json or on memory does not work. It keeps using USER_SRP_AUTH.

{
  "CognitoUserPool": {
    "Default": {
      "PoolId": "us-west-2_xxxx",
      "AppClientId": "xxxx",
      "AppClientSecret": "xxxxx",
      "Region": "us-west-2"
    }
  },
  "Auth": {
    "Default": {
     "authenticationFlowType": "USER_PASSWORD_AUTH"
    }
  }
}

![Uploading Screen Shot 2020-03-31 at 2.14.40 PM.png…]()

**Environment(please complete the following information):**
 - "aws-amplify/aws-sdk-ios" "2.13.0" - Carthage
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - iOS 10.0 or Higher

**Comment by fernandoaguilar** [comment]
hey looks like you can force USER_PASSWORD_AUTH with this setting in your awsconfiguration.json `MigrationEnabled: True`, took me a while to find this in the code, couldnt find this documented anywhere, pretty frustrating these past hours have been. Hope this helps.

**Comment by VinnyScorsatto** [comment]
Hey @fernandoaguilar , thanks for that. I have found this as well, but not sure how to make it work since I have to do a CUSTOM_AUTH and if the user is not found I do the migration.. Can you share your awsconfiguration.json if that is ok? Thanks a lot for your help

**Comment by royjit** [comment]
Hi @VinnyScorsatto 

Can you please give an idea of your auth flow? We would like to understand the your use case and try to reproduce the scenario. Looks like you are using different type of auth mechanism in a single app and it is not something that AWSMobileClient currently support. 
Also, what all lambda triggers are you planning to use?

**Comment by VinnyScorsatto** [comment]
Hey @royjit , thanks for that,

Sure.. So basically I am following our web flow.

I first do CUSTOM_AUTH, but if the user is not found, I do USER_PASSWORD_AUTH that triggers a user migration to from our db to cognito.

Since there is no way to use two auth flows, I will probably need to handle the migration out of the AWSMobileClient.

Discussing with my team, we believe that I can try to use only USER_PASSWORD_AUTH with this setting in MigrationEnabled: True. I will give it a try and let you know... thanks

**Comment by VinnyScorsatto** [comment]
Hey @royjit , I managed to make it worked using USER_PASSWORD_AUTH and setting MigrationEnabled: True. So I will close it for now. Thanks @fernandoaguilar for the tip!

**Comment by fernandoaguilar** [comment]
@Vinnyscorsatto no problem. Glad I could help!

**Comment by radianttap** [comment]
> hey looks like you can force USER_PASSWORD_AUTH with this setting in your awsconfiguration.json `MigrationEnabled: True`, took me a while to find this in the code, couldnt find this documented anywhere, pretty frustrating these past hours have been. Hope this helps.

Where in the configuration.json you MigrationEnabled = true?

**Comment by VinnyScorsatto** [comment]
@radianttap , I had to it in the code, by the time it did not work in the .json file

 static let configuration: [String: Any] = [
         "CognitoUserPool": [
           "Default": [
             "PoolId": "",
             "AppClientId": "",
             "Region": "",
             "MigrationEnabled": "YES"
           ]
         ],
         "Auth": [
             "Default": [
               "authenticationFlowType": "USER_PASSWORD_AUTH"
             ]
         ]
     ]

**Comment by fernandoaguilar** [comment]
this is what worked for us
```json

{
	"CognitoUserPool": {
		"Default": {
			"PoolId": "...",
			"AppClientId": "...",
			"AppClientSecret": "...",
			"Region": "...",
            "MigrationEnabled": true,
            "EnableSFAuthenticationSesssion": true
		}
	},
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "...",
                "AppClientId": "...",
                "AppClientSecret": "...",
                "SignInRedirectURI": "...",
                "SignOutRedirectURI": "...",
                "Scopes": ["phone", "email", "profile", "openid", "aws.cognito.signin.user.admin"],
                "EnableSFAuthenticationSesssion": true
            }
        }
    }
}

**Comment by radianttap** [comment]
Thank you both, will try as soon as I can. It's amazing to me that there's no documentation for the structure of this JSON, at least I could not find it anywhere.

**Comment by radianttap** [comment]
Adding `MigrationEnabled` param into `CognitoUserPool.Default` part of the config worked; now SDK obeys the auth flow type specified in `Auth.Default` section of the config.
Thanks again.
