### ISSUE TITLE
AWSS3TransferUtilityMultiPartUploadTask shows in progress status after completion

### ISSUE THREAD

**Issue by kamil3** [aws-amplify/aws-sdk-ios#2399]
**Describe the bug**
AWSS3TransferUtilityMultiPartUploadTask shows in progress status after completion.

This is how I retrieve all upload tasks:
```swift
func allMultiPartUploadTasks() -> [AWSS3TransferUtilityMultiPartUploadTask] {
    let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: AWSConfigurationProvider.transferUtilityOptionsKey)!
    return transferUtility.getMultiPartUploadTasks().result!.compactMap({ $0 as? AWSS3TransferUtilityMultiPartUploadTask })
}
```
Upload method:
```swift
func uploadFileURL(
    url: URL,
    key: String,
    progressBlock: ((Double) -> Void)?,
    completionHandler: ((Result<AWSS3TransferUtilityMultiPartUploadTask, Error>) -> Void)?,
    continueWithBlock: ((Result<AWSS3TransferUtilityMultiPartUploadTask, Error>) -> Void)?
) {
    let expression = AWSS3TransferUtilityMultiPartUploadExpression()
    expression.progressBlock = { _, progress in
        progressBlock?(progress.fractionCompleted)
    }
    let completionHandler: AWSS3TransferUtilityMultiPartUploadCompletionHandlerBlock = { task, error in
        if let error = error {
            completionHandler?(.failure(error))
        } else {
            completionHandler?(.success(task))
        }
    }

    let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: AWSConfigurationProvider.transferUtilityOptionsKey)!
    transferUtility.uploadUsingMultiPart(
        fileURL: url,
        bucket: "bucketName",
        key: key,
        contentType: "text/plain",
        expression: expression,
        completionHandler: completionHandler
    ).continueWith { task in
        if let error = task.error {
            continueWithBlock?(.failure(error))
        }
        if let result = task.result {
            continueWithBlock?(.success(result))
        }
        return nil
    }
}
```
Setting up handlers:
```swift
func setMultiPartUploadTaskHandlers(
    task: AWSS3TransferUtilityMultiPartUploadTask,
    progressBlock: ((AWSS3TransferUtilityMultiPartUploadTask, Double) -> Void)?,
    completionHandler: ((Result<AWSS3TransferUtilityMultiPartUploadTask, Error>) -> Void)?
) {
    task.setProgressBlock { task, progress in
        progressBlock?(task, progress.fractionCompleted)
    }
    task.setCompletionHandler { task, error in
        if let error = error {
            completionHandler?(.failure(error))
        } else {
            completionHandler?(.success(task))
        }
    }
    task.suspend()
    task.resume()
}
```
Supporting background upload:
```swift
func application(_ application: UIApplication, handleEventsForBackgroundURLSession identifier: String, completionHandler: @escaping () -> Void) {
    AWSS3TransferUtility.interceptApplication(application, handleEventsForBackgroundURLSession: identifier, completionHandler: completionHandler)
}
```

**To Reproduce**
This happens only when I start uploading an url, then progress starts. When it's near finishing I go to background. I wait a while to make sure upload finishes. I force close the app. When I open the app again and retrieve all tasks, it shows there is one in progress. Handlers are not called. I can only remove this task by reinstalling the app, or registering transfer utility again:
```swift
AWSS3TransferUtility.remove(forKey: AWSConfigurationProvider.transferUtilityOptionsKey)
AWSS3TransferUtility.register(
    with: configuration!,
    transferUtilityConfiguration: tuConf,
    forKey: AWSConfigurationProvider.transferUtilityOptionsKey
) { (error) in
}
```

**Which AWS service(s) are affected?**
AWSS3

**Expected behavior**
Upload task should not retain with in progress status according to steps described above. It should return completed status or call a completion handler.  

**Environment(please complete the following information):**
 - SDK Version: 2.13.0
 - Dependency Manager: Carthage
 - Swift Version : 5.1.3

**Device Information (please complete the following information):**
 - Device: iPhone7
 - iOS Version: iOS 13.3.1

**Comment by palpatim** [comment]
Hi @kamil3 

> I wait a while to make sure upload finishes.

Can you verify that the upload actually completes by going to your S3 destination and seeing the file? Simply waiting is not enough to guarantee that the upload completes successfully.

That said, if you are able to verify that the object is in fact uploaded correctly, and you're still seeing this, then that sounds like a bug we'll need to investigate.

**Comment by kamil3** [comment]
Hi @palpatim

I'll try to investigate it next week, because I'm not the owner of this S3.
However, even if it's not there, it would still looks like a bug. Progress and completion handlers are not called, task seems to be frozen.

**Comment by dziwiedz** [comment]
Hi @palpatim - as @kamil3 wrote - we don't have access to S3, but soon we will have ability to check it by making api request. In the meantime I will try to talk with backend guys do they are able to help me with that.

We will update you when we will have more informations :)
