### ISSUE TITLE
Getting UserPoolsToken Invalid sooner

### ISSUE THREAD

**Issue by AjayKokchaMutualMobile** [aws-amplify/aws-sdk-ios#2400]
We are using
`AWSCognitoService.client = AWSMobileClient(configuration: awsConfiguration)`
[here awsConfiguration is a Dictionary]
In the awsConfiguration we have added an additional parameter `"MigrationEnabled" : true.`
We have added this  `"migrationEnabled: true"` to AWS configuration as we need the user migration script to be triggered. 
After adding this parameter, we have noticed that our token is invalidated after an hour. 
 In this method:
`AWSCognitoService.client.addUserStateListener(self) { (userState, info) in }`
We are getting userState as signedOutUserPoolsTokenInvalid in every 60 mints and as per documentation when state goes to this, we have no choice but to sign out the user and show him a sign in screen. 
We wanted to understand why the state is going to signedOutUserPoolsTokenInvalid state in every 60 mins. 
When we did not have the migrationFlag in our configuration, it was working as expected. 
We would like to understand what is the right way of adding MigrationEnabled in the AWS configuration json file or when we pass it as a dictionary. 
FYI: Our token expiry limit is set to 24 hours. And we are using the latest SDK version.
```
 - AWSAuthCore (2.13.1):
    - AWSCore (= 2.13.1)
  - AWSCognitoIdentityProvider (2.13.1):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
    - AWSCore (= 2.13.1)
  - AWSCognitoIdentityProviderASF (1.0.1)
  - AWSCore (2.13.1)
  - AWSMobileClient (2.13.1):
    - AWSAuthCore (= 2.13.1)
    - AWSCognitoIdentityProvider (= 2.13.1)
```

**Comment by Saravanakumar22** [comment]
I am using **AWSMobileClient** `federatedSignIn` for Facebook login. After the successful login, the token has expired within **10 mins** and I'm trying to upload some content to **S3** ended up with this error **Unable to refresh. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Invalid login token. Token expired: 1587968552 >= 1587739762}**.  Please help out with this

Note. I have added `AWSMobileClient.default().addUserStateListener` method.

**Comment by drochetti** [comment]
Hi @Saravanakumar22, the token expiration after 10 minutes when using SIWA is being tracked here #2513. Make sure you follow that issue and we will follow up there.
