### ISSUE TITLE
Migrating from AWSSignInManager to AWSMobileClient

### ISSUE THREAD

**Issue by cornr** [aws-amplify/aws-sdk-ios#2404]
Our current app version uses the `AWSSignInManager` for sign in functionality Including Cognito User Pool as well as Google and Facebook (via the `AWSIdentityProvider`s included in AWS-SDK-iOS).
As I have noted in https://github.com/aws-amplify/aws-sdk-ios/issues/1809 there is no `IdentityProvider` implementation for "Sign In With Apple". Therefore we spend the last couple of weeks migrating our whole sign in process to `AWSMobileClient` (which works together with Apple SignIn). And we are almost there...

No we are facing the issue, that current users (current app version) will be logged out after an update to the new version (which will be using `AWSMobileClient` instead of `AWSSignInManager`).
In detail: `AWSMobileClient` says a user previously signed in with `AWSSignInManager` is not signed in.

Is there a way to migrate the stored credentials from `AWSSignInManager` so that the user can stay signed in with the switch to `AWSMobileClient`?

**Which AWS Services are you utilizing?**
Cognito Identity Pool

**Environment(please complete the following information):**
 - SDK Version: 2.13.0
 - Dependency Manager: Carthage
 - Swift Version : 5.2

**Comment by cornr** [comment]
This issue looks like a duplication of https://github.com/aws-amplify/aws-sdk-ios/issues/1243 but I am curious if there is a maybe manual process of migrating the credentials.

**Comment by palpatim** [comment]
@cornr There is no supported way of migrating credentials. AWSMobileClient uses different keys and constructions for its persisted credentials.

**Comment by cornr** [comment]
As @Thuran mentioned in #1243 a forced re sign in is no good for the user experience and increases the likelihood of app deletion.

**Comment by palpatim** [comment]
Hi @cornr, we'll keep the feature request #1243 on our backlog for evaluation against other enhancements. In the meantime, I'm closing this issue.
