### ISSUE TITLE
Unable to switch Pool configuration

### ISSUE THREAD

**Issue by kostiag** [aws-amplify/aws-sdk-ios#2405]
**State your question**
I have multiple environments dev/test and would like to be able to switch between the 2. However, once logged in to dev I keep getting token from dev environment for user that exists in both or not able to login with a user that exists only in test. I have tried:
mobileClient?.signOut(options: SignOutOptions(signOutGlobally: true, invalidateTokens: true), 
as well as 
                mobileClient?.clearCredentials()
                mobileClient?.clearKeychain()
I am initializing client using configuration:
let configuration: [String: Any] = [
                "IdentityManager": [
                    "Default": [:]
                ],
                "CognitoUserPool": [
                    "Default": [
                        "AppClientId": connectionData["CognitoIdentityUserPoolAppClientId"],
                        "PoolId": connectionData["CognitoIdentityUserPoolId"],
                        "Region": connectionData["CognitoIdentityUserPoolRegionString"]
                    ]
                ],
                "CredentialsProvider": [
                    "CognitoIdentity": [
                        "Default": [
                            "PoolId": connectionData["CredentialsProviderPoolId"],
                            "Region": connectionData["CognitoIdentityUserPoolRegionString"]
                        ]
                    ]
                ]
            ]
            let mobileClient = AWSMobileClient(configuration: configuration)
            mobileClient.initialize { (userstate, error) in

**Which AWS Services are you utilizing?**
Cognito , AWSMobileClient
**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
  - AWSCore (2.13.1)
  - AWSMobileClient (2.13.1):
    - AWSAuthCore (= 2.13.1)
    - AWSCognitoIdentityProvider (= 2.13.1)
  - AWSS3 (2.13.1):
    - AWSCore (= 2.13.1)

 - Dependency Manager: Cocoapods
 - Swift Version : 5
**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: 13
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by palpatim** [comment]
We do not support switching between AWSMobileClient configurations on the fly. In order to support this case, you'd have to re-launch the app and initialize AWSMobileClient with a different set of configuration values.

**Comment by kostiag** [comment]
Thanks that’s unfortunate
