### ISSUE TITLE
Questions  about S3

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/aws-sdk-ios#2406]
Hello,

I have some questions about S3.

Let’s say I am creating an app like a social network.
Pictures uploaded by users are completely public, everyone can see. Even from outside the system. Because sometimes you receive emails and these emails have a link to one of those pictures. So, I guess I need public URLs, rather than using that logic for signing requests explained here:
https://github.com/aws-amplify/aws-sdk-ios/issues/2282

I think it is possible if I upload all the pictures inside public/ and and setup proper permissions like this guy, correct?
https://github.com/aws-amplify/aws-sdk-ios/issues/2233

But my question is, can every single file be deleted/modified by its owner? (a Cognito user) or is that impossible given that the key does not contain the user id? (public/1234567.jpg)

My next question is, I think I have to use AWSS3TransferUtility.default().uploadData to upload pictures, but, what about if I want to upload 10 pictures at the same time? Does aws sdk include any queue or anything like that or do I have to embed that inside NSOperation and use my own NSOperationQueue?
I see a file called AWSS3TransferUtilityTasks (plural) but it seems to me it is only about individual tasks, isn’t it?
However, I see  cancelAll in AWSS3TransferManager.h and the doc says " Cancels all of the upload and download requests.". So, where is that queue?

Thanks a lot for suggestions.

**Which Category is your question related to?**
Storage

**Amplify CLI Version** 
4.13.2

**What AWS Services are you utilizing?**
S3, Cognito, Aurora, AppSync

**Comment by Ricardo1980** [comment]
@palpatim  @royjit 
Any recommendation?
Thanks a lot.

**Comment by lawmicha** [comment]
Hi @Ricardo1980, if you want to send dynamic emails with links to your images, does CloudFront fit your use case? https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-s3-amazon-cloudfront-a-match-made-in-the-cloud/

Regarding file access permissions: https://docs.amplify.aws/lib/storage/configureaccess?platform=js (although JS docs, the amplify provisioning is the same across the platforms)
- public - anyone can access, so to your question, everyone can modify and delete
- protected - keys are made with appending the identityId, ie. protected/<id>/restOfKey, can only be modifiied by the user of <id> and read only for everyone else
- private - same as protected, cannot be read by anyone except for the user with <id>.
I think what you are looking for here is to use the protected folder when showing images in the app, so users can upload and only the user that uploaded the image can modify/delete but everyone else can read.

Regarding multiple uploads, we currently do not support this, you'll have to accomplish this by looping over the images and calling upload for each image. The tasks represents the transferUtiliity operation which can be resumed, paused, cancelled, etc.
