### ISSUE TITLE
Error using AWSMobileClient with cognito user pool --> Fatal error: Unexpectedly found nil while unwrapping an Optional value: file

### ISSUE THREAD

**Issue by Sagato** [aws-amplify/aws-sdk-ios#2411]
Hello I setup a Cognito User Pool on my aws console.
Now I am trying to setup my ios APP (SwiftUI) with the AWSMobileClient (authentication).
But I am receiving an Error, I can not explain.

> Fatal error: Unexpectedly found nil while unwrapping an Optional value: file

On This line:
> AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift, line 211

I provided my awsconfiguration.json file in the project root.

**code snippets**

and called this on my appdelegate:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        AWSMobileClient.default().initialize { (userState, error) in
            if let userState = userState {
                print("UserState: \(userState.rawValue)")
            } else if let error = error {
                print("error: \(error.localizedDescription)")
            }
        }
        return true
    }
```
I can see the console message --> `UserState: signedOut`

On my login view I am calling on submit:

```
func signIn() {
        self.loading = true
        self.error = false
        print(username)
        print(password)
        session.signIn(username: username, password: password) { (signInResult, err) in
            print("Error happened")
            if let error = err  {
               print("\(error.localizedDescription)")
           } else if let signInResult = signInResult {
               switch (signInResult.signInState) {
               case .signedIn:
                   print("User is signed in.")
               case .smsMFA:
                   print("SMS message sent to \(signInResult.codeDetails!.destination!)")
               default:
                   print("Sign In needs info which is not yet supported.")
               }
           }
        }
    }
```

session.signIn() contains:
```
 func signIn(username: String, password: String, handler: @escaping (SignInResult?, Error?) -> Void) {
     AWSMobileClient.default().signIn(username: username, password: password, completionHandler: handler)
}
```

**Environment(please complete the following information):**
 - pod  'AWSMobileClient', '~> 2.12.0'      # Required dependency
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Standard Xcode emulator iphone 11 Pro Max  iOS 13.4

**Comment by royjit** [comment]
Hi @Sagato ,

Can you please provide a complete stack trace?
Also what is `session` object in your code snippet above.

**Comment by MaheshSC** [comment]
Hi here

When am trying to signing using AWSMobilse SDK

the app crashes with the same error

```
AWSMobileClient.default().signIn(username: username, password: password) { (signInResult, error) in

            if let error = error  {
                print("\(error)")
                // in real life, present an error message to user
            } else if let signInResult = signInResult {
                switch (signInResult.signInState) {
                case .signedIn:
                    print("User is signed in.")
                case .smsMFA:
                    print("SMS message sent to \(signInResult.codeDetails!.destination!)")
                default:
                    print("Sign In needs info which is not et supported.")
                }
            }
        }

```

**Comment by MaheshSC** [comment]
> Hi @Sagato ,
> 
> Can you please provide a complete stack trace?
> Also what is `session` object in your code snippet above.

Hi please can you look below my comment and give me reply

**Comment by royjit** [comment]
@MaheshSC 
Please provide the crash log / stack trace, so we can debug the issue.

**Comment by MaheshSC** [comment]
Hi 

i don't know what happened i have updated my Xcode & Mac to the latest one now am in Xcode 11.4
and it started working am able to login with username and password

now i need help in implementing custom login flow also by sending the clientMetaData

I will try myself and get back to you if i have any problem

**Comment by lawmicha** [comment]
here's the link to custom auth flow from the docs https://docs.amplify.aws/sdk/auth/custom-auth-flow?platform=ios

closing this issue now, as the original problem is resolved. feel free to open a new issue if you see a bug with the relavant details

**Comment by MaheshSC** [comment]
@lawmicha 

can you please help me in this

**Comment by pruales** [comment]
+1 I'm having this exact same problem.

**Comment by tnsivakumar** [comment]
I had the same problem. But It got resolved after I drag and drop the awsconfiguration.json from finder into the Xcode. As mentioned in this documentation - https://docs.amplify.aws/sdk/auth/getting-started/q/platform/ios#install-dependencies. But I am not sure you are facing the same.

**Comment by mobee-bill** [comment]
@pruales I am experiencing the same crash with AWSMobileClientExtensions.swift.  Has the issue resolved for you?

**Comment by frankieackah** [comment]
Hey guys did this issue get fixed ? Currently trouble with the google webui sign in.

**Comment by rochnaldo** [comment]
bonjour moi aussi j'ai un erreur de ce type je commence tout juste le code et je ne sais pas quoi faire

**Comment by rochnaldo** [comment]
![Capture d’écran 2020-06-30 à 18 07 05](https://user-images.githubusercontent.com/67075985/86136150-c2be5580-bafc-11ea-9a54-ad96b190e69e.png)

**Comment by rochnaldo** [comment]
si quelqu'un pense savoir merci

**Comment by palpatim** [comment]
@rochnaldo I'm sorry, we don't have any French speaking staff to help with this problem.

Based on your screen shot, it looks like your crash has nothing to do with the SDK, but rather is having a problem dequeuing a table cell. Check that there exists a cell with that identifier somewhere in your storyboard.

If you believe you are experiencing a problem from the SDK, please file a new issue with the details requested by the "Bug" template so we can investigate.
