### ISSUE TITLE
How to check username is available or not?

### ISSUE THREAD

**Issue by yosuke1985** [aws-amplify/aws-sdk-ios#2418]
**State your question**
Cognito setting: Username - Users can use a username and optionally multiple alternatives to sign up and sign in. 

I want to check the `username` or `preferred username` is exist or not.
How can I do that?
Only can check by `AWSMobileClient.default().signUp` method by error?
Maybe this method also can check but it needs to set the passwords and also it created the users.

**Which AWS Services are you utilizing?**
Amplify, Cognito

**Environment:**
 - SDK Version: AWS SDK for iOS 2.13.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Comment by royjit** [comment]
This is not currently supported by Cognito. I have talked with the Cognito service team and they would take this as a feature request.

**Comment by yosuke1985** [comment]
@royjit Thank you. I will wait.
