### ISSUE TITLE
AWSMobileClient Custom_Auth SignIn pass clientMetaData/Validation data to Define Auth Challenge Trigger 

### ISSUE THREAD

**Issue by MaheshSC** [aws-amplify/aws-sdk-ios#2435]
I have successfully implemented the Custom Auth SignIn using AWSMobileClient SDK

Requirement is 
i need to let the backend know what i am logging in with Phone or Email based on it sending SMS / SNS backend will do tho

So i am not able to understand how to do this

I tried sending validation data too but not able to get the validationData in define auth challenge

here is the signIn method

```
AWSMobileClient.default().signIn(username: username, password: "dummyPassword", validationData: ["verify_field": "phone_number"]) { (signInResult, error) in
            if let error = error  {
                print("\(error)")
                if let handler = completion {
                    handler(nil, error)
                }
            } else if let signInResult = signInResult {
                
                switch (signInResult.signInState) {
                case .signedIn:
                    print("User is signed in.")
                case .smsMFA:
                    print("SMS message sent to \(signInResult.codeDetails!.destination!)")
                default:
                    print("Sign In needs info which is not et supported.")
                }
                if let handler = completion {
                    handler(signInResult, nil)
                }
            }
        }
```

**Comment by MaheshSC** [comment]
@lawmicha 
@royjit 

Can you please provide me quick help
am struggling from 1 weak just to pass some data to DefineAuthChallenge/CreateAuthChallenge
i want to send some key value pairs

**Comment by royjit** [comment]
Hi @MaheshSC 
Could you please share the authentication flow that you are using? 
As mentioned [here](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#CognitoUserPools-InitiateAuth-request-ClientMetadata) only a few lambda triggers receive the clientMetadata for the initiateAuth flow. `AWSMobileClient.signIn` method internally calls `initiateAuth` and pass the validationData to these lambdas. 
If you are calling `AWSMobileClient.confirmSignIn` for a `.customChallenge` response, it sends the clientMetaData to more lambda triggers as explained [here](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html#CognitoUserPools-RespondToAuthChallenge-request-ClientMetadata).

Please check if the above handles your use case.

**Comment by MaheshSC** [comment]
Hi @royjit 

as given above the code thats the one am using to sign in the user
and later on another code to confirm signin

I have see the documentation you given links in the comment

but there is no where i can find the client side implementation
like i want the documentation how to achieve this in iOS - Swift, Android - Java
Please help me with this

**Comment by MaheshSC** [comment]
If you think my requirement cannot be fulfilled by this flow (MobileClient)
please help me any other flow where i can pass some key-values to backend while logging the users 
so backend can use the key-values whether to send SMS/SNS to verify the login

**Comment by royjit** [comment]
Hi @MaheshSC 
The `validationData` passed in `AWSMobileClient.signIn` is internally send as `clientMetadata` and it can be accessed through the following lambda triggers:
- Pre signup
- Pre authentication
- User migration
Note that _Define Auth Challenge_ lambda trigger is not in the list.

Also you can pass `clientMetaData` through `AWSMobileClient.confirmSignIn`, in which case the clientMetaData can be accessed through the following lambda triggers:
- Post authentication
- Pre token generation
- Define auth challenge
- Create auth challenge
- Verify auth challenge
