### ISSUE TITLE
Error upon file uploading with CEPH

### ISSUE THREAD

**Issue by Alex-C-Eltima** [aws-amplify/aws-sdk-ios#2436]
**State your question**
We use your AWS iOS SDK to work with CEPH server (Ceph Object Gateway S3 API). After switching from AWSS3TransferManager to AWSS3TransferUtility neither uploading nor downloading of any files is working anymore, and returns the error. Below is the code example, we will appreciate your assistance. 

**Which AWS Services are you utilizing?**
Ceph Object Gateway S3 API

**Provide code snippets (if applicable)**

Here is a code example of uploading Screen.png file.

```
NSString *bucketName = @"my-new-bucket";
NSString *endpoint = @"https://ubuntu-srv";
AWSStaticCredentialsProvider *credentialsProvider = [[AWSStaticCredentialsProvider alloc] initWithAccessKey:self->accessKey secretKey:self->secretKey];
AWSEndpoint *customEndpoint = [[AWSEndpoint alloc] initWithRegion:AWSRegionUSEast1 service:AWSServiceS3 URL:[[NSURL alloc]initWithString:endpoint]];
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 endpoint:customEndpoint credentialsProvider:credentialsProvider];
[AWSS3 registerS3WithConfiguration:configuration forKey: bucketName];
[AWSS3TransferUtility registerS3TransferUtilityWithConfiguration:configuration forKey:bucketName];
AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility S3TransferUtilityForKey:bucketName];

AWSTask *task = [transferUtility uploadFile:[NSURL fileURLWithPath:@"/Users/user1/Desktop/Screen.png"]
                            bucket:bucketName
                                key:@"Screen.png"
                        contentType:@"image/png"
                        expression:nil
                    completionHandler:^(AWSS3TransferUtilityUploadTask * _Nonnull task, NSError * _Nullable error) {
    if (error) {
        NSLog(@"%@", error); // "A server with the specified hostname could not be found."
    }
}];
[task waitUntilFinished];


Printing description of error:
Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found."
 UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x600000c67ed0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}},
  _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <42F98E16-2B6E-4279-BE0F-88EC4CB49995>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <42F98E16-2B6E-4279-BE0F-88EC4CB49995>.<1>"
), NSLocalizedDescription=A server with the specified hostname could not be found.,
 NSErrorFailingURLStringKey=https://my-new-bucket.ubuntu-srv/Screen.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MSV0J1J0QHIGJRR3M32X%2F20200407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200407T095102Z&X-Amz-Expires=2999&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Signature=849e93bf5c523ddc99dc8a66e4a939ab65679e5efb840e5ae6141904f6fa7ab0,
  NSErrorFailingURLKey=https://my-new-bucket.ubuntu-srv/Screen.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MSV0J1J0QHIGJRR3M32X%2F20200407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200407T095102Z&X-Amz-Expires=2999&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Signature=849e93bf5c523ddc99dc8a66e4a939ab65679e5efb840e5ae6141904f6fa7ab0, _kCFStreamErrorDomainKey=12}
```

**Environment(please complete the following information):**
 - SDK Version: 2.13.2
 - Dependency Manager: none
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone6s or any other
 - iOS Version: iOS 13

**Comment by lawmicha** [comment]
Hi @Alex-C-Eltima are you able to upload using TransferManager with a proxy like https://www.charlesproxy.com/ connected to see what is the endpoint being uploaded to? I suspect another way you could narrow this down is to use TransferUtility with S3 directly instead of CEPH just to make sure your configuration values are in the right format. You can create a new provision pretty quickly with `amplify add storage` or follow this sample: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferUtility-Sample/Swift

`A server with the specified hostname could not be found.` sounds like configuration may not be in the right format (the expected configuration values may have changed in TransferUtility, compared to TransferManager) or simply DNS resolving for your hostname. you can also try the download case to see if the URL at which it is being downloaded at and try using the URL directly to make sure it is not a DNS problem

**Comment by Alex-C-Eltima** [comment]
Hello, 

Thank you for getting back to me. 

> are you able to upload using TransferManager with a proxy like https://www.charlesproxy.com/ connected to see what is the endpoint being uploaded to?

Yes, the endpoint is like  https://bucket-name.server-name, bucket name is being used for the host name. 

> I suspect another way you could narrow this down is to use TransferUtility with S3 directly

It is working correctly with Amazon, the problem only occurs with CEPH server

> sounds like configuration may not be in the right format (the expected configuration values may have changed in TransferUtility, compared to TransferManager) or simply DNS resolving for your hostname.

But, connection and requests for list of files in the bucket are working correctly, the error occurs only for uploading and downloading operations. 

Hope these comments will clarify something.

**Comment by palpatim** [comment]
@Alex-C-Eltima 

The virtual-hosted style of URL (`bucket-name.server-name`) pattern is the [offically supported](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) way of addressing S3 resources. We have backlog items to completely retire path-based support from the SDK.

Unfortunately, we don't have any particular insight into non-AWS services, and we don't test our SDKs with backends other than those provided by AWS, so we're not able to provide guidance on making this work with the CEPH service.
