### ISSUE TITLE
AWS SNS push notification subscription error(com.amazonaws.AWSSNSErrorDomain error 6.)

### ISSUE THREAD

**Issue by jeky1990** [aws-amplify/aws-sdk-ios#2456]
ios version 13.3.1
phone model ios 6s
AWS version - 
 - AWSSNS (2.13.1):
 - AWSCore ( 2.13.1)

AWS SNS subscribed successfully with error (com.amazonaws.AWSSNSErrorDomain error 6.)
silent notification not working in ios 13 working fine in ios 12
`let apnsPayload : [String:Any] = ["content-available":1]`
APNS payload with message attributes
```
var attribute_values = [String: AWSSNSMessageAttributeValue]()
        let pushType = AWSSNSMessageAttributeValue.init()
        pushType?.stringValue = "background"
        pushType?.dataType = "String"
        
        let priority = AWSSNSMessageAttributeValue.init()
        priority?.stringValue = "5"
        priority?.dataType = "String"
        
        attribute_values.updateValue(pushType!, forKey: "AWS.SNS.MOBILE.APNS.PUSH_TYPE")
        attribute_values.updateValue(priority!, forKey: "AWS.SNS.MOBILE.APNS.PRIORITY")
        
        request?.messageAttributes = attribute_values
```

**why I am not able to subscribe successfully without error and silent push notification not working with this payload and message attributes?**

**Comment by lawmicha** [comment]
hi @jeky1990 I think the error you're seeing corresponds to AWSSNSErrorInvalidParameter

https://github.com/aws-amplify/aws-sdk-ios/blob/df5cb0b37d34759104512fd705a1c9e7e62a2517/AWSSNS/AWSSNSModel.h#L31

It is odd that it started failing in iOS 13. 
Did you at any point upgrade the SDK version that may correlate to the failure? 
When you say that it subscribed successfully with the error, does that mean it the subscription call completed with an error? if that is the case, i don't think it is receiving any messages

**Comment by jeky1990** [comment]
hey @lawmicha thanks for replying
-- I got notification successfully.
-- the main issue is silent notification not receiving. (with above parameter)

**Comment by lawmicha** [comment]
It sounds like there may have been a breaking change in iOS 13. Can you take a look at this and let us know if it's related to your problem? https://aws.amazon.com/blogs/messaging-and-targeting/sending-push-notifications-to-ios-13-devices-with-amazon-sns/

**Comment by jeky1990** [comment]
@lawmicha 
we have set in "**aps**" only one key which is  **["content-available":1]**, so it means the aws automatically set its header value from aps....as per this https://aws.amazon.com/blogs/messaging-and-targeting/sending-push-notifications-to-ios-13-devices-with-amazon-sns/
but it is not set automatically yet... I m also using the latest version of aws sns

**Comment by lawmicha** [comment]
Hi @jeky1990 we'll need to investigate this by creating AWS SNS resources and an iOS app using the AWS SNS SDK to reproduce and further understand how to enable silent notifications. 

Since the error indicates an invalid parameter in the SDK, there may be something incorrect coming from AWS SNS service. Could you also check in the AWS Forums for SNS to see if there are any service related configuration that is incorrect/missed? 
https://forums.aws.amazon.com/forum.jspa?forumID=72

**Comment by lawmicha** [comment]
> hey @lawmicha thanks for replying
> -- I got notification successfully.
> -- the main issue is silent notification not receiving. (with above parameter)

can you clarify what is the current state of the issue?
- are you able to subscribe successfully to sns from your app? Or are you still seeing `AWSSNSErrorInvalidParameter` error?
- are you able to subscribe successfully to sns and then failures like `AWSSNSErrorInvalidParameter` when notifications are sent? both notifications and silent notifications?

It looks like three requirements are there
```
content_available: 1 in your notification payload
apns-push-type = background in your notification header
apns-priority = 5 in your notification header
```

if you could more instructions to set up your system or code snippets, it would help us with the investigation. If this is only happening in iOS 13, there may be a bug related to Apple's release. Is this stil happening with the latest iOS?
