### ISSUE TITLE
Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=-1000 "

### ISSUE THREAD

**Issue by RahulDighe** [aws-amplify/aws-sdk-ios#2472]
**Describe the bug**
I got the following error it is not consistent. Some times it happens some times don't.
**Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=-1000 "Authentication delegate not set" UserInfo={NSLocalizedDescription=Authentication delegate not set}**

**Code Snippet**
[[[self.user getSession] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserSession *> * _Nonnull task) {
            // (Error handling not shown)
            if(task.error){
                NSLog(@"Error %@",task.error.userInfo[@"message"]);
                [self showErrorAlert];
            }else
                if (task.result) {
                }
            return nil;
        }] waitUntilFinished];

I got an error with meaage **Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=-1000 "Authentication delegate not set" UserInfo={NSLocalizedDescription=Authentication delegate not set}**

**Environment(please complete the following information):**
SDK Version: 2.12.1
Dependency Manager: Cocoapods
Swift Version: Objective C

**Device Information (please complete the following information):**
Device: iPhone 11
iOS Version: iOS 13.3.1

**Comment by wooj2** [comment]
Hi @RahulDighe 

Thanks for reaching out out to us!
1.  Is it possible to share with us any additional information/code samples with regards to how you are configuring Cognito for your application?

2.  When you say "Some times it happens and sometimes don't", How often are you seeing this?  Once every minute? or once every hour? Once every day?  Is there a particular action the app is taking that can be correlated to seeing this error message?

2.  Are you using AWSMobileClient, or using AWSCognitoAuth directly?  If you are using AWSCognitoAuth, is there any reason why you are unable to use AWSMobileClient?
https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios

**Comment by RahulDighe** [comment]
**1. Here is I am configuring Cognito**

    AWSServiceConfiguration *serviceConfiguration =
    [[AWSServiceConfiguration alloc] initWithRegion:[self getAWSRegionFromString:cognitoIdentityUserPoolRegion] credentialsProvider:nil];
    //create a pool
    AWSCognitoIdentityUserPoolConfiguration *configuration =
    [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:cognitoIdentityUserPoolAppClientId
                                                         clientSecret:cognitoIdentityUserPoolAppClientSecret
                                                               poolId:cognitoIdentityUserPoolId];
    
    [AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:serviceConfiguration
                                                           userPoolConfiguration:configuration forKey:awsCognitoUserPoolsSignInProviderKey];
    _pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:awsCognitoUserPoolsSignInProviderKey];
    
    if(_pool){
        NSLog(@"pool %@",_pool.token);
    }
    else{
        NSLog(@"Pool not inialized");
    }
}

2. There is no specific action on the app which causes the error. 
3. I am not using AWSMobileClient or AWSCognitoAuth directly.

**Comment by wooj2** [comment]
Hi @RahulDighe ,

The error you're seeing seems to be emitted from:
https://github.com/aws-amplify/aws-sdk-ios/blob/655e13b7db063a30831cb9c968775999f9e40c90/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L620

Which happens when `self.pool.delegate` is set to nil.  Looking at your configuration, it looks like you are not setting `_pool.delegate`, like in our sample app here:
https://github.com/awslabs/aws-sdk-ios-samples/blob/523617320a5a7ba351549a7017a372f6ee2b3db3/CognitoYourUserPools-Sample/Objective-C/CognitoYourUserPoolsSample/AppDelegate.m#L54

So seems like you would need to assign the delegate, and then implement the appropriate delegate functions.

That being said, if AWSMobileClient can fit your use case for auth, we highly recommend using that over directly using these low level libraries.

Best of luck!

**Comment by royjit** [comment]
Closing this issue because of no communication. Feel free to contact us if you have further questions.
