### ISSUE TITLE
EC2 not working on iOS

### ISSUE THREAD

**Issue by OthmanT** [aws-amplify/aws-sdk-ios#2493]
**Describe the bug**
I an trying to list the instances in my account with no success.
I have the permission set in the IAM.
I have S3 and SNS working with no problem.

**To Reproduce**
1. Run the provided snippet on a iOS project using the AWSEC2 framework

**Observed Behavior**
No instances description returned
Error return `Domain=com.amazonaws.AWSEC2ErrorDomain Code=0`

**Expected Behavior**
Getting a list of the instances I own

**Stack Trace**
No crash.

**Code Snippet**
```
    AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc]
                                                         initWithRegionType:AWSRegionUSEast1
                                                          identityPoolId:kIdentity];
    
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:credentialsProvider];
    
    [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;

    AWSEC2 *ec2 = [AWSEC2 defaultEC2];

    AWSEC2DescribeInstancesRequest *request = [AWSEC2DescribeInstancesRequest new];
    [ec2 describeInstances:request completionHandler:^(AWSEC2DescribeInstancesResult * _Nullable response, NSError * _Nullable error) {
        if(error){
            NSLog(@"%@ = %@", @"EC2 describe Error", error);
        }else{
            NSLog(@"%@ = %@", @"EC2 describe Response", response);
        }
    }];
```

**Unique Configuration**
I'm trying this on iOS and MacOS

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

**Screenshots**
Not needed.

**Environment(please complete the following information):**
 - SDK Version: last one
 - Dependency Manager: Cocoapods
 - Objective-c
 - Xcode Version: 13.3.1

**Device Information (please complete the following information):**
 - Device: iPhone 11 Pro Max and MacOS
 - iOS Version: iOS 13.3.1 & Catalina 10.15.2

**Additional context**
Add any other context about the problem here like your specific use case.

**Relevant Console Output**
Always return the following error : 
`Domain=com.amazonaws.AWSEC2ErrorDomain Code=0`

**Comment by OthmanT** [comment]
For some reason EC2 does not accept the CognitoPoolID, I have to log using an access key and a secret key to make it work

**Comment by palpatim** [comment]
One brief note: 
> I'm trying this on iOS and MacOS

We do not officially support the SDK on MacOS yet.

That said, if this is happening also on iOS, the fact that it works when you use static credentials strongly suggests that either your app isn't properly loading your IdentityPool configuration, or that the IdentityPool is not properly configured to allow the `ec2:DescribeInstances` action. I'd start with the second one.

Please ensure the IAM Roles associated with your IdentityPool have the appropriate policy permissions in place. At a minimum, you'd likely need `ec2:DescribeInstances`. Also remember that Cognito IdentityPools can be associated with both authenticated *and* unauthenticated roles, so make sure your permissions are attached to the correct role for your use case.

You can verify that the roles are set up properly by using the AWS command line tool to assume those role credentials and doing an `aws ec2 describe-instances`.

Hope this helps.
