### ISSUE TITLE
Sign-in with Apple for drop-in auth in AWSMobileClient/AWSAuthSDK/AWSAuthUI 

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-ios#2537]
Need Apple Sign-in capability added to added to AWSMobileClient.default().showSignIn

**Which AWS Services is the feature request for?**
AWSMobileClient : Drop-in Sign-in UI via AWSMobileClient, AWSAuthUI, AWSAuthCore, AWSSignInProvider.

**Describe the solution you'd like**

Add an Apple sign-in button to the showSignIn UI .  Add aws-sdk-ios/AWSAuthSDK/Sources/AWSAppleSignIn (AWSSppleSignInProvider) and related classes.

**Comment by BillBunting** [comment]
@palpatim Thank you and the team for adding AWSAppleSignIn.  The pod AWSAppleSignIn is not available although it has been release, please advise.

```
pod update 
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `AWSAppleSignIn (= 2.14.1)`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by palpatim** [comment]
Please see [my response](https://github.com/aws-amplify/aws-sdk-ios/issues/2833#issuecomment-655661697) to your comment in the other thread: There are compilation/import errors with that pod that we're fixing now, and plan to release a new minor version to fix as soon as we're able.

**Comment by palpatim** [comment]
We've released the AWSAppleSignIn module as part of [2.14.2](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.14.2). Available via normal distribution channels, including [CocoaPods](https://cocoapods.org/pods/AWSAppleSignIn).

**Comment by BillBunting** [comment]
@palpatim Thank you.  I was able to add sign in with Apple last night. I have it working with issues - when user state is signedOutFederatedTokensInvalid, calling AWSMobileClient.default().showSignIn(...) is redisplaying the sign-in rather than refreshing quietly and returning.  This results in the user needing to sign-in after a short period of inactivity (~10 min). Is this the expected behavior?  My understanding is that I should just be calling showSignIn() again which should just refresh and continue and not display the sign in to the end user. Or, should I be calling a lower-level API to refresh the token?  (My code works fine for Facebook and Google, as is)

The documentation says to : 
`
signedOutFederatedTokensInvalid: The tokens associated with the federation provider like Google or Facebook have expired and need to re-submitted to AWSMobileClient. You can do that by calling the federatedSignIn method or by showing the drop in UI. If the end user is unable to sign in, call releaseSignInWait method to return an error to the calling API.
`  (https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSMobileClient/Enums/UserState.html)

**Comment by palpatim** [comment]
@BillBunting The 10-minute expiration is a known issue with the SIWA integration: see https://github.com/aws-amplify/aws-sdk-ios/issues/2513 for more discussion. We're still investigating the right way to fix this, but I don't have an update just yet.

**Comment by BillBunting** [comment]
@palpatim thank you for the info.  I added a some logging to my prior comment, if that helps in any way.

**Comment by BillBunting** [comment]
@palpatim On August 2, Apple rejected an attempt to release an update to my app (need to release a bug fix version).  

"Guideline 4.8 - Design - Sign in with Apple - We noticed that your app uses a third-party login service but does not offer Sign in with Apple. Apps that use a third-party login service for account authentication must offer Sign in with Apple to users as an equivalent option. To resolve this issue, please revise your app to offer Sign in with Apple as an equivalent login option."

Please make fixing #2513 a high priority. Thank you.

**Comment by BillBunting** [comment]
Has there been any progress or any work/conversation between Amazon and Apple to resolve this issue?

**Comment by drochetti** [comment]
Hey @BillBunting we are investigating #2513 with high priority. I'll close this one to keep the communication in a central place and we will follow up with you there.
