### ISSUE TITLE
Provide a code example to work with `AWSPinpointTargetingSendMessagesRequest` in swift

### ISSUE THREAD

**Issue by lingxiao** [aws-amplify/aws-sdk-ios#2546]
**State your question**
I am working with iOS in swift 4, developing in xcode 11. I would like to send a PinPoint message from the client side to a list of specific users, whose device token is known. I am using `AWSPinpointTargetingSendMessagesRequest` per this SO answer (https://stackoverflow.com/questions/51576333/send-push-notification-from-ios-using-aws-pinpoint).

**Which AWS Services are you utilizing?**

Cognito, Amplify, GraphQL, PinPoint.

**Provide code snippets (if applicable)**

```
let appId : String = "s09d......"
let sendMessagesRequest = AWSPinpointTargetingSendMessagesRequest()!
sendMessagesRequest.applicationId = appId
sendMessagesRequest.messageRequest = messageRequest
AWSPinpointTargeting.default().sendMessages(sendMessagesRequest){ response, error in 
        ...
}
```

The issue is I do not know how to specify the `messageRequest` object. I know what it's suppose to be based on the doc here: (https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSPinpoint/Classes/AWSPinpointTargetingSendMessagesRequest.html#/c:objc(cs)AWSPinpointTargetingSendMessagesRequest(py)messageRequest), but a code sample would be helpful.

**Environment(please complete the following information):**
 - SDK Version: latest release
 - Dependency Manager: pd
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: iPhone  11
 - iOS Version: 13.4.1
 - Specific to simulators: N/A

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by lingxiao** [comment]
Need update ASAP

**Comment by lawmicha** [comment]
Does this work for you?
```swift
// Create the request object
let request = AWSPinpointTargetingSendMessagesRequest()!
// Create the message request object
let messageRequest = AWSPinpointTargetingMessageRequest()!

// set up the message request object with your data
messageRequest.traceId = "traceId"

// set the message request on the request
request.messageRequest = messageRequest
```
