### ISSUE TITLE
Pass clientMetaData to resendSignUpCode call

### ISSUE THREAD

**Issue by pedroaiwin** [aws-amplify/aws-sdk-ios#2547]
**Which AWS Services is the feature request for?**
AWSMobileClient

**Is your feature request related to a problem? Please describe.**

After the issue created by @Skyfallz #2299  the parameter ClientMetadata was added to different Cognito API calls, but the [resendSignUpCode](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ResendConfirmationCode.html) call was not included. 

As in the [signUp](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html) I need to pass the clientMetaData parameter to the resendSignUpCode call, would this be possible?

Thank you very much.

**Comment by javiboo** [comment]
+1

**Comment by royjit** [comment]
This is released in the latest version of the SDK. Please take a look. 
Closing this ticket.
