### ISSUE TITLE
*SEND* push notification client side

### ISSUE THREAD

**Issue by lingxiao** [aws-amplify/aws-sdk-ios#2554]
**State your question**

I need to send push  notification client side

**Which AWS Services are you utilizing?**

Amplify, GraphQL, Pinpoint. 

**Provide code snippets (if applicable)**

        let params = AWSPinpointTargetingSendMessagesRequest()!
        params.applicationId = _appid
        params.messageRequest = nil

I do not know how to specify the  messageRequest object per documentation here [https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSPinpoint/Classes/AWSPinpointTargeting.html](url). In javascript it would be a simple JSON object like:

    const sendMessagesParams = {
        ApplicationId: process.env.PINPOINT_APP_ID,
        SendUsersMessageRequest: {
            Users: {
                [whoReceive]: {}
            },
            MessageConfiguration: {
                APNSMessage: {
                    Action: 'OPEN_APP',
                    Title: 'You have a new message',
                    SilentPush: false,
                    Body: content
                },
                GCMMessage: {
                    Action: 'OPEN_APP',
                    Title: 'You have a new message',
                    SilentPush: false,
                    Body: content
                }
            }
        }
    };

**Environment(please complete the following information):**
 - SDK Version: [latest]
 - Dependency Manager: [POD]
 - Swift Version : [4.0]

**Device Information (please complete the following information):**
 - Device: [iphone 11]
 - iOS Version: [ iOS 13.4]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by royjit** [comment]
Duplicate issue - https://github.com/aws-amplify/aws-sdk-ios/issues/2546
