### ISSUE TITLE
AWSMobileClient SignUp/SignIn with different AuthType

### ISSUE THREAD

**Issue by MaheshSC** [aws-amplify/aws-sdk-ios#2569]
Current setup we have is 
When user registers new account with Phone and Email
What we want to Achieve is to Confirm both in one shot

So our configuration is it confirms Phone number first and for Confirming user has to re-login the app

for that we are doing auto login in the background

But due to am using Auth Type as CUSTOM_AUTH am unable to use another Auth Type USER_PASSWORD_AUTH

Can someone help me how to use the dual Auth Types ?

**Comment by royjit** [comment]
Dual auth type is not currently supported with AWSMobileClient. Please check if you can make use of lambda triggers to achieve your use case.
