### ISSUE TITLE
 Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Invalid login token. Token expired: 1589092400 >= 1589092129}

### ISSUE THREAD

**Issue by RahulDighe** [aws-amplify/aws-sdk-ios#2570]
**Describe the bug**
When I log in the first time then it works perfectly When I try after some time like 1 or 2 hrs then got the error **Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Invalid login token. Token expired: 1589092400 >= 1589092129}**
When I killed the app try again then its works.

**Environment(please complete the following information):**

SDK Version: 2.12.1 also I have tried with latest release 2.13.0
Dependency Manager: Cocoapods
Swift Version: Objective C
Device Information (please complete the following information):

Device: iPhone 11
iOS Version: iOS 13.3.1
**Additional context**

got error message in AWSTASK

**code snippet**

 AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
    [[transferUtility uploadData:mediaData
                          bucket:[AppDefaults getS3Bucket]
                             key:key
                     contentType:mediaMimeType
                      expression:expression
               completionHandler:completionHandler] continueWithBlock:^id(AWSTask *task) {
        if (task.error) {
            NSLog(@"upload Error: %@", task.error);
        }
        if (task.result) {
            dispatch_async(dispatch_get_main_queue(), ^{
                NSLog(@"Uploading....");
            });
        }
        return nil;
    }];

**Please guide.**

**Comment by royjit** [comment]
Hi @RahulDighe 

How does your `auth` implemented? Do you use AWSMobileClient to log In?
Can you please provide some code snippet?

**Comment by RahulDighe** [comment]
Hi @royjit I am not using AWSMobileClient for login

**Here is code snippet**
[[[self.user getSession] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserSession *> * _Nonnull task) {
            // (Error handling not shown)
            if(task.error){
                NSLog(@"Error %@",task.error.userInfo[@"message"]);
                [self showErrorAlert];
            }else
                if (task.result) {
                    CustomCognitoIdentityProvider *customProviderManager = [[CustomCognitoIdentityProvider alloc]initWithTokens:@{[AppDefaults getProviderID]:task.result.idToken.tokenString}];
                    [self uploadNewPin:customProviderManager];
                    
                }
            return nil;
        }] waitUntilFinished]

**AWSCognitoCredentialsProvider**
AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc]initWithRegionType:[self getAWSRegionFromString:self->cognitoIdentityUserPoolRegion] identityPoolId:self -> cognitoIdentityPoolId identityProviderManager:customProviderManager];
    
        if (credentialsProvider.identityId != nil) {   // AWSCognitoCredentialsProvider
            // delete the old Cognito Id
            [credentialsProvider clearKeychain];
            NSLog(@"Old id cleared");
        }
    
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc]
                                              initWithRegion:[self getAWSRegionFromString:self->cognitoIdentityUserPoolRegion] credentialsProvider:credentialsProvider];
    AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;

**Comment by royjit** [comment]
The tokens get expired after a certain period of time. You need to refresh the token using the refreshtoken before it get expired. 

I suggest you  to use the latest Amplify library which takes care of all this heavy lifting for you. For more info check out:
https://docs.amplify.aws/lib/q/platform/ios

If you are starting with a new project, and looking to add auth to your app, you can use this guide to get started with auth:
https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios

If you do not already have amplify integrated in your app, you can use the following two links to get started:
**Prereq (account setup & amplify cli setup)**
https://docs.amplify.aws/lib/project-setup/prereq/q/platform/ios

**Basic project setup (if needed)**
https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios

**Comment by Naveenwebbaysys** [comment]
I have the same issue. I'm unable to find the solution. can u help me
