### ISSUE TITLE
Allow public access level for result structs initializer

### ISSUE THREAD

**Issue by aizatomar** [aws-amplify/aws-sdk-ios#2576]
**Which AWS Services is the feature request for?**
AWSMobileClient

**Is your feature request related to a problem? Please describe.**
I am trying to unit test API such as the signIn API:
```
public func signIn(username: String,
                       password: String,
                       validationData: [String: String]? = nil,
                       completionHandler: @escaping ((SignInResult?, Error?) -> Void)) {
...
}
```
 I created a protocol with the same function name and arguments and make AWSMobileClient conforms to this protocol. However, when trying to create a mock `SignInResult` object to pass into the completionHandler, I was not allowed to do so because there is an `init` function with an `internal` access that does not allow me to initialize a new `SignInResult` object.

**Describe the solution you'd like**
Can we have public access level to such result struct initializer for mocking in unit testing? Example: SignInResult, SignUpResult etc.

**Describe alternatives you've considered**
I created a struct with the exact name in my project to "expose" the init function. Didn't want to change the name intending to give familiarity to the existing API function and its arguments. However, since the module and the class name share the same name AWSMobileClient, I am not able to disambiguate between the module and the class name to access the AWSMobileClient SignInResult through `AWSMobileClient.SignInResult`. In the end, I just created the same exact struct but had to give it a different(longer) name. Not elegant but it works. Wish it can be more elegant.

**Additional context**
Current SignInResult struct.
```
public struct SignInResult {
    public let signInState: SignInState
    public let parameters: [String: String]
    public let codeDetails: UserCodeDeliveryDetails?
    
    internal init(signInState: SignInState, parameters: [String: String] = [:], codeDetails: UserCodeDeliveryDetails? = nil) {
        self.signInState = signInState
        self.parameters = parameters
        self.codeDetails = codeDetails
    }
}
```

My AWSMobileClient extension
```
func signIn(username: String,
                password: String,
                completionHandler: @escaping ((SignInResult?, Error?) -> Void)) {
        self.signIn(username: username,
                    password: password,
                    validationData: nil) {
                        (result: SignInResult?, error: Error?) in
                        completionHandler(result, error)
        }
    }
```

My unit test extension
```
func signIn(username: String,
                password: String,
                completionHandler: @escaping ((SignInResult?, Error?) -> Void)) {
        self.signIn(username: username,
                    password: password,
                    validationData: nil) {
                        (result: SignInResult?, error: Error?) in
                        let result = SignInResult(signInState: .signedIn, parameters: [:], codeDetails: nil)
                        completionHandler(result, error)
        }
    }
```
This will return me an error stating the initializer is inaccessible due to `internal` access level.

**Comment by lawmicha** [comment]
Hi @aizatomar, thanks for opening this issue, I haven't tried this out myself, but I am just wondering, could you add `@testable import AWSMobileClient` in your unit test, would it allow access to the internal constructor?

**Comment by aizatomar** [comment]
Hey @lawmicha . Apologies for the late reply. I briefly tried it and it seems I am able to access the internal constructor. Let me just make all the necessary changes and double confirm it.

**Comment by aizatomar** [comment]
Hey @lawmicha . So I refactored my codes and found out that all I needed to do was import AWSMobileClient as `@testable` in my unit test class as you suggested. I honestly didn't know this is possible at all. The codes are so much neater and more elegant now. :)

Thank you!
