### ISSUE TITLE
Question Regarding S3 and IdentityId

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/aws-sdk-ios#2577]
**State your question**
I understand S3 allows uploads to a private and protected bucket for users using their identityId. My questions is is it possible for this identityId to change for a user? Let's say the user transfers to a new device or the AWSMobileClient's cache is cleared etc. Will my users lose access to their uploaded documents?

**Which AWS Services are you utilizing?**
AWS S3 AWSMobileClient

**Comment by lawmicha** [comment]
I don't believe the identityId will ever change once the user has signed In. The identityId is from Cognito Identity Pool https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetId.html

There are some certain behaviors to keep in mind. When using AWSMobileClient, the user is immediately signed in as guest, and assigned an IdentityId. When the user authenticates and signs in for the first time, the identityId that was assigned earlier while they were a guest is now their unique IdentityId.
If the user switches devices, then will be assigned another identityId during the time which they are a guest in the app. But once they log in with the same credentials, the authenticated user's identityId will then be switched to their unique identityId that was also on the previous device.

**Comment by julien-tamade** [comment]
Ok thank you this is reassuring and good to know!
