### ISSUE TITLE
Issue with AppSync after switching between Environments in App

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/aws-sdk-ios#2579]
**Describe the bug**
I have an issue switching between amplify environments for my iOS app. I'm using Cognito Pools, AppSync, and S3. if a user is logged in to the old environment, when the new app loads AWSMobileClient still says they're logged in. I realized I can do a getAttributes call to make the app log them out automatically with a .signedOutUserPoolsTokenInvalid, but the issue is once signed back in, non of my AppSync calls fire. All the functions that implement an AppSync call just stop right when it gets to them. They don't return any error or any result so I'm assuming the calls are never even made. If the user quits the app and reopens, then appsync is working fine. 

My app initializes S3 and AppSync through the AppDelegate didFinishLaunchingWithOptions, and I'm assuming there is some sort of initialization issue from initializing with expired credentials, however, I have tried to re-initialize both S3 and AppSync at after SignIn when the MobileClient should have its new credentials, but that still doesn't work. So I'm not sure really what else to do. My AppSync initialization also depends on my S3TransferUtility's initialization.

**To Reproduce**
1. Create an app with cognito user pools and appsync. Create two amplify environments. Log in with the app on one environment, then switch the awsconfiguration.json file and rerun.

**Observed Behavior**

**Expected Behavior**
I would expect at the very least Appsync to return some sort of error instead of not being called at all. I would also Expect to be able to log in with a new environment and reinitialize the AWS services so they work. 

**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.

initialize S3:
```
    func initializeS3(){
        print("AppDelegate: Initializing S3...")
        let credentialProvider = AWSCognitoCredentialsProvider(regionType: .USEast2, identityPoolId: (awsConfig?.CredentialsProvider.CognitoIdentity.Default.PoolId)!)
//        let credentialProvider = AWSMobileClient.default()

        let configuration = AWSServiceConfiguration(region: .USEast2, credentialsProvider: credentialProvider)
            
        let tuConf = AWSS3TransferUtilityConfiguration()
        // add configuration here: tuConf.
        print("AppDelegate: Identity Pool Id: \(AWSMobileClient.default().identityPoolId)")
        AWSS3TransferUtility.register(with: configuration!, transferUtilityConfiguration: tuConf, forKey: "transfer-utility-with-advanced-options") { (error) in
            if let error = error{
                print("AppDelegate: initializeS3(): error registering s3 transfer utility")
            }
            DispatchQueue.main.async{self.initializeAppSync()}
        }
    }
```
Initialize AppSync
```
    func initializeAppSync() {
        do {
            print("AppDelegate: initializing Appsync")
            // You can choose the directory in which AppSync stores its persistent cache databases
            let cacheConfiguration = try AWSAppSyncCacheConfiguration()

            let poolsAuthProvider: AWSCognitoUserPoolsAuthProviderAsync = {
                class MyCognitoUserPoolsAuthProvider : AWSCognitoUserPoolsAuthProviderAsync {
                    func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
                        AWSMobileClient.default().getTokens { (tokens, error) in
                            print("Got Tokens")
                            if error != nil {
                                callback(nil, error)
                            } else {
                                #if DEBUG
                                print("graphQL token: \(tokens?.idToken?.tokenString ?? "")")
                                #endif
                                callback(tokens?.idToken?.tokenString, nil)
                            }
                        }
                    }
                }
                return MyCognitoUserPoolsAuthProvider()
            }()

            // so that AWSS3PreSignedURLBuilder.default() inits properly
            AWSServiceManager.default()?.defaultServiceConfiguration = AWSS3TransferUtility.default().configuration

            // Initialize the AWS AppSync configuration
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: AWSAppSyncServiceConfig(),
                                                                  userPoolsAuthProvider: poolsAuthProvider,
                                                                  cacheConfiguration: cacheConfiguration,
                                                                  s3ObjectManager: AWSS3TransferUtility.default(),
                                                                  presignedURLClient: AWSS3PreSignedURLBuilder.default())

            // Initialize the AWS AppSync client
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
            appSyncClient?.apolloClient?.cacheKeyForObject = { [$0["__typename"], $0["id"]] }
            print("Successfully initialized appsync")
            _ = CommunityManager.shared
        } catch {
            print("Error initializing appsync client. \(error)")
        }
    }
```
Init

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.12.7
 - Dependency Manager: CocoaPods
 - Swift Version : 5
 - Xcode Version: 11.4.1

**Device Information (please complete the following information):**
 - Device: iPhone 6s
 - iOS Version: 11.2.1

**Additional context**

**Relevant Console Output**

**Comment by lawmicha** [comment]
Hi @julien-tamade, thanks for reporting this issue, this looks similar to https://github.com/aws-amplify/aws-sdk-ios/issues/2389 
We'll need to investigate this further and there may be a possible bug in AWSMobileClient for the scenario: swapping userpool configuration then relaunching the app.

**Comment by julien-tamade** [comment]
@lawmicha , thanks for the response. I actually made some progress on this issue since posting. My app is successfully able to detect when a user's userpool tokens are invalid and here I added `AWSMobileClient.default().releaseSignInWait()` and then AWSMobileClient.default().signOut(). The issue here was there is a bug in releaseSignInWait causing the app to crash when using user pools [#2571](https://github.com/aws-amplify/aws-sdk-ios/pull/2571). I was able for the time being to just comment out the line `       self.tokenFetchLock.leave()` directly in the pod and everything seems to be working.

**Comment by drochetti** [comment]
@julien-tamade switching environments without restarting the app is not something that is supported. There are some unforeseen consequences of doing that automatically, such as uploads in progress, local cached data being used by the current session, etc that makes it unsafe to just switch the environment while de app is being executed.

If that's a feature you're looking to use in development time, I recommend you use enforce the app restart whenever you switch environments. You can read a more extensive discussion here https://github.com/aws-amplify/amplify-ios/issues/527

**Comment by julien-tamade** [comment]
Hi @drochetti, thank you for the response. I first experienced this issue when I had to migrate all of my users to a new environment, which was a production use case. Even though their app restarted after the update and would have been initialized with the new environment's aws config file (the old one was not in the app bundle), I guess the AWSMobileClient or maybe AWSCore still cached using the old environment and therefore Appsync initialized improperly and couldn't be reconfigured. And because Appsync would throw no errors when called, I was unable to respond to the error to then prompt the user to take action

**Comment by lawmicha** [comment]
Thanks for the response, what did your users do in this production use case? Did they have to reinstall the app to get it working? I'm going to mark this as feature request, as related to https://github.com/aws-amplify/amplify-ios/issues/527

**Comment by julien-tamade** [comment]
I think just restarting the app worked. So after they updated the app they would open it. They would be forced to create a new password as part of the environment migration and when they got logged in to their new account, the app wouldn't be able to pull their info from appsync. If they Fully restarted the app and went back in it would work but a lot of users didn't know to do that or know how so they were left confused

**Comment by royjit** [comment]
We recently released a bug to clear out any previous auth configuration if the current configuration is different. https://github.com/aws-amplify/aws-sdk-ios/pull/3853 . Could you test is the issue still exists?

**Comment by diegocstn** [comment]
@julien-tamade I'm optimistically closing this but feel free to comment if this is still an issue.
