### ISSUE TITLE
Best practice for using device biometric authentication like FaceID and TouchID

### ISSUE THREAD

**Issue by deepeshsunku** [aws-amplify/aws-sdk-ios#2583]
**State your question**

Hello, what is the best practice for using cognito authentication with device biometric authentication like FaceID and TouchID?

Want to provide an option to the user to authenticate via FaceID/TouchID for consequent logins after logging in using username/password for the first time.

**Comment by lawmicha** [comment]
Hi @deepeshsunku 
I think you will have to first get the user to login, store the credentials in their keychain, then that will enable the ability to use touchId/faceId. upon authenticating with touchId/faceId, you can retrieve the credentials from keychain and log them back in using the regular AWSMobileClient signIn method

https://developer.apple.com/documentation/localauthentication

**Comment by AllioNicholas** [comment]
> store the credentials in their keychain
@lawmicha does this mean that credentials are stored in plain text?

**Comment by lawmicha** [comment]
> > store the credentials in their keychain
> 
> @lawmicha does this mean that credentials are stored in plain text?

I don’t think so, I haven’t tried so myself but it looks like Apple provides a secure way to do it 

https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain

**Comment by pzmudzinski** [comment]
@lawmicha I assume you meant login via email/password but what about Google/Apple/Facebook sign in?
If user logs in with email and password we actually can save those in keychain and use it later for automatic login but what about social platforms? SDK does not expose anything which could be used for further relogin.

**Comment by pzmudzinski** [comment]
I assume answer is no - it's only viable for email/pwd login. Implemented it using `LocalAuthentication` framework.
