### ISSUE TITLE
S3 Downloading failing due to NSCocoaErrorDomain Code=257

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/aws-sdk-ios#2592]
**Describe the bug**
I have an app that is currently using S3 Transfer Utility to download content. Usually this works fine, but sometimes after loading my build either from testflight or from my computer, nothing will load because of `Error Domain=NSCocoaErrorDomain Code=257 "The file couldn’t be opened because you don’t have permission to view it."`. The issue occurs both downloading jpegs and downloading unity asset bundles. I've seen a similar issue in the past, but nothing was ever clearly resolved so I'm not sure what the issue is. [#2105](https://github.com/aws-amplify/aws-sdk-ios/issues/2105). the only solution seems to be to restart my phone once the app is installed. Then everything works fine.

**To Reproduce**
Create an app using cognito and s3transfer utility. Download content and try to use that content. 

**Observed Behavior**

**Expected Behavior**
I expect everything to download fine and be accessible.

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

AWSMobileClient, AWSAppSync, AWSS3TransferUtility

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.12.7]
 - Dependency Manager: Cocoapods
 - Swift Version : 5
 - Xcode Version: 11.4.1

**Device Information (please complete the following information):**
 - Device: iPhone 6s, iPhone Xr, iPhone 7plus
 - iOS Version: iOS 11.2.1, iOS 13.4

**Relevant Console Output**

```
Error Domain=NSCocoaErrorDomain Code=257 "The file couldn’t be opened because you don’t have permission to view it." UserInfo={Server=AmazonS3, Accept-Ranges=bytes, Content-Type=image/jpeg, Date=Fri, 15 May 2020 17:15:48 GMT, Last-Modified=Tue, 12 May 2020 04:38:08 GMT, x-amz-request-id=945F2E9A4611035C, Content-Length=579729, x-amz-id-2=y25fEuxNzKeKGbAT047C2gDLY9th4KGmE1Hh9jb811kyUmoH7qdBAlxb9aUXjESMip/QmQSkxtI=, Etag="075ab9e4cb74462a412eaa05da6c44d2"}
```

**Comment by drochetti** [comment]
hey @julien-tamade this seems to be an app sandboxing issue that we have no way to control when files are added to the filesystem. This post has more context around the limitations and how to workaround it, but I believe it's outside of the scope of `AWSS3TransferUtility` to handle.

https://developer.apple.com/forums/thread/96062
