### ISSUE TITLE
Getting AWS AppSync Subscriptions to Allow to Listen to any post

### ISSUE THREAD

**Issue by pbishnupuri** [aws-amplify/aws-sdk-ios#2605]
This is my current Schema (with other sections too)

type Log
@model
@auth(rules: [{allow:owner, queries: null}])
@key(name: "byUser" fields: ["userID", "createdAt"] queryField: "logsByUser")
@searchable
{
id: ID!
title: String!
user: User! @connection(name: "UserLogs")
userID: ID!
...
}

So I am trying to create a subscription anytime a log is created. However it keeps asking me for "owner"

subscription onCreateLog{
onCreateLog(owner: ""){
...
}
}

What should I change the auth to if I just want to subscribe to all logs. I still want to keep it so only the owner can mutate their own logs.

**Which AWS Services are you utilizing?**
AppSync, Amplify, iOS Graphql

**Provide code snippets (if applicable)**
Code snippet provided

**Environment(please complete the following information):**
Amplify CLI -> 4.19.0
 - Dependency Manager: Cocoapods

**Device Information (please complete the following information):**
 - iOS Version: 11.4.1

**Comment by palpatim** [comment]
Hi @pbishnupuri,

You should be able to allow public subscriptions as described [here](https://docs.amplify.aws/cli/graphql-transformer/directives#authorizing-subscriptions):

> You may disable authorization checks on subscriptions or completely turn off subscriptions as well by specifying either `public` or `off` in `@model`:
>    `@model (subscriptions: { level: public })`

**Comment by pbishnupuri** [comment]
Thank you!
