### ISSUE TITLE
AWSMobileClientExtensions: Crashing with Thread 1: EXC_BREAKPOINT

### ISSUE THREAD

**Issue by mobee-bill** [aws-amplify/aws-sdk-ios#2615]
**Describe the bug**
I am using AWSMobileClient with the hosted UI for Sign in with Apple.  On both a real device and simulator I am consistently crashing when attempting to get the credentials or identity id.  I have seemingly randomly been able to obtain these a couple times without a crash. Obtaining the token however is working without fail.
(On a simulator, the crash is `Thread 10: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`

**To Reproduce**
The following is the code I am using which occurs on button press:
```
AWSMobileClient.default().initialize { (userState, error) in
    if let error = error {
        print("error: \(error.localizedDescription)")
    }
    else if let userState = userState {
        self.view.makeToast("Apple UserState: \(userState.rawValue)")
        
        switch(userState){
            
        case .signedIn:
            AWSMobileClient.default().getTokens { (tokens, error) in
                if let tokens = tokens {
                    print("tokens: \(tokens)")
                }
            }
            AWSMobileClient.default().getIdentityId().continueOnSuccessWith(block: {_ in
                    print("identity id: \(AWSMobileClient.default().identityId ?? "nil")")
            })

            AWSMobileClient.default().getAWSCredentials { (credentials, error) in
                if let error = error {
                    print("\(error.localizedDescription)")
                } else if let credentials = credentials {
                    print("access key: \(credentials.accessKey)")
                }
            }
        case .signedOut:
            let hostedUIOptions = HostedUIOptions(scopes:["email"], identityProvider: "SignInWithApple")

            AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, hostedUIOptions: hostedUIOptions) { (userState, error) in
                if let error = error as? AWSMobileClientError {
                    print(error.localizedDescription)
                }
                if let userState = userState {
                    print("Status: \(userState.rawValue)")
                }
            }
            
        default:
            AWSMobileClient.default().signOut(options: SignOutOptions(invalidateTokens: true)) { (error) in
                print("Error: \(error.debugDescription)")
            }
            //AWSMobileClient.default().signOut()
        }
    }
}
```

**Observed Behavior**
App is crashing almost every time I try to obtain identityId or credentials

**Expected Behavior**
Obtain IdentityId and credentials without a crash.  And receive an error if something is wrong with config/setup.

**Stack Trace**
I am having trouble getting a stack trace due to xcode getting stuck on the breakpoint.

**Code Snippet**
It seems like the following line is the main culprit: (AWSMobileClientExtensions.swift line 108)
`dict[self.userPoolClient!.identityProviderName] = tokens.idToken!.tokenString!`

**Unique Configuration**
The following is my AWSConfig file
```
{
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:xxx",
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-1_xxx",
            "AppClientId": "xxx",
            "AppClientSecret": "xxx",
            "Region": "us-east-1"
        }
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "AppClientId": "xxx",
                "WebDomain": "xxx.auth.us-east-1.amazoncognito.com",
                "AppClientSecret": "xxx",
                "SignInRedirectURI": "app://",
                "SignOutRedirectURI": "app://",
                "Scopes": ["email"]
            }
        }
    }
}

```
**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient, HostedUI, Sign in with Apple via Cognito

**Screenshots**
<img width="356" alt="Screen Shot 2020-05-20 at 9 41 50 AM" src="https://user-images.githubusercontent.com/13965507/82453194-368d2d00-9a7e-11ea-8631-14e60a851ae1.png">
<img width="1105" alt="Screen Shot 2020-05-20 at 9 41 25 AM" src="https://user-images.githubusercontent.com/13965507/82453208-3b51e100-9a7e-11ea-878e-d9564f67852b.png">

**Environment(please complete the following information):**
 - SDK Version: AWSAuthCore (2.13.3)
   AWSAuthUI (2.13.3)
   AWSMobileClient (2.13.3)
   AWSUserPoolsSignIn (2.13.3)
 - Dependency Manager: CocoaPods
 - Swift Version : 5.0
 - Xcode Version: 11.4.1

**Device Information (please complete the following information):**
 - Device: iphone 8 (real), iphone 11 pro (simulator)
 - iOS Version: 13.4.1

**Comment by mobee-bill** [comment]
After adding my own conditionals in to avoid the crash, I was able to get errors and found that my identity pool had not provided my user pool as an authenticated provider.

**Comment by shaikhshoeb** [comment]
Have any one sorted this crash issue? please can someone add here a code to rectify this crash?
