### ISSUE TITLE
Empty Sign-In Screen

### ISSUE THREAD

**Issue by HighIntensity19** [aws-amplify/aws-sdk-ios#2640]
**State your question**
I am not sure why my sign-in screen is empty when using AWS Cognito?  Do I need to specify something about a username and password?  

![No_Sign_In](https://user-images.githubusercontent.com/52213875/82628353-342bef80-9bb2-11ea-894c-8555b1e4ddbe.png)

**Which AWS Services are you utilizing?**
Cognito.

**Provide code snippets (if applicable)**
**For viewDidLoad():**
```
switch(AWSMobileClient.default().currentUserState) {
        case .signedIn:
            DispatchQueue.main.async {
                print("User is logged in.")
            }
        case .signedOut:
AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, signInUIOptions: SignInUIOptions(
                                                    canCancel: true,
                                                    logoImage: UIImage(named: "Default.jpeg"),
                                                    backgroundColor: .yellow,
                                                    secondaryBackgroundColor: .orange,
                                                    primaryColor: .blue,
                                                    disableSignUpButton: false))
                                        { (signInState, error) in
                                            if let signInState = signInState {
                                                print("Sign in flow completed: \(signInState)")
                                            } else if let error = error {
                                                print("error logging in: \(error.localizedDescription)")
                                            }
                                        }
        default:
            AWSMobileClient.default().signOut()
        }
```

**For a button action:**
```
AWSMobileClient.init().showSignIn(navigationController: self.navigationController!, { (userState, error) in
                if(error == nil) {
                    DispatchQueue.main.async {
                        self.s3UrlLabel.text = "Logged in"
                    }
                }
            })
                        AWSMobileClient.default().initialize { (userState, error) in
                            if let userState = userState {
                                switch(userState) {
                                case .signedIn:
                                    DispatchQueue.main.async {
                                        self.s3UrlLabel.text = "Logged in"
                                    }
                                case .signedOut:
                                    AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, { (userState, error) in
                                        if(error == nil) {
                                            DispatchQueue.main.async {
                                                self.s3UrlLabel.text = "Logged in"
                                            }
                                        }
                                    })
                                default:
                                    AWSMobileClient.default().signOut()
                                }
                            } else if let error = error {
                                print("error: \(error.localizedDescription)")
                            }
                        }
```

**Environment(please complete the following information):**
 - SDK Version: 
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 11.4

**Comment by wooj2** [comment]
Hi @HighIntensity19,
The issue you are reporting seems to be related to this issue:
https://github.com/aws-amplify/aws-sdk-ios/issues/1082

Can you provide some additional information with regards how you are configuring cognito?

If you are getting started, with the aws mobile sdk and AWSMobileClient (our client for auth), you can check out our documentation here:
https://docs.amplify.aws/sdk/auth/getting-started/q/platform/ios

**Comment by HighIntensity19** [comment]
Thanks for your quick response! I'm trying out a few things and will report back if any work.  Going to start from scratch using the AWS SDK docs you sent (thanks).  Here is what I have in my awsconfiguration.json file, which means I think it is different from #1082:

```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-###",
                "Region": "us-east-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-2_###",
            "AppClientId": "###",
            "AppClientSecret": "###",
            "Region": "us-east-2"
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}
```

**Comment by wooj2** [comment]
Hi @HighIntensity19 ,

Sorry to lead you down the AWS SDK path.... but as of today, we have released Amplify for iOS & Android.  We recommend using the Amplify Libraries as they are use-case centric libraries which make it faster/easier to build applications.  For more info check out:
https://docs.amplify.aws/lib/q/platform/ios

If you are starting with a new project, and looking to add auth to your app, you can use this guide to get started with auth:
https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios

If you do not already have amplify integrated in your app, you can use the following two links to get started:
**Prereq (account setup & amplify cli setup)**
https://docs.amplify.aws/lib/project-setup/prereq/q/platform/ios

**Basic project setup (if needed)**
https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios
