### ISSUE TITLE
About authentication providers setting for Sign in with Apple

### ISSUE THREAD

**Issue by wxforgb** [aws-amplify/aws-sdk-ios#2647]
**State your question**
In our service, we use Federated Identities only. We obtained Apple services id from apple developer site and set it to [Federated Identities]-[Authentication providers] - [Apple]Tab - [Apple Services ID].

This setting is ok In our web site, but in our native app we got a error message like this
"Token is not from a supported provider of this identity pool."

If we set app's Bundle Identifier to authentication providers instead of Apple Services ID, It would be working. But our web site will become bad.
Is there method to solve this problem?
Thanks for your help with this!

(Apple requires that services id need be different from Bundle Identifier.)

**Which AWS Services are you utilizing?**
Cognito Federated Identities

**Comment by lawmicha** [comment]
@wxforgb what APIs are you trying to use with the SDK and how are you setting up the native app to get the error message?
