### ISSUE TITLE
"risk of termination" because not calling UIApplication.endBackgroundTask(_:)

### ISSUE THREAD

**Issue by OceanBuzz** [aws-amplify/aws-sdk-ios#2648]
https://github.com/aws-amplify/aws-sdk-ios/blob/71a3a35b4622452d4a25418596a6151b31a791f2/AWSPinpoint/AWSPinpointSessionClient.m#L348

self.bgTask is being overwritten in some cases on line 348 without being used in a call to UIApplication.endBackgroundTask(_:). You can see this by backgrounding and foregrounding the app a few times with less than 5 seconds between each.

iOS logged in the console:
[BackgroundTask] Background Task 13 ("com.amazonaws.AWSPinpointSessionBackgroundTask"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by diegocstn** [comment]
The PR https://github.com/aws-amplify/aws-sdk-ios/pull/3084 was merged, this issue will be closed after a release with the fix is out.

**Comment by palpatim** [comment]
We released this on 2.18.1
