### ISSUE TITLE
[NSTimer invalidate] called from wrong thread

### ISSUE THREAD

**Issue by OceanBuzz** [aws-amplify/aws-sdk-ios#2649]
https://github.com/aws-amplify/aws-sdk-ios/blob/71a3a35b4622452d4a25418596a6151b31a791f2/AWSPinpoint/AWSPinpointSessionClient.m#L278

On line 301 endCurrentSession is called from a background thread, which causes [self.bgTimer invalidate] to be called on that background thread, rather than the thread it was created on, the main thread, on line 357. 

From apple docs: "You must send this message from the thread on which the timer was installed. If you send this message from another thread, the input source associated with the timer may not be removed from its run loop, which could prevent the thread from exiting properly."  https://developer.apple.com/documentation/foundation/nstimer/1415405-invalidate?language=objc

**Comment by OceanBuzz** [comment]
This is overall a concerningly complex threading model throughout. How about a simpler approach, like creating a single serial background queue for all internal work (at least on the subject of analytics and/or pinpoint) and dispatch_async to and from that serial queue and the main queue? That way you wouldn't need all the @synchronize() blocks, no code would ever be run by two different threads, and your internal work would be logically sequential. If there are cases where you need to be able to cancel internal work too, you can use a serial background NSOperationQueue instead.

**Comment by palpatim** [comment]
@OceanBuzz Thanks for the report, the investigation, and the suggestion. We're looking at improving the threading model, among other things, in this SDK, and will update when we have more info. In the meantime, we'll see if we can patch this issue without causing any downstream impacts.

**Comment by palpatim** [comment]
@OceanBuzz 

We've investigated this, with all of the risks associated with mucking around in this threading code, we're reluctant to take this on without some bug being tied to this.

For now, we're going to resolve this as a "won't fix" and revisit when we take on the larger issue of concurrency handling in the AWS Mobile SDKs.
