### ISSUE TITLE
Line of code after return statement, never executed

### ISSUE THREAD

**Issue by OceanBuzz** [aws-amplify/aws-sdk-ios#2650]
https://github.com/aws-amplify/aws-sdk-ios/blob/71a3a35b4622452d4a25418596a6151b31a791f2/AWSPinpoint/AWSPinpointSessionClient.m#L296

These two lines are after the return statement, and so are never executed.

**Comment by palpatim** [comment]
Thanks for the report @OceanBuzz. We've released the fix for this on https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.15.0
