### ISSUE TITLE
Enter foreground but never endBackgroundTask

### ISSUE THREAD

**Issue by OceanBuzz** [aws-amplify/aws-sdk-ios#2651]
https://github.com/aws-amplify/aws-sdk-ios/blob/71a3a35b4622452d4a25418596a6151b31a791f2/AWSPinpoint/AWSPinpointSessionClient.m#L149

When the app enters foreground with a backgroundTask still active, it should end it, otherwise iOS writes warnings to the console.

So add something like:
    if (self.bgTask != UIBackgroundTaskInvalid) {
        [[UIApplication sharedApplication] endBackgroundTask:self.bgTask];
        self.bgTask = UIBackgroundTaskInvalid;
    }

**Comment by diegocstn** [comment]
Hi @OceanBuzz,
thanks for reporting this issue. 
Looks like the SDK is not properly marking a previously created background task as completed when the app transition back from background to foreground _before_ the scheduled `NSBlockOperation`, used for ending and processing the pending Pinpoint session, starts.

**Comment by diegocstn** [comment]
The PR https://github.com/aws-amplify/aws-sdk-ios/pull/3084 was merged, this issue will be closed after a release with the fix it out.
