### ISSUE TITLE
Attributes from targetingClient should return values from remote (even after reinstall).

### ISSUE THREAD

**Issue by mihaigabriel1992** [aws-amplify/aws-sdk-ios#2652]
CurrentEndpointProfile from targetingClient returns empty list for when calling attribute forKey. 

1. Added an attribute to targetingClient.
2. Retrieve attribute and endpoint id - it exists
3. Reinstall app
4. Retrieve attribute and endpoint id - attribute is missing but the endpoint id is the same

Making the HTTP request to retrieve endpoint I can see the attributes there.
Also if I change the attributes from HTTP put it doesn't change in the app.

**Expected Behavior**
I should be able to retrieve the attributes remotely and have them after reinstall and also if I change the attributes manual I should be able to see the changes in the app.

**Stack Trace**
Please provide a stack trace if applicable e.g. a crash is occurring.

**Code Snippet**
`
pinpointTargetingClient?.addAttribute(categories,
            forKey: "categories")
        pinpointTargetingClient?.updateEndpointProfile()
let categories = profile?.attribute(forKey: "categories") ?? []`

Pinpoint SDK.
 - SDK Version: 2.13.2
 - Dependency Manager: Cocoapods
 - Swift Version : 5
 - Xcode Version: 11.4

**Device Information (please complete the following information):**
 - Device: iPhone 8
 - iOS Version: 11.4.1
 - Specific to simulators: iPhone 11

**Comment by lawmicha** [comment]
Hi @mihaigabriel1992, thanks for reporting this issue. I was able to reproduce this and what I've noticed is that
- when updating the endpoint, the endpoint is persisted locally in user defaults. this is retrieved across app deletes [[link](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSPinpoint/AWSPinpointTargetingClient.m#L153)]
- on app delete, and reinstall, the endpoint is pulled from user defaults, and attributes/metrics are removed before it gathers current app information to populate the endpoint profile [[link](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSPinpoint/AWSPinpointTargetingClient.m#L78-L83)] 

What this means is that the current behavior of `currentEndpointProfile` does not represent the data from the pinpoint service, it is gathered data that can be used to update the endpoint with, ie. current retrievable demographics information, optOut value derived from the app settings and configuration, attributes and metrics populated from the global metrics and attributes.

`pinpointTargetingClient?.addAttribute(categories, forKey: "categories")` is adding the attribute to global attributes in memory, which is the reason why you are able to see attributes returned from the current endpoint. 

To better identify what a solution would be for your use case, could you expand on why require the attributes from the endpoint profile across an app reinstall?

**Comment by mihaigabriel1992** [comment]
@lawmicha Thank you for your reply. I encountered this problem when I wanted to add categories on a user and filter the notifications based on that category. I have a server that sends notification to all the user based on the categories selected by them. I also need to retrieve them on the device because the user can delete/add more categories and I didn't want to add authentication logic. Hope this makes sense.

Regards
