### ISSUE TITLE
Deep linking with with Pinpoint using SwiftUI / SceneDelegate

### ISSUE THREAD

**Issue by AlexKashi** [aws-amplify/aws-sdk-ios#2669]
**State your question**
Is it possible to receive deep links from notifications sent by pinpoint when using SceneDelegate / SwiftUI? 

Whenever a push notification is opened, the function

 (void)handleNotificationReceived:(UIApplication *) app
                  withNotification:(NSDictionary *) userInfo
  shouldHandleNotificationDeepLink:(BOOL) shouldHandleNotificationDeepLink

is not called. The app opens, although no callbacks are triggered for handling deep linking. 

**Which AWS Services are you utilizing?**
AWSPinpoint

**Provide code snippets (if applicable)**

https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios
https://github.com/awsdocs/amazon-pinpoint-developer-guide/blob/master/doc-source/mobile-sdk-ios-deep-linking.md

*Environment(please complete the following information):**
 - SDK Version: 12.13.4
 - Dependency Manager: CocoPods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: iOS 13.4

**Comment by palpatim** [comment]
@AlexKashi To the best of my knowledge, iOS 13 & SwiftUI support didn't change the way notification delegate methods are invoked--you still have to implement them in your AppDelegate and register pinpoint to handle notification events, as [noted in the SDK docs](https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios#connect-to-your-backend).

Can you confirm that you are confirming notification authorization, registering for remote notifications, and registering Pinpoint to handle remote notifications as noted in those docs? (Make sure to implement the `application(_:,didFailToRegisterForRemoteNotificationsWithError:)` method as well to discover whether push notification registration encountered any issues.)

**Comment by AlexKashi** [comment]
My AppDelegate is set up, and I can receive notifications just fine, however, when A user presses a notification with the body: 

[AnyHashable("data"): {
    pinpoint =     {
        deeplink = "appname://conversation";
    };
}, AnyHashable("aps"): {
    alert =     {
        body = "message";
        title = Appname;
    };
    "content-available" = 1;
    "mutable-content" = 0;
}]

- (void)handleNotificationReceived:(UIApplication *) app
                  withNotification:(NSDictionary *) userInfo
  shouldHandleNotificationDeepLink:(BOOL) shouldHandleNotificationDeepLink 

is not called, and subsequently 

 (void)handleNotificationDeepLinkForNotification:(NSDictionary*) userInfo

is not called


When the notification is original received with the app in the background 

- (void)handleNotificationReceived:(UIApplication *) app
                  withNotification:(NSDictionary *) userInfo
  shouldHandleNotificationDeepLink:(BOOL) shouldHandleNotificationDeepLink

is called, and responds with "Received notification with app on background."


I do see in the console when I turn on verbose logging and receive a notification the following messages get printed, not sure if related. 

2020-05-29 09:59:19:978 Appname[5703:1403230] No valid Pinpoint Push payload found
2020-05-29 09:59:19:979 Appname[5703:1403230] Received notification with app on background.
2020-05-29 09:59:19:979 Appname[5703:1403230] Cannot determine event type from Push payload
2020-05-29 09:59:19:979 Appname[5703:1403230] Not valid Pinpoint push notification

It seems like there are some differences between handling push notifications in SwiftUI/SceneDelegate, however it may be constrained to user routing only https://nalexn.github.io/swiftui-deep-linking/ although, as it stands I don't receive any callbacks in AppDelegate or SceneDelegate that I received a deep link

**Comment by AlexKashi** [comment]
Fixed by the following: 

```
typealias NotificationPayload = [AnyHashable: Any]

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, UNUserNotificationCenterDelegate{

    // AppDelegate Methods
    ....
    

    // Access SceneDelegate And control view state through an EnviromentObject 
    private func sceneDelegate(_ application: UIApplication) -> SceneDelegate? {
        return application.windows
            .compactMap({ $0.windowScene?.delegate as? SceneDelegate })
            .first
    }

    // MARK: Handle Push Notification Press
    public func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        print(TAG, "Tapped Notification")
        let userInfo = response.notification.request.content.userInfo
        guard let payload = userInfo[AWSDataKey] as? NotificationPayload,
            let pinpoint = payload[AWSPinpointKey] as? NotificationPayload,
            let deeeplink = pinpoint["deeplink"] as? String,
            let url = URL(string: deeeplink) else{
                completionHandler()
                return
        }
        
        handleURL(url)
        completionHandler()
    }
}
```
