### ISSUE TITLE
AWS cognito Drop-In

### ISSUE THREAD

**Issue by Wazambe** [aws-amplify/aws-sdk-ios#2670]
With SWIFT for IOS, I Incorporated the AWS Auth Drop-In view AWSSignInViewController as the starting point to what i hope to be a nice app. So all seems to be working well.

Except when the VC presents, an error is generated that it is presenting without basically conforming to the superview / Navigation controller's layout

"Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x7fe33101dc00; frame = (4 4; 271 142); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x600001cd9a70>; layer = <CALayer: 0x6000012e7040>; contentOffset: {0, 0}; contentSize: {271, 0}; adjustedContentInset: {0, 0, 0, 0}; dataSource: (null)>"

I checked and the reference to the presenting View Controller is passed as part of the config.

**Comment by royjit** [comment]
Hi @Wazambe 

Can you please provide a code snippet on how you are presenting the sign in view controller in your app.

**Comment by Wazambe** [comment]
Good day

Thank you so much for the response

I'm basically just using the .presentViewController method on the initial
Nav controller, as per a sample/demo I got somewhere

Regards

Mark

*private*  *func* presentAuthUIViewController() {

        *let* config = AWSAuthUIConfiguration()

            config.enableUserPoolsUI = *true*

          //config.addSignInButtonView(class: AWSFacebookSignInButton)

          //config.addSignInButtonView(class: AWSGoogleSignInButton.self)

            config.backgroundColor =  colorLiteral(red: 0, green:
0.4510560036, blue: 0.752143681, alpha: 1)

            config.font = UIFont (name: "Helvetica Neue", size: 12)

            config.logoImage = UIImage(named: "Face.png")

            config.isBackgroundColorFullScreen = *false*

            config.canCancel = *true*

            config.secondaryBackgroundColor = .white



        AWSAuthUIViewController.presentViewController(

         with: *self*.navigationController!,

            configuration: config, completionHandler: { (provider:
AWSSignInProvider, error: Error?) *in*

                *if* error == *nil* {

                    print("SignIn succeeded.")

                       *self*.getUserAtributes()

                       *self*.checkUserLogIn(*self*.finalSignInCheck)

                       *self*.finalSignInCheck = *true*

                } *else* {

                    print("End user faced error while loggin in, take any
required action here... " + error.debugDescription)

                }

        })

    }
