### ISSUE TITLE
Null Initialization Vector Used for Symmetric Encryption

### ISSUE THREAD

**Issue by mmathewsTableau** [aws-amplify/aws-sdk-ios#2679]
The use of CCCrypt in [AWSMobileAnalyticsEncryptedBufferedReader](https://github.com/aws-amplify/aws-sdk-ios/blob/6ab2982040eaca984eab38e311b98c3b9227b773/AWSMobileAnalytics/Internal/AWSMobileAnalyticsEncryptedBufferedReader.m#L102) passes in a null value for the Initialization Vector. Rotating new values for the Initialization Vector will ensure a different output which makes it impossible for an attacker to see that the encrypted data hasn't changed.

**Comment by royjit** [comment]
Thank you for reaching out regarding this issue. We agree with your analysis that a fixed IV results in deterministic encryption, which will reveal plaintext equivalence. The AWSMobileAnalytics SDK was deprecated in Dec 2018, and replaced by AWS Pinpoint's analytics features. Please use AWS Pinpoint for analytics going forward.

**Comment by mmathewsTableau** [comment]
Okay, sounds good. thanks for the response
