### ISSUE TITLE
Set Session for Cognito custom auth response

### ISSUE THREAD

**Issue by srgray** [aws-amplify/aws-sdk-ios#2682]
**State your question**
Is it possible to set the Session value on a Cognito custom auth response? I think we have done it with the Android SDK (see code snippet below). But the iOS SDK seems to not give us the same access.

Use case: We initiate the Cognito custom auth process with a manual HTTP POST (i.e. NOT using Cognito library) so that we can persist the Session between app launches. So, we need to be able to manually set the Session for the custom auth response and not rely on Cognito library's session management.

**Which AWS Services are you utilizing?**
Cognito user pools

**Provide code snippets (if applicable)**
See Android code snippet thats sends a Custom Auth challenge response with the Session value that we specify:

```
        val client = AmazonCognitoIdentityProviderClient(AWSMobileClient.getInstance())
        val providerKey =
            "cognito-idp.${client.regions.getName()}.amazonaws.com/${userPool.userPoolId}"
        val userPool = CognitoUserPool(context, AWSMobileClient.getInstance().configuration)
        val user = userPool.getUser(userName)
        val authChallengeRequest = RespondToAuthChallengeRequest()
        val map = HashMap<String, String>()
        map[CognitoServiceConstants.CHLG_RESP_ANSWER] = authCode
        map[CognitoServiceConstants.AUTH_PARAM_USERNAME] = userName
        authChallengeRequest.session = sessionToken
        authChallengeRequest.challengeName = "CUSTOM_CHALLENGE"
        authChallengeRequest.clientId = userPool.clientId
        authChallengeRequest.challengeResponses = map
        return Single.create { subscriber ->
            user.respondToChallenge(authChallengeRequest, object : AuthenticationHandler {
                override fun onSuccess(
                    userSession: CognitoUserSession?,
                    newDevice: CognitoDevice?
                ) {
                    AWSMobileClient.getInstance().federatedSignIn(
                        providerKey,
                        userSession?.idToken?.jwtToken,
                        object : Callback<UserStateDetails> {
                            override fun onResult(result: UserStateDetails?) {
                                subscriber.onSuccess(ResponseMarshaller(SignInResult.DONE, null))
                            }
                            override fun onError(e: Exception?) {
                                subscriber.onSuccess(ResponseMarshaller(SignInResult.DONE, null))
                            }
                        }
                    )
                }
                override fun onFailure(exception: java.lang.Exception?) {
                    if (exception != null) {
                        subscriber.onError(exception)
                    }
                }
                override fun getAuthenticationDetails(
                    authenticationContinuation: AuthenticationContinuation?,
                    userId: String?
                ) {
                }
                override fun authenticationChallenge(continuation: ChallengeContinuation?) {}
                override fun getMFACode(continuation: MultiFactorAuthenticationContinuation?) {}
            }, true).run()
        }
```

**Environment(please complete the following information):**
 - SDK Version: 2.13.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Comment by wooj2** [comment]
Hi @srgray ,

Sorry for the delay.  Looking at the provided Android code, theoretically, there should be nothing that stops you from doing this on iOS, but please be advised that your use case is not officially supported.

Can you be more specific about where you are having trouble getting access to update the session token?

The following is a link to the AWSCognitoIdentityProviderRespondToAuthChallengeRequest which contains the `session` property.

https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSCognitoIdentityProvider/Classes/AWSCognitoIdentityProviderRespondToAuthChallengeRequest.html#/c:objc(cs)AWSCognitoIdentityProviderRespondToAuthChallengeRequest(py)session

**Comment by srgray** [comment]
It's been a while since I looked at this, but I believe the issue we were having is that the `session` property was hidden from us due to Swift access control (maybe it was an `internal` property and thus not accessible from outside the SDK?)

**Comment by palpatim** [comment]
@srgray As far as we can see from both the docs that @wooj2 linked, and a quick sanity test trying to access this in code, `session` is read/write.

```swift
let authChallengeRequest = AWSCognitoIdentityProviderRespondToAuthChallengeRequest()!
authChallengeRequest.session = "my-session-token"
```

Please let us know if you do remember what blocked you from this use case.
