### ISSUE TITLE
Sign In Screen can't be showed due to AWSAuthUI Dependency Error

### ISSUE THREAD

**Issue by destantifw** [aws-amplify/aws-sdk-ios#2724]
I'm trying to connect my apps to google sign in using AWS. But, the sign in screen can't be showed because AWS keep producing error like 
this : 

> AWSAuthUI dependency is required to show the signIn screen. Please import the dependency before using this API

my code to show signin screen:
`AWSMobileClient.default().showSignIn(navigationController: self.navigationController!,)`

pods:
![image](https://user-images.githubusercontent.com/14884055/84351604-e9682b00-abe5-11ea-8572-bdd19e1a1230.png)

How to solve this problem?

**Comment by wooj2** [comment]
Hi @destantifw ,

Looks like you're trying to use AWSMobileClient w/ Drop-in UI to do a federated sign in with google?   If so, this is not supported with the native drop-in ui.  Instead, you are required to use the hosted UI.  If you continue to use AWSMobileClient, our documentation can be found here:
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios

That being said, AWSMobileClient is now considered to be dated and is being replaced by Amplify.
Amplify's Auth category's documentation can be found here:
https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios
