### ISSUE TITLE
Parameters dictionary is empty with SignInResult with signedIn state

### ISSUE THREAD

**Issue by saravr** [aws-amplify/aws-sdk-ios#2741]
**State your question**

What values are returned in the SignInResult "parameters"? I see it empty. I was hoping it may contain the email address used in the signin (so that I can avoid doing an async getAttributes).

**Which AWS Services are you utilizing?**

Cognito User Pool

**Provide code snippets (if applicable)**

```
        AWSMobileClient.default().signIn(username: username, password: password) { (signInResult, error) in {
             ...
            switch(signInResult.signInState) {
            case .signedIn:
                print("User is signed in.")
                // Trying to see any useful information in signInResult.parameters (seeing it empty)
             ....
```
**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]  AWSMobileClient Pod version 2.12.7
 - Dependency Manager: [e.g. Cocoapods, Carthage] cocoapods
 - Swift Version : [e.g. 4.0] 5

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] iPhone 11 simulator
 - iOS Version: [e.g. iOS 11.4] 13.5
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by royjit** [comment]
Hi @saravr 
Thank you for reaching out to us. The `parameters` property in the `SignInResult` is used to return any additional info back to the caller after a successful signIn operation. For example, in case of custom authentication flow, extra information can be passed back to the callback after sign in completes. User attributes are not returned in this property and you have to use api like `AWSMobileClient.default().getUserAttributes` to fetch those information.
