### ISSUE TITLE
Is it possible to set timeout and maximum retry in AWSCognitoIdentityUser?

### ISSUE THREAD

**Issue by cjeremylin** [aws-amplify/aws-sdk-ios#2755]
**State your question**

We are using [CognitoYourUserPoolsSample](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Objective-C) currently. 

There is a problem when we use

 `[[self.user getDetails] continueWithBlock`

 to get User's information back. If networking is unavailable, we have to wait for 4 minutes until this request complete. We can get the following error message print in console every 60 seconds.

`CognitoYourUserPoolsSample[885:433951] Task <67A54CCB-6CFB-41B3-AE6C-34F96670C782>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102,`

But it did not return in this function until 4 minutes (might be 4 times max-retry * 60 seconds timeout ). At this moment, we implement an alternative to add cancel with timer if this function did not response in 60 seconds. We would like to notify user there might be a network issue as soon as possible or fail fast, instead of waiting for 4 minutes and getting the timeout error in the API invocation. 

We understand that might be kind of httpClient under the hood. What we want to know is it possible to modify the request timeout and maximum retry for kind of wrapped class. For example,  [AWSCognitoIdentityUser](https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m)
  
**Which AWS Services are you utilizing?**
Amazon Cognito 

**Provide code snippets (if applicable)**
`[[self.user getDetails] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserGetDetailsResponse *> * _Nonnull task) {  } `

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29] 2.12.3
 - Dependency Manager: [e.g. Cocoapods, Carthage] Cocoapods
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] iPhone11
 - iOS Version: [e.g. iOS 11.4] iOS 13.5.1
 - Specific to simulators:

**Comment by palpatim** [comment]
@cjeremylin For new projects, we recommend you use the [Amplify Auth category](https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios], which handles much of the work of configuring and managing connections for you. The Cognito User Pools SDK is still supported with bug fixes and security updates, but we won't be adding new features to that SDK.

For your specific question, the `AWSServiceConfiguration` that we use to configure the underlying SDKs expose both a `timeoutIntervalForRequest` and a `timeoutIntervalForResource` value that might help you achieve the behavior you're after. You can find more information in [the AWS Mobile SDK API reference](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/).

**Comment by saravr** [comment]
@palpatim I am using Amplify 1.5.0. Where do I configure the timeout / retries for sign In/sign up etc?
I tried setting it like below

        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USWest2, identityPoolId: Constants.IDENTITY_POOL_ID)
        configuration = AWSServiceConfiguration(region: .USWest2, credentialsProvider: credentialsProvider)
        configuration.allowsCellularAccess = true
        configuration.maxRetryCount = 1
        configuration.timeoutIntervalForRequest = 1
        configuration.timeoutIntervalForResource = 1
        AWSServiceManager.default().defaultServiceConfiguration = configuration

and

            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSS3StoragePlugin())
            try Amplify.configure()

But I still the login requests take about 4 mins to finally fail (when network is disabled)

**Comment by mygzi** [comment]
Discovered a workaround for this: 

Your first request will cause the AWS SDK to fetch a Cognito ID on your behalf, based on the `credentialsProvider` you passed in. This will indeed perform 3 retries after an initial failure, resulting in the observed 4 minute delay. Various setting referenced by @palpatim above - e.g. `timeoutIntervalForRequest` - do not impact this delay as they don't appear to apply to this implicit Cognito request. 

Instead, if you initiate an explicit Cognito ID request *before* launching your first request, you can implement your own timeout and declare AWS unreachable before proceeding. 

```
var cognitoTimer : DispatchSourceTimer?
let credentialsProvider = AWSCognitoCredentialsProvider(regionType: cognitoRegion, identityPoolId: identityPoolId)
// explicit Cognito ID request
let task = credentialsProvider.getIdentityId().continueWith(block: { task in
    cognitoTimer?.cancel()
    // check task.error and task.result, proceed with AWS requests if successful
}
// use a timer, e.g. DispatchSourceTimer, to cancel the task after your desired timeout
cognitoTimer = DispatchSource.makeTimerSource()
cognitoTimer?.schedule(deadline: .now() + 30)
cognitoTimer?.setEventHandler { [weak self] in
    task.result?.cancel()
    // AWS is unreachable :-(
}
cognitoTimer?.resume()
```

If you don't wait to launch your first request, you will find a 5 second(!) timeout baked into the SDK:

```
error.domain // com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper
error.localizedDescription // "Obtaining an identity id in another thread failed or didn't complete within 5 seconds."
```
