### ISSUE TITLE
Using aws-amplify/aws-sdk-ios in another SDK 

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [aws-amplify/aws-sdk-ios#2756]
Integrate aws-amplify/aws-sdk-ios with 2 different API keys, one which is used by iOS SDK and one which is used by the iOS app itself using the same SDK to trace logs. Will this cause any conflicts like other logging frameworks ?

[app] ---uses---> aws-amplify/aws-sdk-ios SDK
[app] ---uses---> my custom SDK
[my custom SDK] ---uses---> aws-amplify/aws-sdk-ios SDK

Will the above be supported without any issues or clashes ?

**Comment by wooj2** [comment]
Hi,

I'm having some trouble understanding what you are asking.  I'm not sure what you mean by "one is used by the iOS app itself using the same SDK to trace logs".  Maybe it might help if you can follow one of the templates we have put together here:
https://github.com/aws-amplify/aws-sdk-ios/issues/new/choose

Thank you

**Comment by deepesh-vasthimal-cko** [comment]
Hi 

What i meant was can i use the amplify/aws-sdk-ios SDK both in the iOS app and the SDK at the same time without having conflicts ? . 

Thanks

**Comment by royjit** [comment]
Duplicate issue - https://github.com/aws-amplify/aws-sdk-ios/issues/2784
Feel free to re-open the issue if this is a separate issue.
