### ISSUE TITLE
Could not find module 'AWSMobileClient' for target 'arm64-apple-ios'

### ISSUE THREAD

**Issue by ravikanthAtGeospark** [aws-amplify/aws-sdk-ios#2776]
i am getting error , while adding SDK inside my Custom SDK 
`Could not find module 'AWSMobileClient' for target 'arm64-apple-ios'; found: x86_64-apple-ios-simulator, x86_64`

<img width="294" alt="Screenshot 2020-06-22 at 11 51 11 AM" src="https://user-images.githubusercontent.com/43139135/85255274-92811200-b47f-11ea-810a-e42605c9bc80.png">

**Comment by palpatim** [comment]
@ravikanthAtGeospark Sorry you're having problems with this, but we'll need more details to help. Can you explain your setup a bit more?

- How are you obtaining and including the frameworks: CocoaPods, Carthage, direct import, build-from-source?
  - If the latter, from where do you download the frameworks?
  - If you're building from source, what mechanism are you using to kick off the build & then import into your project?
- What version of Xcode are you using?

**Comment by ravikanthAtGeospark** [comment]
How are you obtaining and including the frameworks: CocoaPods, Carthage, direct import, build-from-source?
    I am using CocoaPods 
If the latter, from where do you download the frameworks?
  i have take framework from pod folder.
If you're building from source, what mechanism are you using to kick off the build & then import into your project?
Create a folder imported the framework ,
What version of Xcode are you using?
Xcode 11.5

**Comment by palpatim** [comment]
If you're using CocoaPods, it will automatically instrument your project--you shouldn't take frameworks from the Pods folder. Further, you need to make sure you're opening the XCWorkspace, **NOT** the .xcodeproj file. See https://github.com/aws-amplify/aws-sdk-ios#cocoapods for more details.

**Comment by jim3ex** [comment]
Could not find module 'AWSMobileClient' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64

Standard Cocoapods install. Xcode 12.2 - I believe this is related to new Apple arm64 based Macs. Is there a solution?

**Comment by granchenkooleg** [comment]
I tried on a Mac with Intel and this finds the module, but with M1 I couldn't find the module
