### ISSUE TITLE
Using aws-amplify/aws-sdk-ios in app and also custom SDK used by that app. 

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [aws-amplify/aws-sdk-ios#2784]
**State your question**
Can I use aws-amplify/aws-sdk-ios SDK in my app and also inside custom SDK which i have written. meaning there are 2 instances of aws-amplify/aws-sdk-ios running one in app and one in my custom SDK. Will this not cause a clash ? 

[app] ---uses---> aws-amplify/aws-sdk-ios SDK
[app] ---uses---> my custom SDK
[my custom SDK] ---uses---> aws-amplify/aws-sdk-ios SDK

**Which AWS Services are you utilizing?**
aws-amplify/aws-sdk-ios

**Provide code snippets (if applicable)**
N/A 

**Environment(please complete the following information):**
NA

**Device Information (please complete the following information):**
 NA

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by palpatim** [comment]
Generally, iOS projects resolve dependencies to a single binary. If you have custom frameworks that depend on the AWS SDK for iOS, it's best to have each of them rely on the SDK, but not package it directly with the framework. The host app would be responsible for importing a single binary version that all of the app dependencies would use.

Do note that the SDK expects to be configured once, and shares that configuration with all use cases. It's certainly possible to configure and run multiple AWS services from the SDK (e.g., using AWSMobileClient for auth, Pinpoint for analytics, and Lex for interactions, for example).

Hope this helps.

**Comment by palpatim** [comment]
If I understand your description, the configuration you describe will not work: the SDK expects to be run with at most one user at a time. Depending on your configuration, this might be a "guest" or "unauthenticated" user, or a user that has been authenticated via one of the various supported authN mechanisms.

I encourage you to look closely at your use cases and see if you really need two different client-side users. You might be able to accomplish your desired outcomes by, for example, triggering Lambda functions from various service calls, which emit notifications to SNS topics that other services subscribe to and use to process their notifications. Not knowing anything about your use case, I have to say I'm hard pressed to think of a time when I'd want a totally separate client-side authentication context running alongside my user's auth context.

**Comment by bimal-geospark** [comment]
> Generally, iOS projects resolve dependencies to a single binary. If you have custom frameworks that depend on the AWS SDK for iOS, it's best to have each of them rely on the SDK, but not package it directly with the framework. The host app would be responsible for importing a single binary version that all of the app dependencies would use.
> 
> Do note that the SDK expects to be configured once, and shares that configuration with all use cases. It's certainly possible to configure and run multiple AWS services from the SDK (e.g., using AWSMobileClient for auth, Pinpoint for analytics, and Lex for interactions, for example).
> 
> Hope this helps.



> Generally, iOS projects resolve dependencies to a single binary. If you have custom frameworks that depend on the AWS SDK for iOS, it's best to have each of them rely on the SDK, but not package it directly with the framework. The host app would be responsible for importing a single binary version that all of the app dependencies would use.
> 
> Do note that the SDK expects to be configured once, and shares that configuration with all use cases. It's certainly possible to configure and run multiple AWS services from the SDK (e.g., using AWSMobileClient for auth, Pinpoint for analytics, and Lex for interactions, for example).
> 
> Hope this helps.

This is exactly what I am doing to achive a connection from SDK to AWSIOT, but createKeysAndCertificate function returns always nil , so unable to create key ans certificate, and do further action.

**Comment by royjit** [comment]
@bimal-geospark 
Your issue seems to be specific to AWSIoT, could you please create a new issue [here](https://github.com/aws-amplify/aws-sdk-ios/issues/new/choose) and provide us more details to debug the issue,
