### ISSUE TITLE
Crash in AWSMobileClient, in the signIn method

### ISSUE THREAD

**Issue by radianttap** [aws-amplify/aws-sdk-ios#2814]
**Describe the bug**
Using Cognito, AWSMobileClient 2.13.6. 
We have a form to input mobile number, which calls the public method `signIn(username: String, password: String, validationData: [String: String]? = nil, completionHandler: @escaping ((SignInResult?, Error?) -> Void)`. It crashes on line with `user!.getSession(...)` because `user` is force-unwrapped while it's still `nil`.

**To Reproduce**
1. Make a call to said signIn method
2. User's mobile number is taken in the form and we call `AWSMobileClient.signIn` method sending said phone number (full form, with international calling code) as username and NSUUID string as password.

**Observed Behavior**
Crashes.

**Expected Behavior**
Should go through. This was working in 2.13.0

**Stack Trace**
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000010170e8d0 in AWSMobileClient.signIn(username:password:validationData:completionHandler:) at /.../Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift:211

```

**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.

**Unique Configuration**
I am not sure what I should provide here. It's a mobile app + service, using Cognito for user authentication and token management.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient

**Screenshots**
<img width="1676" alt="awsmobileclient-implicit-user-unwrapping-crash" src="https://user-images.githubusercontent.com/80697/86019460-eca54880-ba26-11ea-8cd0-24eb2580539c.png">

**Environment(please complete the following information):**
 - SDK Version: AWSMobileClient 2.13.6. 
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2
 - Xcode Version: 11.5

**Device Information (please complete the following information):**
 - Device: iPhone 11 Pro
 - iOS Version: iOS 13.5.1
 - Specific to simulators:

**Additional context**

**Relevant Console Output**

**Comment by radianttap** [comment]
My bad, I used wrong config (with no details for UserPool).

Still, it's a crashing issue in the AWSMobileClient and forced-unwrap on the `user` should not be done.

**Comment by Simer-ios** [comment]
I am also facing same issue , Anybody solved it , Please help me.

**Comment by alexandrahably** [comment]
This issue is still causing a crash if a wrong config is used. Could you please avoid the force unwrapping?
