### ISSUE TITLE
Uploading to AppStore connect with version 2.13.4 fails with invalid mach-o format

### ISSUE THREAD

**Issue by eito** [aws-amplify/aws-sdk-ios#2817]
**Describe the bug**
Uploading a build of our app to AppStore Connect fails with the following error: 

> Invalid Mach-O Format. The Mach-O in bundle "FieldMaps.app/Frameworks/AWSCore.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

> Invalid Mach-O Format. The Mach-O in bundle "FieldMaps.app/Frameworks/AWSPinpoint.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

I have verified that the strip-frameworks.sh script is run after the embed libraries phase.

**To Reproduce**
1. Archive an app that embeds AWSCore/AWSPinpoint
2. Attempt to validate/upload to AppStore Connect

**Observed Behavior**
Fails with invalid mach-o format

**Expected Behavior**
Should upload successfully

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSCore/AWSPinpoint

**Screenshots**
![image](https://user-images.githubusercontent.com/775643/86189561-c949ce80-baf6-11ea-91c5-0328a9b99e34.png)

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29] 2.13.4
 - Dependency Manager: [e.g. Cocoapods, Carthage] none
 - Swift Version : [e.g. 4.0] 5.2
 - Xcode Version: [e.g. 11.4] 11.5

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] any
 - iOS Version: [e.g. iOS 11.4] any
 - Specific to simulators:

**Comment by eito** [comment]
upgrading to 2.14.0 seems to have fixed it, but i didn't notice anything in the diff that would suggest it _should_ fix it.

**Comment by royjit** [comment]
@eito 
There was a bug which was fixed in 2.14.0 related to release build of apps. That bug might be responsible for the appstore issue, more details are in this PR - https://github.com/aws-amplify/aws-sdk-ios/pull/2815

Closing this since the original issue is resolved. Feel free to contact us if you are facing any other issue.
