### ISSUE TITLE
AWSMobileClient.default().showSignIn returns aliasExists

### ISSUE THREAD

**Issue by mihaigabriel1992** [aws-amplify/aws-sdk-ios#2820]
**State your question**
AWSMobileClient.default().showSignIn works ok at register but after some time the user is signed out and when he tries to log in again it will return aliasExists and no other message. Is there a way to solve this issue without an update of the App is store?

**Which AWS Services are you utilizing?**
AWSMobileClient Cognito

**Provide code snippets (if applicable)**

`AWSMobileClient.default().showSignIn(
            navigationController: self.navigationController!,
            hostedUIOptions: hostedUIOptions) {
                (userState, error) in
                                      
                if let error = error as? AWSMobileClientError {
                    print(error.localizedDescription)
                }
}`

**Environment(please complete the following information):**
 - SDK Version: AWSMobileClient / 2.13.2
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 8
 - iOS Version:13.5.1
 - Specific to simulators:

Strange thing is that in app delegate at when I initialize the AWSMobileClient it replies with signedIn and when I do `AWSMobileClient.default().getUserAttributes { (attributes, error) in` it returns with signedOut error

**Comment by AboulEinein** [comment]
I'm getting the same error using `AWSMobileClient` version `2.14.2 `

**Comment by parthkunaico** [comment]
@mihaigabriel1992 @AboulEinein 
did you find any workaround for that issue ?

**Comment by mihaigabriel1992** [comment]
@parthkunaico unfortunately no.

**Comment by ravikanhasoft** [comment]
I am facing the same issue `aliasExists` with `message` as a `blank string `. @mihaigabriel1992  have you got any solution or alternate?

**Comment by wooj2** [comment]
Hi,

Thanks for taking the time to reach out to us.

We are having trouble reproducing the issue you are seeing.
1.  Are you using the same method to sign in once the session expires?
2.  It seems that you are using hosted UI, but is there anything unique to your configuration?
3.  How is your userpool configured with regards to how users can sign in?  For example,  What does this page look like?
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1911939/101206231-b1d1bd00-3623-11eb-9f29-9d1db6c19e2c.png">

**Comment by royjit** [comment]
Hi,

I am optimistically closing this issue, hope you are not blocked. Feel free to reach us if you are still facing any issue.
