### ISSUE TITLE
Undeclared selector 'startCustomAuthentication_v2'

### ISSUE THREAD

**Issue by idrougge** [aws-amplify/aws-sdk-ios#2821]
**Describe the bug**
AWSCognito leaks warnings into Xcode build log.

**To Reproduce**
1. Install AWSCognitoIdentityProvider (2.14.0)
2. Build.

**Observed Behavior**
Several semantic issues reported in cmd-5 pane in Xcode and CI build logs, most of them about `Undeclared selector 'startCustomAuthentication_v2'`.
There is also a warning about `Unused variable 'userAttributes'`.

**Expected Behavior**
No build warnings should surface from such a common dependency.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSCognitoIdentityProvider

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.14.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2
 - Xcode Version: 11.5

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 13
 - Specific to simulators: No

**Comment by idrougge** [comment]
This is still present in SDK 2.15.2. It prevents building with "treat warnings as errors" enabled and diverts attention from issues in one's own source code.

**Comment by idrougge** [comment]
Now there is also a deprecation warning leaking:

**Comment by idrougge** [comment]
I would appreciate a followup from AWS here.

**Comment by idrougge** [comment]
I would appreciate a followup from AWS here.

**Comment by akrant06** [comment]
@lawmicha  - Do we have any update here? this issue still persist in latest version of aws sdk/

**Comment by lawmicha** [comment]
Sorry for the confusion, unassigning myself to make sure this gets picked up by someone on the team working on this category of issues. This issue appears to be triaged and pending actual assignee

**Comment by atierian** [comment]
Thanks for opening this issue. We don't plan on addressing all benign warnings within the AWS SDK for iOS at this time.
