### ISSUE TITLE
AWSS3 not updating to version 2.14.1 using CocoaPods

### ISSUE THREAD

**Issue by umerasif** [aws-amplify/aws-sdk-ios#2833]
**Describe the bug**
If the pod file only has `pod 'AWSS3'` and we do `pod update` or `pod install`, then we get 

<img width="695" alt="Screen Shot 2020-07-08 at 1 16 07 PM" src="https://user-images.githubusercontent.com/4849696/86894996-48ee2380-c11d-11ea-88cb-bf883ca9e682.png">

We are not getting the latest version which is 2.14.1 according to the podspec file. This situation gets more complicated if we are also using other AWS pods like if we have the following pods in our pod file,

<img width="255" alt="Screen Shot 2020-07-08 at 1 21 25 PM" src="https://user-images.githubusercontent.com/4849696/86895476-f5300a00-c11d-11ea-9617-5808e5f0adfe.png">

Now if we do `pod update` or `pod install` then we get into the following situation,

<img width="341" alt="Screen Shot 2020-07-08 at 1 25 35 PM" src="https://user-images.githubusercontent.com/4849696/86895963-b2bafd00-c11e-11ea-83a4-b5ad96aca6ae.png">

As you can see, we are getting AWSS3 version 0.0.2 which is terrible. The expected behaviour should be to get AWSS3 version 2.14.1

**Environment:**
 - SDK Version: [2.14.1]
 - Dependency Manager: [Cocoapods v1.9.3]
 - Swift Version : [5.2.4]
 - Xcode Version: [11.5]

**Comment by nick3389** [comment]
@umerasif Same issue here.

**Comment by umerasif** [comment]
We don't have a 2.14.1 version here,

https://github.com/CocoaPods/Specs/tree/master/Specs/8/a/8/AWSS3

**Comment by BillBunting** [comment]
... I'm blocked also waiting for 2.14.1 which should be available now.  Hopefully, it will be added to the pod spec very soon. 

my podfile contains: 
```
  pod 'AWSCore', '= 2.14.1'
  pod 'AWSUserPoolsSignIn', '= 2.14.1'
  pod 'AWSAuthUI', '= 2.14.1'
  pod 'AWSPinpoint', '= 2.14.1'
  pod 'AWSS3', '= 2.14.1'   
  pod 'AWSDynamoDB', '= 2.14.1'
  pod 'AWSCognito', '= 2.14.1'   
  pod 'AWSAuthCore', '= 2.14.1'
  pod 'AWSAPIGateway', '= 2.14.1'
  pod 'AWSMobileClient', '= 2.14.1'
  pod 'AWSGoogleSignIn', '= 2.14.1'
  pod 'AWSFacebookSignIn', '= 2.14.1'
```
Error due to missing AWSS3 2.14.1 (and 2.14.0 will not satisfy the dependency)
```% pod update 
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AWSS3":
  In Podfile:
    AWSS3 (= 2.14.1)
```

**Comment by palpatim** [comment]
We're investigating this. The release and push to CocoaPods completed successfully at 2020-07-08 00:40:52 UTC, but I confirm that neither the search indexes nor the [AWSS3 Pod page](https://cocoapods.org/pods/AWSS3) have been updated. We've seen delays of several hours in the past updating search indexes, but in my experience, the pod page is quick to update. Other pods from the same release (AWSCore, AWSSQS, AWSMobileClient, etc) appear to be updated as expected.

We'll investigate the push to see if there's anything unusual in the podspec, and failing all else, we'll try re-pushing the AWSS3 pod to see if that "unjams" the CocoaPods index.

**Comment by palpatim** [comment]
Other inconsistencies: `pod search` returns the expected version (2.14.1 in all cases but AWSCognitoIdentityProviderASF), for all pods except:

- AWSAppleSignIn (new pod) not present
- AWSAuth (2.14.0)
- AWSCognitoAuth (2.13.4)
- AWSS3 (2.14.0)
- AWSiOSSDKv2 (2.14.0)

**Comment by palpatim** [comment]
Force-push succeeded:

```bash
pod trunk push --allow-warnings --verbose AWSS3.podspec
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

Updating spec repo `trunk`
...
...
...
  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/05a9e5d727ce6c33840c84cdc71c953bc99bbd44/Specs/8/a/8/AWSS3/2.14.1/AWSS3.podspec.json  - Log messages:
    - July 8th, 08:34: Push for `AWSS3 2.14.1' initiated.
    - July 8th, 08:34: Push for `AWSS3 2.14.1' has been pushed (1.030252972 s).
```

**Comment by palpatim** [comment]
It looks like the other pod failures are due to legitimate build problems that didn't show up as errors in our CD pipeline. We'll investigate & fix those separately, but the AWSS3 issue appears to be resolved.

**Comment by BillBunting** [comment]
@palpatim Same issue with the new AWSAppleSignIn ? 

```
pod update 
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `AWSAppleSignIn (= 2.14.1)`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by palpatim** [comment]
> It looks like the other pod failures are due to legitimate build problems that didn't show up as errors in our CD pipeline. We'll investigate & fix those separately, but the AWSS3 issue appears to be resolved.

AWSAppleSignIn is covered in the above statement. We're working on a fix for that, but it will unfortunately involve a new minor version release to fix some compilation/import errors.
