### ISSUE TITLE
How to get the error description from S3 upload failure

### ISSUE THREAD

**Issue by SukanyaDey** [aws-amplify/aws-sdk-ios#2834]
Hi,

I am using S3 to upload pdf files. But if my upload task fails due to some reason I am not getting the exact error code or description of the error. The upload is being done using AWSTransferUtility.

The error object in the completion handler only returns description like below,
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)"

But this is not sufficient to get the details. Upon checking further I was able to get the response code from task.reponse.statuscode. But I need the exact error message to show alert to the user. Is there any way to get it? 

Thank you.

**Comment by Ricardo1980** [comment]
I have a similar problem.
If you use Charles Web Proxy (in your iPhone or in your desktop), you will receive a better description of your error.
Hope this helps.

**Comment by SukanyaDey** [comment]
I don't want to use another library for getting the error codes. It will be really helpful if I get the error codes directly from the AWS Amplify SDK. Like I got the status code as 403. But in AWS documentation I can see there are multiple error codes for 403 like below,
AccessDenied
AccountProblem
AllAccessDisabled
CrossLocationLoggingProhibited
InvalidAccessKeyId
InvalidObjectState
InvalidPayer
InvalidSecurity
NotSignedUp
RequestTimeTooSkewed
SignatureDoesNotMatch

I would like to get the error code from above list.

**Comment by lawmicha** [comment]
Hi @SukanyaDey, for error handling, i believe you can
- as you've mentioned, check `task.response.statusCode`
- cast the `error` as `NSError`. this will give you the domain, code, localizedDescription, etc
- then using error.code to initialize [AWSS3TransferUtilityErrorType](https://github.com/aws-amplify/aws-sdk-ios/blob/0f985322625566a566726e8ca2c24d5a5bc678b8/AWSS3/AWSS3TransferUtility.h#L24) 

If you need more fine grain error codes, you may need fall back to directly using `AWSS3` and call S3 APIs, then initialize [AWSServiceErrorType](https://github.com/aws-amplify/aws-sdk-ios/blob/0f985322625566a566726e8ca2c24d5a5bc678b8/AWSCore/Service/AWSService.h#L26) from the error

If this is a new application, i'd recommend trying out AWSS3StoragePlugin https://docs.amplify.aws/lib/storage/getting-started/q/platform/js It internally uses TransferUtility and have some related code (https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Storage/AWSS3StoragePlugin/Support/Utils/StorageErrorHelper.swift#L52)

**Comment by SukanyaDey** [comment]
When I try to see the details of the NSError I get these details,
code: 2 , 
domain: com.amazonaws.AWSS3TransferUtilityErrorDomain , 
description: The operation couldn’t be completed. (com.amazonaws.AWSS3TransferUtilityErrorDomain error 2.)

But I'm not sure how to set the error type as AWSServiceErrorType in the completion handler. The application I'm using is in objective c and it not a new one.

**Comment by lawmicha** [comment]
since the domain is AWSS3TransferUtilityErrorDomain, the '2' corresponds to this enum https://github.com/aws-amplify/aws-sdk-ios/blob/0f985322625566a566726e8ca2c24d5a5bc678b8/AWSS3/AWSS3TransferUtility.h#L24 and not the AWSServiceErrorType. So that is `AWSS3TransferUtilityErrorClientError`. Since this is a client error, are you able to retry the upload and does it become successful? is it a transient problem?

**Comment by SukanyaDey** [comment]
Hi @lawmicha  I will add the error handling using AWSS3TransferUtilityErrorType. Because in any case I am not getting the error type as AWSServiceErrorType. The issue is happening in production. So, till now we are not sure if it is due to service error or client error. When I am trying to simulate the error in dev, I am getting client error. So I updated that code here. But in any case the SDK was not returning a value for AWSServiceErrorType.

**Comment by lawmicha** [comment]
Hi @SukanyaDey, sorry for the confusion, when using TransferUtility, the error is AWSS3TransferUtilityErrorType. Only when using `AWSS3` directly will the error type be AWSServiceErrorType. Since you are using TransferUtility, you do not get the error type as AWSServiceErrorType.

**Comment by SukanyaDey** [comment]
Thanks for the info. @lawmicha .

**Comment by AnishaGoSharp** [comment]
Hi @SukanyaDey , did you got the solution to this error. I am also getting the same error.

**Comment by SukanyaDey** [comment]
@AnishaGoSharp Hii !! I was actually simulating the error to do proper error handling. There can be multiple reasons for this issue. Not sure what is the issue in your case. Did you solve the problem already?
