### ISSUE TITLE
AWSS3TransferUtility not uploading in background with mobile data enabled only

### ISSUE THREAD

**Issue by nick3389** [aws-amplify/aws-sdk-ios#2835]
**Describe the bug**

I use AWSS3TransferUtility to upload files either in the foreground or the background. When the app is in the background, I can see that the upload task is created successfully but the completionHandler is never called unless I move the app to the foreground. This behaviour is strange as this was working normally. This happens only in a cellular connection

**To Reproduce**
1. Try to upload a file by using transfer utility only with 4G enabled in a device with a **AWSServiceConfiguration** which has set
`allowsCellularAccess = true`

Setup your AppDelegate with this:

```
func application(_ application: UIApplication, handleEventsForBackgroundURLSession identifier: String, completionHandler: @escaping () -> Void) {
     print("rejoining session in the background.")
     AWSS3TransferUtility.interceptApplication(application, handleEventsForBackgroundURLSession: identifier, completionHandler: completionHandler)
}
```

Finally, try to upload a file like this:

```
transferUtility?.uploadFile(url, bucket: bucket, key: key, contentType: contentType, expression: expression, completionHandler: self.completionBlockUpload).continueWith { (task) -> Any? in
       if let error = task.error {
             print("error in creating aws upload task: \(error)")
        }   
        if let uploadTask = task.result {
           // Do something with uploadTask.
           print("aws upload task created successfully")
        }
        return nil
}
```

```
completionBlockUpload = { (task, error) -> Void in
      if let error = error {
          print("error in upload task: \(error)")
      } else {
          print("file uploaded")     
      }
}
``` 

**Observed Behavior**
I do not see the _file uplaoded_ print as nothing happens while the app stays in the background. However the _aws upload task created successfully_ print is logged. The completionBlock is called once I move the app in the foreground. With wifi enabled the upload is completed in the background too.

**Expected Behavior**
I was expecting my upload to be completed successfully in the background too with cellular enabled only.

**Environment(please complete the following information):**
 - SDK Version: 2.1.4.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2.4
 - Xcode Version: 11.5

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: iOS 13.5.1

**Comment by lawmicha** [comment]
Hi @nick3389, we'll have to try and reproduce the behavior. Can you see if this helps? Under your project Target, Signing & Capabilites, + Capability, add Background Modes, and enable
- Background fetch
- Background processing

**Comment by nick3389** [comment]
@lawmicha I have already enabled them. Do you propose to start/resume uploading during background processing too?

**Comment by lawmicha** [comment]
i've seen similar issues where progress handler stops getting called while in background even though it was actually still uploading. I ended up trying with some code where i resumed the task when the application went into foreground and that made the progress handlers work again https://github.com/aws-amplify/aws-sdk-ios/issues/1513#issuecomment-531407454

You mentioned that that completion handler is not called, could you confirm that is the case? one way i can think of is to trigger an upload and wait for complete, the time it took is going to be the same time to wait. trigger the same upload, and move the app to background, expected that no reporting on progress occurs, but completion is called eventually after the same amount of time elapsed. If you wait long enough, the logs should show completed, is this the case? 

resuming the upload during background processing sounds like an good test to do, how would you accomplish this?

**Comment by nick3389** [comment]
@lawmicha I don't use the progress handler so i don't know its behaviour. I will test it and will come back. However, the case is this:

**Expected behaviour** 
iPhone connected to Wifi -> app in the background -> a file starts uploading -> completion Handler is called even when the app is in the background

**Unexpected behaviour **
iPhone connected only to Cellular -> app in the background -> a file starts uploading -> completion Handler is not called unless the app is moved in the foreground.

**Comment by nick3389** [comment]
@lawmicha any news regarding this?

**Comment by sspogra** [comment]
Same with 2.26.1 and iOS 15

**Comment by royjit** [comment]
> iPhone connected only to Cellular -> app in the background -> a file starts uploading -> completion Handler is not called unless the app is moved in the foreground.

When the app is in background the iOS take over the preference on when to upload the data. Apple set this value via - https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411552-discretionary, guessing that this might be affecting the call here?

You mention here that the callback is not invoked, but does the upload succeeds if you look in the AWS S3 console?

**Comment by nick3389** [comment]
@royjit No nothing happens. It's like the app is dormant. I will check once more with the most recent version of the SDK and get back to you.

**Comment by lawmicha** [comment]
May be related discussion https://github.com/aws-amplify/amplify-ios/discussions/1740
