### ISSUE TITLE
Hello, I need to know how to decrypt data that already encrypted in AWS server side with the mobile application (the region is eu-west-3 Paris), anyone can help me in this please ?

### ISSUE THREAD

**Issue by Ynes-sk** [aws-amplify/aws-sdk-ios#2837]

**Comment by lawmicha** [comment]
Which AWS Services are you utilizing? Perhaps AWS KMS is what you are looking for? https://docs.aws.amazon.com/kms/latest/APIReference/Welcome.html

we provide the AWS KMS cocoapod here https://cocoapods.org/pods/AWSKMS

**Comment by Ynes-sk** [comment]
Thank you, yes I'm using KMS and I need to decrypt the data that is already encrypted , I can't find a specific method that do this

**Comment by lawmicha** [comment]
Does this work for you? https://docs.aws.amazon.com/kms/latest/APIReference/API_Decrypt.html

AWS KMS forums link is at the bottom of that page [here](https://forums.aws.amazon.com/forum.jspa?forumID=182) may provide you with more relevant questions/answers. The iOS SDK only provides a thin client to help you interact with AWS KMS. 

You can also check out [Amplify](https://docs.amplify.aws/lib/q/platform/ios) if you are developing a new application

**Comment by Ynes-sk** [comment]
yes I read this but I can't find what I can use actually in my iOS application in order to decrypt the data (SDK or any tool), I have only access ID key and Access secret key (maybe arn key ). I think I need at first link my iOS app to the aws server using this keys then using a request (That I don't know how) in order to deal with the decryption (the data decrypted with KMS is an url I think that will be returned as a plaintext I'm not sure about that because the decryption in invisible for me), thank you n advance

**Comment by ihattab** [comment]
Hello I still have the same issue .. can anyone here tell me how to resolve the problem ?

**Comment by palpatim** [comment]
With these low-level AWS SDKs, you generally create a "bare" request and then assign values to them. For example in your case, you could do something like:

```swift
func decrypt(ciphertext: Data, keyId: String) {
    let request = AWSKMSDecryptRequest()!
    request.ciphertextBlob = ciphertext
    request.keyId = keyId
    // ... and so on, for all the attributes you require for your operation

    // Then invoke the request
    AWSKMS.default().decrypt(request).continueWith { task in
        if let error = task.error {
            print("Error decrypting: \(error.localizedDescription)")
            return nil
        }
        guard let result = task.result, let plaintextData = result.plaintext else {
            print("Decrypt result data unexpectedly empty")
            return nil
        }
        print("Success: \(plaintextData)")
        return nil
    }.waitUntilFinished()
}
```

Also note that the low-level SDKs use "tasks", which is why we `return nil` at the end of our `continueWith` block above. See our [README.md](https://github.com/aws-amplify/aws-sdk-ios#working-with-awstask) for pointers.

Hope this helps.
