### ISSUE TITLE
AWSMobileClient.default().showSignIn() Drop-in UI Button Background Issues

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-ios#2844]
**Describe the bug**
The SignInUIOptions primaryColor appears behind the buttons.  The background behind the buttons should match the secondaryBackgroundColor (or system background when nil) or the button background could be transparent. See screenshot.

**To Reproduce** / **Code Snippet**

In either standard or dark mode.

```
AWSMobileClient.default().showSignIn(navigationController: navigationController,
                                                 signInUIOptions: SignInUIOptions(canCancel: false,
                                                                                  logoImage: UIImage( named:"loginViewIcon") ,
                                                                                  backgroundColor: UIColor.systemGray,
                                                                                  primaryColor: UIColor.systemRed),
                                                 { (signInUserState, error) in
...
```

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient Drop-in UI

**Screenshots**
![IMG_3506](https://user-images.githubusercontent.com/5861783/86990986-fab44100-c16b-11ea-9e59-68458a99691b.jpeg)

**Environment(please complete the following information):**
 - SDK Version: 2.14.2
 - Dependency Manager: Cocoapods
 - Swift Version : 5
 - Xcode Version: 11.5

**Device Information (please complete the following information):**
 - Device: Any, iPhone Xs
 - iOS Version: 13.1 (any)
 - Specific to simulators: No

**Comment by wooj2** [comment]
@BillBunting - thanks for reporting this.  I've submitted a PR which applies the secondaryColor to the button backgrounds instead of the primaryColor.

**Comment by wooj2** [comment]
Optimistically closing this issue as the code has been pushed to our main branch.

**Comment by BillBunting** [comment]
@wooj2 thank you.  I'll try it out as soon as the cocoapod is available.
