### ISSUE TITLE
Occasional unexpected 401 responses for valid  tokens

### ISSUE THREAD

**Issue by Anthony-Todd-CGI** [aws-amplify/aws-sdk-ios#2854]
**Describe the bug**
We are seeing occasional instances of API calls returning 401 (Not Authorized) responses where we do not believe that his should be the case. The tokens that we are using are refreshed before the calls so should be valid. The refresh token has almost certainly not expired given the expiration length.

We are using `getTokens()` in the `AWSMobileClient ` extension the ensure that the token is up to date before the call is made. If the token refresh fails for any reason then the API call will not be made.

All uses who reported this issue are using Username and passwords in the Cognito User pool.

**To Reproduce**
We have not been able to reproduce the error.

**Expected behavior**
We expect the API to validate the token that should be valid at this point. If the token has expired we expect it to have been refreshed prior to the API Call. If there was an issue refreshing the token then we expect an error to be thrown before attempting the web API call.

**Screenshots**
None.

**Environment(please complete the following information):**
 - Amplify Framework Version:   - AWSMobileClient (2.13.4):
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhones 6 - 11
 - iOS Version: iOS12/iOS13

**Additional context**
All users that have reported the the issue have updated their app to a version that is now using the AWSMobileClient. The previous version used an older version of the `AWSCognitoIdentityProvider` directly.

**Comment by lawmicha** [comment]
Hi @Anthony-Todd-CGI , moving this other to the SDK as it sounds this is an existing app using the SDKs, migrating from `AWSCognitoIdentityProvider` to `AWSMobileClient`. Could you provide additional info like what does your code snippet for getting tokens and how are you using it? which other SDKs are you using?

**Comment by Anthony-Todd** [comment]
Here are the code samples requested.

# Refreshing tokens
This is the method call that we use to get the session tokens.

```swift
/// Gets the session tokens from AWSCognito API. Session tokens are refreshed when expired.
/// - Parameter reset: force refreshes the tokens used for testing token refresh.
/// - Returns: returns a Task<UserSession> object that returns either tokens or an error.
public func getSession(_ reset:Bool = false) -> Task<UserSession> {
    
    // test token refresh
    if reset {
        AuthenticatedUser().resetExperationDate()
    }
    
    let refreshSessionTask = Task<UserSession>()
    awsClient.getTokens { (tokens, error) in
        
        guard let tokens = tokens else {
            refreshSessionTask.completeTask(result: nil, error: error ?? AuthenticationErrors.NoTokens)
            return
        }
        refreshSessionTask.completeTask(result: UserSession(tokens: tokens), error: error)
    }
    
    return refreshSessionTask
}
```

# API Session Call

I've included the following snippet, this creates a task object then calls the getSession method. Once that completes we take the token and make the API call passing in the fresh token. This method has been modified so that we can monitor the id tokens and expiration dates.

```swift
let task = Task<T>()

UIApplication.shared.showNetworkActivityIndicator()

#if DEBUG
let authUser = AuthenticationUseCaseProvider.instance.getCurrentUserUsecase().getCurrentUser()
    
do {
    print("idToken: ", authUser.keychain.idToken ?? "None")
    print("idTokenExpirationDate: ", authUser.keychain.expirationDate ?? "None")
}
#endif


AuthenticationUseCaseProvider.instance.getCurrentUserUsecase().getSession().continue(withClosure: { (sessionResult, error) in

    #if DEBUG
    let authUser = AuthenticationUseCaseProvider.instance.getCurrentUserUsecase().getCurrentUser()
        
    do {
        print("idToken: ", authUser.keychain.idToken ?? "None")
        print("idToken: ", sessionResult?.idToken ?? "None")
        print("idTokenExpirationDate: ", authUser.keychain.expirationDate ?? "None")
        print("idTokenExpirationDate: ", sessionResult?.expirationDate.description ?? "None")
    }
    #endif
    
    if let error = error {
        UIApplication.shared.hideNetworkActivityIndicator()
        task.completeTask(result: nil, error: error)
        return
    }

    // sessionResult is only nil is there is an error. which is handled above.
    guard let request = route.request(authToken: sessionResult?.idToken ?? "" ) else {
        UIApplication.shared.hideNetworkActivityIndicator()
        task.completeTask(result: nil, error: ConnectionError.couldNotGenerateRequest)
        return
    }

    task.urlSessonTask = self.session.dataTask(with: request, completionHandler: { (data, urlResponse, error) in
    ...
    })
})

return task
```

**Comment by jonsimpson-c** [comment]
Hi AWS, 

Please can we have an update to this ticket please. This relates to a live issue that is causing considerable problems for our user base.

Many Thanks.
Jon Simpson Consultant

**Comment by DongQuanRui** [comment]
Hi, sorry for the late update. 
- Can you try to reproduce this by installing the version of your app that used CognitoIdentityProvider, then follow your user’s upgrade path, which presumably is to install a newer version of your app that uses AWSMobileClient. We haven’t seen any prior reports of customers having problems with that upgrade path, but  maybe you’re hitting a path we haven’t seen.
- If you are able to reproduce, then turn on the verbose log by doing 
```
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

to see if your code is sending the correct request.
- What service are you using for API?
- What authentication mode are you using (e.g. how are you authenticating users given the idToken)?
And then we can further investigate. Thanks
