### ISSUE TITLE
Email option for MFA

### ISSUE THREAD

**Issue by bfallon** [aws-amplify/aws-sdk-ios#2860]
We would like to use Email for MFA in our app.

We are using AWSMobileClient

In our app, we are using the code: 
`AWSMobileClient.default().signIn(username: email, password: password) { (signInResult, error) in`

The possible SignInResult states are:
```
public enum SignInState: String {
    case unknown = "UNKNOWN"
    case smsMFA = "CONFIRMATION_CODE"
    case passwordVerifier = "PASSWORD_VERIFIER"
    case customChallenge = "CUSTOM_CHALLENGE"
    case deviceSRPAuth = "DEVICE_SRP_AUTH"
    case devicePasswordVerifier = "DEVICE_PASSWORD_VERIFIER"
    case adminNoSRPAuth = "ADMIN_NO_SRP_AUTH"
    case newPasswordRequired = "NEW_PASSWORD_REQUIRED"
    case signedIn = "SIGN_IN_COMPLETE"
}
```

I see **smsMFA** but there is no email option. Is this possible? 

We are using the following versions:
pod 'AWSMobileClient', '2.13.1'
pod 'AWSCognito', '2.13.1'

**Environment**
XCode 11.6
Swift 4

**Device Information**
All iOS devices

**Comment by wooj2** [comment]
Hi @bfallon ,

Unfortunately, this is not an option that is supported by the Cognito service, and therefore, there are no changes that we can make from the SDK/Amplify perspective.

That being said, there are two routes I can think of that you can go down:
1.  Use the AWS Developer Forums to request this as a feature request w/ the cognito team.
or
2.  Implement this as a custom-auth workflow.  The documentation for custom authflows with AWSMobileClient is located here:
https://docs.amplify.aws/sdk/auth/custom-auth-flow/q/platform/ios

best of luck!
