### ISSUE TITLE
Upload to bucket failed with error Domain=NSCocoaErrorDomain Code=512

### ISSUE THREAD

**Issue by sarojkumarojha** [aws-amplify/aws-sdk-ios#2884]
**Describe the bug**
while uploading data to bucket it gives error Domain=NSCocoaErrorDomain Code=512 
in our app I am using AWSS3(2.7.0) to upload db file to bucket , sometimes it gives an error 
Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved." UserInfo={NSUserStringVariant=Folder}
 I am trying to upload file when app is in background .

could you please help me out .

**To Reproduce**
1. 'Open App -  put app in background - upload file . '
2. get app to foreground , see the error 

**Expected Behavior**
it should upload the data , without any error 

**Code Snippet**
```
AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
  [[transferUtility uploadData:compressData
                              bucket:aWSNewBucketName
                                 key:<key>
                         contentType:@"application/x-gzip"
                          expression:expression
                   completionHandler:completionHandler] continueWithBlock:^id(AWSTask *task) {
            if (task.error) {
               
            }
            if (task.result) {
            }
            return nil;
        }];

```

**Environment(please complete the following information):**
 - SDK Version: 2.7.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1
 - Xcode Version: 11.3.1

**Device Information (please complete the following information):**
 - Device: iPhone 7 ,iPhone XR
 - iOS Version: iOS 13.5.1 , iOS 13.6

**Comment by sarojkumarojha** [comment]
@DongQuanRui Any thought on above issue .

**Comment by DongQuanRui** [comment]
Hi @sarojkumarojha, thanks for reaching out. 
I am a bit confused by the reproduce steps you provided: 
Isn't "Open App -> UploadFile -> Put App to background -> Get App to foreground" be the right order?
I tried out myself trying to upload a 27MB large image and everything works fine.

- How often do you see this error (right at the time when app goes to background? or some time before moving the app to background)
- Can you provide a larger and more detailed stack trace?

**Comment by sarojkumarojha** [comment]
Hi @DongQuanRui  , thanks for your reply . Our App is designed like it will upload data/file when app in background .
So the steps are  Open App -> Put App to background -> UploadFile(3-5MB),
As I debugged app found issue with SDK , the SDK first it tries to save in cache directory  then uploads to bucket , for ios 13+ some device its giving the  error (Domain=NSCocoaErrorDomain Code=512) and unable to write in cache dir. Could you please check from that angle .
Found similar issue on the
apple developer forum.Please find the link for the same below.
https://developer.apple.com/forums/thread/128927

Thanks.

**Comment by DongQuanRui** [comment]
Hi, @sarojkumarojha . Sorry for the late reply. I am not sure if I understand correctly. 

Your App runs like:
1, Open App. (the file is chosen by user on this step?)
2, Put App to background (or the file is chosen by app on this step?), and put app into background, the file upload will be triggered

So I tried again with my sample App:
1, open App and choose an image but not uploading it
2, put app to background (meaning to call the upload method in ` func sceneWillResignActive()` which sits inside `SceneDelegate` class)
- I tried several time but I didn't see the error you saw. So maybe there are some steps I was not reproducing correctly. 
- Or how often are you seeing this error? happen once every 10 upload? 
Could you provide further details on it?

**Comment by sarojkumarojha** [comment]
Hi @DongQuanRui Thanks for reply , you understood  correctly what our app does , As I debugged more , the issue is with file writing API , its happening  with more than 400+ user not with all to give a clue all affected user are iOS version 13+

Upload file to S3 by calling uploadData API and the API returns an error with error code 512 , because while writing file to temp directory it fails .
This issue happens only for some users and it does not return error to all the users.Found similar issue on the
apple developer forum.Please find the link for the same below.

https://developer.apple.com/forums/thread/128927

Please find the code snippet below.

(AWSTask<AWSS3TransferUtilityUploadTask *> *)uploadData:(NSData *)data
bucket:(NSString *)bucket
key:(NSString *)key
contentType:(NSString *)contentType
expression:(AWSS3TransferUtilityUploadExpression *)expression
completionHandler:(AWSS3TransferUtilityUploadCompletionHandlerBlock)completionHandler {}
// Saves the data as a file in the temporary directory.
NSString *fileName = [NSString stringWithFormat:@"%@.tmp", [[NSProcessInfo processInfo] globallyUniqueString]];
NSString *filePath = [self.cacheDirectoryPath stringByAppendingPathComponent:fileName];
NSURL *fileURL = [NSURL fileURLWithPath:filePath];

NSError *error = nil;
BOOL result = [data writeToURL:fileURL
options:NSDataWritingAtomic
error:&error];
if (!result) {
if (completionHandler) {
AWSS3TransferUtilityUploadTask *uploadTask = [AWSS3TransferUtilityUploadTask new];
uploadTask.bucket = bucket;
uploadTask.key = key;
completionHandler(uploadTask,error);
}
}
Error :
Error Domain=NSCocoaErrorDomain Code=512 “The file couldn’t be saved.” UserInfo={NSUserStringVariant=Folder}

**Comment by palpatim** [comment]
Related to #2885?

**Comment by KorolZhu** [comment]
I have the same problem of <NSCocoaErrorDomain Code=512 “The file couldn’t be saved.” UserInfo={NSUserStringVariant=Folder}>，but my app not using aws sdk, so i think is not about aws, maybe the os bug.

i guess this issue happened After upgrading the latest os version, because all device version is ios 13+, most is ios13.6 and 13.5, and file can not write at document, library, temp, can not write to sandbox at all.
