### ISSUE TITLE
AWSMobileClient: Immediately Signed out After Federated Sign in?

### ISSUE THREAD

**Issue by bumbleparrot** [aws-amplify/aws-sdk-ios#2894]
I am using AWSMobileClient directly to federate my logins. I'm not using any "escape hatch". As soon as I get the "signedIn" user state. I try to get the user Attributes. The call immediately crashes the SDK in the releaseSignInWait() method.

Why does the app crash? Am I doing the federated login sequence correctly?

**Which AWS Services are you utilizing?**
Cognito Identity Pools
AWSMobile Client

**Provide code snippets (if applicable)**
1. I federate my login by providing the jwt token (from Google) to the federatedSignIn method.
`AWSMobileClient.default().federatedSignIn(providerName: authProviderString, token: token) { (userState: UserState?, error: Error?)`

2. Once the completion handler returns and I am in the signedIn state, I attempt to get any user attributes available via getUserAttributes.
`AWSMobileClient.default().getUserAttributes { (attrs: [String : String]?, error: Error?)`

3. The above call crashed the SDK on line 725 of AWSMobileClientExtension.swift file. The SDK crashes on this line `self.credentialsFetchLock.leave()`

4. The error in the above crash states: `Amplify] AWSMobileClient Event listener - signedOutUserPoolsTokenInvalid`

**Why would my token be invalid or signed out if I did this within the userState being "signedIn"?**

**Full Code**
```
        AWSMobileClient.default().federatedSignIn(providerName: authProviderString, token: token) { (userState: UserState?, error: Error?) in
            if error != nil {
                switch(error as? AWSMobileClientError) {
                case .notAuthorized:
                    completionHandler(user, nil, FederatedAuthError.notAuthorized)
                    return
                case .federationProviderExists:
                    completionHandler(user, UserState.signedIn, nil)
                    return
                default:
                    completionHandler(user, nil, FederatedAuthError.signInError)
                    return
                }
            }
            switch(userState) {
            case .signedIn:
                completionHandler(user, userState, nil)
                AWSMobileClient.default().getUserAttributes { (attrs: [String : String]?, error: Error?) in
                    print("attrs: \(attrs)")
                    print("error: \(error)")
                    print("end")
                }
            case .signedOutUserPoolsTokenInvalid:
                completionHandler(user, userState, nil)
            default:
                completionHandler(user, nil, FederatedAuthError.signInError)
            }
        }
```
**awsconfiguration.json**
```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:xxxxxxx",
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-1xxxxxxxxx",
            "AppClientId": "xxxxxxx",
            "AppClientSecret": "xxxxxxxxx",
            "Region": "us-east-1"
        }
    },
    "DynamoDBObjectMapper": {
        "Default": {
            "Region": "us-east-1"
        }
    },
    "S3TransferUtility": {
        "Default": {
            "Bucket": "xxxxxxxxx",
            "Region": "us-east-1"
        }
    },
    "S3": {
        "Default": {
            "Bucket": "xxxxxxx",
            "Region": "us-east-1"
        }
    }
}

```

**Environment(please complete the following information):**
 - AWSMobileClient 2.14.2
 - Cocoapods
 - Swift Version: 5

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 13.1
 - This happens on real devices as well as simulators.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by bumbleparrot** [comment]
Hello, 

I saw that this was resolved in the latest version **2.15.0** with regards to the crash. [PR: #2866](https://github.com/aws-amplify/aws-sdk-ios/pull/2866)

Additionally, I learned that getting user attributes this way is not expected as the user is not signed into the **User Pool**. There will never been any attributes.

1. Can we update the documentation or method comments to indicate that the getUserAttributes() method only applies to users that are signed in via User Pools?
2. Can the team point me in the right direction if I want to store simple key value pairs for users signed into the **Identity Pool**? More directly, what SDK and APIS do I use to create the dataset and store values against **Identity Pool** Identity Ids?

Thanks!
-Bumbleparrot

**Comment by palpatim** [comment]
> 1. Can we update the documentation or method comments to indicate that the getUserAttributes() method only applies to users that are signed in via User Pools?

Thanks for the suggestion, we will investigate.

> 2. Can the team point me in the right direction if I want to store simple key value pairs for users signed into the **Identity Pool**? More directly, what SDK and APIS do I use to create the dataset and store values against **Identity Pool** Identity Ids?

AFAIK, there is no facility for adding user attributes to an IdentityPool. Cognito IdentityPools are for Authorization ("AuthZ") of a call, not Authenticating ("AuthN") a user. You can set up your own backing store for attributes, e.g., in AppSync, or you can use Cognito UserPools to federate into your IdentityPool.

**Comment by bumbleparrot** [comment]
Thanks @palpatim,

After much investigation and experimentation, I figured out what my path is.

My objective was to provide “as native as possible” a sign up experience that allowed 3 social providers (Google, Apple, Facebook). Additionally, I wanted the ease of managing user profile data with the “nice to haves” like local cache and synchronization. 

**I learned that you can’t fully have both.**

Before deciding if you need a User Pool or Identity pool, you have to ask yourself two questions and decide which is more important.

1. Do you want to manage user profile data (without doing your own dynamo DB style data store)?
2. How native do you want the “sign in with” experience?

**User Profile Data Management is more important**
- If you want to store user data and get all the “nice to haves” (like local cache and sync) you have to use a **User Pool** with social login enabled.
- In this case you will be using `Amplify.Auth.signInWithWebUI()`
- The draw back is that the “as native as possible” experience is compromised a bit. I think there are two experiences you can choose from using this path.
    1. **Sheet that opens up the providers sign in page (keeping your app's experience in the background)**:
        - You can have an experience where the user clicks the "Sign in with Google" button and is prompted by your app that it wants to open a website sheet. The rest of the sign in / up experience happens in the sheet with your app in the background. (Good, this feels normal for most users).
        - The detail here is when the user clicks "Sign in With Google", they will be prompted that they will be going to the Hosted UI page (**amazoncognito.com**). (Bad, the user didn't expect this domain and could get scared. You can customize this domain to be less scary) 
       - There will be an immediate redirect to Google after agreeing to goto (**amazoncognito.com**). The user most likely won't notice this. (Good, most users won't notice the redirect)
       - The user will land on the expected accounts.google.com page and sign in from there. (Good, this feels familiar)
    2. **Hosted UI inside of app as a full screen view controller (takes you away from your app's experience)**:
        - You can use the Hosted UI inside your app via navigation controller. This takes over the whole screen and shows the Cognito Hosted UI with the sign in / up options. (Bad, this feels less normal as the Hosted UI will never fully feel like your own app no matter how much you customize it).
       - The sign in, sign up reset password experience is all inside of these full screen takeovers. (Good, feels normal again but still completely separate from the main app)
       - Once completed, the user will be taken back the your app. (Good, feels normal)

**Native Sign in Experience is more important**
- If you want the "as native as possible" experience, you have to give up the "out of the box" user profile data management and synchronization and go with an **Identity Pool**.
- In this case you will be using `AWSMobileClient.default().federatedSignIn()`
- The result is that you will have to "roll your own" Dynamo table and store user profile there. You can tie the data to the users unique Identity Pool id.
- The user experience will be as follows:
    - Clicking "Sign in with Google" will prompt the user that the app wants to open a sheet to (**google.com**). (Good, no weird domains to scare the user).
    - The sheet will keep your app in the background (Good, this feels normal to users).
    - The user is immediately taken to accounts.google.com without any redirects. (Good, no weird redirects)
    - The buttons can be the native ones provided by Google, Apple, Etc. (Good, familiar looking standard buttons from each provider).

@palpatim, @royjit is my understanding of how these two products work and their resulting user experiences correct?

I hope this helps others!

**Comment by bumbleparrot** [comment]
Is the my recap understanding correct?

Confirmation would help many new to this SDK and save them ***A LOT*** of time.

**Comment by palpatim** [comment]
@bumbleparrot 

Sorry for the late reply on this. Your summary is accurate and useful--thanks so much for putting in the work to summarize it!

I'm going to close this issue now, but thanks again for providing context for future readers.
