### ISSUE TITLE
User Pools, Hosted UI - SignOut

### ISSUE THREAD

**Issue by bumbleparrot** [aws-amplify/aws-sdk-ios#2904]
I’m using User Pools with social sign in and hosted UI.

When calling Amplify.Auth.signOut, the app is prompting the user to open up the hosted UI page to sign out.

The user clicks okay, the page opens, immediately closes, and the sign out is complete.

Is this expected behavior?

Is there a way to call sign out without the user having to agree to the UI prompt to open the Hosted UI page?

**Comment by turtle-on-the-storm** [comment]
Yes. For me the app prompts user to open up the hosted UI page and then the see the message is also wrong:
<App Name> wants to use <hosted UI> to Sign In

It should be Sign Out. The best option would be not to show the popup at all.

I see the exact same issue. Any help or workarounds?

**Comment by bumbleparrot** [comment]
@turtle-on-the-storm, A work around I thought of was just to call the URL manually via URLSession.

However, I'm having an issue because swift doesn't like the redirect URL parameters.

Have you tried this?

See Stackoverflow thread [here.](https://stackoverflow.com/questions/63224049/swift-url-with-custom-scheme-in-query-string-fails-redirect-uri)

**Comment by bumbleparrot** [comment]
I think this is what the URL is supposed to look like:
```
https://xxxxxx.auth.us-east-1.amazoncognito.com/logout?client_id=49jaf4a848hakh&logout_uri=myapp%3A%2F%2F&redirect_uri=myapp%3A%2F%2F&response_type=token
```

**Comment by palpatim** [comment]
Hi all.

Calling the logout URL directly is not supported. The `signOut` method clears internal state as well as launching the HostedUI to invoke the logout flow on the provider. 

The behavior @bumbleparrot reports is expected: HostedUI uses a web view to manage its OAuth flows, and so all auth related activities are conducted through a webview, including sign up, sign in, and sign out. The webview prompting, then appearing briefly and then disappearing is expected (although unfortunate).

The webview reporting a "sign in" message even though you're signing out is likewise an artifact of Apple's implementation. When we launch an OAuth flow, all the webview gets is a URL, without knowing what is happening. The "Sign In" message is provided by Apple and we don't have a way to override it.
