### ISSUE TITLE
AWSCognito - Managing Datasets

### ISSUE THREAD

**Issue by bumbleparrot** [aws-amplify/aws-sdk-ios#2909]
***Issue***
I have successfully implemented Identity Pool authentication. My underlying AWS requests to Dynamo etc work without issue.

With an Identity Pool Identity, I am trying to manage the dataset associated to the identity. I want to create a simple data set and assign key value pairs.

For this I am using AWSCognito APIs.

My issue is that I am getting an error after calling .synchronize().continueWith(block:). The response from the server is:
```
{"code":"BadRequest","message":"Identity pool id is missing or incorrect in the request URI.","type":"client"}
```

***Questions***
- How do I set the Pool Id?
- Is my AWSConfiguration.json correct?
- @awsmobilesdk , @royjit , can you guys help me?

**Provide code snippets (if applicable)**
***Here is my AWSconfigurationFile***
```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:f906d38e-f3c3-45a9-8fef-457e8288aa91",
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-1_GbwGGJCm6",
            "AppClientId": "xxxxxxx",
            "AppClientSecret": "yyyyyyyy",
            "Region": "us-east-1"
        }
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "myapp88c46c2d-88c46c2d-dev.auth.us-east-1.amazoncognito.com",
                "AppClientId": "xxxxxxx",
                "AppClientSecret": "yyyyyyy",
                "SignInRedirectURI": "myapp://",
                "SignOutRedirectURI": "myapp://",
                "Scopes": [
                    "phone",
                    "email",
                    "openid",
                    "profile",
                    "aws.cognito.signin.user.admin"
                ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    },
    "DynamoDBObjectMapper": {
        "Default": {
            "Region": "us-east-1"
        }
    },
    "S3TransferUtility": {
        "Default": {
            "Bucket": "xxxxx-dev",
            "Region": "us-east-1"
        }
    },
    "S3": {
        "Default": {
            "Bucket": "xxxxx-dev",
            "Region": "us-east-1"
        }
    },
    "Cognito": {
        "Default": {
            "PoolId": "us-east-1:f906d38e-f3c3-45a9-8fef-457e8288aa91",
            "Region": "us-east-1"
        }
    }
}
```

***Code to create a profile data set, and store a key and value****
```
let dataset = AWSCognito.default().openOrCreateDataset("profile")

let data = dataset.getAll()
dataset.setString("horse", forKey: "animal")
dataset.synchronize()?.continueWith(block: { (task:AWSTask<AnyObject>) -> Any? in
      print("Faulted?: \(task.isFaulted)")
      return nil
})
```

***The above code gets a response from the server as***
```
{"code":"BadRequest","message":"Identity pool id is missing or incorrect in the request URI.","type":"client"}
```

**Which AWS Services are you utilizing?**
Amplify (1.0.5)
AWSMobileClient (2.15) - To Federate Sign In
AWSCognito (2.15) - To create and manage the data set.

**Environment(please complete the following information):**
 - Amplify (1.0.5)
 - AWSMobileClient (2.15) - To Federate Sign In
 - AWSCognito (2.15) - To create and manage the data set.
 - SDK Version: 2.15
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Simulator and Physical
 - iOS Version: 14 Beta
 - Specific to simulators:

**Comment by bumbleparrot** [comment]
***Work around Found***

I was able to create a dataset and save values to it if I set the configuration for Cognito in the code like below:
```
        let credentialProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: "us-east-1:f906d38e-f3c3-45a9-8fef-457e8288aa91")
        let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
```

***Notice that the identity pool is the same as what is specified in the awsconfiguration.json***.

I think this is a ***BUG*** with Cognito loading the configuration from the awsconfiguration file.

Can you guys please verify and get this fixed?

**Comment by bumbleparrot** [comment]
After even more testing, it seems like the Cognito initializer only cares about the "Region" key being in the awsconfiguration.json file.

The ***Cognito initializer completely, ignores or doesn't care about the presence of the "PoolId" key***. This makes sense given the error that is being generated when trying to use the Cognito API.

This also explains why programmatically setting the Cognito configuration works but the same configuration from the awsconfiguration.json file doesn't.

@awsmobilesdk @royjit does this make sense?

**Comment by lawmicha** [comment]
Hi @bumbleparrot thanks for the updates, do you have a code reference to the Cognito initializer?

> The _**Cognito initializer completely, ignores or doesn't care about the presence of the "PoolId" key**_. This makes sense given the error that is being generated when trying to use the Cognito API.

**Comment by bumbleparrot** [comment]
Hi @lawmicha ,

I don’t use any specific initializer. I use the default shared instance of the Cognito object. By default this loads a configuration from the AWS configuration.json. (I know this for sure because if I take out the “Cognito” key from the config file, the default shared instance fails to load.)

I think this is the pattern for most “main” objects in the SDK. You used the .default() or .sharedInstance and it loads the config from the awsconfiguration.json file (which is normally generated by The Amplify CLI)

Does that help?

**Comment by bumbleparrot** [comment]
Do you guys need anymore info? Is this really a bug or is my awsconfiguratjon.json wrong?

**Comment by palpatim** [comment]
@bumbleparrot Sorry for the delayed response on this. We should have realized much earlier that you were asking about Cognito Sync, which has been deprecated for a couple of years now and which we just removed in SDK release 2.20.0. Because it has been deprecated, we don't have any on-team knowledge of the system behaviors or what might be causing this specific problem. Please investigate using Amplify DataStore or the AWS AppSync SDK to handle user data.
