### ISSUE TITLE
Secure code by using NSSecureCoding instead of NSCoding

### ISSUE THREAD

**Issue by mmathewsTableau** [aws-amplify/aws-sdk-ios#2914]
NSCoding does not verify the type of object upon deserialization and therefore is vulnerable to object substitution attacks. The code can protect itself from these attacks by using NSSecureCoding instead: https://developer.apple.com/documentation/foundation/nssecurecoding?language=objc 

Various spots where NSCoding is used:
https://github.com/aws-amplify/aws-sdk-ios/search?q=NSCoding&unscoped_q=NSCoding

**Comment by palpatim** [comment]
Thank you for rep​​orting ​​your concern, and for your patience as we investigated. The AWS Mobile SDK’s use of NSCoding does not represent a security issue. However, NSSecureCoding introduces improvements, so we are currently replacing the SDK’s use of NSCoding with NSSecureCoding. We’ll update this issue as we make progress on those changes.

**Comment by mmathewsTableau** [comment]
Thanks @palpatim for looking into. It sounds like you have gathered enough information to conclude that the specific usages are not an issue. 

It's a conclusion that I wanted to try to get to myself but I couldn't without enough context about how the code works. To help alleviate my concerns, would you be able to explain why the usage in AWS SDK are not a security issue? Thanks

**Comment by palpatim** [comment]
All subclasses of `AWSMTLModel` now support `NSSecureCoding`, with a few exceptions:

  - AWS IoT:
    - `AWSIoTDataDeleteThingShadowResponse`
    - `AWSIoTDataGetThingShadowResponse`
    - `AWSIoTDataPublishRequest`
    - `AWSIoTDataUpdateThingShadowRequest`
    - `AWSIoTDataUpdateThingShadowResponse`
  - Amazon Lambda:
    - `AWSLambdaInvocationRequest`
    - `AWSLambdaInvocationResponse`
  - Amazon S3:
    - `AWSS3GetObjectOutput`
    - `AWSS3GetObjectTorrentOutput`
    - `AWSS3PutObjectRequest`
    - `AWSS3RecordsEvent`
    - `AWSS3UploadPartRequest`

    To support `NSSecureCoding` for those types, host apps will have to create a subclass of the base type, and override the appropriate `initWithCoder:` methods to provide a type-safe unarchiving method.

The remaining uses of `NSCoding` are all scoped to the deprecated client `AWSS3TransferManager`, which has been deleted for some time, and will be removed in Dec 2020. These include uses in `AWSS3TransferManager` itself, and the support library `AWSTMCache`.

Once we publish the various model-support PRs, and publish the release that removes the deprecated clients, we will update and close this issue.

**Comment by mmathewsTableau** [comment]
Thanks @palpatim for the update and the quick turnaround.

**Comment by palpatim** [comment]
We published support for the remaining, non-deprecated clients & models on https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.18.1

We will update and close this ticket when we complete the final work to remove the deprecated `AWSS3TransferManager` and its dependencies.

**Comment by palpatim** [comment]
We removed the deprecated clients in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0. This should remove the last usages of NSCoding in the SDK.
