### ISSUE TITLE
trying to add pods to an objective c project

### ISSUE THREAD

**Issue by Maxim-Gorin** [aws-amplify/aws-sdk-ios#2915]
I just added this code. 
	pod 'AWSMobileClient', :modular_headers => true
	pod 'AWSAuthCore', :modular_headers => true
	pod 'AWSCognitoIdentityProvider', :modular_headers => true

![AWSMobileClient swift 2020-08-06 16-52-00](https://user-images.githubusercontent.com/68773483/89540923-5ecb3300-d806-11ea-917f-deba35cd9950.png)

Can you tell me how to fix this?

**Comment by wooj2** [comment]
Hi @Maxim-Gorin ,

I'm having a little bit of trouble reproducing the issue you are seeing.  I understand you have an Objective-C project and trying to add in a couple of the libraries via CocoaPods.

Would you be able provide:
* Sample of what you have in your Podfile
* Sample code that is causing your project to fail?

Thanks!
