### ISSUE TITLE
Complier Error - Swift 5.1.3 cannot be imported by the Swift 5.2.2 compiler

### ISSUE THREAD

**Issue by sheethaljc** [aws-amplify/aws-sdk-ios#2924]
In iOS AWS library, we are facing a challenge. My XCode version was 11.3.1 and download AWS framework using Carthage. Recently I update My XCode to 11.4.1, then I was getting error like below.

module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.2 compiler: /Users/sheethal/Documents/Ondot/AppAnalystics/Project_App_Anayatics/AppAnalyticsWorkSpace/AppAnalytics/AppAnalytics/AppAnalytics-Framework/AWSMobileClient.framework/Modules/AWSMobileClient.swiftmodule/arm64-apple-ios.swiftmodule

When downloaded AWS with Carthage update (xcodebuild used latest XCode Version), then start to work in XCode 11.4.1. But will not work in older XCode (11.3.1).

Seem this will make dependency with each XCode version. Could you please help us on this?

**Comment by palpatim** [comment]
Hi @sheethaljc. The binaries that we upload for each release are built with the latest production version of Xcode that our CI/CD tool (CircleCI) supports. We [recently upgraded to use the Xcode 11.6 image](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.15.1), which should resolve this specific issue.

In future, if you encounter this issue, you can work around it by building the dependency using Carthage's `--no-use-binaries` flag. The obvious downside is that it builds the SDK from scratch, which can be a lengthy operation, but it does work around the framework incompatibilities.

Longer term, we'd like to support module stability, but as of the last time I checked, there was a bug in Xcode that prevented us from building frameworks for distribution if the exported module name was the same as a publicly-exported class. Thus, our `AWSMobileClient` exported class conflicted with the name of the `AWSMobileClient` module. It's possible that recent versions of Xcode have resolved this, but we haven't had a chance to validate that yet.

Hope this helps.
