### ISSUE TITLE
Getting secrets from parameter store

### ISSUE THREAD

**Issue by SikFar** [aws-amplify/aws-sdk-ios#2932]
Hello,

Do you still not provide support for getting secret from Parameter Store?

**Comment by wooj2** [comment]
Hi @SikFar 

Can you provide some additional information?  What do you mean by "Parameter store"?  Does it have to do with an AWS Service?  Is there any specific documentation you are looking at?

Thank you.

**Comment by palpatim** [comment]
@SikFar That is correct, we don't currently publish a Systems Manager SDK.
