### ISSUE TITLE
Multi-factor authentication(TOTP) feature support for iOS

### ISSUE THREAD

**Issue by vikkyios** [aws-amplify/aws-sdk-ios#2937]
**Which AWS Services is the feature request for?**
Amplify Multi-factor authentication on iOS & Android SDK libraries

**Is your feature request related to a problem? Please describe.**
We are using AWS Amplify as Auth module in our application which servers 7 Million users.
We Added TOTP MFA support on web, like to add same for Mobile apps.

**Describe the solution you'd like**
similar methods added to JavaScript libraries on Multi-factor authentication

**Describe alternatives you've considered**
Not sure if there are any alternate way to add TOTP!!

**Additional context**
any help towards this would be appreciated.

**Comment by wooj2** [comment]
Hi @vikkyios ,

Thank you for reaching out to us.  This seems to be a duplicate feature request, initially requested here:

https://github.com/aws-amplify/aws-sdk-android/issues/1361
