### ISSUE TITLE
i want use awss3 servers in macoS

### ISSUE THREAD

**Issue by kotercy9527** [aws-amplify/aws-sdk-ios#2938]
hello, when i develop my macOS project,i want to user awss3 servers.but i can not find the sdks,can you help me?

**Comment by kotercy** [comment]
I have the same demand

**Comment by wooj2** [comment]
Hi @kotercy9527 ,

Thanks for reaching out, but this seems to be a duplicate request that was originally requested here:
https://github.com/aws-amplify/aws-sdk-ios/issues/1603

**Comment by msuzoagu** [comment]
@wooj2 You take the time to respond here by closing but won't update on the existing request, which means that you guys know this is critical but refuse to give any feedback on existing request. The least you can do is display some respect to the developers. 

A good response can be anyone of: 

- It is in the works

-  we have decided at this time not to work on this feature

- this is the roadblock we are facing

Not responding at all shows how much you value the folks who use the solutions you build.
