### ISSUE TITLE
AWSLex fails to build in Xcode 12 beta 4

### ISSUE THREAD

**Issue by sebskuse** [aws-amplify/aws-sdk-ios#2943]
**Describe the bug**

AWSLex fails to build in Xcode 12 beta 4, producing compilation errors.

**To Reproduce**
1. Open the project in Xcode 12
2. Select the `AWSLex` scheme and build for "Any iOS device"
3. Build

**Observed Behavior**
The framework fails to compile with the message:

```
/Users/user/test/aws-sdk-ios/AWSLex/AWSLexInteractionKit.m:1003:34: error: expected a type
- (void)requestRecordPermission:(PermissionBlock)response {
                                 ^
```

**Expected Behavior**
The framework compiles.
**Environment(please complete the following information):**
 - SDK Version: 2.15.1
 - Dependency Manager: Carthage, but issue happens when building via Xcode.
 - Swift Version : 5.3
 - Xcode Version: 12.0 Beta 4

**Additional context**

The framework fails to compile on AWSLexInteractionKit.h:519:

`- (void)requestRecordPermission:(PermissionBlock)response;`

It appears in the iOS 14 SDK `PermissionBlock` has been removed as a typealias, and replaced with an inline declaration of `void (^)(BOOL granted)`. `AWSLexInteractionKit.h` should probably be updated to reflect that.

**Comment by palpatim** [comment]
I believe this will be addressed by https://github.com/aws-amplify/aws-sdk-ios/pull/2868

**Comment by palpatim** [comment]
We released this in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.15.2
