### ISSUE TITLE
Facebook SDK version needs upgrade

### ISSUE THREAD

**Issue by joeboyscout04** [aws-amplify/aws-sdk-ios#2944]
**Describe the bug**
The `AWSFacebookSignIn` portion of the AWS SDK is currently locked to version 5.8 of `FBSDKCoreKit`/`FBSDKLoginKit` in Cocoapods.  

Facebook recently had a major outage which caused many apps to crash on startup.  They recommend all client developers updating to at least 7.0.1 of the SDK:
https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md#701

Would it be possible to upgrade the AWS SDK so we can stay on top of these changes from Facebook? 

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSFacebookSignIn, Cognito, AWSMobileClient

**Environment:**
 - SDK Version: 2.15.1 
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1
 - Xcode Version: 11.6

**Comment by palpatim** [comment]
Implementation note: In addition to exploring the Facebook SDK itself, we need to understand how later versions of the SDK work with the Facebook API version. Currently Cognito only supports through API v6.0. If the SDK and API versions are tied together, that limits our ability to upgrade.

**Comment by joeboyscout04** [comment]
I believe that in recent times the FB SDK major versions reflect API version, so version 7.x.x of the FB SDK uses version 7.0 of Facebooks API, version 6.x.x uses version 6.0.

**Comment by palpatim** [comment]
Notes for the team:
* *Next steps* - understand how later versions of the SDK work with the Facebook API version. Currently Cognito only supports through API v6.0. If the SDK and API versions are tied together, that limits our ability to upgrade.

**Comment by palpatim** [comment]
This was released on the [2.17.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.17.0) release. If you pin to a particular version of the SDK, please update your Podfiles to point to at least `~> 2.17.0`.

Please note that this release includes a couple of breaking changes, so please review the release notes to see if those changes affect you.

Please let us know if you have any questions.

**Comment by royjit** [comment]
PR pending - https://github.com/aws-amplify/aws-sdk-ios/pull/3043

**Comment by ruiguoamz** [comment]
PR Pending - [#3082](https://github.com/aws-amplify/aws-sdk-ios/pull/3082)

**Comment by wooj2** [comment]
This was released as part of AWS SDK iOS 2.18.0:
https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.18.0
