### ISSUE TITLE
Crash at AWSMobileClientExtensions.swift line 109

### ISSUE THREAD

**Issue by shaikhshoeb** [aws-amplify/aws-sdk-ios#2961]
I want to do facebook, google sign in
i have used below code but after sign in 
app gets crashed at this line.  Crash at AWSMobileClientExtensions.swift line 109
Can any one help ?

My code to do login--->

 let hostedUIOptions = HostedUIOptions(scopes: ["email"], identityProvider: "Google")
       AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, hostedUIOptions: hostedUIOptions) { (userState, error) in
                 if (error as? AWSMobileClientError) != nil {
                                     
                 }
                 if let userState = userState {
                     print(userState.jsonValue)
                     print("Status: \(userState.rawValue)")
                   
                 }
             }

![Screenshot 2020-08-20 at 2 14 27 PM](https://user-images.githubusercontent.com/13327379/90748594-00b34b00-e2f0-11ea-80f9-1ac10e1be92b.png)

**Comment by shaikhshoeb** [comment]
SDK Version: Latest updated with cocaPod update.
Dependency Manager: Cocoapods
Swift Version : 5.0
Xcode Version:  11.4
Device Information iPhone x and in simulator

Device: All device
iOS Version: iOS 13.0

Yes Crash still occurs. just send the code to login with AWSMobileClient HostOption - Social login like google facebook.

**Comment by shaikhshoeb** [comment]
Using this below code


    let hostedUIOptions = HostedUIOptions(scopes: ["email"], identityProvider: "Facebook")
        AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, hostedUIOptions: hostedUIOptions) { (userState, error) in
            if (error as? AWSMobileClientError) != nil {
                // appDelegate.requestAccessToCalendar()
            }
            if let userState = userState {
                print(userState.jsonValue)

            }
        }

**Comment by shaikhshoeb** [comment]
It still crashing -
Check the attach screen shot 

![Screenshot 2020-08-25 at 1 35 20 PM](https://user-images.githubusercontent.com/13327379/91149308-8b24f180-e6d8-11ea-861e-dcdae684022a.png)

**Comment by royjit** [comment]
Hi @shaikhshoeb Can you please check if the error happens when we pass "openid" in the list of scopes while you sign in? I think the `idToken` is not returned if we do not pass the right scopes to Cognito.

```swift
let hostedUIOptions = HostedUIOptions(scopes: ["email", "openid"], identityProvider: "Facebook")
    AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, hostedUIOptions: hostedUIOptions) { (userState, error) in
        if (error as? AWSMobileClientError) != nil {
            // appDelegate.requestAccessToCalendar()
        }
        if let userState = userState {
            print(userState.jsonValue)

        }
    }
```

We will try to add a fix so that the call returns an error instead of a crash.

**Comment by palpatim** [comment]
We released this on https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.18.1
