### ISSUE TITLE
nil transfer utility after successful registration

### ISSUE THREAD

**Issue by lmramirez** [aws-amplify/aws-sdk-ios#2962]
**State your question**

I have set up my transfer utility like so:

```
        let credentialProvider = AWSBasicSessionCredentialsProvider(accessKey: uploadCredentials.accessKeyId,
                                                                     secretKey: uploadCredentials.secretAccessKey,
                                                                     sessionToken: uploadCredentials.sessionToken)

        guard let configuration = AWSServiceConfiguration(region: .USWest2, credentialsProvider: credentialProvider) else {
            completion?(.failure(.configurationFailed))
            return
        }
        configuration.sharedContainerIdentifier = config.appGroupId

        AWSS3TransferUtility.register(
            with: configuration,
            transferUtilityConfiguration: defaultTransferUtilityConfiguration,
            forKey: utilityKey
        ) { error in
            if let error = error {
                completion?(.failure(.failedToRegister(error: error)))
                return
            }

            guard let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: utilityKey) else {
                // *** This code path should never be hit, but it sometimes is ****
                completion?(.failure(.utilityNotFound))
                return
            }

            let uploadService = VideoFileUploadService(config: config,
                                                       transferUtility: transferUtility,
                                                       videoId: videoId,
                                                       s3Bucket: s3Bucket)

            completion?(.success(uploadService))
        }
```

I've noticed in my application logs however, that on occasion, the `transferUtility` is `nil`. The docs indicate that this should only ever happen when there was an error in the registration, however, we can see that I am checking for the error in the lines preceding the getting of the transfer utility. How is this possible?

**Which AWS Services are you utilizing?**
S3

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.13.4
 - Dependency Manager: cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 10.4, but also many others
 - iOS Version: 13.6
 - Specific to simulators: No

**Comment by lawmicha** [comment]
Hi @lmramirez, Could you enable verbose logging?
```
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

Do you have any relevant logs to share when it successfully registers but then retrieving it returns nil?

related code
1. init https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSS3/AWSS3TransferUtility.m#L389
2. retrieve for key https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSS3/AWSS3TransferUtility.m#L331

**Comment by wooj2** [comment]
Hi @lmramirez 

I chatted with @royjit , and he noticed that the completion block could be called before the execution of `registerS3TransferUtilityWithConfiguration:transferUtilityConfiguration:forKeycompletionHandler:` completes.

Sure enough, I looked into this and seems correct.  Most of the time this won't happen because of a task that gets kicked off in `linkTransfersToNSURLSession:tempTransferDictionary:completionHandler`, but it seems very possible for the completion handler to be fired off in the same execution as the calling code.  Oops!  To fix this, I've submitted a PR here, which wraps the completion handler and defers the call of the completion handler.

Thanks again for reporting this!

**Comment by lmramirez** [comment]
@wooj2 thanks for taking a look at this!

**Comment by wooj2** [comment]
Hi @lmramirez !

Thanks again for submitting this bug report.  I've submitted the code change to `main`, and should be included as part of our next release.  I will be optimistically closing this ticket for now, but feel free to re-open if you have any questions and/or concerns regarding this issue.

Thanks again!
