### ISSUE TITLE
OTP Authentication using Cognito custom authentication

### ISSUE THREAD

**Issue by Purnachndar** [aws-amplify/aws-sdk-ios#2963]
**State your question**
I'm able to successfully receive the SMS and login but end up receiving multiple OTPs (* 3 OTPs)

**Which AWS Services are you utilizing?**
Cognito
Lambda

**Provide code snippets (if applicable)**
**CreateAuthChallenge**

const AWS = require('aws-sdk');
exports.handler = (event, context, callback) => {
//Create a random number for otp
const challengeAnswer = Math.random().toString(10).substr(2, 6);
const phoneNumber = event.request.userAttributes.phone_number;
//sns sms
const sns = new AWS.SNS({ region: 'us-east-1' });
sns.publish(
{
Message: 'your otp: ' + challengeAnswer,
PhoneNumber: phoneNumber,
MessageStructure: 'string',
MessageAttributes: {
'AWS.SNS.SMS.SenderID': {
DataType: 'String',
StringValue: 'AMPLIFY',
},
'AWS.SNS.SMS.SMSType': {
DataType: 'String',
StringValue: 'Transactional',
},
},
},
function (err, data) {
if (err) {
console.log(err.stack);
console.log(data);
return;
}
console.log("Data In Create", data);
return data;
}
);
//set return params
event.response.privateChallengeParameters = {};
event.response.privateChallengeParameters.answer = challengeAnswer;
event.response.challengeMetadata = 'CUSTOM_CHALLENGE';
callback(null, event);
};

**Define Auth Challenge**

exports.handler = (event, context) => {
if (event.request.session.length === 0) {
event.response.issueTokens = false;
event.response.failAuthentication = false;
event.response.challengeName = 'CUSTOM_CHALLENGE';
} else if (
event.request.session.length === 1 &&
event.request.session[0].challengeName === 'CUSTOM_CHALLENGE' &&
event.request.session[0].challengeResult === true
) {
event.response.issueTokens = true;
event.response.failAuthentication = false;
} else {
event.response.issueTokens = false;
event.response.failAuthentication = true;
}
context.done(null, event);
};

**Pre sign-up Function**

exports.handler = (event, context, callback) => {
// Confirm the user
event.response.autoConfirmUser = true;
// Set the email as verified if it is in the request
if (event.request.userAttributes.hasOwnProperty('email')) {
event.response.autoVerifyEmail = true;
}
// Set the phone number as verified if it is in the request
if (event.request.userAttributes.hasOwnProperty('phone_number')) {
event.response.autoVerifyPhone = true;
}
// Return to Amazon Cognito
callback(null, event);
};

**Verify function**

exports.handler = (event, context) => {
if (event.request.privateChallengeParameters.answer === event.request.challengeAnswer) {
event.response.answerCorrect = true;
} else {
event.response.answerCorrect = false;
}
context.done(null, event);
};

Thanks in Advance :) 
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by Purnachndar** [comment]
Hi Team, 

Could someone here help me with how to fix this issue??

**Comment by royjit** [comment]
Hi @Purnachndar 

Create auth challenge might be called multiple times in  your auth flow. It looks like you are not checking if it is the right step to send the SMS. In your `CreateAuthChallenge` check `event.request.challengeName == 'CUSTOM_CHALLENGE' ` and then trigger the SMS logic.

An example if given at the end of this doc - https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-create-auth-challenge.html

**Comment by Purnachndar** [comment]
Hi @royjit 

I tried all possible scenarios but couldn't able to fix the issue. Please check the source code of CreateAuthChallenge.


const AWS = require('aws-sdk');
exports.handler = (event, context, callback) => {
  //Create a random number for otp
  const challengeAnswer = Math.random().toString(10).substr(2, 6);
  const phoneNumber = event.request.userAttributes.phone_number;
  //sns sms
  const sns = new AWS.SNS({ region: 'us-east-1' });
  if (!event.request.session || !event.request.session.length && event.request.challengeName === 'CUSTOM_CHALLENGE'){
     event.response.publicChallengeParameters = { trigger: 'true' };
    sns.publish(
      {
        Message: 'your otp: ' + challengeAnswer,
        PhoneNumber: phoneNumber,
        MessageStructure: 'string',
        MessageAttributes: {
          'AWS.SNS.SMS.SenderID': {
            DataType: 'String',
            StringValue: 'AMPLIFY',
          },
          'AWS.SNS.SMS.SMSType': {
            DataType: 'String',
            StringValue: 'Transactional',
          },
        },
      },
      function (err, data) {
        if (err) {
          console.log(err.stack);
          console.log(data);
          return;
        }
        return data;
      }
    );
    event.response.privateChallengeParameters = {};
    event.response.privateChallengeParameters.answer = challengeAnswer;
    event.response.challengeMetadata = 'CUSTOM_CHALLENGE'
    // `CODE-${challengeAnswer}`
  }
  //set return params

  callback(null, event);
};

Thanks in advance

**Comment by Purnachndar** [comment]
Hi @royjit it would be great if you help me out.

Thanks in advance :)

**Comment by lawmicha** [comment]
@Purnachndar were you able to resolve your issue?

**Comment by Purnachndar** [comment]
Yes, I resolved @lawmicha
