### ISSUE TITLE
Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=0 "(null)" UserInfo={__type=ValidationException, message=1 validation error detected: Value 'YourIdentityPoolId' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+

### ISSUE THREAD

**Issue by gurjindersinghkhalsa** [aws-amplify/aws-sdk-ios#2988]
**Describe the bug**
I am using AWSRekognition to comapare two images. But i am getting the above error

**To Reproduce**
1. Initialize AWSCognitoCredentialsProvider with region and Identity poll id
2. AWSServiceConfiguration using region and credentialsProvider
3. Make AWSRekognition with key USWest2Rekognition
4. Register AWSRekognition with configuration and key
5. Call compareFaces method of Rekognition

**Observed Behavior**
It is not showing response

**Expected Behavior**
It should show response whether two images contains the same person

**Code Snippet**
let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USWest2,
identityPoolId:"us-west-2:xxxxxx-xxxx-xxxx-xxxx-xxxxxxx")
let configuration = AWSServiceConfiguration(region:.USWest2, credentialsProvider:credentialsProvider)
AWSServiceManager.default().defaultServiceConfiguration = configuration
let Rekognition = AWSRekognition(forKey: "USWest2Rekognition")
AWSRekognition.register(with: configuration!, forKey: key)
Rekognition.compareFaces(request) { (respone, error) in
   print(respone) // nil
  print(error) // showing above error
}

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
I am using AWSRekognition

**Environment(please complete the following information):**
 - SDK Version: 2.13.4
 - Dependency Manager: Cocoapods
 - Swift Version :  5.0
 - Xcode Version: 11.6

**Device Information (please complete the following information):**
 - Device: iPhone XR
 - iOS Version: 13.5
```

**Comment by gurjindersinghkhalsa** [comment]
I have change the AWSRekognition key to "testCompareFaces"
let Rekognition = AWSRekognition(forKey: "testCompareFaces")
Now getting this error
**(Error Domain=com.amazonaws.AWSNetworkingErrorDomain Code=2 "URLSession is nil or invalidated" UserInfo={NSLocalizedDescription=URLSession is nil or invalidated})**

**Comment by palpatim** [comment]
The error message you posted in the issue title suggests that your Identity Pool is not configured correctly: it looks like you may have copied and pasted documentation code that includes an pool ID value of `YourIdentityPoolId`. Please verify the configuration is correct and provide an updated code sample.

Next: You're attempting to retrieve the client before registering it:

```swift
let Rekognition = AWSRekognition(forKey: "USWest2Rekognition")
AWSRekognition.register(with: configuration!, forKey: key)
```

Those two lines should be reversed: register it first, then instantiate it.

Hope this helps.
