### ISSUE TITLE
Will Amazon Pinpoint be affected by Apple’s New Policy Opt-in Consent for Advertising Identifiers?

### ISSUE THREAD

**Issue by cjeremylin** [aws-amplify/aws-sdk-ios#2991]
**State your question**

Since [Apple’s iOS 14](https://developer.apple.com/app-store/user-privacy-and-data-use/) Requires [New Opt-in Consent for Advertising Identifiers](https://www.lexology.com/library/detail.aspx?g=9f281437-5d27-41fe-a6c6-7a9f8ea0d55c), as Pinpoint (Amazon Mobile Analytics) events tracking user, we are considering Pinpoint's client_id will be the new unique device_id for iOS devices. Therefore, here's our questions for the client_id:

1) The uniqueness of the client_id; will different iOS device generate identical client_id?
2) Base on what situation, the client_id will be changed? How about reinstalling the app?
3) If users opt-out IDFA(ID for advertisers), any impact to the client_id?
4) Did the definition of client_id change since 2015 or 2016?

p.s: We still using legacy (2016) mobile analytics SDK

Thanks. 

**Which AWS Services are you utilizing?**
Amazon Mobile Analytics

**Provide code snippets (if applicable)**
Record Custom Events

    CustomEvent customEvent = new CustomEvent("LevelComplete");

    // Add attributes
    customEvent.AddAttribute("LevelName","Level1");
    customEvent.AddAttribute("CharacterClass","Warrior");
    customEvent.AddAttribute("Successful","True");

    // Add metrics
    customEvent.AddMetric("Score",12345);
    customEvent.AddMetric("TimeInLevel",64);

    // Record the event
    analyticsManager.RecordEvent(customEvent);

**Environment(please complete the following information):**
 - SDK Version: 2.2.4
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by palpatim** [comment]
We are evaluating this and will provide a response when we have more information.

**Comment by royjit** [comment]
We have added the information into our doc - https://docs.amplify.aws/lib/info/overview/q/platform/ios Please take a look.
