### ISSUE TITLE
All the external frameworks are deprecated

### ISSUE THREAD

**Issue by UncleRic** [aws-amplify/aws-sdk-ios#2992]
**Describe the bug**
Attempting to compile example projects yield compiler warnings.
Code should be modernized to at least iOS 12.

**To Reproduce**
1. open Xcode.
2. open any example project.

**Observed Behavior**
Compiler Warnings

**Expected Behavior**
Clean compile.

**Configuration**
Merely out-of-the-box

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

Screenshots
All the associated frameworks
<img width="819" alt="Screen Shot 2020-09-01 at 12 58 28 PM" src="https://user-images.githubusercontent.com/862735/91900071-f6c80b00-ec52-11ea-9e5b-93f2c55ef27b.png">

**Environment(please complete the following information):**
 - SDK Version: Given Sample
 - Dependency Manager:  Cocoapods
 - Swift Version : 5.3
 - Xcode Version: 12.0 beta 6 (12A8189n)

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version:  iOS 9+

```
AWSDDLog.sharedInstance.logLevel = .debug
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Comment by diegocstn** [comment]
Closing in favor of https://github.com/aws-amplify/aws-sdk-ios/issues/3025
