### ISSUE TITLE
Uploading to App Store fails due to Invalid Mach-O Format when bitcode is enabled for app target

### ISSUE THREAD

**Issue by EdGonzalez-** [aws-amplify/aws-sdk-ios#3005]
**Describe the bug**
Uploading to App Store fails with the following:

> App Store Connect Operation Error
> ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "Flight Manager.app/Frameworks/AWSLambda.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains armv7(machine code) and arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

**To Reproduce**
1. Archive app with AWSLambda.framework (app target must have bitcode enabled)
2. Upload to App Store

**Observed Behavior**
Errors due to invalid mach-o format

Note:  If bitcode is disabled, does not error.  Appears to be a regression of the issue resolved #2817 

**Expected Behavior**
Should upload with no error

**Environment(please complete the following information):**
 - SDK Version: 2.15.0
 - Dependency Manager:  None
 - Swift Version :  5.2
 - Xcode Version:  11.7

**Device Information (please complete the following information):**
 - Device:  Any
 - iOS Version:  Any

**Comment by palpatim** [comment]
You're showing "Dependency Manager: None"--does that mean you're downloading binary frameworks, or building the project as source?

**Comment by EdGonzalez-** [comment]
Downloading binary frameworks.

**Comment by palpatim** [comment]
@EdGonzalez- As of 2.22.2, we are distributing the binary frameworks as XCFrameworks. Can you try with this version and see if you still see the issue?

**Comment by EdGonzalez-** [comment]
@palpatim Latest frameorks are working properly. Thanks.
