### ISSUE TITLE
[Objective-C - Cocoapods] Build failure since version 2.12.3 (AWSPinpointTargetingModel.h)

### ISSUE THREAD

**Issue by FedeRelab** [aws-amplify/aws-sdk-ios#3007]
**Describe the bug**
Since version 2.13.3 I got a double error in AWSPinpointTargetingModel.h (line 2403) using Objective-C (Cocoapods).
It seems that the word "operator" can't be used for name of a variable.

**To Reproduce**
1. Build
2. See errors

**Code Snippet**
@property (nonatomic, assign) AWSPinpointTargetingOperator operator;

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
Pinpoint

**Screenshots**
<img width="288" alt="Schermata 2020-09-09 alle 09 47 01" src="https://user-images.githubusercontent.com/34335916/92570910-c00d7880-f282-11ea-907f-eedd5d7232c3.png">
<img width="935" alt="Schermata 2020-09-09 alle 10 03 48" src="https://user-images.githubusercontent.com/34335916/92572040-2cd54280-f284-11ea-9626-20273a7e68ab.png">

**Environment(please complete the following information):**
 - SDK Version: 2.16.0
 - Dependency Manager: Cocoapods
 - Swift Version : Objective-C
 - Xcode Version: 11.7

**Device Information (please complete the following information):**
 - Device: iPhoneX
 - iOS Version: iOS 13.7
 - Specific to simulators:

**Relevant Console Output**
Pods/Headers/Public/AWSPinpoint/AWSPinpointTargetingModel.h:2403:68: Expected a type
Pods/Headers/Public/AWSPinpoint/AWSPinpointTargetingModel.h:2403:1: Property requires fields to be named

**Comment by royjit** [comment]
Hi @FedeRelab 

I tried to build a new objc project with the AWSPinpoint SDK and it worked without any issue. You mentioned two versions in your bug report. So I tried with 2.12.3, 2.13.3 and 2.16.0 and it all worked. Here is the pod file:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjecTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjecTest
  pod 'AWSPinpoint', '~> 2.13.3'

end

```

Can you try a clean build and see if it get resolved? Please share the Podfile if you are still facing the issue.
