### ISSUE TITLE
didCompletePasswordAuthenticationStepWithError not calling when sign in.

### ISSUE THREAD

**Issue by KosalaFMF** [aws-amplify/aws-sdk-ios#3009]
New to AWS framework but it work like anything I am not faced any issue until today from last 1 week
-Sign up Works fine get OTP (phone number verification)
-Confirm Sign Up Works Fine (Successfully confirm)
-Sign in getting an issue.
bellow code:

-(IBAction)didTapOnSignInButton:(id)sender{  self.passwordAuthenticationCompletion.result = [[AWSCognitoIdentityPasswordAuthenticationDetails alloc] initWithUsername:_usernameText password:self.ibPassword.text];
NSLog(@"%@",self.passwordAuthenticationCompletion);
}

-(void) getPasswordAuthenticationDetails: (AWSCognitoIdentityPasswordAuthenticationInput *) authenticationInput  passwordAuthenticationCompletionSource: (AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails *> *) passwordAuthenticationCompletionSource {
    self.passwordAuthenticationCompletion = passwordAuthenticationCompletionSource;
    dispatch_async(dispatch_get_main_queue(), ^{
        if(!self.usernameText)
            self.usernameText = authenticationInput.lastKnownUsername;
    });   
}
-(void) didCompletePasswordAuthenticationStepWithError:(NSError*) error {
    dispatch_async(dispatch_get_main_queue(), ^{
        if(error){
              nslog(@"Error ");
        }else{
            self.usernameText = nil;
            [self dismissViewControllerAnimated:YES completion:nil];
        }
    });
}

pods using --- $awsVersion = '~> 2.10.0'
                          pod 'AWSCore', '~> 2.10.0'
                          pod 'AWSCognitoIdentityProvider', $awsVersion

Never called getPasswordAuthenticationDetails and didCompletePasswordAuthenticationStepWithError

when I was call user.getSession() getPasswordAuthenticationDetails calling but didCompletePasswordAuthenticationStepWithError not calling

what is wrong.......

Following this document
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Objective-C/CognitoYourUserPoolsSample

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.10.0]
 - Dependency Manager: Cocoapods

**Device Information (please complete the following information):**
 - Device: iPhone 7
 - iOS Version: 13

**Comment by royjit** [comment]
Hi @KosalaFMF 

You mentioned that it was working without any issue one week back? Did you change anything in the code? or updated to a newer version? As per your bug report, you are using an older version of the SDK, you can try with the latest SDK and see if the issue exists.

Also, if you are starting new, I recommend you to try our latest iOS Amplify library - https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios The new library does all the heavy lifting for you, sign up and sign in should be an easier experience.

New signIn api:

```swift
Amplify.Auth.signIn(username: username, password: password) { result in
        switch result {
        case .success:
            print("Sign in succeeded")
        case .failure(let error):
            print("Sign in failed \(error)")
        }
    }
```

**Comment by KosalaFMF** [comment]
I did `AWSCognitoIdentityPasswordAuthenticationDetails *result = [[AWSCognitoIdentityPasswordAuthenticationDetails alloc] initWithUsername:[defaults objectForKey:@"unameTyped"] password:[defaults objectForKey:@"pwrdTyped"]];
            self.passwordAuthenticationCompletion.result = result;` this thing inside `getPasswordAuthenticationDetails` method , problem solved. thanks @royjit
