### ISSUE TITLE
Can i use aws-sdk-ios library for Share Extension in iOS ?

### ISSUE THREAD

**Issue by mdawais92** [aws-amplify/aws-sdk-ios#3013]
I am using aws-sdk-ios for iOS share extension. I wanna use this for uploading media in share extension. Is this library is supported for ios share extension? If yes, how?

When i add this via pod to my extension target. I got compilation errors.
[UIApplication sharedApplication] is not supported as i wanna use this in extension.

**Comment by wooj2** [comment]
Unfortunately the AWS SDK for iOS is only supported for iOS apps, not extensions (or app clips, or widgets) at the moment.  We have flagged this as a feature request here:
https://github.com/aws-amplify/aws-sdk-ios/issues/2978

Given that this has already been reported, I will be closing this issue.
