### ISSUE TITLE
Add Support to Swift Package Manager

### ISSUE THREAD

**Issue by julioarregoitia** [aws-amplify/aws-sdk-ios#3076]
**Which AWS Services is the feature request for?**
PinPoint

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Just for use this library with Swift Package Manager

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by royjit** [comment]
Closing as dup https://github.com/aws-amplify/aws-sdk-ios/issues/313

**Comment by julioarregoitia** [comment]
Okey thanks, to many issues to check before post the my. Best regards
