### ISSUE TITLE
How to get Access Token after getting Identity ID.

### ISSUE THREAD

**Issue by KosalaFMF** [aws-amplify/aws-sdk-ios#3079]
This is the code what I have added.

func awsSignInFacebook(fbAuthToken: String){

        let logins = ["graph.facebook.com" : fbAuthToken]
        let customIdentityProvider = CustomIdentityProvider(tokens: logins)
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .APSouth1, identityPoolId:              AWSConstants.CognitoFederatedIdentityUserPoolId, identityProviderManager: customIdentityProvider)

        let configuration = AWSServiceConfiguration(region: .APSouth1, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        credentialsProvider.getIdentityId().continueWith { (task: AWSTask!) -> AnyObject? in
            
            if (task.error != nil) {
                print("Error: " + (task.error?.localizedDescription)!)
                
            } else {
                // the task result will contain the identity id
                let cognitoId = task.result
                Log.add(info: "Cognito ID : \(cognitoId)")
            }
            return nil
        }
    }

class CustomIdentityProvider: NSObject, AWSIdentityProviderManager {

    var tokens : [String : String]?
    
    init(tokens: [String : String]) {
        self.tokens = tokens
    }
    
    @objc func logins() -> AWSTask<NSDictionary> {
        return AWSTask(result: tokens! as NSDictionary)
    }
### }

I am getting cognitoId successfully, so now how can I get AccessToken.

**Comment by lawmicha** [comment]
Hi @KosalaFMF, could you explain what you want to do with the access token? Are you trying to pass in the `fbAuthToken` to Cognito Identity Pool service for federated sign in? I don't think Cognito Identity Pool will provide an access token and only the identityId. 

Have you tried AWSMobileClient and call federatedSignIn with the fb token? https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios

**Comment by KosalaFMF** [comment]
Hi @lawmicha , thanks for responding, yah they returning only identity ID, I have managed with that, now I need to do apple sign in with this way, I am not using MobileClient, because full login flow did by this SDK, now I need to implement Apple sign in only, can you please help me to do SIWA with this AWS SDK.I need objective c sample.

**Comment by royjit** [comment]
Hi @KosalaFMF 

We do not have a sample with Objective C. But you can do the same flow that you used for Facebook to signIn with Apple.

1. Use Apple's api to sign in : https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple
2. Pass the identity id that you got after signIn to Cognito SDK something like this:
```seift
let logins = ["appleid.apple.com" : appleIdToken]
let customIdentityProvider = CustomIdentityProvider(tokens: logins)
```

Also here is the documentation that setup Cognito for Apple signIn. - https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios#set-up-sign-in-with-apple

**Comment by KosalaFMF** [comment]
Yeah Thats works fine @royjit
