### ISSUE TITLE
Storage: Background session not validated in iOS Simulator

### ISSUE THREAD

**Issue by preethiChimerla** [aws-amplify/aws-sdk-ios#3083]
**An error occurred on the xpc connection to setup the background session: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process.} **

I am running XCUITest on Xcode 11.5 and Xcode 12.
I am trying to get a file from S3 before the UITest starts executing. 
I provide details (bucket name, file name) to setup configuration to connect to S3. 
I am able to successfully get the file and use it when I run the tests on iOS 11, 12 simulators. 
But When I try to do the same on iOS Simulator. I am having an error that says my background session is not validated.

An error occurred on the xpc connection to setup the background session: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process.}

I get the error on AWSS3TransferUtility.m file.
Exactly after executing this line: 
 _session = [NSURLSession sessionWithConfiguration:configuration
                                                 delegate:self
                                            delegateQueue:nil];

A clear and concise description of what the bug is. Please be as detailed as possible and help us help you.

**To Reproduce**
1. Go to 'Xcode 11.5 or 12, simulator iOS > 13 '
2. Create a Sample UITest in your project. In the XCTest setup, 
Try to access a AWSS3 bucket using AWS transferutility.
Provide configuration to connect to S3. 
3. now run the app.
4.  you should see the error when the configuration is setting up.

An error occurred on the xpc connection to setup the background session: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process.}

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: latest SDK pod file
 - Dependency Manager: [ Cocoapods ]
 - Swift Version : [5.0]
 - Xcode Version: [11.5, 12]

**Device Information (please complete the following information):**
 - Device: [ iOS 13, 14 Simulator ]
 - iOS Version: [e.g. iOS 13, iOS 14]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here like your specific use case.

**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
AWSDDLog.sharedInstance.logLevel = .debug
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Comment by palpatim** [comment]
I've seen some anecdotes on Xamarin forums that indicate your host app needs to be signed for background sessions to be properly validated. We'll need to try and reproduce this issue in an unsigned app, then add signing and see if the problem goes away. If so, we need to understand what the error actually means from a practical standpoint. Does it prevent any transfers from occurring? Only background transfers?

**Comment by 1Cor125** [comment]
In [this closed ticket](https://github.com/xamarin/xamarin-macios/issues/7101) the team discussed trying to match Xcode's behavior of signing apps automatically when using a sim. This sort of thing creates friction for devs. Now if I build a little sample app in one of my package repos I need to sign the app to make sure everything works well in the sim. Is there a ticket somewhere to track this request? That way we don't have devs continuing to report this as a bug only to be told to sign their app to run it in the sim.

**Comment by Rishabh6211** [comment]
Hi @preethiChimerla did you solve it yet.
I am facing same issue

**Comment by brennanMKE** [comment]
@preethiChimerla Were you able to try associating a provisioning profile with your app to authorize background sessions? It appears this is either a restriction in the iOS Simulator which is intentional or a bug. Please try a current version of Xcode and the iOS Simulator and associating a provisioning profile.

**Comment by umair0214** [comment]
Hi @brennanMKE,
I am getting the same error. Working well on the device(IOS15) but not on Simulator(IOS15). I am using the latest version of Xcode 13.1 and AWS

I am also getting it in the same file. AWSS3TransferUtility.m file.

Exactly after executing this line:
_session = [NSURLSession sessionWithConfiguration:configuration
delegate:self
delegateQueue:nil];

Did you get a chance to fix this issue??
