### ISSUE TITLE
iOS SDK EndpointProfileUser store user attributes

### ISSUE THREAD

**Issue by yannianliu** [aws-amplify/aws-sdk-ios#3086]
I saw AWS SDK for Android 2.16.11 has began to support storing user attributes, which will persist even after updating the endpoint.
￼Can iOS SDK has the same functionality soon?
Thank you

**Comment by lawmicha** [comment]
Hi @yannianliu, I will mark this as a feature request

related Android, https://github.com/aws-amplify/aws-sdk-android/pull/1535

**Comment by ruiguoamz** [comment]
PR https://github.com/aws-amplify/aws-sdk-ios/pull/3142 has been merged in, pending release.

**Comment by palpatim** [comment]
We released this on https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.18.1
