### ISSUE TITLE
AWSS3TransferUtilityMultiPartUploadTask  resume,Failing transfer

### ISSUE THREAD

**Issue by Guolanlan** [aws-amplify/aws-sdk-ios#3087]
** I use AWSS3TransferUtility to getMultiPartUploadTasks,then AWSS3TransferUtilityMultiPartUploadTask to resume , Always report errors
**
why ??? What did i do wrong？？？

this is error  log

Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Message=Expected to send [13988147], but sent [12582912] and there are no remaining parts. Failing transfer }

**Comment by lawmicha** [comment]
is this the same question as https://github.com/aws-amplify/aws-sdk-ios/issues/3088 ? closing as duplicate, feel free to provide more details over in the other Issue
