### ISSUE TITLE
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Message=Expected to send [13988147], but sent [12582912] and there are no remaining parts. Failing transfer }

### ISSUE THREAD

**Issue by Guolanlan** [aws-amplify/aws-sdk-ios#3088]
AWSS3TransferUtility *S3TransferUtility = [AWSS3TransferUtility S3TransferUtilityForKey: FS3S3TransferUtility];
    NSArray * resultArray = [[S3TransferUtility getMultiPartUploadTasks] result];
 for (AWSS3TransferUtilityMultiPartUploadTask * uploadTask in resultArray) {
        if ([uploadTask.key isEqualToString:blockParam.taskey]) {
                    [uploadTask resume];
}
[uploadTask setCompletionHandler:^(AWSS3TransferUtilityMultiPartUploadTask * _Nonnull task, NSError * _Nullable error) {
                if (error) {
}

always this error  /// why???
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Message=Expected to send [13988147], but sent [12582912] and there are no remaining parts. Failing transfer }

**Comment by Guolanlan** [comment]
but  _progress is finish

**Comment by lawmicha** [comment]
Hi @Guolanlan sorry for the inconvenience caused.

Could you provide the SDK version that you are using? The latest is 2.17.0 if you are't on the latest already

What reproduce steps can I take to set up my app to reproduce your issue? did you run `amplify add storage`?

Does this happen consistently with multipart upload? 

Do you have a file size requirement to use multipart upload over a normal upload? Does it work with just upload?

If you are starting off AWS, we recommend getting started with the Amplify framework with the S3 storage plugin here: https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios#initialize-amplify-storage

**Comment by Guolanlan** [comment]
Improper use, it's okay now, there is no such problem

**Comment by Guolanlan** [comment]
App Uninstalll ,again start
