### ISSUE TITLE
Endpoints is not creating properly in dashboards

### ISSUE THREAD

**Issue by fbarraganef** [aws-amplify/aws-sdk-ios#3126]
I checking out my pinpoint dashboard and I seeing the revenue, units sold, paying users. 

But when I check the endpoints or something related with the endpoint is 0.

<img width="1253" alt="Screen Shot 2020-09-17 at 12 10 40" src="https://user-images.githubusercontent.com/28632162/93504390-085e1380-f8df-11ea-8d2e-ff4fb5eb321f.png">

¿What could be the issue? 

Because If I want create a campaign, the first need I need is the endpoints.

**Comment by wooj2** [comment]
Hi @fbarraganef 

1.  Are you able to provide reproduction steps for the issue you are seeing where you are seeing 0 for purchases for endpoint?  I would like to reproduce what you are seeing.  It is unclear if SDK is incorrectly sending information, or the data is not being rendered correctly.  Perhaps you can turn on logging, and inspect the payload you are sending and check to see if any information is missing.  To turn on logging you can do this by adding this to your AppDelegate.
```
AWSDDLog.sharedInstance.logLevel = .verbose
```

2.  With regards to creating a dynamic segment (and sending targets messages to your users).  I was unable to reproduce what you are seeing.  I followed the instructions to enable push notifications located here:
https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios

After following the guide above, and running an instance of my application, I was immediately able to create a dynamic segment for my application.  Is there anything different in your application that is different from the documentation?  If so, can you please explain, or provide sample code where appropriate?

**Comment by fbarraganef** [comment]
@wooj2 thank you, I was able to reach my device using the endpoints from the dynamic segment. 

I had tu put the email from the user to the .address parameter from the targetingClient of the pinpoint object. Once I assigned this parameter I was able to detect the endpoint.

![Screen Shot 2020-10-27 at 16 55 25](https://user-images.githubusercontent.com/28632162/97371084-14da7200-1876-11eb-9665-4ef0657481f2.png)

But I don't know why once the user email is listed in the filter of the segment after a period of time it disappear then I'm not able to search it in the filter box using the email. 

What I have to take in consideration or what is happening? is there a caducation time for the endpoints? or something is overwritten?

Thanks

**Comment by wooj2** [comment]
Hi @fbarraganef 

Unfortunately, I'm not super familiar with how long a email should show up/disappear.  It might be an issue with the filter you're setting, or it could be a service bug.  I'm guessing you've taken a look at our [documentation on segments](https://docs.aws.amazon.com/pinpoint/latest/userguide/segments.html) and didn't find what you were looking for...

Perhaps you could try to post your question on the [AWS Forums for pinpoint](https://forums.aws.amazon.com/forum.jspa?forumID=225) (or look for an existing issue?) as this sounds like more of a Pinpoint related issue rather than a iOS/SDK client issue.

Best of luck!
