### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by tdouglas1313** [aws-amplify/aws-sdk-ios#313]
https://swift.org/package-manager/#conceptual-overview

**Comment by nzayatz14** [comment]
+1

**Comment by bobhigs** [comment]
+1

**Comment by moghtaderi** [comment]
+1, I'm having the same request!

**Comment by ahawk66** [comment]
+1

**Comment by sekelj13** [comment]
+1

**Comment by yosuke-matsuda** [comment]
We are closely [monitoring](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageManagerCommunityProposal.md#support-for-other-languages) the development of Swift Package Manager. We'll update the thread when we have something we can share. Thanks.

**Comment by satyaavasarala** [comment]
+1

**Comment by futoase** [comment]
+1

**Comment by tdouglas1313** [comment]
I believe Objective-C is still not supported, But has there been any talks about writing a swift version that is linux compatible. It would be really nice to be able to talk to services like DynamoDB using swift on an EC2 without having to use the low level API.

**Comment by ilazakis** [comment]
+1

**Comment by BrianL3** [comment]
+1

**Comment by medampudi** [comment]
+1

**Comment by hervouinc** [comment]
+1

**Comment by kochrt** [comment]
+1

**Comment by foscomputerservices** [comment]
+1

**Comment by alexch2000** [comment]
+1

**Comment by jthomas** [comment]
👍

**Comment by noppoMan** [comment]
@tdouglas1313 @nzayatz14 @bobhigs @moghtaderi @ahawk66 @sekelj13 @yosuke-matsuda @satyaavasarala @futoase @tdouglas1313 @ilazakis @BrianL3 @medampudi @hervouinc @kochrt @foscomputerservices @alexch2000 @jthomas 

I've alternatively released an AWS-SDK written purely in Swift. It also supports Linux and Swift PM.
https://github.com/noppoMan/aws-sdk-swift

Now I using it in our production environment.

**Comment by rex-remind101** [comment]
Please do this

**Comment by justinpawela** [comment]
I assume this would be a prerequisite to supporting Swift on Lambda... would be very nice.

**Comment by arekt** [comment]
+1 to support swift package manager, it is more stable now

**Comment by palpatim** [comment]
We are closing this request for the time being.

1. Swift Package Manager [doesn't support iOS modules like UIKit](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#depending-on-apple-modules). Workarounds exist to allow SPM-managed dependencies to be used in iOS apps, but they currently are fairly cumbersome.
2. Our SDK is intended to be used in an iOS app and as such, relies on iOS frameworks (e.g. UIKit). Enabling SPM support in our SDK would imply support for Linux and MacOS, neither of which are actually supported.

So, although they each have their own tradeoffs, we recommend at this time that developers continue to use either CocoaPods or Carthage as a dependency manager, or rely directly on building the SDK frameworks as part of your app.

**Comment by rex-remind101** [comment]
@palpatim for many of us the intent isn't to use SPM for iOS but for server side systems on AWS.

I understand that currently this SDK is intended to be used on iOS only and that currently, from what I can tell, it is bound to Obj-C and therefor not capable server-side. On that note, I'm only stating this to voice the needs of many in the Swift community. Many of us hope that some collaboration between the AWS team and the community can spin up towards work on a server-side Swift SDK.

**Comment by palpatim** [comment]
Thanks for the note @rex-remind101. We're investigating the request to make a server-side Swift SDK: please see #1030.

**Comment by mxcl** [comment]
Just to add here, I wanted to write a Swift script that uses AWS stuff. So this would be very useful.

**Comment by w0mba7** [comment]
Can we get this added now that there is support for iOS apps in Xcode 11?

**Comment by palpatim** [comment]
@w0mba7

Although we do not have plans for server-side support, official iOS support makes this a more reasonable option now. I'm reopening this and adding it to our feature request backlog.

**Comment by w0mba7** [comment]
Awesome thanks!

**Comment by dlednik** [comment]
+1

I'm surprised it's written in ObjectiveC and not with Swift from the start. But we really need a plain swift library so it can be used in plain linux swift projects. I was hoping I can write my project with swift but looks like I'm stuck with C no :D

**Comment by marwey** [comment]
> @w0mba7
> 
> Although we still do not have plans for server-side support, official iOS support makes this a more reasonable option now. I'm reopening this and adding it to our feature request backlog.

The Smoke framework supports server-side Swift for AWS services.  Including the Swift package manager. See here: https://github.com/amzn/smoke-aws

**Comment by hishma** [comment]
+1

**Comment by PalringoBen** [comment]
+1

**Comment by lvnkmn** [comment]
+1

**Comment by mruvim** [comment]
+1

**Comment by makoni** [comment]
+1

**Comment by justin-robinson** [comment]
Any updates on this?

**Comment by hodovani** [comment]
+1

**Comment by JeffESchmitz** [comment]
+1

**Comment by harryhan24** [comment]
+1

**Comment by lakersr8ers** [comment]
+1

**Comment by BrentMifsud** [comment]
+1

**Comment by AlbertoLourenco** [comment]
+1

**Comment by rap-morgan** [comment]
+1

**Comment by JamalBelilet** [comment]
Any updates?

**Comment by farshadtx** [comment]
+1

**Comment by prayash** [comment]
Hi, any updates on this? SwiftPM is definitely the standard for adding dependencies now so I'd expect AWS' SDK to support this since the demand is pretty high!

**Comment by MaxDesiatov** [comment]
Hi @palpatim @royjit, thank you for your hard work on this SDK! Would you be able to clarify when the support SwiftPM is going to be added?

**Comment by BrentMifsud** [comment]
@MaxDesiatov I have not had much of an opportunity to dig into the source code. But I suspect theres some assets that are a blocker for this until swift 5.3

**Comment by MaxDesiatov** [comment]
Now is great time to start then, one could add `Package.swift` with 5.3 in its header, which would allow testing the package with Xcode 12.

**Comment by dlbuckley** [comment]
I will echo others by saying this is something we are really looking into and would love to see some early support for this during the Swift 5.3 beta period. If there are any issues then they can be reported to Apple and hopefully fixed before release.

**Comment by makoni** [comment]
Google already started working on support of binary frameworks distributing via Swift Package Manager: https://github.com/firebase/firebase-ios-sdk/issues/3136

So that might be an example

**Comment by jacobsapps** [comment]
+1

**Comment by maximkrouk** [comment]
+1
Maybe enabling SPM support via binary targets may be a nice solution for the start.
Examples:
https://github.com/sparkle-project/Sparkle/pull/1634
https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

**Comment by WarSunsOfPeace** [comment]
So now that xcode 12 is out along with swift 5.3 can we get this updated?

**Comment by AustinFuller** [comment]
+1 This would be an awesome addition. Thanks for the work guys. 🙏

**Comment by BrandonNott** [comment]
+1

**Comment by AugustDev** [comment]
This is very needed issue 🙏

**Comment by makoni** [comment]
Examples Objective-C projects that did add support for Swift Package Manager:

https://github.com/amplitude/Amplitude-iOS
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution
https://github.com/OneSignal/OneSignal-iOS-SDK

Probably they might be helpful for dev team to add support for Swift PM. Really hope it will be added

**Comment by julioarregoitia** [comment]
I can't believe this issue was opened in 2016 and it hasn't been closed yet.Please just add support for SPM

**Comment by patagoniacode** [comment]
Swift Package Manager support is a key feature.
It would be an awesome addition 🚀
Thanks!

**Comment by BrentMifsud** [comment]
> Swift Package Manager support is a key feature.
> 
> It would be an awesome addition 🚀
> 
> Thanks!

At this point I'd say it's a required feature. Cocoapods heavily bloats your repo. We have to pay extra for GitHub LFS because some of our dependencies ended up having files > 100mb (looks angrily at here maps)

**Comment by nmtitov** [comment]
Hello hello ⏳

**Comment by dlbuckley** [comment]
May as well just use [Soto](https://github.com/soto-project/soto) as it actually seems to be going the direction that the community wants.

**Comment by Daemon-Devarshi** [comment]
+1

**Comment by gevartosky** [comment]
+1

**Comment by marciogranzotto** [comment]
Does anyone has a workaround to use this with SPM? I have a private SDK that will be distributed as a SPM lib and I need to have AWSCognitoIdentityProvider as a dependency.

**Comment by BrentMifsud** [comment]
> Does anyone have a workaround to use this with SPM? I have a private SDK that will be distributed as a SPM lib and I need to have AWSCognitoIdentityProvider as a dependency.

As @dbuckley mentioned above, you can use Soto (if you don't mind a framework wrapping another framework)

Otherwise you could always fork the dependency you need and add SPM support to it yourself.

**Comment by drochetti** [comment]
Hi everyone, thanks for your patience.

We are currently investigating Swift Package Manager support. We have quite a few AWS SDKs so there's a lot of surface area to cover. We are prioritizing SwiftPM support on Amplify, the SDK will be prioritized according to what Amplify consumes first.

That being said, feel free to comment with the SDKs you use and are looking forward to SPM support.

Last but not least, we have no ETA but we're actively working on this and I'll keep this issue updated with the status. Also feel free to follow the progress on the Amplify repo https://github.com/aws-amplify/amplify-ios/issues/90

**Comment by Daemon-Devarshi** [comment]
> Hi everyone, thanks for your patience.
> 
> We are currently investigating Swift Package Manager support. We have quite a few AWS SDKs so there's a lot of surface area to cover. We are prioritizing SwiftPM support on Amplify, the SDK will be prioritized according to what Amplify consumes first.
> 
> That being said, feel free to comment with the SDKs you use and are looking forward to SPM support.
> 
> Last but not least, we have no ETA but we're actively working on this and I'll keep this issue updated with the status. Also feel free to follow the progress on the Amplify repo [aws-amplify/amplify-ios#90](https://github.com/aws-amplify/amplify-ios/issues/90)

Great news, looking forward to it. Here are the list of libraries which I am using in one of the projects:

1. AWSCognito
2. AWSCognitoAuth
3. AWSCognitoIdentityProvider
4. AWSCognitoIdentityProviderASF
5. AWSCore

**Comment by BrentMifsud** [comment]
> Hi everyone, thanks for your patience.
> 
> We are currently investigating Swift Package Manager support. We have quite a few AWS SDKs so there's a lot of surface area to cover. We are prioritizing SwiftPM support on Amplify, the SDK will be prioritized according to what Amplify consumes first.
> 
> That being said, feel free to comment with the SDKs you use and are looking forward to SPM support.
> 
> Last but not least, we have no ETA but we're actively working on this and I'll keep this issue updated with the status. Also feel free to follow the progress on the Amplify repo [aws-amplify/amplify-ios#90](https://github.com/aws-amplify/amplify-ios/issues/90)

Awesome.

We use AWSCore and S3

**Comment by palpatim** [comment]
@Daemon-Devarshi 

> AWSCognito

Please note that this SDK has been [deprecated for a couple of years](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.8.0) and will be [removed altogether in December](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.18.0). After that time, we will no longer publish any updates to the Cognito Sync mobile SDK for iOS.

[Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios) is our recommended solution for syncing data across devices, but you can also use the [AppSync client](https://docs.amplify.aws/sdk/api/graphql/q/platform/ios)

**Comment by dlbuckley** [comment]
Great news that SPM work is finally starting 🎉

> That being said, feel free to comment with the SDKs you use and are looking forward to SPM support.

For us we are mostly concerned about `AWSCore`, `AWSCloudwatch` and `AWSLogs`.

**Comment by rromanchuk** [comment]
> We are prioritizing SwiftPM support on Amplify, the SDK will be prioritized according to what Amplify consumes first.

Ugghh, that KPI doesn't make sense to me, but regardless, this Package.swift should have no prior knowledge of what Amplify is or that it even exists. 


`AWSCore`
  - AWSServiceConfiguration, DeveloperAuthenticatedIdentityProvider, AWSCognitoCredentialsProviderHelper,  

`AWSS3`
- AWSS3TransferUtility, AWSS3TransferUtilityConfiguration

`AWSDynamoDB`
  - AWSDynamoDBObjectModel, AWSDynamoDBModeling, AWSDynamoDBObjectMapper, AWSDynamoDBObjectMapperConfiguration

~`AWSMobileClient`~

**Comment by mregnauld** [comment]
So, any update on this?
I personally need the support for:

- API Gateway
- Cognito
- S3

**Comment by bsarrazin** [comment]
AppSync is what our team needs this for...
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/288

**Comment by p4checo** [comment]
👋 
Thanks for looking into this! On our side, we're using:
- AWSCognito
- AWSKinesis

**Comment by Nomad-Go** [comment]
AWSCognito
S3
IoT Core

**Comment by jacobsapps** [comment]
Is there also the intent to support AWS Amplify with this too? 

I'm using the main services given by Amplify:  
- Amplify
- AWSCognitoAuthPlugin
- AWSAPIPlugin
- AWSDataStorePlugin
- AWSS3StoragePlugin

**Comment by palpatim** [comment]
> Is there also the intent to support AWS Amplify with this too?

As @drochetti mentioned [above](https://github.com/aws-amplify/aws-sdk-ios/issues/313#issuecomment-713731221), that is our priority for SPM support. :)

**Comment by palpatim** [comment]
The AWS Mobile SDK for iOS can now be installed via Swift Package Manager. See the [README](https://github.com/aws-amplify/aws-sdk-ios/blob/main/README.md) for full details.

**Comment by AlexKarpov** [comment]
Does anyone have have an error during compile saying: `Failed to build module 'AWSMobileClientXCF' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced`?

**Comment by palpatim** [comment]
@AlexKarpov I encountered that error while we were testing & developing SPM itself. We resolved it by:

- Quit Xcode
- If applicable: Deintegrate CocoaPods (See the "Migrating to SPM from CocoaPods" of @Kilo-Loco's [blog post](https://aws.amazon.com/blogs/mobile/swift-package-manager-support-for-amplify/))
- Clear derived data
- Reopening the app in Xcode from the ".xcodeproj" file (not the "workspace file" that was originally created by CocoaPods)

If you haven't previously integrated with CocoaPods, some of that won't apply, but the general guidance is that SPM is pretty aggressive about caching packages, and if there's anything odd about one of the cached artifacts it could cause issues.

**Comment by AlexKarpov** [comment]
@palpatim Thank you! It helped.

**Comment by cameroncooke** [comment]
I'm having trouble consuming the AWS Mobile SDK as a depdencncy of another SPM package. My `Package.swift` file looks like:

```swift
import PackageDescription

let package = Package(
    name: "MyPackage",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "MyPackage,
            targets: ["MyPackage"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(name: "AWSiOSSDKV2", url: "https://github.com/aws-amplify/aws-sdk-ios-spm", .upToNextMinor(from: "2.23.2")),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "MyPackage",
            dependencies: [.product(name: "AWSCognitoIdentityProviderXCF", package: "AWSiOSSDKV2")]),
        .testTarget(
            name: "MyPackageTests",
            dependencies: ["MyPackage"]),
    ]
)
```

Getting error:

```
product 'AWSCognitoIdentityProviderXCF' not found in package 'AWSiOSSDKV2'. it is required by package 'MyPackage' target 'MyPackage'.
```

I've tried without specking the package name in the dependency but then it errors saying `unknown package 'AWSiOSSDKV2' in dependencies of target 'MyPackage'; valid packages are: 'aws-sdk-ios-spm'`
