### ISSUE TITLE
Error using an existing API Gateway

### ISSUE THREAD

**Issue by bluepixeltech** [aws-amplify/aws-sdk-ios#3133]
Hi,

I create the sample Pet Store API in API Gateway (with Cognito User Pool as Authorizer) and I am trying to communicate with it in a Swift iOS app. I manually added the following items in amplifyconfiguration.json as described in https://docs.amplify.aws/lib/restapi/existing-resources/q/platform/ios and https://docs.amplify.aws/lib/restapi/authz/q/platform/ios.

"awsAPIPlugin": {
                    "PetStore": {
                        "endpointType": "REST",
                        "endpoint": "*******",
                        "region": "us-east-1",
                        "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                    }
  }

"api": {
        "plugins": {
            "awsAPIPlugin": {
                "PetStore": {
                    "endpointType": "REST",
                    "endpoint": "*****",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
   }

I integrated the API SDK as stated in https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk-ios-swift.html and configured with:

let client = AI2ARPetStoreClient.default()
        
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSRegionType.USEast1, identityPoolId: "********")
        let configuration = AWSServiceConfiguration(region: AWSRegionType.USEast1, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration

(AI2ARPetStoreClient) is the client API class generated automatically in the SDK.

Upon build and run I get the error: 
2020-10-17 10:41:53.944691-0500 AI2 AR[32263:1849960] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

It's raised related to the configuration.credentialsProvider property in AI2ARPetStoreClient:
let signer: AWSSignatureV4Signer = AWSSignatureV4Signer(credentialsProvider: configuration.credentialsProvider, endpoint: self.configuration.endpoint)

PS: - The user is successfully signed in using Cognito with Amplify.Auth.signInWithWebUI
      - Testing on both device and simulator running iOS 14.0.1
      - Amplify version: 1.3.1

Any help would be appreciated!

**Comment by palpatim** [comment]
Hi @bluepixeltech 

Please refer to the [Amplify REST API Docs](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/ios#install-amplify-libraries) for instructions on accessing your API endpoint via Amplify.  Hope this helps.

**Comment by palpatim** [comment]
Leaving this open as a bug so we can update the AWS documentation at https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk-ios-swift.html to point to the Amplify and SDK docs.

**Comment by palpatim** [comment]
Note to @aws-amplify/ios-team: Submit a PR on https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/how-to-generate-sdk-ios-swift.md to point to [Amplify REST API Docs](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/ios#install-amplify-libraries).
