### ISSUE TITLE
Offline sign-out and improved logout UX with the Hosted UI

### ISSUE THREAD

**Issue by samrayner** [aws-amplify/aws-sdk-ios#3141]
## Which AWS Services is the feature request for?
AWS iOS SDK / Amplify iOS SDK 

## Is your feature request related to a problem? Please describe.

When using the Hosted UI for authentication with a third-party identity provider (in our case, our own OIDC server), there are multiple issues with the sign out functionality. Please note that we have direct User Pool login disabled so the Hosted UI redirects immediately to our login form.

**1. The user is unable to fully sign out while they are offline.**
The page load in the presented SafariViewController fails and the user is not signed out of the app. We can locally sign them out of the app using `awsMobileClient.signOut()` but we have no means of clearing the cookies of the `SFAuthenticationSession` so the _apparently_ signed out app is immediately signed back in if someone goes to sign in as a different user later. Due to this, signing them out locally is not an option as it gives users a false sense of being fully signed out when they are not.

**2. iOS presents a warning about amazoncognito.com wanting to sign IN not OUT.**
This is misleading and confusing for the user.

**3. A SafariViewController appears and immediately disappears when invalidating tokens.**
Though we appreciate it is necessary with the current set up, this behaviour feels like a bug to the user and could cause doubt that the log out process has been successful.

## Describe the solution you'd like

We appreciate that the current behaviour is designed to ensure that the identity provider tokens are invalidated on sign out. While this is a good idea, the downsides of the current user experience outweigh the security benefit for us. Our tokens have a short enough expiry that not immediately invalidating them isn't too much of a risk.

The simplest solutions we have come up with that hopefully has little impact on other use cases:

If the SDK was updated to use `ASWebAuthenticationSession` instead of the deprecated `SFAuthenticationSession` and the [prefersEphemeralWebBrowserSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio?language=objc) option was made available we could set that to `true` for sign-in. We would then be able to locally sign out the user even if they were offline and, when someone goes to sign in again, they would not be automatically signed back in as the old session cookies would not exist.

We understand that using this option would rule out invalidating the tokens using the existing sign out functionality but that's OK for our use case. Ideally, if this solution was implemented, Amplify would also be updated to support it and provide a `signOutLocally` method that didn't require us to use the [escape hatch](https://docs.amplify.aws/lib/auth/escapehatch/q/platform/ios).

## Similar issues

We have tried various workarounds discussed in these issues but none solve the problem of the persisted `SFAuthenticationSession` unfortunately.

https://github.com/aws-amplify/aws-sdk-ios/issues/2904
https://github.com/aws-amplify/aws-sdk-ios/issues/2886
https://github.com/aws-amplify/aws-sdk-ios/issues/2715
https://github.com/aws-amplify/aws-sdk-ios/issues/1724
https://github.com/aws-amplify/amplify-ios/issues/634
https://github.com/aws-amplify/amplify-ios/issues/745

**Comment by pedrofspinho** [comment]
Hi @palpatim. Thank you for the update. Is this something that we can expect to be finished in the upcoming days/week? (sorry, i'm kinda new in how AWS works, but i'm experience the same issue described above)

**Comment by palpatim** [comment]
@pedrofspinho Once we put an issue into "work in progress" it means it's in our queue and being worked on. We don't have an ETA for delivery, but we'll update this issue when we have more info.

**Comment by hakanyildizay** [comment]
@palpatim thank you for your feedback. We are also experiencing with the same issue. 
It would be great if you can prioritize this problem.

**Comment by doc-rj-celltrak** [comment]
@palpatim Thanks for the info. This request has a few parts. It would be great to know if they are they all being worked on, or just the offline issue (1)?

**Comment by pedrofspinho** [comment]
> @pedrofspinho Once we put an issue into "work in progress" it means it's in our queue and being worked on. We don't have an ETA for delivery, but we'll update this issue when we have more info.

Thank you for the reply. I'm interested in managing the popup appearing after signing out. 

Thank you for the hardwork

**Comment by pedrofspinho** [comment]
Hi @palpatim! Any progress on this issue? Just trying to manage expectations on my company about this popup appearing. 

Will this be something solved before Christmas?

**Comment by palpatim** [comment]
@pedrofspinho No ETA yet. We'll update this ticket when we have more info.

**Comment by pedrofspinho** [comment]
> @pedrofspinho No ETA yet. We'll update this ticket when we have more info.

Thank you

**Comment by mattcat10** [comment]
Is there an ETA on this? We have run into this problem as well, and would like to upgrade our app to use amplify but do not want to sacrifice user experience.

**Comment by royjit** [comment]
We have created a PR [here](https://github.com/aws-amplify/amplify-ios/pull/1037) with the change that uses ASWebAuthenticationSession. Will update once it is released.

**Comment by royjit** [comment]
Hi,

Thank you for the patience while we were working on this. We have upgraded hostedUI to use ASWebAuthenticationSession and the changes are released in - https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.22.0

We have added new apis for supporting `ASWebAuthenticationSession` :

```swift
@available(iOS 13, *)
     public func showSignIn(presentationAnchor: ASPresentationAnchor,
                            hostedUIOptions: HostedUIOptions,
                            _ completionHandler: @escaping(UserState?, Error?) -> Void) 

@available(iOS 13, *)
     public func signOut(presentationAnchor: ASPresentationAnchor,
                         options: SignOutOptions = SignOutOptions(),
                         completionHandler: @escaping ((Error?) -> Void))
```

You can enable private session by setting the flag `signInPrivateSession` in `HostedUIOptions`:

```swift
let hostedUIOptions = HostedUIOptions(signInPrivateSession: true)
```

Similar changes are released in Amplify-iOS as well - https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0. Please reach back to us if you have any questions.

**Comment by pedrofspinho** [comment]
Hi royjit, 

Just confirming that when we call logout we will no longer see the same popup as login. Is this correct?

Thank you, 
Pedro

**Comment by doc-rj-celltrak** [comment]
@royjit Does this resolve all 3 issues in the issue description above?  Also, can you explain a private session? What's the purpose of it?

**Comment by doc-rj-celltrak** [comment]
Hi @royjit I'm using the new APIs for ASWebAuthenticationSession, and I'm setting signInPrivateSession to true. However, when I sign out with the new API, I'm still getting the permission popup. I'm including a screenshot (please disregard the yellow color). Can you help? Thanks.

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-08 at 11 33 52](https://user-images.githubusercontent.com/55109813/107259073-2baa6c00-6a02-11eb-9757-67b7b35b8007.png)

**Comment by royjit** [comment]
> Just confirming that when we call logout we will no longer see the same popup as login. Is this correct? Meaning point 2 of the described behaviour was fixed?

@pedrofspinho  SignOut popup will not be shown if you signIn via private session and then do a local signOut during the signOut. Explained below with code samples.

> Does this resolve all 3 issues in the issue description above? Also, can you explain a private session? What's the purpose of it?

@doc-rj-celltrak  Yes, the three issues can be addressed if you use privateSession during signIn and then just do a local only signOut. Private session sets the `prefersEphemeralWebBrowserSession` field of [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession). By doing this the signIn process will ask the browser to start in a private authentication session. Which enables us to do a local only signOut and do not require to show `ASWebAuthenticationSession` again during signOut. Since it is a local only signOut you can do this while you are 1) offline 2) no popup 3) no webview. This is same behavior that @samrayner suggested in the issue description.

---

Usage with code sample

If you would not like to see the popup during signOut, you have to start the signIn process via privateSession and then during signOut just do a local signOut. The usage of the new privateSession api defer based on whether you are using AWSMobileClient or Amplify.Auth. Here are the code sample for both:

__**AWSMobileClient**__

1. Start signIn flow with private session:

```swift

let hostedUIOptions = HostedUIOptions(signInPrivateSession: true)
AWSMobileClient.default().showSignIn(presentationAnchor: self.view.window!,
                                    hostedUIOptions: hostedUIOptions) {
}
```

2. [SignOut locally](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSMobileClient/Classes/AWSMobileClient.html#/s:15AWSMobileClientAAC7signOutyyF)  so that popup is not shown:

```swift
AWSMobileClient.default().signOut()
```

---

__**Amplify.Auth**__

1. SignIn using the private session.
```swift
Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!, 
                            options: .preferPrivateSession()) { ... }
```
2. Signout using the signout api (it will internally invoke local signOut if private session was used during signIn).

```swift
Amplify.Auth.signOut { ... }
```

**Comment by james-mallory** [comment]
@royjit I found this issue while researching the same desired behavior in a react-native app. What is the best way for me to know when https://github.com/aws-amplify/amplify-js gets updated with these changes?

**Comment by royjit** [comment]
@james-mallory Feel free to create a Github issue in the JS repo and link this issue there.

**Comment by doc-rj-celltrak** [comment]
@samrayner and/or @royjit I still have issue #1 (can't fully sign out when offline) in Android. Do you know if there is an Android equivalent solution to this issue? Thanks.

**Comment by royjit** [comment]
@doc-rj-celltrak I am not sure about how Android logic works, please raise an issue in Android repo - https://github.com/aws-amplify/aws-sdk-android

**Comment by doc-rj-celltrak** [comment]
Thanks @royjit I raised the issue in aws-sdk-android -- https://github.com/aws-amplify/aws-sdk-android/issues/2359

**Comment by mudilajaganios** [comment]
> > Just confirming that when we call logout we will no longer see the same popup as login. Is this correct? Meaning point 2 of the described behaviour was fixed?
> 
> @pedrofspinho SignOut popup will not be shown if you signIn via private session and then do a local signOut during the signOut. Explained below with code samples.
> 
> > Does this resolve all 3 issues in the issue description above? Also, can you explain a private session? What's the purpose of it?
> 
> @doc-rj-celltrak Yes, the three issues can be addressed if you use privateSession during signIn and then just do a local only signOut. Private session sets the `prefersEphemeralWebBrowserSession` field of [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession). By doing this the signIn process will ask the browser to start in a private authentication session. Which enables us to do a local only signOut and do not require to show `ASWebAuthenticationSession` again during signOut. Since it is a local only signOut you can do this while you are 1) offline 2) no popup 3) no webview. This is same behavior that @samrayner suggested in the issue description.
> 
> Usage with code sample
> 
> If you would not like to see the popup during signOut, you have to start the signIn process via privateSession and then during signOut just do a local signOut. The usage of the new privateSession api defer based on whether you are using AWSMobileClient or Amplify.Auth. Here are the code sample for both:
> 
> ****AWSMobileClient****
> 
> 1. Start signIn flow with private session:
> 
> ```swift
> let hostedUIOptions = HostedUIOptions(signInPrivateSession: true)
> AWSMobileClient.default().showSignIn(presentationAnchor: self.view.window!,
>                                     hostedUIOptions: hostedUIOptions) {
> }
> ```
> 
> 1. [SignOut locally](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSMobileClient/Classes/AWSMobileClient.html#/s:15AWSMobileClientAAC7signOutyyF)  so that popup is not shown:
> 
> ```swift
> AWSMobileClient.default().signOut()
> ```
> 
> ****Amplify.Auth****
> 
> 1. SignIn using the private session.
> 
> ```swift
> Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!, 
>                             options: .preferPrivateSession()) { ... }
> ```
> 
> 1. Signout using the signout api (it will internally invoke local signOut if private session was used during signIn).
> 
> ```swift
> Amplify.Auth.signOut { ... }
> ```

I just updated my cocoapod for Amplify. I am seeing the version 1.5.0. When will be the 1.6.0 version available in Cocoapods

**Comment by palpatim** [comment]
@mudilajaganios 1.6.0 has been available since 4-Feb. Please make sure you update your pods with `pod update` rather than installing them with `pod install`. (Although if you do a `pod install --repo-update`, you can get the same behavior.)

**Comment by palpatim** [comment]
@mudilajaganios Please open a different issue for this, since it's not really related to the HostedUI problem. That will let us track your problem separately.

**Comment by VishnuNCS** [comment]
Hi,

Not able to update to Amplify iOS version 1.6.0 through pods. It is still updating to 1.5.0. Any suggestions?

```
Analyzing dependencies
Downloading dependencies
Installing AWSAuthCore (2.19.1)
Installing AWSComprehend (2.19.1)
Installing AWSMobileClient (2.19.1)
Installing AWSPluginsCore (1.5.0)
Installing AWSPolly (2.19.1)
Installing AWSPredictionsPlugin (1.5.0)
Installing AWSRekognition (2.19.1)
Installing AWSTextract (2.19.1)
Installing AWSTranscribeStreaming (2.19.1)
Installing AWSTranslate (2.19.1)
Installing Amplify (1.5.0)
Installing AmplifyPlugins (1.5.0)
Installing CoreMLPredictionsPlugin (1.5.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 19 dependencies from the Podfile and 50 total pods installed.
```

**Comment by deveshmittalncs** [comment]
Is there a parallel flag on the Android SDK as well?

**Comment by mudilajaganios** [comment]
> Hi,
> 
> Not able to update to Amplify iOS version 1.6.0 through pods. It is still updating to 1.5.0. Any suggestions?
> 
> ```
> Analyzing dependencies
> Downloading dependencies
> Installing AWSAuthCore (2.19.1)
> Installing AWSComprehend (2.19.1)
> Installing AWSMobileClient (2.19.1)
> Installing AWSPluginsCore (1.5.0)
> Installing AWSPolly (2.19.1)
> Installing AWSPredictionsPlugin (1.5.0)
> Installing AWSRekognition (2.19.1)
> Installing AWSTextract (2.19.1)
> Installing AWSTranscribeStreaming (2.19.1)
> Installing AWSTranslate (2.19.1)
> Installing Amplify (1.5.0)
> Installing AmplifyPlugins (1.5.0)
> Installing CoreMLPredictionsPlugin (1.5.0)
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 19 dependencies from the Podfile and 50 total pods installed.
> ```

Just see if it works for you

https://github.com/aws-amplify/amplify-ios/issues/1082

**Comment by MuhammadSalmanSiddiqui** [comment]
Tackle this issue using Javascript, I just added a condition of checking logout word in a path generated on pressing signOut button. That's it.

`async function urlOpener(url, redirectUrl) {
  if (await InAppBrowser.isAvailable()) {
    if (!url.includes("logout")) {
      const { type, url: newUrl } = await InAppBrowser.openAuth(
        url,
        redirectUrl,
        {
          modalEnabled: false,
          showTitle: false,
          enableUrlBarHiding: false,
          enableDefaultShare: false,
          ephemeralWebSession: false,
        }
      );
      if (type === "success") {
        Linking.openURL(newUrl);
      }
    }
  }
}`
