### ISSUE TITLE
AWSAppleSignIn, expose ASAuthorizationAppleIDCredential as property of AWSAppleSignInProvider

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-ios#3143]
**Which AWS Services is the feature request for?**
AWSAppleSignIn, AWSAppleSignInProvider class

**Is your feature request related to a problem? Please describe.**
Upon initial user Sign in with Apple, `(void)authorizationController:(ASAuthorizationController *)controller
   didCompleteWithAuthorization:(ASAuthorization *)authorization` returns the authorization containing the authorization credential as `ASAuthorizationAppleIDCredential`

In order for an app to get the Apple account person name and email address, app code needs access to the credentials. Apple only returns the fullName and email on the initial login. 

**Describe the solution you'd like**
Expose a property named credentials in AWSAppleSignInProvider.h as follows:

```
@interface AWSAppleSignInProvider : NSObject<AWSSignInProvider>

/**
 Fetches the shared instance for AWSAppleSignInProvider.

 @return the single instance of AWSAppleSignInProvider
 */
+ (instancetype)sharedInstance;

/**
 Sets the ViewController used for Apple SignIn.
 */
- (void)setViewControllerForAppleSignIn:(UIViewController *)signInViewController;

// Upon initial SIWA, Apple returns name and email (if requested by scope)
// Make them avaialble by exposing the credentials.
@property (strong, atomic) ASAuthorizationAppleIDCredential *credentials;

@end

NS_ASSUME_NONNULL_END
```

and implement it as follows (AWSAppleSignInProvider.m): 

```
- (void)authorizationController:(ASAuthorizationController *)controller
   didCompleteWithAuthorization:(ASAuthorization *)authorization {
    self.credentials = [authorization credential];
    NSData *idTokenData = [self.credentials identityToken];
    if (idTokenData != nil) {
        self.idToken = [[NSString alloc] initWithData:idTokenData encoding:NSUTF8StringEncoding];
        [[AWSSignInManager sharedInstance] completeLogin];
    } else {
        
    }
}
```

Example use of the credential: 

```
ASAuthorizationAppleIDCredential *appleCredentials = AWSAppleSignInProvider.sharedInstance.credentials;

if (appleCredentials != nil && appleCredentials.email != nil ) {
        NSLog(@"First Apple sign-in has email and name");
        NSString *userFullName = [NSPersonNameComponentsFormatter localizedStringFromPersonNameComponents:appleCredentials.fullName style:NSPersonNameComponentsFormatterStyleDefault options:0];
        // save the user's name and email into app new account...
```

**Comment by palpatim** [comment]
@BillBunting Thanks for the PR. It is merged and will go out in the next release.

**Comment by royjit** [comment]
This has been released - https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.21.0 , closing the issue.
