### ISSUE TITLE
Delete user from user pool cognito

### ISSUE THREAD

**Issue by shaikhshoeb** [aws-amplify/aws-sdk-ios#3167]
this code does not work it throughs an error saying 
Error deleting user: The operation couldn’t be completed. (com.amazonaws.AWSCognitoIdentityProviderErrorDomain error 20.)

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods]
 - Swift Version : [e.g. 5.0]
 - Xcode Version: [e.g. 11.4]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhoneX, Simulator]
 - iOS Version: [e.g. iOS 14.0]

**Additional context**
Add any other context about the problem here like your specific use case.

 AWSCognitoIdentityUserPool.default().currentUser()?.delete().continueWith(block: { (task) -> Any? in
            if let error = task.error {
                print("Error deleting user: \(error.localizedDescription)")
            }
            if let _ = task.result {
                print("User deleted successfully.")
            }
            return nil
        })

**Comment by ruiguoamz** [comment]
Hi, @shaikhshoeb 

I will find a time to try the code way of deleting users. 

At the same time. I want to ask your use case. Are you granting users permission of removing user from user pool or you want administrative control on your users? 

If it is the second use case, you can go into AWS Cognito console and do that manually, if it's the first use case, I ned to spend some time trying to reproduce the issue.

**Comment by ruiguoamz** [comment]
Hi, @shaikhshoeb 
I tried this method on my sample App.

I could see the same error message if I do not have any user signing in due to unauthorized error.

But it works when you have a user signed in and the user can only delete themselves.
