### ISSUE TITLE
Problem with AWSCognitoUserPoolsAuthProviderAysnc protocol

### ISSUE THREAD

**Issue by kunnchoi** [aws-amplify/aws-sdk-ios#3169]
**State your question**
We are randomly experiencing 401 errors when trying to upload data through AWSAppSyncClient.
Based on our investigation, this problem seems to be due to a sort of a race condition between the thread for uploading data through AWSAppSync SDK and the thread for refreshing id token within AWSMobileClient SDK because the function to upload data can be called while AWSMobileClient SDK is synchronously refreshing id token. 

- Before refactoring our code, I wanted to confirm with AWS engineers that the 401 error upon uploading data can be resolved if we synchronously handle uploading data and refreshing id token.    

- And another question is 'getLatestAuthToken', that we implement to comfort to 'AWSCognitoUserPoolsAuthProviderAysnc' protocol to have AWSAppSync SDK take care of refreshing id token, is called every time a GraphQL request is made. I was wondering if this is supposed to be done this way by design.

- And my last question is 'idToken' is refreshed every time 'getTokens' is called under 'getLastestAuthToken'. I was also wondering if this is supposed to be done this way by design on the AWS SDK side or if we are missing something in our code. See my snippet of code below 

**Which AWS Services are you utilizing?**
AWS AppSync, AWS Cognito, AWS S3 

**Provide code snippets (if applicable)**
```
class AWSClientManager {

...

  private var _appSyncClient: AWSAppSyncClient?
  var appSyncClient: AWSAppSyncClient? { return self._appSyncClient }

  func initializeAppSync() {
    do {
      let cacheConfiguration = try AWSAppSyncCacheConfiguration()
      let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: AWSAppSyncServiceConfig(), userPoolsAuthProvider: AWSMobileClient.default(), cacheConfiguration: cacheConfiguration)      
      _appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
      // Set id as the cache key for objects. See architecture section for details
      _appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }
    } catch {
      AWSClientManager.logger.error("Error initializing appsync client (\(error.localizedDescription))")
      print("Error initializing appsync client. \(error)")
    }
  }

  func uploadEvents(_ event: UploadEventsMutation) {
    dispatchQueue.async {
      self._appSyncClient?.perform(mutation: event, resultHandler: { (result, error) in
        if let err = error {
          AWSClientManager.logger.error("Event Upload Error (\(err.localizedDescription))")
        }
      })
    }

...

}

extension AWSMobileClient: AWSCognitoUserPoolsAuthProviderAsync {
  public func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
      let dispatchGroup = DispatchGroup()
      dispatchGroup.enter()
      self.getTokens { (tokens, error) in
        dispatchGroup.leave()
        if error != nil {
          callback(nil, error)
        } else {
          callback(tokens?.idToken?.tokenString, nil)
        }
      }
      dispatchGroup.wait()
  }
}

```

**Environment(please complete the following information):**
 - SDK Version: 
    'AWSAppSync', '3.1.6'
    'AWSMobileClient', '2.16.0'
    'AWSS3', '2.16.0'

 - Dependency Manager: [Cocoapods]
 - Swift Version : [5.0]

**Device Information (please complete the following information):**
 - Device: [iPhone 11 Pro Max]
 - iOS Version: [iOS 14.0.1]

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by lawmicha** [comment]
Hi @kunnchoi 

> Before refactoring our code, I wanted to confirm with AWS engineers that the 401 error upon uploading data can be resolved if we synchronously handle uploading data and refreshing id token.

I'm not sure what you mean exactly, could you provide a code snippet of how you would synchronously do this? I believe the AppSync SDK only provides an asynchronous `getLatestToken` with the callback in the method signature
ie. 
```swift
func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) 
```
> And another question is 'getLatestAuthToken', that we implement to comfort to 'AWSCognitoUserPoolsAuthProviderAysnc' protocol to have AWSAppSync SDK take care of refreshing id token, is called every time a GraphQL request is made. I was wondering if this is supposed to be done this way by design.

Yes this is correct, you can see the example here under "Cognito User pool" https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#authorization-modes

> And my last question is 'idToken' is refreshed every time 'getTokens' is called under 'getLastestAuthToken'. I was also wondering if this is supposed to be done this way by design on the AWS SDK side or if we are missing something in our code. See my snippet of code below

Yes, usually i have seen developers use either the `idToken` or the `accessToken` depending on their use case. However, if you are able to get a successful request using the idToken, i would stick with that unless there's a reason to use another. if your are getting 401 errors only once in a while then that is most likely saying it is not a problem with the type of token you are using.

Example from https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#authorization-modes
```swift
func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
    AWSMobileClient.default().getTokens { (tokens, error) in
        if error != nil {
            callback(nil, error)
        } else {
            callback(tokens?.idToken?.tokenString, nil)
        }
    }
}
```
I noticed in your example
```swift
public func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
    let dispatchGroup = DispatchGroup()
    dispatchGroup.enter()
    self.getTokens { (tokens, error) in
        dispatchGroup.leave()
        if error != nil {
            callback(nil, error)
        } else {
            callback(tokens?.idToken?.tokenString, nil)
        }
    }
    dispatchGroup.wait()
}
```

You are using a dispatch group which will block at `dispatchGroup.wait()`. Could you try removing the dispatch group like in the docs example to see if you can fix the 401 issues? 

How frequent Is the 401 response occuring?

**Comment by kunnchoi** [comment]
@lawmicha I tested after entirely removing dispatchGroup code but still getting 401 errors consistantly

**Comment by lawmicha** [comment]
Hi @kunnchoi when you say consistently, does that mean you were not able to make a single successful request? If so, this is most likely a problem with the authorization mode set on your AppSync service. Can you provide us with the steps you took to provision your API?

**Comment by kunnchoi** [comment]
@lawmicha  I meant by I can easily reproduce the 401 error issue although it randomly occur. 
Our GraphQL APIs are queued up via OperationQueue and synchronously handled one at a time, and OperationQueue is suspended while 'getTokens' function is being operated.

**Comment by palpatim** [comment]
Thanks for the additional information. We're investigating this and will update this ticket when we have more info.

**Comment by diegocstn** [comment]
Hi @kunnchoi,
I noticed in your code snippet that you're wrapping the GraphQL mutation call in a `dispatchQueue.async {...}` block.
Can you share how is that queue being initialized and its QoS level?
`AppSyncClient.perform(mutation:)` accepts a `queue` parameter of type `DispatchQueue` on which the result handler will be called and defaults to `DispatchQueue.main`.
Could you instead try passing your queue to `.perform(mutation:queue:)`?

```swift
func uploadEvents(_ event: UploadEventsMutation) {
     self._appSyncClient?.perform(mutation: event, queue: dispatchQueue, resultHandler: { (result, error) in
        if let err = error {
          AWSClientManager.logger.error("Event Upload Error (\(err.localizedDescription))")
        }
    })
```
