### ISSUE TITLE
Wrong link in the documentation

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/aws-sdk-ios#3171]
Go here:
https://github.com/aws-amplify/aws-sdk-ios#awstask

Click
Working with AWSTask, which is pointing to http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html

Then, this page will appear
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/what-is-aws-mobile.html

So, the link is wrong.

Can you fix it? Thanks.

**Comment by ruiguoamz** [comment]
Hi, @Ricardo1980 

Sorry for the inconvenience. The `awstask`'s link has become a redirected link for a while. I will see how I can fix it. But for now, this [link](https://web.archive.org/web/20171210054441/http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html) may help you. Feel free to reach out again if it's not helpful

**Comment by ruiguoamz** [comment]
Hi, we have merged in the fix. Thanks for reporting this!
