### ISSUE TITLE
dyld: Symbol not found: error while using xcframework in app which internally using AWSMobileClient

### ISSUE THREAD

**Issue by vimitahirpara** [aws-amplify/aws-sdk-ios#3187]
**Describe the bug**
dyld: Symbol not found: _$s15AWSMobileClient0aB5ErrorO017idTokenAndAcceessE9NotIssuedyACSS_tcACmFWC
  Referenced from: /private/var/containers/Bundle/Application/48F0BD65-CA57-45E1-A73C-FB391E246021/ClinicalWrapper.app/Frameworks/CoreSDK.framework/CoreSDK
  Expected in: /private/var/containers/Bundle/Application/48F0BD65-CA57-45E1-A73C-FB391E246021/ClinicalWrapper.app/Frameworks/AWSMobileClient.framework/AWSMobileClient
 in /private/var/containers/Bundle/Application/48F0BD65-CA57-45E1-A73C-FB391E246021/ClinicalWrapper.app/Frameworks/CoreSDK.framework/CoreSDK
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**To Reproduce**
I am using AWSMobileCLient in my frmaework. I had created .xcframework and integrated in application. I had updated pods for both framework project and application to 2.18.0.  I am getting above error while running/ luanching the application.

**Observed Behavior**
Above error occures in both simulator and device.
**Expected Behavior**
It shoul run successfully both on simulator and device

**Stack Trace**
Please provide a stack trace if applicable e.g. a crash is occurring.

**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]
 - Xcode Version: [e.g. 11.4]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here like your specific use case.

**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
AWSDDLog.sharedInstance.logLevel = .debug
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Comment by palpatim** [comment]
One of the questions we ask is your Dependency manager: How are you integrating the AWSMobileClient.framework into your app? Binary packages downloaded from our repo? Carthage? CocoaPods? Something else?

There are issues consuming binaries built with different versions of Swift, but the error message you report doesn't sound like you're hitting that condition. We haven't explored xcframeworks deeply, so we don't have a lot of insight into what could be causing your particular issue. I will note that our integration instructions for [Carthage](https://github.com/aws-amplify/aws-sdk-ios#carthage) and [binary frameworks](https://github.com/aws-amplify/aws-sdk-ios#frameworks) include a custom build phase that strips unused architectures at compile time, which is not something that has to be done with xcframeworks. However, I'm not clear what the expectation is for *consuming* a non-XCFramework inside an XCFramework--should you strip the unused architectures from the non-XCF or not? You might investigate from there and see if that provides any insights.

Hope this helps

**Comment by royjit** [comment]
We have added support for XCFramework in AWS SDK for iOS 2.22.1, please follow the steps here to use xcframework - https://github.com/aws-amplify/aws-sdk-ios#setup. I am optimistically closing this issue, feel free to reach out if you are facing any issue.
