### ISSUE TITLE
AWSMobileClient.default().username returns alias instead of username for custom auth

### ISSUE THREAD

**Issue by SNagappan** [aws-amplify/aws-sdk-ios#3194]
Workflow:
I implemented custom auth in my application following these steps: https://docs.amplify.aws/sdk/auth/custom-auth-flow/q/platform/ios#custom-authentication-in-amplify. On the backend, authentication is done through the define/create/verify lambda triggers in cognito. The registration of new users is all done on the server side with admin create user, set password, and linking 3rd party provider accounts.

Problem:
When I sign in using AWSMobileClient.default().signIn() using an alias, AWSMobileClient.default().username returns the alias instead of the username. For example, if i signed in with an email alias, AWSMobileClient.default().username would return the email of the user instead of the actual username. My expectation is that it would always return the username.

Environment:
Swift
AWSMobileClient 2.12.7
Xcode 12.0.1
Cocoapods

**Comment by royjit** [comment]
Hi @SNagappan 

Thank you for reporting this bug. We have created a PR to address the issue - https://github.com/aws-amplify/aws-sdk-ios/pull/3198

**Comment by palpatim** [comment]
We released this on https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.19.0
