### ISSUE TITLE
[AWSSignatureV4Signer generateQueryStringForSignatureV4WithCredentialProvider: ...] doesn't handle spaces (or other characters requiring encoding) correctly

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/aws-sdk-ios#3215]
When spaces (or other non-URI-safe characters) are present in the target path, the `keyPath` argument must be percent-encoded (using `.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)`. However, `urlComponents.percentEncodedPath` effectively negates the encoding step that has occurred. SigV4 requires that [the canonical request](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) be URI-encoded **twice** (step 2). In [`AWSSignatureV4Signer generateQueryStringForSignatureV4WithCredentialProvider: ...`](https://github.com/aws-amplify/aws-sdk-ios/blob/0f985322625566a566726e8ca2c24d5a5bc678b8/AWSCore/Authentication/AWSSignature.m#L390), it is effectively URI-encoded **zero** times.

**Observed Behavior**

Requests using signed URLs with spaces in their paths fail with authentication errors at the the API Gateway level.

**Expected Behavior**

Requests using signed URLs with spaces in their paths succeed.

**Code Snippet**

```swift
let url = "/path with spaces"
// URL-encode spaces, etc.
let keyPath = String(url.path.dropFirst())
percentEncodedKeyPath = keyPath.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)!

let task = AWSSignatureV4Signer
    .generateQueryStringForSignatureV4(
        withCredentialProvider: credentialsProvider,
        httpMethod: .GET,
        expireDuration: 60,
        endpoint: endpoint!,
        keyPath: percentEncodedKeyPath,
        requestHeaders: requestHeaders,
        requestParameters: .none,
        signBody: true)

task.waitUntilFinished()

if let error = task.error as NSError? {
    print("Error occurred: \(error)")
}

if let result = task.result {
  let signedUrl = result as URL

  // requesting signedUrl results in authentication failures because the canonical requests do not match
}
```

When I attempt to work around this by double-encoding it myself, the signed URL includes the double-encoding rather than matching the original URL:

```swift
let url = "/path with spaces"
// URL-encode spaces, etc.
let keyPath = String(url.path.dropFirst())
percentEncodedKeyPath = keyPath.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)!

let task = AWSSignatureV4Signer
    .generateQueryStringForSignatureV4(
        withCredentialProvider: credentialsProvider,
        httpMethod: .GET,
        expireDuration: 60,
        endpoint: endpoint!,
        keyPath: percentEncodedKeyPath
          .addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)!
          .addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)!,
        requestHeaders: requestHeaders,
        requestParameters: .none,
        signBody: true)

task.waitUntilFinished()

if let error = task.error as NSError? {
    print("Error occurred: \(error)")
}

if let result = task.result {
    let signedUrl = result as URL

    // requesting signedUrl results in authentication failures because the canonical requests do not match
    // also, signedUrl's path does not match the original URL's path and needs to be rewritten (this is a workaround):

    var urlComponents = URLComponents(url: signedUrl, resolvingAgainstBaseURL: false)!
    // re-use the original path
    urlComponents.path = url.path
    
    let correctlySignedUrl = (urlComponents.url)!
}
```

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

`AWSSignatureV4Signer`

**Environment(please complete the following information):**
 - SDK Version: 2.18.1
 - Dependency Manager: Cocoapods, Carthage
 - Swift Version : 5.3
 - Xcode Version: 12.1

**Device Information (please complete the following information):**
 - Device:  iPhone 11, Simulator
 - iOS Version: iOS 14.1

**Comment by wooj2** [comment]
Seems related to: https://github.com/aws-amplify/aws-sdk-ios/issues/3362

**Comment by mojodna** [comment]
https://github.com/aws-amplify/aws-sdk-ios/pull/3378 claims that this was addressed in https://github.com/aws-amplify/amplify-ios/pull/1080 (see also https://github.com/aws-amplify/amplify-ios/commit/e5eb079aae91516455320bf61f93ba40c8e5316c).

These appear to touch Amplify, but not the AWS SDK for iOS (as described above).

**Comment by mojodna** [comment]
@ameter did your implementation run into this problem, or are you using a different signer (Amplify vs. aws-sdk-ios)?

**Comment by ameter** [comment]
@mojodna I ran into the same problem.  I ended up implementing essentially the same workaround you did.

**Comment by ameter** [comment]
Fixed!

The next release of aws-sdk-ios (which will be released sometime next week) will include the fix.  Note that the fix is backward compatible with the workaround of double-encoding the url before passing it to the signer, so existing code will not break.
