### ISSUE TITLE
The kSecUseNoAuthenticationUI is deprecated WARNING in AWSUICKeyChainStore.m

### ISSUE THREAD

**Issue by 1mash0** [aws-amplify/aws-sdk-ios#3225]
**Describe the bug**
Adding and building AWSConprehend libs causes a kSecUseNoAuthenticationUI deprecated WARNING on line 541 of AWSUICKeyChainStore.m.

Deprecations:
'kSecUseNoAuthenticationUI' is deprecated: first deprecated in iOS 9.0 - Use kSecUseAuthenticationUI instead.

**To Reproduce**
1. create on iOS project
2. add AWSComprehend libs
3. build

**Expected Behavior**
No Deprecated warning

**Code Snippet**
`query[(__bridge __strong id)kSecUseNoAuthenticationUI] = (__bridge id)kCFBooleanTrue;`

**Environment(please complete the following information):**
 - SDK Version: 2.19.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0
 - Xcode Version: 12.1

**Device Information (please complete the following information):**
 - Device: n/a
 - iOS Version: n/a
 - Specific to simulators: n/a

**Comment by royjit** [comment]
The PR is merged in and released in 2.21.0 - https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.21.0 Closing this issue.
