### ISSUE TITLE
Need to support ARM64 target for new Macs - iOS Simulator

### ISSUE THREAD

**Issue by jim3ex** [aws-amplify/aws-sdk-ios#3230]
Standard Cocoapods installation - successful. Build is fine for iPhone target but fails for simulator targets

"Could not find module 'AWSMobileClient' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64"

**To Reproduce**
1. Install Xcode 12.2
2. Standard cocoa pods install of AWSMobileClient and AWSAPIGateway
3. Build for simulator

**Observed Behavior**
"Could not find module 'AWSMobileClient' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64"

**Expected Behavior**
Successful simulator build

**Code Snippet**
target 'XXXXXXXX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XXXXXXX
  pod 'AWSMobileClient'
  pod 'AWSAPIGateway'

end

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient, AWSAPIGateway:

**Environment(please complete the following information):**
 - SDK Version: 2.19.1
 - Dependency Manager: Cocoapods
 - Swift Version : Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
 - Xcode Version: 12.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 14.2
 - Specific to simulators: iPhone 11

**Comment by diegocstn** [comment]
hi @jim3ex, sorry you're having problems setting up your project.

Are you on a new Apple Silicon Mac?

Can you please verify what's the value of the following flags in your project "Build Settings"?
- `Architectures`
- `Excluded Architectures`
- `Build Active Architecture Only`

**Comment by Rusik** [comment]
Any updates on that?
