### ISSUE TITLE
How can I assemble the URL of a file that was uploaded AWSS3TransferUtility.default().uploadData?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/aws-sdk-ios#3264]
**State your question**

Context: I am creating an iOS app using Amplify, S3, AppSync, Aurora Serverless and other services.

My project uses S3, and I modified slightly some permissions (the cloud formation templates generated by amplify) to allow world-wide downloads, or public reads. Also, my app shouldn't need anything like getPresignedUrl, given that I want use a normal URL, pointing directly to S3, so I can download images super fast and use SDWebImage caching features and/or embed these images in emails.

The URLs are working fine, I take them from AWS Console and I see the public permissions are working OK.

I know that the urls I have this structure, more or less:
`https://<Bucket>.s3-aws-<Region>.amazonaws.com/<Key>`
which is what I see in my S3 AWS console.

I see in the file awsconfiguration.json generated by amplify has:

```
    "S3TransferUtility": {
        "Default": {
            "Bucket": "xxxxxxxxxxxxxxxx3b4473b13febebea2d5ca3dev-dev",
            "Region": "eu-west-1"
        }
    },
```

 I also see in the file amplifyconfiguration.json generated by amplify this:

```
        "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "xxxxxxxxxxxxxxxxxxxxxxxxxxbebea2d5ca3dev-dev",
                "region": "eu-west-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
```

(BTW, why do I have two files with the same info?)

So, the info I need is there but I am not sure how I should access it.

Do I have to use the iOS API framework to assemble that URL? Or get the bucket/region? Or do I just read the JSON files and I generate the URL manually? It is not clear to me.

Reading Amplify docs I don't see anything about this. They insist in using presigned URLs, but that does not apply to my use case (read images from emails and using SDWebImage cache)

Playing with the debugger I tried different things:

`AWSS3TransferUtility.default().configuration.endpoint`
returns nil

`AWSS3TransferUtility.default().configuration.regionType`
returns EUWest1

`AWSS3.default().configuration.endpoint`
triggers an assert with:
Thread 1: Exception: "The service configuration is `nil`. You need to configure `awsconfiguration.json`, `Info.plist` or set `defaultServiceConfiguration` before using this method."
(the message does not make any sense to me)

Note that to upload pictures I am using this framework:
`AWSS3TransferUtility.default().uploadData`
and it is working perfectly.

Here is how I start my AppSync API:
```
  do {
    let appSyncServiceConfig = try AWSAppSyncServiceConfig()
    let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: appSyncServiceConfig,
                                                          userPoolsAuthProvider: AWSMobileClient.default() as AWSCognitoUserPoolsAuthProvider,
                                                          cacheConfiguration: nil,
                                                          s3ObjectManager: AWSS3TransferUtility.default())
    appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)

} catch {
    print("Error initializing appsync client. \\(error)")
    return nil
}
```

What should I do? How do I assemble the URLs (the key is returned by my database)?

Thanks a lot for your suggestions

**Which AWS Services are you utilizing?**
For this specific issue: Amplify, S3, Cognito

**Provide code snippets (if applicable)**
Above

**Environment(please complete the following information):**
 - SDK Version: 
  - AWSAppSync (3.1.11)
  - AWSMobileClient (2.18.1)
  - AWSPinpoint (2.18.1)
  - AWSS3 (2.18.1)
  - AWSUserPoolsSignIn (2.18.1)
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: iOS 13.5.1
 - Specific to simulators: I only use real devices.

**Comment by diegocstn** [comment]
hi @Ricardo1980,
thanks for reaching out.

> Do I have to use the iOS API framework to assemble that URL? Or get the bucket/region? Or do I just read the JSON files and I generate the URL manually? It is not clear to me.

We currently don't support an API for building an S3 URL as per your use case.
SDWebImage should cache the image locally, and making requests only in case of cache misses, so as a workaround you should be able to use a presigned URL generated with `Amplify.Storage.getURL(key: options:)`.
In this regards, would [SDWebImage cacheKeyFilter](https://github.com/SDWebImage/SDWebImage/blob/master/Docs/HowToUse.md#using-cache-key-filter) be helpful? 

> (BTW, why do I have two files with the same info?)

The `awsconfiguration.json` is used by the "legacy" SDKs, whereas `amplifyconfiguration.json` is for the new Amplify :)

**Comment by Ricardo1980** [comment]
@diegocstn Thanks for reply.

> presigned URL generated with Amplify.Storage.getURL(key: options:).

That is not an option because I also want the URLs for emails and apart from that I use the old SDK, not the new one.

I also realised that when using 
AWSS3TransferUtility.default().uploadData
in the task returned in the completion block, there is a property with the bucket. That's what I need to assemble the URL.

Why not just reading the json file and using that data to build my URLs? That info is enough for me, but I would prefer to use the framework. Is that my only option? 

Thanks a lot for suggestions.

**Comment by e1block** [comment]
@Ricardo1980 Any luck?
