### ISSUE TITLE
How to control s3 upload bandwidth

### ISSUE THREAD

**Issue by oyljerry** [aws-amplify/aws-sdk-ios#3265]
**State your question**

I found in [C++ SDK](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/client-config.html), there is a **writeRateLimiter**, which are used to throttle the bandwidth used by the transport layer. 
In iOS SDK, How can I control this bandwidth?

**Which AWS Services are you utilizing?**
S3

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 
AWSS3 (2.18.1)

 - Dependency Manager: 
Cocoapods

 - Swift Version : 
Objective-C

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: iOS 13.5.1
 - Specific to simulators: real device

**Comment by wooj2** [comment]
Hi @oyljerry ,

Thanks for reaching out to us.

I'm not super familiar with the AWS SDK for C++ library, but I took a brief look at the link you have provided.  It seems to be a client configuration that can be configured when accessing AWS services, as long as the you are using the C++ SDK.    The AWS SDK for iOS does not use the C++ SDK, and unfortunately, we do not support this capability.

Best of luck!
