### ISSUE TITLE
Using Analytics to send push to iOS

### ISSUE THREAD

**Issue by helloniklas** [aws-amplify/aws-sdk-ios#3267]
Previously there was docs for how to use push notifications with Amplify. It all now seems to be gone. I can only find deprecated docs on mobile hub.

pinpoint!.notificationManager.interceptDidRegisterForRemoteNotifications(
             withDeviceToken: deviceToken)

I set up auth with anonymous guest use and Analytics in Amplify.

But how do I get the iOS app to pass the device token to Pinpoint? No device tokens, end points or users appear in the Pinpoint console, so I can't create a segment that has any eligible endpoints to push to.

Any hints on how to push to users with Amplify Analytics would be much appreciated.

**Comment by wooj2** [comment]
Hi @helloniklas ,

Thanks for reaching out, but there is a subtle difference between the Amplify Libraries for iOS, released in May 2020, (which currently does not integrate with push notifications), and the AWS SDK for iOS, which has been around for a while, which does support push notifications.

Assuming you are using the AWS SDK for iOS, the documentation has been moved here:
https://docs.amplify.aws/sdk/q/platform/ios

Specifically, the documentation I think you are looking for is located here:
https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios

But, please let us know if you have any specific questions.

Thanks again, and best of luck.

**Comment by helloniklas** [comment]
Ok thanks for the info. I found another post that helped. Seems I can use Amplify then feed the configuration in manually to AWS Pinpoint, and thereby get it to work. 

https://github.com/aws-amplify/amplify-ios/issues/662

**Comment by royjit** [comment]
Glad you are able to move forward, closing this issue.
