### ISSUE TITLE
AWSS3TransferUtilityUploadTask memory leak

### ISSUE THREAD

**Issue by Nomad-Go** [aws-amplify/aws-sdk-ios#3268]
**Describe the bug**

I made a demo project to practice SwiftUI and Combine. I abstracted the S3 SDK underneath these declarative tools and I now observe the "piping" (AWSS3TransferUtilityUploadTask, AWSS3TransferUtilityUploadExpression) being retained after uploading.

**To Reproduce**
1. Clone [demo project](https://github.com/labs-nomad/S3TransferDemo)
2. Install pods and open workspace
3. Tap the "Upload Random JPEG's" button and wait 5 seconds after upload for UI elements to disappear 
4. Inspect the memory graph and observe a retained AWSS3TransferUtilityUploadTask and AWSS3TransferUtilityUploadExpression for every upload.

**Observed Behavior**
For every upload a AWSS3TransferUtilityUploadTask and AWSS3TransferUtilityUploadExpression are retained.

**Expected Behavior**
Once my upload completes I would like the supporting objects to disappear.

**Stack Trace**
N/A

**Code Snippet**

```swift
public func upload(objectToUpload object: S3Uploadable) -> Future<S3Uploadable, Error> {
    let future: Future<S3Uploadable, Error> = Future<S3Uploadable, Error> { promise in
        guard let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: self.utilityKey.key) else {
            promise(.failure(S3TransferError.couldNotRetrieveTransferUtility))
            return
        }

        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = { (_ task: AWSS3TransferUtilityTask, _ progress: Progress) in
            object.progress.send(progress.fractionCompleted)
        }


        let completionHandle: AWSS3TransferUtilityUploadCompletionHandlerBlock = { (task, p_error) -> Void in
            guard let error = p_error else {
                promise(.success(object))
                return
            }
            promise(.failure(error))
        }

        let key: String = object.objectCloudKey

        let contentType: String = object.contentType.rawValue

        switch object.uploadableObjectLocation {
        case .DATA_OBJECT(let data):
            _ = transferUtility.uploadData(data, key: key, contentType: contentType, expression: expression, completionHandler: completionHandle).continueWith { (task) -> Any? in
                if let result = task.result {
                    object.add(task: result)
                }
                guard let error = task.error else {
                    return nil
                }
                promise(.failure(error))
                return nil
            } as? AWSTask<AWSS3TransferUtilityTask>
        case .LOCAL_FILE(let url):
            _ = transferUtility.uploadFile(url, key: key, contentType: contentType, expression: expression, completionHandler: completionHandle).continueWith(block: { (task) -> Any? in
                if let result = task.result {
                    object.add(task: result)
                }
                guard let error = task.error else {
                    return nil
                }
                promise(.failure(error))
                return nil
            }) as? AWSTask<AWSS3TransferUtilityTask>
        }
    }
    return future
}
```

**Unique Configuration**

I'm trying to abstract the S3 SDK underneath Combine and integrate it with SwiftUI.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

AWS S3 SDK

**Screenshots**
AWS Objects still around after upload
![Screen Shot 2020-11-29 at 2 04 56 PM](https://user-images.githubusercontent.com/42352379/100554863-a3168f00-324c-11eb-91f4-44b740922c7c.png)
Retain and release history (All my calls have a corresponding release)
![Screen Shot 2020-11-29 at 2 04 41 PM](https://user-images.githubusercontent.com/42352379/100554870-a873d980-324c-11eb-94dc-e7ca161b26dd.png)
Retain and release history (All my calls have a corresponding release)
![Screen Shot 2020-11-29 at 2 02 21 PM](https://user-images.githubusercontent.com/42352379/100554872-add12400-324c-11eb-8f47-abf1c40c671f.png)
App doing its thing.
![IMG_E3168AA261D4-1](https://user-images.githubusercontent.com/42352379/100554680-15866f80-324b-11eb-9335-c994530ed2b4.jpeg)

**Environment(please complete the following information):**
 - SDK Version: 2.19.1
 - Dependency Manager: Cocoapods (but can't wait for SPM support)
 - Swift Version : 5
 - Xcode Version: Version 12.2 (12B45b)

**Device Information (please complete the following information):**
 - Device: iPhone 7
 - iOS Version: iOS 14
 - Specific to simulators: N/A

**Additional context**
I spent some considerable time trying out different Combine methods and tweaking certain things to see if the remaining retain count was mine. I concluded that something else in the SDK is retaining the supporting transfer objects.

**Comment by wooj2** [comment]
Hi @Nomad-Go ,

Thank you for taking the time to submit a this memory leak to us.  Despite having your sample code, and running it within instruments, I was unable to observe any memory leaks.

I'm using an unauthenticated role, and attempting to upload to an s3 bucket... Are there any other differences in your configuration that I may not have?

Thanks!

Below is a screenshot of me attempting to reproduce the memory leak in instruments:
![Screen Shot 2020-12-04 at 2 46 57 PM](https://user-images.githubusercontent.com/1911939/101222901-9d9bb900-363f-11eb-9ff4-3c8faa6dcaf7.png)

**Comment by Nomad-Go** [comment]
Hey! Thank you for reviewing. I observed AWSS3TransferUtilityUploadTask and AWSS3TransferUtilityUploadExpression sticking around in memory when I expected them to be gone after the upload. I look for these objects by marking a "Generation" in the Leaks instrument. While the instrument does not flag any leaks My memory creeps up after every upload. Here is a screenshot of my "Generation" timing

![Screen Shot 2020-12-04 at 3 21 51 PM](https://user-images.githubusercontent.com/42352379/101224917-e43fe200-3644-11eb-87d1-c52cebcf49ce.png)

The first flag is pre upload, you can then see the memory spike as images are generated in memory before being cached to disk for upload. The second flag is during upload while all upload tasks are on the UI. The last flag is once the UI elements have disappeared. 

I go back to generation number two and type "AWS" at the bottom. To see the items remaining for that generation.

![Screen Shot 2020-12-04 at 3 26 57 PM](https://user-images.githubusercontent.com/42352379/101225032-3da81100-3645-11eb-8ad4-6d1df0709249.png)

I expect these to disappear after upload and UI element removal. In my Combine subscriptions I set the `task` (AWSS3TransferUtilityTask) I'm retaining to nil on upload completion. It seems there is a retain cycle somewhere which is also keeping my JPEGUpload objects around.

![Screen Shot 2020-12-04 at 3 31 57 PM](https://user-images.githubusercontent.com/42352379/101225283-e5254380-3645-11eb-8d69-33fac1eeb8b0.png)

It seems to be coming from inside the `Future<S3Uploadable, Error>` I'm wrapping the upload in. Maybe I missunderstand the SDK and the AWSS3TransferUtilityUploadTask and AWSS3TransferUtilityUploadExpression are supposed to stick around?

**Comment by wooj2** [comment]
@Nomad-Go 

Thank you for explaining that it is not an explicit memory leak.  I've been able to reproduce what you are seeing, and it looks like that there is something in the application (probably a Future?) that is holding a reference to the `AWSS3TransferUtilityUploadTask` and `AWSS3TransferUtilityUploadExpression`.

I looked at the code, but I am not well versed with your style of programming.  Just as an experiment, is it possible to set up your code to:
1.  Upload 5 images
2. After finishing uploading and waiting 5 seconds for the images to disappear, remove the instance of `TransferListViewModel`?

If the instances of `AWSS3TransferUtilityUploadTask` and `AWSS3TransferUtilityUploadExpression` get removed out of memory, then we'll know it has something to do with `TransferListViewModel`.

**Comment by Nomad-Go** [comment]
I didn't realize I had a style! I hope that is not a bad thing. I tried a few things in the project including adding the `S3Uploadable` object to capture lists inside the Combine Future. I also tried deallocating the `S3TransferController` and the `TransferListViewModel` Unfortunatly I did not see a change. When I go inspect an instance of `AWSS3TransferUtilityUploadTask` in Xcode debug tools I see the responsible caller is the `-[AWSS3TransferUtility internalUploadFile` function.

<img width="1440" alt="Screen Shot 2020-12-14 at 10 45 34 PM" src="https://user-images.githubusercontent.com/42352379/102157677-aae64e00-3e5e-11eb-823c-288085360516.png">

I will continue to investigate to make sure It's not something else though. Thank you for your help on this!

**Comment by KennethLee95** [comment]
Hi you can try to manually clear the TransferUtility by using AWSS3TransferUtility.remove(forKey: self.utilityKey.key), I have this issues as well and this works for me.

**Comment by Nomad-Go** [comment]
@KennethLee95 Yes, it appears that removing the registered transfers utility releases the memory. I have an instance of my `S3TransferController` which stays around for the life of the app. I guess I could refactor to create and destroy a new utility for every upload. Not a huge fan of this design though. Might look into abstracting the whole process away into a resigned URL or switching to the [SOTO AWS SDK](https://github.com/soto-project/soto).

**Comment by wooj2** [comment]
Hi @Nomad-Go

We do not recommend creating/destroying instances of TransferUtility for each upload.  Perhaps there is some other point in your application lifecycle where you can release the instance?  In any case, we do not consider this a memory leak and we believe the system is behaving as designed.

Best of luck!
