### ISSUE TITLE
There is already a user which is signed in

### ISSUE THREAD

**Issue by quetool** [aws-amplify/aws-sdk-ios#3273]
**State your question**

I´m really new to AWS and I need clarification about this particular line here [https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift#L198](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift#L198)
Why is this in that way? Cause I don't think this is on the Android SDK. Why do I can't re-login a user?
For example, if I login an user and then kill the application, which is the correct way to re-login the user?

**Which AWS Services are you utilizing?**

AWSMobileClient

**Environment(please complete the following information):**
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by wooj2** [comment]
Hi @quetool ,

This line detects if the user is already signed in.  If the user is already logged in, we call the completion handler.  If you want to re-login a user, you will need to sign out first, and then call signIn again.
