### ISSUE TITLE
Assertion failure in awsmtl_JSONDictionaryTransformerWithModelClass

### ISSUE THREAD

**Issue by Air-Craft** [aws-amplify/aws-sdk-ios#3285]
**Describe the bug**
For some reason the code below is giving me an assertion failure on 2.19.1 (and as far back as 2.13.0).  

```
+ (NSValueTransformer *)awsmtl_JSONDictionaryTransformerWithModelClass:(Class)modelClass {
	NSParameterAssert([modelClass isSubclassOfClass:AWSMTLModel.class]);
```

And what is odd is it appears to be fine...

```
(lldb) p modelClass.superclass
(Class) $3 = AWSModel
(lldb) p modelClass.superclass.superclass
(Class) $4 = AWSMTLModel
```

Any ideas??? Thx!

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
```
pod 'AWSCore', '~>2.19'
pod 'AWSCognito', '~>2.19'
pod 'AWSPinpoint', '~>2.19'
pod 'AWSS3', '~>2.19'
pod 'AWSSNS', '~>2.19'
```
 - Swift Version : 5.2
 - Xcode Version: 12.2
 - iOS: 14.2, Sim and Devixe

**Comment by palpatim** [comment]
@Air-Craft Can you give a stack trace that shows the class that is inheriting from AWSModel, or a code snippet that replicates this? We code-generate most of these SDKs, but AWSS3 and AWSCognito both have hand-generated code as well, and it's possible we missed a conformance.

Also, please note that AWSCognito has been [deprecated for a couple of years](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.8.0), and has been [removed as of 2.20.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0).

**Comment by Air-Craft** [comment]
Hey sorry.  It was due to a duplicate copy of the SDK being included in the
final product. My fault! Thanks for the reply.
H


http://air-craft.co
<http://air-craft.co/?utm_source=emailsig-ac1-website&utm_medium=email-signature&utm_campaign=air-craft-general>
 · 0779 055 6418 · London
