### ISSUE TITLE
Remove AWSElasticLoadBalancing and AWSAutoScaling

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/aws-sdk-ios#3295]
In the [2.17.0 release of the AWS Mobile SDK for Android](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.17.0), the Android SDK dropped support for the Auto Scaling and Load Balancing SDKs.

We observed low usage, and reasoned that these infrastructure services are inappropriate to call directly from a mobile handset. We suggest that customers expose any needed functionality to mobile customers through API Gateway. Customers should continue to enjoy these services through backend programs written with AWS' traditional (non-mobile) SDKs.

We did not coordinate this with the iOS team. As it stands, the [`AWSElasticLoadBalancing`](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSElasticLoadBalancing.podspec) and [`AWSAutoScaling`](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSAutoScaling.podspec) frameworks continue to exist in the iOS SDK. To keep functional parity, we request that they be likewise dropped.

**Comment by palpatim** [comment]
We'll take this under consideration and ensure we don't have meaningful usage on the iOS side that would warrant different behavior on that platform. Assuming we don't see significant usage, we'll announce deprecation and then remove a few months after that announcement.
