### ISSUE TITLE
SSL Certificate pinning.

### ISSUE THREAD

**Issue by rsakhnievych** [aws-amplify/aws-sdk-ios#3328]
**State your question**
Hi guys. I'm using AWSAPIGateway and want to implement SSL Certificate Pinning to make my API calls more secure. I try to find some information about how to implement this in Amazon documentation but probably can't. Does the AWSAPIGateway or AWSCore SDK have a possibility to implement SSL certificate pinning? And how I can secure my API calls from the MiTM attack in case Amazon SDK doesn't support SSL pinning?
Thanks in advance!

**Which AWS Services are you utilizing?**
- AWSAPIGateway

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.21.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.3

**Device Information (please complete the following information):**
- Any iOS device

**Comment by nick3389** [comment]
Any news about this? I also use AWS SDK for uploading to S3 and certificate pinning would be very useful...

**Comment by diegocstn** [comment]
Hey @rsakhnievych @nick3389, 
we don't support certificate pinning. We recommend to use the OS-provided security measures such as [App Transport Security](https://developer.apple.com/documentation/security/preventing_insecure_network_connections) which includes enforcement of minimum TLS levels (version 1.2 or later), validation of trust chains, and Certificate Transparency..
