### ISSUE TITLE
Building a project on M1 Mac, a header file is missing from AWSS3

### ISSUE THREAD

**Issue by codeslubber** [aws-amplify/aws-sdk-ios#3337]
**Describe the bug**
The compiler simply cannot find these two symbols: `AWSS3TransferManagerErrorDomain` and `AWSS3TransferManagerErrorType`

**Code Snippet**
```
let completionHandler: AWSS3TransferUtilityUploadCompletionHandlerBlock = {
  (task, err) -> Void in
  DispatchQueue.main.async {
    dLog("On completion block...")
    if let error = err as NSError? {
      if error.domain == AWSS3TransferManagerErrorDomain,
        let code = AWSS3TransferManagerErrorType(rawValue: error.code) {
          switch code {
            case .cancelled, .paused:
              break
            default:
              dLog("Error uploading: \(key) Error: \(error)")
            }
         } else {
             dLog("Error uploading: \(key) Error: \(error)")
         }
```
The two constants in here are not found. When I drill open the framework, the .h file that contains them on other machines is not there.

**Unique Configuration**

M1 Macbook Pro
used ignore binaries on carthage

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

We are using a lot of them Cognito, AppSync, Amplify, and S3

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: Carthage
 - Swift Version : 5.3.1
 - Xcode Version: 12.2

**Device Information (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - iOS Version: 14.2

**Comment by ruiguoamz** [comment]
Hi, @codeslubber 

Thanks for reaching out. 

`AWSS3TransferManagerErrorDomain` and `AWSS3TransferManagerErrorType` has been removed from the latest version. You can either use `AWSS3TransferUtilityErrorDomain` and `AWSS3TransferUtilityErrorType` or update the code snippet you provided for your own use case.

**Comment by royjit** [comment]
`AWSS3TransferManager` was deprecated [here](https://github.com/aws-amplify/aws-sdk-ios/blob/36ffe697db24073dd1ce3d1df748707b254bee2a/AWSS3/AWSS3TransferManager.h#L53) in version [2.8.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.8.0) and removed from the SDK in [2.20.0 ](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0). Please use the latest SDK as mentioned.

**Comment by codeslubber** [comment]
So strange. We checked our version numbers. One of us had the header file in question, I did not. Ok, thanks, will let you know.

**Comment by codeslubber** [comment]
Yes that fixed it thanks.
