### ISSUE TITLE
Refresh token expiration

### ISSUE THREAD

**Issue by yagofilipe** [aws-amplify/aws-sdk-ios#3338]
Hi guys,

My team was make a test with refresh token expiration and when the refresh token expire (after 60 minutes), the getTokens completion never execute.

**Environment**
- SDK Version: 2.20.0
- Dependency Manager: Cocoapods
- Swift Version : 5

**Device Information**
- Any iOS device

Thanks & Regards.

**Comment by royjit** [comment]
Hi @yagofilipe,

Which SDK are you using? If you are trying with `AWSMobileClient` please follow this documentation to refresh the token - https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/ios#token-fetch-and-refresh .

**Comment by yagofilipe** [comment]
Hi @royjit 

I'm using AWSMobileClient.

I implemented the listener according documentation, and the listener not executed.
After debug `getTokens` method on `AWSMobileClientExtensions`, when refresh token expire, this method only calls `tokenFetchLock.wait()`. So `mobileClientStatusChanged` method and `getTokens completionHandler` didn't be called.
