### ISSUE TITLE
Help with proper awsconfiguration.json file for configuring auth with a preexisting user pool

### ISSUE THREAD

**Issue by pdswllc** [aws-amplify/aws-sdk-ios#3342]
**State your question**
I have a user pool that I created via a CloudFormation template. I am not using AWS Amplify. I would like to use the drop in UI that AWSMobileClient provides to sign a user into the app (I already have this working via the AWSCognitoAuth library, but I don't like the webview that it hosts the sign in flow).

I get the error `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `awsconfiguration.json` or `Info.plist` before using this method.'`

I have tried a couple of ways to configure the client:

1) awsconfiguration.json file only
2) awsconfiguration.json file and runtime configuration

I think my configuration file is wrong, I would appreciate help with it since I have not seen any examples that involve only using a user pool for auth. The ones I have seen also have an identity pool. And after my config is fixed, will I be able to use solely the runtime configuration? I thought I read somewhere that the awsconfiguration.json file is needed when calling certain sign in methods on the `AWSMobileClient`.

**Which AWS Services are you utilizing?**
AWS Cognito User Pool (only, not identity)

**Provide code snippets (if applicable)**

Please note the comment is not actually in my json file, but rather I added it below to add color.
My attempt at runtime configuration:
```
-- In AppDelegate.swift
var  awsMobileClient: AWSMobileClient!
func initMobileClient()
        let configuration: [String: Any] = [
            "IdentityManager": [
                "Default": [:]
            ],
            "CredentialsProvider": [
                "CognitoUser": [ // I THINK THIS IS PROBABLY WRONG BUT I COULDN'T FIND ANY USER POOL EXAMPLES
                    "Default": [
                        "PoolId": "us-east-1_XXXX",
                        "Region": "us-east-1"
                    ]
                ]
            ],
            "CognitoUserPool": [
                "Default": [
                    "PoolId": "us-east-XXXX",
                    "AppClientId": "XXX",
                    "Region": "us-east-1"
                ]
            ]
        ]

        awsMobileClient = AWSMobileClient(configuration: configuration)
        awsMobileClient.initialize { (userState, error) in
            if let error = error {
                print("Error initializing AWSMobileClient: \(error.localizedDescription)")
            } else if let userState = userState {
                print("AWSMobileClient initialized. Current UserState: \(userState.rawValue)")
            }
        }
}
```

The actual error occurs when I call this method:
```
appDelegate.awsMobileClient.showSignIn(navigationController: navController) { (userState, error) in
            ...
}

```

And here's the `awsconfiguration.json` file I have in the project (target is set properly)
```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoUser": {
            "Default": {
                "PoolId": "us-east-XXX",
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-XXX",
            "AppClientId": "XXXX",
            "Region": "us-east-1"
        }
    }
}

```

**Environment(please complete the following information):**
 - SDK Version: 2.19.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone11
 - iOS Version: 14
 - Specific to simulators: false

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by pdswllc** [comment]
Also if there is some sort of alternative option here that does not require the configuration at all please inform.

It would be great to be able to do something like this that does not require this cumbersome config file

```
let config = AWSCognitoUserPoolConfig(poolId: , appClientId: , region: )
AWSMobileClient.signIn(config)
```

**Comment by royjit** [comment]
Here is a sample configuration:

```json

{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "xxx",
                "Region": "xxx"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "xxx",
            "AppClientId": "xxx",
            "AppClientSecret": "xxx",
            "Region": "xxx"
        }
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "xxx",
                "AppClientId": "xxx",
                "AppClientSecret": "xx",
                "SignInRedirectURI": "xxx",
                "SignOutRedirectURI": "xxx",
                "Scopes": [
                    "phone",
                    "email",
                    "openid",
                    "profile",
                    "aws.cognito.signin.user.admin"
                ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}

```

**Comment by pdswllc** [comment]
@royjit thank you for the response.

I edited your sample slightly, because I don't have a client secret for this user pool client.

Also please note that I don't use Identity Pools. For the `CredentialsProvider` section, I used the same pool ID as my user pool because I wasn't sure what else to put there.

```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1_XXX", // THIS IS THE SAME AS THE CognitoUserPool PoolId below
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-XXX",
            "AppClientId": "XXX",
            "Region": "us-east-1"
        }
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": XXX",
                "AppClientId": "XXX",
                "SignInRedirectURI": "XXX",
                "SignOutRedirectURI": "XXX",
                "Scopes": [
                    "email",
                    "openid",
                    "profile"
                ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}

```



I still get that error: `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `awsconfiguration.json` or `Info.plist` before using this method.'`

Is that error also thrown when the configuration is not correct? Or does this mean it can't even find the file?

**Comment by royjit** [comment]
> Is that error also thrown when the configuration is not correct? Or does this mean it can't even find the file?

Could be either of it, so to eliminate the possibilities can you please check these:

1. If you are using `awsconfiguration.json`, make sure that the file is added to your apps target. And follow the steps below to initialize `AWSMobileClient`, you do not need to call init on AWSMobileClient in this case:
```swift
AWSMobileClient.default().initialize { (userState, error) in

}
```

2. If you are using runtime configuration using in-memory object, follow the step like this:
```swift
let mobileClient = AWSMobileClient(configuration: configuration)
mobileClient.initialize { (userState, error) in
    // initialization logic
}
```
Doc = https://docs.amplify.aws/sdk/configuration/setup-options/q/platform/ios#configure-using-an-in-memory-object


Can you also provide the stack trace of the crash to pin point to the exact issue? The above error message is thrown from different places and stack trace should help us to narrow it down.

**Comment by pdswllc** [comment]
Thanks for your help @royjit . I was able to get the drop in UI working for the email sign up flow. Will I need to add anything to the `awsconfiguration.json` file to get auth with Google to work? If so would you happen to have a sample of that as well? Thanks

**Comment by royjit** [comment]
For google and facebook through drop in UI, you might need a configuration something like this:

```json
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "<xxxx>",
                "Region": "<xxxx>"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "<xxxx>",
            "AppClientId": "<xxxx>",
            "AppClientSecret": "<xxxx>",
            "Region": "<xxxx>"
        }
    },
    "GoogleSignIn": {
        "Permissions": "email,profile,openid",
        "ClientId-WebApp": "<xxxx>",
        "ClientId-iOS": "<xxxx>"
    },
    "FacebookSignIn": {
        "AppId": "<xxxx>",
        "Permissions": "public_profile"
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}
```

Keep in mind that social provider federate through Cognito Identity Pool if you are using DropIn UI. So you need to provide the Cognito Identity Pool information as well.

**Comment by pdswllc** [comment]
Thanks for the help this has been very helpful.
