### ISSUE TITLE
Support Building XCFramework

### ISSUE THREAD

**Issue by cody1024d** [aws-amplify/aws-sdk-ios#3348]
**Which AWS Services is the feature request for?**

AWSLex

**Is your feature request related to a problem? Please describe.**
Since Xcode 12, Carthage has moved to using XCFrameworks for its dependencies.  Currently you cannot build an XCFramework of AWS-SDK-IOS (and it's dependency AWSLex.

It fails with the following:

```
/Users/Cody/Dev/Work/ProjectU/university-mobile-native/Frameworks/Carthage/Checkouts/aws-sdk-ios/AWSLex/Bluefront/libBlueAudioSourceiOS.a(BFDecoder.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/Cody/Dev/Work/ProjectU/university-mobile-native/Frameworks/Carthage/Checkouts/aws-sdk-ios/AWSLex/Bluefront/libBlueAudioSourceiOS.a' for architecture arm64
```

**Comment by mmdumi** [comment]
Hi guys, How much longer will it take to compile the project for xcframework ?
We're stuck compiling our repo for M1 macs currently for the aws dependency.
Thank you.

**Comment by royjit** [comment]
We added support for XCFrameworks in 2.22.1. Please see [Carthage installation instructions](https://github.com/aws-amplify/aws-sdk-ios#xcframeworks-recommended) or [XCFramework installation instructions](https://github.com/aws-amplify/aws-sdk-ios#xcframework-setup) in the README for more info.

Do note that the AWSLex binary framework currently does not include support for arm64, as that SDK ships with binary frameworks that aren't amenable to that architecture. We're exploring options there, but for now, if you need arm64 support on AWSLex, you can either consume them from source, or use version 2.22.0 or earlier.

**Comment by brucerune** [comment]
Any update on a fix for this?
Is 2.22.0 solid from a security POV?
