### ISSUE TITLE
getUserAttributes error message misleading when using oidc (or other) federationProvider

### ISSUE THREAD

**Issue by mattcat10** [aws-amplify/aws-sdk-ios#3349]
The error message that is thrown when calling `getUserAttributes` is misleading when using a federationProvider that is not userPools or hostedUI such as "oidc". The error should be a not supported error rather than a not signed in error message. 

https://github.com/aws-amplify/aws-sdk-ios/blob/6085bdf31b421849d59e7d30be7e164c2583f465/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift#L891

is there a reason oidc is guarded?

**Comment by lawmicha** [comment]
Hi @mattcat10, I would like to understand how you are getting into that state, do you provide your users a way to sign in using your own ODIC provider and cognito's user pools- which is why you are calling getUserAttributes for some users?

**Comment by mattcat10** [comment]
@lawmicha Thanks for the response.

We had followed some amplify docs for an older version of amplify for iOS so we were using the AWSMobileClient directly for federated logins specifically for apple once we got the token through normal apple login procedure we'd call federatedSignIn with the token which would create a user in the Cognito user pool. The providerName was getting called with
`IdentityProvider.apple.rawValue`. When calling getUserAttributes to get the attributes the provider type was "oidc" and would return attributes from the user pool.

Here is the code we were using

```
configuration = AWSCognitoAuthConfiguration(
                 appClientId: Bundle.main.signInWithAppleClientId,		                      
                 appClientSecret: Bundle.main.signInWithAppleClientSecret,		
                 scopes: Set<String>(["openid", "aws.cognito.signin.user.admin"]),		
                 signInRedirectUri: "<appscope>://",		
                 signOutRedirectUri: "<appscope>://",		
                 webDomain: Bundle.main.signInWithAppleDomain,		
                 identityProvider: "SignInWithApple",		
                 idpIdentifier: nil,		
                 userPoolIdForEnablingASF: nil)
         AWSCognitoAuth.registerCognitoAuth(with: configuration, forKey: "cognitoAuth")		                     
         self.auth = AWSCognitoAuth(forKey: "cognitoAuth")		
         self.auth?.delegate = self		
         self.auth?.getSession { (session: AWSCognitoAuthUserSession?, error: Error?) in		
             if error != nil {		
                 	
             } else {		
                 if let token = session?.accessToken {		
                     AWSMobileClient.default().federatedSignIn(provider: IdentityProvider.apple.rawValue, token: token.tokenString) 
                        ......		
                 }
           }
```

I understand that this is not the recommended method of signing in anymore and we have changed our code to use ``` Amplify.Auth.signInWithWebUI ``` and ```Amplify.Auth.fetchUserAttributes``` to get attributes. But since the error was returning notSignedIn I had a bit of trouble debugging this because I had a valid token but the provider was not supported by latest version of Amplify and Amplify was throwing a deceiving notSignedIn error so I am suggesting that the error be more detailed.
