### ISSUE TITLE
Remove deprecated unarchiveObjectWithFile method

### ISSUE THREAD

**Issue by kyleclegg** [aws-amplify/aws-sdk-ios#3352]
The method unarchiveObjectWithFile is deprecated and deemed unsecure/less secure than unarchive*OfClass. Please remove the following instance of use:

AWSTMDiskCache.m

**Comment by palpatim** [comment]
We removed that module, along with the deprecated client that used it, in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0. Please see https://github.com/aws-amplify/aws-sdk-ios/issues/2914 for additional context. If you are still seeing that API used in the latest version of the SDK, please provide additional details so we can investigate further.

**Comment by kyleclegg** [comment]
Great, thank you!
