### ISSUE TITLE
Can I use AWSMobileClient.default() after runtime configuration?

### ISSUE THREAD

**Issue by srgray** [aws-amplify/aws-sdk-ios#3353]
**State your question**
I am changing my app from using `awsconfiguration.json` to using runtime configuration like:
```
        let awsMobileClient = AWSMobileClient(configuration: awsMobileClientConfig)
        awsMobileClient.initialize { (userState, error) in
           //
        }

```
My question: after `.initialize()`, can I then later use `AWSMobileClient.default()` for convenience sake? It looks like that returns a different object than `awsMobileClient`, but I thought the documentation said that every instance of `AWSMobileClient` would share the same configuration? What if I called `AWSMobileClient.default().initialize()` immediately after `awsMobileClient.initialize()`?
Or, should I maintain my own singleton pattern in my app for `awsMobileClient` object?

**Which AWS Services are you utilizing?**
AWSMobileClient, Cognito

**Provide code snippets (if applicable)**
see above

**Environment(please complete the following information):**
 - SDK Version: 2.13.1
 - Dependency Manager: CocoaPods
 - Swift Version : 5.3

**Device Information (please complete the following information):**
  - iOS Version: iOS 14.1

**Comment by diegocstn** [comment]
Hi @srgray, thanks for contacting us.

Yes, you'll need to manage your own instance of `AWSMobileClient` as that would be different than the one you would normally get access to via the `default` static method.

Calling `AWSMobileClient.default().initialize()` will initialize the instance stored as `AWSMobileClient` static property, resulting in two different initialized instances sharing the same configuration reference.
Please note that multiple instances of `AWSMobileClient` isn't a use case we currently support.
