### ISSUE TITLE
AppSync in AppClip

### ISSUE THREAD

**Issue by astas79** [aws-amplify/aws-sdk-ios#3354]
AppSync requests always fails in AppClip, after successful authentication.

The same request works in complete IOS app, but not AppClip. 

**To Reproduce**
1. Create AppClip
2. Authenticate with guest identity using cognito identities.
3. perform AppSync.fetch 
4. Error returned "Could not connect to the server."

AWSMobileClient, Cognito, AppSync

 - SDK Version: [e.g. 3.1.21]
 - Cocoapods
 - Swift Version : 5.0
 - Xcode Version: 12.1

 - Device: Phone Xs
 - iOS Version: iOS 14.3

Task <16653CAF-E180-4A7C-AEC2-A1FCE0C6D0B3>.<4> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=65, NSUnderlyingError=0x282150ba0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=65, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <16653CAF-E180-4A7C-AEC2-A1FCE0C6D0B3>.<4>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <16653CAF-E180-4A7C-AEC2-A1FCE0C6D0B3>.<4>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=https://cognito-identity.us-east-1.amazonaws.com/, NSErrorFailingURLKey=https://cognito-identity.us-east-1.amazonaws.com/, _kCFStreamErrorDomainKey=1}

**Comment by palpatim** [comment]
@astas79 Currently, the AWS SDK for iOS, Amplify iOS, and AppSync are only supported for iOS apps, not extensions, app clips, or widgets. Please see https://github.com/aws-amplify/aws-sdk-ios/issues/2978 for an open feature request tracking support for this.
