### ISSUE TITLE
AWSMobileClient fails to build using CocoaPods use_modular_headers! without frameworks

### ISSUE THREAD

**Issue by bmwalters** [aws-amplify/aws-sdk-ios#3358]
**Describe the bug**
When `use_modular_headers!` is enabled without `use_frameworks!`, `AWSMobileClient` fails to build. See also the comments in #2818 for more users experiencing this problem.

It looks like #3039 attempted to solve this (specifically "Include transitive dependencies in AWSMobileClient" by @palpatim) but I'm still seeing this issue.

**To Reproduce**
1. Create a new iOS App project named "Test" using Xcode.
2. Create a `Podfile` in the project directory with the following contents:
```ruby
use_modular_headers!
target 'Test'
pod 'AWSMobileClient', '2.21.1'
```
3. From the project directory, run `pod install`.
4. Close the Xcode project and open the CocoaPods-created workspace, then build.

**Observed Behavior**
`/projects/Test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift:659:39: Cannot find type 'AWSServiceConfiguration' in scope`

**Expected Behavior**
Expected a successful build.

**Stack Trace**
N/A

**Code Snippet**
See above.

**Unique Configuration**
N/A

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient

**Screenshots**
N/A

**Environment(please complete the following information):**
 - SDK Version: 2.21.1
 - Dependency Manager: CocoaPods
 - Swift Version : 5.3.2
 - Xcode Version: 12.3

**Device Information (please complete the following information):**
 - Device: any
 - iOS Version: any
 - Specific to simulators: no

**Additional context**
N/A

**Relevant Console Output**
N/A

**Comment by bmwalters** [comment]
Possibly relevant: `use_modular_headers!` seems to be generating module maps for `AWSCore` (where the problematic `AWSServiceConfiguration` type is defined).

(You can see this by removing `use_modular_headers!` from the `Podfile` so it becomes just
```
target 'Test'
pod 'AWSMobileClient', '2.21.1'
```
then `pod install` fails with "The Swift pod `AWSMobileClient` depends upon `AWSAuthCore`, `AWSCognitoIdentityProvider`, `AWSCore`, and `AWSCognitoIdentityProviderASF`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies".)

I assume those targets "do not define modules" because they don't [set `"DEFINES_MODULES => "YES"`](https://github.com/CocoaPods/CocoaPods/issues/10068#issuecomment-698757001).

**Comment by diegocstn** [comment]
Hi @bmwalters, 
thanks for reaching out and reporting the issue. Following your instructions I managed to repro the build issue.

It'd be helpful to know why you're enabling `use_modular_headers!` to better understand and handle your and similar use cases.
Also, does statically linking your dependencies using `use_frameworks! :linkage => :static` instead of using modular headers help you?

**Comment by bmwalters** [comment]
Sure. The motivation is to build using static libraries instead of frameworks (this [is the default](https://guides.cocoapods.org/syntax/podfile.html#use_frameworks_bang) if `use_frameworks!` is not specified.) The root cause is to reduce app launch overhead incurred by the dynamic linker.

I tested using `use_frameworks! :linkage => :static` (with and without `use_modular_headers!`) and it worked. This should achieve the static linking goal so I'm fine with this issue being closed unless you want to track being able to build as "static library w/ modular headers".

**Comment by diegocstn** [comment]
Thanks for your feedback, I'll close this issue for now but feel free to reopen it if you have more questions.

**Comment by NicholasJCameron** [comment]
Could we re-open this error, or explain a little better I added use_frameworks! :linkage => :static and it still did not archive.
