### ISSUE TITLE
Unable to Build in XCode 12.3 via Carthage

### ISSUE THREAD

**Issue by ericpalyan** [aws-amplify/aws-sdk-ios#3381]
**Describe the bug**
I am unable to grab the framework via Carthage in XCode 12.3 (Swift 5.3.2). I get the following error:
```
*** Fetching aws-sdk-ios
*** Checking out aws-sdk-ios at "2.22.0"
*** xcodebuild output can be found in /var/folders/z1/8rqrglqn2dj8_yj1z2fv5j700000gn/T/carthage-xcodebuild.zVJMGL.log
*** Downloading aws-sdk-ios.framework binary at "AWS SDK for iOS 2.22.0"
***  Skipped installing aws-sdk-ios.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1) and the local version is 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)."

    Falling back to building from the source
*** Building scheme "AWSAPIGateway" in AWSiOSSDKv2.xcodeproj
Build Failed
Task failed with exit code 1:
This usually indicates that project itself failed to compile.
```

**To Reproduce**
1. carthage update

**Comment by k0syan** [comment]
Same here, any news?

**Comment by ericpalyan** [comment]
> Same here, any news?

I also asked on Discord and I was told to keep an eye on the requests below which should solve the issue. I was not given an estimated timeline but it’s being actively worked on.

https://github.com/aws-amplify/aws-sdk-ios/pull/3365

https://github.com/aws-amplify/aws-sdk-ios/pull/3368

**Comment by royjit** [comment]
As of 2.22.1, we distribute the binaries as XCFrameworks. :) Please see [Carthage installation instructions](https://github.com/aws-amplify/aws-sdk-ios#xcframeworks-recommended) or [XCFramework installation instructions](https://github.com/aws-amplify/aws-sdk-ios#xcframework-setup) in the README for more info.

Do note that the AWSLex binary framework currently does not include support for arm64, as that SDK ships with binary frameworks that aren't amenable to that architecture. We're exploring options there, but for now, if you need arm64 support on AWSLex, you can either consume them from source, or use version 2.22.0 or earlier.

Please let us know if you have any further issues. Ref this https://github.com/aws-amplify/aws-sdk-ios/issues/3033 for more information.
