### ISSUE TITLE
TransferUtility uploadFile method gives error when uploading video

### ISSUE THREAD

**Issue by rahulvyas** [aws-amplify/aws-sdk-ios#3395]
**Describe the bug**
TransferUtility uploadFile method gives error when uploading video/photo. 

**To Reproduce**
1. Go to Pick any video
2. Upload video using transfer utility uploadFile method
3.Look closely into console log we get an error `Failed to issue sandbox extension for file file:///private/var/mobile/Containers/Data/PluginKitPlugin/B01B0949-D271-4F0A-9532-978EB1B96CB1/tmp/trim.C5585D38-4898-46B3-B14C-216EB67C1ADA.MOV, errno = 1`

**Observed Behavior**
Getting error in console `Failed to issue sandbox extension for file file:///private/var/mobile/Containers/Data/PluginKitPlugin/B01B0949-D271-4F0A-9532-978EB1B96CB1/tmp/trim.C5585D38-4898-46B3-B14C-216EB67C1ADA.MOV, errno = 1`

**Expected Behavior**
Video should be uploaded using URL

**Stack Trace**
Failed to issue sandbox extension for file file:///private/var/mobile/Containers/Data/PluginKitPlugin/B01B0949-D271-4F0A-9532-978EB1B96CB1/tmp/trim.C5585D38-4898-46B3-B14C-216EB67C1ADA.MOV, errno = 1

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient

**Screenshots**
![Screenshot 2021-01-29 at 11 57 06 AM](https://user-images.githubusercontent.com/87060/106242542-d9ad5d80-622d-11eb-840a-7d2960b23ccf.png)

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.19.1]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [N/A] [Using Objective-C]
 - Xcode Version: [11.7]

**Device Information (please complete the following information):**
 - Device: [ iPhone8]
 - iOS Version: [ iOS 13.5]

**Additional context**
Also the strange issue is AWSS3TransferUtilityUploadCompletionHandlerBlock invoked just after the error and gives no error.

**Comment by palpatim** [comment]
Hi @rahulvyas , the AWS SDK is only supported for standalone iOS apps, not app extensions (such as Today Widgets, Watch extensions, etc).

If you are not using the SDK in an app extension but only in a standalone app, and are still seeing this error, please provide more detail including the configuration for your bucket, and some sample code showing how you configure and invoke the TransferUtility.

**Comment by rahulvyas** [comment]
I have standalone iOS app. I'm just using transferutility to upload video to bucket. 
My flow of the app is like this

Step 1 - User selects a video from gallery
Step 2 - I create **AWSS3TransferManagerUploadRequest** object with all the required details like body,bucket,key,mime-type etc.
Step 3 - Upload media using Transfer Utility **uploadData method of TransferUtility and it works** but If I use **uploadFIle method of TransferUtility** and pass AWSS3TransferManagerUploadRequest body parameter as FIleURL I get the exception in console log as stated in the original question. 

**I have to use SDK version 2.19.1 because I used TransferManager class at other locations in my app and the latest version of SDK has it removed completely.**

**My only concern here is uploadData method will copy the media to some location in storage and it will increase the disk space. That's why I raised the issue here.**

```
- (void)beginUpload {
    NSMutableArray* medias = _medias;
    NSArray* urlRequests = _uploadURLRequestsArray;
    
    AWSS3TransferUtilityUploadCompletionHandlerBlock completionHandler = ^(AWSS3TransferUtilityUploadTask *task, NSError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            // Do something e.g. Alert a user for transfer completion.
            // On failed uploads, `error` contains the error object.
            dispatch_async(dispatch_get_main_queue(), ^{
                
                if(error == nil){
                    MediaItem* uploaded = [self getMediaItemFromFileName:task.key];
                    if (uploaded) {
                        uploaded.fileName = task.key;
                        uploaded.isUploaded = YES;
                    }
                    if ([self allMediaUploaded]) {
                        [self removeTransferUtilityForKey:self.uniqueIdentifier];
                        if(self.delegate && [self.delegate respondsToSelector:@selector(didUploadedAllMedias:)]){
                            self.status = MEDIA_STATUS_UPLOADED;
                            [self.delegate didUploadedAllMedias:YES];
                        }
                        if(!self.shouldNotUseProgressHUD){
                            [SVProgressHUD showProgress:1.0 status:@"Finishing"];
                            [SVProgressHUD dismissWithDelay:1 completion:^{
                                self.status = MEDIA_STATUS_UPLOADED;
                                if (self.completionHandler) {
                                    self.completionHandler(self.status);
                                    [self reset];
                                }
                            }];
                        }
                        
                    }
                }else {
                    //NSLog(@"Error uploading %@",[error localizedDescription]);
                }
                
                
            });
        });
    };
    
    __weak typeof(self) weakSelf = self;

    AWSS3TransferUtilityUploadExpression *expression = [AWSS3TransferUtilityUploadExpression new];
    expression.progressBlock = ^(AWSS3TransferUtilityTask * _Nonnull task, NSProgress * _Nonnull progress) {
                //Update a progress bar.
                //NSLog(@"Total progress for %@ is %@",self.uniqueIdentifier,progress.description);
                if (progress.totalUnitCount > 0) {

                    MediaItem* item = [self getMediaItemFromFileName:task.key];
                    item.uploadedBytes = progress.completedUnitCount;

                    NSInteger totalProgress = [self totalPrecentageForAllVideos];
                    self.uploadProgress = totalProgress/(totalVideo*100);

                    if(self.delegate && [self.delegate respondsToSelector:@selector(didUpdatedProgress:forIdentifier:)]) {
                        [self.delegate didUpdatedProgress:self.uploadProgress forIdentifier:nil];
                    }
                   // NSLog(@"Total Progress for %@ is %ld\nTotal Videos %f\nFinal Progress %f",self.uniqueIdentifier,(long)totalProgress,totalVideo,self.uploadProgress);
                }
    };
    
    
        
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        __strong typeof(weakSelf) strongSelf = weakSelf;
        if (strongSelf) {
            for (AWSS3TransferManagerUploadRequest* uploadRequest in urlRequests) {
                        
                        MediaItem* item = [strongSelf getMediaItemFromFileName:uploadRequest.key];
                        if(item && item.isUploaded){
                            continue;
                        }
                        if (uploadRequest) {
                            
                            [strongSelf upload:uploadRequest expression:expression completionHandler:completionHandler withCompletionBlock:^(BOOL uploadSuccess) {
                            }];
                        }
                    }
        }
        
    });
}


- (void)upload:(AWSS3TransferManagerUploadRequest *)uploadRequest expression:(AWSS3TransferUtilityUploadExpression *)expression
completionHandler:(AWSS3TransferUtilityUploadCompletionHandlerBlock)transferUtilityUploadCompletionHandlerBlock withCompletionBlock:(void (^) (BOOL uploadSuccess))completionHandler {
    
    if (!self.transferUtility) {
        if(self.uniqueIdentifier){
            self.transferUtility = [AWSS3TransferUtility S3TransferUtilityForKey:self.uniqueIdentifier];
            if (!self.transferUtility) {
                [AWSS3TransferUtility registerS3TransferUtilityWithConfiguration:AWSServiceManager.defaultServiceManager.defaultServiceConfiguration forKey:self.uniqueIdentifier];
                self.transferUtility = [AWSS3TransferUtility S3TransferUtilityForKey:self.uniqueIdentifier];
                
            }
        }else {
            self.transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
        }
    }
    
    [[self.transferUtility uploadFile:uploadRequest.body bucket:uploadRequest.bucket key:uploadRequest.key contentType:uploadRequest.contentType expression:expression completionHandler:transferUtilityUploadCompletionHandlerBlock]  continueWithBlock:^id(AWSTask *task) {
        if (task.error) {
            if ([task.error.domain isEqualToString:AWSS3TransferManagerErrorDomain]) {
                 dispatch_async(dispatch_get_main_queue(), ^{
                     switch (task.error.code) {
                         case AWSS3TransferManagerErrorCancelled:{
                              if (!self.shouldNotUseProgressHUD) {
                                  [SVProgressHUD showProgress:0 status:NSLocalizedString(@"cancelled", nil)];
                                  [SVProgressHUD dismissWithDelay:2];
                              }
                            self.status = MEDIA_STATUS_CANCELLED;
                             [self reset];
                         }
                         case AWSS3TransferManagerErrorPaused:
                         {
                            self.status = MEDIA_STATUS_PAUSED;
                              if (!self.shouldNotUseProgressHUD) {
                                  [SVProgressHUD showProgress:self.uploadProgress status:NSLocalizedString(@"paused", nil)];
                              }
                         }
                        break;
                    default:
                              if (!self.shouldNotUseProgressHUD) {
                                  [SVProgressHUD showProgress:0 status:NSLocalizedString(@"upload_failed", nil)];
                                  [SVProgressHUD dismissWithDelay:1 completion:NULL];
                              }
                        self.status = MEDIA_STATUS_ERROR;
                        break;
                     }
                     if (self.completionHandler) {
                         self.completionHandler(self.status);
                     }
                });
            }
            else {
                NSLog(@"Upload failed: [%@]", task.error);
                if(!self.shouldNotUseProgressHUD){
                    [SVProgressHUD showProgress:0 status:NSLocalizedString(@"upload_failed", nil)];
                    [SVProgressHUD dismissWithDelay:1 completion:^{
                        self.status = MEDIA_STATUS_ERROR;
                        if (self.completionHandler) {
                            self.completionHandler(self.status);
                        }
                    }];
                }else {
                    self.status = MEDIA_STATUS_ERROR;
                    if (self.completionHandler) {
                        self.completionHandler(self.status);
                    }
                }
                
                
            }
        }
        
        if (task.result) {
            dispatch_async(dispatch_get_main_queue(), ^{
                
                
                //self.videoFileName = uploadRequest.key;
                self.status = MEDIA_STATUS_UPLOADING;
                
                return;
            });
        }
        return nil;
        
    }];
}
```

**Comment by palpatim** [comment]
Thanks for clarifying @rahulvyas. A quick search shows others experiencing similar problems as of iOS 13:

- https://stackoverflow.com/questions/56909566/video-upload-error-when-choosing-from-library
- https://github.com/dropbox/SwiftyDropbox/issues/256

And the root cause appears to be that iOS 13+ treats assets returned from the Image Picker more explicitly as resources owned by another app, and requires your app to copy that data to a cache available to your app. See discussion on [this SO thread](https://stackoverflow.com/questions/57798968/didfinishpickingmediawithinfo-returns-different-url-in-ios-13/58099385)

Hope this helps.

**Comment by rahulvyas** [comment]
@palpatim thanks for the heads up. I'll look into it. Also, when do you guys fix this issue?

**Comment by palpatim** [comment]
> @palpatim thanks for the heads up. I'll look into it. Also, when do you guys fix this issue? Is there anyone who can explain that if we use uploadData method of transfer utility and when upload finished it removes the copied file?

We wouldn't be able to fix this issue--your app is providing data to the TransferUtility for upload, so it would have to be your app that copies the data to a place where it can be accessed for the duration of the upload routine.

**Comment by rahulvyas** [comment]
> > @palpatim thanks for the heads up. I'll look into it. Also, when do you guys fix this issue? Is there anyone who can explain that if we use uploadData method of transfer utility and when upload finished it removes the copied file?
> 
> We wouldn't be able to fix this issue--your app is providing data to the TransferUtility for upload, so it would have to be your app that copies the data to a place where it can be accessed for the duration of the upload routine.

In this case, I have to manually create a copy and then delete the copy once the upload is finished. Isn't it possible to give a path of the location where TransferUtility can access the resource and then later at some point I call a method that clears the uploaded resoures ?

**Comment by palpatim** [comment]
>  I have to manually create a copy and then delete the copy once the upload is finished

That is correct. The TransferUtility doesn't recognize that these assets should be handled differently. It's not likely that we'd attempt to take this on as a feature request, since the rules for handling these assets are opaque, and it's not clear that we'd be able to identify them as such in any case, since the returned URL is just a pointer to a .mov file.
