### ISSUE TITLE
XCFramework 2.22.1 - iOS app crashes with error: "Use of unimplemented initializer 'init()' for class 'AWSMobileClientXCF.SignInUIOptions' "

### ISSUE THREAD

**Issue by abildgaard** [aws-amplify/aws-sdk-ios#3410]
**Describe the bug**
Our IOS app crashes when using the XCFramework 2.22.1 release (downloaded as XCFrameworks).  

We use AWSMobileClient(configuration: ...) to initialize our AWS mobile client and the app crashes when invoking the AWSMobileClient function showSignIn(...) -- when we want it to show a web login to authenticate our users. 

_This does not happen for the same code when we use the 2.22.0 release compiled using Carthage. It behaves as expected and shows the web login and we can proceed to login and make use of the AWS SWK._

**To Reproduce**
1. download the 2.2.1 release distributed as XCFrameworks
2. add 'import AWSMobileClientXCF' where appropriate 
3. use something like our simplified code snippet detailed below
4. add your appropriate configuration details for your AWS instance 
5. run the code

**Observed Behavior**
App crashes in AWSMobileClient function showSignIn(...) [it never shows an new pop-up window with the expected web login] and displays the following error:

**_Fatal error: Use of unimplemented initializer 'init()' for class 'AWSMobileClientXCF.SignInUIOptions'_**

**Expected Behavior**
I expected to see a popup window with a web login. 

This is the behavior we get using the 2.22.0 release compiled using Carthage with the same code base.

**Stack Trace**
N/A

**Code Snippet**

```
import AWSMobileClientXCF
...
let configuration : [String: Any] = [
    "IdentityManager": [ ...  ],
    "CredentialsProvider": [ ...],
     "CognitoUserPool": [ ...],
     "Auth": [ ...]
]

let navigationController =  UINavigationController()
navigationController.setNavigationBarHidden(true, animated: false)
let viewController = UIViewController()
navigationController.addChild(viewController)

let hostedUIOptions = HostedUIOptions(scopes: ["openid"])

let mobileClient = AWSMobileClient(configuration: configuration)
mobileClient.showSignIn(navigationController: navigationController, hostedUIOptions: hostedUIOptions) { (userState, error) in 
    // show success or failure  <<-- code never reaches this part, crashes in above showSignIn(...) in Xcode debugger
}

```

**Unique Configuration**
We don't use the AWSMobileClient.default() to initialize but use the AWSMobileClient(configuration: configuration) out of necessity.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
```- AWS SDK iOS 2.22.1 (XCFrameworks)
- AWSAuthCore.xcframework
- AWSCognitoIdentityProvider.xcframework
- AWSCognitoIdentityProviderASF.xcframework
- AWSCore.xcframework
- AWSMobileClientXCF.xcframework
```
**Screenshots**
N/A

**Environment(please complete the following information):**
 - SDK Version:  2.22.1 XCFramework  (downloaded as XCFrameworks)
 - Dependency Manager: N/A -
 - Swift Version : 5.3.2
 - Xcode Version: 12.4

**Device Information (please complete the following information):**
 - Device:  Simulator
 - iOS Version: iOS 14.4
 - Specific to simulators: No, same happens on iPhone testing

**Additional context**
N/A

**Relevant Console Output**
```
Fatal error: Use of unimplemented initializer 'init()' for class 'AWSMobileClientXCF.SignInUIOptions'
Cognito Test 2[4408:372907] Fatal error: Use of unimplemented initializer 'init()' for class 'AWSMobileClientXCF.SignInUIOptions'

Red labeled error in Xcode debugger: Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

```

**Comment by royjit** [comment]
We are investigating this issue and this PR should fix it - https://github.com/aws-amplify/aws-sdk-ios/pull/3411. In the mean time you might be able to work around the crash by invoking hostedUI using a dummy `SignInUIOptions`:

```swift
let hostedUIOptions = HostedUIOptions(scopes: ["openid"])
        let signInUIOptions = SignInUIOptions(logoImage: nil)
        AWSMobileClient.default().showSignIn(navigationController: self.navigationController!,
                                             signInUIOptions: signInUIOptions,
                                             hostedUIOptions: hostedUIOptions) { (state, error) in

        }
```

**Comment by abildgaard** [comment]
Latest release version (2.22.2) works with my testing - thanks for the fast turnaround!
