### ISSUE TITLE
How to get HLS URL with AWSKinesisVideoArchivedMedia 

### ISSUE THREAD

**Issue by HiLittlePiper** [aws-amplify/aws-sdk-ios#3420]
Hello everyone:

I want to use AWSKinesisVideoArchivedMedia to fetch the HLS URL of Video Stream, but it will return the error below:

**error	Error?	domain: "com.amazonaws.AWSKinesisVideoArchivedMediaErrorDomain" - code: 7	0x0000000282044990

[1]	(null)	"NSLocalizedFailureReason" : "ResourceNotFoundException:https://kinesisvideo.amazonaws.com/doc/2017-09-30/"**

but actual web client can get the HLS URL to view this stream .

I refer to the AWSKinesisVideoArchivedMediaTests sample, could you give me some suggestion to solve this issue?

appreciate for help !!!

Attachment:
<img width="814" alt="AWSKinesisVideoArchivedMedia Error" src="https://user-images.githubusercontent.com/49709583/107062690-88e0ca80-6814-11eb-8f45-f3926b3162a3.png">

**Comment by lawmicha** [comment]
Hi @HiLittlePiper, coud you provide more details to reproduce this? Could like to narrow this down to an issue with the SDK or the service. 

Could you provide how you set you the AWS backend and the code snippet that you are referring to that is causing the error? 

> but actual web client can get the HLS URL to view this stream .

what does this mean? is that the AWS Console?
