### ISSUE TITLE
MQTT reconnect in background getIdentityRef error: -25308

### ISSUE THREAD

**Issue by mikeper031** [aws-amplify/aws-sdk-ios#3423]
Hi. We are experiencing connection issues using the IotDataManager mqtt API  in the following circumstances

1. connect the app to IOT using **iotDataManager.connect(...)** when app in foreground - success publish/subscribe
2. issue disconnect after a while when app is in foreground
3. issue a connection after a while when the app is in background using **iotDataManager.connect(...)** i get the error:
    **getIdentityRef error: -25308
    Could not find SecIdentityRef**
4. issue a connection after a while when app is in background using **iotDataManager.connectUsingWebSocket(...)** - success publish/subscribe

AWS IOS SDK version: 2.21.0

**Comment by gadget-man** [comment]
I'm having exactly the same issue (AWS iOS SDK version : 2.27.6. I'd love to know if this issue was ever resolved (or a workaround identified)

**Comment by gadget-man** [comment]
Searching around on the internet for similar issues from others, I also wonder whether this is relevant:
https://github.com/evgenyneu/keychain-swift/issues/78#issuecomment-549045569

**Comment by harsh62** [comment]
@gadget-man Our team is investigating the issue the will provide an update soon.

**Comment by gadget-man** [comment]
@harsh62  are you able to provide any update (or timescales) for this fix?  Currently, Apple Watch apps that need to call the AWS iOS SDK on their paired phone in the background are unable to work.

**Comment by royjit** [comment]
The change has been released in version 2.27.10 https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.27.10
