### ISSUE TITLE
AWSCognito Cocoapods not updated to 2.22

### ISSUE THREAD

**Issue by danquack** [aws-amplify/aws-sdk-ios#3429]
**Describe the bug**
A clear and concise description of what the bug is. Please be as detailed as possible and help us help you.

**To Reproduce**
1. Go to https://cocoapods.org/pods/AWSCognito https://github.com/CocoaPods/Specs/tree/master/Specs/7/9/a/AWSCognito 

**Observed Behavior**
The latest available is 2.19.1

**Expected Behavior**
2.22.2 Should be in line with the other AWS Pods. Im trying to utilize functionality implemented with core 2.22 release, but without the cognito pod update, I can not update.

**Comment by palpatim** [comment]
@danquack The AWSCognito SDK was [deprecated in December 2018](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.8.0), and we [stopped distributing it in December 2020](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0).
