### ISSUE TITLE
AWSMobileClient returning same error (notAuthorized) in different scenarios. How are we to differentiate?

### ISSUE THREAD

**Issue by tylerjames** [aws-amplify/aws-sdk-ios#3431]
**State your question**
I'm using a native experience for sign in and I'd like to add some reliable error handling. However I'm running into some issues with the API that make it difficult to do so. They are the following:

1. The `AWSMobileClientError` enum is roughly 40 items long. The documentation for something like `AWSMobileClient.signIn()` doesn't state which errors could be thrown so we're left to make an educated guess based on the error names and handle the rest in a generic way.
2. There are no error codes or underlying errors propagated. This would be fine if it weren't for the next point:
3. **The same error case is being used for more than one scenario** and the only way to differentiate between them is by parsing the English language error message. For example if I call `AWSMobileClient.signIn()` with the wrong password I'll get: `notAuthorized(message: "Incorrect username or password.")` if I try a few more times with the wrong password I'll get: `notAuthorized(message: "Password attempts exceeded")`

I don't want to show these back-end error messages to the user (what if they don't speak English?) I need to map them to my own localized error messages. Also, if there's something to be done about a "Password attempts exceeded" error then I'll need to tell the user that as well ("Try again in a few minutes?", "Reset your password" etc)

There are some dedicated error cases `tooManyFailedAttempts(message: String)`, `tooManyRequests(message: String)` that might be more appropriate here but aren't used.

So what's the appropriate way of handling these overloaded errors? I could parse the English language string but it appears to be coming from the backend so it could be changed at any time.

Ugh. After typing all this I found a Github issue on the JS version of the library ([here](https://github.com/amazon-archives/amazon-cognito-identity-js/issues/479)) mentioning the same problem in 2018. That person was referred to an existing issue from 2017 ([here](https://github.com/amazon-archives/amazon-cognito-identity-js/issues/479)).

So any hope of this ever been sorted out is effectively nil.

**Which AWS Services are you utilizing?**
AWS Cognito Auth

**Environment(please complete the following information):**
 - SDK Version: 2.19.1
 - Dependency Manager: CocoaPods
 - Swift Version : 5

**Comment by palpatim** [comment]
Long term, we need to audit errors from the service to ensure we have comprehensive coverage of error scenarios.

Unfortunately, there is not a good short-term fix for this--any changes we make to error structures or behaviors are likely to break existing clients, and without the audit noted above, it's not clear what we could do to enhance the current developer experience.

We'll take this on as a feature request to come up with a more robust error handling paradigm.

**Comment by dlamon1** [comment]
Could there be an attribute added to the response object with a string stating which aspect of the auth threw the error e.g. password / username / email / phone. With just that attribute alone a switch case could easily be checked client side.

**Comment by shivam-heady** [comment]
I've been facing a similar situation re: error handling.
There can be a lot of possibilities of what went wrong during any authentication flow and we should be in a position to convey this to the user to ensure they're aware of next steps on their part. 

One possible workaround I've been thinking of is to show the user a verbose message of _what could've possibly gone wrong_ and how best they can resolve this issue, and append the error string sent by the server as a technical description. 

A feasible workaround for now, but the error handling should be verbose and all possible cases should be available thru the SDK.

**Comment by atierian** [comment]
Thanks for opening this issue. We recommend using the Auth category in Amplify Swift for all of your app authentication / authorization related needs -- for more information, please visit https://docs.amplify.aws/swift/build-a-backend/auth/
