### ISSUE TITLE
Update Facebook SDK to version 9.x

### ISSUE THREAD

**Issue by joeboyscout04** [aws-amplify/aws-sdk-ios#3432]
**Which AWS Services is the feature request for?**
AWSFacebookSignIn, Cognito, AWSMobileClient

**Is your feature request related to a problem? Please describe.**
The `AWSFacebookSignIn` portion of the AWS SDK is currently locked to version 8.0.0 of `FBSDKCoreKit`/`FBSDKLoginKit` in Cocoapods.  (See #2944 ).

Facebook recently released version 9.0 of their SDK and deprecated version 8.0 and below. 
https://developers.facebook.com/blog/post/2021/01/19/introducing-facebook-platform-sdk-version-9/

Facebook's 9.0 SDK introduced "limited data" mode, presumably to comply with the changes from Apple dealing with AppTrackingTransparency in iOS 14.  Specifically, Apple as mentioned that they will start to require apps to request permission before gathering tracking data from users starting with iOS 14.5.  

**Describe the solution you'd like**
AWSMobileClient should upgrade to Facebook 9.0 SDK and handle the additional migration steps to support "limited data" mode. 

**Describe alternatives you've considered**
None

**Additional context**
Additional information about the changes to User Privacy from Apple:
https://developer.apple.com/app-store/user-privacy-and-data-use/

**Comment by royjit** [comment]
@joeboyscout04 Thank you for bringing this to our notice.

Concerns regarding adding the new SDK:

1. This looks like a breaking change from the release notes Facebook has removed Auto Initialization of SDK.

> Currently, the Facebook Platform SDKs automatically initializes on launch. We will be removing this auto-initialization feature beginning today.
> 
> If you currently rely on the Facebook Platform SDKs being automatically initialized for use, you will now need to explicitly initialize the SDK by making the appropriate calls. More information about initializing the SDKs can be found at - https://developers.facebook.com/docs/ios/getting-started/

2. We might need to provide an api to adjust "Limited" login. mode.

Created a draft PR - https://github.com/aws-amplify/aws-sdk-ios/pull/3433

**Comment by royjit** [comment]
The PR is merged in and released in AWS iOS SDK 2.23.0 - https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.23.0

**Comment by joeboyscout04** [comment]
Thanks for the quick work!
