### ISSUE TITLE
federatedSignIn always returns `signIn`state

### ISSUE THREAD

**Issue by ppave** [aws-amplify/aws-sdk-ios#3435]
I've set up project using `amplify add auth`. Successfully checked guest users appeared in Cognito Identity Pool. After I have enabled my OpenID Authentication provider in Identity Pool settings.

I've tried the following scenarios:
1. No guest users allowed, no custom identity providers allowed
2. Guest users allowed, no  custom identity providers allowed
3. Guest users allowed, custom identity providers allowed

Tried both Amplify Escape Hatch  approach and AWSMobileClient
```swift
         let plugin = try Amplify.Auth.getPlugin(for: "awsCognitoAuthPlugin") as! AWSCognitoAuthPlugin
            guard case let .awsMobileClient(awsmobileclient) = plugin.getEscapeHatch() else {
                print("Failed to fetch escape hatch")
                return
            }
            print("Fetched escape hatch - \(awsmobileclient)")
        
            awsmobileclient.federatedSignIn(providerName: "asdsadsda",
                                            token: "asdsda") { (userState, error) in
                if let error = error {
                    print("Error in federatedSignIn: \(error)")
                    return
                }

                guard let userState = userState else {
                    print("userState unexpectedly nil")
                    return
                }
                print("federatedSignIn successful: \(userState)")
            }
```

```
     AWSMobileClient.default().federatedSignIn(providerName: IdentityProvider.facebook.rawValue, token: "FACEBOOK_TOKEN_HERE") { (userState, error)  in
                if let error = error {
                    print("Federated Sign In failed: \(error.localizedDescription)")
                } else {
                    print("Federated Sign In succeeded: \(userState)")
                }
            }
```

Putting any fake data into `providerName` and `token` all the time I get `signedIn` userState.

I've tried to call `federatedSignIn` on empty projects with default (username) configuration, social providers configuration, guest users configuration - all the time `federatedSignIn` is successful with singIn userState.

Meanwhile, I am able to pass the `federatedSignIn` process with valid identity name and token - in this case I see a linked login in Identity Pool.

**Comment by royjit** [comment]
Closing this as duplicate - https://github.com/aws-amplify/aws-sdk-ios/issues/1307. We will update the [ticket 1307](https://github.com/aws-amplify/aws-sdk-ios/issues/1307) when we have more info.
