### ISSUE TITLE
Cannot archive project for the app store or build XCFramework when setting -fembed-bitcode in project settings

### ISSUE THREAD

**Issue by sha8wn** [aws-amplify/aws-sdk-ios#3462]
Hello AWS Team,

**Describe the bug**
I am developing an XCFramework and have integrated the AWSLambda pod as my only dependency for my needs https://cocoapods.org/pods/AWSLambda which I believe also installs AWSCore. I want my framework to support bitcode so after looking at some ideas online, I added -fembed-bitcode to my framework project's build settings: 
![image](https://user-images.githubusercontent.com/1778742/110192486-e08c4900-7e47-11eb-8028-a421ab59d043.png)

and have set BITCODE_GENERATION_MODE to bitcode in my target's build settings as you can see here: 
![image](https://user-images.githubusercontent.com/1778742/110192539-1cbfa980-7e48-11eb-911d-fcf6757e3377.png)

Now I am trying to build the framework or archive my demo project to upload to the store and I see the following error:
```
ld: bitcode bundle could not be generated because '/Users/shawnfrank/Library/Developer/Xcode/DerivedData
/BanyanService-fyspisckoapkweaevvtajphnszki/Build/Products/Debug-iphoneos/AWSCore/AWSCore.framework
/AWSCore' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode 
Archive or Install build file '/Users/shawnfrank/Library/Developer/Xcode/DerivedData/BanyanService-
fyspisckoapkweaevvtajphnszki/Build/Products/Debug-iphoneos/AWSCore/AWSCore.framework/AWSCore' 
for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The screenshot of what was shown in my xcode: 
![image](https://user-images.githubusercontent.com/1778742/110192549-2c3ef280-7e48-11eb-9a92-fa0b10b1f528.png)

**To Reproduce**
1. Open XCode and create an XCFramework or Framework as it is called now
2. Integrate AWSLambda as a pod dependency and install the pods, project structure: http://prntscr.com/10du588
3. Make the build settings as described: http://prntscr.com/10du6sj  and http://prntscr.com/10du7uf
4. Try to build the framework or archive the project
5. The error mentioned above appears

**Expected Behavior**
The Framework to build successfully and projects integrating the framework to archive successfully.

**Proposed Solution**

- An updated version which takes care of this issue
- Perhaps I am doing something wrong and I need to change something ?
- I am open to manually integrating the framework if this is the fastest way, if you can tell me what settings would need to be changed in order to manually embed AWSCore and AWSLambda frameworks

Thanks in advance

**Comment by palpatim** [comment]
Thanks for the detailed report @sha8wn. Minor note: Could you attach your screenshot images to the GitHub issue rather than linking to a third party solution like prntscr.com? That domain in particular is blocked by some enterprises (including ours), so it'll be challenging for everybody to see the settings & messages you're referencing.

In any case, we may be able to fix this by enabling bitcode in our project, but we'll need to research to see the right way to do it. It's not immediately clear to me whether this is enabled on a per-framework build, or at the archive level, or at some other intermediate step like `bitcode_bundle`.

**Comment by sha8wn** [comment]
Hello @palpatim - Thanks for your response. I have added the screenshots as per your request.

I understand this will probably take some time to fix and release, is there any solution I can take in the interim so that I can build my project ?

As I mentioned, I am open to manually installing the AWS Lambda and AWS Core frameworks for now and manually changing the build settings for them if you can guide me as I need to ship my SDK soon so if you have any advice on that front while you fix this - that would be much appreciated.

Thanks.

**Comment by palpatim** [comment]
@sha8wn Sorry, without more troubleshooting, I can't suggest a workaround. You might be able to build the SDK projects from source as you build your framework, but I'm guessing that's not a great option for you.

**Comment by sha8wn** [comment]
Hello @palpatim ,

Hope you had a good weekend.

I am open to that solution until you'll investigate and fix this with cocoapods. 

If I can understand which specific frameworks I need and any other settings I need to modify when manually integrating these frameworks, that would be helpful.

Is it just AWS Core and AWS Lambda to work AWS Lambdas ?

Thank you for your support and guidance.

**Comment by palpatim** [comment]
> Is it just AWS Core and AWS Lambda to work AWS Lambdas ?

Correct! The **AWSLambda** SDK depends on **AWSCore**, which itself has no additional external dependencies.

**Comment by sha8wn** [comment]
Hi @palpatim - it's proving quite difficult to manually build this so I was wondering if there was a way to manually make calls to AWSCognito and invoke AWSLambdas without the frameworks as a raw HTTP request or something like that you could point me towards ?

**Comment by palpatim** [comment]
It is certainly *possible* to manually make calls to any AWS service, including Cognito or Lambda--they're just HTTPS endpoints on the public internet. Whether it's *practical* is a very different story. :) If you'd like to explore it further though, you can look through the AWS service documentation for the services you want to interact with. The service's API reference will explain the various request and response shapes, which you would provide as JSON payloads when you invoke the service at the HTTP endpoint.
