### ISSUE TITLE
Creating an AWSDynamoDBObjectModel subclass with an existing property name

### ISSUE THREAD

**Issue by sha8wn** [aws-amplify/aws-sdk-ios#3472]
Hello AWS Team,

Hope you are doing well.

**State your question**
I am trying to scan a DynamoDB table and to make things easier for me, I want to map the results to an AWSDynamoDBObjectModel. The issue I have currently is that one of the items in my table have the key `description` so you can say my data is something like this:
```
{
  "userId": "1234",
  "description": "something"
}
```

Now in my AWSDynamoDBObjectModel subclass, I try to create a property description and it seems that it is already used as I get the error in Xcode: `Cannot override with a stored property 'description'`

Is my only solution to change the name at the source or something can be done to override this at the ios sdk level ?

**Which AWS Services are you utilizing?**
AWSDynamoDB

**Environment(please complete the following information):**
 - SDK Version: [latest version]
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Comment by palpatim** [comment]
@sha8wn You'll have to override this at your model source. Currently we face similar challenges as we translate service APIs into service clients--the service might define a `description` field on a request or response object, and we have to translate that to something like `descriptionValue` to avoid conflicting with keywords & reserved property names.

(As a side note, we don't generally recommend direct access to DynamoDB from an app layer--it doesn't scale as well, and doesn't provide the same security options, as fronting your persistence layer with a dedicated API layer like AppSync or API Gateway.)

Hope this helps.

**Comment by sha8wn** [comment]
Thanks @palpatim - got it, clear.

Thanks for the advice as well, for now we are connect to DynamoDB only for our app used by our QA team to make sure everything is done right and not in any release or client facing applications.
