### ISSUE TITLE
The right way to clear AWSCognitoCredentialsProvider

### ISSUE THREAD

**Issue by sha8wn** [aws-amplify/aws-sdk-ios#3473]
Hello AWS Team,

**State your question**

This is possibly a duplicate to #1014 but I could not find a useful solution there that worked for me.

I have two environments `development` and `production` which has it's own `identityPoolIds` respectively.

My team constantly needs to switch between these two environments.

It seems that once I set the environment on launch, there is no going back in that session, I need to quit the app and restart again for the changes to reflect and pull data from the right environment.

Even after calling `invalidateCachedTemporaryCredentials`, `clearCredentials`, `clearKeychain` on the `AWSCognitoCredentialsProvider` it still seems to use the cached version and not the new ones I provide.

How do I properly tear down / reset the `AWSCognitoCredentialsProvider` or the default `AWSServiceConfiguration` so that I can dynamically switch environments or a way to hold initialize multiple credentials providers ?

**Which AWS Services are you utilizing?**

AWSCore, AWSDynamoDB

**Provide code snippets (if applicable)**

I have a tear down function which gets called first
```
private static func tearDownCognito() {
    if let credentialsProvider = AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider 
    as? AWSCognitoCredentialsProvider {
      credentialsProvider.invalidateCachedTemporaryCredentials()
      credentialsProvider.clearCredentials()
      credentialsProvider.clearKeychain()
    }
}
```

Then I have another function to set the configuration:
```
private static func authenticateWithCognito(inEnvironment environment: AWSEnvironment) {

    tearDownCognito()

    var identityPoolId = AWSConstants.COGNITO_IDENTITY_POOL_ID_DEVELOPMENT
    
   if environment == .production {
      identityPoolId = AWSConstants.COGNITO_IDENTITY_POOL_ID_PRODUCTION
    }
    
    let credentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSConstants.COGNITO_REGIONTYPE,
                                                            identityPoolId: identityPoolId)
    
    let serviceConfiguration = AWSServiceConfiguration(region: AWSConstants.COGNITO_REGIONTYPE,
                                                       credentialsProvider: credentialsProvider)

    AWSServiceManager.default().defaultServiceConfiguration = serviceConfiguration
}
```
**Environment(please complete the following information):**
 - SDK Version: Latest versions of both
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Comment by palpatim** [comment]
@sha8wn We don't currently support switching environments without restarting the app. You can read a more extensive discussion here: https://github.com/aws-amplify/amplify-ios/issues/527 (that issue happens to be in the Amplify repo, but the underlying issues are the same).

**Comment by sha8wn** [comment]
@palpatim - can I conclude that I also cannot have multiple service configurations in the same session ?
