### ISSUE TITLE
multi-part upload resume after restarting the app using transferUtility with key 

### ISSUE THREAD

**Issue by Faisal666** [aws-amplify/aws-sdk-ios#3479]
**State your question**
How to make upload resume after restarting the app using transferUtility with key 

**Which AWS Services are you utilizing?**
AWS S3

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.23.2 
 - Dependency Manager: Cocoapods
 - Swift Version : 4.3

**Device Information (please complete the following information):**
 - Device:iPhone x, 8 plus
 - iOS Version: 14.4

**Comment by palpatim** [comment]
@Faisal666 are you reporting something different than you reported in https://github.com/aws-amplify/aws-sdk-ios/issues/3474 ?

**Comment by Faisal666** [comment]
@palpatim 
I'm requesting only an info or guide here not reporting a issue.

**Comment by palpatim** [comment]
Thanks for clarifying. Please see the [Managing Transfers When an App Restarts](https://docs.amplify.aws/sdk/storage/transfer-utility/q/platform/ios#managing-transfers-when-an-app-restarts) documentation.

**Comment by brennanMKE** [comment]
See #3817
