### ISSUE TITLE
Sign in with Apple token invalid after sign in

### ISSUE THREAD

**Issue by martaGonz** [aws-amplify/aws-sdk-ios#3484]
After a successful sign in, my federated tokens get invalidated. It only happens with "Sign in with Apple". So the users who sign in with Apple can't make API requests.

**Which AWS Services are you utilizing?**
Amplify
Cognito

**Provide code snippets (if applicable)**
```
  AWSMobileClient.default().federatedSignIn(providerName: IdentityProvider.apple.rawValue, token: token) { (userState, error)  in
            if let error = error {
                print("Federated Sign In failed: \(error.localizedDescription)")
            }else{
                print("federatedSignIn successful: \(userState)")
            }
        }
```

The result in the console:
AWSMobileClient Event listener - signedIn
AWSMobileClient Event listener - signedOutFederatedTokensInvalid
 
Do I have to refresh the token? How can I do it?  I use my own sign in UI

**Comment by palpatim** [comment]
Hi @martaGonz,

Please see https://github.com/aws-amplify/aws-sdk-ios/issues/2513#issuecomment-774130422 for a discussion of Cognito's current support for Sign In With Apple. In that discussion, you'll see that the options for supporting `federatedSignIn` are to require your user to login after the initial Apple **identity token** expires (24 hours), or to set up a backend layer that can use the authorization token, refresh token, and client secret to request new identity tokens on your user's behalf.

That said, in your issue report above, you might be saying that this happens immediately after a user signs in, which would not be expected. If that's the case, we'll need some more detail:

- How did you configure your IdentityPool to use Sign In With Apple as an Authentication Provider? Is the **Apple Service ID** you used in that configuration the same as the app bundle ID for your application?
- What is the value of the `token` you're passing above? Can you provide some more code around that snippet?
- How are you initializing AWSMobileClient before calling `federatedSignIn`?

**Comment by martaGonz** [comment]
Hi @palpatim, 

I read that thread before but I don't know how to to do that backend layer for the authorization token. Is there a tutorial about how to do that?

1) I did this 1-2 years ago and it has been working well until recently. 
The Apple Service ID is different from the app bundle ID. 

2) The token I pass is the AppleIDCredential from here: 

` if let appleIDCredential = authorization.credential as? ASAuthorizationAppleIDCredential {
let userID = appleIDCredential.user`


3) This is my AppDelegate where I put all the initialisations:

`    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

           do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin()) 
            try Amplify.add(plugin: AWSAPIPlugin())
            try Amplify.add(plugin: AWSS3StoragePlugin())
            
            Amplify.Logging.logLevel = .verbose
            
            try Amplify.configure()
            fetchCurrentAuthSession()
           
            let cacheConfiguration = try AWSAppSyncCacheConfiguration()
       
     let appSyncServiceConfig = try AWSAppSyncServiceConfig()
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: appSyncServiceConfig, cacheConfiguration: cacheConfiguration)
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
         
            appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }
        } catch {
            print("Error initializing appsync client. \(error)")
        }
  
        // Initialize AWSMobileClient
              _ = AWSMobileClient.default()
                  .interceptApplication(application, didFinishLaunchingWithOptions:launchOptions)
      
        // FACEBOOK CONFIGURATION
         ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
          
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.APNortheast1,
           identityPoolId:"xxxxxxx")

        let configuration = AWSServiceConfiguration(region:.APNortheast1, credentialsProvider:credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
    
        // analytics
        let pinpointConfiguration = AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions)
        pinpoint = AWSPinpoint(configuration: pinpointConfiguration)
  
        AnalyticsPinpoint.shared.setupClient(withLaunchOptions: launchOptions)
        
        // push notifications
         registerForPushNotifications()
  
        return true
        
        //        initializeAppSyncWhenCognitoAuth()
        
    }`

**Comment by palpatim** [comment]
> The Apple Service ID is different from the app bundle ID. After this I tried to create a service ID with the same id as the app bundle id and it didn't let me use that same name

Sorry for the confusion: You don't need to create the service ID in Apple's site, you need to update your Cognito Identity Pool's "Sign In With Apple" configuration with your bundle ID.

**Comment by palpatim** [comment]
> The app has been using AWS for 2 years and it has been working well until recently, when I also wanted to start using the new Amplify. Maybe I broke something there.

I'm surprised that you got automatic token refresh working with Sign In With Apple in the AWS Mobile SDK for iOS. Can you share the code you used to obtain the token and pass it to the Identity Pool? The SDK doesn't have any particular refresh mechanisms, and would have relied on you manually passing it in just like Amplify does (although the API calls to pass the token are obviously different between SDK and Amplify).


> I read that thread that you mention but how can I do the refresh token on the server? Is there a tutorial on how to do this with AWS?

There is no tutorial; your app's use case will determine the right path for you. Asking your users to sign in when their token expires is the lowest effort for you, and not too burdensome for users as long as they allow SIWA flows to be approved via TouchID or FaceID. If your use case doesn't support that, you'd have to go through the service-side flow, but we do not have any documentation for that.

**Comment by martaGonz** [comment]
Yes, I ask the user to login again when the token is no longer valid, so I guess that's fine.

I have made the changes you suggested and it's working now. It's weird that I have been sending the other id to  "federated sign in" for one year and it worked.  

About the bundle ID, I have put it on the identity pool configuration, but not in the user pool. Is this correct? In the user pool I let it as it was with the Apple Service ID.  

Thank you so much for your help

**Comment by palpatim** [comment]
> About the bundle ID, I have put it on the identity pool configuration, but not in the user pool. Is this correct? In the user pool I let it as it was with the Apple Service ID.

Confusingly, yes, this is correct. :(

The User Pool uses the service-side OAuth flow, which expects the Service ID you set up on your Apple Developer account. Federated identities uses the bundle ID.

Glad it's working for you.
