### ISSUE TITLE
Hosted UI permission alert before iOS 13.0

### ISSUE THREAD

**Issue by hamzakhanfar** [aws-amplify/aws-sdk-ios#3486]
**State your question**
After login using hosted UI, I'm trying to logout but a permission alert is being presented, so how to sign out without presenting a webview?.

**Which AWS Services are you utilizing?**
AWS SDK (Cognito).

**Provide code snippets**
AWSMobileClient.default.signOut() { error in }

**Environment:**
 - SDK Version: [e.g. 2.23.2]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [e.g. 4.0]

**Device Information:**
 - Device: [iPhone8, iPhone12]
 - iOS Version: [iOS 11.1, iOS 14.3]
 - iPhone 8, iPhone 12:

I noticed that the problem was fixed recently for the iOS version above 13.0 by setting 'Private Session' flag in HostedUIOptions and sign out locally.
But I couldn’t find anyway to solve this problem and sign out without showing any webview before ios 13.0.
Also, the alert message is confusing, it showing sing in instead of sign out.

**Comment by palpatim** [comment]
Unfortunately, there is no way to prevent the alert from showing up on iOS versions prior to 13.0. That alert is presented by the system as a security measure to let end users know which site is asking to perform OAuth flows. There is no way to tell from the URL whether a given flow is a sign in or sign out flow, which means iOS' alert has a misleading message in "sign out" cases. Sorry we don't have a solution for you on this.
