### ISSUE TITLE
Getting "The network connection was lost" error in the response for GetClip API

### ISSUE THREAD

**Issue by shishir87** [aws-amplify/aws-sdk-ios#3500]
Hi,

I am developing an iOS app which have the functionality of downloading a 5 minutes Clip from KVS.
I am using GetClip API to download the clip by following this documentation.
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetClip.html

But I am facing the error "The network connection was lost" frequently when clip is getting downloaded.

Please find below details

 - SDK Version: 2.23.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1
 - Device: iPhone 6, iPhone XR (both are physical devices)
 - iOS Version: iOS 14.4.2
 - I did not use any simulator

Similar issue has been raised for Android app also. Here is the link for same.
[https://github.com/aws-amplify/aws-sdk-android/issues/2394](https://github.com/aws-amplify/aws-sdk-android/issues/2394)

**Comment by palpatim** [comment]
@hassanctech any thoughts on this one?

**Comment by palpatim** [comment]
Also pinging @disa6302

**Comment by royjit** [comment]
Requesting @aws-amplify/amplify-codegen  to check if we can get the models updated.

**Comment by lawmicha** [comment]
Pending release of https://github.com/aws-amplify/aws-sdk-ios/pull/3866

**Comment by diegocstn** [comment]
Released with AWS SDKs [v2.26.4](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.26.4)

**Comment by jijopulikkottil** [comment]
> Hi,
> 
> I am developing an iOS app which have the functionality of downloading a 5 minutes Clip from KVS. I am using GetClip API to download the clip by following this documentation. https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetClip.html
> 
> But I am facing the error "The network connection was lost" frequently when clip is getting downloaded.
> 
> Please find below details
> 
> * SDK Version: 2.23.3
> * Dependency Manager: Cocoapods
> * Swift Version : 5.1
> * Device: iPhone 6, iPhone XR (both are physical devices)
> * iOS Version: iOS 14.4.2
> * I did not use any simulator
> 
> Similar issue has been raised for Android app also. Here is the link for same. [aws-amplify/aws-sdk-android#2394](https://github.com/aws-amplify/aws-sdk-android/issues/2394)

Do you have sample code in Swift or Obj C for getClip functionality ?
