### ISSUE TITLE
APP freezes(Memory Leak) while using Lex Sample Example

### ISSUE THREAD

**Issue by jtarun4625** [aws-amplify/aws-sdk-ios#3508]
**Describe the bug**
We are using this sample application: https://github.com/awslabs/aws-sdk-ios-samples/tree/main/Lex-Sample/Swift
It freezes or hangs while using the voice method to interact with the application.  AWSLexVoiceButton does not work after the first initialization, according to me the problem is due to the memory leak and sudden increase in the CPU usage (up to 99%).
Please see the screenshot here: https://ibb.co/TB3rTQK

**To Reproduce**
1. Clone the https://github.com/awslabs/aws-sdk-ios-samples/ repo.
2. use the swift example of Lex-Sample.
3. Configure the credentials as per the Readme.
4. Run the application.
5. Go to Voice.
6. Click on the mic.
7. It will produce the output and then memory and CPU spike will happen.

**Observed Behavior**
Memory and CPU spike and app got freeze or hangs

**Expected Behavior**
There should be no sudden spike in the memory and CPU. The app should not hang.

**Stack Trace**
Follow the **To Reproduce**

**Code Snippet**
Follow the **To Reproduce**

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
Clone the Repo and see the Podfile

**Screenshots**
https://ibb.co/TB3rTQKc

**Environment(please complete the following information):**
 - SDK Version: Latest(See podfile)
 - Dependency Manager: Cocoapods
 - Swift Version : 5
 - Xcode Version: 12.4

**Device Information (please complete the following information):**
 - Device: Simulator iPhone SE (2nd Generation)
 - iOS Version: 14.4
 - Specific to simulators:

**Comment by lawmicha** [comment]
Hi @jtarun4625 could you paste the images into this github issue? prefer to access them through github, and also the links are broken now

**Comment by katsamsoft** [comment]
https://ibb.co/TB3rTQK ....
Will add the images here as well.

**Comment by thisisabhash** [comment]
Fix merged with https://github.com/awslabs/aws-sdk-ios-samples/pull/353. Please pull the latest changes from `main` to try it out.
