### ISSUE TITLE
Cannot refresh access tokens

### ISSUE THREAD

**Issue by samitaha2** [aws-amplify/aws-sdk-ios#3511]
**Describe the bug**
Once `defaultServiceConfiguration` is set, it cannot be changed. This means if a user's credentials expire mid-session, they cannot be refreshed

**To Reproduce**
```
// Set the keys/secret once with 1 & 2
let credentialsProvider = AWSStaticCredentialsProvider(accessKey: "1", secretKey: "2")
let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialsProvider)
AWSServiceManager.default()?.defaultServiceConfiguration = configuration

// Refresh the keys/secret once with 3 & 4        
let credentialsProvider2 = AWSStaticCredentialsProvider(accessKey: "3", secretKey: "4")
let configuration2 = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialsProvider2)
AWSServiceManager.default()?.defaultServiceConfiguration = configuration2

// Observe that printing the key/secret will show the values for 1&2, even though it was set for 3&4 most recently
print((AWSServiceManager.default()?.defaultServiceConfiguration.credentialsProvider.credentials()))
```

**Observed Behavior**
The keys/secret for 1&2 was printed.

**Expected Behavior**
I expect the key/secret for 3&4 to print.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSS3 2.23.3
**Screenshots**
![image](https://user-images.githubusercontent.com/73542626/114589476-b3586500-9c55-11eb-97de-355ad1e7fc4e.png)

**Environment(please complete the following information):**
 - SDK Version: [2.23.3]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [e.g. 5]
 - Xcode Version: [e.g. 12.4]

**Device Information (please complete the following information):**
 - Device: [e.g. iPad Pro 11-inch]
 - iOS Version: [e.g. iOS 14.4.2]

**Comment by palpatim** [comment]
The AWSCognitoStaticCredentialsProvider is intended for use only by static credentials--that is, credentials that don't change over the course of your app session. If you are manually managing credentials via some other mechanism, you'll need to write a custom type that conforms to `AWSCredentialsProvider` and use it as the CredentialsProvider for your SDK configuration. The `AWSCredentialsProvider` protocol requires a method called `credentials` that returns an AWSTask whose `result` is the current credentials to use. Hope this helps.
