### ISSUE TITLE
Which AWS service can I use for audio live streaming?

### ISSUE THREAD

**Issue by martaGonz** [aws-amplify/aws-sdk-ios#3532]
I have seen services and tutorials for live streaming video only. 
Can you recommend me any service, documentation or tutorial for getting this done using AWS?

**Comment by lawmicha** [comment]
Since this question has been out for awhile now and no traction, i'm going to close it since there isn't a related SDK in the repo related to this. Feel free to reach out further to the community in the Discord channel https://discord.gg/jWVbPfC
