### ISSUE TITLE
[AWSMobileClient] Dropin UI getToken call is stuck

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/aws-sdk-ios#3550]
**Steps to reproduce** 

1. Sign in to Cognito user pool using drop in UI
1. In a loop call getToken and getAWSCredentials multiple times.
1. Try to manually deprecate  the tokens while the above loops are executing, so that AWSMC will ask to signIn again. This is block all the pending getToken, getAWSCredential calls.
1. SignIn with the same user using dropInUI. 
1. Notice that the blocked calls are not completed.
1. Make another getToken call, the completion is not invoked.

**Comment by palpatim** [comment]
This only applies to drop-in UI, not to `AWSMobileClient.signIn`?

**Comment by lawmicha** [comment]
> This only applies to drop-in UI, not to `AWSMobileClient.signIn`?

I believe this is only related to drop-in UI, + @royjit to clarify, steps to repro originally from him
