### ISSUE TITLE
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Thu, 06 May 2021 11:17:04 GMT, x-amz-request-id=G08XH9BJXF245TEZ, x-amz-id-2=kd/dynZ7oiyyfut1gb7iwezVW63XL+cmN54R6LN7fyiS7R2icbQsDWXaU5a3vRYjY44FUYgJick=}

### ISSUE THREAD

**Issue by RahulWhiz** [aws-amplify/aws-sdk-ios#3569]
**Describe the bug**
When the user login and calls AWSS3TransferUtilityUploadTask then it works perfectly and gets success in response. But once the user logout and then login with a different user then AWSS3TransferUtilityUploadCompletionHandlerBlock gets failed.
**get the following error: **
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Thu, 06 May 2021 11:17:04 GMT, x-amz-request-id=G08XH9BJXF245TEZ, x-amz-id-2=kd/dynZ7oiyyfut1gb7iwezVW63XL+cmN54R6LN7fyiS7R2icbQsDWXaU5a3vRYjY44FUYgJick=}

Failed to Upload 
 {
Connection = close;
"Content-Type" = "application/xml";
Date = "Thu, 06 May 2021 11:17:04 GMT";
Server = AmazonS3;
"Transfer-Encoding" = Identity;
"x-amz-id-2" = "kd/dynZ7oiyyfut1gb7iwezVW63XL+cmN54R6LN7fyiS7R2icbQsDWXaU5a3vRYjY44FUYgJick=";
"x-amz-request-id" = G08XH9BJXF245TEZ;
}

I used contentType as image/jpeg.

**Environment(please complete the following information):**
SDK Version: 2.12.1
Dependency Manager: Cocoapods
Swift Version: Objective C

**Observed Behavior**
For the second user, AWSS3TransferUtilityUploadTask get failed
**Expected Behavior**
AWSS3TransferUtilityUploadTask should work for every user

**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.

 AWSS3TransferUtilityUploadCompletionHandlerBlock completionHandler = ^(AWSS3TransferUtilityUploadTask *task, NSError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (error) {
                NSLog (@"Failed to Upload %@",error.userInfo.description);
            } else {
                NSLog (@"Successfully Uploaded TransferID %@",task.transferID);
                NSLog (@"Successfully Uploaded Response %@",task.response);
            }
        });
    };

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
Cognito
**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.15.3 
 - Dependency Manager: Cocoapods
 - Swift Version : Objective C
 - Xcode Version: 12.4

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: 14.2
 - Specific to simulators:

**Additional context**
When using the same user(Credentials) after logout then it works. But when the second user login when the first user logout then it doesn't work for the second user. But, strangely when I kill the app then it works for the second user.

Please guide.

**Comment by palpatim** [comment]
The latest version is 2.24.0, and we have made changes to the authentication code in the intervening time between 2.19.0 and 2.24.0.

Can you provide additional info? What calls are you using to log the user in & out?

**Comment by RahulWhiz** [comment]
Actually, We are using AWSCognito (2.19.1), AWSCore (2.21.0), AWSCognitoIdentityProvider (2.21.0),  and AWSS3 (2.21.0). The latest version of the AWSCognito is 2.19.1 that's the reason we have used v2.19.1.

We are getting the following error when I have tried to Update AWSCore to 2.24.0
"CocoaPods could not find compatible versions for pod "AWSCore"(2.24.0)."

Please let me know If I am missing anything.


We are using following API for Login 
https://8dnx6cpzp1.execute-api.us-east-1.amazonaws.com/api/users/byLogin

For Logout we are not using any API. We have cleared(delete) the things form local data like token, remove remove data From Keychain and userdefaults.

**Comment by RahulWhiz** [comment]
Please advise

**Comment by palpatim** [comment]
`AWSCognito` has been deprecated for a couple of years, and we removed it altogether in December 2020. You probably won't be able to use different versions of SDK components together--we usually have validation to ensure that the versions of each SDK match Core. We haven't made a lot of code changes to the S3 SDK since 2.19.0, but we have made one that might be relevant: https://github.com/aws-amplify/aws-sdk-ios/commit/d47d7498e1

The API you linked is a lambda function, which suggests you're using some kind of custom authentication, which adds additional complexity to the investigation, and makes it hard to validate behaviors. What makes you believe this is an SDK problem rather than a custom authentication problem? Can you post code samples to reproduce this using the latest SDK and standard auth mechanisms like HostedUI or AWSMobileClient?

**Comment by RahulWhiz** [comment]
Could you please tell me What functionality AWSCognito had? We are using AWSCognito v2.19.1. Actually, what happened, I have commented AWSCognito in the podfile and installed the pod, still my app working fine. That means We are not using AWSCognito Or Other AWS frameworks use It internally. Please advise.

**Comment by palpatim** [comment]
AWSCognito was used for "Cognito Sync", which was a data synchronization feature that has been replaced AWS AppSync. No frameworks use it internally. Your app may have used it, but it's also possible that it was in your dependency tree because the Pod contained the word "Cognito" which makes it sound like something that you should pull in to get auth working. :)

**Comment by riteshpatelgate6** [comment]
Hello @palpatim 

When the customer's device's date time setting is not accurate, then the sdk does not upload the image file and throws an error **Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2“**
I recently upgraded to AWS S3 iOS sdk version 2.30.4, but it still doesn't work. However with the automatic date time setting it works perfectly. Please suggest is there any solution for this. The same case works well in the Android platform.
Thanks
