### ISSUE TITLE
Hosted UI signOutOptions completion not called if it  was previously cancelled by the user.

### ISSUE THREAD

**Issue by jarvis32123** [aws-amplify/aws-sdk-ios#3570]
I use this pattern to log out of AWS using the hosted UI. This pops up the safari browser and if you click "Continue", it will sign you out and the completion will then be called. This is good because I can ensure the user is logged out before I navigate them to a new viewcontroller.

```
// Setting invalidateTokens: true will make sure the tokens are invalidated
AWSMobileClient.default().signOut(options: SignOutOptions(invalidateTokens: true)) { (error) in
    print("Error: \(error.debugDescription)")

   // Run code here to take user to a new viewcontroller
}
```

There is one issue: If the user clicks "cancel" to the alert that comes up asking them to navigate to safari, and then clicks sign out again (which once again shows the alert), and clicks "Continue", the user gets signed out, but the completion never gets called. 

It seems to only call the first time, but not if the user cancelled it  before.

version 2.24.0

**Comment by royjit** [comment]
I could not reproduce this issue in my sample app. Followed the same steps as you mentioned. Could you please provide more  information?

1. Is this issue consistently reproducible?
2. Did you restart the app after the first `Cancel` during signout?
3. What version of iOS SDK you are  using?
4. Can you provide the code snippet that used to signIn the user.
