### ISSUE TITLE
signOut with options shows incorrect alert to launch browser.

### ISSUE THREAD

**Issue by jarvis32123** [aws-amplify/aws-sdk-ios#3571]
When I use this code to sign out it shows me an alert that says "sign in" when it should show "sign out. This is confusing the the end user and they may not press "continue" to sign out.

```
// Setting invalidateTokens: true will make sure the tokens are invalidated
AWSMobileClient.default().signOut(options: SignOutOptions(invalidateTokens: true)) { (error) in
    print("Error: \(error.debugDescription)")
}
```

<img width="262" alt="Screen Shot 2021-05-10 at 12 21 50 PM" src="https://user-images.githubusercontent.com/50498410/117713441-859a0980-b18a-11eb-881e-fb3d8c199e25.png">

2.24.0

**Comment by palpatim** [comment]
I'm not sure what you're asking. The flow is iOS' standard implementation of OAuth, which explicitly prevents an app from knowing anything about the underlying auth flow, to protect user credentials like username & password. What are you concerned about?

**Comment by jarvis32123** [comment]
@palpatim I think I misunderstood. Never mind, thank you.

**Comment by MuhammadSalmanSiddiqui** [comment]
Tackle this issue using Javascript, I just added a condition of checking logout word in a path generated on pressing signOut button. That's it.

`async function urlOpener(url, redirectUrl) {
  if (await InAppBrowser.isAvailable()) {
    if (!url.includes("logout")) {
      const { type, url: newUrl } = await InAppBrowser.openAuth(
        url,
        redirectUrl,
        {
          modalEnabled: false,
          showTitle: false,
          enableUrlBarHiding: false,
          enableDefaultShare: false,
          ephemeralWebSession: false,
        }
      );
      if (type === "success") {
        Linking.openURL(newUrl);
      }
    }
  }
}`
