### ISSUE TITLE
How can I attach the myIOTPolicy policy to the user’s Cognito Identity Id in code?

### ISSUE THREAD

**Issue by lgh89** [aws-amplify/aws-sdk-ios#3574]
**Describe the bug**

How can I attach the myIOTPolicy policy to the user’s Cognito Identity Id in code?
Just like Android code：
AttachPolicyRequest attachPolicyReq = new AttachPolicyRequest();
attachPolicyReq.setPolicyName("myIOTPolicy"); // name of your IOT AWS policy
attachPolicyReq.setTarget(AWSMobileClient.getInstance().getIdentityId());
AWSIotClient mIotAndroidClient = new AWSIotClient(AWSMobileClient.getInstance());
mIotAndroidClient.setRegion(Region.getRegion("<YOUR-AWS-REGION>")); // name of your IoT Region such as "us-east-1"
mIotAndroidClient.attachPolicy(attachPolicyReq);

I found that IOS does not have this part in the document, but Android does：
https://docs.amplify.aws/sdk/pubsub/getting-started/q/platform/android#aws-iot

**Comment by royjit** [comment]
Do you have `TestFullPolicy` IAM policy defined in your  AWS IoT Console? Looks like the error is `ResourceNotFoundException` suggesting that the policy might not be present?
