### ISSUE TITLE
How to set AWSNetworkingRetryType.shouldCorrectClockSkewAndRetry for AWSS3TransferUtility

### ISSUE THREAD

**Issue by nastasiupta** [aws-amplify/aws-sdk-ios#3582]
I want to set `shouldCorrectClockSkewAndRetry` when using `let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "USEast1S3TransferUtility")` to upload a file to server.
If I set my device time to manual and change it the current date - 30 mins, for example, and using `transferUtility?.uploadFile(fileURL, bucket: bucketName, key:...` I get an error while uploading. I want to retry the request with this option set `shouldCorrectClockSkewAndRetry`, but I don't find how can I set it. 

**Environment(please complete the following information):**
 - SDK Version: 
'AWSElasticLoadBalancing', '2.24.1'
'AWSS3', '2.24.1'
'AWSCore', '2.24.1' 
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Comment by brennanMKE** [comment]
You can call `aws_setRuntimeClockSkew` which is available from AWSCore. You can see it is used in [AWSSignature](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCore/Authentication/AWSSignature.m#L212) where it will use that date when preparing a pre-signed URL. 

Let us know if this works for you.
