### ISSUE TITLE
Remove strip-frameworks.sh AWSCore build product

### ISSUE THREAD

**Issue by brennanMKE** [aws-amplify/aws-sdk-ios#3622]
**Describe the bug**

A shell script is included in the build product when it should not be a part of the build target.

**To Reproduce**

1. Build AWSCore
2. View the contents in the .framework directory
3. See strip-frameworks.sh is in there

**Observed Behavior**

Script is included as a resource in the framework.

**Expected Behavior**

This is a script meant to be run as a part of the build, not included as a resource.

**Stack Trace**

N/A

**Code Snippet**

N/A

**Unique Configuration**

N/A

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

AWSCore

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]
 - Xcode Version: [e.g. 11.4]

Xcode 12.5

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**

N/A

**Relevant Console Output**

N/A

**Comment by palpatim** [comment]
Now that we're building XCFrameworks, we should be able to remove this altogether, and remove references from it in docs.

@royjit, thoughts?
