### ISSUE TITLE
iOS crash in APP enterbackground and close MQTT

### ISSUE THREAD

**Issue by winfast** [aws-amplify/aws-sdk-ios#3625]
**Describe the bug**
A clear and concise description of what the bug is. Please be as detailed as possible and help us help you.

**To Reproduce**

**Observed Behavior**

**Expected Behavior**

**Stack Trace**
Please provide a stack trace if applicable e.g. a crash is occurring.

**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSCore, AWSIOT)

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.42.2]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]
 - Xcode Version: [e.g. 11.4]

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: [e.g. iOS 14.2]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here like your specific use case.

**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
<img width="1220" alt="截屏2021-06-05 下午4 56 30" src="https://user-images.githubusercontent.com/7712917/120886143-04198800-c61f-11eb-94b2-e31f04627548.png">

#11 Thread
AWSIoT.  -[AWSIoTMQTTClient cleanUpToDecoderStream] + 108

AWSIoT   -[AWSIoTMQTTClient webSocket:didCloseWithCode:reason:wasClean:] + 204

AWSIoT  __41-[AWSSRWebSocket safeHandleEvent:stream:]_block_invoke_2 + 148

libdispatch.dylib  __dispatch_call_block_and_release + 32

libsystem_pthread.dylib
__pthread_wqthread + 216

**Comment by royjit** [comment]
Closing this as duplicate, please add more details to this thread - https://github.com/aws-amplify/aws-sdk-ios/issues/3303
