### ISSUE TITLE
Can't use the Storage library with App Clips because of background downloads

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/aws-sdk-ios#3632]
The S3 storage library cannot be used with App Clips because such library defaults to downloading using background tasks, which App Clips don't allow.

It would be great to have a way to force the download to happen in the foreground to obviate this issue.

**Comment by palpatim** [comment]
Currently, the AWS SDK for iOS is only supported for iOS apps, not extensions, app clips, or widgets. Closing this issue in favor of the [open feature request](https://github.com/aws-amplify/aws-sdk-ios/issues/2978)
