### ISSUE TITLE
Issue using cognito with xcode

### ISSUE THREAD

**Issue by OwenCozine** [aws-amplify/aws-sdk-ios#3634]
**State your question**
I have been unable to get cognito to work on the app I am building. I copied the AWS IOS tutorial app and have been using the same code for sign in. However, whenever I try to run the app I get stuck on the sign in screen and have this error: 
Sign in failed AuthError: There is already a user which is signed in. Please log out the user before calling showSignIn. 
Any idea how to fix this?
**Which AWS Services are you utilizing?**
Cognito
**Provide code snippets (if applicable)**
class UserData : ObservableObject {
    private init() {}
    static let shared = UserData()

    @Published var notes : [Note] = []
    @Published var isSignedIn : Bool = false
}

struct ContentView: View {
    
    @ObservedObject private var userData: UserData = .shared
    var body: some View {
    if (userData.isSignedIn) {}
    else {SignInButton()}

public func signIn() {

        _ = Amplify.Auth.signInWithWebUI(presentationAnchor: UIApplication.shared.windows.first!) { result in
            switch result {
            case .success(_):
                print("Sign in succeeded")
            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }
    }

**Environment(please complete the following information):**
 - SDK Version: 4.52.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 12 simulator
 - iOS Version: iOS 14
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by palpatim** [comment]
Can you specify which tutorial app you're using? There are a few out there, and it will be helpful to start from the same place.

Does the tutorial app work as expected? If so, what changes did you make between the tutorial and your app code that might account for the different behavior?

**Comment by OwenCozine** [comment]
> Can you specify which tutorial app you're using? There are a few out there, and it will be helpful to start from the same place.
>  I used the AWS Amplify iOS front end tutorial, where you make an app called getting started
> Does the tutorial app work as expected? If so, what changes did you make between the tutorial and your app code that might account for the different behavior?
> One of my teammates said the tutorial app was working for them, but when I go back to that commit it doesn't work for me. However, I emailed aws and they said that the issue was code-based. I have gone through the code many many times and cannot find anything that we changed with the sign in process or aws backend.
