### ISSUE TITLE
Parse Issue

### ISSUE THREAD

**Issue by Hareesh17** [aws-amplify/aws-sdk-ios#3648]
I'm using OpenCV to draw spots on face. while using openCV, I got below errors,
1. Out-of-line definition of '~basic_ostream<_CharT, _Traits>' does not match any declaration in 'basic_ostream<_CharT, _Traits>'
2. Expected member name or ';' after declaration specifiers

Latest OpenCV used. Added OpenCV in app, iOS Version 14.2

Please help me

**Comment by brennanMKE** [comment]
@Hareesh17 This repo is for the AWS SDK. If you need help with OpenCV I would have you create an issue with [that repo](https://github.com/opencv/opencv).
