### ISSUE TITLE
updateUserAttributes errors about not being logged, despite being logged in?

### ISSUE THREAD

**Issue by gt-in** [aws-amplify/aws-sdk-ios#3654]
After updating from an older version of the SDK, calls to updateUserAttributes began failing, claiming there was no user signed in, despite a user being logged in.

My app is using userPools, but I've tracked this down to the guard statement in updateUserAttributes in AWSMobileClientExtensions (that did not exist previous to SDK 2.15 or so).

It seems that the internal federationProvider variable is not being set. How is this variable set? I can't find any documentation about config file changes and I clearly have a a functioning PoolId in my config:

   ["IdentityManager": ["Default:": [:]],
 "CredentialsProvider": ["CognitoIdentity": ["Default": ["Region": "us-east-1",
 "PoolId": "us-east-1:xxxxx:userpool/my-poolid-here"]]],
 "CognitoUserPool": ["Default": ["PoolId": "my-poolid-here",
 "AppClientId": "xxx",
 "Region": "us-east-1"]]]

**Environment(please complete the following information):**
 - SDK Version: 2.19.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Device Information (please complete the following information):**
 - Device: iPhone 11, simulator
 - iOS Version: 14
 - Specific to simulators: No

**Comment by royjit** [comment]
Hi @gt-in You have to call `AWSMobileClient.default().initialize` before accessing any AWSMobileClient apis. `AWSMobileClient.default().initialize` should set the federationProvider correctly.
