### ISSUE TITLE
AWSAuthCore & AWSCognitoIdentityProviderASF Fatal Error Xcode 13 SPM

### ISSUE THREAD

**Issue by brendenk1** [aws-amplify/aws-sdk-ios#3656]
**Describe the bug**
Adding AWSiOSSDKV2 to Xcode 13 project using SPM and selecting AWSAuthCore and / or AWSCognitoIdentityProviderASF causes fatal error when launching application.

**To Reproduce**
1. Add ASWiOSSDKV2 to project packages
2. Select AWSAuthCore and or AWSCognitoIdentityProviderASF
3. Build and run project

**Observed Behavior**

After build and run the fatal error output is: 
`Library not loaded: @rpath/AWSCognitoIdentityProviderASF.framework/AWSCognitoIdentityProviderASF`

**Expected Behavior**
Application should launch without issue.

**Stack Trace**
```
Thread 1
0_abort_with_payload
10_dyld_start
```
```
dyld`__abort_with_payload:
    0x1054f2a78 <+0>:  mov    x16, #0x209
    0x1054f2a7c <+4>:  svc    #0x80
->  0x1054f2a80 <+8>:  b.lo   0x1054f2aa0               ; <+40>
    0x1054f2a84 <+12>: pacibsp 
    0x1054f2a88 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1054f2a8c <+20>: mov    x29, sp
    0x1054f2a90 <+24>: bl     0x1054f08c8               ; cerror_nocancel
    0x1054f2a94 <+28>: mov    sp, x29
    0x1054f2a98 <+32>: ldp    x29, x30, [sp], #0x10
    0x1054f2a9c <+36>: retab  
    0x1054f2aa0 <+40>: ret    
```

**Environment(please complete the following information):**
 - SDK Version: 2.24.0
 - Dependency Manager: Swift Package Manager
 - Swift Version : 5.5
 - Xcode Version: 13.0 Beta 0-1

**Device Information (please complete the following information):**
 - Device: iPhone 12 Pro Simulator
 - iOS Version: iOS 15.0

**Additional context**
Add any other context about the problem here like your specific use case.

**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
dyld[28020]: Library not loaded: @rpath/AWSCognitoIdentityProviderASF.framework/AWSCognitoIdentityProviderASF
  Referenced from:
```

**Comment by brennanMKE** [comment]
@brendenk1 Have you linked and embedded the required frameworks in your app?

See [Adding Package Dependencies to Your App].

[Adding Package Dependencies to Your App]: https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app

**Comment by brendenk1** [comment]
@brennanMKE yep! Added and use a number of Swift packages in a variety of projects. 

What's interesting about this is it will crash without even adding a single import or calling any code in the library. Just simply adding the SPM with those two modules causes the issue.

**Comment by btrane** [comment]
I'm seeing this in Xcode 12.5 as well. It _does_ resolve the package and build successfully, but crashes on startup with the same message:
```
dyld: Library not loaded: @rpath/AWSCognitoIdentityProviderASF.framework/AWSCognitoIdentityProviderASF
  Referenced from: /Users/myusername/Library/Developer/Xcode/DerivedData/LightyearLabs-epxriplappjfqtclkgympirflplo/Build/Products/Debug-iphonesimulator/AWSCognitoIdentityProvider.framework/AWSCognitoIdentityProvider
  Reason: image not found
dyld: launch, loading dependent libraries
```

Here's my stack trace:
```
Thread 1
0_abort_with_payload
10_dyld_start
```
```
dyld`__abort_with_payload:
    0x10cc54ae0 <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x10cc54ae5 <+5>:  movq   %rcx, %r10
    0x10cc54ae8 <+8>:  syscall 
->  0x10cc54aea <+10>: jae    0x10cc54af4               ; <+20>
    0x10cc54aec <+12>: movq   %rax, %rdi
    0x10cc54aef <+15>: jmp    0x10cc52cf0               ; cerror_nocancel
    0x10cc54af4 <+20>: retq   
    0x10cc54af5 <+21>: nop    
    0x10cc54af6 <+22>: nop    
    0x10cc54af7 <+23>: nop    
```

**Comment by brennanMKE** [comment]
@brendenk1 & @btrane Can you confirm that you are also bringing in AWSCore?

See the attached files which includes an Xcode workspace, Swift package and an Xcode project for the app which uses AWSCognitoIdentityProviderASF. It brings in AWSCore as well. It is able to build and run without the error you are seeing. Can you try it to see how it works for you?

[Issue3656.zip](https://github.com/aws-amplify/aws-sdk-ios/files/6743185/Issue3656.zip)
