### ISSUE TITLE
Limit change to Blob handling to Location Service

### ISSUE THREAD

**Issue by brennanMKE** [aws-amplify/aws-sdk-ios#3663]
**Describe the bug**

A recent change to Blob handling has caused changes which break integration tests.

**To Reproduce**
1. Run integration tests for AWSLambda
2. See failed tests

**Comment by diegocstn** [comment]
Fix released with [v.24.3](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.24.3)
