### ISSUE TITLE
Question about threading in AWSMobileClient and initialize/addUserStateListener

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/aws-sdk-ios#3695]
**State your question**
When using 
`AWSMobileClient.default().initialize`
and
`AWSMobileClient.default().addUserStateListener`
Do I have to use `DispatchQueue.main.async {}` in their completion closures?
I don't see anything about threading in the documentation.

**Which AWS Services are you utilizing?**
AWSMobileClient

**Provide code snippets (if applicable)**
NA

**Environment(please complete the following information):**
 - SDK Version: 2.24.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.4

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: iOS 13.5.1
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by royjit** [comment]
@Ricardo1980 Thank you for reaching out. Using of `DispatchQueue.main.async` depends on your app use case. `initialize` api is called on sync with the current thread. `addUserStateListener`'s callback will be called from multiple thread which would be asynchronous from the calling thread of `AWSMobileClient.default().addUserStateListener`

**Comment by Ricardo1980** [comment]
Thanks a lot @royjit

That's what I saw reading the source code, but no mention or documentation about that.

So, as far as I understand, when using `initialize` from a view controller or app delegate, it does not require anything special because it is already using the main thread, but when using `addUserStateListener` from these cases, then I must use `DispatchQueue.main.async`.
Am I right? Thanks a lot.

**Comment by lawmicha** [comment]
To clarify, i believe you should use `DispatchQueue.main.async` in the callback of `addUserStateListener` when your use case requires it- being the need to be on the main thread to perform UI work.
