### ISSUE TITLE
AWS lex initialisation error 

### ISSUE THREAD

**Issue by guris12** [aws-amplify/aws-sdk-ios#3704]
Getting error while initialising amazon lex service 

**Which AWS Services are you utilizing?**
AWS lex 
**Provide code snippets (if applicable)**
error Error Domain=com.amazonaws.AWSLexErrorDomain Code=0 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=AccessDeniedException:http://internal.amazon.com/coral/com.amazon.coral.service/}

**Comment by guris12** [comment]
Please provide guide on how to use Amazon lex sample code

**Comment by lawmicha** [comment]
Hi @guris12, there is a sample here: https://github.com/awslabs/aws-sdk-ios-samples/tree/main/Lex-Sample/Swift
