### ISSUE TITLE
Segmentation fault: 11 occurs in Xcode 12.5. No simple workaround.

### ISSUE THREAD

**Issue by aaadonai** [aws-amplify/aws-sdk-ios#3717]
**Describe the bug**
This issue is the same as #3563 and #3436 although the workaround presented on those issues don't work in my case.
In my case, I have implemented as proposed in the sample code here: https://github.com/awsdocs/aws-ios-developer-guide/blob/master/build/s3transferutility.rst#when-a-suspended-app-returns-to-the-foreground

I want to pass the block to the new extension method as proposed in the workaround linked in the two issues above, but when I do that I am getting a compile error that I can't figure out.

The error I am getting is:
`Assigning to 'AWSS3TransferUtilityProgressBlock  _Nullable __autoreleasing * _Nullable' (aka 'void (^__autoreleasing *)(AWSS3TransferUtilityTask * _Nonnull __strong, NSProgress * _Nonnull __strong)') from incompatible type 'AWSS3TransferUtilityProgressBlock _Nullable' (aka 'void (^)(AWSS3TransferUtilityTask * _Nonnull __strong, NSProgress * _Nonnull __strong)')` 
This is on line `20` and `21` of ViewController.swift in the sample project linked bellow.

You will also be able to see  that I had the code provided in the docs commented out. I implemented the current docs example code to see if the `Segmentation fault: 11` was also occurring before I tried the workaround for this issue.

I haven't written Objective C in a while so it might be possible that I am missing something.

It's hard to believe that the Apple Radar opened in Feb it is still open. I have tried the current Xcode 13 beta 5 and the issue still occurs there too.

I would appreciate any help. Thanks

**To Reproduce**
1. Go to 'https://github.com/aaadonai/TestAws'
2. Clone the project
3. Open the project on Xcode 
4. Compile project

**Observed Behavior**
Compile throws error when implementing an workaround that is supposed to get by the issue where the compiler crashes when using the AWS documentation sample code.

**Expected Behavior**
Project should compile without errors.

**Code Snippet**
Please find the example project here: https://github.com/aaadonai/TestAws

**Unique Configuration**
All the code to reproduce the issue is in the sample project (link above). No need to configure Cognito since the bug is triggered at compile time.

**Environment(please complete the following information):**
 - SDK Version: 2.24.1
 - Dependency Manager:  Cocoapods
 - Swift Version : 5.4.2 
 - Xcode Version: 12.5.1

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators: iPhone SE 12.5

**Comment by brennanMKE** [comment]
@aaadonai I am looking at your code from the other repo. Thanks for sharing that. I have made it build and here is the code below.

.h:

```objc
#import <AWSS3/AWSS3.h>

NS_ASSUME_NONNULL_BEGIN

@interface AWSS3TransferUtilityBlocks: NSObject

@property (nonatomic, nullable, strong) AWSS3TransferUtilityProgressBlock uploadProgressBlock;
@property (nonatomic, nullable, strong) AWSS3TransferUtilityUploadCompletionHandlerBlock completionHandlerBlock;

- (instancetype)initWithUploadProgressBlock:(nullable AWSS3TransferUtilityProgressBlock)uploadProgressBlock
                          completionHandler:(nullable AWSS3TransferUtilityUploadCompletionHandlerBlock)completionHandlerBlock;

@end

@interface AWSS3TransferUtility (Extensions)

- (void)reassignBlocks:(AWSS3TransferUtilityBlocks *)blocks;

@end

NS_ASSUME_NONNULL_END
```

.m:

```objc
#import <AWSS3/AWSS3.h>
#import "AWSS3TransferUtility+Extensions.h"

@implementation AWSS3TransferUtilityBlocks

- (instancetype)initWithUploadProgressBlock:(AWSS3TransferUtilityProgressBlock)uploadProgressBlock
                          completionHandler:(AWSS3TransferUtilityUploadCompletionHandlerBlock)completionHandlerBlock {
    self = [super init];
    if (self) {
        self.uploadProgressBlock = uploadProgressBlock;
        self.completionHandlerBlock = completionHandlerBlock;
    }
    return self;
}

@end


@implementation AWSS3TransferUtility (Extensions)

- (void)reassignBlocks:(AWSS3TransferUtilityBlocks *)blocks {

    [self enumerateToAssignBlocksForUploadTask:^(AWSS3TransferUtilityUploadTask * _Nonnull uploadTask,
                                                 AWSS3TransferUtilityProgressBlock  _Nullable __autoreleasing * _Nullable uploadProgressBlockReference,
                                                 AWSS3TransferUtilityUploadCompletionHandlerBlock  _Nullable __autoreleasing * _Nullable completionHandlerReference) {
        *uploadProgressBlockReference = blocks.uploadProgressBlock;
        *completionHandlerReference = blocks.completionHandlerBlock;
    } downloadTask:nil];
}

@end
```

Then in the Swift code I have this code.

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    let blocks = AWSS3TransferUtilityBlocks(uploadProgressBlock: uploadProgressBlock, completionHandler: completionBlockUpload)
    transferUtility.reassign(blocks)
}
```

Please try this out and let us know if it works for you.

**Comment by aaadonai** [comment]
@brennanMKE Thanks a lot!
I have just implemented your solution on my main project and it is building now.
I really appreciate your help.
