### ISSUE TITLE
Missing support for `GetClip` request

### ISSUE THREAD

**Issue by sochalewski** [aws-amplify/aws-sdk-ios#3741]
**Which AWS Services is the feature request for?**
AWSKinesisVideoArchivedMedia

**Is your feature request related to a problem? Please describe.**
The iOS library misses suport for [`GetClip`](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetClip.html) request.

On the other hand this is already live in the Android library. See [GetClipRequest.java](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-kinesisvideo-archivedmedia/src/main/java/com/amazonaws/services/kinesisvideoarchivedmedia/model/GetClipRequest.java) and its [invocation](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-kinesisvideo-archivedmedia/src/main/java/com/amazonaws/services/kinesisvideoarchivedmedia/AWSKinesisVideoArchivedMediaClient.java#L452) in their `AWSKinesisVideoArchivedMediaClient` which is an equivalent to `AWSKinesisVideoArchivedMedia`).

**Describe the solution you'd like**
An easy way to get a clip using a stream name and `AWSKinesisVideoArchivedMediaFragmentSelector` as an input.

That's exactly what the mentioned above `GetClipRequest` does (`ClipFragmentSelector` is their `AWSKinesisVideoArchivedMediaFragmentSelector`'s equivalent).

This also requires extending an existing `AWSKinesisVideoAPIName` enum to add a missing support for `AWSKinesisVideoGetDataEndpointInput.apiName` (which exists in the Android library as [`GET_CLIP`](https://github.com/aws-amplify/aws-sdk-android/search?q=GET_CLIP)).

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/aws-amplify/aws-sdk-ios/issues/3500

**Comment by royjit** [comment]
GetClip is currently supported in the SDK - https://github.com/aws-amplify/aws-sdk-ios/blob/509d4df3cb5ca09415ee98fb446b1b5221d35f5d/AWSKinesisVideoArchivedMedia/AWSKinesisVideoArchivedMediaService.m#L287

**Comment by sochalewski** [comment]
@royjit But `AWSKinesisVideoAPIName` is still missing `GET_CLIP`, so it's unusable.

> As a prerequisite to using GetCLip API, you must obtain an endpoint using `GetDataEndpoint`, specifying GET_CLIP for the `APIName` parameter.
[Source](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetClip.html)
