### ISSUE TITLE
WiFi only uploading

### ISSUE THREAD

**Issue by oleg-moseyko** [aws-amplify/aws-sdk-ios#3756]
**Which AWS Services is the feature request for?**
AWSS3TransferUtility

**Is your feature request related to a problem? Please describe.**
I  would like to have option in my app to have ability for user to upload any image/video with:
- WiFi only
- WiFi or Cellular

**Describe the solution you'd like**
it would be good to have setting: onlyWiFi.
`````
if onlyWiFi == true {
    if isAppConnectedViaWiFiWithInternet == true { start uploading process} 
    else { waiting for wifi with Internet is connected and start uploading process }
}
`````
**Code example**
`````
TransferUtility.uploadUsingMultiPart(
                data: assetData,
                bucket: bucket,
                key: key,
                contentType: meta.mimeType,
                expression: expression,
                onlyWiFi: true,  //<<<<<<<<<<
                completionHandler: AWSS3Transfer.shared.completionHandler)
                .continueWith(block: continueWithBlock)
        }
`````

**Comment by atierian** [comment]
This should be possible today through setting [allowsCellularAccess](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1409406-allowscellularaccess) to `false` / `NO` on the underlying session or, if this satisfies your use case, only invoking `uploadUsingMultiPart(...)` when the user is connected to wifi (observing through `NWPathMonitor`). Please let us know if you're still experiencing this issue.
