### ISSUE TITLE
Can't connect using a temp certificate obtained from provisioning claim.

### ISSUE THREAD

**Issue by JohannSopraSzck** [aws-amplify/aws-sdk-ios#3769]
**State your question**

How can I connect using a temp certificate obtained from provisioning claim ?

**Which AWS Services are you utilizing?**

AWS IoT

**Provide code snippets**

I request a temp certificate from provisioning claim and with that done I try to connect using the iotDataManager and my freshly received cert.

```
        let claimRequest = AWSIoTCreateProvisioningClaimRequest()!
        claimRequest.templateName = "myTemplateName"
        let claimResponse = iot.createProvisioningClaim(claimRequest)
        claimResponse.continueWith { (response) in
            if let result = response.result, let certificateId = result.certificateId {
                let uuid = UUID().uuidString;
                // Connect to the AWS IoT data plane service w/ certificate
                self.iotDataManager.connect( withClientId: uuid, cleanSession:true, certificateId:certificateId, statusCallback: self.mqttEventCallback)
            }
            return nil
        }
```

The problem is inside the connect() function there is a check to see if the private key is inside Keychain (see below):

AWSIoTMQTTClient.m:
```
- (BOOL)connectWithClientId:(NSString*)clientId
                     toHost:(NSString*)host
                       port:(UInt32)port
               cleanSession:(BOOL)cleanSession
              certificateId:(NSString*)certificateId
                  keepAlive:(UInt16)theKeepAliveInterval
                  willTopic:(NSString*)willTopic
                    willMsg:(NSData*)willMsg
                    willQoS:(UInt8)willQoS
             willRetainFlag:(BOOL)willRetainFlag
             statusCallback:(void (^)(AWSIoTMQTTStatus status))callback {
    
    if (self.userDidIssueConnect ) {
        //Issuing connect multiple times. Not allowed.
        return NO;
    }
    //Intialize connection state
    self.userDidIssueDisconnect = NO;
    self.userDidIssueConnect = YES;
    self.session = nil;
    
    SecIdentityRef identityRef = [AWSIoTKeychain getIdentityRef:[NSString stringWithFormat:@"%@%@",[AWSIoTKeychain privateKeyTag], certificateId ]];
    if (identityRef == NULL) {
        AWSDDLogError(@"Could not find SecIdentityRef");
        return NO;
    };
```

AWSIoTKeychain.m:
```
+ (SecIdentityRef)getIdentityRef:(NSString*)tag {
    OSStatus sanityCheck = noErr;
    SecIdentityRef identityRef = NULL;
    
    NSMutableDictionary * queryIdentityRef = [[NSMutableDictionary alloc] init];
    
    [queryIdentityRef setObject:(id)kSecClassIdentity forKey:(id)kSecClass];
    [queryIdentityRef setObject:tag forKey:(id)kSecAttrApplicationTag]; 
    [queryIdentityRef setObject:(id)kSecAttrKeyTypeRSA forKey:(id)kSecAttrKeyType];
    [queryIdentityRef setObject:[NSNumber numberWithBool:YES] forKey:(id)kSecReturnRef];
    
    sanityCheck = SecItemCopyMatching((CFDictionaryRef)queryIdentityRef, (CFTypeRef *)&identityRef);
    
    if (sanityCheck != noErr){
        AWSDDLogError(@"getIdentityRef error: %d",(int)sanityCheck);
        identityRef = NULL;
    }
    
    return identityRef;
}
```

And an error is reported as the private key is not in Keychain, so the connect function doesn't go anywhere.

A solution for this would be to add my certificate in Keychain using the addCertificateToKeychain() function of the AWSIoTKeychain object:

```
+ (BOOL)addCertificateToKeychain:(NSString*)cert {
        return [AWSIoTKeychain addCertificate:[AWSIoTKeychain certToDer:cert]];
}
```

But the SDK doesn't offer public access to this object and/or function.

This problem has already been reported, see below, on the AWS Developer forums and here on Github but no answer has been given to it yet.

https://github.com/aws-amplify/aws-sdk-ios/issues/552
https://forums.aws.amazon.com/thread.jspa?threadID=302154
https://github.com/aws-amplify/aws-sdk-ios/issues/1498

**Environment:**
 - SDK Version: 2.25.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information:**
 - Device: iPhone 12 Simulator & iPhone X
 - iOS Version: iOS 14.5 & iOS 14.7.1

**Comment by brennanMKE** [comment]
@JohannSopraSzck Please review this docs for [AWSIoTManager](https://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSIoTManager.html#//api/name/importIdentityFromPKCS12Data:passPhrase:certificateId:) which includes `+importIdentityFromPKCS12Data:passPhrase:certificateId:` which is the method you will want to use. You can see used in our [sample code](https://github.com/awslabs/aws-sdk-ios-samples/blob/c4b17b290538f09a29ac2fc201d67be807c3cb23/IoT-Sample/Swift/IoTSampleSwift/ConnectionViewController.swift#L171) which shows how to use a certificate you build into the app or [creating one at runtime](https://github.com/awslabs/aws-sdk-ios-samples/blob/c4b17b290538f09a29ac2fc201d67be807c3cb23/IoT-Sample/Swift/IoTSampleSwift/ConnectionViewController.swift#L189). The [code for this method](https://github.com/aws-amplify/aws-sdk-ios/blob/2ce94a7fda175ed6ffd86c993b0ace219b926ac2/AWSIoT/AWSIoTManager.m#L218) handles the integration with the keychain.

With your code you will get back `AWSIoTCreateProvisioningClaimResponse` which includes properties for [certificateId](https://github.com/aws-amplify/aws-sdk-ios/blob/625ef5d3a7b1cf33cc0f25b1af722681be9790f6/AWSIoT/AWSIoTModel.h#L3909) and [certificatePem](https://github.com/aws-amplify/aws-sdk-ios/blob/625ef5d3a7b1cf33cc0f25b1af722681be9790f6/AWSIoT/AWSIoTModel.h#L3914). You can transform PEM to PKCS12 to use with the public method.

Alternatively you can generate a certificate like it shown with the [sample project](https://github.com/awslabs/aws-sdk-ios-samples/blob/c4b17b290538f09a29ac2fc201d67be807c3cb23/IoT-Sample/Swift/IoTSampleSwift/ConnectionViewController.swift#L189-L235).

**Comment by jdanthinne** [comment]
Any idea on how to easily convert PEM to PKCS12. Is there an utility method in the SDK for that?

**Comment by jdanthinne** [comment]
For the record, I managed to convert the temp PEM certificate to a PKCS12 using a Swift version of OpenSSL, including a rootCA as well if needed. You can check my gist here: https://gist.github.com/jdanthinne/8a6557744ba5498de1952d176d293293
Any comment on that solution would be greatly appreciated.
