### ISSUE TITLE
Unable to Build AWSMobileClientXCF 

### ISSUE THREAD

**Issue by invinciible** [aws-amplify/aws-sdk-ios#3795]
I have added the target dependency as .product(name: "AWSMobileClientXCF", package: "AWSiOSSDKV2")

However in the existing project which was using `AWSMobileClient` and now when I add

#if canImport(AWSMobileClientXCF)
import AWSMobileClientXCF
#endif

It doesn't build. 

Error: Failed to build module 'AWSMobileClientXCF' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'

Xcode: 12.5.1

**Comment by lawmicha** [comment]
Hi @invinciible, thanks for opening this issue, i've transferred it over to the main repro from https://github.com/aws-amplify/aws-sdk-ios-spm so that there is more visibility

**Comment by royjit** [comment]
Looks like the CircleCI was using older Xcode version, created this PR to address this - https://github.com/aws-amplify/aws-sdk-ios/pull/3803

**Comment by invinciible** [comment]
Thank you. It's working now.

**Comment by cody1024d** [comment]
Having the same issue as @invinciible.

**Comment by bryansum** [comment]
As per https://developer.apple.com/forums/thread/674582?answerId=663665022#663665022:
> The real issue here is that pre-built binary libraries are required to be built with Library Evolution, as I stated. The compiler versions error is an example of a symptom that appears when this requirement is not met. If this library is from a vendor, please follow up with them about getting a version with Library Evolution enabled inside of an XCFramework.

`AWSMobileClientXCF` needs to be built using `BUILD LIBRARY FOR DISTRIBUTION` to truly fix this issue it seems.

**Comment by phantumcode** [comment]
Closing this issue in favor of issue https://github.com/aws-amplify/aws-sdk-ios/issues/3874
