### ISSUE TITLE
Ability to delete a cognito user through the Amplify iOS SDK (AWSMobileClient)

### ISSUE THREAD

**Issue by cyrillelegrand** [aws-amplify/aws-sdk-ios#3824]
This is a clone of issue #1207 which has been closed.

Ability to delete a user will be mandatory starting January 21, 2022, as per Apple's recent annoucements.

**Comment by dmiluski** [comment]
Hi @cyrillelegrand , did you come across any update for handling Deleting a cognate user? I'm also looking into this for our project and determining if this will be something we do through the Amplify/Client? Or via our own back end services?

**Comment by cyrillelegrand** [comment]
Release 2.26.7 from today solves this, confirmed working.
