### ISSUE TITLE
AWSCognitoAuth leaks ASWebAuthenticationSession and itself

### ISSUE THREAD

**Issue by jbb1003** [aws-amplify/aws-sdk-ios#3830]
Git tag 23185bcf6c - version 2.26.2
Xcode 13.0 (13A233)
iPhone SE running iOS 14.8
iPhone simulator running iOS 15.0

Although not documented, it is clear from checking memory traces that ASWebAuthenticationSession retains its completionHandler block after it has been called. The reference for self (AWSCognitoAuth) is not weak, so AWSWebAuthenticationSession holds a strong ref to AWSCognitoAuth. A return reference creating a loop is held by the asAuthSession variable in AWSCognitoAuth.

See AWSCognitoAuth.swift
```
@property (nonatomic, strong) ASWebAuthenticationSession *asAuthSession;

....

- (void)launchASWebAuthenticationSession:(NSURL *)hostedUIURL API_AVAILABLE(ios(13.0)) {
    NSString *callbackURLString = [[self urlEncode:self.authConfiguration.signInRedirectUri] copy];
    NSURL *callbackURL = [[NSURL alloc] initWithString:callbackURLString];
    NSString *callbackURLScheme = callbackURL.scheme;
    self.asAuthSession = [[ASWebAuthenticationSession alloc] initWithURL:hostedUIURL
                                                       callbackURLScheme:callbackURLScheme
                                                       completionHandler:^(NSURL * _Nullable url,
                                                                           NSError * _Nullable error) {
        [self handleSignInCallbackWithURL:url error:error];
    }];
```

Since AWSCognitoAuth is itself created every time we launch the hosted UI in configureAndRegisterCognitoAuth we end up leaking quite a bit more than just the ASWebAuthenticationSession,.
```
    public func showSignIn(presentationAnchor: ASPresentationAnchor,
                           hostedUIOptions: HostedUIOptions,
                           _ completionHandler: @escaping(UserState?, Error?) -> Void) {
        if case .signedIn = self.currentUserState {
            completionHandler(nil, AWSMobileClientError.invalidState(message: "There is already a user which is signed in. Please log out the user before calling showSignIn."))
            return
        }
        developerNavigationController = nil
        configureAndRegisterCognitoAuth(hostedUIOptions: hostedUIOptions, completionHandler)
```

The retain loop needs to be broken, either by making asAuthSession weak, or by explicitly nilling it in the completionHandler.

The same problem will apply to launchASWebAuthenticationSessionForSignOut

**Comment by jbb1003** [comment]
Testing shows this is also a problem for sfAuthSession (which is hardly surprising, because it works the same way under the hood)

**Comment by royjit** [comment]
Thank you for reporting the issue, here is a PR to fix: https://github.com/aws-amplify/aws-sdk-ios/pull/3969
