### ISSUE TITLE
Cannot use AWSCore latest(2.26.2) with AWSCognito

### ISSUE THREAD

**Issue by HashimPhilips** [aws-amplify/aws-sdk-ios#3839]
AWSCognito latest version available in cocoapod is 2.19.1 which depends on AWSCore 2.19.1 so basically we cannot use AWSCore 2.26.2

**To Reproduce**
* create new project
* pod init
* add the following to the pod file
   ``` 
        pod 'AWSCore','2.26.2'
        pod 'AWSCognito' 
  ```
* pod install

**Observed Behavior**
error while pod install
```
   [!] CocoaPods could not find compatible versions for pod "AWSCore":
     In Podfile:
       AWSCognito was resolved to 2.1.0, which depends on
       AWSCore (~> 2.1.0)

      AWSCore (= 2.26.2)
```

**Expected Behavior**
AWSCognito (2.26.2) version should be there which depends on AWSCore 2.26.2

**Comment by diegocstn** [comment]
@HashimPhilips we've deprecated and then removed in [v2.20.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0) the `AWSCognito` pod. We recommend using [Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios).
