### ISSUE TITLE
Eliminate blocking code in block operations

### ISSUE THREAD

**Issue by brennanMKE** [aws-amplify/aws-sdk-ios#3871]
**Describe the bug**

There are Block Operations being added to OperationQueues which use DispatchGroup to `enter()` and `leave()` with `wait()` which blocks the thread while async work is done. This work may include network activity which introduces latency while the thread is blocked. There has been evidence of thread explosion which lead to the [getAWSCredentials](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift#L765) method. This code is making the block wait on the current thread to change this block to use serial behavior so it does not leave the block until the work is completed.

An Operation transitions between 4 states: ready, executing, finished and cancelled. A Block Operation will be set to `executing` when `start()` is called on it and when the execution leaves the block it is set to `finished` allowing the OperationQueue to start other operations. This update introduces `AsyncBlockOperation` which does not block the thread and instead provides a `done()` closure to the block which is called once the async work is completed. It then changes the state to `finished` and notifies of the state change via KVO.

Testing is showing that it reduces the number of threads which are created while running many operations. Since the update operations are done for the purposes of auth it impacts every service which uses auth as well as Amplify Plugins.

See: [Asynchronous Versus Synchronous Operations](https://developer.apple.com/documentation/foundation/operation#1661231)

> If you always plan to use queues to execute your operations, it is simpler to define them as synchronous. If you execute operations manually, though, you might want to define your operation objects as asynchronous. Defining an asynchronous operation requires more work, because you have to monitor the ongoing state of your task and report changes in that state using KVO notifications. But defining asynchronous operations is useful in cases where you want to ensure that a manually executed operation does not block the calling thread.

**To Reproduce**

See [amplify-ios#1279](https://github.com/aws-amplify/amplify-ios/issues/1279) for a customer issue and a sample app which repros the issue.

**Observed Behavior**

Due to threads being blocked there is a thread explosion when there are many operations running concurrently which makes calls into `getIdentityId` which leads to this code in AWSMobileClient.

**Expected Behavior**

Threads should not be blocked when the async work can be done without blocking.

**Stack Trace**
Please provide a stack trace if applicable e.g. a crash is occurring.

See the linked issue for logs collected in the sample project.

**Comment by royjit** [comment]
This is implemented in as per this PR - https://github.com/aws-amplify/aws-sdk-ios/pull/3872
