### ISSUE TITLE
Recompile AWSMobileClientXCF with Swift 5.5 (Xcode 13.1 support)

### ISSUE THREAD

**Issue by cody1024d** [aws-amplify/aws-sdk-ios#3874]
Currently, when adding `AWSMobileClientXCF`, you get errors stating it was compiled with Swift v. 5.3.2. This is currently a **blocker** for any devs using XCode 13.1.

Creating this issue for visibility, although this was also reported in #3795

**Comment by invinciible** [comment]
@royjit This isn't fixed yet in the new release.

**Comment by diegocstn** [comment]
@invinciible which version of the SDKs are you using?

**Comment by davedega** [comment]
AWSMobileClientXCF was compiled with a different Swift compiler 

AWSiOSSDKV2. `2.27.6`
Xcode `13.3`


![image](https://user-images.githubusercontent.com/838391/162267130-80ad30d7-70e8-49ae-82c7-442e999ba084.png)

**Comment by lawmicha** [comment]
Related https://circleci.com/docs/2.0/testing-ios/
