### ISSUE TITLE
Missing support for `AWSKinesisVideoAPINameGetClip`

### ISSUE THREAD

**Issue by sochalewski** [aws-amplify/aws-sdk-ios#3916]
**Which AWS Services is the feature request for?**
AWSKinesisVideo

**Is your feature request related to a problem? Please describe.**
The iOS library misses suport for `AWSKinesisVideoAPINameGetClip` (`GET_CLIP`) in `AWSKinesisVideoAPIName`.

**Describe the solution you'd like**
An easy way to get an endpoint URL to be used in [`GetClip`](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetClip.html) request.

**Describe alternatives you've considered**
N/A

**Additional context**
#3741

**Comment by sharadrj** [comment]
The title and description for this issue seems confusing. Reading from #3741, my understanding is that GetDataEndpoint needs to be updated in iOS SDK with GET_CLIP parameter.

**Comment by sharadrj** [comment]
Currently GetDataEndpoint returns the same endpoint for GET_CLIPS and GET_HLS_STREAMING_SESSION_URL. So, while the iOS SDK is not fixed, using GET_HLS_STREAMING_SESSION_URL may work as a temporary solution.
