### ISSUE TITLE
Backup file to bucket failed : error -NSURLErrorDomain Code=-1200

### ISSUE THREAD

**Issue by sarojkumarojha** [aws-amplify/aws-sdk-ios#3932]
**Describe the bug**
we use  aws sdk in our App  to upload/download zip file to AWS bucket  , through cocoa pod 
  ```
 pod 'AWSCore', '2.19.1'
    pod 'AWSS3', '2.19.1'
    pod 'AWSCognito', '2.19.1'
```
currently we are facing backup failure issue for more number of users 
The error details here : 
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://s3.us-east-1.amazonaws.com/<bucket>....Test.sqlite.gz, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <F7911687-43C0-4E02-9B65-D01F07A6569C>.<10>, _NSURLErrorRelatedURLSessionTaskErrorKey=( "LocalDataTask <F7911687-43C0-4E02-9B65-D01F07A6569C>.<10>" ), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://s3.us-east-1.amazonaws.com/...Test.sqlite.gz, NSUnderlyingError=0x2800f5380 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSS

**Observed Behavior**
 File upload  to AWS bucket failed 

**Expected Behavior**
 File upload  to AWS bucket should success  

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
   pod 'AWSCore', '2.19.1'
    pod 'AWSS3', '2.19.1'
    pod 'AWSCognito', '2.19.1'

**Environment(please complete the following information):**
 - SDK Version: 2.19.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0
 - Xcode Version: 13.0

**Device Information (please complete the following information):**
 - Device:  iPhone 11 Pro Max
 - iOS Version:  14.8.1

**Comment by lawmicha** [comment]
Hi @sarojkumarojha, was this working before and now no longer works? Did you perform any upgrades? iOS platform support or pod updates to the SDK?

is this related and does this solve your problem? https://stackoverflow.com/questions/32755674/ios9-getting-error-an-ssl-error-has-occurred-and-a-secure-connection-to-the-ser

**Comment by sarojkumarojha** [comment]
Hi @lawmicha , thanks for the update , currently its working but for few users we are getting this error .
Due to this error back up of data to s3 bucket is failing . 
It would be good if will get to know any instance are we using HTTP ? 

BTW , there is no connection with ios9 App Transport Security (ATS), because in our App other HTTPS request are working fine .

**Comment by pablogeek** [comment]
any updates on this?

**Comment by atierian** [comment]
Please update to the latest version of the of the AWS SDK for iOS -- currently [2.33.5](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.33.5). Thanks!
