### ISSUE TITLE
IoT Tests are flaky

### ISSUE THREAD

**Issue by brennanMKE** [aws-amplify/aws-sdk-ios#3938]
`testPubSubWithMultipleMQTTBrokersWithWebSocket - AWSIoTTests.AWSIoTDataManagerTests`

This test is flaky and should be reviewed.

**To Reproduce**
1. Run test automation multiple times
2. Observe this test failing

**Comment by thisisabhash** [comment]
Released in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.26.7. Closing.
