### ISSUE TITLE
OCMock binary is not compatible with Apple Silicon M1 Macs

### ISSUE THREAD

**Issue by brennanMKE** [aws-amplify/aws-sdk-ios#3939]
**Describe the bug**

The OCMock binary (libOCMock.a) has not been built for modern Apple Silicon and is included in the repo as a binary. It will need to be updated to include a slice for arm64 for Apple Silicon.

**To Reproduce**
1. Clone SDK repo to M1 Mac
2. Build
3. Run tests

Since this binary has not been updated in a while and the header files are in the OCMock folder it will require finding the version originally used for this build or update the SDK to use a newer version of OCMock. Below are the build commands which could b used once the right version is selected. It may be close to v3.0.

```sh
CONFIGURATION=Release

xcodebuild -project Source/OCMock.xcodeproj clean
xcodebuild -project Source/OCMock.xcodeproj -scheme OCMockLib -sdk iphoneos15.0 -configuration ${CONFIGURATION} build
xcodebuild -project Source/OCMock.xcodeproj -scheme OCMockLib -sdk iphonesimulator15.0 -configuration ${CONFIGURATION} build
```

**Comment by brennanMKE** [comment]
Here is the full script.

```sh
#!/bin/sh

# git clone git@github.com:erikdoe/ocmock.git ocmock
# git checkout tags/v3.0 -b v3.0-branch

OUTPUT_DIR="./Output"

if [ -d "${OUTPUT_DIR}" ]; then
    rm -rf "${OUTPUT_DIR}"
fi

CONFIGURATION=Release

xcodebuild -project Source/OCMock.xcodeproj clean
xcodebuild -project Source/OCMock.xcodeproj -scheme OCMockLib -sdk iphoneos15.0 -configuration ${CONFIGURATION} build
xcodebuild -project Source/OCMock.xcodeproj -scheme OCMockLib -sdk iphonesimulator15.0 -configuration ${CONFIGURATION} build

BUILD_PATH=$(locate-build-path)

PLATFORMS="iphoneos iphonesimulator"

mkdir -p "${OUTPUT_DIR}"

for PLATFORM in ${PLATFORMS}; do
    LIBRARY_PATH="${BUILD_PATH}/Build/Products/${CONFIGURATION}-${PLATFORM}/libOCMock.a"
    if [ -f "${LIBRARY_PATH}" ]; then
        mkdir -p "${OUTPUT_DIR}/${PLATFORM}"
        cp "${LIBRARY_PATH}" "${OUTPUT_DIR}/${PLATFORM}"
    fi
    if [ "iphoneos" == "${PLATFORM}" ]; then
        HEADERS_PATH="${BUILD_PATH}/Build/Products/${CONFIGURATION}-${PLATFORM}/OCMock"
        if [ -d "${HEADERS_PATH}" ]; then
            cp -rp "${HEADERS_PATH}" "${OUTPUT_DIR}"
        fi
    fi
done
```

* [locate-build-path](https://gist.github.com/brennanMKE/5ca36274b3249c2086a09950039feb8f)

Since `libOCMock.a` is linked directly by many test targets the most minimal change would be to replace that binary. I do not know if a FAT binary will work in this case since arm64 for Macs may be different than it is for iPhones which are also arm64. If a single binary can work for Intel and M1 Macs to build and run tests that would be the option which has the fewest changes.

**Comment by lawmicha** [comment]
Related https://github.com/aws-amplify/aws-sdk-ios/commits/stehlib.3939-ocmock

**Comment by MikePendo** [comment]
Why not to build OCmock as xcframework? that should resolve the issue no?
