### ISSUE TITLE
Got some crash reports on Crashlytics from AWSMobileClient 2.26.6. 

### ISSUE THREAD

**Issue by koogawa** [aws-amplify/aws-sdk-ios#3949]
**Describe the bug**

The app is on poduction and we are getting these crashes frequently from AWSMobileClient 2.26.6. 

![image](https://user-images.githubusercontent.com/893643/147545762-9cbf0249-e082-4591-a12e-a0c6065f1885.png)

**To Reproduce**
1. Launch app

**Observed Behavior**

**Expected Behavior**

**Stack Trace**

<img width="1291" alt="スクリーンショット 2021-12-23 8 44 52" src="https://user-images.githubusercontent.com/893643/147546055-df129c85-3ead-4689-8fc7-bca20b2a0050.png">

**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.

```
        do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSS3StoragePlugin())
            try Amplify.configure()
        } catch {
            Logger.default().logError(error)
        }
```

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.26.6]
 - Dependency Manager: Cocoapods
 - Swift Version : 5
 - Xcode Version: 13

```
- Amplify (1.17.0):
    - Amplify/Default (= 1.17.0)
  - Amplify/Default (1.17.0)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.17.0):
    - AWSAuthCore (~> 2.26.5)
    - AWSCognitoIdentityProvider (~> 2.26.5)
    - AWSCognitoIdentityProviderASF (~> 2.26.5)
    - AWSCore (~> 2.26.5)
    - AWSMobileClient (~> 2.26.5)
    - AWSPluginsCore (= 1.17.0)
  - AmplifyPlugins/AWSS3StoragePlugin (1.17.0):
    - AWSCore (~> 2.26.5)
    - AWSPluginsCore (= 1.17.0)
    - AWSS3 (~> 2.26.5)
  - AppSyncRealTimeClient (1.6.0):
    - Starscream (~> 3.1.1)
  - AWSAppSync (3.4.1):
    - AppSyncRealTimeClient (~> 1.4)
    - AWSCore (~> 2.26.0)
    - ReachabilitySwift (= 5.0.0)
    - SQLite.swift (~> 0.12.2)
  - AWSAuthCore (2.26.6):
    - AWSCore (= 2.26.6)
  - AWSCognitoIdentityProvider (2.26.6):
    - AWSCognitoIdentityProviderASF (= 2.26.6)
    - AWSCore (= 2.26.6)
  - AWSCognitoIdentityProviderASF (2.26.6):
    - AWSCore (= 2.26.6)
  - AWSCore (2.26.6)
  - AWSMobileClient (2.26.6):
    - AWSAuthCore (= 2.26.6)
    - AWSCognitoIdentityProvider (= 2.26.6)
    - AWSCognitoIdentityProviderASF (= 2.26.6)
    - AWSCore (= 2.26.6)
  - AWSPinpoint (2.26.6):
    - AWSCore (= 2.26.6)
  - AWSPluginsCore (1.17.0):
    - Amplify (= 1.17.0)
    - AWSCore (~> 2.26.5)
  - AWSS3 (2.26.6):
    - AWSCore (= 2.26.6)
  - AWSSNS (2.26.6):
    - AWSCore (= 2.26.6)
```

**Device Information (please complete the following information):**
 - Device: Any device
 - iOS Version: iOS 14 - 15
 - Specific to simulators:

**Additional context**
Add any other context about the problem here like your specific use case.

**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
AWSDDLog.sharedInstance.logLevel = .debug
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Comment by lawmicha** [comment]
A fix has been released in [2.26.7](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.26.7), will close this for now but let us know if you are still seeing issues.
