### ISSUE TITLE
Getting error 'AWSApiGatewayBridge.h' file not found

### ISSUE THREAD

**Issue by rajput09** [aws-amplify/aws-sdk-ios#3970]
**I am using   AWSAPIGateway SDK to call our server api's**
I am following these steps :-
**The generated SDK depends on the AWS Mobile SDK for iOS. There are ways to import it into your project:

* CocoaPods

You should use one of these two ways to import the AWS Mobile SDK but not both. Importing both ways loads two copies of the SDK into the project and causes compiler errors.

## With CocoaPods

1. The AWS Mobile SDK for iOS is available through [CocoaPods](https://cocoapods.org/). If you have not installed CocoaPods, install it by running the command:

        $ gem install cocoapods
        $ pod setup

    Depending on your system settings, you may have to use `sudo` for installing `cocoapods` as follows:

        $ sudo gem install cocoapods
        $ pod setup

1. Move the generated `Podfile` to the same directory as your Xcode project file. Additionally starting from CocoaPods 1.0.0 you need to explicitly mention the target. To do this update the `<YourXCodeTarget>` section in `Podfile`.  If your project already has `Podfile`, you can add the following line to the existing `Podfile`.

        pod 'AWSAPIGateway', '~> 2.6.33'

1. Then run the following command:

        $ pod install

1. Open up `*.xcworkspace` with Xcode.
1. Add all files (`*.swift` and `*.h` files) under the `generated-src` directory to your Xcode project. The generated-src already includes the Bridging header file (Bridging_Header.h), include that file in your build settings for xcode target. If you already have a bridging header then add

        #import "AWSApiGatewayBridge.h"

to your list of imports in the bridging header.

# Use the SDK in your project

1. Grab the `defaultClient` from your code

        let client = CLASSICRUMMYTESTClassicRummyRestAPIClient.defaultClient()

1. You can now call your method using the client SDK

        
        client.janusAuthenticationChangePasswordPost(body authorization(authorization).continueWithBlock{ (task: AWSTask?) -> AnyObject? in
            if let error = task.error {
                print("Error occurred: \(error)")
                return nil
            }

            if let result = task.result {
                // Do something with result
            }

            return nil
        }
        

#Using AWS IAM for authorization
To use AWS IAM to authorize API calls you can set an `AWSCognitoCredentialsProvider` object as the default provider for the SDK.

        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: CognitoRegionType, identityPoolId: CognitoIdentityPoolId)

        let configuration = AWSServiceConfiguration(region: DefaultServiceRegionType, credentialsProvider: credentialsProvider)

        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration

#Using API Keys
You can set the `apiKey` property of the generated SDK to send API Keys in your requests.

        client.APIKey = @"your api key";
**

**i am utilizing AWSApiGateway service**

After done all these things i am getting error 'AWSApiGatewayBridge.h' file not found 
attached you a some SS as well please check
<img width="1437" alt="Screenshot 2022-01-10 at 6 18 42 PM" src="https://user-images.githubusercontent.com/87544220/148772403-2cb5a31e-0c9c-4666-bdd2-ce44cf573eb4.png">
<img width="1434" alt="Screenshot 2022-01-10 at 6 10 09 PM" src="https://user-images.githubusercontent.com/87544220/148772447-97e78280-cbb6-41a6-8bd7-0e892154df72.png">
THis is my AWSAPI gate way client file

**Comment by atierian** [comment]
Thanks for opening this issue @rajput09.
It appears you may be following an outdated version of the SDK README.
Following the instructions in the [README](https://github.com/aws-amplify/aws-sdk-ios/blob/main/README.md#cocoapods) or the [CocoaPods setup section of the SDK Setup Options ](https://docs.amplify.aws/sdk/configuration/setup-options/q/platform/ios/#cocoapods-setup) documentation should resolve this issue.
Please let us know if this resolves your issue. Thanks.
