### ISSUE TITLE
AWSMobileClient.default().getTokens, completion not called

### ISSUE THREAD

**Issue by piroznoe** [aws-amplify/aws-sdk-ios#3986]
**Describe the bug**
`AWSMobileClient.default().getTokens(_ completionHandler: @escaping (Tokens?, Error?) -> Void)`
Callback not called when refresh token is expired

**To Reproduce**
1. sign in with `signIn(username: String, password: String)`
2. wait until refresh token expires
3. call `getTokens(_ completionHandler: @escaping (Tokens?, Error?) -> Void)`
4. completionHandler never called 

**Observed Behavior**
Completion not called 

**Expected Behavior**
Completion called

**Areas of the SDK**
AWSMobileClient

**Environment:**
 - SDK Version: [2.12.0, 2.27.0]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [4.5-5.5]
 - Xcode Version: [11.4-13]

**Additional context**
`- (AWSTask<AWSCognitoIdentityUserSession*>*) customAuthInternal: (id<AWSCognitoIdentityCustomAuthentication>) authenticationDelegate {`

`continueWithSuccessBlock` not called in this function

**Comment by royjit** [comment]
When the refresh token expires, you have to call `signIn(username: String, password: String)` to get new refresh token. So the flow will be like this:
1. sign in with signIn(username: String, password: String)
2. wait until refresh token expires
3. call getTokens(_ completionHandler: @escaping (Tokens?, Error?) -> Void)
4. sign in with signIn(username: String, password: String) 
5. completionHandler for `getTokens` should be called. 

The `getTokens` api will wait for the signIn to complete to return to the callback.

**Comment by piroznoe** [comment]
@royjit Thanks for your response, how I can detect what refresh token expired? I expect to get some error from `getTokens`

>  If there is no refresh token and the user is signed in, a notification is dispatched to indicate requirement of user to re-signin

The documentation doesn't contain anything about the expiration

**Comment by royjit** [comment]
You can listen to different state changes by 👍 
```
AWSMobileClient.default().addUserStateListener(self) { (userState, info) in
            switch (userState) {
            case .guest:
                print("user is in guest mode.")
            case .signedOut:
                print("user signed out")
            case .signedIn:
                print("user is signed in.")
            case .signedOutUserPoolsTokenInvalid:
                print("need to login again.")
            case .signedOutFederatedTokensInvalid:
                print("user logged in via federation, but currently needs new tokens")
            default:
                print("unsupported")
            }
        }
```

**Comment by piroznoe** [comment]
Thanks this is exactly what I was looking for

**Comment by BobDG** [comment]
I don't believe the issue is fully solved. The UserStateListener is unreliable in my case, sometimes I get a callback there, sometimes twice, and sometimes not at all.
Besides, it's crucial that completion handlers are always called, even in error scenarios. If an error occurs during the operation, the completion handler should be called with appropriate error information to allow the calling code to handle it gracefully.

So if the user needs to sign in again, that's also something that can simply be given in the completion handler.
