### ISSUE TITLE
Is AWSS3TransferUtility compatible with CloudFront?

### ISSUE THREAD

**Issue by lucianoiam** [aws-amplify/aws-sdk-ios#4006]
What are the alternatives if not possible?

**Comment by brennanMKE** [comment]
You can look at [AWSS3TransferUtilityConfiguration](https://github.com/aws-amplify/aws-sdk-ios/blob/1717726d13d603328462e26244c3aff954648beb/AWSS3/AWSS3TransferUtility.h#L687-L699) to see it has a property for `bucket` but not `endpoint`. You can see [where these properties are set](https://github.com/aws-amplify/aws-sdk-ios/blob/7e761ee96330e32c9b76d1cdb67d48eb757e76b2/AWSS3/AWSS3TransferUtility.m#L111-L114).

The section in the JSON file also only has a value for `Bucket` and `Region`. 

```json
"S3TransferUtility": {
    "Default": {
        "Bucket": "BUCKET",
        "Region": "us-east-1"
    }
}
```

You could create an issue to request support for a CloudFront feature and others could show their interest in this feature on that issue.
