### ISSUE TITLE
Call a lambda function directly from ios /w AWS crendential

### ISSUE THREAD

**Issue by joybro** [aws-amplify/aws-sdk-ios#4037]
**State your question**
According to my understanding, users can assume an authenticated role from Cognito identity pool, and use the role credential to access AWS components. So I think it would be possible to call a lambda function directly from client using aws sdk's lambda interface ([like this for web](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-lambda/index.html#asyncawait)).

But I found aws-amplify doesn't have such an interface to call Lambda. Can anyone confirm if this approach(calling lambda directly from ios) doesn't make sense at all, or it is possible for Javascript, but not for iOS simply because aws-amplify doesn't support it yet?

**Which AWS Services are you utilizing?**
Cognito(UserPool and IdentityPool) and Lambda

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [2.27.3]
 - Dependency Manager: [Swift Dependency Manager]
 - Swift Version : [5.0]

**Device Information (please complete the following information):**
 - Device: [iPhone13, Simulator]
 - iOS Version: [iOS 15]

**Comment by royjit** [comment]
Amplify iOS makes it easy for you by handling all the underlying auth and connection. Follow this link to setup AWS Lambda and APIGateway - https://docs.amplify.aws/lib/restapi/getting-started/q/platform/ios/ . 

On the other hand if you would like to do this directly with AWS Lambda, use the underlying aws-sdk-ios library - https://github.com/aws-amplify/aws-sdk-ios/tree/main/AWSLambda

**Comment by joybro** [comment]
@royjit Thank you for the links! aws-sdk-ios seems to be what I was looking for.
