### ISSUE TITLE
AWSS3TransferUtility upload file with url from Files app fail

### ISSUE THREAD

**Issue by nastasiupta** [aws-amplify/aws-sdk-ios#4044]
**Describe the bug**
We are using AWSS3TransferUtility to upload images (using uploadData method)  and videos (using uploadFile method) that the user is selecting from the library (Photos app).
Right now we want to enable a future to upload image, videos, audio files from the Files app, using UIDocumentBrowserViewController, which return an array of URLs.

This is an example of a video URL from Photos selection and the upload works without any issue:
```
file:///private/var/mobile/Containers/Data/Application/DBF1E585-2208-4D6E-8001-ABB58F4AC88C/tmp/DB1C6850-FA71-4B06-8D22-C747CE2B4CC2.mp4
```

Those 2 URLs are provided by the UIDocumentBrowserViewControllerDelegate, which represents 2 files (1 image and 1 video) from the Files app:
```
file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/@video/Video%20Test.mp4
file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/IMG_2546.JPG
```

When I try to use the method AWSS3TransferUtility.uploadFile (as I do for a video) it fails instantly.
```
<AWSTask: 0x13b8ccbe0; completed = YES; cancelled = NO; faulted = YES; result = (null)>
Optional(Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=4 "(null)")
```

As I mentioned, everything works like a charm if the URL is from the Photos app, the issue happens for any kind of file that is provided by the Files app using UIDocumentBrowserViewController.

**To Reproduce**
1. Make sure you have the following SDKs versions: 
  pod 'AWSElasticLoadBalancing', '2.27.3'
  pod 'AWSS3', '2.27.3'
  pod 'AWSCore', '2.27.3'
2.  Use UIDocumentBrowserViewController to select at least 1 file from the Files app
3. Use AWSS3TransferUtility.uploadFile(url: URL method to upload that file to AWS
4. On the continue block you will receive the following error:
<AWSTask: 0x13b8ccbe0; completed = YES; cancelled = NO; faulted = YES; result = (null)>
Optional(Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=4 "(null)")**Observed Behavior**

**Expected Behavior**
It should work without an issue, as it works with an URL from a video provided by the Photos (device library).

**Stack Trace**
-

**Code Snippet**
```
let expression = AWSS3TransferUtilityUploadExpression()
expression.progressBlock = { task, progress in
    let overallProgress: Int = Int(progress.fractionCompleted * 100)
    DispatchQueue.main.async {
        completion?(nil, UploadMediaWorkerResponse.progress(data.newMedia, overallProgress))
     }
}

let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: awsTransferUtilityKey)
let uid: String = currentUser.uid

let fileExtension = fileURL.pathExtension
transferUtility?.uploadFile(fileURL, bucket: awsBucket, key: "\(uid)/\(data.fileName).\(fileExtension)", contentType: url.mimeType, expression: expression, completionHandler: { (task, error) in
    self.uploadTask = nil
    let uploadedMedia = UploadedMedia(ext: fileExtension, filename: data.fileName, url: task.request?.url)
    DispatchQueue.main.async {
        completion?(nil, .finished(data.newMedia, uploadedMedia))
    }
}).continueWith(block: { (task) in
    self.uploadTask = task.result
    return nil
})
```

**Unique Configuration**
-

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
  pod 'AWSElasticLoadBalancing', '2.27.3'
  pod 'AWSS3', '2.27.3'
  pod 'AWSCore', '2.27.3'
(at this moment this is the last version)

**Screenshots**
-

**Environment(please complete the following information):**
 - SDK Version: 2.27.3
 - Dependency Manager: -
 - Swift Version : 5
 - Xcode Version: 13.3 (13E113)

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: 15.3.1
 - Specific to simulators: NO

**Additional context**
-

**Relevant Console Output**
Even if I set the AWSDDLog, I don't get any additional information about the issue.
```

**Comment by nastasiupta** [comment]
@brennanMKE  any update on this?

**Comment by nastasiupta** [comment]
@atierian Any ETA on this?

**Comment by atierian** [comment]
Hey @nastasiupta. This is most likely a permissions issue due to the URLs provided living in the iCloud Drive as confirmed by the path component in the URLs `com~apple~CloudDocs`. From the [documentation](https://developer.apple.com/documentation/uikit/uidocumentbrowserviewcontroller) on `UIDocumentBrowserViewController`:

> Don't assume that the files you access are local. Users can store files in iCloud Drive, or in any cloud storage that provides a current File Provider extension.

Those URLs provided are security-scoped URLs, and you'll need to use [`startAccessingSecurityScopedResource()`](https://developer.apple.com/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso) in combination with [`stopAccessingSecurityScopedResource()`](https://developer.apple.com/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou) to access the data within those files. I don't believe we have any formal guidance on handling uploads of these types of resources, but perhaps the simplest way of accomplishing this is temporarily persisting the in the app's sandbox and using that `URL`.

Here's a simplified example:
```swift
struct ScopedResourceFile {
    let name: String
    let data: Data
}

func documentBrowser(
    _ controller: UIDocumentBrowserViewController,
    didPickDocumentsAt documentURLs: [URL]
) {
    
    let fileContents = documentURLs.compactMap { url -> ScopedResourceFile? in
        let startAccess = url.startAccessingSecurityScopedResource()
        guard startAccess else {
            print("Issue accessing security scoped resource at :\(url)")
            return nil
        }
        defer { url.stopAccessingSecurityScopedResource() }
        do {
            let data = try Data(contentsOf: url)
            let fileName = url.lastPathComponent
            return ScopedResourceFile(name: fileName, data: data)
        } catch {
            print("Couldn't create Data from contents of file at url: \(url)")
            return nil
        }
    }
    
    let localFileURLS = locallyCacheFiles(fileContents) // make this yourself, creating new 
    // files in your app's local sandbox. Here's an example signature 
    // `func locallyCacheFiles(_ contents: [ScopedResourceFile]) -> [URL]`
    
    // Now you have local URLs for the files you'd like to upload.
}
```

**Comment by oleg-moseyko** [comment]
Hi @nastasiupta 

I have the same issue. 
I use uploadUsingMultiPart for PHAsset which was saved(for dir .applicationSupportDirectory) to a file with space or russian letter ("путин хуйло.png").

It does not depend on startAccessingSecurityScopedResource/stopAccessingSecurityScopedResource.
````
 let dir = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).last!
````
````
    transferUtility.uploadUsingMultiPart(
        fileURL: fileURL,   !!!! <<<<<<
        bucket: bucket,
        key: key,
        contentType: meta.mimeType,
        expression: expression,
        completionHandler: completionHandler(finishBlock: finishBlock)
    ).continueWith(block: continueWithBlock(uuid: uuid))
````

**Comment by nastasiupta** [comment]
@atierian It worked. I get data from that url and use method uploadData instead.
