### ISSUE TITLE
AWS image upload of less than 1 MB taking over 30 seconds

### ISSUE THREAD

**Issue by harikrishnabista7** [aws-amplify/aws-sdk-ios#4054]
**The main issue I am facing is that, even after the progress reaches 1.0 it takes over 30 seconds to get the completion callback. Because of this I am having trouble to show the upload progress in UI.**

**Can somebody check my implementation. Or Is there any settings I have to enable for this.**

    private func startUploadTransfer(data: Data, key: String) {
        let progressBlock: AWSS3TransferUtilityProgressBlock = { [weak self] (_, progress) in
            guard let self = self else { return }
            DispatchQueue.main.async {
                self.invokeProgress(progress: progress.fractionComplete)
            }
        }
        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = progressBlock
        
        let key = file.key
        status = .transfering
        task = AWSS3TransferUtility.default().uploadData(data, bucket: AppConstants.bucketName, key: key, contentType: file.contentType.rawValue, expression: expression) { [weak self] _, error in
            guard let self = self else { return }
            if let error = error {
                DispatchQueue.main.async {
                    self.error = error
                    self.status = .error
                }
            } else {
                guard let cdnURL = URL(string: AppConstants.cdnPath) else { assertionFailure(); return }
                let filePath = cdnURL.appendingPathComponent(key)
               
                DispatchQueue.main.async {
                    self.result = filePath
                    self.status = .completed
                }
            }
        }
    }

**Comment by harsh62** [comment]
@harikrishnabista7 Could you please share the version of the sdk you are using? Was the SDK updated recently? Was this working before as expected?

**Comment by harikrishnabista7** [comment]
> @harikrishnabista7 Could you please share the version of the sdk you are using? Was the SDK updated recently? Was this working before as expected?

Current version of the sdk is 2.27.3. It was updated recently but I faced this issue in earlier version as well but it didn't matter much as I didn't have the requirement to show the progress in the UI.
But now I need to show progress.

**Comment by harikrishnabista7** [comment]
> > @harikrishnabista7 Could you please share the version of the sdk you are using? Was the SDK updated recently? Was this working before as expected?
> 
> Current version of the sdk is 2.27.3. It was updated recently but I faced this issue in earlier version as well but it didn't matter much as I didn't have the requirement to show the progress in the UI. But now I need to show progress.

I found out that in debugging the latency is considerably higher

**Comment by brennanMKE** [comment]
I've prepared a sample project with 2 versions to observe uploads. The first uses the Amplify library and the other uses Transfer Utility directly from the SDK. I am using the Network Link Conditioner from Apple the simulate network behavior for Edge, 3G and LTE networks. There are delays as expected but I am not able to observe any reason why the apps would be blocking. Please try these apps for yourself. You will need to run `setup.sh` in the root to clone the repos which are needed and also provide your own configuration to AWS & Amplify to access an S3 bucket.

* [Amplify.zip](https://github.com/aws-amplify/aws-sdk-ios/files/8499086/Amplify.zip)
* [SDK.zip](https://github.com/aws-amplify/aws-sdk-ios/files/8499087/SDK.zip)

Let us know if you observe this behavior with these sample projects.
