### ISSUE TITLE
Support for Mac Catalyst

### ISSUE THREAD

**Issue by choule99** [aws-amplify/aws-sdk-ios#4065]
Pretty much self explanatory, we want to use AWS Chimes, on a multi-platform iOS Application using Mac Catalyst, but right now, we just can't do anything, we're blocked.

**Comment by smhk** [comment]
Any news on this guys ?

**Comment by royjit** [comment]
Chime SDK is available in AWS Swift SDK - https://github.com/awslabs/aws-sdk-swift/tree/release/0.2.4/release/AWSChime. Can you check if this SDK unblocks you?

**Comment by atierian** [comment]
Can you let us know if using the AWS SDK for Swift (linked above) unblocks you? 
If not, what exactly is the issue you're experiencing when trying to build for catalyst? With a basic sample application, it appears to be working fine.

**Comment by smhk** [comment]
hi @atierian  , thanks for the response, but I last looked at this issue 8 (!) months ago. I'm afraid it's completely out of my loop now!  Maybe the others can help, best JP
