### ISSUE TITLE
Support M1 mac (solved)

### ISSUE THREAD

**Issue by mzying2013** [aws-amplify/aws-sdk-ios#4088]
If I run the app on a Mac (Designed for iPhone), I get the error errSecParam (-50). 

At `AWSIoTManager.m Line:363`
Replace with:
```
if (@available(iOS 14, )) {
  publicKeyRef = SecTrustCopyKey(trust);
} else {
  publicKeyRef = SecTrustCopyPublicKey(trust);
}
```

Please see my blog post for details: https://blog.mzying.com/index.php/archives/322

**Comment by harsh62** [comment]
Thanks for providing the workaround. Closing this issue.
