### ISSUE TITLE
s3TransferUtility - How can to find task by transferID in order to cancel it?

### ISSUE THREAD

**Issue by oleg-moseyko** [aws-amplify/aws-sdk-ios#4098]
**State your question**
How can to find task by transferID in order to cancel it?

**Which AWS Services are you utilizing?**
AWSS3
s3TransferUtility - uploadUsingMultiPart

**Provide code snippets (if applicable)**
I have this way but not sure it is good 
`````
func findTask(transferId: String) -> AWSS3TransferUtilityMultiPartUploadTask? {
    for uploadTask in self.s3TransferUtility.getMultiPartUploadTasks().result! {
        if let task = uploadTask as? AWSS3TransferUtilityMultiPartUploadTask {
            if task.transferID == transferId {
                return task
            }
        }
    }
    return nil
}
`````

**Comment by thisisabhash** [comment]
Hello,
This code snippet seems correct. Could you let us know your use case you're trying to solve?

**Comment by oleg-moseyko** [comment]
Hi @thisisabhash 
i have a list of transferIds in realm db and if user clicks "cancel upload" on photo i need to cancel this MultiPart UploadTask. so do:
1. find task by transferId
2. cancel this task

**Comment by harsh62** [comment]
@oleg-moseyko I believe for your use case, that is the correct way to do it. Incase you are facing any issues with it, kindly let use know.
