### ISSUE TITLE
Setting Up the IAM Policy for Asynchronous Synthesis example 

### ISSUE THREAD

**Issue by guris12** [aws-amplify/aws-sdk-ios#4113]
**State your question**
How can I setup  IAM Policy for Asynchronous Synthesis ? 

**Which AWS Services are you utilizing?**
AWSPolly, S3 

Could you please help  ?

**Comment by thisisabhash** [comment]
Hello, 
I found steps to set up IAM Policy for Asynchronous Synthesis here : https://docs.aws.amazon.com/polly/latest/dg/asynchronous-iam.html
Please let us know if you have further questions.
