### ISSUE TITLE
AWS IOT connection error 403 during register MQTT

### ISSUE THREAD

**Issue by kuldipsinh09** [aws-amplify/aws-sdk-ios#4116]
I faced this issue during connect AWS IoT MQTT, 
IoT connection is always in “Connecting” or “Connection Error” state, the connection status is never seen as “Connected”.

On Connect MQTT it will return this error in below  **method of AWSSRWebSocketDelegate**
 (void)webSocket:(AWSSRWebSocket *)webSocket didFailWithError:(NSError *)error {*

**Error description**
Error Domain=AWSSRWebSocketErrorDomain Code=2132 "received bad response code from server 403" UserInfo={NSLocalizedDescription=received bad response code from server 403, HTTPResponseStatusCode=403}

For connect with IOT connection i choose connectUsingWebSocketWithClientId option.

This error has not come in every iPhone device except iphone12(iOS 15.4.1) and iphone11(iOS 15.4.1).
I have some other iPhone devices which have iOS 15.4.1 or below version, But this issue does not come in that devices.

I tried with updated pod  version AWSIoT 2.27.7

I have checked AWS policies and other configurations, please let me know if any other configuration is needed.

Please note this issue observes some specific devices which I mentioned above, In other devices it is working fine.

Please share your thoughts on how we can resolve this issue.

**Comment by ameter** [comment]
Are you seeing this issue on physical devices or simulators?

**Comment by kuldipsinh09** [comment]
Yes, I faced this issue on physical devices which are iphone12(iOS 15.4.1) and iphone11(iOS 15.4.1). In simulator it is working properly.

**Comment by harsh62** [comment]
@kuldipsinh09 Can you try resetting your devices having the issue and try to validate if the issue still persists?

**Comment by kuldipsinh09** [comment]
@harsh62  Thank you for your suggestion. I have reset my device and this issue is resolved as of now. But, my concern is if this issue observe after release app on App Store, then how can we ask user for reset his device. Can you please give me root cause or more enlightened way for resolve this issue.

**Comment by harsh62** [comment]
@kuldipsinh09 From what I understand is that something didn't work as expected when using the keychain in AWS IOT. If this issue comes up again, it would be nice to debug on the phone and capture the logs to deep dive into the investigation of the issue. For now I will resolve the issue, and you can reopen the issue if it starts happening again.
