### ISSUE TITLE
ITMS-90338: Non-public API usage Frameworks/AmplifyPlugins.framework/AmplifyPlugins: _SFAuthenticationErrorDomain

### ISSUE THREAD

**Issue by Lebron1992** [aws-amplify/aws-sdk-ios#4176]
**Describe the bug**
We receive the email from Apple for today's build:

ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/AmplifyPlugins.framework/AmplifyPlugins: _SFAuthenticationErrorDomain. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

It worked two days ago.

Any solution to figure out the issue? Thanks!

**Comment by thisisabhash** [comment]
Hello, This issue was resolved by Apple few days ago. Please check https://github.com/aws-amplify/amplify-ios/issues/1870 for a similar discussion on this topic.
