### ISSUE TITLE
 S3TransferUtility. iPhone can has not enough size of memory to load full video data 

### ISSUE THREAD

**Issue by oleg-moseyko** [aws-amplify/aws-sdk-ios#4178]
I want to upload a big video using S3TransferUtility. It provides uploadFileUsingMultipart and uploadDataUsingMultipart methods where I need to provide the file URL.
Photos URL can be inaccessible and I need to extract data to a temporary directory.
1. It may need too much time before the actual upload starts.
2. iPhone can has not enough size of memory to load full data.

My questions are: 
1. Is it possible to upload the big video(for example ~10, 100, ... GB) using multipart (S3TransferUtility) if iPhone has insufficient memory to load full data. Maybe some way with InputStream/OutputStream.
2. Best practice to upload a big video?

**Which AWS Services are you utilizing?**
S3TransferUtility

**Environment(please complete the following information):**
 - SDK Version:  2.6.29

**Device Information (please complete the following information):**
 - Device: iPhone

**Comment by oleg-moseyko** [comment]
ping

**Comment by royjit** [comment]
Current implementation of S3TransferUtility require extra storage to keep temporary files while uploading. It creates a copy of the file during upload so an equivalent amount memory might be required to upload.

**Comment by harsh62** [comment]
I am marking this as a feature-request for us to go through and optimize.
