### ISSUE TITLE
iot问题

### ISSUE THREAD

**Issue by Yaoqihao** [aws-amplify/aws-sdk-ios#4180]
我在iphone上安装测试demo:IoTSampleSwift,并配置了awsconfiguration.json文件与Constants.swift文件 但还是提示我无法创建密钥和/或证书，请检查Constants.swift中的值，请问我该如何解决这个问题。

Translation: I installed the test demo: IoTSampleSwift on the iphone, and configured the awsconfiguration.json file with the Constants.swift file but it still prompts me that the key and/or certificate cannot be created, please check the value in Constants.swift, how can I solve this question.

**Comment by phantumcode** [comment]
Hi @Yaoqihao Did you follow all the steps in the README? https://github.com/awslabs/aws-sdk-ios-samples/blob/main/IoT-Sample/Swift/README.md

Can you provide the error log or error message?  What do you have defined in the Constants.swift?

**Comment by Yaoqihao** [comment]
你好，这个问题我这边已经解决了，现在有个问题是我将如何获取设备是否离线或在线的状态？

**Comment by phantumcode** [comment]
You can subscribe to the lifecyle events to monitor device client device states.  See IoT documentation: https://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html
