### ISSUE TITLE
Unable to auto Refresh access token 

### ISSUE THREAD

**Issue by JyotsnaPiOSDEV** [aws-amplify/aws-sdk-ios#4181]
Describe the bug
We have reviewed the doc. Mobile sdk for ios have auto refresh supported. But I am facing issue on auto refresh
SDK Version. AWSMobileClient 2.26.6'
1. Sign in mobile with AWSMobileClient
2. Get token from fetchAccessToken() and passing to api header its working 
3. After 8 min we have set expiration time expected behaviour access token should refresh automatically 
4. Receiving error on api  call Token expired

Way1. Before Api call I have done manually

```objc
//Get new token manually in AWSAuthManager. class
func fetchAccessToken(_ completion: @escaping(String)->Void) {
         let user = userPool?.currentUser()
                let task = user?.getSession()
                if let session = task?.result {
                    guard let accessToken = session.accessToken?.tokenString else {
                            completion(self.accessToken!)
                               return
                            }
                        self.accessToken = accessToken
                         completion(accessToken)
                }
            }
```
// Rest api call with new token

```objc
AWSAuthManager.shared.fetchAccessToken { accessToken in
            print("call back session \(AWSAuthManager.shared.accessToken!)")
            var headers = [
                "token": accessToken,  "thingName":thingName
           ]
            REQUEST_MANAGER.withPOSTAWS(endPointUrl: API_URLs.updateshadow, param: stateDict, headers: headers) { (response) in
                if response != nil {
                  print("response
                }
            }
if token expired I am getting delay in this manual process 
Way2 -  calling get token on 401 and retrying request and its working .This is again manual way

if httpResponse.statusCode == 401 {
          self.retryAndRefreshToken(url: endPointUrl, param: param, headers: headers ?? ["token" :""accesstoken]) { isComplete in
            print(“Retry result)
          }
func retryAndRefreshToken(url : String,param: [String:Any],headers:[String:String],completionHandler: @escaping (Bool?) -> Void ){
    var  userPool:AWSCognitoIdentityUserPool?
    let user = userPool?.currentUser()
    AWSMobileClient.default().getTokens { (tokens, error) in
      if let error = error {
        print(error.localizedDescription)
      }
      let UpdateaccessToken = tokens?.accessToken?.tokenString
      var token: [String : String]?
      token = headers
      token?["token"] = UpdateaccessToken
      //Retry api call with new token
      self.withPOSTAWS(endPointUrl: url, param: param, headers: token) { (response) in
        if response != nil {
          completionHandler(true)
        }
      }
    }
  }
```
I am receiving on call fetchAccessToken -
Request body:
{"UserContextData":{"EncodedData":""},"AuthFlow":"REFRESH_TOKEN_AUTH","ClientId":""}
Is any way to get new access token from auto refresh way ?

**Comment by royjit** [comment]
Can you try using `AWSMobileClient.default().getTokens` inside your `fetchAccessToken` method instead of calling `getSession`?

**Comment by JyotsnaPiOSDEV** [comment]
> Can you try using `AWSMobileClient.default().getTokens` inside your `fetchAccessToken` method instead of calling `getSession`?

Yes I have tried that too still not working

**Comment by JyotsnaPiOSDEV** [comment]
> ```objc
> func retryAndRefreshToken(url : String,param: [String:Any],headers:[String:String],completionHandler: @escaping (Bool?) -> Void ){
>     var  userPool:AWSCognitoIdentityUserPool?
>     let user = userPool?.currentUser()
>     AWSMobileClient.default().getTokens { (tokens, error) in
>       if let error = error {
>         print(error.localizedDescription)
>       }
>       let UpdateaccessToken = tokens?.accessToken?.tokenString
>       var token: [String : String]?
>       token = headers
>       token?["token"] = UpdateaccessToken
>       //Retry api call with new token
>       self.withPOSTAWS(endPointUrl: url, param: param, headers: token) { (response) in
>         if response != nil {
>           completionHandler(true)
>         }
>       }
>     }
>   }
> ```

**Comment by royjit** [comment]
The getTokens call to AWSMobileClient should refresh the token automatically if the refresh token has not expired.  To debug further can you try enabling verbose logs and provide us the log information, redact sensitive information before pasting the logs here. You can enable verbose logging by:

```
AWSDDLog.sharedInstance.add(AWSDDTTYLogger())
AWSDDLog.sharedInstance.logLevel = .verbose
```

Also can you try using the latest SDK 2.27.10 is the latest version.

**Comment by JyotsnaPiOSDEV** [comment]
> The getTokens call to AWSMobileClient should refresh the token automatically if the refresh token has not expired. To debug further can you try enabling verbose logs and provide us the log information, redact sensitive information before pasting the logs here. You can enable verbose logging by:
> 
> ```
> AWSDDLog.sharedInstance.add(AWSDDTTYLogger())
> AWSDDLog.sharedInstance.logLevel = .verbose
> ```
> 
> Also can you try using the latest SDK (v 2.27.10) and see if the issue is reproducible?

I find a way around and its  working.
AWSMobileClient.default().initialize { state , er in
        AWSMobileClient.default().getTokens { (tokens, error) in
            if let error = error {
                print(error.localizedDescription)
            }
            let UpdateaccessToken = tokens?.accessToken?.tokenString
            completion(UpdateaccessToken)
        }
        }
Is this right way to do refresh token , initialize AWSmobile client then getAccesstoken call.Please
give me your valuable feedback.Thanks a lot.

**Comment by JyotsnaPiOSDEV** [comment]
using the latest SDK (v 2.27.10) I am not getting error 401
solved
Thanks
<img width="609" alt="Screenshot 2565-06-21 at 7 30 36 PM" src="https://user-images.githubusercontent.com/91535382/174829738-c15843e3-a526-4752-bde0-f7f0e62b2431.png">
d

**Comment by royjit** [comment]
Yes you are right, you should initialize AWSMobileClient before using it.

**Comment by JyotsnaPiOSDEV** [comment]
OK thanks Its solved
