### ISSUE TITLE
Cannot target My Mac (Designed for iPad) on M1

### ISSUE THREAD

**Issue by hstriepe** [aws-amplify/aws-sdk-ios#4190]
As part of the debugging process, we like to use the "target My Mac (Designed for iPad)" on M1.

Various AWS modules fail for unsupported option '-fsanitize=thread' for target arm64-apple-ios9.
AWSCognitoIdenitityProvider, AWSMobileClientXCF-Target, AWSCore-Target 1

In Xcode
1. In scheme selector set to arget My Mac (Designed for iPad)
2. Hit Build or Go key

**Observed Behavior**
Errors as indicated above.

**Expected Behavior**
Builds as on iPhone and runs.

This is only meaningful on Apple Silicon running Monterey.

Xcode 13.4.2, target iOS 15, Mac Studio running macOS 12.4

**Comment by brennanMKE** [comment]
Please see the feature request in Amplify iOS for macOS support.

https://github.com/aws-amplify/amplify-ios/issues/1124

We currently do not support macOS with the AWS SDK. Our new Swift SDK which is currently in Dev Preview supports both iOS and macOS.

**Comment by abegehr** [comment]
@brennanMKE, is there any new on the "new Swift SDK"?

**Comment by harsh62** [comment]
Closing the ticket in favour of https://github.com/aws-amplify/amplify-ios/issues/1124 .. Please subscribe to it to get more updates on macOS support.
