### ISSUE TITLE
crash when AWSMobileClient .internalCredentialsProvider?.identityProvider

### ISSUE THREAD

**Issue by kostiag** [aws-amplify/aws-sdk-ios#4218]
**Describe the bug**
Using my own login UI and login/out workflow, during the logout process once in a while observing a crash.
on line 
self.internalCredentialsProvider?.identityProvider.identityId = nil when identityProvider is NIL obviously

where mobileClient is an instance of AWSMobileClient of course
self.mobileClient?.signOut() CRASHES - multiple ways of getting into this situation, have seen this throughout various versions

po self.mobileClient?.currentUserState
▿ Optional

some : AWSMobileClient.UserState.signedIn
Screen Shot 2022-06-30 at 9 55 50 AM

**Stack Trace**
Please provide a stack trace if applicable e.g. a crash is occurring.

**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient

**Screenshots**

**Environment(please complete the following information):**

AWSAuthCore (2.27.10):
AWSCore (= 2.27.10)
AWSCognitoIdentityProvider (2.27.10):
AWSCognitoIdentityProviderASF (= 2.27.10)
AWSCore (= 2.27.10)
AWSCognitoIdentityProviderASF (2.27.10):
AWSCore (= 2.27.10)
AWSCore (2.27.10)
AWSMobileClient (2.27.10):
AWSAuthCore (= 2.27.10)
AWSCognitoIdentityProvider (= 2.27.10)
AWSCognitoIdentityProviderASF (= 2.27.10)
AWSCore (= 2.27.10)

**Device Information (please complete the following information):**
iPad 15.5 but irrelevant have seen it multiple times on various devices and versions

**Additional context**
Add any other context about the problem here like your specific use case.

**Comment by harsh62** [comment]
@kostiag .. Thanks for taking the time to raise the issue. 

There were some recent fixes around `internalCredentialsProvider`, could you please try out with the latest version i.e. [`2.27.12`](https://github.com/aws-amplify/aws-sdk-ios/releases).

If the issue still persists, can you please provide a stack trace?
