### ISSUE TITLE
Cognito update attribute return success but codeDeliveryDetailsList is nil

### ISSUE THREAD

**Issue by hrvoje0099** [aws-amplify/aws-sdk-ios#4255]
**State your question**
I’m trying to update email atrribute, but I dont get verification code on email. Response is success, but `codeDeliveryDetailsList` is `nil`. Why? What that mean?

This is my code:
```
let emailAttribute = AWSCognitoIdentityUserAttributeType(name: "email", value: newEmail)
let attributes = [emailAttribute]
cognitoPool?.currentUser()?.update(attributes).continueWith { [weak self] response in
   guard let self = self else { return nil }

   if let error = response.error as? NSError {
      print("Cognito error - update email attribute: \(error)")
      self.processCognitoError(error)
   } else {
      DispatchQueue.main.async {
         self.didContinueToEmailVerifyScreen?()
      }

      print(response.result?.codeDeliveryDetailsList)
   }
   return nil
}
```

**Which AWS Services are you utilizing?**
Cognito

**Environment(please complete the following information):**
 - SDK Version: 2.27.13
 - Dependency Manager: SPM
 - Swift Version : 5

**Comment by harsh62** [comment]
@hrvoje0099 This feels like that you succeeded to update your email using the API. `codeDeliveryDetailsList` will only have a value if its required to confirm an attribute. In your case it feels like Cognito is not setup to verify emails. Please refer to the screenshot attached. In your case, it feels like the value is set to No Verification.  

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/6162866/184004824-7ce224b8-7e14-4c67-bde8-2284516b8695.png">

**Comment by hrvoje0099** [comment]
@harsh62 Yes as I wrote, response is success but I don’t get verification code on email and `codeDeliveryDetailsList` is `nil`. 
Verify is set to email:
![image](https://user-images.githubusercontent.com/24483776/184085056-74fcf206-08e6-4c7c-b5f1-609592f2aef9.png)

**Comment by harsh62** [comment]
@hrvoje0099 Can you please share the verbose logs of the request by adding the following changes. 

Import AWSCore module
```
import AWSCore
```
and then enable verbose loggin. 
```
AWSDDLog.sharedInstance.add(AWSDDTTYLogger())
AWSDDLog.sharedInstance.logLevel = .verbose
```

**Comment by hrvoje0099** [comment]
@harsh62 This is logs:

```
2022-08-15 16:51:42:243 GameStar[7034:314998] Request headers:
{
    "Content-Type" = "application/x-amz-json-1.1";
    Host = "cognito-idp.eu-central-1.amazonaws.com";
    "User-Agent" = "aws-sdk-iOS/2.27.13 iOS/15.5 hr-US";
    "X-Amz-Date" = 20220815T145142Z;
    "X-Amz-Target" = "AWSCognitoIdentityProviderService.UpdateUserAttributes";
}
2022-08-15 16:51:42:243 GameStar[7034:314998] Request body:
{"UserAttributes":[{"Value":"hrvoje0099@gmail.com","Name":"email"}],"AccessToken":"eyJraWQiOiJCd2FCTDBUUzk0dHl3RUJXc2s5WnM2NDVHc1wvc0crd29QVE5HdGFTV1dFQT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIyNDdjZTFjYi04NGVmLTRmNzAtOTk0Ni1lMmQ1ZGI2MDhjNzgiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9BWEdYbE1XNnciLCJjbGllbnRfaWQiOiIydmJuMW80bG8zOGtmdDBtMW5qb2E1OGs4NiIsIm9yaWdpbl9qdGkiOiJkOTMzYTI2OS0wNjdjLTRjYmEtODI0NC1iNmFhNWJjYTcxNTYiLCJldmVudF9pZCI6IjY5MWZmZmM2LWU0ZTgtNDY5My1hNDFiLTNmM2E4ODg0YmE5OSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NjA1NzUwODcsImV4cCI6MTY2MDU3ODY4NywiaWF0IjoxNjYwNTc1MDg3LCJqdGkiOiJjMDg4ZTNhZS03NTQ4LTQzOGEtODNjYy1hY2IxMjA1MTYzMDUiLCJ1c2VybmFtZSI6IjI0N2NlMWNiLTg0ZWYtNGY3MC05OTQ2LWUyZDVkYjYwOGM3OCJ9.CdM3_S4dgT1SVnSQhk1DXyMnQh2r1dI3AuYTWBWEii_iZMHgE8CNJfV_nHufB5figgbxARygi-YzENCxziTDSNm7UewIGj_Tmnfzf_egasQiSKvqIsohK7YjOVxhV8vocSrkhhjMOCcLTRN-GdIYkwiwS3pmhnYyqVJtZL0stcSvA4xFV9CJhJvX1eSigQhYxDGOahOuRYThXKbuNmqp1T9MzKp23t_6SezREAjgbIlx4v5h0j6bsHtvEMjy-1uZ6-frlDnTA3FVISTujh-1LNS773lzBZGJeBpzuv7bR7IiI_OmssSQfXLSAUpvVlLPPGuvTDx1F_gf7LwNfww3bQ"}
2022-08-15 16:51:42:424 GameStar[7034:315228] Response headers:
{
    "Content-Length" = 2;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Mon, 15 Aug 2022 14:51:42 GMT";
    "x-amzn-requestid" = "53a70e1e-9bcf-439f-b9bf-ca9042320f3c";
}
2022-08-15 16:51:42:425 GameStar[7034:315228] Response body:
{}
Success cognito - update email attribute! 
Details: nil
```

**Comment by harsh62** [comment]
@hrvoje0099 Thanks for the information. I will investigate further.. 

Please always remember to redact sensitive information like `accessTokens` and `email` in this case.

**Comment by harsh62** [comment]
@hrvoje0099 I wanted to ask if email gets updated on Cognito even though you never got a code?

**Comment by hrvoje0099** [comment]
@harsh62 I noticed that this problem happens to me if I try to update with the same email.

**Comment by harsh62** [comment]
@hrvoje0099 Then in that case it is expected. Because no real update happened in Cognito.
