### ISSUE TITLE
Xcode 14 beta is getting symbols not found

### ISSUE THREAD

**Issue by josher8** [aws-amplify/aws-sdk-ios#4283]
**Describe the bug**
Been testing Xcode 14 to ensure our apps work fine when it comes out. I have a cocoapod with a dependency of AWSS3. When I try to compile the app using xcodebuild, I get this error below. 

❌ Undefined symbols for architecture x86_64
❌   "_OBJC_CLASS_$_AWSServiceConfiguration", referenced from:
❌   "_OBJC_CLASS_$_AWSStaticCredentialsProvider", referenced from:
❌ ld: symbol(s) not found for architecture x86_64
❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)

I get this error the first time I run xcodebuild in the command line, but if i do it again, it compiles fine. But if I clear the derived data, then I'll get this error for the first compile again. Just wondering if this could be a bug in the iOS pod, Xcode 14, or in my project. The cocoapod that has AWSS3 pod compiles fine. I been pulling my hair out for days on this! This is only doing it in Xcode 14.

**To Reproduce**
Install a cocoapod with a dependency of AWSS3.
Build the project in the command line using xcodebuild. 

**Expected Behavior**
Should compile fine.

**Stack Trace**
❌ Undefined symbols for architecture x86_64
❌   "_OBJC_CLASS_$_AWSServiceConfiguration", referenced from:
❌   "_OBJC_CLASS_$_AWSStaticCredentialsProvider", referenced from:
❌ ld: symbol(s) not found for architecture x86_64
❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Code Snippet**
 xcodebuild -derivedDataPath "tmp/Build" -workspace ProjectWorkspace.xcworkspace -scheme "ProjectScheme"

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSS3 pod

**Environment(please complete the following information):**
 - SDK Version: 2.27.13
 - Dependency Manager: Cocoapods
 - Swift Version :5.0
 - Xcode Version: 14.0 beta 6

**Comment by atierian** [comment]
Thanks for opening this and for the thorough details @josher8. We'll look into it and respond on this issue with any updates.

**Comment by royjit** [comment]
Are you seeing these issue in the non-beta Xcode 14?

**Comment by josher8** [comment]
Yes I still got that error on the release Xcode. I did manage to figure out a solution. In the pod that had AWS, I added this in the podspec   s.static_framework = true and seemed to solve the issue.
