### ISSUE TITLE
Xcode warning: AWSS3TransferUtilityTasks: Writable atomic property 'taskIdentifier' cannot pair a synthesized setter with a user defined getter

### ISSUE THREAD

**Issue by yoasha** [aws-amplify/aws-sdk-ios#4284]
**Describe the bug**
While compiling with Xcode 14 Beta 6 or Xcode 13.4.1, getting the following warning:
AWSS3TransferUtilityTasks: Writable atomic property 'taskIdentifier' cannot pair a synthesized setter with a user defined getter

See attached screenshot.

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/5601548/187421350-b2773f75-bc68-4999-92e1-1ae890effe94.png">

**Comment by yoasha** [comment]
I looked closer for the cause of the warning and found the following:

There is a readonly taskIdentifier property at:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/5601548/187459094-3b9927a8-9ecf-4c63-8c73-20eea93f7058.png">

While there is a readwrite taskIdentifier property at:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/5601548/187460423-779626b1-c313-4396-8997-0b8f7432c035.png">

Now comes a custom getter method without a setter for a synthesized property which is causing the warning:
![](https://user-images.githubusercontent.com/5601548/187421350-b2773f75-bc68-4999-92e1-1ae890effe94.png)

**Comment by atierian** [comment]
Thanks for opening this issue. The fix for this warning will be included in the next release.
