### ISSUE TITLE
Submitted our app with new Xcode 14.0 and got this warning.

### ISSUE THREAD

**Issue by ahamel** [aws-amplify/aws-sdk-ios#4306]
The app references non-public selectors in Payload/bryte.app/Frameworks/AWSAuthCore.framework/AWSAuthCore: reloadSession

**Comment by thisisabhash** [comment]
There is similar discussion which was posted earlier. Closing this as a duplicate. 
https://github.com/aws-amplify/aws-sdk-ios/issues/4314
