### ISSUE TITLE
AWSIdentityProviderAmazonCognitoIdentity 

### ISSUE THREAD

**Issue by jiayew868** [aws-amplify/aws-sdk-ios#4307]
**Describe the bug**
A clear and concise description of what the bug is. Please be as detailed as possible and help us help you.

NSString *const AWSIdentityProviderAmazonCognitoIdentity = @"cognito-identity.amazonaws.com";

cognito-identity.amazonaws.com （usa）
cognito-identity.cn-north-1.amazonaws.com.cn （china）

we need change the default value , it can be work in china.  can you help check have a other way change the value  thanks

**Comment by royjit** [comment]
Thanks for opening this issue. We'll look into it and respond on this issue with any updates.

**Comment by royjit** [comment]
Can you give me details on how you are using the SDK. What kind of authentication mechanism you are using with Cognito. It would be great if you can provide us the following details:


---

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error


**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.


**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]


**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
AWSDDLog.sharedInstance.logLevel = .debug
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```
