### ISSUE TITLE
Xcode 14

### ISSUE THREAD

**Issue by xbindai** [aws-amplify/aws-sdk-ios#4310]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/84165254/190351043-d4bbc069-f0e6-496c-a8b9-6e131a204c04.png">

**Comment by donadev** [comment]
Up!

**Comment by thisisabhash** [comment]
Hello,
Could you please add detailed steps of reproduction for this issue and the use case you're trying to achieve. Also, please add information about the SDK version, Xcode version etc. so that it can help us in determining root cause.

**Comment by atierian** [comment]
This issue appears to be related to https://github.com/aws-amplify/aws-sdk-ios/issues/4283. Could you please try the option to link the frameworks statically as outlined in this [comment](https://github.com/aws-amplify/aws-sdk-ios/issues/4283#issuecomment-1249773668). Let us know if you still have problems after trying this.

**Comment by atierian** [comment]
@kvnh 
The usage of `s.static_framework = true` in that linked comment applies to a cocoapod that has a dependency on one of the pods from the SDK. Can you try `use_frameworks! :linkage => :static` in your podfile to see if that resolves your issue? [[Podfile Syntax Reference](https://guides.cocoapods.org/syntax/podfile.html#use_frameworks_bang)]

**Comment by kvnh** [comment]
Thanks @atierian 
In this case I managed to resolve my issue by updating `AWSMobileClient` from 2.12.0 to 2.17.0 and then updating the min deployment target to 13.

**Comment by atierian** [comment]
Great, thanks for letting us know.

**Comment by igorkirnosov** [comment]
@atierian Hi, do you think there is any way to do it without use_frameworks? Im trying to use `cocoapods-user-defined-build-types` plugin but im not really sure what params to set. Im tried to set static_framework on pod which is using AWSCore but then compiler returned error that I cant do it bc of AWSCore..
