### ISSUE TITLE
How do we know if federatedSignIn is actually succeeded?

### ISSUE THREAD

**Issue by zhangji** [aws-amplify/aws-sdk-ios#4394]
**State your question**
I am trying to setup this SDK to login with a OIDC provider. I found out `AWSMobileClient.default().federatedSignIn(providerName, token)` was always succeeded with any random provider name and token. So how do we know if federatedSignIn is actually succeeded? 
The reason I am asking this is because I put this federatedSignIn method with correct provider name and token from my OIDC provider, but I always get logs with `federatedSignIn successful` and then `user logged in via federation, but currently needs new tokens`.
 
**Which AWS Services are you utilizing?**
Amplify
Cognito

**Provide code snippets (if applicable)**
```
    AWSMobileClient.default().federatedSignIn(providerName: "randomstring",
                                              token: "randomstring") { userState, error in
        if let error = error {
            print("Error in federatedSignIn: \(error)")
            return
        }
        
        guard let userState = userState else {
            print("userState unexpectedly nil")
            return
        }
        
        print("federatedSignIn successful: \(userState)")
    }

        AWSMobileClient.default().addUserStateListener(self) { (userState, info) in
                switch (userState) {
                    case .guest:
                        print("user is in guest mode.")
                    case .signedOut:
                        print("user signed out")
                    case .signedIn:
                        print("user is signed in.")
                    case .signedOutUserPoolsTokenInvalid:
                        print("need to login again.")
                    case .signedOutFederatedTokensInvalid:
                        print("user logged in via federation, but currently needs new tokens")
                    default:
                        print("unsupported")
                }
        }
```

**Environment(please complete the following information):**
 - SDK Version: 2.28.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 15.5
 - Specific to simulators: iPhone 13 pro max

**Comment by harsh62** [comment]
@zhangji The implementation currently doesn't validate the token and provider in `federatedSignIn` call. The call simply saves the provider and token in the local cache and makes the `getAWSCredentials` request, but doesn't return the result. 

I would suggest to make separate `getAWSCredentials()` call. During this request, Cognito will validate the token against the provider.

**Comment by zhangji** [comment]
@harsh62 Thanks for the explanation. I then tried making `getAWSCredentials()` call after `federatedSignIn` like below, but I always got error `Obtaining an identity id in another thread failed or didn't complete within 5 seconds.`. What could be wrong here?
```
                    AWSMobileClient.default().getAWSCredentials { (credentials, error) in
                        if let error = error {
                            print("error in getAWSCredentials", error.localizedDescription)
                        } else if let credentials = credentials {
                            print("getAWSCredentials:", credentials.accessKey)
                        }
                    }
```

**Comment by harsh62** [comment]
Can you share some logs so that we can identify what exactly is going wrong.. 

We can enable verbose logging using the following code. 
```
            AWSDDLog.sharedInstance.add(AWSDDTTYLogger())
            AWSDDLog.sharedInstance.logLevel = .verbose
```
and importing 
```
 import AWSCore
```

**Comment by zhangji** [comment]
@harsh62 Here is the log. It sounds like a token issue?
```
2022-11-14 12:08:33:262 PollySample[54961:22308287] Response headers:
{
    "Content-Length" = 111;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Mon, 14 Nov 2022 18:08:33 GMT";
    "x-amzn-errormessage" = "Unauthenticated access is not supported for this identity pool.";
    "x-amzn-errortype" = "NotAuthorizedException:";
    "x-amzn-requestid" = "77a559fa-c905-4a4d-b355-3d98b96e3dba";
}
2022-11-14 12:08:33:262 PollySample[54961:22308287] Response body:
{"__type":"NotAuthorizedException","message":"Unauthenticated access is not supported for this identity pool."}
2022-11-14 12:08:33:262 PollySample[54961:22308287] GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]
2022-11-14 12:08:33:262 PollySample[54961:22308287] Obtaining an identity id in another thread failed or didn't complete within 5 seconds.
2022-11-14 12:08:33:262 PollySample[54961:22308287] Unable to refresh. Error is [Error Domain=com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper Code=0 "Obtaining an identity id in another thread failed or didn't complete within 5 seconds." UserInfo={NSLocalizedDescription=Obtaining an identity id in another thread failed or didn't complete within 5 seconds.}]
error in getAWSCredentials Obtaining an identity id in another thread failed or didn't complete within 5 seconds.
2022-11-14 12:08:33:264 PollySample[54961:22308287] Request headers:
{
    "Content-Type" = "application/x-amz-json-1.1";
    Host = "cognito-identity.us-east-1.amazonaws.com";
    "User-Agent" = "aws-sdk-iOS/2.28.0 iOS/15.5 en_US";
    "X-Amz-Date" = 20221114T180833Z;
    "X-Amz-Target" = "AWSCognitoIdentityService.GetId";
}
2022-11-14 12:08:33:264 PollySample[54961:22308287] Request body:
{"IdentityPoolId":"us-east-1:56964fd8-789c-4082-8861-5b2268c6b03f","Logins":{"pxhknzjhah7j-demo.authing.cn\/oidc":"vjnP03jSEofReQ6ZwLCV4jRUBunx3Yvm0nXjQGVO8Mp"}}
Error: The operation couldn’t be completed. (com.amazonaws.AWSCognitoIdentityErrorDomain error 8.)
2022-11-14 12:08:33:499 PollySample[54961:22308287] Response headers:
{
    "Content-Length" = 111;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Mon, 14 Nov 2022 18:08:33 GMT";
    "x-amzn-errormessage" = "Invalid login token. Not a valid OpenId Connect identity token.";
    "x-amzn-errortype" = "NotAuthorizedException:";
    "x-amzn-requestid" = "c24b35ab-e86f-49a6-8fa1-c1ceca76dbec";
}
2022-11-14 12:08:33:499 PollySample[54961:22308287] Response body:
{"__type":"NotAuthorizedException","message":"Invalid login token. Not a valid OpenId Connect identity token."}
2022-11-14 12:08:33:499 PollySample[54961:22308287] GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Invalid login token. Not a valid OpenId Connect identity token.}]
2022-11-14 12:08:33:499 PollySample[54961:22308286] Unable to refresh. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Invalid login token. Not a valid OpenId Connect identity token.}]
user logged in via federation, but currently needs new tokens
```

**Comment by harsh62** [comment]
@zhangji 

It seems like your tokens are invalid 

```
{"__type":"NotAuthorizedException","message":"Invalid login token. Not a valid OpenId Connect identity token."}
```

Also guest access to identity pool is not enabled. 
```
{"__type":"NotAuthorizedException","message":"Unauthenticated access is not supported for this identity pool."}
```

**Comment by zhangji** [comment]
@harsh62 I have tried feeding `federatedSignIn()` with id token, access token and refresh token. It looks like access token is the one to make this method works. Is this expected? I didn't find a good reference in https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/#federated-sign-in taking about the OIDC setup.

For the refresh token, does this IOS SDK store it in  the cache automatically so that it can be used to re-fetch access token when it's expired? If yes, when did the IOS SDK store the refresh token? Because I didn't pass the refresh token to SDK directly.

**Comment by harsh62** [comment]
@zhangji 
AWS SDK does not automatically refresh the provider's access token. It is the responsibility of the developer to write that logic. The iOS SDK will only cache the provider token (in your case access token) and use that to get the AWS Temporary credentials. 

Once the token expires, you would need to listen to this user state `signedOutFederatedTokensInvalid` to refresh the access token yourself.

**Comment by harsh62** [comment]
I think you are looking at the wrong documentation. The behaviour that you are seeing is valid for Cognito User Pool Tokens and not when federating.

> federatedSignIn() can be used to obtain federated "Identity ID" using external providers like Google, Facebook or Twitter. If the tokens are expired and new tokens are needed, a notification will be dispatched on the AWSMobileClient listener with the user state signedOutFederationTokensInvalid. You can give the updated tokens via the same federatedSignIn() method.

[Reference to the correct Federation documentation](https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/)

With respect to the example that you shared, I don't think it refreshed the token, as the accessToken seems to be the same for both the API calls.

**Comment by zhangji** [comment]
@harsh62 Thanks for all your help. I think I have figure out the token issue and get a much better understanding of the token flow now. For learning this AWS IOS SDK,  I mainly rely on https://docs.amplify.aws/sdk/q/platform/ios/, but I found a non-official archive version https://web.archive.org/web/20171208072327/http://docs.aws.amazon.com/mobile/sdkforios/developerguide/Welcome.html, which seems to provide more details of this SDK. Does AWS still have an official version similar to this archive one?

**Comment by harsh62** [comment]
@zhangji The legacy documentation has been migrated over to https://docs.amplify.aws/ . We don't maintain any other documentation. I would strongly recommend to always refer to the updated documentation.

**Comment by zhangji** [comment]
Okay. This issue is good to be closed.

**Comment by zhangji** [comment]
@harsh62 It looks like AWS is trying to suggest us to build new app using the amplify library https://github.com/aws-amplify/amplify-swift, but it seems that the amplify library is lacking a lot of AWS services compared to this IOS SDK, like dynamoDB, Polly, IoT, etc. Does it mean we should only use this IOS SDK instead of the Amplify one if we want to connect to a lot of different AWS services in our APP? I am new to AWS IOS development so trying to figure out the best practices.

**Comment by harsh62** [comment]
Yes. Amplify makes it easy to connect to some of the categories like Auth, Storage, Analytics and more.. But if you want to interact with all the different kind of AWS services, you should either use the [aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios) or [aws-sdk-swift](https://github.com/awslabs/aws-sdk-swift/).
