### ISSUE TITLE
AWSS3TransferUtility URL of public uploaded file

### ISSUE THREAD

**Issue by e1block** [aws-amplify/aws-sdk-ios#4422]
**State your question**

How do I get the URL of the **uploaded** file to S3 on completion? Reconstructing the correct URL is hit or miss depending on bucket configuration it seems. I'm using `AWSS3TransferUtility.uploadFile()` which works as expected. I need the URL itself, since it needs to be shared. I understand that this isn't the typical use case, since public access is not common. Nonetheless, this is required for my issue.

**Which AWS Services are you utilizing?**

S3

**Environment(please complete the following information):**
 - SDK Version: Main branch - `d0667b076a3411d097d3194418713ee98356a967`
 - Dependency Manager: Swift Package Manager
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone 13
 - iOS Version: iOS 16.1

**Comment by ruisebas** [comment]
Hi @e1block! Sorry for the late response.

The URL to access a bucket's file should be:

```
https://[BUCKET_NAME].s3.[REGION].amazonaws.com/[KEY]
```

As you mentioned, this only works if the bucket is properly configured to allow public access, i.e. you've turned **off** "Block public access" and defined an appropriate policy to allow the operation.

For example, this policy allows read access to anything in your bucket:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
        "Sid": [STATEMENT_ID],
        "Action": [
           "s3:GetObject"
        ],
        "Effect": "Allow",
        "Resource": "[BUCKET_ARN]/*",
        "Principal": "*"
        }
    ]
}
```

Alternatively, if you'd like a URL that you can use regardless of the bucket's permissions, you can generate a presigned URL. However, please note that these URLs have a maximum expiration date of 7 days.

Here's an example using the `AWSS3PreSignedURLBuilder`:

```swift
let request = AWSS3GetPreSignedURLRequest()
request.bucket = // Your bucket
request.key = // The file key
request.expires = // Expiration date
request.httpMethod = AWSHTTPMethod.GET

let preSignedUrlBuilder = AWSS3PreSignedURLBuilder(configuration: configuration)
preSignedUrlBuilder?.getPreSignedURL(request).continueWith(block: { task in
    if let error = task.error {
        // Handle error
    }

    if let result = task.result {
        print("presigned url: \(result)")
    }

    return task
})
```

Please let us know if you have any other question. Thanks!
