### ISSUE TITLE
Does not contain bitcode when using AWSCognito

### ISSUE THREAD

**Issue by halilpostaci** [aws-amplify/aws-sdk-ios#4477]
I got this error after update Xcode 14. If I switch Enable Bitcode to "No" it is working but I don't want to do it. Is there a solution to this problem? Do we have to use Enable Bitcode as a no?

'/Users/-/Library/Developer/Xcode/DerivedData/HotelApp-dvxyavtulfukemaexmfxgwnnlstw/Build/Products/Debug-iphoneos/AWSCognito/AWSCognito.framework/AWSCognito' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/-/Library/Developer/Xcode/DerivedData/HotelApp-dvxyavtulfukemaexmfxgwnnlstw/Build/Products/Debug-iphoneos/AWSCognito/AWSCognito.framework/AWSCognito' for architecture arm64

AWSCognito

<img width="966" alt="Screenshot 2022-12-26 at 23 09 45" src="https://user-images.githubusercontent.com/10594719/209580680-ab2bb2bc-8b90-496e-8206-a80bca5f4627.png">

Environment(please complete the following information):

 - SDK Version: 2.19.1
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

Device Information (please complete the following information):
 - Device: iPhone 8 plus
 - iOS Version: iOS 16.2

Could you help me? Thank you.

**Comment by ruisebas** [comment]
Hi @halilpostaci, thanks for opening this issue and sorry for the delay.

The **Amazon Cognito Sync** (`AWSCognito`) client is no longer supported, it was removed in version [2.20.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0). 

To support data synchronization in your app, you can check out the **DataStore** category from the [**AWS Amplify library**](https://github.com/aws-amplify/amplify-swift). 
Or if you cannot or do not wish to migrate to Amplify, you can use the [**AWS AppSync SDK**](https://github.com/awslabs/aws-mobile-appsync-sdk-ios) instead.

Let me know if you have any other question.
