### ISSUE TITLE
Unable to Build AWSMobileClientXCF error. XCode 14.2 + SPM

### ISSUE THREAD

**Issue by nickgavrilov** [aws-amplify/aws-sdk-ios#4487]
Hi! I added Added AWSMobileClient as dependency in SPM

However i got the following message
`Failed to build module 'AWSMobileClientXCF'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.`

 - SDK Version: 2.29.1
 - Dependency Manager: SPM
 - Swift Version : 5.7.2

I checked previous issues and see that this one is not new. And possible fix for it will be recompiling it. :/

**Comment by ruisebas** [comment]
Hi @nickgavrilov! Thanks for opening this issue and sorry for the delay.

I was not able to reproduce this using Xcode 14.2, SPM and Swift version 5.7.2, I was able to add and build `AWSMobileClientXCF` to a sample app correctly. 

However, I did manage to get the same build error as yours if I do not select the `AWSCore` library as well when adding the package:
![](https://raw.githubusercontent.com/aws-amplify/aws-sdk-ios/main/readme-images/spm-setup-04-select-dependencies.png)

Could you please double check if perhaps this is your case as well?
Thanks!
