### ISSUE TITLE
AWSMobileClient - Cannot find type 'AWSTaskCompletionSource' in scope swift

### ISSUE THREAD

**Issue by MasamMahmood** [aws-amplify/aws-sdk-ios#4490]
** AWSMobileClient - AWSTaskCompletionSource**
I am trying to set SNS Push notification using XCode 14.2 Intel machine Macbook pro. It gives me error
`Cannot find type 'AWSTaskCompletionSource' in scope swift`

I have set Pods and using latest release of AWS-SDK-IOS accordingly. I clean the project rebuilt it but same error. 
Please guide me thank you. 

```
target 'Project' do
  use_modular_headers!
  #AWS SNS Push Notification SDK
  pod 'AWSMobileClient', '~> 2.29.1'
  pod 'AWSPinpoint', '~> 2.29.1'
  pod 'AWSAuthCore', '~> 2.29.1'
  pod 'AWSCognitoIdentityProvider', '~> 2.29.1'
  pod 'AWSCore', '~> 2.29.1'
  pod 'AWSCognitoIdentityProviderASF', '~> 2.29.1'
  pod 'AWSS3', '~> 2.29.1'
  pod 'AWSAPIGateway', '~> 2.29.1'

end

```
![Screenshot 2023-01-05 at 6 19 26 PM](https://user-images.githubusercontent.com/36441313/210854260-0a6fe549-9e3c-45b5-8df7-6e08bf8045de.png)

**Comment by jaymalave** [comment]
insert `use_frameworks!` at the start of your `Podfile` just below platform and ENV[].

**Comment by phantumcode** [comment]
@MasamMahmood This can be fix by removing `use_modular_headers!` and replace it with `use_frameworks!` in the Podfile and then adding necessary framework as dependencies (i.e. add AWSMobileClient.framework

```
target 'Project' do
  use_frameworks!
  #AWS SNS Push Notification SDK
  pod 'AWSMobileClient', '~> 2.29.1'
  pod 'AWSPinpoint', '~> 2.29.1'
  pod 'AWSAuthCore', '~> 2.29.1'
  pod 'AWSCognitoIdentityProvider', '~> 2.29.1'
  pod 'AWSCore', '~> 2.29.1'
  pod 'AWSCognitoIdentityProviderASF', '~> 2.29.1'
  pod 'AWSS3', '~> 2.29.1'
  pod 'AWSAPIGateway', '~> 2.29.1'

end
```

<img width="903" alt="image" src="https://user-images.githubusercontent.com/103537251/222634122-72b01dca-1a37-4d3c-9224-8a7fa8f03dfb.png">

**Comment by phantumcode** [comment]
Closing this issue as there were no additional response from requester.  Please re-open if this is still an issue.
