### ISSUE TITLE
AWSTask Memory Leaks

### ISSUE THREAD

**Issue by pepper28** [aws-amplify/aws-sdk-ios#4493]
I have built my working application using AWS IOS SDK and although it works when I evaluated the application using stack tracing tools I have seen 38 memory leaks all referring to some aspect of AWS functions.

<img width="1578" alt="Screenshot 2023-01-06 at 5 26 41 PM" src="https://user-images.githubusercontent.com/6935344/211397810-f61b792c-148d-4079-b260-92d2310d6754.png">

**Comment by atierian** [comment]
Thanks for opening this issue @pepper28. We'll investigate it and respond here with any updates.

**Comment by pepper28** [comment]
Thanks, Ian for the reply.  The one very interesting aspect of the issues I’m having is the code I’m using is a direct copy of the sample code from Amazon without modifications.


Robert Bolder
nGage Behavior, LLC
President & CEO
***@***.***

phone: 201-247-2151



On Jan 17, 2023, at 9:28 AM, Ian Saultz ***@***.***> wrote:



Thanks for opening this issue @pepper28<https://github.com/pepper28>. We'll investigate it and respond here with any updates.

**Comment by phantumcode** [comment]
@pepper28 Can you provide additional details on sample code or sample app you're using? Please provide code snippet or reference to documentation you used.

What version of the AWS iOS SDK are you using and which service/client are you using that is causing the memory leak?
