### ISSUE TITLE
How to use AWS Polly?

### ISSUE THREAD

**Issue by Bawenang** [aws-amplify/aws-sdk-ios#4506]
**State your question**
Hi, I am trying to make the PollySample work. I've changed the Cognito Pool ID and Region in the `awsconfiguration.json` like this:

```
{
    "Version": "1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                "Region": "us-east-1"
            }
        }
    },
    "Polly": {
        "Default": {
            "Region": "us-east-1"
        }
    },
    "PollySynthesizeSpeechUrlBuilder": {
        "Default": {
            "Region": "us-east-1"
        }
    }
}
```

I have also done the 6 steps in the readme to set the Cognito and IAM.

The successBlock of the AWSTask to get the voices are not being hit. I've added a breakpoint there and it  didn't break. How do I use Polly and also handle the error for the AWSTask?

I have read the guide and I am still confused.

**Which AWS Services are you utilizing?**
AWS Polly

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.29.1
 - Dependency Manager: Cocoapods
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 15.5
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by Bawenang** [comment]
So, I've handled the error and it returned this error:

```
AWS Task failed! with error: Error Domain=com.amazonaws.AWSPollyErrorDomain Code=0 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=AccessDeniedException:http://internal.amazon.com/coral/com.amazon.coral.service/}
```

**Comment by Bawenang** [comment]
Hi, I've fixed it. It is my mistake in setting things up. It worked fine now.

**Comment by ponikarovskii** [comment]
@Bawenang hey! I'm facing the same issue. Could you please explain how did you fix it? thx in advance

**Comment by ponikarovskii** [comment]
okay, literally, you just need to do 3.5 and 3.6 from https://github.com/awslabs/aws-sdk-ios-samples/tree/main/Polly-Sample/Swift
