### ISSUE TITLE
AWSPollySynthesizeSpeechURLBuilder fails when I load from background 

### ISSUE THREAD

**Issue by guris12** [aws-amplify/aws-sdk-ios#4546]
Hi 

I am using amazon polly API for swift iOS 

let builder = AWSPollySynthesizeSpeechURLBuilder.default().getPreSignedURL(input)
builder.continueOnSuccessWith { (awsTask: AWSTask<NSURL>) -> Any? in } 

App  fails when I load from background , what could be the reasons ? 

Thanks

**Comment by atierian** [comment]
Thanks for opening this issue @guris12.
Can you please elaborate on what exactly fails? Also please enable verbose logging and post logs from a background attempt here; those will help us diagnose this. Thanks.
