### ISSUE TITLE
Extend Advance Usage

### ISSUE THREAD

**Issue by Yurssoft** [aws-amplify/aws-sdk-ios#4578]
This feature is requested to extend API of `AWSMobileClient` from `internal` to `public`. 

I do understand that it has been designed in this way, so exactly you cannot do what I describe here.

I would like to be able to login user with custom server implementation that generates for me `AWSCognitoIdentityUserSession`. By that I mean to have clear way to just set `idToken` & `accessToken` & `refreshToken`. To get you more of idea what I am looking for, consider this piece of code:
```swift
Auth.auth().signIn(withCustomToken: customToken ?? "") { user, error in
  // ...
}
```
Credit - https://firebase.google.com/docs/auth/ios/custom-auth

In this example we are able to use custom authenticate system to sign in user.

Ideally, I would like to have some direct way to do this without exposing `internal` APIs.

**Comment by royjit** [comment]
Hi @Yurssoft Thank you for reaching us. You can provide custom id token to federate to Cognito Identity Pool. You can find the documentation here - https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/ 

Note that this feature is available only with Amazon Cognito Identity Pool, and not with Amazon Cognito User Pool.

**Comment by Yurssoft** [comment]
Thank you for this. I will try to get to BE send me it👌

**Comment by victorOwnID** [comment]
Hi @royjit - I'm also looking into this. The flow is not very clear to me. If I have a id_token from Cognito user pool that I got trough a custom_challenge authentication flow with my server, and I have that id_token on my mobile app, how can I pass it to start the session on the Amplify SDK?

Can you clarify?

Thank you

**Comment by Yurssoft** [comment]
To expand what is the question - we use `federatedSignIn` with `providerName: IdentityProvider.developer.rawValue`. It was [Developer Authenticated Identities with Cognito Identity](https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/#developer-authenticated-identities-with-cognito-identity). 
We got our session. Session says that it signed in. Pretty much what we wanted. After we signed in, we trying go get user attributes, using `Amplify.Auth.fetchUserAttributes()`. It return error. 

Adding full session that we got.

```swift
▿ AWSAuthCognitoSession
  - isSignedIn : true
  ▿ userSubResult : Result<String, AuthError>
    ▿ failure : AuthError: Session expired could not fetch user sub
Recovery suggestion: Invoke Auth.signIn to re-authenticate the user
      ▿ sessionExpired : 3 elements
        - .0 : "Session expired could not fetch user sub"
        - .1 : "Invoke Auth.signIn to re-authenticate the user"
        - .2 : nil
  ▿ identityIdResult : Result<String, AuthError>
    ▿ failure : AuthError: Session expired could not fetch identity id
Recovery suggestion: Invoke Auth.signIn to re-authenticate the user
      ▿ sessionExpired : 3 elements
        - .0 : "Session expired could not fetch identity id"
        - .1 : "Invoke Auth.signIn to re-authenticate the user"
        - .2 : nil
  ▿ awsCredentialsResult : Result<AuthAWSCredentials, AuthError>
    ▿ failure : AuthError: Session expired could not fetch AWS Credentials
Recovery suggestion: Invoke Auth.signIn to re-authenticate the user
      ▿ sessionExpired : 3 elements
        - .0 : "Session expired could not fetch AWS Credentials"
        - .1 : "Invoke Auth.signIn to re-authenticate the user"
        - .2 : nil
  ▿ cognitoTokensResult : Result<AuthCognitoTokens, AuthError>
    ▿ failure : AuthError: Session expired could not fetch cognito tokens
Recovery suggestion: Invoke Auth.signIn to re-authenticate the user
      ▿ sessionExpired : 3 elements
        - .0 : "Session expired could not fetch cognito tokens"
        - .1 : "Invoke Auth.signIn to re-authenticate the user"
        - .2 : nil
 ```

As you might expect, next we have error on `Amplify.Auth.fetchUserAttributes()`
```swift
▿ AuthError: Could not fetch attributes, there is no user signed in to the Auth category
Recovery suggestion: SignIn to Auth category by using one of the sign in methods and then call user attributes apis
  ▿ signedOut : 3 elements
    - .0 : "Could not fetch attributes, there is no user signed in to the Auth category"
    - .1 : "SignIn to Auth category by using one of the sign in methods and then call user attributes apis"
    - .2 : nil
```

We would like to ask for more details how we can get `Amplify.Auth.fetchUserAttributes()` to work correctly with custom id token.
Thanks!

**Comment by harsh62** [comment]
API's like `fetchUserAttributes` only work when signed into Cognito User Pool. These API's are not supported when federating with a 3P IdToken.

**Comment by victorOwnID** [comment]
Hi @harsh62, thank you for your reply.

We would like to be able to login a user in  a user pool using the Cognito AccessToken, refreshToken and id_token. As it is possible today in the JS library: https://stackoverflow.com/a/67872625/18770645

We have a feature request open for Android as well: https://github.com/aws-amplify/amplify-android/issues/2291

**Comment by harsh62** [comment]
@victorOwnID Amplify Swift doesn't support setting tokens created outside of Amplify. Please file a feature request with the Swift team and the team can look into prioritizing it.
