### ISSUE TITLE
Native social SignIn with User Pools

### ISSUE THREAD

**Issue by tbates-mffy** [aws-amplify/aws-sdk-ios#4579]
**State your question**

Can I get some clarity on if it is actually possible to have native social SignIn implemented with AWSMobileClient and User pools?
If so, is there any documentation on how to get it running? I DO NOT want to use the WebUI

We currently have email and password flow running in live (natively). I am not using Amplify, but using AWSMobileClient directly.

I wish to implement a native Apple Sign in and Google Sign in button. Ideally, each user that registers will be added to the existing user pool.

All the documentation I have found shows how to configure the social signin, but implies that it is only for WebUI.

On a different project, I have both Google and Apple running on a user pool with the Amplify and WebUI so I am confident that the Apple side of things is configured correctly.

**Which AWS Services are you utilizing?**

AWSMobileClient
AWSMobileClientXCF

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.30.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone and Simulator
 - iOS Version: 14, 15, 16
 - Specific to simulators: No

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by royjit** [comment]
Hi @tbates-mffy  Thank you for reaching out. Amazon Cognito User Pool only support webUI based flow for social provider signIn. We have to go via the webUI for Apple SignIn and other social providers.

**Comment by tbates-mffy** [comment]
@royjit That is a shame. Especially considering the user experience of the web UI.
Do you have any plans to introduce the ability to build a native experience?

**Comment by abdallahshaban557** [comment]
Hi @tbates-mffy - we are working closely with the Amazon Cognito team to deliver a solution for this problem. We agree that the web UI experience is subpar when building mobile apps, and this is now one of our highest priority items to address.

**Comment by abdallahshaban557** [comment]
@tbates-mffy - please trust that we are trying our best, this is priority number 1 for us for our Authentication features.

**Comment by tbates-mffy** [comment]
@abdallahshaban557 are there any updates on this?

**Comment by abdallahshaban557** [comment]
Hi @tbates-mffy  - we are making some progress in defining that feature with the Cognito team. We do not have a date yet, but we will provide one in our Github repos when we lock it down.
