### ISSUE TITLE
Receive Message With Topic

### ISSUE THREAD

**Issue by fingerplay** [aws-amplify/aws-sdk-ios#4587]
**Describe the bug**
I have used the AWS IOT SDK to receive a MQTT message from server ,and find all messages received contains topic as the prefix. 

**To Reproduce**

**Observed Behavior**
the message is like this :
"\0\u{1D}le/116697644/prp/dsr/app/getr\0\u{01}{\"id\":645,\"d\":{\"onln\":1,\"online\":1,\"led_blink\":0,\"temp_value\":0,\"d1\":1,\"d2\":0,\"d3\":1000,\"d4\":157,\"d5\":\"012C03E803E8\",\"work_mode\":0,\"bright_value\":1000,\"switch_led\":1,\"colour_data\":\"012C03E803E8\",\"scene_data\":\"000064003203010103E803D4000000000300DA03B7037A000000000300B203E8035A0000000003008903B603B50000000003005903E8039900000000\"}}, 
there are some strange characters like \0\u{1D} around topic "le/116697644/prp/dsr/app/getr". And I can't remove them from the message.
**Expected Behavior**
 expected message is  "{\"id\":645,\"d\":{\"onln\":1,\"online\":1,\"led_blink\":0,\"temp_value\":0,\"d1\":1,\"d2\":0,\"d3\":1000,\"d4\":157,\"d5\":\"012C03E803E8\",\"work_mode\":0,\"bright_value\":1000,\"switch_led\":1,\"colour_data\":\"012C03E803E8\",\"scene_data\":\"000064003203010103E803D4000000000300DA03B7037A000000000300B203E8035A0000000003008903B603B50000000003005903E8039900000000\"}}"

**Stack Trace**
Please provide a stack trace if applicable e.g. a crash is occurring.

**Code Snippet**
I implement AWSIoTMQTTClientDelegate method 'receivedMessageData' here,  and get message from data parameter

``` 
   func receivedMessageData(_ data: Data!, onTopic topic: String!) {
        let stringValue = String(data: data, encoding: String.Encoding.utf8)            
            let millisecond = Date().milliStamp
            print("✅✅✅✅✅✅✅✅✅✅✅✅LE didReceiveMessage✅✅✅✅✅✅✅✅✅✅✅✅" + "millisecond = \(millisecond)")
            debugPrint("message:", stringValue)
            print("\n--------------------------------------------------------------------------------\n")        
    }
```

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [2.30.2]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [4]
 - Xcode Version: [14.0]

**Device Information (please complete the following information):**
 - Device: [iPhone13]
 - iOS Version: [e.g. iOS 16.0.3]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here like your specific use case.

**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
AWSDDLog.sharedInstance.logLevel = .debug
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Logs**

Please logs in the code block below. (See: [Logs Guidance](https://github.com/aws-amplify/aws-sdk-ios/blob/main/LogsGuidance.md.md))

<details>
<summary>Log Messages</summary>

```
INSERT LOG MESSAGES HERE
```
</details>

**Comment by jcjimenez** [comment]
Hi, @fingerplay thanks for your patience, we're working on testing your changes in a wider context so we can ensure other user's aren't negatively impacted.

**Comment by fingerplay** [comment]
Ok,it actually needs more testing.

在 2023-03-18 02:32:25，"JC Jimenez" ***@***.***> 写道：


Hi, @fingerplay thanks for your patience, we're working on testing your changes in a wider context so we can ensure other user's aren't negatively impacted.

**Comment by atierian** [comment]
Hi @fingerplay, thanks for opening this issue. 
What you're seeing before and after the topic are bytes that are included in the packet for various purposes. In this particular case, it looks control field and length bytes of the start of packet and the payload length bytes between the topic and payload. 

The goods news is that you don't need to manually decode / parse that information out.

The recommended way to subscribe to a topic is though `AWSIoTDataManager().subscribe(toTopid:qoS:messageCallback:)` as documented here: https://docs.amplify.aws/sdk/pubsub/working-api/q/platform/ios/#subscribe-to-a-topic. Using this API will give you the correct payload for a specific topic.

Let me know if you have any other questions, thanks!

**Comment by fingerplay** [comment]
ok,thanks
