### ISSUE TITLE
Disappointing documentation 

### ISSUE THREAD

**Issue by adamdahan** [aws-amplify/aws-sdk-ios#4602]
Honestly not even one of your examples work. Provide 0 e2e examples. What a disappointment. I'd expect more from amazon. 👎

**Comment by ruisebas** [comment]
Hi @adamdahan ! I'm sorry you had a bad experience with our current documentation.

Could you please provide more details about what you are trying to achieve, so we can help you and address the gaps in the docs?

Thanks!
