### ISSUE TITLE
AWSS3 Version 2.29.1 can't be installed

### ISSUE THREAD

**Issue by TheSuperiorStanislav** [aws-amplify/aws-sdk-ios#4606]
**Describe the bug**
Pod can't be installed

**To Reproduce**

Create Podfile with 
```
pod 'AWSS3', '~>  2.29.1'
```

**Observed Behavior**
Pod can't be installed

**Expected Behavior**
Pod is installed

**Stack Trace**
```
[!] CocoaPods could not find compatible versions for pod "AWSS3":
  In Podfile:
    AWSS3 (~> 2.29.1)

None of your spec sources contain a spec satisfying the dependency: `AWSS3 (~> 2.29.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Code Snippet**
```
pod 'AWSS3', '~>  2.29.1'
```

**Logs**

Please logs in the code block below. (See: [Logs Guidance](https://github.com/aws-amplify/aws-sdk-ios/blob/main/LogsGuidance.md.md))

<details>
<summary>Log Messages</summary>

```
[!] CocoaPods could not find compatible versions for pod "AWSS3":
  In Podfile:
    AWSS3 (~> 2.29.1)

None of your spec sources contain a spec satisfying the dependency: `AWSS3 (~> 2.29.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
</details>

**Comment by TheSuperiorStanislav** [comment]
Could you make `2.29.x` available again? We have an older version of the project which is dependent on this, and we need this to for testing breaking changes on new releases.

**Comment by ruisebas** [comment]
We have no plans on making `2.29.x` available through CocoaPods.

However, there were no functional changes in neither `AWSCore` nor `AWSS3` between `2.29.x` and. `2.30.x`, so you should be safe to upgrade and test using the newest version.

Alternatively, if you absolutely need to use `2.29.x`, you can checkout the code for said release and set it up as a local pod.

**Comment by TheSuperiorStanislav** [comment]
I see, okay then
