### ISSUE TITLE
AWSMobileClient v2.30.4 crashes on call to AWSMobileClient.default().signOut() works on 2.30.2

### ISSUE THREAD

**Issue by pmurphyjam** [aws-amplify/aws-sdk-ios#4609]
Calling this in Swift

AWSMobileClient.default().signOut()

Eventually calls :
performUserPoolSignOut()
and then crashes on this line :
185 :   if let task = self.userpoolOpsHelper.customAuthChallengeTaskCompletionSource?.task, !task.isCompleted {

Works in v2.30.2

We call this on our logout, and it use to work fine until this latest update now it crashes every time for any user.

Crash is on an iPhone 14Pro Max with latest iOS.

I'm running Xcode v14.2 (14C18)
iOS : 16.3.1
Swift 5.0

**Comment by ruisebas** [comment]
Hi @pmurphyjam , thanks for opening this issue.

I was unable to reproduce the crash, I could sign out successfully.  
Do you know if there is any pre-condition that triggers this crash? E.g. users with their token expired, users signing in and out repeatedly, etc?

To help us debug further, would you be able to provide any of the following?
1. The full crashlog
2. The logs you see in the console when it crashes. You can enable verbose logging to the console by doing this:
    ```swift
    AWSDDLog.sharedInstance.logLevel = .verbose
    AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
    ```
3. The contents of your `awsconfiguration.json` file with sensitive information removed.

Thanks!

**Comment by stephen-alexander** [comment]
Have also encountered this issue.

It is triggered by calling AWSMobileClient.default().signOut() when the user is not signed in. 

> AWSMobileClient.performUserPoolSignOut()
> Thread 1: Swift runtime failure. Unexpectedly found nil while implicitly unwrapping an Optional value.

**Comment by jcjimenez** [comment]
Hi @pmurphyjam, while this fix may not directly solve the root cause of what broke between the two versions you mention, it may mitigate the crash in the form of an error:

https://github.com/aws-amplify/aws-sdk-ios/pull/4665

**Comment by royjit** [comment]
@emrekarasahin Can you please provide us the entire crash log that is symbolicated? 
Also, did you initialize AWSMobileClient before calling `signOut` ?

**Comment by royjit** [comment]
Are you using in memory configuration of AWSMobileClient like this: 

```swift
let awsmobileClient = AWSMobileClient(configuration: configuration)
```

if yes, make sure to use the same object for any subsequent calls to `AWSMobileClent` and do not use the singleton `AWSMobileClient.default` .

https://docs.amplify.aws/sdk/configuration/setup-options/q/platform/ios/#configure-using-an-in-memory-object

**Comment by emrekarasahin** [comment]
> Are you using in memory configuration of AWSMobileClient like this:
> 
> ```swift
> let awsmobileClient = AWSMobileClient(configuration: configuration)
> ```
> 
> if yes, make sure to use the same object for any subsequent calls to `AWSMobileClent` and do not use the singleton `AWSMobileClient.default` .
> 
> https://docs.amplify.aws/sdk/configuration/setup-options/q/platform/ios/#configure-using-an-in-memory-object

No we are using it as a singleton for all.
