### ISSUE TITLE
AWSCognito blocking Update AWSSDK pods 

### ISSUE THREAD

**Issue by marwen1609** [aws-amplify/aws-sdk-ios#4638]
**Describe the bug**
I want to update my AWSSDK from **2.19.1** to **2.30.4**  using Cocoapods  but i keep getting this issue that AWSCognito is dependent on AWS Core 2.1.0   

**Observed Behavior**

```
 AWSCognito was resolved to 2.1.0, which depends on
      AWSCore (~> 2.1.0)

    AWSS3 was resolved to 2.30.4, which depends on
      AWSCore (= 2.30.4)
```

**Expected Behavior**
I want to be able to update all other aws pods, since AWSCognito **2.19.1** is the latest version on Cocoapods this is blocking the other pods : 

 ```
 # AWS
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSIoT'
  pod 'AWSS3'
  pod 'AWSAPIGateway'
```

**Environment(please complete the following information):**
 - SDK Version: 2.19.1
 - Dependency Manager:  Cocoapods
 - Swift Version : 5.0
 - Xcode Version: 14.0

**Device Information (please complete the following information):**
 - Device: N/A
 - iOS Version: 16
 - Specific to simulators:

**Comment by harsh62** [comment]
@marwen1609 Would you be able to share your POD file, redacted any sensitive information.

**Comment by marwen1609** [comment]
@harsh62  sure here you go : 

```
platform :ios, '14.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target '*******' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # General
  pod 'SwiftLint'

  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'

  # AWS
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSIoT'
  pod 'AWSS3'
  pod 'AWSAPIGateway'

  # Braze
  pod 'Appboy-iOS-SDK'

  # Payment
  pod 'Stripe'

  pod 'GooglePlaces'
  pod 'Charts'
  pod 'SwiftDate', '~> 5.0'
  pod 'MHLoadingButton'

  target '**********' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Fixes iOS Simulator deployment target warnings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings["DEVELOPMENT_TEAM"] = "***********"
    end
  end
end

```

**Comment by harsh62** [comment]
Hi @marwen1609, the Amazon Cognito Sync (AWSCognito) client is no longer supported, it was removed in version [2.20.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0).
So you should remove ` pod 'AWSCognito'` from your POD file and you should be good with updating your PODs.

**Comment by marwen1609** [comment]
@harsh62  Thank you now it updates normally 💯
