### ISSUE TITLE
Cannot upload to AppStore Connect due to AWSAuthCore:reloadSession issue.

### ISSUE THREAD

**Issue by jwarmkessel** [aws-amplify/aws-sdk-ios#4652]
**Describe the bug**
This issue was closed but I haven't had any luck uploading to AppStore Connect due to the same reloadSession issue. Check the last few comments after the issue was closed. [A clear and concise description of what the bug is. Please be as detailed as possible and help us help you.](https://github.com/aws-amplify/aws-sdk-ios/issues/4314)

I am using Cocoapods 1.12.0.

**To Reproduce**
1. Archive build
2. Upload to AppStore Connect 

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient, Cognito, Pinpoint 

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.30.4
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0
 - Xcode Version: 14.2

**Device Information (please complete the following information):**
 - Device: Simulator 
 - iOS Version: iOS 16

**Comment by jwarmkessel** [comment]
cc: @phantumcode

**Comment by atierian** [comment]
Hi @jwarmkessel, thanks for opening this issue. 

What error are you seeing that's preventing you from uploading to App Store Connect?

We're aware of the warning that is displayed when uploading, but it shouldn't prevent the upload from happening. In the issue you linked, there's a through explanation as to why this warning occurs.

If this is indeed blocking you from successfully uploading, please provide us with a screenshot or post the error message here so we can investigate.

**Comment by jwarmkessel** [comment]
@atierian thanks for the quick response. You're right. I do see that the app is uploaded. What's confusing is that Xcode only mentions the warning and I believe only offers a cancel button.

**Comment by atierian** [comment]
Thanks for letting us know. I'm glad to hear it's not blocking you!

And yes, agreed, the warning and how it's presented is very confusing.
