### ISSUE TITLE
S3 uploads are slower in IOS compared to Android

### ISSUE THREAD

**Issue by chawda** [aws-amplify/aws-sdk-ios#4662]
We are trying to upload image of around 1 Mb and it is taking around 30 seconds to finish upload. Inside progress block we get fractionCompleted 1.0, but after this completion for success is taking around 20 seconds.

We are using transfer utility.
We are facing this with and without using multipart.
Both iOS and Android are using same bucket.
android is taking around 5-10 seconds to complete upload, but iOS is taking around 25-40 seconds to upload.
We are facing this while app is in foreground.

Environment

SDK Version: 2.30.4
Dependency Manager: SPM
Swift Version : 5.6.1
Xcode Version: 14.1 (14B47b)

Device Information
Device: iphone SE second generation
iOS Version: iOS 16.1

**Comment by harsh62** [comment]
@chawda It seems this issue is very similar to the one posted in Amplify Swift (https://github.com/aws-amplify/amplify-swift/issues/1542). 

Would you be able to try this workaround mentioned [here](https://github.com/aws-amplify/amplify-swift/issues/1542#issuecomment-1462827342)?

**Comment by atierian** [comment]
Hey @chawda, we just released [AWS SDK for iOS version 2.31.1](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.31.1) that makes large improvements to upload speed. For an overview of these improvements, see https://github.com/aws-amplify/amplify-swift/pull/2925. 

Thanks for your patience.
