### ISSUE TITLE
with AWSCore pod version '2.30.4' Xcode gives error for bitcode enabled build

### ISSUE THREAD

**Issue by SanamdeepSingh-826** [aws-amplify/aws-sdk-ios#4680]
**Xcode gives error when using AWSCore pod version '2.30.4' for bitcode enabled build**

**i am using AWSCore pod version '2.30.4'**

**pod 'AWSCore', '~> 2.30.4'**

**Environment(please complete the following information):**
 - SDK Version: 2.30.4
 - Dependency Manager: Cocoapods
 - Swift Version : [e.g. 4.0]

**Device Information :**
 - While creating a archive for any iOS Device

ld: '/Users/apple/Library/Developer/Xcode/DerivedData/...-hgmfslkrxnfzmhgmoipqhochpvnz/Build/Intermediates.noindex/ArchiveIntermediates/.../BuildProductsPath/Release-iphoneos/AWSCore/AWSCore.framework/AWSCore' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/apple/Library/Developer/Xcode/DerivedData/...-hgmfslkrxnfzmhgmoipqhochpvnz/Build/Intermediates.noindex/ArchiveIntermediates/.../BuildProductsPath/Release-iphoneos/AWSCore/AWSCore.framework/AWSCore' for architecture arm64

**Comment by harsh62** [comment]
@SanamdeepSingh-826 

Did you recently update the SDK from an older version to `2.30.4`. It seems like you are still using the locally cached version not the latest with bitcode, please run `pod cache clean --all` and then `pod install` to pull it down from the repo again. Or may be just run the following with deintegrate. 
```
pod cache clean --all && pod deintegrate && pod install
```

**Comment by MurtuzaSrashtaSoft** [comment]
Solve Disable BitCode in target and project level both.  

<img width="818" alt="Screenshot 2023-05-06 at 4 04 29 PM" src="https://user-images.githubusercontent.com/64843262/236625970-67a64ba7-41ad-46ea-aa1f-7da98b2c79ca.png">
