### ISSUE TITLE
aws-sdk-ios-samples: Download completes with no error, but no file downloaded

### ISSUE THREAD

**Issue by derwaldgeist** [aws-amplify/aws-sdk-ios#4702]
We are trying to integrate the S3TransferUtility into an existing iOS app. For our use-case, Amplify would be too bulky, so we want to go for the low-level APIs. In preparation of this, I am trying to get the S3TransferUtility sample work from this repository:

https://github.com/awslabs/aws-sdk-ios-samples

I think I have setup everything correctly, and the file download completes without any error. But the image I downloaded is not being displayed. I tried to debug this and found out that the returned NSData object `data` always contains 469 bytes, which is way lower than the actual size we uploaded to S3 for testing purposes.

The upload case doesn't work at all, the upload progress bar just gets stuck and nothing happens anymore.

What might be a reason for this weird behaviour? I would at least expect an error message if something goes wrong.

**Comment by royjit** [comment]
Hi @derwaldgeist  We recommend you to try out the Amplify Storage category. You only need to include Amplify AWSS3StoragePlugin and AWSCognitoAuthPlugin to get this started - https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios/ . The package size depend on the framework you add to the project.

If you would still like to use the AWS SDK for iOS, here are some tutorial on how to setup - https://docs.amplify.aws/sdk/storage/getting-started/q/platform/ios/ . Hopefully this will unblock you, if not could you provide the verbose log of your app after redacting sensitive informations. Here are some instructions on how to setup verbose logging - https://docs.amplify.aws/sdk/configuration/setup-options/q/platform/ios/#logging

**Comment by derwaldgeist** [comment]
Hi @royjit, Thanks for your fast response, highy appreciated!

Regarding Amplify: Yes, I had seen these docs. However, my setup is a bit more complicated, as the app is based on Unity. My goal is to create a native Unity plugin, so I have to hook everything into their build process. Having to use any additional CLI tools here is a burden, especially if you don't know what they're doing. I will have to mimic all of these steps, so I can setup the build process in Unity accordingly. Otherwise, the build could not be automated.

Is there any documentation what the CLI tools are actually doing internally, like setting up pods, modifying .plist files etc?

Another challenge is that Amplify is using Swift. To my experience, this quite often causes problems when integrating with Unity. So I was pleased to see that the low-level iOS samples were still available in Objective-C. Although language-wise Swift is much more modern and nicer, using it in such a setup lets you run into quite some quirks.

Also, thanks for the hint to detailled logging. Will have a look into that.

**Comment by derwaldgeist** [comment]
After enabling logging, I saw this PermanentRedirect message in the logs:

"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

However, there is no way to specify an endpoint in the sample code, only the bucket and the region. This does not seem to be enough, though.

**Comment by derwaldgeist** [comment]
Another reason why I want to go for the low-level APIs: Amplify expects a certain bucket layout (folders "public", "protected", "private"), which my app does not use. Changing this would cause a lot of trouble, since I would have to take care of existing app versions as well.

BTW: Is there any documentation how once could use the low-level APIs with an authenticated user? The current sample files seem to assume that the IAM role is unauthenticated. I guess that's a security risk, isn't it?
