### ISSUE TITLE
EXC_BAD_ACCESS AWSPinpointEventRecorder crash when device is locked

### ISSUE THREAD

**Issue by mmathewsTableau** [aws-amplify/aws-sdk-ios#4721]
**Describe the bug**
Our app crashes when AWSPinpointEventRecorder tries to update the sqlite database while the device is locked. The crash occurs on this [line](https://github.com/aws-amplify/aws-sdk-ios/blob/2.30.4/AWSPinpoint/AWSPinpointEventRecorder.m#L1120).

We end up in this block because `db executeUpdate` fails. This makes sense because our app is configured with NSFileProtectionComplete, which means the app does not have access to the underlying filesystem when the device is locked. What I have observed is the first call to `db.lastError` in this code block is successful but the second call (the line referenced above) fails with EXC_BAD_ACCESS. I believe the action of getting the last error may close the database(?). 

I have a local fix that gets rid of this crash from happening in AWSPinpointEventRecorder. I plan to make a PR with this fix. However, I will say that I've occasionally seen EXC_BAD_ACCESS errors happening inside AWSFMDatabase using the same repro steps (it usually requires many more repro attempts to get this)

**To Reproduce**

Prereq (use an app that has NSFileProtectionComplete). I am also using a real device (not 100% sure if that's required)
1. Attach debugger to the app
2. Put breakpoint [here](https://github.com/aws-amplify/aws-sdk-ios/blob/2.30.4/AWSPinpoint/AWSPinpointEventRecorder.m#L1114). Do something to make sure the app hits it. 
3. Once the app hits the breakpoint, lock the device
4. Wait at least 5 seconds.. maybe more..
5. Step over the rest of the logic. `result` should be `no` and once you enter the  [error logging](https://github.com/aws-amplify/aws-sdk-ios/blob/2.30.4/AWSPinpoint/AWSPinpointEventRecorder.m#L1119) code block , the `*error = db.lastError;` line should cause EXC_BAD_ACCESS and a crash. 

**Observed Behavior**

App crashes

**Expected Behavior**

App doesn't crash. I think the app not being able to update the database is expected, however, I would expect the library to handle this scenario more gracefully (ie not crash) 

**Stack Trace**

Pods/AWSPinpoint/AWSPinpoint/AWSPinpointEventRecorder.m:1120:36 __60-[AWSPinpointEventRecorder putEvents:error:endpointProfile:]_block_invoke_3.234
Pods/AWSCore/AWSCore/FMDB/AWSFMDatabaseQueue.m:187:9__49-[AWSFMDatabaseQueue beginTransaction:withBlock:]_block_invoke
Pods/AWSCore/AWSCore/FMDB/AWSFMDatabaseQueue.m:176:5 -[AWSFMDatabaseQueue beginTransaction:withBlock:]
Pods/AWSPinpoint/AWSPinpoint/AWSPinpointEventRecorder.m:1113:21 __60-[AWSPinpointEventRecorder putEvents:error:endpointProfile:]_block_invoke_2.233
Pods/AWSCore/AWSCore/Bolts/AWSTask.m:331:21 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke

**Code Snippet**

https://github.com/aws-amplify/aws-sdk-ios/blob/2.30.4/AWSPinpoint/AWSPinpointEventRecorder.m#L1120

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
PinPoint

**Screenshots**

N/A

**Environment(please complete the following information):**

 - SDK Version:
  pod 'Amplify', '1.29.1'
  pod 'AmplifyPlugins/AWSPinpointAnalyticsPlugin', '1.29.1'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin', '1.29.1'

 - Dependency Manager: Cocoapods
 - Xcode Version: 14.2

**Device Information (please complete the following information):**
 - Device: Looking at customer data. It's not specific to any device. Happening on various iphones and reproed on ipad. One example (if needed ) - iphone 12
 - iOS Version: Looking at customer data. It's not specific to any iOS version. One example (if needed) 16.4.1
 - Specific to simulators: No

**Additional context**

Mentioned above but you will need some data protection on the app that's executing (ie NSFileProtectionComplete)

**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
AWSDDLog.sharedInstance.logLevel = .debug
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Logs**

Please logs in the code block below. (See: [Logs Guidance](https://github.com/aws-amplify/aws-sdk-ios/blob/main/LogsGuidance.md.md))

<details>
<summary>Log Messages</summary>

```
INSERT LOG MESSAGES HERE
```
</details>

**Comment by harsh62** [comment]
@mmathewsTableau Thanks for opening the issue. The team will investigate and get back to you.

**Comment by mmathewsTableau** [comment]
Here is the PR for a fix I tested locally:
https://github.com/aws-amplify/aws-sdk-ios/pull/4728

**Comment by ruisebas** [comment]
Hi @mmathewsTableau ! Thanks for opening this issue and for submitting a fix for it.

The PR has been merged and the fix should be included in the SDK next release 🎉.

**Comment by mmathewsTableau** [comment]
Awesome, thanks @ruisebas! Would you happen to have a rough idea of when the next release is expected to be? (trying to figure out whether I should patch locally or if I can wait until the next release)

**Comment by ruisebas** [comment]
Sure, the next release should be next week 😃

**Comment by royjit** [comment]
The PR is released, closing the issue.

**Comment by mmathewsTableau** [comment]
@ruisebas , apologies if you are not the right person to ask but would you also have an idea of when the plugins that depend on this library will get updated to be compatible with a version that has a fix ( >= 2.33.0)? 

I'm unable to get this fix into our app since we have a transient dependency on AWSPinpoint through the plugins: AmplifyPlugins/AWSPinpointAnalyticsPlugin & AmplifyPlugins/AWSCognitoAuthPlugin which are not yet compatible with 2.33.0 of AWSPinpoint

**Comment by ruisebas** [comment]
Hi @mmathewsTableau , thanks for bringing this up.

We will release a new Amplify v1 version shortly that updates the SDK dependency and post an update here once it's done.

**Comment by ruisebas** [comment]
Apologies for the delay in updating here until today.
[1.30.2](https://github.com/aws-amplify/amplify-swift/releases/tag/1.30.2) was released updating the SDK dependency to `2.33.x`.

**Comment by mmathewsTableau** [comment]
We released a new version of our app with this change and unfortunately, we are still seeing this issue occur :( 

We already had plans to upgrade to Amplify V2 before V1 loses support. Any ideas if this issue will persist in V2 of amplify (ie is this code path still relevant in V2)? @ruisebas

**Comment by ruisebas** [comment]
Hi @mmathewsTableau! Amplify v2 does not depend on this SDK, so this code path is not relevant if you upgrade.

I've quickly attempted to reproduce this issue on an app using Amplify v2 and while the operation did fail to write to the local database as expected (due to the protection), the application did not crash.
