### ISSUE TITLE
Unable to download AWSKinesisVideoWebRTCStorage-2.31.1.zip while building with 

### ISSUE THREAD

**Issue by alemiser** [aws-amplify/aws-sdk-ios#4723]
I have an iOS  14.2 app that compiles without issue back in February 2023 that includes aws-sdk-ios-spm library using the swift package manager.
But now (May 8th, 2023) when I do a clean git CI/CD get I am getting this error

"failed downloading 'https://releases.amplify.aws/aws-sdk-ios/AWSKinesisVideoWebRTCStorage-2.31.1.zip' which is required by binary target 'AWSKinesisVideoWebRTCStorage': badResponseStatusCode(403)"
This breaks the build due to failure to download the library.

**Which AWS Services are you utilizing?**
N/A

**Provide code snippets (if applicable)**
![image](https://user-images.githubusercontent.com/10187994/236890059-d1386267-c8ce-4b8f-9184-6211adf8676a.png)
Package dependency
https://github.com/aws-amplify/aws-sdk-ios-spm

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - 5.0

**Device Information (please complete the following information):**
 - Simulator iPhone 14
 - iOS 16.2

**Comment by harsh62** [comment]
Thanks for raising this issue. I am actively working on getting a fix out.  Expect a release to be out soon. Will update once we have more details.

**Comment by ruisebas** [comment]
Hi @alemiser, this should be fixed in the newest **`2.32.0`** version. 

Could you please check? Thanks!

**Comment by sjedruszkiewicz** [comment]
@ruisebas This version indeed fixes the problem, thanks.

**Comment by alemiser** [comment]
sorry been busy with other issues, i can also verify that this issue have been fixed. Thank you very much!
