### ISSUE TITLE
ChimeIdentityService RegisterAppInstanceUserEndpoint is returning "conflictException"

### ISSUE THREAD

**Issue by jwarmkessel** [aws-amplify/aws-sdk-ios#4731]
Describe the bug
Chat push notifications aren't working because I'm getting a failure when trying to RegisterAppInstanceUserEndpoint.

Expected behavior
Expecting successful registration.

Logs
"Optional(Error Domain=com.amazonaws.AWSChimeSDKIdentityErrorDomain Code=2 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=ConflictException})"

Test environment Info (please complete the following information):

Device: iPhone 13, 14.
OS: iOS 16.4
Version AmazonChimeSDK: 3.40
Additional context

**Comment by jwarmkessel** [comment]
```
        let request: AWSChimeSDKIdentityRegisterAppInstanceUserEndpointRequest = AWSChimeSDKIdentityRegisterAppInstanceUserEndpointRequest()
        
        let endpointAttributes: AWSChimeSDKIdentityEndpointAttributes = AWSChimeSDKIdentityEndpointAttributes()
        endpointAttributes.deviceToken = deviceToken
        request.allowMessages = AWSChimeSDKIdentityAllowMessages.all
        request.clientRequestToken = UUID().uuidString
        request.appInstanceUserArn = appInstanceUserArn
        
        var type: AWSChimeSDKIdentityAppInstanceUserEndpointType = Environment.current() == .development ? .apnsSandbox : .apns
        
        if type == .apns {
            print("apns")
        } else if type == .apnsSandbox {
            print("apnsSandbox")
        }
                
        request.types = type
        request.resourceArn = "arn:aws:mobiletargeting:[region]:[app instance]:apps/[pinpoint id]" //pinpoint ARN
        request.endpointAttributes = endpointAttributes
        
        awsChimeSDKIdentityClient?.registerAppInstanceUserEndpoint(request) { response, error in
            completion(response, error)
        }

**Comment by ruisebas** [comment]
Hi @jwarmkessel, thanks for opening this issue.

I was able to successfully invoke `registerAppInstanceUserEndpoint` without getting any error using the [Amazon Chime iOS Chat Demo app](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat-ios) and the latest `AWSChimeSDKIdentity` version (which is **2.31.1**).

Playing around, I managed to get the **ConflictException** error only when I invoked `registerAppInstanceUserEndpoint` again with the same values. 

It seems that the Chime service will reject a "duplicated" **RegisterAppInstanceUserEndpoint** API call, so I'd advice you to check that you have the necessary validations in your code.

If that doesn't work, there might be something else wrong in your set up. According to [the API docs](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_identity-chime_RegisterAppInstanceUserEndpoint.html#API_identity-chime_RegisterAppInstanceUserEndpoint_Errors), a **ConflictException** means that:
>The request could not be processed because of conflict in the current state of the resource.
>
>HTTP Status Code: 409

**Comment by jwarmkessel** [comment]
- Could you try a AWSChimeSDKIdentityAppInstanceUserEndpointType.apns type setup versus  AWSChimeSDKIdentityAppInstanceUserEndpointType.apnsSandbox?

- If I terminate the app and start again and call ```awsChimeSDKIdentityClient?.registerAppInstanceUserEndpoint(request) { response, error in
            completion(response, error)
        }``` this will cause an error? Is this what you mean by "duplicated RegisterAppInstanceUserEndpoint API call".
        

-  "The request could not be processed because of conflict in the current state of the resource." is too vague for me to help me fully debug this issue. 

- This request.clientRequestToken = UUID().uuidString should technically make the request unique since I'm generating a new UUID string every time this is getting called.

**Comment by ruisebas** [comment]
> Could you try a AWSChimeSDKIdentityAppInstanceUserEndpointType.apns type setup versus AWSChimeSDKIdentityAppInstanceUserEndpointType.apnsSandbox?

I got the same result, worked the first time and did not work if called again.

> If I terminate the app and start again and call awsChimeSDKIdentityClient?.registerAppInstanceUserEndpoint(request) { response, error in completion(response, error) } this will cause an error? Is this what you mean by "duplicated RegisterAppInstanceUserEndpoint API call".

Yes, it will result in an error if the first `registerAppInstanceUserEndpoint(_:)` succeeded. 

What I meant with "duplicated" was attempting to register the same endpoint more than once. It seems that once the endpoint is registered, you should not attempt to register it again, otherwise it fails. 

In your app, try calling `awsChimeSDKIdentityClient.deregisterAppInstanceUserEndpoint(_:)` first and then `awsChimeSDKIdentityClient.registerAppInstanceUserEndpoint(_:)`, it should succeed. 

Or at least that's the behaviour I am experiencing.

**Comment by jwarmkessel** [comment]
Okay, I'll try that out! Thanks!

**Comment by jwarmkessel** [comment]
Looks like if I have not successfully registered I don't get an endpoint to use for deregistering.

**Comment by jwarmkessel** [comment]
Maybe there's something wrong when registering the same app instance ARN (chime users) with multiple device tokens? Or the other way around?

**Comment by jwarmkessel** [comment]
A little more context. Push notifications were working initially, but when I push the app to TestFlight they stopped working. Even after I set the type to .apns.

**Comment by jwarmkessel** [comment]
I just hit this error as well: 

error: Optional(Error Domain=com.amazonaws.AWSChimeSDKIdentityErrorDomain Code=4 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=ResourceLimitExceededException})

**Comment by jwarmkessel** [comment]
So production apps now have notifications working. I had to delete the app and reinstall. Prevent registration from calling more than once... wonder why this would be problematic. However, my personal account is getting this message: 

error: Optional(Error Domain=com.amazonaws.AWSChimeSDKIdentityErrorDomain Code=4 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=ResourceLimitExceededException})

I don't know how to retrieve the endpointID to deregister.

**Comment by ruisebas** [comment]
Great! Deleting the app and reinstalling might have gotten you a new `deviceToken`, so that could be why the request succeeded. 

Make sure to include a check to prevent calling `registerAppInstanceUserEndpoint` more than once for the same token.

**ResourceLimitExceededException** is just another of the API valid error responses. Based on it's name, I'd advice you to check your Service Quotas. 

And regarding `endpointID`, you get it from the `AWSChimeSDKIdentityRegisterAppInstanceUserEndpointResponse` object. You might want to store it if you wish to use it later.
