### ISSUE TITLE
Cannot use AWSCore latest(2.30.4) with AWSCognito & with AWSS3

### ISSUE THREAD

**Issue by gurmeet0052** [aws-amplify/aws-sdk-ios#4740]
I want to install AWSCognito, AWSS3 & AWSRekognition, first two depends upon different version of AWSCore(2.19.1) and AWSRekognition depend on different versions of the AWSCore that is (2.30.4). How can I resolve this conflict in the AWSCore version dependency so that I can use all of them in my project.  

Here is the code of my podfile :
    pod 'AWSS3'
    pod 'AWSCognito'
    pod 'AWSRekognition'

if I install pods after adding above repo details the version of AWSCore and all other frameworks i'm getting is 2.19.1, But for AWSRekognition I need '2.30.4' version. Now if I replace pod 'AWSRekognition' with below line  

    pod 'AWSRekognition', :git => 'https://github.com/aws-amplify/aws-sdk-ios.git', :tag => '2.30.4'

I'm getting below error : 

[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In snapshot (Podfile.lock):
    AWSCore (= 2.19.1)

  In Podfile:
    AWSRekognition (from `https://github.com/aws-amplify/aws-sdk-ios.git`, tag `2.30.4`) was resolved to 2.30.4, which depends on
      AWSCore (= 2.30.4)

Specs satisfying the `AWSCore (= 2.19.1), AWSCore (= 2.30.4)` dependency were found, but they required a higher minimum deployment target.

**Comment by royjit** [comment]
The pod `AWSCognito` was deprecated and removed on 2.20.0 https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0 . This pod was linked to the deprecated service Cognito Sync https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-sync.html .

**Comment by royjit** [comment]
If you are looking for Cognito Services like Cognito User Pool or Cognito Identity Pool you can follow the guide here - https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/
