### ISSUE TITLE
Crash AWSIoTMQTTClient webSocketDidOpen 

### ISSUE THREAD

**Issue by JeansHuang** [aws-amplify/aws-sdk-ios#4775]
![image](https://github.com/aws-amplify/aws-sdk-ios/assets/4213741/8f630eb7-932c-4e68-b264-971d7b950538)

**Comment by thisisabhash** [comment]
Hello,
Could you please provide your AWS configuration file with sensitive information removed and code snippets that you're using. It'd be great to provide verbose logs as well using steps here : https://github.com/aws-amplify/aws-sdk-ios#logging

**Comment by JeansHuang** [comment]
> 

![image](https://github.com/aws-amplify/aws-sdk-ios/assets/4213741/377d3acb-85bf-4a6b-8390-7af593cc94d4)

**Comment by weidongliu** [comment]
@JeansHuang 
I also encountered this crash in version 2.30.4 of AWSIoT. Which version did you encounter? When the app locks the screen in the foreground and unlocks the screen after a while, this crash happens occasionally

**Comment by phantumcode** [comment]
@JeansHuang Can you provide a sample app that we could use to reproduce the crash?

**Comment by phantumcode** [comment]
@JeansHuang @weidongliu Are you still experiencing this crash issue? Can you help provide a sample app to reproduce the issue?

**Comment by phantumcode** [comment]
Closing issue to inactivity, please re-open if this is still an active blocking issue.
