### ISSUE TITLE
Error in Xcode 15 beta.

### ISSUE THREAD

**Issue by iJamesAdi9** [aws-amplify/aws-sdk-ios#4789]
How can I fix it?
my project base on Objective-C.
Thank you.
<img width="855" alt="CleanShot 2566-06-20 at 01 03 47@2x" src="https://github.com/aws-amplify/aws-sdk-ios/assets/116384545/bb14275b-c574-470f-83f5-e095fe3374f8">

**Comment by atierian** [comment]
Thanks for opening this issue.
Based on this [thread](https://developer.apple.com/forums/thread/731090) on Apple Developer Forums, this appears to be a known issue with the new linker included with Xcode 15 beta.

According to [this comment](https://developer.apple.com/forums/thread/731090?answerId=755628022#755628022), you can work around it by passing `-ld64` to  **Other Linker Flags**.

**Comment by iJamesAdi9** [comment]
Thanks!!
