### ISSUE TITLE
AWSAuthUI layout and dark mode issues

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-ios#4800]
**Describe the bug**
AWSAuthUI 2.33.0 SignIn.storyboard has a two issues 

(1) when displaying all three provider buttons (named "Provider Row 1" to 3) the top provider button overlaps the label "or sign in with" Refactoring the constrains is recommended to produce a more visually appealing layout (proper and adaquate spacing between labels and buttons recommended).

(2) Does not correctly support Dark Mode.  Some views may have hard coded background or label colors vs using System default background / label colors. Use of "Secondary System Background Color" is recommended to appear under "Sign in with Apple" button (to avoid black on black colors)

**To Reproduce**
1. call AWSMobileClient.default().showSignIn with 3 sign-in providers (Apple, Google, and Facebook) plus Cognito username / password login
2. Observe layout issues 
3. Toggle the phone to Dark Mode
4. Observe some areas of the screen darken, button text may be unreadable, etc. 

**Environment(please complete the following information):**
 - SDK Version: 2.33.0
 - Dependency Manager: Cocoapods
 - Swift Version : [e.g. 4.0]
 - Xcode Version: [e.g. 11.4]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: not iOS specific (testing in 15+)
 - Specific to simulators: No

**Comment by ruisebas** [comment]
Hi @BillBunting , thanks for opening this issue.
We'll take a look and add a comment once we have an update.

**Comment by ruisebas** [comment]
A fix for these issues has been merged into the `main` branch and will be available in the next release.

**Comment by ruisebas** [comment]
The fix has been released in v[2.33.2](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.33.2)
