### ISSUE TITLE
AWSS3TransferUtility timeout in multi part upload of a large file

### ISSUE THREAD

**Issue by TomRaz** [aws-amplify/aws-sdk-ios#4812]
**Describe the bug**
I get a timeout after 50 minutes when trying to upload a large file (10GB) using AWSS3TransferUtility multi part upload. This happens even when I set timeoutIntervalForResource to 24 hours (in seconds of course). We are not using AWS Cognito credentails, but instead use we are using **static credentials**.

**To Reproduce**
```
AWSS3TransferUtility.default().transferUtilityConfiguration.timeoutIntervalForResource = 60*60*24 //24 hours
let transferUtility = AWSS3TransferUtility.default()
transferUtility.uploadUsingMultiPart(
  fileURL:fileUri,
  bucket: AWS_BUCKET_NAME,
  key: fileId,
  contentType: "video/mp4",
  expression: expression,
  completionHandler: completionHandler)
}

```
**Observed Behavior**
The upload task fails after 50 minutes, with the following error: 

`The operation couldn’t be completed. (NSURLErrorDomain error -1001.)`

**Expected Behavior**
The upload should continue even after 50 minutes, since the timeoutIntervalForResource was increased from the default of 50 minutes to 24 hours.

**Unique Configuration**
We are not using AWS Cognito credentials, but instead using static credentials, since we know that AWS cognito has the 50 minutes timeout issue.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSS3TransferUtility

**Environment(please complete the following information):**
 - SDK Version: 2.33.0
 - Dependency Manager: Cocoapods
 - Swift Version :  5.8.1 
 - Xcode Version: 14.3.1

**Device Information (please complete the following information):**
 - Device: iPhone 14 Pro Simulator, iPhone 14 Device
 - iOS Version: 13.0
 - Specific to simulators: No

**Comment by ruisebas** [comment]
Hi @TomRaz, thanks for opening this issue. We'll take a look and post a comment once we have an update.

**Comment by royjit** [comment]
Looks like you are using the default instance of AWSS3TransferUtility to set the `timeoutIntervalForResource`. Can you change that and use the instance that you have configured ? 
```swift
transferUtility.transferUtilityConfiguration.timeoutIntervalForResource = 60*60*24 //24 hours
```

**Comment by TomRaz** [comment]
> Looks like you are using the default instance of AWSS3TransferUtility to set the `timeoutIntervalForResource`. Can you change that and use the instance that you have configured ?
> 
> ```swift
> transferUtility.transferUtilityConfiguration.timeoutIntervalForResource = 60*60*24 //24 hours
> ```

@royjit It is already set to this instance, I didn't include that in the original post, edited it now:

```
let transferUtility = AWSS3TransferUtility.default()
AWSS3TransferUtility.default().transferUtilityConfiguration.timeoutIntervalForResource = 60*60*24 //24 hours
transferUtility.uploadUsingMultiPart(
  fileURL:fileUri,
  bucket: AWS_BUCKET_NAME,
  key: fileId,
  contentType: "video/mp4",
  expression: expression,
  completionHandler: completionHandler)
}

```

**Comment by royjit** [comment]
Thank you for the reply. Looking at the source code it looks like the timeout value is set only while initializing transferUtility - https://github.com/aws-amplify/aws-sdk-ios/blob/fc5b585c63b7260332b179d14bd3bd18df00bd3b/AWSS3/AWSS3TransferUtility.m#L283 , so any runtime change on this value might not have the desired effect. 

Will you be able to try creating an instance of transferUtility and passing the configuration?

```swift

        var transferUtilityConfiguration = AWSS3TransferUtilityConfiguration()
        transferUtilityConfiguration.timeoutIntervalForResource = 60*60*24
        AWSS3TransferUtility.register(with: serviceConfig, transferUtilityConfiguration: transferUtilityConfiguration, forKey: "key")
        let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "key")
        transferUtility.uploadUsingMultiPart(...)

```

**Comment by TomRaz** [comment]
@royjit Thank you, it worked!

**Comment by royjit** [comment]
@TomRaz Thank you for confirming, please reach us if you face any issues or have questions. Closing this issue.
