### ISSUE TITLE
AWS send the verify code to wrong email 'u***@y***' when call AWSMobileClient.default().forgotPassword.

### ISSUE THREAD

**Issue by linjiework** [aws-amplify/aws-sdk-ios#4837]
**State your question**
I call AWSMobileClient.default().forgotPassword() to reset the password, whatever the username(email) is used, AWS always return the same data ‘{"CodeDeliveryDetails":{"AttributeName":"email","DeliveryMedium":"EMAIL","Destination":"u***@y***"}}’.
There isn't the username(email) begin with 'u' in the Cognito User Pool. My AWS account is not begin with 'u'. I don't know who is "u***@y***".

Response headers:
{
    "Content-Length" = 100;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Fri, 14 Jul 2023 02:59:07 GMT";
    "x-amzn-requestid" = "90b2a2e2-edc8-404b-bb8b-87018d9c4597";
}
Response body:
{"CodeDeliveryDetails":{"AttributeName":"email","DeliveryMedium":"EMAIL","Destination":"u***@y***"}}

My APP can works with the function AWSMobileClient.default().signUp(), AWSMobileClient.default().signIn(), AWSMobileClient.default().signOut(), so the AWS configure of my APP is OK. 

**Which AWS Services are you utilizing?**
AWS Services is cognito-idp.ap-southeast-1.amazonaws.com

**Provide code snippets (if applicable)**

    public func userRequestResetPassword(username: String) {
        
        print("[userRequestResetPassword] Username:\(username).")
        
        AWSMobileClient.default().forgotPassword(username: "username") { (forgotPasswordResult, error) in
            
            var description: String = NSLocalizedString("Unknown Error!", comment: "comment");
            
            if let forgotPasswordResult = forgotPasswordResult {
                switch(forgotPasswordResult.forgotPasswordState) {
                case .confirmationCodeSent:
                    print("[userRequestResetPassword] Confirmation code sent via \(forgotPasswordResult.codeDeliveryDetails!.deliveryMedium) to: \(forgotPasswordResult.codeDeliveryDetails!.destination!)")
                    description = "";
                    self.gCommand = AwsUserAuthCommand.None;
                    self.notifySend(command: AwsUserAuthCommand.RequestResetPassword, result: AwsUserAuthResult.Success, description: description);
                    return
                default:
                    print("[userRequestResetPassword] Error: Invalid case.")
                    self.gCommand = AwsUserAuthCommand.None;
                    self.notifySend(command: AwsUserAuthCommand.RequestResetPassword, result: AwsUserAuthResult.Failed, description: description);
                    return;
                }
            } else if let error = error {
                print("[userRequestResetPassword] Error occurred: \(error.localizedDescription)")
                description = error.localizedDescription;
                self.gCommand = AwsUserAuthCommand.None;
                self.notifySend(command: AwsUserAuthCommand.RequestResetPassword, result: AwsUserAuthResult.Failed, description: description);
                return;
            }
        }
        gCommand = AwsUserAuthCommand.RequestResetPassword;
    }
       

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 aws-sdk-iOS/2.33.0
 - Dependency Manager: [e.g. Cocoapods, Carthage]
Swift Package Manager
 - Swift Version : [e.g. 4.0]
Swift 5
XCode Version 14.3 (14E222b)

**Device Information (please complete the following information):å**
 - Device: [e.g. iPhone6, Simulator]
 iPhone 13
 - iOS Version: [e.g. iOS 11.4]
 iOS/15.4
 - Specific to simulators:

**Comment by harsh62** [comment]
@linjiework Thanks for opening the issue. Would you be able to share the process of your sign up in more detail and what attributes are passed during sign up? Also if you could provide more details on how the user pool is setup in terms username? i.e. Do you have an alias set up in the user pool to login?

To help us debug further, would you be able to provide any of the following?
1. The logs you see in the console when the error happens. You can enable verbose logging to the console by doing this:

```
AWSDDLog.sharedInstance.logLevel = .verbose 
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```



2. The contents of your awsconfiguration.json file with sensitive information removed.

**Comment by harsh62** [comment]
@linjiework Following up on this. Would it be possible that you have the "Prevent user existence errors" setting enabled in your Cognito console? 

https://repost.aws/knowledge-center/cognito-prevent-user-existence-errors

> When the Prevent User Existence Errors setting is turned on and a user is deactivated, isn’t found, or can’t recover passwords, Amazon Cognito returns CodeDeliveryDetails. Code delivery details provide a simulated delivery medium for a user instead of returning the exception named UserNotFoundException. The simulated delivery medium is determined by the user name’s input format and the user pool’s recovery settings.

**Comment by linjiework** [comment]
@harsh62  Thank You for Your Reply!
I got the error message '{"__type":"UserNotFoundException","message":"Username/client id combination not found."}' after clear the Prevent user existence errors setting under Advanced security configurations in  App clients settings.

![settings](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/e4f8745b-2cfe-4832-88cc-dcd385aef104)

Follows are the full log:
[userRequestResetPassword] Username:linjiework@163.com.
2023-07-15 09:53:43:100 MouseTrap[94782:10465546] Request headers:
{
    "Content-Type" = "application/x-amz-json-1.1";
    Host = "cognito-idp.ap-southeast-1.amazonaws.com";
    "User-Agent" = "aws-sdk-iOS/2.33.0 iOS/15.4 zh_CN";
    "X-Amz-Date" = 20230715T015343Z;
    "X-Amz-Target" = "AWSCognitoIdentityProviderService.ForgotPassword";
}
2023-07-15 09:53:43:100 MouseTrap[94782:10465546] Request body:
{"UserContextData":{"EncodedData":"eyJwYXlsb2FkIjoie1widXNlcm5hbWVcIjpcInVzZXJuYW1lXCIsXCJjb250ZXh0RGF0YVwiOntcIkFwcGxpY2F0aW9uVmVyc2lvblwiOlwiMS4wLTFcIixcIlBob25lVHlwZVwiOlwiaVBob25lMTQsNVwiLFwiRGV2aWNlSWRcIjpcImZjOWUzOGNlLWFlZjktNDc4MS1iZmE3LTU4YjdiYmIxZjVhN1wiLFwiU2NyZWVuV2lkdGhQaXhlbHNcIjpcIjExNzBcIixcIlBsYXRmb3JtXCI6XCJpT1NcIixcIlNjcmVlbkhlaWdodFBpeGVsc1wiOlwiMjUzMlwiLFwiQXBwbGljYXRpb25UYXJnZXRTZGtcIjpcIjkwMDAwXCIsXCJBcHBsaWNhdGlvbk5hbWVcIjpcImNuLmxpbmppZXN0dWRpby5Nb3VzZVRyYXBcIixcIkRldmljZU9zUmVsZWFzZVZlcnNpb25cIjpcIjE1LjRcIixcIkRldmljZUZpbmdlcnByaW50XCI6XCJBcHBsZVxcXC9pUGhvbmVcXFwvaVBob25lMTQsNVxcXC8tOjE1LjRcXFwvLVxcXC8tOi1cXFwvcmVsZWFzZVwiLFwiVGhpcmRQYXJ0eURldmljZUlkXCI6XCJDNDZCMUVCMS05Mzc3LTREMDItODA5My0yQjMwMTI0MjdCQzBcIixcIkRldmljZUxhbmd1YWdlXCI6XCJ6aC1IYW5zXCIsXCJDbGllbnRUaW1lem9uZVwiOlwiKzA4OjAwXCIsXCJCdWlsZFR5cGVcIjpcInJlbGVhc2VcIixcIkRldmljZU5hbWVcIjpcIkxcIn0sXCJ1c2VyUG9vbElkXCI6XCJhcC1zb3V0aGVhc3QtMV82dEEyWEpQb1ZcIixcInRpbWVzdGFtcFwiOlwiMTY4OTM4NjAyMzA4M1wifSIsInZlcnNpb24iOiJJT1MyMDE3MTExNCIsInNpZ25hdHVyZSI6InRDQUxxQXBZQ3RlVnIrSGxVajdkb3hRZEpSMHJwd25KWUlXeXJmcVhwdEU9In0="},"ClientMetadata":{},"Username":"username","SecretHash":"xZyLk6UTBa34jS8iOSp8DUuGvi2JKh\/Z2+fCbNCnSNM=","ClientId":"6f22qs6huij6ni28068a9n5um8"}
2023-07-15 09:53:45:997 MouseTrap[94782:10466102] Response headers:
{
    "Content-Length" = 88;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Sat, 15 Jul 2023 01:53:45 GMT";
    "x-amzn-errormessage" = "Username/client id combination not found.";
    "x-amzn-errortype" = "UserNotFoundException:";
    "x-amzn-requestid" = "8a2e85d9-ad72-40cc-ad6f-8c8af49cc754";
}
2023-07-15 09:53:45:997 MouseTrap[94782:10466102] Response body:
{"__type":"UserNotFoundException","message":"Username/client id combination not found."}

I can ensure that the username exists. And I can sigin with this username, using the function AWSMobileClient.default().signIn(username: username, password: password).

![image](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/005bba0e-4e46-4c48-a5a9-d6f8b4d3729f)

My sigup code:
`
        AWSMobileClient.default().signUp(username: username, password: password) { (signUpResult, error) in
            
            var result: AwsUserAuthResult = .Failed;
            var description: String = NSLocalizedString("Unknown Error!", comment: "comment");
            
            if let signUpResult = signUpResult {
                switch(signUpResult.signUpConfirmationState) {
                case .confirmed:
                    print("[userSignUp] User is signed up and confirmed.")
                    result = .UsernameExist;
                    description = NSLocalizedString("A user with this email already exists.", comment: "comment");
                    break;
                case .unconfirmed:
                    print("[userSignUp] User is not confirmed and needs verification via \(signUpResult.codeDeliveryDetails!.deliveryMedium) sent at \(signUpResult.codeDeliveryDetails!.destination!)")
                    result = .UserNotConfirmed;
                    description = NSLocalizedString("A user with this email already exist! Do you want to resend verification Email?", comment: "comment");
                    break;
                case .unknown:
                    print("[userSignUp] Unknown case")
                    result = .Failed;
                    break;
                default:
                    print("[userSignUp] Unexpected case")
                    result = .Failed;
                    break;
                }
                self.gCommand = AwsUserAuthCommand.None;
                self.notifySend(command: AwsUserAuthCommand.SignUp, result: result, description: description);
                return;
                
            } else if let error = error {
                if let error = error as? AWSMobileClientError {
                    switch(error) {
                    case .usernameExists(let message):
                        print("[userSignUp] message:\(message).")
                        result = .UsernameExist;
                        description = NSLocalizedString("A user with this email already exists.", comment: "comment");
                        break;
                    default:
                        result = .Failed;
                        break
                    }
                }
                print("[userSignUp] Description:\(error.localizedDescription).")
                self.gCommand = AwsUserAuthCommand.None;
                self.notifySend(command: AwsUserAuthCommand.SignUp, result: result, description: description);
                return;
            }
            
            self.gCommand = AwsUserAuthCommand.None;
            self.notifySend(command: AwsUserAuthCommand.SignUp, result: AwsUserAuthResult.Success, description: description);
        }
`

My awsconfiguration.json:
{
    "Version": "1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "ap-southeast-1:43b3dc96-fbb4-****-****-***********”,
                "Region": "ap-southeast-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "ap-southeast-1_6t********”,
            "AppClientId": "6f22qs6h**************”,            
            "AppClientSecret": "6ooqeaneg*”************************,
            "Region": "ap-southeast-1"
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "socialProviders": [],
            "usernameAttributes": [
                "EMAIL"
            ],
            "signupAttributes": [
                "EMAIL"
            ],
            "passwordProtectionSettings": {
                "passwordPolicyMinLength": 8,
                "passwordPolicyCharacters": []
            },
            "mfaConfiguration": "OFF",
            "mfaTypes": [
                "SMS"
            ],
            "verificationMechanisms": [
                "EMAIL"
            ]
        }
    },
    "PinpointAnalytics": {
        "Default": {
            "AppId": "690827006b*************”,
            "Region": "ap-southeast-1"
        }
    },
    "PinpointTargeting": {
        "Default": {
            "Region": "ap-southeast-1"
        }
    },
    "AppSync": {
        "Default": {
            "ApiUrl": "https://lyyluagffzcr3omaokahbl3tge.appsync-api.ap-southeast-1.amazonaws.com/graphql",
            "Region": "ap-southeast-1",
            "AuthMode": "API_KEY",
            "ApiKey": "da2-erzb*************”,
            "ClientDatabasePrefix": "mousetrapios_API_KEY"
        }
    }
}


Summary:
1. I user the email as username.
2. The username exists in the User pools.
3. The username can work with the function AWSMobileClient.default().signIn(), but cannot work with the function AWSMobileClient.default().forgotPassword().
4. My Android APP which using the Amplify libraries can work on the same User pools. My Android APP hasn't encountered this problem.

This problem is very strange, I don't know where the problem occurred

**Comment by linjiework** [comment]
> @linjiework Thanks for opening the issue. Would you be able to share the process of your sign up in more detail and what attributes are passed during sign up? Also if you could provide more details on how the user pool is setup in terms username? i.e. Do you have an alias set up in the user pool to login?
> 
> To help us debug further, would you be able to provide any of the following?
> 
> 1. The logs you see in the console when the error happens. You can enable verbose logging to the console by doing this:
> 
> ```
> AWSDDLog.sharedInstance.logLevel = .verbose 
> AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
> ```
> 
> 2. The contents of your awsconfiguration.json file with sensitive information removed.

Is the information I have provided sufficient? What additional information needs to be provided?

**Comment by harsh62** [comment]
@linjiework I am currently working on trying to recreate this issue in my local environment. If you could provide how the user pool was set up for 

 if you could provide more details on how the user pool is setup (i.e. do you have an alias username set to email)? Any other special set up that has been done in  the user pools would also help.

**Comment by linjiework** [comment]
> @linjiework I am currently working on trying to recreate this issue in my local environment.
> 
> > if you could provide more details on how the user pool is setup (i.e. do you have an alias username set to email)? Any other special set up that has been done in  the user pools would also help.

Follows are the accouns settings in the user pool and the settings of user pool.

![account_setting](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/da2a825e-a0bf-435a-a15f-eb912896a8cf)

![setting1](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/858331ac-67ff-4396-bbb1-6397e1727a28)

![setting2](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/fec59e18-1367-4b35-aa46-5fa5c54b833c)

![setting3](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/175cd051-42b1-4c5a-8e6d-6ae913cc1fa8)

![setting4](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/9351dcdc-81da-4423-b52d-8cc2b663d2ff)

![setting5](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/1edd805f-4e0a-4560-895b-b6c723296d11)

![setting6](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/df56853d-27a6-49d9-a4e5-83126edf964d)

![setting7](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/d790554e-a707-4bf6-b11e-9932b8c629d2)

**Comment by harsh62** [comment]
@linjiework Thanks for all the information.. I will work on this today and try to provide an update on it as soon as I can.

**Comment by harsh62** [comment]
@linjiework 

I just realized that you are passing the username in the API as a string in quotes, whereas you should be using the parameter. of the method.

So instead of 
```
AWSMobileClient.default().forgotPassword(username: "username")
```
You should be doing 
```
AWSMobileClient.default().forgotPassword(username: username)
```

Similar to how you printing the username in the print statement
```
print("[userRequestResetPassword] Username:\(username).")
```

**Comment by linjiework** [comment]
> @linjiework
> 
> I just realized that you are passing the username in the API as a string in quotes, whereas you should be using the parameter. of the method.
> 
> So instead of
> 
> ```
> AWSMobileClient.default().forgotPassword(username: "username")
> ```
> 
> You should be doing
> 
> ```
> AWSMobileClient.default().forgotPassword(username: username)
> ```
> 
> Similar to how you printing the username in the print statement
> 
> ```
> print("[userRequestResetPassword] Username:\(username).")
> ```

I'm very sorry, I made such a stupid mistakes. The problem has been resolved. Thank you very much for your help!
