### ISSUE TITLE
Crash in -[AWSS3ChunkedEncodingInputStream nextChunk]

### ISSUE THREAD

**Issue by Yuan91** [aws-amplify/aws-sdk-ios#4849]
**Describe the bug**
A clear and concise description of what the bug is. Please be as detailed as possible and help us help you.
When I use aws sdk to upload file which its **size higher than 10M**, a crash occured. It **appears frequently on the iPhone 6sp**, but is less common on models higher than the iPhone 6sp.

**Screenshots**
![image](https://github.com/aws-amplify/aws-sdk-ios/assets/13419348/bd1bb490-ea41-4694-9ea2-262f05a90d66)

**Device Information (please complete the following information):**
 - Device: [ iPhone 6sp]
 - iOS Version: [ iOS 11.4]

**Comment by harsh62** [comment]
@Yuan91 

Is there any other information you can provide for the crash? 
Symbolicated crash, verbose logging?

It would definitely help us further investigate the issue.
