### ISSUE TITLE
ios aws s3 NotImplemented

### ISSUE THREAD

**Issue by LDRHeart** [aws-amplify/aws-sdk-ios#4875]
```objective-c
   AWSBasicSessionCredentialsProvider *credentialsProvider = [[AWSBasicSessionCredentialsProvider alloc] initWithAccessKey:@"****" secretKey:@"****" sessionToken:@"****"];
    
    //2.
    AWSEndpoint *minioEndpoint = [[AWSEndpoint alloc] initWithURL:[NSURL URLWithString:@"https://xxxxx.cn"]];
    //3.
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1
            endpoint:minioEndpoint
            credentialsProvider:credentialsProvider
            localTestingEnabled:YES];
    configuration.maxRetryCount = 500;
    configuration.URLString = @"https://vargobox.cn";
//    configuration.headers = @{@"":@""};
    //4.
    [AWSS3 registerS3WithConfiguration:configuration forKey:@"USWest2S3"];
        
    //数据
    NSData *originData = UIImageJPEGRepresentation([UIImage imageNamed:@"login_background"], 0.5);

    AWSS3 *S3 = [AWSS3 S3ForKey:@"USWest2S3"];

    NSString *fileName= @"123.jpg";
    NSURL *fileURL= [NSURL fileURLWithPath:[NSTemporaryDirectory() stringByAppendingPathComponent:fileName]];
    NSError *error = nil;
    [originData writeToURL:fileURL options:NSDataWritingAtomic error:&error];

    AWSS3PutObjectRequest *request = [[AWSS3PutObjectRequest alloc] init];
    request.bucket = @"xxxx-bucket";
    request.key = fileName;
    request.contentType = @"image/jpeg";
    request.ACL = AWSS3ObjectCannedACLPublicRead;
    request.body = fileURL;
    request.contentLength = [NSNumber numberWithUnsignedInteger:[originData length]];
    [S3 putObject:request completionHandler:^(AWSS3PutObjectOutput * _Nullable response, NSError * _Nullable error) {
  
        
        NSLog(@"====%@",error);
        if (!error) {
            NSLog(@"suc");
        }else{
            NSLog(@"error");
        }
    }];
```

```bash
Error Domain=com.amazonaws.AWSS3ErrorDomain Code=0 "(null)" UserInfo={HostId=ad1c-test-zone-test-default, ResponseObjectError={
    Code = NotImplemented;
    HostId = "ad1c-test-zone-test-default";
    RequestId = "tx00000b9d8f5233e2ad295-0064c8799c-ad1c-test-zone";
}, Code=NotImplemented, RequestId=tx00000b9d8f5233e2ad295-0064c8799c-ad1c-test-zone}
```

**Comment by LDRHeart** [comment]
sdk  AWSS3 2.27.10

**Comment by buyinanhai** [comment]
我用request的方式更离谱 bucket直接拼接到顶级域名上去了 导致连接不到服务器
用AWSS3TransferUtility的方式上传就是 没有回调 也不报错 我服了！！

**Comment by ruisebas** [comment]
Thanks for opening this issue. The team will investigate and get back to you as soon as we have more information.

**Comment by ruisebas** [comment]
Hi @LDRHeart, I was not able to reproduce this issue.

The `NotImplemented` error you are getting is coming directly from the AWS S3 Service and not being handled by this SDK, we're just passing back the error to you. [The documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList) just states that:
> NotImplemented: A header that you provided implies functionality that is not implemented.

Looking at your code, it seems you are attempting to store your data in a third-party provider:
```objective-c
    configuration.URLString = @"https://vargobox.cn";
```

**Comment by ruisebas** [comment]
Hi @LDRHeart, I was not able to reproduce this issue.

The `NotImplemented` error you are getting is coming directly from the AWS S3 Service and not being handled by this SDK, we're just passing back the error to you. [The documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList) just states that:
> NotImplemented: A header that you provided implies functionality that is not implemented.

Looking at your code, it seems you are attempting to store your data in a third-party provider:
```objective-c
    configuration.URLString = @"https://vargobox.cn";
```
Setting this value will attempt to upload to `<bucket>.<URLString>/<key>`. 

If this is the case, then I suspect there might be a configuration issue with that integration in your end that is causing the service to reject to request.
