### ISSUE TITLE
AWSIoT connectViaWebsocket Error: "TCP Conn Failed : error 0:-65554"

### ISSUE THREAD

**Issue by linjiework** [aws-amplify/aws-sdk-ios#4920]
****State your question**
I try to use AWSIoT to connect the IoT server. But failed. My code is copy from the IoT-Sample in aws-sdk-ios-samples. 
The endpoint can work in my Android APP, so the endpoint should be ok.
My iOS APP can work with AWSDynamoDB and AWSLambda, so the aws configure of my iOS APP should be ok.
I don't know where the problem occurred. 

Follows are the full log(I have set AWSDDLog.sharedInstance.logLevel = .verbose):
```bash
[AwsIoT][connectViaWebsocket] Enter.
IOTDataManager: Connecting to IoT using websocket, client id: B1109CB3-4E63-42A2-8055-4FC6C25C3520
AWSIoTMQTTClient: connecting via websocket. 
Using AWSCredentials.
user metadata is : ?SDK=iOS&Version=2.33.0
Metrics collection is: Enabled
-[AWSMQTTSession initWithClientId:userName:password:keepAlive:cleanSession:willTopic:willMsg:willQoS:willRetainFlag:publishRetryThrottle:] [Line 84], Thread:<_NSMainThread: 0x2817fc8c0>{number = 1, name = main} 
+[AWSMQTTMessage connectMessageWithClientId:userName:password:keepAlive:cleanSession:willTopic:willMsg:willQoS:willRetain:] [Line 66], Thread:<_NSMainThread: 0x2817fc8c0>{number = 1, name = main} 
Creating AWSMQTTMessage with raw data >>>>> {length = 73, bytes = 0x00044d51 54540482 012c0024 42313130 ... 6e3d322e 33332e30 } <<<<<
Websocket is created and opened.
[connection] nw_connection_get_connected_socket [C1] Client called nw_connection_get_connected_socket on unconnected nw_connection
TCP Conn 0x2835fba70 Failed : error 0:-65554 [-65554]
[SR] NSStreamEventErrorOccurred <__NSCFOutputStream: 0x2830e6250> Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={_kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, kCFGetAddrInfoFailureKey=8}
[SR] NSStreamEventErrorOccurred <__NSCFInputStream: 0x2830e5f80> Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={_kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, kCFGetAddrInfoFailureKey=8}
[SR] using _delegateDispatchQueue.
didFailWithError: Websocket failed With Error Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={_kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, kCFGetAddrInfoFailureKey=8}
[SR] Failing with error The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 2.)
[SR] Trying to disconnect
```

**Which AWS Services are you utilizing?**
ap-southeast-1.amazonaws.com

**Provide code snippets (if applicable)**
```swift
    static let AWS_IDENTITY_POOL_ID = "ap-southeast-1:43b3dc96–****-49bc-****-********”;
    static let CUSTOMER_SPECIFIC_ENDPOINT = “******-ats.iot.ap-southeast-1.amazonaws.com";    
    static let AWS_IOT_POLICY_NAME = "MOUSETRAP";

    static let AWS_IOT_DATA_MANAGER_KEY = "MouseTrapIotDataManager"
    static let AWS_IOT_MANAGER_KEY = "MouseTrapIotManager"
    
    var iotDataManager: AWSIoTDataManager!
    var iotManager: AWSIoTManager!
    var iot: AWSIoT!
    

	init() {
	
		let credentialsProvider = AWSCognitoCredentialsProvider(regionType:AWS_REGION, identityPoolId:AWS_IDENTITY_POOL_ID);
        
        iotManager = AWSIoTManager.default()
        iot = AWSIoT.default()
        
        // IoT Dataplane must use your account specific IoT endpoint
        let iotEndPoint = AWSEndpoint(urlString: AwsIoT.CUSTOMER_SPECIFIC_ENDPOINT)
        
        // Configuration for AWSIoT data plane APIs
        let iotDataConfiguration = AWSServiceConfiguration(region: Aws.AWS_REGION,
                                                           endpoint: iotEndPoint,
                                                           credentialsProvider: credentialsProvider)
        //IoTData manager operates on xxxxxxx-iot.<region>.amazonaws.com
        AWSIoTDataManager.register(with: iotDataConfiguration!, forKey: AwsIoT.AWS_IOT_DATA_MANAGER_KEY)
        iotDataManager = AWSIoTDataManager(forKey: AwsIoT.AWS_IOT_DATA_MANAGER_KEY)
	}


    func connectViaWebsocket() {
        
        print("[AwsIoT][connectViaWebsocket] Enter.");
        
        let uuid = UUID().uuidString
        // Connect to the AWS IoT data plane service over websocket
        iotDataManager.connectUsingWebSocket(withClientId: uuid, cleanSession: true, statusCallback: mqttEventCallbackWebsocket(_:))
    }
    

    private func mqttEventCallbackWebsocket(_ status: AWSIoTMQTTStatus) {
        guard case .connected = status else {
            mqttEventCallback(status)
            return
        }
        // connected
        print("[AwsIoT][mqttEventCallbackWebsocket] Connected via websocket.");
    }
    
    
    private func mqttEventCallback( _ status: AWSIoTMQTTStatus ) {
        DispatchQueue.main.async {
            print("[AwsIoT][mqttEventCallback] Connection status = \(status.rawValue)")

            switch status {
            case .connecting:
                print( "[AwsIoT][mqttEventCallback] Connecting..." )
                
            case .connected:
                print( "[AwsIoT][mqttEventCallback] Connected" )
                let uuid = UUID().uuidString;
                let defaults = UserDefaults.standard
                let certificateId = defaults.string( forKey: "certificateId")
                print( "[AwsIoT][mqttEventCallback] Using certificate:\n\(certificateId!)\n\n\nClient ID:\n\(uuid)")
                
            case .disconnected:
                print( "[AwsIoT][mqttEventCallback] Disconnected" )
                
            case .connectionRefused:
                print( "[AwsIoT][mqttEventCallback] Connection Refused" )
                
            case .connectionError:
                print( "[AwsIoT][mqttEventCallback] Connection Error" )
                
            case .protocolError:
                print( "[AwsIoT][mqttEventCallback] Protocol Error" )
                
            default:
                print( "[AwsIoT][mqttEventCallback] Unknown State" )
            }
        }
    }
```

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 aws-sdk-iOS/2.33.0
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 Swift Package Manager
 - Swift Version : [e.g. 4.0]
 Swift 5
XCode Version 14.3 (14E222b)

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
iPhone 13
 - iOS Version: [e.g. iOS 11.4]
iOS/15.4
 - Specific to simulators:

**Comment by ruisebas** [comment]
Thanks for opening this issue. The team will investigate and get back to you as soon as we have more information.

**Comment by linjiework** [comment]
How to solve this problem? Do you have any suggestions?

**Comment by linjiework** [comment]
I have solved this issue. And there is a new issue after connected to the IoT endpoint. 

I got the error message 'Received close frame' and 'Closing with code 1000 reason (null)'. There is no reason for the error. I don't know where has problem. 

BTW: I found there are two parameters AWS_IOT_DATA_MANAGER_KEY and AWS_IOT_MANAGER_KEY in the file Constants.swift in aws-sdk-ios-samples' IoTSampleSwift project. In AWS Android SDK, these two parameters are not required. so I don't know how to set it.


Follows are full error message:

Websocket did open and is connected.
Issued Cancel on thread [<NSThread: 0x281a317c0>{number = 14, name = (null)}]
<<<NSThread: 0x281a3c900>{number = 18, name = (null)}>> Initializing MQTTEncoder and MQTTDecoder streams
opening encoder stream.
opening decoder stream.
-[AWSMQTTEncoder stream:handleEvent:] [Line 59] EventCode:1, Thread: <NSThread: 0x281a3c900>{number = 18, name = (null)}
-[AWSMQTTEncoder stream:handleEvent:] [Line 59] EventCode:4, Thread: <NSThread: 0x281a3c900>{number = 18, name = (null)}
MQTTEncoderStatus = 0
-[AWSMQTTSession encoder:handleEvent:] [Line 335], eventCode: 0
MQTTSessionStatus = 0
sending 75 bytes
-[AWSMQTTDecoder stream:handleEvent:] [Line 63] EventCode:1, status:0, stream: <__NSCFInputStream: 0x283d74090>, Thread: <NSThread: 0x281a3c900>{number = 18, name = (null)}
[SR] NSStreamEventHasSpaceAvailable <__NSCFOutputStream: 0x283d70510>
[SR] NSStreamEventHasBytesAvailable <__NSCFInputStream: 0x283d703f0>
[SR] Received close frame
[SR] Closing with code 1000 reason (null)
[SR] Trying to disconnect
[SR] using _delegateDispatchQueue.
[SR] NSStreamEventHasBytesAvailable <__NSCFInputStream: 0x283d703f0>
[SR] NSStreamEventHasSpaceAvailable <__NSCFOutputStream: 0x283d70510>
WebSocket closed with code:1005 with reason:(null)
Connection status = 5
Connection Error

**Comment by phantumcode** [comment]
@linjiework Thanks for submitting the issue.  If you are basing your app from the IOT sample app, can you verify that you have the certificate details set in your code?  These are all the values required for the sample app to work in Constants.swift https://github.com/awslabs/aws-sdk-ios-samples/blob/main/IoT-Sample/Swift/IoTSampleSwift/Constants.swift

**Comment by linjiework** [comment]
@phantumcode Thank you very mush. I built the certificate file (.p12) and add it into the project, then IoT works. This issue has been solved.
