### ISSUE TITLE
AWSIoTDataManager Not able to connect. status is unknown

### ISSUE THREAD

**Issue by Praphin** [aws-amplify/aws-sdk-ios#4934]
**Describe the bug**
AWSIoTDataManager not getting connected on iOS 17 devices. I am calling `AWSIoTDataManager.connect(withClientId. statusCallback is not received even after waiting. 

When manually check status of AWSIoTMQTTStatus it was unknown

**Environment(please complete the following information):**
 - SDK Version: 2.33.4
 - Dependency Manager: SPM
 - Swift Version : Swift 5
 - Xcode Version: Xcode 15.0 beta 7

**Device Information (please complete the following information):**
 - Device: iPhone XS, iPhone 14 Pro Max
 - iOS Version: iOS 17

Logger output
2023-08-30 12:34:23:974 XX_APP[1183:150181] getIdentityRef error: -25300
2023-08-30 12:34:23:974 XX_APP[1183:150181] Could not find SecIdentityRef

**Comment by ruisebas** [comment]
I was unable to reproduce this in Xcode 15 RC, the connection was successful. 

Based on your logs:
```bash
2023-08-30 12:34:23:974 XX_APP[1183:150181] getIdentityRef error: -25300
2023-08-30 12:34:23:974 XX_APP[1183:150181] Could not find SecIdentityRef
```
Your connection is not successful due to error `25300`, which is `errSecItemNotFound`. Please double check you are providing the correct `certificateId`, and that it is stored in the Keychain.

**Comment by PrakharParakh** [comment]
The issue persists, and while I am able to connect with an iOS 18 device, the connection status remains undefined for iOS 17 devices.
