### ISSUE TITLE
wifi connected, but without internet.  Won't use mobile data.

### ISSUE THREAD

**Issue by camhart** [aws-amplify/aws-sdk-ios#4947]
**Describe the bug**
I'm trying to upload files via mobile data using AWSS3TransferUtility while the device has a wifi connection that doesn't have access to the internet.  I am setting AllowsCellularAccess to yes/true in the AWSServiceConfiguration, however changing that value doesn't appear to make a difference.

**To Reproduce**
1.  Connect to wifi network that doesn't have internet
2.  Make sure you still have a mobile connection
3. Try to upload using multi-part upload

**Observed Behavior**
```
Error Domain=NMSURLErrorDomain Code=-1009 \"The Internet connection appears to be offline.\"
```

**Expected Behavior**
The upload should work via mobile data.

**Environment(please complete the following information):**
 - SDK Version: latest as of 9/12/2023, not sure how to identify
 - Dependency Manager: coacoapods
 - Swift Version : Objective C
 - Xcode Version: 14.3.1

**Device Information (please complete the following information):**
 - Device: iphone se 2020
 - iOS Version: 16.6

**Comment by lawmicha** [comment]
Hi @camhart, 

I can see in the initializer code for TransferUtility, the configuration passed to the NSURLSEssion contains  `allowsCellularAccess` property, set from the AWSServiceConfiguration ([code](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSS3/AWSS3TransferUtility.m#L282)). According to https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1409406-allowscellularaccess the value is True by default, so you wouldn't even need to be setting it. 

Are you able to provide additional details such as how you are initializing TransferUtility and more logs related to the entire execution of the multi-part upload API call?
