### ISSUE TITLE
Libraries collision AWS Iot and React Native

### ISSUE THREAD

**Issue by salitbl** [aws-amplify/aws-sdk-ios#4956]
**Libraries collision AWS Iot and React Native**
I am trying to developing an App with React Native and with private native SDK that use AWSIoT.
When I am trying to run this project, the build is failed duo to 12 duplicate codes in classes For example: 
❌  duplicate symbol '_OBJC_IVAR_$_SRIOConsumer._scanner' in
┌─ libAWSIoT.a(AWSSRWebSocket.o)
└─ libSocketRocket.a(SRIOConsumer.o)

 duplicate symbol '_OBJC_CLASS_$_SRIOConsumerPool' in
┌─ libAWSIoT.a(AWSSRWebSocket.o)
└─ libSocketRocket.a(SRIOConsumerPool.o)

❌  duplicate symbol '_SRHTTPResponseErrorKey' in
┌─ libAWSIoT.a(AWSSRWebSocket.o)
└─ libSocketRocket.a(SRWebSocket.o)

AWSSRWebSocket include @interface SRIOConsumer and SocketRocket also has @interface SRIOConsumer Do you have any idea how to resolve this issue?

**Which AWS Services are you utilizing?** - AWSIoT

**Environment**
 - AWSIoT 2.33.4
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0
 - react:  18.2.0
 - react-native:  0.72.3

**Device Information**
 - Device: iPhone 12
 - iOS Version: 16.6.1

**Comment by ruisebas** [comment]
Thanks for opening this @salitbl ! The team will take a look and post any updates here.

**Comment by salitbl** [comment]
@ruisebas 
Thank you!!!
Then the fix will release?
Can I test it before releasing this fix?

ם

**Comment by ruisebas** [comment]
@salitbl sorry for the delay, this change will be released in the next couple of days. 

If you want to test it, you can target the `main` branch.

**Comment by salitbl** [comment]
@ruisebas 
 I added the AWSIoT main branch, It was with the new renaming.
 When I tried to run iOS project with React native - the project crashed.
 Do you know why it crashed?

**Comment by ruisebas** [comment]
No, I don't know why it would crash with React native. 

Could you share the full symbolicated crashlog? That might give us a hint of what's wrong.

**Comment by salitbl** [comment]
This is the error:

dyld`:
    0x1a9b57fc4 <+0>:  mov    x16, #0x209
    0x1a9b57fc8 <+4>:  svc    #0x80
->  0x1a9b57fcc <+8>:  b.lo   0x1a9b57fec               ; <+40>
    0x1a9b57fd0 <+12>: pacibsp 
    0x1a9b57fd4 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1a9b57fd8 <+20>: mov    x29, sp
    0x1a9b57fdc <+24>: bl     0x1a9af3750               ; cerror_nocancel
    0x1a9b57fe0 <+28>: mov    sp, x29
    0x1a9b57fe4 <+32>: ldp    x29, x30, [sp], #0x10
    0x1a9b57fe8 <+36>: retab  
    0x1a9b57fec <+40>: ret    



<img width="1792" alt="Screenshot 2023-11-02 at 15 56 30" src="https://github.com/aws-amplify/aws-sdk-ios/assets/82137437/449a8e6b-8dc1-42ca-a40c-a47e2f5a7c09">

**Comment by ruisebas** [comment]
That is not helpful, and it doesn't reference anything within the `AWSIoT` pod.
Please grab the full crashlog from the device and share it, you can read how to do it [here](https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs#Create-a-crash-report-while-debugging).

In the meantime, I have some follow up questions:
- Does it only happen on a device? Or does it also crash when running in the simulator?
- Have you tried cleaning up the Build Folder and wiping the DerivedData folder?
- Is using the `main` branch the only thing that's changed in the Podfile?

**Comment by salitbl** [comment]
@ruisebas 
Thank you!!!
In the past week I succeed to add main branch to test project, but I have a complex project.
I am trying to add Framework that use AWSIoT, AWSCore, AWSDynamoDB, AWSS3 to react native project.
When I am adding the Framework, the project compilation is failed. 
when you will release this fix? I think this is my way to run my project.

**Comment by ruisebas** [comment]
Hi @salitbl. We held the release due to the crash you reported, and we were waiting to hear back from you.
Just so we're on the same page, you're saying that due to the complexity of your project it seems that it's not easy/reliable for you to use the main branch, so releasing might be the only way for you.

If that's the case, then we will release a new version next week.

**Comment by salitbl** [comment]
@ruisebas 
Thank you.
Yes, I think that when you will releasing those changes it will resolve the crash. 
I will let you know :)

**Comment by salitbl** [comment]
@ruisebas
Hi,
Do you have any update when those changes will be releasing ?
Thank you

**Comment by ruisebas** [comment]
Hi @salitbl.

Sorry for the delay, version [2.33.5](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.33.5) was released yesterday.

Please try it out and let us know if it fixes your issue

**Comment by salitbl** [comment]
@ruisebas 
My app is running 🎉 🎉 🎉
Thank you very much!
