### ISSUE TITLE
iOS 17 New required reason API

### ISSUE THREAD

**Issue by lakshmankreditbee** [aws-amplify/aws-sdk-ios#4977]
From Apple's newly published document ["Describing use of required reason API"](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api):

> Your app or third-party SDK must declare one or more approved reasons that accurately reflect your use of each of these APIs and the data derived from their use. You may use these APIs and the data derived from their use for the declared reasons only. These declared reasons must be consistent with your app’s functionality as presented to users, and you may not use the APIs or derived data for tracking.

Will aws-sdk be either removing the use of these APIs or providing a privacy manifest file for the iOS SDK? Or perhaps are you in contact with Apple about this issue?

**Comment by atierian** [comment]
Quick update - we're prioritizing this work and will update here with any news. Thanks for your patience.

**Comment by lakshmankreditbee** [comment]
Hi, when can we expect an update regarding this issue?

**Comment by mejim707** [comment]
Hello all, I hope you're doing well. I'm reaching out to see if we have an update on availability of the Privacy Manifest. I believe Apple has the deadline set to April 29 this sprint and they will begin rejecting all submissions at that point if they don't include SDKs with this change. 

Thank you for all of the efforts to get this change in place!

**Comment by lawmicha** [comment]
Hello, I'm working on the privacy manifest and have a draft PR in https://github.com/aws-amplify/aws-sdk-ios/pull/5214 

I'm looking into the required use APIs and at first pass, AWSLocation and AWSPinpoint uses UserDefaults, while AWSCore provides a filelogger that uses some of the [File timestamp APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc)

**Comment by liumoshi** [comment]
Hello, I am currently working on the privacy manifest mappings for all third-party libraries, and I noticed that you submitted the corresponding code in PR #5214. When do you plan to release the code to a pod-able version, and approximately when would that be?

**Comment by harshil-vyas08** [comment]
Hello, I also Hoping for the privacy manifest file in the new release as soon as possible.

**Comment by lawmicha** [comment]
I've kicked off the release for 2.34.1 with the privacy manifest changes, will keep this updated once it is finished

**Comment by lawmicha** [comment]
This has been released in 2.34.2 https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.34.2 please let us know if you have any problems with it
