### ISSUE TITLE
AWSMobileClient doesn't work with new swift

### ISSUE THREAD

**Issue by Li11leprince** [aws-amplify/aws-sdk-ios#5007]
**Which AWS Services is the feature request for?**
I wanna use AWSModileClient for user authorization (Sign in with Apple) but when I injected the library to my project I got the next problem:
`Failed to build module 'AWSMobileClientXCF'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.`
Can you please rebuild the project to the actual swift version?

**Comment by atierian** [comment]
Thanks for reporting this @Li11leprince. We'll provide updates here.

**Comment by atierian** [comment]
@Li11leprince how are you consuming `AWSMobileClient` - are you using SPM, CocoaPods, Carthage?

**Comment by Li11leprince** [comment]
@atierian I have tried two ways: SPM and installed as a binary XCFramework. The same issue
