### ISSUE TITLE
how to setup path-style requests with S3 custom endpoint? 

### ISSUE THREAD

**Issue by hradec** [aws-amplify/aws-sdk-ios#5023]
I'm trying to upload data to a custom endpoint S3 bucket using AWSS3TransferUtility.s3TransferUtility(), but the requests are being done using virtual-hosted–style (http://bucketname.mydomain.com) instead of path-style. (http://mydomain.com/bucketname)
Because aws-sdk-ios-spm always try to connect using virtual-hosted-style, my custom S3 bucket never receives a connection request, since it doesn't support virtual-hosted-style. 

**Is there a way to force it to use path-style requests?**
[amplify-swift seems to have support for that](https://github.com/aws-amplify/amplify-swift/blob/efc0061254a3930cb20942c0268811568b6222e5/AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/S3ClientConfigurationProtocol%2BEndpoint.swift#L16), but I couldn't find the same in aws-sdk-ios-spm. 

**Which AWS Services are you utilizing?**
S3, but with a custom endpoint that doesn't support virtual-hosted-style. (using s3ninja as a custom local setup)

**Environment(please complete the following information):**
 - SDK Version: 2.33.1
 - Dependency Manager: XCode Swift Package Manager
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 11 / iPhone 12 / iPad Pro 3rd gen 
 - iOS Version: 14.0
 - Specific to simulators: N/A

**Comment by thisisabhash** [comment]
Thank you for posting this. We'll investigate this and post an update here.

**Comment by ruisebas** [comment]
This is currently not supported by the SDK, so marking it as a feature request

**Comment by ruisebas** [comment]
This feature has been added in [2.33.10](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.33.10).

To to use path-style, you can do this:

```swift
let name = //...
let serviceConfiguration = //...
let transferUtilityConfiguration = AWSS3TransferUtilityConfiguration()
transferUtilityConfiguration.preferredAccessStyle = .path

AWSS3TransferUtility.register(
    with: serviceConfiguration,
    transferUtilityConfiguration: transferUtilityConfiguration,
    forKey: name
)
```
