### ISSUE TITLE
AWSS3TransferUtility not uploading in background with mobile data enabled only.

### ISSUE THREAD

**Issue by Sunfocus** [aws-amplify/aws-sdk-ios#5028]
**Describe the bug**
I use AWSS3TransferUtility to upload files, either in the foreground or the background. When the app is in the background, I can observe that the upload task is created successfully, but the completionHandler is never called unless I bring the app to the foreground. This behavior is unusual, considering it used to function normally. This issue occurs only in a cellular connection.

**Code Snippet**
```swift
    func initializeS3() {
        let credentialsProvider = AWSStaticCredentialsProvider(accessKey: Constant.access,secretKey: Constant.secretID)
        if  let configuration = AWSServiceConfiguration(region: AWSRegionType.USEast2, credentialsProvider: credentialsProvider) {
            configuration.allowsCellularAccess = true
            // Set the default service configuration
            AWSServiceManager.default()?.defaultServiceConfiguration = configuration
            
            // Configure background session
            let backgroundConfiguration = URLSessionConfiguration.background(withIdentifier: "xyz-identifier.backgroundTransfer")
            backgroundConfiguration.isDiscretionary = true
            backgroundConfiguration.sessionSendsLaunchEvents = true

            // Create and configure your AWSS3TransferUtilityConfiguration
            let s3config = AWSS3TransferUtilityConfiguration()
            s3config.isAccelerateModeEnabled = true
            let uniqueIdentifier = "com.xyz.s3config.\(AWSRegionType.USEast2.rawValue)"
            AWSS3TransferUtility.register(with: configuration, transferUtilityConfiguration: s3config, forKey: uniqueIdentifier)

        }
    }

   func application(_ application: UIApplication, handleEventsForBackgroundURLSession identifier: String, completionHandler: @escaping () -> Void) {
        bfprint("handleEventsForBackgroundURLSession \(identifier)")
        AWSS3TransferUtility.interceptApplication(application, handleEventsForBackgroundURLSession: identifier, completionHandler: completionHandler)
        completionHandler()
    }

    func uploadAudioToS3(audioUrl:URL,fileName:String,complition: @escaping(Bool)->()){
        let transferUtility = AWSS3TransferUtility.default()
        transferUtility.configuration.allowsCellularAccess = true
        transferUtility.transferUtilityConfiguration.isAccelerateModeEnabled = true
        transferUtility.configuration.maxRetryCount = 10
        
        print("isAccelerateModeEnabled  : \(transferUtility.transferUtilityConfiguration.isAccelerateModeEnabled)")
        print("allowsCellularAccess  : \(transferUtility.configuration.allowsCellularAccess)")
        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = { task, progress in
            
        }
        
        bfprint("File addded to upload on S3:  \(audioUrl.lastPathComponent)")
        transferUtility.uploadFile(audioUrl, bucket: bucket, key: "\(fileName)", contentType: "audio/x-wav", expression: expression) { (task, error) in
            if let error = error {
                bfprint("Error from S3 \(error.localizedDescription) --- \(fileName)")
                complition(false)
            } else {
                print("File uploaded successfully! \(fileName)")
                bfprint("File uploaded successfully! --- \(fileName)")
                complition(true)
            }
        }
    }
```
**Observed Behavior**
I do not see the file uplaoded print as nothing happens while the app stays in the background. However the aws upload task created successfully print is logged. The completionBlock is called once I move the app in the foreground. With wifi enabled the upload is completed in the background too.

**Expected behaviour**
iPhone connected to Wifi -> app in the background -> a file starts uploading -> completion Handler is called even when the app is in the background

**Unexpected behaviour**
iPhone connected only to Cellular -> app in the background -> a file starts uploading -> completion Handler is not called unless the app is moved in the foreground.

Environment(please complete the following information):

SDK Version: 
 'AWSS3', '~> 2.33.4'
'AWSMobileClient', '~> 2.33.4'
  
Dependency Manager: Cocoapods
Swift Version : 5.9
Xcode Version: 15.0
Device Information (please complete the following information):

Device: iPhone 12 Pro
iOS Version: iOS 17.0.3

It's coming in all iPhone devices and all iOS version.

**Comment by thisisabhash** [comment]
Thank you for posting this. We'll investigate this and post an update here.

**Comment by vikashsingh1** [comment]
this is show blocker for me.

**Comment by vikashsingh1** [comment]
Not working for me and I m uploading data in sequence like once the object uploaded then start new upload. Nothing printing in logs. and in my case either connect on mobile data or wifi upload stop when move in background.

**Comment by vikashsingh1** [comment]
class BatchImagesUploadOp: NetworkOp {
    deinit {
        self.sucess = nil
        self.task = nil
        self.firstSucess = nil
        self.uploadObject = [[]]
        self.data = nil
        NotificationCenter.default.removeObserver(self)
    }
    var uploadObject: [[UploadModel]]
    var sucess: ((_ thub: String, _ actual: String) -> Void)?
    var firstSucess: ((_ thub: String, _ actual: String) -> Void)?
    var task: BoxUploadTask?
    var thub: String = ""
    var actual: String = ""
    var bucketName: String
    var data: Data!
    init(objList : [[UploadModel]], bucketName: String,  sucess: ((_ thub: String, _ actual: String) -> Void)?,
         firstSucess: ((_ thub: String, _ actual: String) -> Void)?) {
        self.uploadObject = objList
        self.bucketName = bucketName
        self.sucess = sucess
        self.firstSucess = firstSucess
    }
    
    override func main() {
        if self.checkCancel() || self.uploadObject.isEmpty {
            self.complete()
            return
        }
        NotificationCenter.default.addObserver(self, selector: #selector(cancelAllTasks), name: .cancelUploadTask, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(cancelOneTask), name: .deleteUploadTask, object: nil)
        let object = self.uploadObject.remove(at: 0)
        self.manageUploadDataTask(uploadTask: object)
    }
    
    @objc func cancelAllTasks(notification: Notification) {
        SocketIOManager.default_.cncUploadingCompleted = true
        appUserDefault.homeUploadingCompleted = true
        appUserDefault.infoUploadingCompleted = true
        self.cancel()
    }
    
    @objc func cancelOneTask(notification: Notification) {
        
        if let userInfo = notification.userInfo as? [String: Any] {
            if let actualKey = userInfo["actualKey"] as? String ,
               let thumbKey = userInfo["thumbKey"] as? String {
                debugPrint("Do not execute This task")
                self.uploadObject = self.uploadObject.filter { batchArray in
                    return !batchArray.contains { element in
                        return element.fileName == actualKey || element.fileName == thumbKey
                    }
                }

                debugPrint("FINAL UPLOAD ARRAY == ", self.uploadObject.count)
            }
        }
    }
    
    func manageUploadDataTask(uploadTask: [UploadModel]) {
        if uploadTask.isEmpty {
            DispatchQueue.main.async {
                self.sucess?(self.thub, self.thub)
                self.firstSucess?(self.thub, self.thub)
                NetOpsBoxQueueMgr.shared.submitOp(netOp: BatchImagesUploadOp(objList: self.uploadObject, bucketName: self.bucketName,
                                                                             sucess: self.sucess,
                                                                             firstSucess: self.firstSucess))
                self.complete()
            }
            return
        }
        var objList = uploadTask
        let object = objList.remove(at: 0)
        self.data = object.object
        let objName = object.fileName
        guard let  transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: self.bucketName) else {
            return
        }
        if let localPath = object.localPath,
           let fileData = try? Data(contentsOf: localPath) {
            data = fileData
        }
        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = { (task, progress) in
            debugPrint("progressBlock", progress.fractionCompleted)
            DispatchQueue.main.async(execute: {
                ImageProgressManger.shared.setProgress(task.key, progress.fractionCompleted)
                NotificationCenter.default.post(name: .uploadProgress, object: task,userInfo:  ["key": task.key,  "progress": progress.fractionCompleted])
            })
        }
        var completionHandler: AWSS3TransferUtilityUploadCompletionHandlerBlock?
        completionHandler = { [weak self] (task, error) -> Void in
            guard let self = self else { return }

            DispatchQueue.main.async(execute: {
                if !self.isCancelled {
                    if let localPath = object.localPath {
//                        CacheManager.shared.deleteURL(localPath)
                    }
                    DispatchQueue.main.async(execute: {

                        if objList.count == 0 {
                            self.actual = objName
                            if self.thub.isEmpty {
                                self.thub = objName
                            }
                            self.firstSucess?(self.thub, self.actual)
                            if self.uploadObject.isEmpty {
                                DispatchQueue.main.asyncAfter(deadline: .now() + 2) { [weak self] in
                                    guard let self = self else { return }
                                    self.sucess?(self.thub, self.actual)
                                    self.complete()
                                }
                            } else {
                                
                                NetOpsBoxQueueMgr.shared.submitOp(netOp: BatchImagesUploadOp(objList: self.uploadObject, bucketName: self.bucketName,
                                                                                             sucess: self.sucess,
                                                                                             firstSucess: self.firstSucess))
                                self.complete()
                            }
                            
                        } else {
                            self.thub = objName
                            self.manageUploadDataTask(uploadTask: objList)
                        }
                        
                    })
                }
                else if self.isCancelled {
                    debugPrint("UPLOAD MODEL self.isCancelled")
                    if self.uploadObject.isEmpty {
                        DispatchQueue.main.asyncAfter(deadline: .now() + 2) { [weak self] in
                            guard let self = self else { return }
                            self.sucess?(self.thub, self.actual)
                            self.complete()
                        }
                    }
                }
            })
        }
        if let uploadTasks: [AWSS3TransferUtilityUploadTask] = transferUtility.getUploadTasks().result as? [AWSS3TransferUtilityUploadTask],
           let task = uploadTasks.filter({ $0.key == objName }).first,
        let progressBlock = expression.progressBlock,
        let completionBlock = completionHandler {
               task.setProgressBlock(progressBlock)
               task.setCompletionHandler(completionBlock)
            return

        }
        transferUtility.uploadData(data,
                                   bucket: bucketName,
                                   key: objName,
                                   contentType: objName.mimeType(),
                                   expression: expression,
                                                    completionHandler: completionHandler).continueWith(block: {  (task) -> AnyObject? in
            if let error = task.error {
                print("Error: \(error)")
            }
            if let result = task.result {
                print("this is result \(result.key)")
            }
            if  task.isCancelled {
                print("task has been cancled")
            }
            return nil
        })
    }
}

**Comment by vikashsingh1** [comment]
{
        let region = appUserDefault.getDynamicRegionData()?.aws_region
        let regionType: AWSRegionType = self.getRegionByID(region)
        let credentialsProvider = AWSStaticCredentialsProvider(accessKey: self.getAccesskey(.s3),
                                                               secretKey: self.getSecretkey(.s3))
        let configuration = AWSServiceConfiguration(region: regionType, credentialsProvider:credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        guard let configuration = configuration else { return }
        let utilityConfiguration = AWSS3TransferUtilityConfiguration()
        let bucket = appUserDefault.getDynamicRegionData()?.upload_bucket 
        utilityConfiguration.bucket = bucket
        self.bucketName = bucket
        AWSDDLog.sharedInstance.logLevel = .verbose
        if AWSS3TransferUtility.s3TransferUtility(forKey: bucket) == nil {
            AWSS3TransferUtility.register(with: configuration, transferUtilityConfiguration: utilityConfiguration, forKey: bucket)
            
        }
    }

**Comment by vikashsingh1** [comment]
Any update here?

**Comment by atierian** [comment]
It sounds like you might have Background App Refresh turned off in settings on your iPhone. Can you please check if that's the case? Thanks.
