### ISSUE TITLE
sessionToken Validity period is set to 50 minutes and 400 uploads are performed in a single instance

### ISSUE THREAD

**Issue by chengssir** [aws-amplify/aws-sdk-ios#5054]
let credentialsProvider = AWSBasicSessionCredentialsProvider(accessKey: accessKey, secretKey: secretKey, sessionToken: model.sessionToken)
 guard let configuration = AWSServiceConfiguration(region: .USWest1, credentialsProvider: credentialsProvider) else {
      complete(.error)
      return
 }
 AWSServiceManager.default().defaultServiceConfiguration = configuration
 let expression = AWSS3TransferUtilityUploadExpression()
 AWSS3TransferUtility.default().uploadFile(urlpath, bucket: model.bucket, key: model.path, contentType: contentType, expression: expression) 

sessionToken is only valid for 50 minutes, after 50 minutes, uploading again will get 400 errors

I understand the source code, singleton initialization when the configuration is set, but there is no way to update

**Comment by lawmicha** [comment]
Hi @chengssir, you can configure the timeout from 50 minutes to a larger value. See this related issue for more details: https://github.com/aws-amplify/aws-sdk-ios/issues/5054 Let us know if this works for you.
