### ISSUE TITLE
subscribeToTopic crash

### ISSUE THREAD

**Issue by tangguoEddy** [aws-amplify/aws-sdk-ios#5159]
Hello, my version is AWSIOSSDKV2 2.33.5, and now I have found that a large number of users are experiencing this error online; please help check it as soon as possible.

<img width="1290" alt="企业微信20240116-下午23933@2x" src="https://github.com/aws-amplify/aws-sdk-ios/assets/149549334/c9f0edc4-bc61-4a4e-92c6-447f27023e7e">

**Comment by tangguoEddy** [comment]
The scenario is in the App extension (TodayExtension) ViewWillAppear, where it iterates over Bluetooth objects and subscribes to topics one by one through AWSSDK. For the specific exception location, please refer to the screenshot below.

<img width="1698" alt="image" src="https://github.com/aws-amplify/aws-sdk-ios/assets/149549334/0cdd7127-01f4-4c0b-9f8e-11fd5d4976ec">


> @tangguoEddy Thanks for raising the issue. Have you been able to reproduce the crash locally in a dev environment? If yes, can you provide more details and logs?
> 
> Furthermore, would you be able to describe your usecase a little bit and give examples of code snippets that is crashing for you. This will vastly help us in recreating the issue in a dev environment.

**Comment by ruisebas** [comment]
Hi @tangguoEddy. 
The exception you are getting indicates you are attempting to subscribe without connecting first, which is not a valid use case. 
Please check that you are calling `connect` first. If you are, I advice to listen for the `connected` state callback before subscribing.

Having said that, please note that App Extensions are not officially supported by the AWS SDK for iOS.

**Comment by tangguoEddy** [comment]
> Hi @tangguoEddy. The exception you are getting indicates you are attempting to subscribe without connecting first, which is not a valid use case. Please check that you are calling `connect` first. If you are, I advice to listen for the `connected` state callback before subscribing.
> 
> Having said that, please note that App Extensions are not officially supported by the AWS SDK for iOS.

Can I understand that the SDK does not currently support app extensions for official integration? Is it because the lifecycle of the extension is different from that of the app that it leads to unforeseen exceptions? Under normal circumstances, the SDK should not crash in any scenario.

**Comment by ruisebas** [comment]
That is correct, under normal circumstances you'd never see this exception. 
I was unable to reproduce it on a standalone iOS application, so it's possible that the App Extension is messing up the expected objects life cycle and causing this. Are you perhaps calling `disconnect()` on a different thread?

If you are able to reproduce this on a standalone iOS app, please provide the full crash report and share how you are interacting with `AWSIoTDataManager`'s methods.

Thanks!

**Comment by ruisebas** [comment]
@tangguoEddy I was also unable to reproduce it with a simple Widget Extension. 
I called `AWSIoTDataManager.subscribe(toTopic:qoS:messageCallback:)` on appear without having called `connect` first, but I didn't get any crash. I just got the expected `false` result.

So please do share the full crash report and any relevant code snippets that show how you interact with these methods.
Thanks!

**Comment by lawmicha** [comment]
Hello, we released [2.33.9](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.33.9) which includes an IoT crash fix https://github.com/aws-amplify/aws-sdk-ios/pull/5185. Please upgrade to this and let us know if you are still experiencing the issue.
