### ISSUE TITLE
How do I reset the AWSPinpoint endpoints when data is migrated with Quick Start?

### ISSUE THREAD

**Issue by jormungand2006** [aws-amplify/aws-sdk-ios#5165]
**State your question**
・How do I reset the AWSPinpoint endpoints (held in UserDefaults and Keychain) when data is migrated with Quick Start on the iPhone?

My understanding is that AWSPinpoint stores the endpointId in both UserDefaults and Keychain after generating it.
https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSPinpoint/AWSPinpointTargetingClient.m#L142

If an app on device 1 that already stores endpointId: AAA is migrated to device 2 with QuickStart, the KeyChain value is not transferred, but the UserDefaults value is, so,
If the user does not initialize terminal device 1 afterwards, there will be multiple endpoints with EndpointId: AAA, is this the intended behavior?

I don't want the endpoints to be taken over, so I would like to reset the EndpointId when the app is launched on device 2. Is such a method provided?

**Which AWS Services are you utilizing?**
・AWSPinpoint

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: AWSSDKiOSV2: 2.33.1 (AWSPinpoint)
 https://github.com/aws-amplify/aws-sdk-ios-spm.git
 - Dependency Manager: SPM
 - Swift Version : 5

**Comment by 5d** [comment]
Hi @jormungand2006,
Thanks for opening the issue. Our team will look into it and provide an update.
