### ISSUE TITLE
Sign in with Apple still not working 

### ISSUE THREAD

**Issue by philipheinser** [aws-amplify/aws-sdk-ios#5211]
Does this still have any priority? Does Amplify plan to over support sign in with apple on iOS? 

https://github.com/aws-amplify/aws-sdk-ios/issues/2633#issuecomment-1938260808

**Comment by ruisebas** [comment]
Hi @philipheinser, this is still a service limitation with Cognito. 
We recommend using **Amplify Auth**; the relevant feature request is being tracked here: https://github.com/aws-amplify/amplify-swift/issues/1121.

Thanks

**Comment by philipheinser** [comment]
@ruisebas the linked issue is 3 years old. There multiple comments saying that was is looking into it or working on this and that there will be updates soon. And that for any years with no outcome or update? For a feature to that was advertised as working on a payed product for many years. Does nobody care about customers. 😢
