### ISSUE TITLE
App Hang - The app was terminated while unresponsive

### ISSUE THREAD

**Issue by bhavinchauhanios** [aws-amplify/aws-sdk-ios#5218]
**Describe the bug**
App Hang AWSS3TransferUtility.m:1044
The app was terminated while unresponsive

**To Reproduce**
![Screenshot 2024-02-27 at 3 04 38 PM](https://github.com/aws-amplify/aws-sdk-ios/assets/7007376/732f4171-94b7-48e2-9fb8-0697cf2f543e)

**Observed Behavior**
After capture through camera there is not uploading image. 

**Expected Behavior**
After capture through camera image should be upload. 

**Stack Trace**
[bugsnag_error_stacktrace_App Hang_event_65d4b19f00d88af802cb0000.txt](https://github.com/aws-amplify/aws-sdk-ios/files/14419039/bugsnag_error_stacktrace_App.Hang_event_65d4b19f00d88af802cb0000.txt)

**Code Snippet**

```
transferUtilityForImage.uploadData(data, bucket: bucketName, key: fileName, contentType: "text/plain", expression: expressionImage, completionHandler: completionHandlerImage).continueWith { (task) -> AnyObject? in
                
                if let error = task.error {
                    console("Error: \(error.localizedDescription)")
                }
                
                if let result = task.result {
                    console("Upload Starting!")
                    console("Uploaded Image URL: https://\(bucketName).s3.ap-south-1.amazonaws.com/\(fileName)")
                }
                
                return nil;
            }
```

**Environment(please complete the following information):**
 - SDK Version: 'AWSS3', '~> 2.13.4'
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2
 - Xcode Version: Version 15.1

**Device Information (please complete the following information):**
 - Device: iPhone 14
 - iOS Version: 17.2.1
 
 Note: Some time generated crash. Otherwise working fine.

**Comment by ruisebas** [comment]
Hi @bhavinchauhanios, thanks for opening this issue.
You're using version [2.13.4](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.13.4), which is almost 4 years old.
Please upgrade to the latest version and let us know if this still happens.

If after upgrading you still see the issue, please enable verbose logging by doing the following:
```swift
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance) // To print the logs in the Xcode console

```
and share the logs up to the crash with us please.
