### ISSUE TITLE
Unable to set new configuration for AWSServiceManager on session token expiration

### ISSUE THREAD

**Issue by amangupta001** [aws-amplify/aws-sdk-ios#5281]
Hi I am also facing the same issue

My Code Snippet

 func isKeysSetToAWSS3Enviroment(path: String) {

        if let keys = AWSCredentials.getKeysDetails() {

            let accessKey = keys.accessKey ?? ""
            let secretKey = keys.secretKey ?? ""
            let sessionKey = keys.sessionId ?? ""

            let credentialsProvider = AWSBasicSessionCredentialsProvider(accessKey: accessKey, secretKey: secretKey, sessionToken: sessionKey)
            let configuration = AWSServiceConfiguration(region: AWSRegionType.USEast1, credentialsProvider: credentialsProvider)
            if let crdeentials = AWSServiceManager.default().defaultServiceConfiguration {
                print("AWSCredentials Before \(crdeentials.credentialsProvider.credentials())")
            }
            AWSServiceManager.default().defaultServiceConfiguration = configuration
            print("AWSCredentials After \(AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials())")

        }
    }
    
    Printing the credentials before and after are always same it not getting changed.
    
    I am completely blocked:
    
    
    Our SDK Version pod 'AWSS3','2.10.3'

**Comment by ruisebas** [comment]
Hi @amangupta001, thanks for opening this issue.

I used the code snippet you provided and was able to change the `defaultServiceConfiguration` successfully. Keep in mind that you can only set that value once, so if you do get the `"AWSCredentials Before {}"` statement printed, it means you've already set the configuration before and you won't be able to change it. Try setting a breakpoint in [that setter](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCore/Service/AWSService.m#L94) to find out where you're calling it from first.

Also, you mentioned you're using version [2.10.3](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.10.3) which is **more than 4 years old**. Please update to the latest release, as there's been a lot of changes since then.

Thanks.

**Comment by amangupta001** [comment]
> Hi @amangupta001, thanks for opening this issue.
> 
> I used the code snippet you provided and was able to change the `defaultServiceConfiguration` successfully. Keep in mind that you can only set that value once, so if you do get the `"AWSCredentials Before {}"` statement printed, it means you've already set the configuration before and you won't be able to change it. Try setting a breakpoint in [that setter](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCore/Service/AWSService.m#L94) to find out where you're calling it from first.
> 
> Also, you mentioned you're using version [2.10.3](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.10.3) which is **more than 4 years old**. Please update to the latest release, as there's been a lot of changes since then.
> 
> Thanks.

if let crdeentials = AWSServiceManager.default().defaultServiceConfiguration {
            print("AWSCredentials Before \(crdeentials.credentialsProvider.credentials())")
        }
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        print("AWSCredentials After \(AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials())")
        
        Do set again once all three got expired () accessKey,Session Id, SecretKey
        
  And Then print 
          print("AWSCredentials After \(AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials())")

It holds the same value .

Don't launch the app again and again

**Comment by ruisebas** [comment]
As previously mentioned, you can only assign `defaultServiceConfiguration` **once**. 

In your example, you're creating a `AWSBasicSessionCredentialsProvider` with static credentials, which you cannot change later. But you can create your own `AWSCredentialsProvider` class that allows you to change those values:

```swift
class CredentialsProvider: NSObject, AWSCredentialsProvider {
    var awsCredentials: AWSCredentials

    init(awsCredentials: AWSCredentials) {
        self.awsCredentials = awsCredentials
    }

    func credentials() -> AWSTask<AWSCredentials> {
        return .init(result: awsCredentials)
    }

    func invalidateCachedTemporaryCredentials() {
        // ...
    }
}
```

And then consume it like this:
```swift
let credentialsProvider = CredentialsProvider(
    awsCredentials: .init(
        accessKey: "accessKey",
        secretKey: "secretKey",
        sessionKey: "sessionKey",
        expiration: nil)
)
let configuration = AWSServiceConfiguration(
    region: AWSRegionType.USEast1,
    credentialsProvider: credentialsProvider
)
AWSServiceManager.default().defaultServiceConfiguration = configuration

print("AWSCredentials before: \(AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials())")
// Prints accessKey, secretKey and sessionKey

credentialsProvider.awsCredentials = .init(
    accessKey: "newAccessKey",
    secretKey: "newSecretKey",
    sessionKey: "newSesionKey",
    expiration: nil
)

print("AWSCredentials after: \(AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials())")
// Prints newAccessKey, newSecretKey and newSesionKey
```

**Comment by amangupta001** [comment]
Giving error while using it 
```
class CredentialsProvider: NSObject, AWSCredentialsProvider {
    var awsCredentials: AWSCredentials

    init(awsCredentials: AWSCredentials) {
        self.awsCredentials = awsCredentials
    }

    func credentials() -> AWSTask<AWSCredentials> {
        return .init(result: awsCredentials)
    }

    func invalidateCachedTemporaryCredentials() {
        // ...
    }
}
```


<img width="979" alt="Screenshot 2024-04-10 at 11 29 24" src="https://github.com/aws-amplify/aws-sdk-ios/assets/22891755/ac95b548-fdac-4c46-a16e-c925ec491ddf">

**Comment by ruisebas** [comment]
It seems you have some Xcode issue. Try cleaning up the build folder and/or wiping Derived Data.

**Comment by amangupta001** [comment]
> It seems you have some Xcode issue. Try cleaning up the build folder and/or wiping Derived Data.

I am using Xcode 15.3
Drived Data is clear still same error.

**Comment by amangupta001** [comment]
Please check my video
https://github.com/aws-amplify/aws-sdk-ios/assets/22891755/bc298749-7b88-4f57-b41f-d9b4b13c7aff

**Comment by amangupta001** [comment]
one update its getting compiled  for simulator not for device

**Comment by ruisebas** [comment]
Are you perhaps defining your own `AWSCredentials` or `AWSTask` types within your code? If so, you'll need to add the `AWSCore` namespace to the signatures, so that the compiler knows which one to use.

For example:
```
func credentials() -> AWSCore.AWSTask<AWSCore.AWSCredentials> {
```

**Comment by amangupta001** [comment]
> Are you perhaps defining your own `AWSCredentials` or `AWSTask` types within your code? If so, you'll need to add the `AWSCore` namespace to the signatures, so that the compiler knows which one to use.
> 
> For example:
> 
> ```swift
> func credentials() -> AWSCore.AWSTask<AWSCore.AWSCredentials> {
> ```

Thanks this code is getting compiled but still **AWSServiceManager.default().defaultServiceConfiguration** prints the old credentials not holding the new credentials 



```
func isKeysSetToAWSS3EnviromentNew(path: String) -> Bool {

        if let keys = AWSCredentials.getKeysDetails() {

            let accessKey = keys.accessKey ?? ""
            let secretKey = keys.secretKey ?? ""
            let sessionKey = keys.sessionId ?? ""

            let credentialsProvider = CredentialsProvider(
                awsCredentials: .init(
                    accessKey: accessKey,
                    secretKey: secretKey,
                    sessionKey: sessionKey,
                    expiration: nil)
            )
            let configuration = AWSServiceConfiguration(
                region: AWSRegionType.USEast1,
                credentialsProvider: credentialsProvider
            )
            
            if let crdentials = AWSServiceManager.default().defaultServiceConfiguration {
                print("AWSCredentials Before \(crdentials.credentialsProvider.credentials())")
            }
            
            AWSServiceManager.default().defaultServiceConfiguration = configuration
            print("AWSCredentials after: \(AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials())")
            return true
        }
        return false
    }
```

**Comment by ruisebas** [comment]
Hi @amangupta001, you last comment is a bit confusing: You stated that 
> I have done plus what you have suggested but still **AWSServiceManager.default().defaultServiceConfiguration** prints the old credentials not holding the new credentials 

but then that

> My this function is always getting called with new AccessToken , secretKey, sessionId even they are not expired

Could you clarify which behaviour you are experiencing?

--- 

Setting that aside, let me take a few steps back and clarify how things work:

#### You can only set the default configuration **once**.

As I stated previously, if `AWSServiceManager.default().defaultServiceConfiguration` is not `nil`, you will not be able to change it. If you call the setter, it will do nothing. So you need to make sure you are not attempting to set it again. A simple check will do:

```swift
guard AWSServiceManager.default().defaultServiceConfiguration == nil else {
    print("Unable to change defaultConfiguration, it's already set.")
    return false
}
```

#### You need to implement `credentials()` properly

Calling `AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials()` will invoke the `credentials()` method of the `CredentialsProvider` you've set in your configuration.

In the custom implementation I shared with you as an example, it will always return whatever `awsCredentials` holds.  So it's up to you to make sure that you manually set that property to the expected value.

If you want to have more of a dynamic implementation, you can implement the `credentials()` method to be something like this:

```swift
func credentials() -> AWSCore.AWSTask<AWSCore.AWSCredentials> {
    if (/* awsCredentials are expired */ ) {
        awsCredentials = // Fetch new credentials
    }
    return .init(result: awsCredentials)
}
```

--- 

If you still cannot make it work, could you please provide us with a sample app/Xcode project that reproduces the issue?

Thanks

**Comment by amangupta001** [comment]
> Hi @amangupta001, you last comment is a bit confusing: You stated that
> 
> > I have done plus what you have suggested but still **AWSServiceManager.default().defaultServiceConfiguration** prints the old credentials not holding the new credentials
> 
> but then that
> 
> > My this function is always getting called with new AccessToken , secretKey, sessionId even they are not expired
> 
> Could you clarify which behaviour you are experiencing?
> 
> Setting that aside, let me take a few steps back and clarify how things work:
> 
> #### You can only set the default configuration **once**.
> As I stated previously, if `AWSServiceManager.default().defaultServiceConfiguration` is not `nil`, you will not be able to change it. If you call the setter, it will do nothing. So you need to make sure you are not attempting to set it again. A simple check will do:
> 
> ```swift
> guard AWSServiceManager.default().defaultServiceConfiguration == nil else {
>     print("Unable to change defaultConfiguration, it's already set.")
>     return false
> }
> ```
> 
> #### You need to implement `credentials()` properly
> Calling `AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials()` will invoke the `credentials()` method of the `CredentialsProvider` you've set in your configuration.
> 
> In the custom implementation I shared with you as an example, it will always return whatever `awsCredentials` holds. So it's up to you to make sure that you manually set that property to the expected value.
> 
> If you want to have more of a dynamic implementation, you can implement the `credentials()` method to be something like this:
> 
> ```swift
> func credentials() -> AWSCore.AWSTask<AWSCore.AWSCredentials> {
>     if (/* awsCredentials are expired */ ) {
>         awsCredentials = // Fetch new credentials
>     }
>     return .init(result: awsCredentials)
> }
> ```
> 
> If you still cannot make it work, could you please provide us with a sample app/Xcode project that reproduces the issue?
> 
> Thanks

[SampleApp.zip](https://github.com/aws-amplify/aws-sdk-ios/files/14954526/SampleApp.zip)

Please find my attached code 

Whole intension is refresh all three keys .

**Comment by ruisebas** [comment]
I used your app and you are calling `isKeysSetToAWSS3Enviroment()` from `viewDidLoad()`, which sets the `defaultServiceConfiguration`. 

And then you call it again on `click_refreshToken` attempting to upgrade the credentials. As I said many times before, you can only set `defaultServiceConfiguration` **once**, which you already do in `viewDidLoad()`. So any attempt to update it later will do nothing.

What you should do instead is have the `CredentialsProvider` as an instance variable and update its credentials on `click_refreshToken()`:

```swift
    private let credentialsProvider = CredentialsProvider(awsCredentials: .init())

    override func viewDidLoad() {
        super.viewDidLoad()
        // Update the credentials provider with the initial credentials
        updateCredentials(
            accessKey: "accessKey",
            secretKey: "secretKey",
            sessionKey: "sessionKey"
        )

        // Set the defaultServiceConfiguration
        AWSServiceManager.default().defaultServiceConfiguration = .init(
            region: .USEast1,
            credentialsProvider: credentialsProvider
        )
    }

    @IBAction func click_refreshToken(_ sender: Any) {
        let oldCredentials = AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials()
        self.lblBeforeCredentials.text = "Before Credentials AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials() \n\n \(oldCredentials)"

        updateCredentials(
            accessKey: "newAccessKey",
            secretKey: "newSecretKey",
            sessionKey: "newSessionKey"
        )

        let newCredentials = AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials()
        self.lblAfterCredentials.text = "After Credentials AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider.credentials() \n\n \(newCredentials)"
    }

    private func updateCredentials(
        accessKey: String,
        secretKey: String,
        sessionKey: String
    ) {
        credentialsProvider.awsCredentials = .init(
            accessKey: accessKey,
            secretKey: secretKey,
            sessionKey: sessionKey,
            expiration: nil
        )
        lblAccesskey.text = ("Accesskey -" + accessKey)
        lblSecretKey.text = ("SecretKey -" + secretKey)
        lblSessionKey.text  = ("SessionKey -" + sessionKey)
    }
```

**Comment by amangupta001** [comment]
Thank u so much @ruisebas Its working now finally credentials are getting updated when ever token get expired with new values
