### ISSUE TITLE
Why awsiot mqtt keepAliveTimeInterval default is 300s？

### ISSUE THREAD

**Issue by weidongliu** [aws-amplify/aws-sdk-ios#5282]
In the awsiot 2.33.10 version, I saw the mqttConfiguration attribute comment of AWSIoTDataManager.h saying the default is 60s, but in AWSIoTDataManager.m I found that it is actually 300s. This will mislead developers. Why do you change it to 300s?
![image](https://github.com/aws-amplify/aws-sdk-ios/assets/13080014/048c684b-b6cb-4a66-a345-62b6336be657)
![image](https://github.com/aws-amplify/aws-sdk-ios/assets/13080014/08446999-fb76-4552-acc2-26757c6367ac)

**Comment by ruisebas** [comment]
Hi @weidongliu, thanks for opening this issue.

The value for `keepAliveTimeInterval` was updated to 300 seconds in version [2.6.6](https://github.com/aws-amplify/aws-sdk-ios/blob/main/CHANGELOG.md#266) back in 2017, but it seems the corresponding attribute comment was not updated to reflect that.

We'll take note and update it.

**Comment by ruisebas** [comment]
The attribute comment has been updated in the latest [2.36.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.36.0) release.
