### ISSUE TITLE
how to handle sessions of multiple logged in users in aws cognito?

### ISSUE THREAD

**Issue by JohnMark023** [aws-amplify/aws-sdk-ios#5360]
how to handle sessions of multiple logged in users in aws cognito?

AWS Cognito

In the app, I want multiple users to be able to log in and switch sessions per user and roles.

**Comment by 5d** [comment]
Hi @JohnMark023 ,
Thanks for raising the issue. Our team will investigate it and get back to you later.

**Comment by ruisebas** [comment]
Hi @JohnMark023, sorry for the delay in our response.
Handing multiple simultaneous sessions is not supported by the AWS SDK for iOS.
