### ISSUE TITLE
AWSIoTMQTTClient scheduleReconnection crash

### ISSUE THREAD

**Issue by tavisbones** [aws-amplify/aws-sdk-ios#5449]
**Describe the bug**
We are on version 2.37.2 version of the sdk and this crash is fairly prevalent in our application

**To Reproduce**
1. Leave the app open for hours

**Observed Behavior**
Crashes

**Expected Behavior**
Doesn't crash

**Stack Trace**
<img width="679" alt="Screenshot 2024-10-04 at 1 10 14 PM" src="https://github.com/user-attachments/assets/ca0bb513-df70-4bbf-9632-dfe33b42c2de">

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
IoT

**Environment(please complete the following information):**
 - SDK Version: 2.37.2
 - Dependency Manager: SPM
 - Swift Version : 5.0
 - Xcode Version: All versions

**Device Information (please complete the following information):**
 - Device: All devices
 - iOS Version: iOS 17

**Comment by mattcreaser** [comment]
Thanks for filing the issue @tavisbones. Could you talk a little bit more about how you're using the SDK? That will help in investigating the issue.

**Comment by tavisbones** [comment]
@mattcreaser we are just opening an IoT connection and let the app run for awhile (hours)

`iotDataManager?.connectUsingWebSocket(withClientId: clientId, cleanSession: true, statusCallback: statusCallback)`

**Comment by ruisebas** [comment]
Closing in favour of https://github.com/aws-amplify/aws-sdk-ios/issues/5453, which has more context.

@tavisbones if you're able, please try out the [`fix/iot-crash`](https://github.com/aws-amplify/aws-sdk-ios/tree/fix/iot-crash) branch that has a potential fix and let us know if it resolves your issues.
