### ISSUE TITLE
Resume from the breakpoint when upload failed with TransferUtilityMultiPartUpload

### ISSUE THREAD

**Issue by zhongruiBlink** [aws-amplify/aws-sdk-ios#5455]
Hi, I am using TransferUtilityMultiPartUpload to upload large video.

And my question is if there have any way, to resume upload from the breakpoint when the upload faild.

I try use the resume(), but I find the callback will show the task is failed imdientily.

**Comment by edisooon** [comment]
Hi @zhongruiBlink  Thanks for submitting the issue! One of our team members will investigate and provide updates here.

**Comment by zhongruiBlink** [comment]
Hi @ruisebas! Thanks for the information.

We're looking for a way to address this issue:

When we start an upload task with 100 chunks, if the upload fails after 50 chunks have been successfully uploaded, we currently have to restart from the first chunk. This means re-uploading those 50 chunks, which takes a lot of time. Is there any way to resume the upload starting from chunk 51?
