### ISSUE TITLE
Crash on `AWSMobileClient` when initialising at runtime. 

### ISSUE THREAD

**Issue by RuiAAPeres** [aws-amplify/aws-sdk-ios#5458]
**State your question**

We are currently initialising `AWPinpoint` dynamically (i.e. without the use of JSON files). We do this, because the configuration is dependant on a few conditions that are only available at a later point. We do the following:

```swift
let localConfiguration = AWSConfiguration.configuration

let credentialsProvider = AWSCognitoCredentialsProvider(regionType: localConfiguration.cognitoPoolRegion.toAWSRegionType,
                                                                identityPoolId: localConfiguration.cognitoPoolId)

let configuration = AWSServiceConfiguration(region: localConfiguration.pinpointRegion.toAWSRegionType,
                                                    credentialsProvider: credentialsProvider)

AWSServiceManager.default().defaultServiceConfiguration = configuration
pinpointConfiguration = AWSPinpointConfiguration(appId: localConfiguration.pinpointAppId, launchOptions: launchOptions)

/// later on:
pinpoint = configuration.pinpoint /// AWSPinpoint
pinpointAnalyticsClient = configuration.analyticsClient /// AWSPinpointAnalyticsClient
```

My `AWSConfiguration` has the following shape:

```swift
struct AWSConfiguration {
    let cognitoPoolId: String
    let cognitoPoolRegion: String
    let pinpointAppId: String
    let pinpointRegion: String
}
```

At a later point, we call this:

```swift
AWSMobileClient.default().interceptApplication(application, didFinishLaunchingWithOptions: options)
```

The above call **works fine** in `DEBUG` mode, but it's crashing in `RELEASE` with the following:

```
Thread 1: "The service configuration is `nil`. You need to configure `awsconfiguration.json` or `Info.plist` before using this method."
```

<img width="458" alt="image" src="https://github.com/user-attachments/assets/ff291205-1ce1-46a0-8199-233f23b2e451">

This is how our `awsconfiguration.json` looked (before removing it):

```json
{
  "UserAgent": "MobileHub/1.0",
  "Version": "1.0",
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "eu-west-xyz",
        "Region": "eu-west-1"
      }
    }
  },
  "IdentityManager": {
    "Default": {}
  },
  "PinpointAnalytics": {
    "Default": {
      "AppId": "pyx",
      "Region": "us-east-1"
    }
  },
  "PinpointTargeting": {
    "Default": {
      "Region": "us-east-1"
    }
  }
}
```

Question:

1. Is there something special happening in Release?
2. Do I even need to call `AWSMobileClient.default().interceptApplication`? We only use AWSPinpoint. 

**Which AWS Services are you utilizing?**

I am using AWSPinpoint.

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: **2.37.1**
 - Dependency Manager: **SPM**
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Simulator iPhone Pro
 -  - iOS Version: iOS 17.5

**Comment by edisooon** [comment]
Hi @RuiAAPeres, thank you for submitting this ticket! One of our team members will do some investigation on this as soon as possible.
Meanwhile, could you provide more log information from the crashes? This might help us identify the issue more easily.

**Comment by ruisebas** [comment]
Hi @RuiAAPeres!

`AWSMobileClient.interceptApplication(_:didFinishLaunchingWithOptions:)` is deprecated and was actually meant to be removed altogether way back in [**`2.11.0`**](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.11.0), but since it's still defined in the Objective-C interface you can still access it.

We apologize for the confusion/inconvenience this caused, and we will take notice to remove these outdated methods soon.

To answer your question: no, you should not use that method. Instead, what you should call from your AppDelegate is the `AWSMobileClient.initialize` method, as described [in the documentation page](https://docs.amplify.aws/gen1/swift/sdk/auth/getting-started/#initialization).

Please update your code and let us know if you're still experiencing the crash.

**Comment by ruisebas** [comment]
It depends on how your backend is configured. If you're not going to use Auth-related operations nor rely on them to submit events to Pinpoint, then it's probably ok to avoid using `AWSMobileClient` altogether.

**Comment by RuiAAPeres** [comment]
I would like you to expand on that `probably ok`. Is it going to be a problem, or not? 😅 I am currently not using any auth-related operations. We only use `AWSPinpoint`.

**Comment by ruisebas** [comment]
Officially, our [guidance is to use both `AWSMobileClient` and `AWSPinpoint`](https://docs.amplify.aws/gen1/swift/sdk/analytics/getting-started/#add-analytics) when adding Analytics in this SDK.

But it depends on your use case and how you've configured your backend. If you don't authenticate your users at all during your app's lifecycle and your Pinpoint application accepts events just fine, then I see no reason to initialize `AWSMobileClient`.

**Comment by RuiAAPeres** [comment]
Thank you @ruisebas. I will close this issue for now. I will re-open (or create a new one) if we have issues. 

**Outcome:** we will use the `AWSPinpoint` framework on its own, without using `AWSMobileClient`.
