### ISSUE TITLE
AWSS3 Asset Validation Failed

### ISSUE THREAD

**Issue by rajeshiosdev** [aws-amplify/aws-sdk-ios#5466]
I am experiencing an issue while attempting to share a build from Xcode 16.1 on macOS 15.1. The process fails with an "Asset validation failed" error. I am unable to proceed with sharing my build due to this error.
pod version I am using 2.37.2 and 2.33.0
![Screenshot 2024-11-21 at 12 50 33 PM](https://github.com/user-attachments/assets/d4ec236b-cc4a-4efc-ae72-0a419fc02b4a)

**Comment by vincetran** [comment]
Hi @rajeshiosdev thanks for your post, someone will take a look at this as soon as they have bandwidth
