### ISSUE TITLE
Required SDK Update for Certification Authority (CA) for Apple Push Notification service (APNs) 

### ISSUE THREAD

**Issue by hafiz-mohsin-confiz** [aws-amplify/aws-sdk-ios#5484]
Hello,
--
As we announced in October 2024, the Certification Authority (CA) for Apple Push Notification service (APNs) is changing. APNs will update the server certificates in sandbox on January 20, 2025, and in production on February 24, 2025. To continue using APNs without interruption, you’ll need to update your application’s Trust Store to include the new server certificate: SHA-2 Root : USERTrust RSA Certification Authority certificate.
To ensure a smooth transition and avoid push notification delivery failures, please make sure that both old and new server certificates are included in the Trust Store before the cut-off date for each of your application servers that connect to sandbox and production. At this time, you don’t need to update the APNs SSL provider certificates issued to you by Apple.

To ensure a smooth transition and avoid push notification delivery failures, please make sure that both old and new server certificates are included in the Trust Store before the cut-off date for each of your application servers that connect to sandbox and production. At this time, you don’t need to update the APNs SSL provider certificates issued to you by Apple.

Is there any change required on app side to do for AWS SNS SDK related for incorporate the above APNS Server Certificate Update?
cc: @ruisebas 
Regards,
Hafiz Mohsin Yaseen.

**Comment by ruisebas** [comment]
Hi @hafiz-mohsin-confiz! This is something that is handled by the service itself, i.e. SNS, and not the SDK.

There's no action required from your side :)

**Comment by hafiz-mohsin-confiz** [comment]
Hi @ruisebas,
Thanks for update on it.
