### ISSUE TITLE
HTTPMaximumConnectionsPerHost parameter for NSURLSessionConfiguration

### ISSUE THREAD

**Issue by dydus0x14** [aws-amplify/aws-sdk-ios#606]
My application runs bunch of requests via AWSServiceManager.

Are there any way to set up custom value for HTTPMaximumConnectionsPerHost for session which is used into AWSServiceManager? The default value for iOS is 4.

Thanks a lot.

**Comment by karthiksaligrama** [comment]
Whats your use case?

**Comment by dydus0x14** [comment]
@karthiksaligrama my app has more than 4 upload/download aws requests at the same time, but aws sdk does't allow running so many because of HTTPMaximumConnectionsPerHost restriction. I think that running more requests would improve performance of my app.

**Comment by rohandubal** [comment]
Hi, currently there is no way to set it to a higher number. I will take this as a feature request to the team.

Thanks,
Rohan

**Comment by dydus0x14** [comment]
@rohandubal thanks a lot

**Comment by fadylateef** [comment]
Same problem here, any updates !
Some other libraries resolved it using nsoperation queue or dispatch methods. 
Any workouts till now ?
