### ISSUE TITLE
AWSURLSessionManager drops "no route to host" error.

### ISSUE THREAD

**Issue by igor-plygime** [aws-amplify/aws-sdk-ios#661]
When underlying network has "no route to host" state I can't get any error about it through regular way. I.e. continueWithBlock is not called at all. E.g.:

```
[[user getDetails] continueWithBlock:^id(AWSTask<AWSCognitoIdentityUserGetDetailsResponse*>* task)
    {
// THIS BLOCK IS NOT CALLED
        if (task.error)
        {
            // SO I CAN'T CATCH "No route to host" ERROR
        }
```

But I can see following log output:

```
[] nw_socket_connect connectx failed: [65] No route to host
[] nw_socket_connect connectx failed: [65] No route to host
[] nw_socket_connect connectx failed: [65] No route to host

AWSiOSSDK v2.5.1 [Error] AWSURLSessionManager.m line:212 | -[AWSURLSessionManager URLSession:task:didCompleteWithError:] | Session task failed with error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x17424ab30 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://cognito-idp.us-east-1.amazonaws.com/, NSErrorFailingURLKey=https://cognito-idp.us-east-1.amazonaws.com/, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}
```

NSURLSession methods return NSURLErrorTimedOut error in "No route to host" case. Why AWSURLSessionManager drops this error case?

**Comment by rohandubal** [comment]
Hi,

Thanks for reporting this. We will investigate and revert.

Thanks,
Rohan

**Comment by rohandubal** [comment]
Hello @igor-plygime 

Apologies for the delayed response.

I tried to reproduce this error on my side with the latest SDK version (`2.7.4`) and was unable to do so. I got the message propagated back to the client. 

Could you please confirm if this is still an issue for you?

Thanks,
Rohan
