### ISSUE TITLE
signRequestV4 does not provide x-amz-content-sha256

### ISSUE THREAD

**Issue by liuxuan30** [aws-amplify/aws-sdk-ios#716]
* What service are you using?
AWS S3 multi part upload.
* In what version of SDK are you facing the problem?
2.5.8
* Is the issue limited to Simulators / Actual Devices?
All are impacted
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Source code
#### Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

This issue is from https://github.com/minio/minio/issues/4731

It is a bug in iOS SDK when use multi part uploading, this AWS Signature V4 spec http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html says:
>The x-amz-content-sha256 header is required for all AWS Signature Version 4 requests. It provides a hash of the request payload. If there is no payload, you must provide the hash of an empty string.
However when uploading files with multi part uploading, the request
>canonical request:
POST
/bins/test.bin
uploadId=7ea51543-1918-4c34-86e3-3e322e721f4d

does not set x-amz-content-sha256.
In code
```objective-c
if ([hostArray firstObject] && [[hostArray firstObject] rangeOfString:@"s3"].location != NSNotFound) {
                //If it is a S3 Request
                authorization = [self signS3RequestV4:request
                                         credentials:credentials];
            } else {
                authorization = [self signRequestV4:request
                                       credentials:credentials];
            }
```
it is calling signRequestV4 instead of signS3RequestV4.
signRequestV4 does not add x-amz-content-sha256 header but signS3RequestV4 does.

**Comment by xuanliu-aa** [comment]
No one checks this?

**Comment by rohandubal** [comment]
Hi,

Thanks for reporting this. We will have a look into it.

Thanks,
Rohan

**Comment by liuxuan30** [comment]
I upload a test demo app for iOS (Xcode 8.3) https://pan.baidu.com/s/1hsGc0rM

**Comment by liuxuan30** [comment]
You just need to walk  through https://github.com/minio/minio/issues/4731, the details and work arounds, root cause is already done.

**Comment by brutasse** [comment]
@rohandubal hello

This happens on 3rd-party endpoints that implement the S3 protocol, but Amazon S3 is not impacted because all S3 endpoints contain the string "s3". Hence the issue with Minio and others…

[This check](https://github.com/aws/aws-sdk-ios/blob/3c855bdc540d55a7c6af8b08d69d8af251079db5/AWSCore/Authentication/AWSSignature.m#L155) is a bit fragile. Would there be a way for `AWSS3Service` to specify that its requests are S3 requests? E.g. set that information in the `AWSNetworkingRequest` object, and do the signing in `AWSURLSessionManager`?

Other AWS SDKs (boto3, go, cpp, php, etc) do not rely on the service uri to decide which singing method to choose. That information comes from higher in the stack.

**Comment by cbommas** [comment]
hello @brutasse 

I have added this request to the backlog for consideration and prioritization. Will reply back on this thread when we have an update.

**Comment by brutasse** [comment]
Thank you @cbommas

**Comment by cbommas** [comment]
@brutasse 

Can you check if https://github.com/aws-amplify/aws-sdk-ios/pull/1114 addresses your request? I am targeting to include this PR in the next rev of the SDK. I will respond back on this thread once I have confirmation.

**Comment by brutasse** [comment]
Thanks @cbommas, that looks good! :+1:

**Comment by cbommas** [comment]
@brutasse 
Version 2.7.4 of the sdk contains this change. I will go ahead and close out this issue.
Please feel to reopen this thread if you run into issues.
