### ISSUE TITLE
AWSPinpoint has no singleton? Am i missing something? 

### ISSUE THREAD

**Issue by rromanchuk** [aws-amplify/aws-sdk-ios#740]
How are we supposed to use this without a singleton? In all your examples you reference a local instance variable. Am i really responsible for passing this around if I need to use this after initialization? 

Competitors: 
`Analytics.logEvent()`
`FBSDKAppEvents.logEvent()`
`Answers.logCustomEvent()`
`Amplitude.instance()`

Do you guys have any production style use case examples? Please don't tell me you are just pulling an ivar from AppDelegate?

**Comment by bruun** [comment]
`AWSMobileClient.sharedInstance.pinpoint`

**Comment by rromanchuk** [comment]
beautiful, thank you!

**Comment by rromanchuk** [comment]
This really still bothers me. I have a bunch of crashes related to `AWSPinpoint`, so today i wanted to go back and make sure it's not a result of SDK drift. I still see this in the official pinpoint integration. For example, here is the integration for analytics. 

```swift
import AWSCore
import AWSPinpoint

     class AppDelegate: UIResponder, UIApplicationDelegate {

         var pinpoint: AWSPinpoint?

         func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions:
         [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

         //. . .

         // Initialize Pinpoint
         pinpoint = AWSPinpoint(configuration:
                 AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions))

         //. . .
         }
     }
```

Here's my beef with this: 
- I don't want to be holding an instance of this client in my app delegate
- It isn't clear (besides your own comment) that we are initializing the client, and it's required to happen in `didFinishLaunchingWithOptions`.  For the analytics instructions, no code follows that actually utilizes this instance. At this point, i'm assuming that the result of this call is not discardable. `  pinpoint = AWSPinpoint(configuration:
                 AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions))`
- The only reason i know what this is for is because i know you're going to use it for notification related delegates inside the app delegate, it's going to be easier to reference this instance than trying to fetch the client from the api. 

OK now for usage

```swift
let pinpointAnalyticsClient =
  		         AWSPinpoint(configuration:
  		             AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: nil)).analyticsClient

 let event = pinpointAnalyticsClient.createEvent(withEventType: "EventName")
  		     event.addAttribute("DemoAttributeValue1", forKey: "DemoAttribute1")
  		     event.addAttribute("DemoAttributeValue2", forKey: "DemoAttribute2")
  		     event.addMetric(NSNumber.init(value: arc4random() % 65535), forKey: "EventName")
  		     pinpointAnalyticsClient.record(event)
  		     pinpointAnalyticsClient.submitEvents()
```

- Ok now you're using the same initializer method to fetch the client. I guess that instance var in the app delegate is discardable. The signature is pretty confusing, now i'm passing `nil` for `launchOptions`
- Ugghh, i guess i have to alias `record()` and `submit()`

Feature requests: 
- Create a discardable alias to initialize the client to better communicate why and what we're doing. 
`AWSPinpoint.initialize()`
- Initialization *should* be an unrecoverable error. According to the doc https://aws-amplify.github.io/aws-sdk-ios/docs/reference/Classes/AWSPinpoint.html#//api/name/pinpointWithConfiguration:

According to the documentation: 

> The AWSPinpoint instance with the specified appId or nil if serviceConfiguration is invalid or appId is empty.

There is *never* a case i would want to continue program execution if initialization failed, nor do i want to be responsible for managing an optional. I could see why this is because of code smell though. Since this method could also be used in other contexts you can't be as defensive about it. At the very least, the example integration should validate the optional and set a forced unwrapped variable. This getting started guide basically allows a user to misconfigure the application and find out the hard way when another developer force unwraps the client to record an event (just like in your documentation) which is nil because the client failed to configure during app launch and the incident was completely swallowed.

- Give me access to the current client that doesn't require 134 characters, and that another developer can understand what's happening by reading the code

- Obfuscate how and when events are sent to aws,  `record()` and `submitEvents()` is pretty annoying, if you have to expose it, it should be advanced usage for a tiny number of use cases
- Make it clear how I should access the client from outside of the app delegate. Is it safe to use a long lived instance defined as a lazy var in my own singleton? I could see that being dangerous during certain lifecycle events

Look at all the code smells that happen in the official documentation for recording an event: 
https://docs.aws.amazon.com/pinpoint/latest/developerguide/integrate-events.html

```swift
let pinpointAnalyticsClient = pinpoint!.analyticsClient
let event = 
    pinpointAnalyticsClient.createEventWithEventType("_userauth.sign_in")

pinpointAnalyticsClient.recordEvent(event)
pinpointAnalyticsClient.submitEvents()
``` 

- An instance of the client magically appeared out of thin air. Which is probably a shortcut because of how annoying it is to use this API with swift 
- Force unwrapping of a library client to record an event. Lets pray someone actually checked that optional during initialization which simply returns nil

I understand this is an artifact of objective-c, and I can only imagine the difficulty in making everyone happy, but I think there is lots of room for improvement! 

Look how unmistakably clear a competitor is:
https://firebase.google.com/docs/analytics/ios/start

**Comment by rromanchuk** [comment]
- Also, it would be nice if you offered a swizzling option for notification setup :)

**Comment by drochetti** [comment]
@rromanchuk I'm sorry it's been so long since we last updated this. Your feedback is valuable and I wonder if you had the chance to look at [Amplify Analytics](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/ios).

Your feedback about the developer experience is super valid. We have been putting a lot of effort into DX in Amplify and I would love to get your feedback if you have a chance to try it.
