### ISSUE TITLE
ValidationException with query on global secondary index (DynamoDB)

### ISSUE THREAD

**Issue by darthpelo** [aws-amplify/aws-sdk-ios#75]
Hi, 
I have a problem with the query on a table with the Global Secondary Indexes. I did not find any example on how to perform a query on any of these indexes.

I'm using version 2.0.7 of the SDK and the configuration of my table is this:
- Primary Hash Key **suggestionId (String)**
- Global Secondary Indexes
  - Index Name **suggestedObjectId-index** with Hash Key **suggestedObjectId (String)**
  - Index Name **senderId-index** with Hash Key **senderId (String)**
  - Index Name **receiverId-index** with Hash Key **receiverId (String)**

I want to make a query on senderId-index, I want to find all the rows with a specific senderId.

I try this solution, without success:

``` objective-c
- (void)dynamoQuery:(SSAUser *)user resultBlock:(void (^)(NSMutableArray *result, NSError *error))resultBlock
{
    AWSDynamoDBObjectMapper *dynamoDBObjectMapper = [AWSDynamoDBObjectMapper defaultDynamoDBObjectMapper];

    AWSDynamoDBQueryExpression *queryExpression = [AWSDynamoDBQueryExpression new];

    queryExpression.hashKeyValues = user.userId;
    queryExpression.indexName = @"senderId-index";
    queryExpression.scanIndexForward = @YES;
    queryExpression.limit = @20;

    [[dynamoDBObjectMapper query:[SSASuggestion class] expression:queryExpression] continueWithBlock:^id(BFTask *task) {
        AWSDynamoDBPaginatedOutput *output = task.result;
        NSMutableArray *results = [NSMutableArray new];

        for (SSASuggestion *suggestion in output.items) {
            [results addObject:suggestion];
        }

        if (results.count > 0) {
            resultBlock(results, nil);
        } else {
            DDLogError(@"Error: [%@]", task.error);
            resultBlock(nil, task.error);
        }
        return nil;
    }];
}
```

I get the following error:

```
Error Domain=com.amazonaws.AWSDynamoDBErrorDomain 
Code=0 "The operation couldn’t be completed. 
(com.amazonaws.AWSDynamoDBErrorDomain error 0.)" 
UserInfo=0x7fb5fbdb5790 {
__type=com.amazon.coral.validate#ValidationException, message=Query condition missed key schema element senderId
}
```

Can anyone tell me what is the correct way to perform this query?

Thanks.

**Comment by vivekkodu** [comment]
Can anyone please provide an example to query using AWSDynamoDB on the secondary index
