### ISSUE TITLE
Cognito IdentityID isn't set with Developer Authenticated Identities

### ISSUE THREAD

**Issue by phdodo** [aws-amplify/aws-sdk-ios#85]
I'm trying to authenticate my users with a custom IdentityProvider following [this scaffold](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/cognito-auth.html#implement-an-identity-provider) but the AWSCredentialsProvider `refresh` or `getIdentityId` never return an `identityID`, as it seems the custom IdentityProvider never sets the identityId neither the token that is then used in the `AWSSTSAssumeRoleWithWebIdentityRequest`.

What should the IdentityProvider refresh method return? A BFTask `withResult:identityId`? 
Is it possible to have a working example of a custom IdentityProvider?

**Comment by donileo** [comment]
This example implies that the username and password be stored in the app leaving them open to being pulled out by malicious users. Doesn't seem right.

**Comment by turacma** [comment]
The above example is pseudo-code. Our full [end-to-end example](https://mobile.awsblog.com/post/Tx3E3NJURV1LNV1/Integrating-Amazon-Cognito-using-developer-authenticated-identities-An-end-to-en) does not store the password locally, only a key that represents the session.

**Comment by donileo** [comment]
@turacma ok thanks. If I am looking for help in understanding and properly implementing Developer Authenticated Provider with Cognito where should I go? The documentation posted I've seen isn't helping me fully understand.

**Comment by turacma** [comment]
@donileo Which documentation are you looking at? The blog post I linked to has a full end-to-end example of Developer Authenticated Identities (iOS/Android/Java backend), and the [developer guide](http://docs.aws.amazon.com/cognito/devguide/identity/developer-authenticated-identities/) has similar information. What further information are you looking for?

**Comment by donileo** [comment]
I have my server successfully retrieving an openID token and returning back to my iOS App. However I am confused about the refresh Function in the custom AWSAbstractCognitoIdentityProvider class. It seems to me that If I perform a login and set the openID Token and logins retrieved by my app this token will expire in 15 minutes (default). So after 15 minutes the AWSSDK will call the refresh function again on its own and perform another login - even if the user is already logged in. Having to perform subsequent logins seems weird to me through my app, so I'm guessing whats expected is that the server API call to getToken is supposed to pass the identity_id and (expired) token. Then the server will take this identity_id and token and validate it as previously being authenticated and then should generate a new one and pass it back to the app. Is this correct?

**Comment by turacma** [comment]
@donileo The refresh would only be called after the expiration of the AWS credentials fetched, which only expire after 1 hour. Additionally, you can control how long that open id token is valid for and include logic in your own refresh method to return the same token (if still valid).

As for refreshing the token after it has expired, relying on the expired token is not recommended as that would offer no mechanism for the user to log out. Again, I would urge you to take a look at our end-to-end sample. It solves this issue by creating a "session key" that is used to sign the requests to the backend and this key could be potentially invalidated by either the server or client.
