### ISSUE TITLE
Unable to successfully update endpoint.

### ISSUE THREAD

**Issue by sauravexodus** [aws-amplify/aws-sdk-ios#861]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Pinpoint, AWS Mobile Hub

* In what version of SDK are you facing the problem?
2.1.2

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
 No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

- Add `configuration.json` to your project.
- Follow steps to initialize analytics from [here](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-analytics.html)
- See the following output when you try to initialize the pinpoint instance:

```xclog
Unable to successfully update endpoint. Error Message:Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain Code=1 "BadRequestException" UserInfo={RequestID=a0145ff1-3320-11e8-b003-6b800874b928, responseStatusCode=400, responseHeaders=<CFBasicHash 0x1c686b780 [0x1b3344310]>{type = immutable dict, count = 12,
entries =>
	0 : Content-Type = <CFString 0x1c0a44ce0 [0x1b3344310]>{contents = "application/json"}
	1 : Access-Control-Allow-Origin = *
	2 : X-Amz-Cf-Id = <CFString 0x1c0486400 [0x1b3344310]>{contents = "JkzQckhTMh87hfT5hC9ygmDhbvwOsoAeLEbRfxdIuwt2hmOrW5Sd9g=="}
	3 : X-Amzn-Trace-Id = <CFString 0x1c0486590 [0x1b3344310]>{contents = "sampled=0;root=1-5abc9201-85f2b0894a37c36c06fea4c3"}
	4 : x-amzn-ErrorType = <CFString 0x1c0a59ec0 [0x1b3344310]>{contents = "BadRequestException"}
	5 : Via = <CFString 0x1c02b3c20 [0x1b3344310]>{contents = "1.1 415c421af891d7c3f4ade60aba542014.cloudfront.net (CloudFront)"}
	12 : x-amz-apigw-id = <CFString 0x1c0a59ef0 [0x1b3344310]>{contents = "EfvAMHoloAMFcmQ="}
	13 : Date = <CFString 0x1c0a59aa0 [0x1b3344310]>{contents = "Thu, 29 Mar 2018 07:13:05 GMT"}
	15 : Content-Length = 81
	17 : Connection = <CFString 0x1c0625400 [0x1b3344310]>{contents = "keep-alive"}
	19 : x-amzn-RequestId = <CFString 0x1c1060f80 [0x1b3344310]>{contents = "a0145ff1-3320-11e8-b003-6b800874b928"}
	22 : X-Cache = <CFString 0x1c0a4ab30 [0x1b3344310]>{contents = "Error from cloudfront"}
}
, Message=Missing Address, responseDataSize=81, NSLocalizedFailureReason=BadRequestException}
```

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Thank you @sauravexodus for reporting to us. Can you upgrade to 2.6.13 (latest as of 03/28) and see if that fixes the problem?

**Comment by Reetalibrarian** [comment]
I just update to sdk 2.6.14 and have the same problem.

**Comment by Reetalibrarian** [comment]
whatever, I randomly write value (such as iPhone vendor ID) 
```
[[_pinpoint.targetingClient currentEndpointProfile] setAddress:<whatever_string>];
```
and now it works, though I think SDK should generate it when there is no such parameter.

**Comment by sauravexodus** [comment]
Sometimes I also get this error:

```
Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain Code=3 "InternalServerErrorException" UserInfo={RequestID=83e149b2-3995-11e8-b56b-e7c665e4ce12, responseStatusCode=500, responseHeaders=<CFBasicHash 0x604000474180 [0x115af3bb0]>{type = immutable dict, count = 12,
entries =>
	0 : Content-Type = <CFString 0x60000024d8c0 [0x115af3bb0]>{contents = "application/json"}
	1 : Access-Control-Allow-Origin = *
	2 : X-Amz-Cf-Id = <CFString 0x600000485cd0 [0x115af3bb0]>{contents = "aI_qj-alXQbUcjrD-CEgfwgSqc8quYcPgb1KSJ1KXSnUDjmw0mQ7dg=="}
	3 : X-Amzn-Trace-Id = <CFString 0x600000287940 [0x115af3bb0]>{contents = "sampled=0;root=1-5ac76718-9c8d315ec983b185c70adaf8"}
	4 : x-amzn-ErrorType = <CFString 0x600000449060 [0x115af3bb0]>{contents = "InternalServerErrorException"}
	5 : Via = <CFString 0x6000002a2c40 [0x115af3bb0]>{contents = "1.1 5757ec60ff8752b8ec09882b6d876f42.cloudfront.net (CloudFront)"}
	12 : x-amz-apigw-id = <CFString 0x600000445250 [0x115af3bb0]>{contents = "E60LwFihIAMFsJQ="}
	13 : Date = <CFString 0x60000024d530 [0x115af3bb0]>{contents = "Fri, 06 Apr 2018 12:24:56 GMT"}
	15 : Content-Length = 87
	17 : Connection = <CFString 0x600000630560 [0x115af3bb0]>{contents = "keep-alive"}
	19 : x-amzn-RequestId = <CFString 0x60000086c880 [0x115af3bb0]>{contents = "83e149b2-3995-11e8-b56b-e7c665e4ce12"}
	22 : X-Cache = <CFString 0x60000084b430 [0x115af3bb0]>{contents = "Error from cloudfront"}
}
, Message=Internal server error, responseDataSize=87, NSLocalizedFailureReason=InternalServerErrorException }
```

**Comment by balaji2591** [comment]
Hi @sauravexodus ,
Can you upgrade the sdk to 2.6.16 and let us know whether you are still facing this issue

**Comment by fbarraganef** [comment]
My version is 2.9.3, and I'm facing the same issue.

**Comment by drwjf** [comment]
I found Pinpoint will report "Unable to successfully update endpoint" after "Push notification" is enabled.

If you delete the app, reinstall and does not enable  "Push notification", that Error Message will not show.

Log is attached here for referencing.

Hint is "Missing Address", which address is missed? 

2019-04-26 23:27:21:914 ***[18602:7019472] Unable to successfully update endpoint. Error Message:Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain Code=2 "BadRequestException" UserInfo={responseStatusCode=400, responseHeaders=<CFBasicHash 0x1c0668ac0 [0x1b42a3538]>{type = immutable dict, count = 12,
entries =>
	0 : Content-Type = <CFString 0x1c46451f0 [0x1b42a3538]>{contents = "application/json"}
	1 : Access-Control-Allow-Origin = *
	2 : X-Amz-Cf-Id = <CFString 0x1c429da60 [0x1b42a3538]>{contents = "YNcoIh2KbLSGl3DEiq_QMnpLWVth1dt97JTS1iYldCjRYKKiZABPfw=="}
	3 : X-Amzn-Trace-Id = <CFString 0x1c4e7c940 [0x1b42a3538]>{contents = "Root=1-5cc3f649-e26018c711b65ec94cab1ed7"}
	4 : x-amzn-ErrorType = <CFString 0x1c465cf80 [0x1b42a3538]>{contents = "BadRequestException"}
	5 : Via = <CFString 0x1c42b1fa0 [0x1b42a3538]>{contents = "1.1 d14f63d70315d420d3e3c9833f55afe1.cloudfront.net (CloudFront)"}
	12 : x-amz-apigw-id = <CFString 0x1c465c830 [0x1b42a3538]>{contents = "YyNriFGhIAMF6QA="}
	13 : Date = <CFString 0x1c465cd40 [0x1b42a3538]>{contents = "Sat, 27 Apr 2019 06:27:21 GMT"}
	15 : Content-Length = 29
	17 : Connection = <CFString 0x1c4821760 [0x1b42a3538]>{contents = "keep-alive"}
	19 : x-amzn-RequestId = <CFString 0x1c4e7c9c0 [0x1b42a3538]>{contents = "83a3a561-68b5-11e9-aaf7-6f173ab1ef78"}
	22 : X-Cache = <CFString 0x1c465cda0 [0x1b42a3538]>{contents = "Error from cloudfront"}
}
, Message=Missing Address, responseDataSize=29, NSLocalizedFailureReason=BadRequestException}

**Comment by drwjf** [comment]
After go through the following document,

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/mobile-hub-add-aws-mobile-push-notifications.html

insert
[pinPoint.notificationManager interceptDidRegisterForRemoteNotificationsWithDeviceToken:deviceToken];

[pinPoint.notificationManager interceptDidReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];

into AppDelegate,

this error message is gone.

**Comment by Foefirelord** [comment]
Same issue still. Pinpoint simply can't manage to send updates to the backend. It appears to accumulate them locally, try to send them, and fails with the "Missing Address" error.

I have Push Notifications disabled for Pinpoint, so it doesn't make sense to add the code that supports push notification handling via Pinpoint. I'm just trying to get it to send updates to the endpoint, and it's failing.

I followed the newest docs fully:
https://aws-amplify.github.io/docs/ios/analytics

But this error prevents the iOS client from dispatching the accumulated session updates to the backend.

**Comment by palpatim** [comment]
Since there was never an actual resolution on this issue, we're reopening it to get it on the backlog.

**Comment by Foefirelord** [comment]
Appears to be a device-only issue. Doesn't occur on simulators, but does occur on both iPhone and iPad.

Happens when the app is brought to foreground and attempts to update the endpoint. I was told by support that this isn't actually about dispatching events, like I thought. Updating the endpoint is a different operation.

The same error (Missing Address) also pops up when sending the app to background, but then it happens alongside event dispatching, which works successfully.

**Comment by Foefirelord** [comment]
Just read this part of the Pinpoint docs:
https://aws-amplify.github.io/docs/ios/analytics#assigning-user-ids-to-endpoints

It says that as long as you're using Cognito User Pools, you don't need to implement that code to set the endpoint based on the signed in user's ID manually, but the error seems to indicate that Pinpoint doesn't see an endpoint to use, or the Pinpoint library fails to set the endpoint in this way on its own.

Has this already been looked into?

**Comment by Foefirelord** [comment]
Turns out you HAVE to implement the Pinpoint SDK methods that intercept push notification registration and intercept the receiving of silent notification, in order for analytics to function properly without throwing errors.

This is absolutely asinine. The code to do this is in the document section called "Push Notifications" -- a section that no one will ever even open if all they want out of Pinpoint is the analytics functionality:
https://aws-amplify.github.io/docs/ios/push-notifications

Specifically, I had to implement `interceptDidRegisterForRemoteNotifications` and `interceptDidReceiveRemoteNotification` in order to allow Pinpoint to get the token received from APNS and make analytics work without throwing any errors, because the SDK apparently needs the push token to be able to send silent notifications to the app while performing its analytics functions -- a fact no one, neither premium support nor the people assigned to the tickets here, was able to clarify.

I ended up finding out about this purely by coincidence after inspecting the `pinpoint.targetingClient.currentEndpointProfile().address` property in Xcode, which has the following description:

> The address is the token returned from APNS to be used to send push notifications.

Once I saw that and dug through the SDK's Pinpoint targeting libraries, I was able to figure out that I was missing the push notification intercept methods, which are documented in a section entirely separate from the "Analytics" section -- a section no one would bother opening if all they want is analytics features.

I guess Pinpoint Analytics uses silent notifications for something or other. Would've been really nice to find this out sooner from support or the team members involved in resolving these tickets, but I'm starting to suspect that nobody currently working on this SDK actually knows how it works.

**Comment by drochetti** [comment]
Hi @Foefirelord,

First of all, thanks for providing such detailed report for this issue and your patience. I've been investigating it and created an app from scratch with Pinpoint configured in order to isolate the issue and reproduce it.

I was not able to repro the exact issue you described *yet*. When following the steps on [iOS Analytics](https://aws-amplify.github.io/docs/ios/analytics) I was able to initialize the Pinpoint Client, submit events and update the endpoint. I also enabled Push Notifications and tried different use cases for recording, submitting events and updating the endpoint, but no luck.

Are you able to share more details with me? Things I'm looking for:

- How are you initializing the Pinpoint client?
- How are you updating the endpoint (in case you are)?
- How often (and when) do you submit events(e.g. main thread, timer, interval, etc)?
- Can you enable a more verbose logging and report what happens right before and right after the error is triggered?
  ```swift
  AWSDDLog.sharedInstance.logLevel = .verbose
  AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
  ```

I'm sorry for your frustration, Push Notifications should not interfere with Analytics indeed, unless you require them. I'm looking into clarifying the issue.

I really appreciate your patience and help on this.

**Comment by Foefirelord** [comment]
@drochetti I'm afraid I don't have time right now to provide code or much more info on top of what I've already provided.

The short of it is that we implemented AWS Amplify authentication via AWSMobileClient and the code in the Analytics section for Pinpoint analytics, but that wasn't enough to allow all analytics features to function properly, as the SDK was throwing errors about being unable to update the endpoint.

The error message was "Missing Address", and I couldn't get a clear answer anywhere what that address was supposed to be, so I only found out the answer to that question after I arbitrarily checked the description of the `pinpoint.targetingClient.currentEndpointProfile().address` property and then looked at the Pinpoint library files to see how exactly analytics works, which led me to realize that Pinpoint **needs** to be able to send silent push notifications to the iOS app for some reason.

During my attempts to resolve this with AWS tech support prior to finding out all this, I was able to use just the code on the Analytics page without any errors in iOS simulators, but never on device. The Missing Address error (and thus the SDK's inability to use push notifications for whatever it is it uses them for) were present on both my iPhone and my co-founders iPad devices when testing, but went away once we implemented the above mentioned notification registration methods to allow the SDK to retrieve the APNS token when our app registers for push notifications with APNS.

**Comment by mharlowfod** [comment]
I also get this same error, just on device. Here's the verbose output:

```
Response headers:
{
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 29;
    "Content-Type" = "application/json";
    Date = "Mon, 21 Oct 2019 22:27:26 GMT";
    Via = "1.1 28b1b9930ccdd3e560b3f8d56677a679.cloudfront.net (CloudFront)";
    "X-Amz-Cf-Id" = "6o1oqgxm624Cj3b7IfE6-FNtISw3vwSAmaYz6UoyBcPyt7hQQPGd7Q==";
    "X-Amz-Cf-Pop" = JFK5;
    "X-Amzn-Trace-Id" = "Root=1-5dae30ce-5c0dacfc7d7211e015f70727";
    "X-Cache" = "Error from cloudfront";
    "x-amz-apigw-id" = "B7yQOFQqoAMF13w=";
    "x-amzn-ErrorType" = BadRequestException;
    "x-amzn-RequestId" = "70ad2ac4-25e6-4ded-ae20-3c9e71c4afaa";
}
2019-10-21 17:27:26:240 FOD[305:25565] Response body:
{"Message":"Missing Address"}
2019-10-21 17:27:26:242 FOD[305:25565] Unable to successfully update endpoint. Error Message:Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain Code=1 "BadRequestException" UserInfo={responseStatusCode=400, responseHeaders=<CFBasicHash 0x281746840 [0x22afc5610]>{type = immutable dict, count = 13,
entries =>
	0 : Content-Type = <CFString 0x2803cc660 [0x22afc5610]>{contents = "application/json"}
	1 : Access-Control-Allow-Origin = *
	2 : X-Amz-Cf-Id = <CFString 0x282e32d00 [0x22afc5610]>{contents = "6o1oqgxm624Cj3b7IfE6-FNtISw3vwSAmaYz6UoyBcPyt7hQQPGd7Q=="}
	3 : X-Amzn-Trace-Id = <CFString 0x28172f940 [0x22afc5610]>{contents = "Root=1-5dae30ce-5c0dacfc7d7211e015f70727"}
	4 : x-amzn-ErrorType = <CFString 0x2803cdfb0 [0x22afc5610]>{contents = "BadRequestException"}
	5 : Via = <CFString 0x28294de00 [0x22afc5610]>{contents = "1.1 28b1b9930ccdd3e560b3f8d56677a679.cloudfront.net (CloudFront)"}
	7 : X-Amz-Cf-Pop = JFK5
	12 : x-amz-apigw-id = <CFString 0x2803cdfe0 [0x22afc5610]>{contents = "B7yQOFQqoAMF13w="}
	13 : Date = <CFString 0x2803cf8d0 [0x22afc5610]>{contents = "Mon, 21 Oct 2019 22:27:26 GMT"}
	15 : Content-Length = 29
	17 : Connection = <CFString 0x280d299a0 [0x22afc5610]>{contents = "keep-alive"}
	19 : x-amzn-RequestId = <CFString 0x28172f8c0 [0x22afc5610]>{contents = "70ad2ac4-25e6-4ded-ae20-3c9e71c4afaa"}
	22 : X-Cache = <CFString 0x2803cfc00 [0x22afc5610]>{contents = "Error from cloudfront"}
}
, Message=Missing Address, responseDataSize=29, NSLocalizedFailureReason=BadRequestException}
```

My implementation is extremely rudimentary as we are just trying to see the "hello world" of what it will capture for our production field.

```
AWSMobileClient.default().initialize { [weak self] (state, error) in
            guard let strongSelf = self else { return }
            
            AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
            AWSDDLog.sharedInstance.logLevel = .verbose

             // Configure Pinpoint Analytics
            strongSelf.pinpoint = AWSPinpoint(configuration: AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: launchOptions))

            // Other AWS setup
}
```

**Comment by toka756** [comment]
Same problem occurred after I integrate aws-sdk to my app. 
What is the reason?

Unable to successfully update endpoint. Error Message:Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain Code=2 "BadRequestException" UserInfo={responseStatusCode=400, responseHeaders=<CFBasicHash 0x282eb87c0 [0x1f625d430]>{type = immutable dict, count = 13,

**Comment by joebernard** [comment]
This seems to be a wider issue as I'm also seeing this problem with the Amplify JS client.

**Comment by palpatim** [comment]
@joebernard Please do file an issue with the [Amplify JS](https://github.com/aws-amplify/amplify-js/issues) repo with details on your issue.
