### ISSUE TITLE
Duplicate Pinpoint events

### ISSUE THREAD

**Issue by YousefED** [aws-amplify/aws-sdk-ios#873]
We're using Pinpoint to record user events. Although we only call record event once, we see a lot of duplicate events ending up in S3 (our firehose copy of Pinpoint data). In extreme cases 100+ duplicates of the same event. Is this a known issue in the sdk?

### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

Pinpoint

* In what version of SDK are you facing the problem?

2.6.12

* Is the issue limited to Simulators / Actual Devices?

Actual Devices

* Can your problem be resolved if you bump to a higher version of SDK?

Will try, need to ship new production build

* Is this problem related to specific iOS version?

No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Pods

**Comment by mureatencio** [comment]
Did you find a solution?
