### ISSUE TITLE
Would you like to provide iOS SDK for cloudsearch? 

### ISSUE THREAD

**Issue by drwjf** [aws-amplify/aws-sdk-ios#874]
* What service are you using?

Cloudsearch

* In what version of SDK are you facing the problem?

No iOS SDK provide Cloudsearch interface. 

No sample code for signaturing to call Cloudsearch api.

* Is the issue limited to Simulators / Actual Devices?

N/A

* Can your problem be resolved if you bump to a higher version of SDK?

Hope so.

* Is this problem related to specific iOS version?

N/A

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

N/A

**Comment by minbi** [comment]
Hi @drwjf ,

We do not currently support Cloud Search. We will take this as a feature request.
