### ISSUE TITLE
Returning ENOTCONN because protocol has not yet been set up 

### ISSUE THREAD

**Issue by yiytan92** [aws-amplify/aws-sdk-ios#908]
I'm getting an error when attempting to upload an image onto my S3 bucket with AWSS3 Transfer Manager. This is the code I am using,

`    
    func uploadPhoto (){
        
        if profileImageView.image == nil {
            print("no photo selected")
            // Do something to wake up user :)
        } else {
            let image = profileImageView.image!
            let fileManager = FileManager.default
            let path = (NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0] as NSString).appendingPathComponent("test3.jpeg")
            let imageData = UIImageJPEGRepresentation(image, 0)
            fileManager.createFile(atPath: path as String, contents: imageData, attributes: nil)
            
            let fileUrl = NSURL(fileURLWithPath: path)
            let uploadRequest = AWSS3TransferManagerUploadRequest()
            uploadRequest?.bucket = "https://s3-ap-southeast-1.amazonaws.com/xxxxxxx"
            uploadRequest?.key = "godhelpme"
            uploadRequest?.contentType = "image/jpeg"
            uploadRequest?.body = fileUrl as URL!
            uploadRequest?.serverSideEncryption = AWSS3ServerSideEncryption.awsKms
            uploadRequest?.uploadProgress = { (bytesSent, totalBytesSent, totalBytesExpectedToSend) -> Void in
                DispatchQueue.main.async(execute: {
                                        print("totalBytesSent",totalBytesSent)
                                        print("totalBytesExpectedToSend",totalBytesExpectedToSend)
                    
                    //                    self.amountUploaded = totalBytesSent // To show the updating data status in label.
                    //                    self.fileSize = totalBytesExpectedToSend
                })
            }
            
            let transferManager = AWSS3TransferManager.default()
            transferManager.upload(uploadRequest!).continueWith(executor: AWSExecutor.mainThread(), block: { (task:AWSTask<AnyObject>) -> Any? in
                if task.error != nil {
                    // Error.
                    print("error")
                } else {
                    // Do something with your result.
                    print("No error Upload Done")
                }
                return nil
            })
        }
`
This is my awsconfiguration

`{
  "Version": "1.0",
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "us-east-1:5f81c74c-ccdb-430f-9b90-7b71330c635e",
        "Region": "us-east-1"
      }
    }
  },
  "IdentityManager": {
    "Default": {}
  },
    "S3TransferUtility": {
        "Default": {
            "Bucket": "https://s3-ap-southeast-1.amazonaws.com/xxxxxx/xxxxx/",
            "Region": "ap-southeast-1"
        }
    }
}`
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSS3 Transfer Manager

* In what version of SDK are you facing the problem?
Using AWSAuthCore (2.6.16)
Using AWSCognito (2.6.16)
Using AWSCore (2.6.16)
Using AWSMobileClient (2.6.16)
Using AWSS3 (2.6.16)

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
iOS 11

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Uploading an image data type to s3 bucket

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by yiytan92** [comment]
![screen shot 2018-04-27 at 12 06 48 pm](https://user-images.githubusercontent.com/26014963/39344209-97eadd30-4a13-11e8-9ff5-96644013fe21.png)

@kvasukib  Ok, i've changed uploadRequest?.bucket = "cubichat"


This is the complete error code i'm getting

**Comment by rohandubal** [comment]
Hello @yiytan92 

Could you use `TransferUtility` instead of `TransferManager`? We recently added support for multi-part upload as well and is preferred over TransferManager.

**Comment by cbommas** [comment]
@yiytan92 

Thank you for your patience as we are working through this issue. I will need you to make one more change to get more diagnostic information. A value of 2 for AWSS3TransferUtilityErrorDomain  indicates that a 4XX error was returned from the server for the request. The latest version of the SDK, 2.6.18, contains logic to propagate additional diagnostic information (thanks to PR https://github.com/aws/aws-sdk-ios/pull/666  submitted by @k4ety ). Can you upgrade to the latest and send me the details of the error? 

See below for a code snippet on how to get the error information

        let errorInfo = err.userInfo["Error"] as? [String: Any]
        if errorInfo != nil {
            print("Found error in response. Details are:")
            for element in errorInfo! {
                print(">> \(element.key): \(element.value)")
            }
       }

**Comment by cbommas** [comment]
@yiytan92 

Just checking back to see if you had a chance to try out the changes
