### ISSUE TITLE
Option to stop audio playback for 'audioInAudioOut' interaction mode.

### ISSUE THREAD

**Issue by yoterpa** [aws-amplify/aws-sdk-ios#909]
I could not find a way (other than implementing a custom `LexInteractionKit` class) to stop the playback of the audio response gotten from **Lex**. Am I missing something here? Is there a way to stop audio playback for `audioInAudioOut` interaction mode using the default `AWSLexInteractionKit` class in the SDK itself?

**Comment by royjit** [comment]
Closing this issue due to little activity, please reach us if you think this feature is important to you.
