### ISSUE TITLE
AWSAuthUIViewController sign-in in landscape orientation

### ISSUE THREAD

**Issue by JesusMartinAlonso** [aws-amplify/aws-sdk-ios#931]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSAuthUIViewController

* In what version of SDK are you facing the problem?
2.6.18
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Present AWSAuthUIViewController from a view controller that is in landscape orientation. The Sign in view is shown but the logo fills the whole screen and the view is not scrollable, so the user is not able to do login.

![screen shot 2018-05-17 at 9 43 56](https://user-images.githubusercontent.com/9574791/40163509-433caf3a-59b7-11e8-8093-231ec3344e2a.png)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by ruisebas** [comment]
This has been fixed in [2.28.1](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.28.1).
Closing.
