### ISSUE TITLE
AWSDynamoDB Framework Still Uses NSNumber

### ISSUE THREAD

**Issue by OBannon37** [aws-amplify/aws-sdk-ios#960]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS DynamoDB

* In what version of SDK are you facing the problem?
2.6.21

* Is the issue limited to Simulators / Actual Devices?
All Devices

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

When can we expect full native support for swift from the AWS DynamoDB SDK? Currently, the DynamoDB Object Mapper relies on NSNumbers, which makes conforming model classes to protocols like Codable (useful for caching) impossible.

This change has been suggested as far back as 2016 (#332 ), but is particularly salient now, as we shift further and further away from Obj-C.

**Comment by rohandubal** [comment]
Hi, the SDK currently uses Mantle internally to do the transformation and it would be a very big change (and probably breaking) to support the native types. But I definitely see your point in supporting native types for conforming to Codable. I will take this as feature request to the team. 

Thanks,
Rohan

**Comment by ukhan-amazon** [comment]
Closing due to new alpha [Swift SDK release](https://github.com/awslabs/aws-sdk-swift).
