### ISSUE TITLE
On sign-up/login UI "tab" on keyboard moves input but UI does not respond

### ISSUE THREAD

**Issue by 24601** [aws-amplify/aws-sdk-ios#984]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
MobileHub Cognito Sign-In
* In what version of SDK are you facing the problem?
2.6.23
* Is the issue limited to Simulators / Actual Devices?
Both
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Create a new app, try to sign in with a new user using a hardware keyboard (iPad Pro with Smart Keyboard for example). Try pressing TAB to move between User Name, PW, Email, Phone fields, when you tab the UI doesn't follow you although the data you are entering is invisibly being entered into that field, touching on the field will then cause the UI to update, with everything you've already typed there. This is really annoying and problematic because you think tab doesn't work but it does, and then you tap, and begin retyping, only to see it was listening the whole time but not giving you the feedback in the UI! 

See video:

https://www.dropbox.com/s/5jxepfap8g06vsw/ScreenRecording_07-07-2018%2010-44-51.m4v?dl=0

**Comment by minbi** [comment]
Thanks for reporting this issue. We will investigate and follow up here

**Comment by EthanLozano** [comment]
I noticed the same. This is what appears in the "Debug View Hierarchy" when focusing on just the password field:
![screen shot 2018-07-12 at 2 41 58 pm](https://user-images.githubusercontent.com/1757759/42655663-64d3ac00-85e2-11e8-81c7-f34479f1daac.png)
So, there is a UIView covering the UITextField that only seems to disappear when the top view is touched. The source is [here](https://github.com/aws/aws-sdk-ios/blob/2.6.23/AWSAuthSDK/Sources/AWSAuthUI/SignIn.storyboard#L121).

I ran into this issue when trying to write a UI test. I have to write the code below to enter text into these fields. Also, it would be nice if these fields included an accessibility identifier to simplify testing.

    private func selectUsername() -> XCUIElement {
        let name = "User Name"
        let tablesQuery = app.tables
        tablesQuery.staticTexts[name].tap()
        return tablesQuery.cells.containing(.staticText, identifier: name).children(matching: .textField).element
    }

    private func selectPassword() -> XCUIElement {
        let tablesQuery = app.tables
        tablesQuery.staticTexts["Password"].tap()
        return tablesQuery.secureTextFields.containing(.button, identifier:"Show").element
    }

**Comment by 24601** [comment]
I'm afraid the bot is going to close this without resolution, it's already labled wontfix, can we get a rulin on if this will be fixed?

**Comment by rohandubal** [comment]
Hello,

This issue is resolved in `2.7.4` SDK release. Please let us know if you continue to face issues.

Thanks,
Rohan
